import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient, DatabaseTransaction } from "../database.js";
import { ApplicationError } from "../shared/application-error.js";

const CARROT_CODE="ITEM-RWD-044",THERMOMETER_CODE="pet_skill_carrot_thermometer";
const CARROT_FEE=20n,THERMOMETER_REWARD=2n,UINT64_MAX=18446744073709551615n;
export interface MiniPetCarrotTradeCommand{targetName:string;sourceIndex:bigint}
export interface MiniPetCarrotTradeResult{status:"traded"|"rejected"|"usage"|"silent";data?:string;outboxId?:string;senderPlayerId?:string;recipientPlayerId?:string;ownedMiniPetId?:string;sourceIndex?:string;recipientIndex?:string;carrotFee?:string;thermometerReward?:string}
interface Player{identity_id?:bigint;player_id:bigint;display_name:string;tier_code:string|null;rank_emoji:string|null}
interface Pet{pet_id:bigint;version:bigint;bag_sequence:bigint|null;display_name:string;emoji_value:string|null;reserved:bigint;protected_ref:bigint;pending_equip:bigint}
interface Stack{quantity:bigint;version:bigint}

// 레거시 outer guard처럼 정확 명령 또는 공백 인자형만 후보로 분류합니다.
export function isMiniPetCarrotTradeCandidate(message:string|undefined):boolean{return message!==undefined&&(message==="/미니펫당근"||/^\/미니펫당근\s+.+$/.test(message))}
// 공백 포함 수신자명과 마지막 양의 uint64 가방번호를 완전 패턴으로 해석합니다.
export function parseMiniPetCarrotTradeCommand(message:string):MiniPetCarrotTradeCommand|null{const match=/^\/미니펫당근\s+(\S(?:.*\S)?)\s+([1-9]\d*)$/.exec(message);if(match===null)return null;const sourceIndex=BigInt(match[2]!);return sourceIndex>UINT64_MAX?null:{targetName:match[1]!.trim(),sourceIndex}}
// 인자형 명령을 DB 대표 alias로 정규화합니다.
export function normalizeMiniPetCarrotTradeDispatchMessage(message:string):string{return isMiniPetCarrotTradeCandidate(message)?"/미니펫당근":message}
function key(value:string):string{return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`}
function stored(value:string|MiniPetCarrotTradeResult):MiniPetCarrotTradeResult{return typeof value==="string"?JSON.parse(value) as MiniPetCarrotTradeResult:value}
function retryable(error:unknown):boolean{const code=typeof error==="object"&&error!==null&&"code" in error?String((error as{code?:unknown}).code??""):"";return code==="ER_CHECKREAD"||code==="ER_LOCK_DEADLOCK"||code==="ER_LOCK_WAIT_TIMEOUT"}
async function withRetry<T>(database:DatabaseClient,work:(transaction:DatabaseTransaction)=>Promise<T>):Promise<T>{let last:unknown;for(let attempt=0;attempt<3;attempt+=1){try{return await database.withTransaction(work)}catch(error){last=error;if(!retryable(error)||attempt===2)throw error}}throw last}

// 한 transaction에서 응답·execution·감사·operation 결과를 완료합니다.
async function complete(t:DatabaseTransaction,input:{operationId:bigint;eventId:string;destinationId:string;identityId:bigint;targetId:bigint|null;resultCode:string;actionCode:string;data:string;result:MiniPetCarrotTradeResult;summary:Record<string,unknown>}):Promise<MiniPetCarrotTradeResult>{
  const outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.operationId,input.destinationId,JSON.stringify({data:input.data})]);
  await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'MINI_PET_CARROT_TRADE',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,input.operationId,input.resultCode]);
  await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'player',?,?,?,'Iris /미니펫당근',?,UTC_TIMESTAMP(3))",[input.operationId,input.identityId,input.targetId,input.actionCode,input.resultCode,JSON.stringify(input.summary)]);
  const result={...input.result,data:input.data,outboxId:outbox.insertId.toString()};await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),input.operationId]);return result;
}

// 킹 이상 회원 사이의 stable 미니펫 소유권과 당근·온도기를 원자 이전합니다.
export class MiniPetCarrotTradeService{
  constructor(private readonly database:DatabaseClient){}
  async handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<MiniPetCarrotTradeResult>{
    if(!isMiniPetCarrotTradeCandidate(input.message))return{status:"silent"};
    return withRetry(this.database,async t=>{
      const sender=(await t.query<Player[]>(`SELECT identity.id identity_id,identity.player_id,profile.current_display_name display_name,profile.tier_code,legacy.rank_emoji
        FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' AND player.deleted_at IS NULL
        JOIN player_profiles profile ON profile.player_id=player.id LEFT JOIN player_legacy_rank_profiles legacy ON legacy.player_id=player.id
        WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE`,[input.externalUserId]))[0];
      if(sender?.identity_id===undefined)return{status:"silent"};
      const operationWrite=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'mini_pet.carrot.trade',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)",[randomUUID(),key(input.eventId),sender.identity_id]);
      const prior=(await t.query<Array<{result_json:string|MiniPetCarrotTradeResult|null}>>("SELECT result_json FROM operations WHERE id=? FOR UPDATE",[operationWrite.insertId]))[0];if(prior===undefined)throw new Error("MINI_PET_CARROT_OPERATION_REQUIRED");if(prior.result_json!==null)return stored(prior.result_json);
      const command=parseMiniPetCarrotTradeCommand(input.message);
      if(command===null)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:null,resultCode:"usage",actionCode:"mini_pet.carrot_trade.reject",data:"❌ 사용법: /미니펫당근 [받는닉네임] [미니펫가방번호]",result:{status:"usage"},summary:{mutation:false}});
      const targets=await t.query<Player[]>(`SELECT player.id player_id,profile.current_display_name display_name,profile.tier_code,legacy.rank_emoji
        FROM player_profiles profile JOIN players player ON player.id=profile.player_id AND player.status='active' AND player.deleted_at IS NULL
        LEFT JOIN player_legacy_rank_profiles legacy ON legacy.player_id=player.id WHERE profile.current_display_name=? ORDER BY player.id LIMIT 2 FOR UPDATE`,[command.targetName]);
      if(targets.length!==1)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:null,resultCode:targets.length>1?"ambiguous_target":"target_not_found",actionCode:"mini_pet.carrot_trade.reject",data:targets.length>1?"동일한 대상명이 여러 명입니다.":`❌ 받는 유저 [${command.targetName}]가 존재하지 않습니다.`,result:{status:"rejected"},summary:{mutation:false,targetName:command.targetName}});
      const recipient=targets[0]!;
      if(recipient.player_id===sender.player_id)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"self_trade",actionCode:"mini_pet.carrot_trade.reject",data:"❌ 자기 자신에게는 보낼 수 없습니다.",result:{status:"rejected"},summary:{mutation:false}});
      if(!(await this.eligible(t,sender.tier_code)))return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"sender_tier_required",actionCode:"mini_pet.carrot_trade.reject",data:`❌[${sender.rank_emoji??""}${sender.display_name}]님, 미니펫 거래는 티어 👑킹 이상부터 가능합니다.`,result:{status:"rejected"},summary:{mutation:false,tierCode:sender.tier_code}});
      if(!(await this.eligible(t,recipient.tier_code)))return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"target_tier_required",actionCode:"mini_pet.carrot_trade.reject",data:`❌[${recipient.rank_emoji??""}${recipient.display_name}]님은 티어 👑킹 미만이라 미니펫을 받을 수 없습니다.`,result:{status:"rejected"},summary:{mutation:false,targetTierCode:recipient.tier_code}});
      const senderPets=await this.bag(t,sender.player_id),recipientPets=await this.bag(t,recipient.player_id),selected=command.sourceIndex>BigInt(senderPets.length)?undefined:senderPets[Number(command.sourceIndex-1n)];
      if(selected===undefined)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"pet_not_found",actionCode:"mini_pet.carrot_trade.reject",data:"❌ 유효하지 않은 미니펫 가방번호입니다.",result:{status:"rejected"},summary:{mutation:false,sourceIndex:command.sourceIndex.toString()}});
      if(selected.reserved>0n||selected.protected_ref>0n||selected.pending_equip>0n)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"pet_protected",actionCode:"mini_pet.carrot_trade.reject",data:"❌ 거래 예약·보호·장착 대기 중인 미니펫은 보낼 수 없습니다.",result:{status:"rejected"},summary:{mutation:false,ownedMiniPetId:selected.pet_id.toString()}});
      const limit=(await t.query<Array<{limit_value:bigint}>>("SELECT COALESCE((SELECT keep_count FROM mini_pet_inventory_limits WHERE player_id=?),100) limit_value",[recipient.player_id]))[0]?.limit_value??100n;
      if(BigInt(recipientPets.length)>=limit)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"target_bag_full",actionCode:"mini_pet.carrot_trade.reject",data:`❌ [${recipient.display_name}]님의 미니펫 가방이 가득 찼습니다.`,result:{status:"rejected"},summary:{mutation:false,targetBagCount:recipientPets.length,limit:limit.toString()}});
      const items=await t.query<Array<{id:bigint;code:string}>>("SELECT id,code FROM item_definitions WHERE code IN (?,?) AND active=TRUE AND stackable=TRUE ORDER BY id",[CARROT_CODE,THERMOMETER_CODE]),carrotItem=items.find(x=>x.code===CARROT_CODE),thermometerItem=items.find(x=>x.code===THERMOMETER_CODE);
      if(carrotItem===undefined||thermometerItem===undefined)throw new ApplicationError("MINI_PET_CARROT_ITEMS_REQUIRED","미니펫 당근거래 아이템 설정을 찾을 수 없습니다.",409);
      const carrot=(await t.query<Stack[]>("SELECT quantity,version FROM inventory_stacks WHERE player_id=? AND item_id=? FOR UPDATE",[sender.player_id,carrotItem.id]))[0],thermometer=(await t.query<Stack[]>("SELECT quantity,version FROM inventory_stacks WHERE player_id=? AND item_id=? FOR UPDATE",[recipient.player_id,thermometerItem.id]))[0];
      if(carrot===undefined||carrot.quantity<CARROT_FEE)return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"insufficient_carrot",actionCode:"mini_pet.carrot_trade.reject",data:"❌ 🥕당근이세요? 아이템 20개가 필요합니다.",result:{status:"rejected"},summary:{mutation:false,requiredCarrot:"20"}});
      for(let i=0;i<recipientPets.length;i+=1){const pet=recipientPets[i]!,sequence=BigInt(i+1);if(pet.bag_sequence!==sequence){const changed=await t.execute("UPDATE owned_mini_pets SET bag_sequence=?,version=version+1 WHERE id=? AND player_id=? AND version=?",[sequence,pet.pet_id,recipient.player_id,pet.version]);if(changed.affectedRows!==1n)throw new ApplicationError("MINI_PET_CARROT_CONFLICT","상대 미니펫 가방이 먼저 변경되었습니다.",409)}}
      const recipientIndex=BigInt(recipientPets.length+1),transferred=await t.execute("UPDATE owned_mini_pets SET player_id=?,bag_sequence=?,version=version+1 WHERE id=? AND player_id=? AND equipped=FALSE AND version=?",[recipient.player_id,recipientIndex,selected.pet_id,sender.player_id,selected.version]);if(transferred.affectedRows!==1n)throw new ApplicationError("MINI_PET_CARROT_CONFLICT","미니펫 가방이 먼저 변경되었습니다.",409);
      let senderSequence=1n;for(const pet of senderPets){if(pet.pet_id===selected.pet_id)continue;if(pet.bag_sequence!==senderSequence){const changed=await t.execute("UPDATE owned_mini_pets SET bag_sequence=?,version=version+1 WHERE id=? AND player_id=? AND version=?",[senderSequence,pet.pet_id,sender.player_id,pet.version]);if(changed.affectedRows!==1n)throw new ApplicationError("MINI_PET_CARROT_CONFLICT","미니펫 가방 순서가 먼저 변경되었습니다.",409)}senderSequence+=1n}
      if((await t.execute("UPDATE inventory_stacks SET quantity=quantity-?,version=version+1 WHERE player_id=? AND item_id=? AND quantity>=? AND version=?",[CARROT_FEE,sender.player_id,carrotItem.id,CARROT_FEE,carrot.version])).affectedRows!==1n)throw new ApplicationError("MINI_PET_CARROT_CONFLICT","당근 보유량이 먼저 변경되었습니다.",409);
      if(thermometer===undefined)await t.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,?,?,1)",[recipient.player_id,thermometerItem.id,THERMOMETER_REWARD]);else if((await t.execute("UPDATE inventory_stacks SET quantity=quantity+?,version=version+1 WHERE player_id=? AND item_id=? AND version=?",[THERMOMETER_REWARD,recipient.player_id,thermometerItem.id,thermometer.version])).affectedRows!==1n)throw new ApplicationError("MINI_PET_CARROT_CONFLICT","당근온도기가 먼저 변경되었습니다.",409);
      await t.execute("INSERT INTO player_counters(player_id,counter_code,period_key,value,updated_at) VALUES (?,'carrot_given','lifetime',1,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE value=value+1,updated_at=UTC_TIMESTAMP(3)",[sender.player_id]);
      await t.execute("INSERT INTO player_counters(player_id,counter_code,period_key,value,updated_at) VALUES (?,'thermo','lifetime',?,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE value=value+VALUES(value),updated_at=UTC_TIMESTAMP(3)",[recipient.player_id,THERMOMETER_REWARD]);
      await t.execute("INSERT INTO inventory_ledger(operation_id,sequence_no,player_id,item_id,quantity_delta,reason_code) VALUES (?,1,?,?,?,'mini_pet_carrot_fee'),(?,2,?,?,?,'mini_pet_carrot_thermometer_reward')",[operationWrite.insertId,sender.player_id,carrotItem.id,-CARROT_FEE,operationWrite.insertId,recipient.player_id,thermometerItem.id,THERMOMETER_REWARD]);
      await t.execute("INSERT INTO mini_pet_carrot_trades(operation_id,sender_player_id,recipient_player_id,owned_mini_pet_id,source_bag_sequence,recipient_bag_sequence,carrot_item_id,carrot_fee,thermometer_item_id,thermometer_reward,pet_version_before,pet_version_after) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",[operationWrite.insertId,sender.player_id,recipient.player_id,selected.pet_id,command.sourceIndex,recipientIndex,carrotItem.id,CARROT_FEE,thermometerItem.id,THERMOMETER_REWARD,selected.version,selected.version+1n]);
      const remain=carrot.quantity-CARROT_FEE,data=`🐹 미니펫 당근거래 완료!\n\n[${sender.rank_emoji??""}${sender.display_name}] 님 → [${recipient.rank_emoji??""}${recipient.display_name}] 님에게\n📦 [${selected.display_name}${selected.emoji_value??""}] 미니펫을 보냈습니다.\n\n- 🥕당근이세요? 20개 차감 (보유: ${remain}개)\n- 🌡️당근온도기 2개 지급`;
      return complete(t,{operationId:operationWrite.insertId,eventId:input.eventId,destinationId:input.destinationId,identityId:sender.identity_id,targetId:recipient.player_id,resultCode:"traded",actionCode:"mini_pet.carrot.trade",data,result:{status:"traded",senderPlayerId:sender.player_id.toString(),recipientPlayerId:recipient.player_id.toString(),ownedMiniPetId:selected.pet_id.toString(),sourceIndex:command.sourceIndex.toString(),recipientIndex:recipientIndex.toString(),carrotFee:CARROT_FEE.toString(),thermometerReward:THERMOMETER_REWARD.toString()},summary:{ownedMiniPetId:selected.pet_id.toString(),sourceIndex:command.sourceIndex.toString(),recipientIndex:recipientIndex.toString(),carrotFee:"20",thermometerReward:"2"}});
    })
  }
  // 공용 킹 이상 거래 tier 정책을 확인합니다.
  private async eligible(t:DatabaseTransaction,tierCode:string|null):Promise<boolean>{const rows=await t.query<Array<{allowed:bigint}>>("SELECT COUNT(*) allowed FROM market_registration_tier_policies WHERE tier_code=? AND can_register=TRUE",[tierCode]);return(rows[0]?.allowed??0n)>0n}
  // stable owned ID와 보호 참조를 포함한 미니펫 가방을 잠급니다.
  private bag(t:DatabaseTransaction,playerId:bigint):Promise<Pet[]>{return t.query<Pet[]>(`SELECT pet.id pet_id,pet.version,pet.bag_sequence,definition.display_name,definition.emoji_value,
    EXISTS(SELECT 1 FROM market_mini_pet_reservations reservation WHERE reservation.owned_mini_pet_id=pet.id) reserved,
    EXISTS(SELECT 1 FROM mini_pet_protected_refs protected WHERE protected.owned_mini_pet_id=pet.id AND protected.active=TRUE) protected_ref,
    EXISTS(SELECT 1 FROM mini_pet_equip_confirmations confirmation WHERE confirmation.consumed_at IS NULL AND confirmation.cancelled_at IS NULL AND confirmation.expires_at>=UTC_TIMESTAMP(3) AND (confirmation.selected_owned_mini_pet_id=pet.id OR confirmation.previous_owned_mini_pet_id=pet.id)) pending_equip
    FROM owned_mini_pets pet JOIN mini_pet_definitions definition ON definition.id=pet.mini_pet_definition_id
    WHERE pet.player_id=? AND pet.equipped=FALSE ORDER BY COALESCE(pet.bag_sequence,pet.id),pet.id FOR UPDATE`,[playerId])}
}
