import { createHash,randomUUID } from "node:crypto";
import type { DatabaseClient,DatabaseTransaction } from "../database.js";

type Numeric=bigint|number|string;
type Stored=string|MiniPetEliteCombineResult;
interface OwnerRow{identity_id:Numeric;player_id:Numeric;display_name:string;}
interface RecipeRow{id:Numeric;recipe_version:number;point_cost:Numeric;success_rate:string;material_grade_name:string;material_min_enhancement:Numeric;excluded_material_name:string;}
interface OwnedRow{id:Numeric;definition_id:Numeric;display_name:string;grade_display_name:string|null;enhancement_level:Numeric;bag_sequence:Numeric|null;version:Numeric;reserved:number;protected_ref:number;pending_equip:number;}
interface RewardRow{pool_sequence:number;definition_id:Numeric;display_name:string;emoji_value:string|null;sale_price:Numeric;battle_experience:Numeric;castle_experience:Numeric;raid_experience:Numeric;}

const COMMAND_CODE="MINI_PET_ELITE_COMBINE",BASE_COMMAND="/미니펫조합엘리트";
export interface MiniPetEliteCombineCommand{firstIndex:bigint;secondIndex:bigint;}
export interface MiniPetEliteCombineResult{status:"success"|"failed"|"usage"|"rejected"|"silent";playerId?:string;firstOwnedMiniPetId?:string;secondOwnedMiniPetId?:string;createdOwnedMiniPetId?:string;rewardDefinitionId?:string;rewardName?:string;pointCost?:string;pointBalanceAfter?:string;successRoll?:number;rewardRoll?:number;data?:string;outboxId?:string;auditId?:string;replayed?:boolean;}

// 레거시 outer guard와 같은 명령 토큰 경계만 엘리트 조합 후보로 허용합니다.
export function isMiniPetEliteCombineCandidate(message:string|undefined):boolean{return message!==undefined&&(message===BASE_COMMAND||message.startsWith(BASE_COMMAND+" "));}

// 서로 다른 두 양수 uint64 가방번호만 실행 인자로 해석합니다.
export function parseMiniPetEliteCombineCommand(message:string):MiniPetEliteCombineCommand|null{const match=/^\/미니펫조합엘리트\s+([1-9]\d*)\s+([1-9]\d*)$/.exec(message);if(match===null)return null;const firstIndex=BigInt(match[1]!),secondIndex=BigInt(match[2]!),max=(1n<<64n)-1n;if(firstIndex>max||secondIndex>max||firstIndex===secondIndex)return null;return{firstIndex,secondIndex};}

// 파라미터 명령을 공용 레지스트리 대표 별칭으로 정규화합니다.
export function normalizeMiniPetEliteCombineDispatchMessage(message:string):string{return isMiniPetEliteCombineCandidate(message)?BASE_COMMAND:message;}

// 레시피 성공률과 보상 풀 순서를 고정된 두 RNG 표본으로 결정합니다.
export function resolveMiniPetEliteCombineRoll(input:{successRate:number;rewardCount:number;random:()=>number}){const clamp=(value:number)=>Math.max(0,Math.min(0.9999999999999999,value)),successRoll=clamp(input.random()),success=successRoll<input.successRate;if(!success)return{successRoll,success,rewardRoll:null,rewardIndex:null};const rewardRoll=clamp(input.random());return{successRoll,success,rewardRoll,rewardIndex:Math.floor(rewardRoll*input.rewardCount)};}

function integer(value:Numeric):bigint{return BigInt(String(value).split(".")[0]??"0");}
function stored(value:Stored):MiniPetEliteCombineResult{return typeof value==="string"?JSON.parse(value) as MiniPetEliteCombineResult:value;}
function key(value:string):string{return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;}
function fixed(value:number):string{return value.toFixed(17);}
function commas(value:bigint):string{return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
function retryable(error:unknown):boolean{if(typeof error!=="object"||error===null)return false;const value=error as{code?:unknown;errno?:unknown};return value.code==="ER_CHECKREAD"||value.code==="ER_LOCK_DEADLOCK"||value.errno===1020||value.errno===1213;}

async function complete(t:DatabaseTransaction,input:{operationId:bigint;eventId:string;destinationId:string;owner:OwnerRow;firstId:bigint|null;secondId:bigint|null;resultCode:string;data:string;result:MiniPetEliteCombineResult;summary:Record<string,unknown>}):Promise<MiniPetEliteCombineResult>{
  const outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.operationId,input.destinationId,JSON.stringify({data:input.data})]);
  await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,?,?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,COMMAND_CODE,input.operationId,input.resultCode]);
  const audit=await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'player',?,'mini_pet.elite.combine',?,'Iris /미니펫조합엘리트',?,UTC_TIMESTAMP(3))",[input.operationId,input.owner.identity_id,input.owner.player_id,input.resultCode,JSON.stringify(input.summary)]);
  const result={...input.result,playerId:String(input.owner.player_id),firstOwnedMiniPetId:input.firstId?.toString(),secondOwnedMiniPetId:input.secondId?.toString(),data:input.data,outboxId:outbox.insertId.toString(),auditId:audit.insertId.toString(),replayed:false};
  await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),input.operationId]);return result;
}

// 350억 선차감·10% 성공·성공 시 재료 소비와 엘리트 보상 지급을 한 transaction으로 처리합니다.
export class MiniPetEliteCombineService{
  constructor(private readonly database:DatabaseClient,private readonly random:()=>number=Math.random){}
  async handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<MiniPetEliteCombineResult>{if(!isMiniPetEliteCombineCandidate(input.message))return{status:"silent"};for(let attempt=0;attempt<3;attempt++){try{return await this.handleOnce(input);}catch(error){if(attempt===2||!retryable(error))throw error;}}throw new Error("MINI_PET_ELITE_COMBINE_RETRY_EXHAUSTED");}
  private handleOnce(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<MiniPetEliteCombineResult>{return this.database.withTransaction(async t=>{
    const owner=(await t.query<OwnerRow[]>("SELECT identity.id identity_id,identity.player_id,profile.current_display_name display_name FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' JOIN player_profiles profile ON profile.player_id=player.id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' AND identity.player_id IS NOT NULL FOR UPDATE",[input.externalUserId]))[0];if(owner===undefined)return{status:"silent"};
    const scope=`mini-pet.elite.combine:${owner.identity_id}`;await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,?,?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)",[randomUUID(),scope,key(input.eventId),owner.identity_id]);
    const operation=(await t.query<Array<{id:Numeric;result_json:Stored|null}>>("SELECT id,result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,key(input.eventId)]))[0];if(operation===undefined)throw new Error("MINI_PET_ELITE_COMBINE_OPERATION_REQUIRED");if(operation.result_json!==null)return{...stored(operation.result_json),replayed:true};const operationId=integer(operation.id);
    const command=parseMiniPetEliteCombineCommand(input.message);if(command===null)return complete(t,{operationId,eventId:input.eventId,destinationId:input.destinationId,owner,firstId:null,secondId:null,resultCode:"usage",data:"사용 방법: /미니펫조합엘리트 [미니펫가방번호] [미니펫가방번호]",result:{status:"usage"},summary:{mutation:false,reason:"invalid_command"}});
    const recipe=(await t.query<RecipeRow[]>("SELECT id,recipe_version,point_cost,success_rate,material_grade_name,material_min_enhancement,excluded_material_name FROM mini_pet_elite_combine_recipes WHERE recipe_code='ELITE-COMBINE' AND active=TRUE ORDER BY recipe_version DESC LIMIT 1 FOR UPDATE"))[0];if(recipe===undefined)throw new Error("MINI_PET_ELITE_COMBINE_RECIPE_REQUIRED");
    const account=(await t.query<Array<{balance:Numeric;version:Numeric}>>("SELECT balance,version FROM currency_accounts WHERE player_id=? AND currency_code='point' FOR UPDATE",[owner.player_id]))[0];if(account===undefined)throw new Error("MINI_PET_ELITE_COMBINE_POINT_ACCOUNT_REQUIRED");
    const pets=await t.query<OwnedRow[]>(`SELECT pet.id,pet.mini_pet_definition_id definition_id,definition.display_name,definition.grade_display_name,pet.enhancement_level,pet.bag_sequence,pet.version,EXISTS(SELECT 1 FROM market_mini_pet_reservations reservation WHERE reservation.owned_mini_pet_id=pet.id) reserved,EXISTS(SELECT 1 FROM mini_pet_protected_refs protected_ref WHERE protected_ref.owned_mini_pet_id=pet.id) protected_ref,EXISTS(SELECT 1 FROM mini_pet_equip_confirmations confirmation WHERE confirmation.selected_owned_mini_pet_id=pet.id AND confirmation.consumed_at IS NULL AND confirmation.cancelled_at IS NULL AND confirmation.expires_at>UTC_TIMESTAMP(3)) pending_equip FROM owned_mini_pets pet JOIN mini_pet_definitions definition ON definition.id=pet.mini_pet_definition_id WHERE pet.player_id=? AND pet.equipped=FALSE ORDER BY COALESCE(pet.bag_sequence,pet.id),pet.id FOR UPDATE`,[owner.player_id]);
    const first=pets[Number(command.firstIndex-1n)],second=pets[Number(command.secondIndex-1n)],cost=integer(recipe.point_cost),balanceBefore=integer(account.balance);
    const invalid=first===undefined||second===undefined||first.id===second.id||[first,second].some(pet=>pet.grade_display_name!==recipe.material_grade_name||integer(pet.enhancement_level)<integer(recipe.material_min_enhancement)||pet.display_name===recipe.excluded_material_name||Number(pet.reserved)===1||Number(pet.protected_ref)===1||Number(pet.pending_equip)===1);
    if(invalid)return complete(t,{operationId,eventId:input.eventId,destinationId:input.destinationId,owner,firstId:first?integer(first.id):null,secondId:second?integer(second.id):null,resultCode:"invalid_material",data:"조합할 창조 300강 미니펫 두 마리를 다시 확인해 주세요.",result:{status:"rejected"},summary:{mutation:false,reason:"invalid_material",firstIndex:command.firstIndex.toString(),secondIndex:command.secondIndex.toString()}});
    if(balanceBefore<cost)return complete(t,{operationId,eventId:input.eventId,destinationId:input.destinationId,owner,firstId:integer(first.id),secondId:integer(second.id),resultCode:"insufficient_point",data:`포인트가 부족합니다. 필요 포인트: 🅟${commas(cost)}`,result:{status:"rejected",pointCost:cost.toString(),pointBalanceAfter:balanceBefore.toString()},summary:{mutation:false,reason:"insufficient_point",pointCost:cost.toString(),balance:balanceBefore.toString()}});
    const rewards=await t.query<RewardRow[]>("SELECT reward.pool_sequence,reward.mini_pet_definition_id definition_id,definition.display_name,definition.emoji_value,reward.sale_price,reward.battle_experience,reward.castle_experience,reward.raid_experience FROM mini_pet_elite_combine_rewards reward JOIN mini_pet_definitions definition ON definition.id=reward.mini_pet_definition_id WHERE reward.recipe_id=? AND reward.active=TRUE AND definition.active=TRUE ORDER BY reward.pool_sequence FOR UPDATE",[recipe.id]);if(rewards.length===0)throw new Error("MINI_PET_ELITE_COMBINE_REWARD_REQUIRED");
    const roll=resolveMiniPetEliteCombineRoll({successRate:Number(recipe.success_rate),rewardCount:rewards.length,random:this.random}),balanceAfter=balanceBefore-cost;
    const currency=await t.execute("UPDATE currency_accounts SET balance=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE player_id=? AND currency_code='point' AND version=?",[balanceAfter.toString(),owner.player_id,account.version]);if(currency.affectedRows!==1n)throw new Error("MINI_PET_ELITE_COMBINE_CURRENCY_CONFLICT");await t.execute("INSERT INTO currency_ledger(operation_id,sequence_no,player_id,currency_code,delta,balance_after,reason_code) VALUES (?,1,?,'point',?,?,'mini_pet_elite_combine')",[operationId,owner.player_id,(-cost).toString(),balanceAfter.toString()]);
    let reward:RewardRow|undefined,createdId:bigint|null=null;
    if(roll.success){reward=rewards[roll.rewardIndex!];if(reward===undefined)throw new Error("MINI_PET_ELITE_COMBINE_REWARD_INDEX");const ids=[integer(first.id),integer(second.id)];await t.execute("DELETE FROM mini_pet_title_assignments WHERE owned_mini_pet_id IN (?,?)",ids);const deleted=await t.execute("DELETE FROM owned_mini_pets WHERE player_id=? AND id IN (?,?)",[owner.player_id,...ids]);if(deleted.affectedRows!==2n)throw new Error("MINI_PET_ELITE_COMBINE_MATERIAL_CONFLICT");const remaining=await t.query<Array<{id:Numeric}>>("SELECT id FROM owned_mini_pets WHERE player_id=? AND equipped=FALSE ORDER BY COALESCE(bag_sequence,id),id FOR UPDATE",[owner.player_id]);for(let index=0;index<remaining.length;index++)await t.execute("UPDATE owned_mini_pets SET bag_sequence=?,version=version+1 WHERE id=?",[index+1,remaining[index]!.id]);const created=await t.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,equipped,sale_price,is_elite,bag_sequence,enhancement_level,battle_experience,castle_experience,raid_experience,version) VALUES (?,?,FALSE,?,TRUE,?,0,?,?,?,1)",[owner.player_id,reward.definition_id,reward.sale_price,remaining.length+1,reward.battle_experience,reward.castle_experience,reward.raid_experience]);createdId=created.insertId;}
    await t.execute("INSERT INTO mini_pet_elite_combine_events(operation_id,player_id,recipe_id,recipe_version,first_owned_mini_pet_id,second_owned_mini_pet_id,first_definition_id,second_definition_id,point_cost,point_balance_before,point_balance_after,success_roll,success,reward_roll,reward_pool_sequence,reward_definition_id,created_owned_mini_pet_id,material_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[operationId,owner.player_id,recipe.id,recipe.recipe_version,first.id,second.id,first.definition_id,second.definition_id,cost.toString(),balanceBefore.toString(),balanceAfter.toString(),fixed(roll.successRoll),roll.success,roll.rewardRoll===null?null:fixed(roll.rewardRoll),reward?.pool_sequence??null,reward?.definition_id??null,createdId,JSON.stringify([{id:String(first.id),definitionId:String(first.definition_id),displayName:first.display_name,bagSequence:String(first.bag_sequence),enhancement:String(first.enhancement_level),version:String(first.version)},{id:String(second.id),definitionId:String(second.definition_id),displayName:second.display_name,bagSequence:String(second.bag_sequence),enhancement:String(second.enhancement_level),version:String(second.version)}])]);
    const data=roll.success?`엘리트 미니펫 조합 성공!\n획득: ${reward!.emoji_value??""}${reward!.display_name}\n사용 포인트: 🅟${commas(cost)}`:`엘리트 미니펫 조합에 실패했습니다.\n재료 미니펫은 유지됩니다.\n사용 포인트: 🅟${commas(cost)}`;
    return complete(t,{operationId,eventId:input.eventId,destinationId:input.destinationId,owner,firstId:integer(first.id),secondId:integer(second.id),resultCode:roll.success?"success":"failed",data,result:{status:roll.success?"success":"failed",createdOwnedMiniPetId:createdId?.toString(),rewardDefinitionId:reward?String(reward.definition_id):undefined,rewardName:reward?.display_name,pointCost:cost.toString(),pointBalanceAfter:balanceAfter.toString(),successRoll:roll.successRoll,rewardRoll:roll.rewardRoll??undefined},summary:{mutation:true,success:roll.success,recipeVersion:recipe.recipe_version,pointCost:cost.toString(),balanceBefore:balanceBefore.toString(),balanceAfter:balanceAfter.toString(),firstOwnedMiniPetId:String(first.id),secondOwnedMiniPetId:String(second.id),successRoll:fixed(roll.successRoll),rewardRoll:roll.rewardRoll===null?null:fixed(roll.rewardRoll),rewardPoolSequence:reward?.pool_sequence??null,rewardDefinitionId:reward?String(reward.definition_id):null,createdOwnedMiniPetId:createdId?.toString()??null}});
  });}
}
