SELECT
  CONSTRAINT_NAME,
  CHECK_CLAUSE,
  (LENGTH(CHECK_CLAUSE) - LENGTH(REPLACE(CHECK_CLAUSE, '''BADGE''', ''))) / LENGTH('''BADGE''') AS badge_occurrences
FROM information_schema.CHECK_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE()
  AND CONSTRAINT_NAME = 'chk_object_registry_type';

SELECT COUNT(*) AS preserved_type_count
FROM (
  SELECT 'ITEM' AS object_type UNION ALL SELECT 'PET' UNION ALL SELECT 'FURNITURE'
  UNION ALL SELECT 'TITLE' UNION ALL SELECT 'PET_TITLE' UNION ALL SELECT 'PACKAGE'
  UNION ALL SELECT 'CURRENCY' UNION ALL SELECT 'SKILL' UNION ALL SELECT 'HOME_BUILDING'
  UNION ALL SELECT 'MINI_PET'
) expected
JOIN information_schema.CHECK_CONSTRAINTS checks
  ON checks.CONSTRAINT_SCHEMA = DATABASE()
 AND checks.CONSTRAINT_NAME = 'chk_object_registry_type'
 AND LOCATE(CONCAT('''', expected.object_type, ''''), checks.CHECK_CLAUSE) > 0;

SELECT COUNT(*) AS badge_objects
FROM object_registry
WHERE object_type = 'BADGE';
