import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { after,before,describe,it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";

const enabled=process.env.WAVE12_ISOLATED_MARIADB_TEST==="true",required=(name:string)=>process.env[name]??"wave12-not-configured";
const sources=["member","pet_home","equipped_furniture","member_pet","pet_skill","member_title","pet_title","mini_pet_title","mini_pet_collection","trial_tower","pet_explore","guild","attendance_light","board","free_market"];

describe("Wave12 admin diagnostics actual HTTP ingress",{skip:!enabled},()=>{
  let database:DatabaseClient;const apps=new Set<ReturnType<typeof buildApp>>(),token="wave12-isolated-token",admin="wave12-http-admin",ordinary="wave12-http-ordinary",roomId="990000000000412",roomName="Wave12 진단방",replies:Array<{room:string;data:string}>=[];
  before(async()=>{database=createDatabaseClient(loadConfig().database);await database.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=1 WHERE command_code<>'ADMIN_STATUS_ALL'");await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code IN ('ADMIN_CHARACTER_COUNT_STATS','ADMIN_MATZZANG_TIME_CHECK')");
    await database.execute("INSERT INTO players(id,status,version) VALUES (412001,'active',1),(412002,'active',1),(412003,'active',1)");await database.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (412001,'Wave12 관리자',1),(412002,'Wave12 일반',1),(412003,'Wave12 대상',1)");const identity=await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (412001,'kakao',?,'Wave12 관리자','linked')",[admin]);await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (412002,'kakao',?,'Wave12 일반','linked')",[ordinary]);await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (412901,'wave12-http-admin','Wave12 관리자','synthetic','active')");await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (412901,?)",[identity.insertId]);await database.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 412901,id FROM admin_roles WHERE code='super_admin'");
    for(const [environment,identity]of[["dev","hoibot-dev"],["prod","hoibot-prod"]]as const){const snapshot=await database.execute("INSERT INTO legacy_snapshot_sets(environment_code,database_identity,snapshot_version,snapshot_at,snapshot_status) VALUES (?,?,12001,'2026-09-07 05:18:00','ready')",[environment,identity]);for(const code of sources){const raw=oracleRaw(code);await database.execute("INSERT INTO legacy_source_snapshots(snapshot_set_id,source_code,raw_json,content_sha256,utf16_code_unit_count,entity_count,read_status,captured_at) VALUES (?,?,?,?,?,0,'valid','2026-09-07 05:18:00')",[snapshot.insertId,code,raw,createHash("sha256").update(raw).digest("hex"),raw.length]);}await database.execute("UPDATE legacy_snapshot_environments SET active_snapshot_set_id=? WHERE environment_code=?",[snapshot.insertId,environment]);}
    await database.execute("INSERT INTO player_pets(id,player_id,display_name,pet_type_code,experience,enhancement_level,version) VALUES (412777,412003,'Wave12 펫','legacy-sky',100,10,1)");await database.execute("INSERT INTO player_pet_elementals(player_pet_id,display_name,grade_code,grade_display_name,raid_charm,castle_charm) VALUES (412777,'정령','rare','희귀',40,50)");await database.execute("INSERT INTO player_pet_pendants(player_pet_id,display_name,grade_code,grade_display_name,raid_charm,castle_charm) VALUES (412777,'펜던트','rare','희귀',60,70)");await database.execute("INSERT INTO player_legacy_ring_reward_snapshots(player_id,ring_name,ring_grade,enhancement_level,raid_charm,castle_charm,source_version) VALUES (412003,'레거시 반지','희귀',1,11,13,'wave12')");await database.execute("INSERT INTO player_pet_intimacy(player_pet_id,charm) VALUES (412777,500)");await database.execute("INSERT INTO player_homes(player_id,display_name,base_experience) VALUES (412003,'Wave12 홈',1000)");await database.execute("INSERT INTO player_home_badge_cubes(player_id,badge_code,castle_percent,raid_percent,pet_upgrade_percent,explore_percent,equipped) VALUES (412003,'W12',20,20,50,10,TRUE)");await database.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES (412003,'premium',TRUE,TRUE)");await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT 412003,id,7,1 FROM item_definitions WHERE code='ITEM-RWD-CASTLE-BEGINNER'");await database.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (412003,'🥇',1)");
  });
  after(async()=>{for(const app of apps)await app.close();await database.close();});
  it("routes both commands through buildApp, preserves exact legacy sections and suppresses inbox replay",async()=>{let operational=true;const app=appWithRoom(()=>operational,"dev"),send=(id:string,user:string,message:string)=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:roomName,sender:"Wave12",json:{_id:id,chat_id:roomId,user_id:user}}});
    const characterId=`wave12-http-character-${Date.now()}`,before=replies.length;assert.equal((await send(characterId,admin,"/글자수통계")).statusCode,202);assert.equal(replies.length,before+1);const character=replies.at(-1)!.data;assert.match(character,/^📊 글자수 통계\n\n\[핵심 데이터\]/);assert.match(character,/펜던트: .* \/ 3명/);assert.match(character,/\[운영 데이터\][\s\S]*펫탐험/);assert.match(character,/↳ 동기화: \/길드데이터동기화, \/전체동기화/);assert.equal((await send(characterId,admin,"/글자수통계")).statusCode,202);assert.equal(replies.length,before+1);assert.deepEqual(await receipt(`iris:${characterId}`,"stats.character_count.read"),[1n,1n,1n,1n]);
    const matzangId=`wave12-http-matzang-${Date.now()}`;assert.equal((await send(matzangId,admin,"/맞짱시간체크 Wave12 대상")).statusCode,202);const matzang=replies.at(-1)!.data;assert.match(matzang,/^👊 맞짱 시간체크 👊\n기준: \[🥇Wave12 대상\]/);assert.match(matzang,/종합매력: 18,951💕/);assert.match(matzang,/홈데이터 로드: 1ms/);assert.match(matzang,/캐슬-공격아이템: 7💕 \/ 1ms/);assert.match(matzang,new RegExp(`응답 공통 처리📋${"\u200b".repeat(500)}`));assert.match(matzang,new RegExp(`세부 계산📋${"\u200b".repeat(500)}`));assert.match(matzang,/※ 전투\/상대선정\/저장은 실행하지 않았습니다\.$/);assert.deepEqual(await receipt(`iris:${matzangId}`,"admin.matzang_time_check:412901"),[1n,1n,1n,1n]);
    const denied=`wave12-http-denied-${Date.now()}`;await send(denied,ordinary,"/글자수통계");assert.deepEqual(await receipt(`iris:${denied}`,"stats.character_count.read"),[0n,0n,0n,0n]);const state=(await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='ADMIN_STATUS_ALL'"))[0];assert.equal(state?.rollout_state,"LEGACY_ONLY");const statusId=`wave12-http-status-${Date.now()}`,beforeStatus=replies.length;await send(statusId,admin,"/상태전체");assert.equal(replies.length,beforeStatus);assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_key=?",[`iris:${statusId}`]),0n);operational=false;const wrong=`wave12-http-wrong-${Date.now()}`;await send(wrong,admin,"/맞짱시간체크 Wave12 대상");assert.deepEqual(await receipt(`iris:${wrong}`,"admin.matzang_time_check:412901"),[0n,0n,0n,0n]);operational=true;
    const prodApp=appWithRoom(()=>true,"prod"),prodId=`wave12-http-prod-${Date.now()}`;await prodApp.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:"/글자수통계",room:roomName,sender:"Wave12",json:{_id:prodId,chat_id:roomId,user_id:admin}}});const stored=(await database.query<Array<{result_json:string|{environment:string}}>>("SELECT result_json FROM operations WHERE idempotency_scope='stats.character_count.read' AND idempotency_key=?",[`iris:${prodId}`]))[0]!,result=typeof stored.result_json==="string"?JSON.parse(stored.result_json)as{environment:string}:stored.result_json;assert.equal(result.environment,"prod");});
  function appWithRoom(isOperational:()=>boolean,environment:"prod"|"dev"){const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:environment,IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave12-isolated-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});let tick=0;const app=buildApp(config,{database:createDatabaseClient(config.database),adminDiagnosticNow:()=>++tick,inspectIrisChannel:async()=>isOperational()?{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async reply=>{replies.push(reply);}});apps.add(app);return app;}
  async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await database.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}async function receipt(eventId:string,scope:string){return[await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[scope,eventId]),await count("SELECT COUNT(*) value FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId]),await count("SELECT COUNT(*) value FROM command_executions WHERE event_id=?",[eventId]),await count("SELECT COUNT(*) value FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId])];}
});

function oracleRaw(code:string):string{if(code==="member")return JSON.stringify({member:{가:{},나:{}}});if(code==="member_pet")return JSON.stringify({가:{pendant:{}},나:{pendantBag:[]},다:{pendantBag:{}}});if(code==="member_title"||code==="pet_title"||code==="mini_pet_title"||code==="mini_pet_collection")return JSON.stringify({member:{가:{}}});if(code==="trial_tower")return JSON.stringify({user:{가:{}}});if(code==="pet_explore")return JSON.stringify({userBet:{가:{}},autoFixedDungeon:{나:{}},record:{다:{}},bet:{x:[{user:"라"}]}});if(code==="guild")return JSON.stringify({guilds:{g1:{members:{가:{},나:{}}},g2:{members:{나:{},다:{}}}}});if(code==="attendance_light")return JSON.stringify({users:{가:{},나:{}}});if(code==="board")return JSON.stringify({memo:[{user:"가"}],record:[{user:"나"},{user:"가"}]});if(code==="free_market")return JSON.stringify({listings:[{seller:"가"}],completedLogs:[{seller:"나",buyer:"다"}]});return JSON.stringify({가:{}});}
