import assert from "node:assert/strict";import{describe,it}from"node:test";import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";import{ApplicationError}from"../src/shared/application-error.js";import{AdminRoleDeleteService,isAdminRoleDeleteCommand}from"../src/admin/role-delete-service.js";
function scripted(q:unknown[]){const left=[...q],sql:string[]=[];let id=1300n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);if(!left.length)throw new Error(`Unexpected query: ${s}`);return left.shift()as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);id++;return{affectedRows:1n,insertId:id};}};const database:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw new Error()},execute:async()=>{throw new Error()},withTransaction:async<T>(w:(x:DatabaseTransaction)=>Promise<T>)=>w(tx),close:async()=>undefined};return{database,sql};}const cmd=(m:string,e="e")=>({externalUserId:"master",channelId:"room",eventId:e,message:m});
describe("admin role delete command",()=>{it("accepts only a complete target",()=>{assert.equal(isAdminRoleDeleteCommand("/관리자삭제 대상"),true);for(const m of["/관리자삭제","/관리자삭제 대상 ","관리자삭제 대상"])assert.equal(isAdminRoleDeleteCommand(m),false);});});
describe("admin role delete service",()=>{
 it("revokes the sole manager role and disables operator sessions",async()=>{const s=scripted([[{operator_id:7n}],[],[{player_id:2n,external_identity_id:92n}],[{id:3n}],[{operator_id:8n}],[{operator_id:8n}],[{role_count:0n}]]);const r=await new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 대상"));assert.equal(r.operatorDisabled,true);for(const f of["DELETE FROM admin_operator_roles","UPDATE admin_operators SET status='inactive'","UPDATE admin_sessions","INSERT INTO admin_role_assignment_history","INSERT INTO command_audit"])assert.ok(s.sql.some(x=>x.includes(f)),f);});
 it("keeps an operator active when another role remains",async()=>{const s=scripted([[{operator_id:7n}],[],[{player_id:2n,external_identity_id:92n}],[{id:3n}],[{operator_id:8n}],[{operator_id:8n}],[{role_count:1n}]]);const r=await new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 대상"));assert.equal(r.operatorDisabled,false);assert.equal(s.sql.some(x=>x.includes("status='inactive'")),false);});
 it("rejects a target without manager role",async()=>{const s=scripted([[{operator_id:7n}],[],[{player_id:2n,external_identity_id:92n}],[{id:3n}],[{operator_id:8n}],[]]);await assert.rejects(()=>new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 대상")),(e:unknown)=>e instanceof ApplicationError&&e.code==="ADMIN_ROLE_NOT_ASSIGNED");});
 it("rejects unauthorized actor before target lookup",async()=>{const s=scripted([[]]);await assert.rejects(()=>new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 대상")),(e:unknown)=>e instanceof ApplicationError&&e.statusCode===403);});
 it("replays same target and rejects changed content",async()=>{const stored={status:"revoked",targetPlayerId:"2",targetOperatorId:"8",targetName:"대상",roleCode:"manager",operatorDisabled:true,outboxId:"9",auditId:"10",data:"완료"};let s=scripted([[{operator_id:7n}],[{result_json:JSON.stringify(stored)}]]);assert.equal((await new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 대상"))).replayed,true);s=scripted([[{operator_id:7n}],[{result_json:JSON.stringify(stored)}]]);await assert.rejects(()=>new AdminRoleDeleteService(s.database).execute(cmd("/관리자삭제 다른대상")),(e:unknown)=>e instanceof ApplicationError&&e.code==="ADMIN_ROLE_DELETE_REPLAY_MISMATCH");});
});
