import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { CapableDatabaseClient, ControlledDatabaseTransaction, DatabaseTransaction, DatabaseWriteResult, ReadOnlySnapshotTransaction } from "../src/database.js";
import { executeAppWiringEntrypoint, type AppWiringEntrypointHandlers } from "../src/dispatch/app-wiring-entrypoint-runner.js";
import { MariaAppWiringOperationProvider, type AppWiringEffectMode, type AppWiringMutationParticipant, type AppWiringRoute } from "../src/dispatch/app-wiring-operation-provider.js";
import { createEnvironmentContext, verifyStartupDatabaseIdentity } from "../src/runtime/environment-context.js";

type Row=Record<string,unknown>;
const fingerprint="d".repeat(64);
const marketOperationId="market01";
class MemoryDatabase implements CapableDatabaseClient {
  row?:Row;
  readonly domainWrites:string[]=[];
  readonly typedReceipts=new Map<string,string>();
  readonly receiptLinks:Array<readonly unknown[]>=[];
  readSnapshots=0;
  failCompletionOnce=false;
  duplicateTerminalOnInsert=false;
  uncertainCommitOnce=false;
  uncertainClaimCommitOnce=false;
  driftGenerationOnUncertain=false;
  driftClaimIdentityOnUncertain=false;
  ambiguousReceiptLinkDuplicate=false;
  typedOperationStatus="COMPLETED";
  async ping(){} async verifyRollback(){return true;} async close(){}
  async query<T>(sql:string):Promise<T>{if(sql==="SELECT DATABASE() AS database_identity")return[{database_identity:"hoi_bot"}] as T;return[] as T;}
  async execute():Promise<DatabaseWriteResult>{throw new Error("RAW_POOL_WRITE_FORBIDDEN");}
  async withTransaction<T>(work:(tx:DatabaseTransaction)=>Promise<T>):Promise<T>{return this.withControlledTransaction(work as (tx:ControlledDatabaseTransaction)=>Promise<T>);}
  async withReadOnlySnapshot<T>(work:(tx:ReadOnlySnapshotTransaction)=>Promise<T>):Promise<T>{this.readSnapshots+=1;return work({query:async<R>()=>[] as R});}
  async withControlledTransaction<T>(work:(tx:ControlledDatabaseTransaction)=>Promise<T>):Promise<T>{
    const snapshot=this.snapshot();
    let tx!:ControlledDatabaseTransaction;
    tx={query:async<R>(sql:string,values:readonly unknown[]=[])=>this.txQuery<R>(sql,values),execute:(sql,values=[])=>this.txExecute(sql,values),withSavepoint:async<R>(nested:(tx:ControlledDatabaseTransaction)=>Promise<R>)=>{const savepoint=this.snapshot();try{return await nested(tx);}catch(error){this.restore(savepoint);throw error;}}};
    try{const result=await work(tx);if(this.uncertainClaimCommitOnce&&this.row?.claim_state==="CLAIMED"){this.uncertainClaimCommitOnce=false;if(this.driftClaimIdentityOnUncertain)this.row.app_wiring_operation_id="other001";throw Object.assign(new Error("CLAIM_COMMIT_RESULT_UNKNOWN"),{commitMayHaveSucceeded:true});}if(this.uncertainCommitOnce&&this.row?.claim_state==="COMPLETED"){this.uncertainCommitOnce=false;if(this.driftGenerationOnUncertain)this.row.lease_generation=BigInt(this.row.lease_generation as bigint)+1n;throw Object.assign(new Error("COMMIT_RESULT_UNKNOWN"),{commitMayHaveSucceeded:true});}return result;}catch(error){if((error as {commitMayHaveSucceeded?:boolean}).commitMayHaveSucceeded!==true)this.restore(snapshot);throw error;}
  }
  private snapshot(){return{row:this.row===undefined?undefined:{...this.row},writes:this.domainWrites.slice(),typed:new Map(this.typedReceipts),links:this.receiptLinks.slice()};}
  private restore(value:ReturnType<MemoryDatabase["snapshot"]>){this.row=value.row;this.domainWrites.splice(0,Infinity,...value.writes);this.typedReceipts.clear();for(const entry of value.typed)this.typedReceipts.set(...entry);this.receiptLinks.splice(0,Infinity,...value.links);}
  private async txQuery<T>(sql:string,values:readonly unknown[]):Promise<T>{
    if(sql.includes("FROM canonical_app_wiring_operations"))return(this.row?.request_identity_fingerprint===values[0]?[this.row]:[]) as T;
    if(sql.startsWith("SELECT result_fingerprint,operation_status FROM canonical_market_operations")){const stored=this.typedReceipts.get(String(values[0]));return(stored===undefined?[]:[{result_fingerprint:stored,operation_status:this.typedOperationStatus}]) as T;}
    if(sql.includes("FROM canonical_app_wiring_receipt_links WHERE canonical_app_wiring_receipt_link_id=")){const stored=this.receiptLinks.find(link=>link[0]===values[0]);if(stored===undefined)return[] as T;const columns=["canonical_app_wiring_receipt_link_id","app_wiring_operation_id","receipt_kind","result_fingerprint","daily_prayer_operation_id","home_aggregate_operation_id","market_operation_id","member_title_operation_id","mini_pet_title_operation_id","package_use_operation_id","pet_explore_operation_id","pet_explore_event_control_operation_id","pet_title_operation_id","player_identity_operation_id"];return[Object.fromEntries(columns.map((column,index)=>[column,stored[index]]))] as T;}
    return[] as T;
  }
  private async txExecute(sql:string,v:readonly unknown[]):Promise<DatabaseWriteResult>{
    if(sql.startsWith("INSERT INTO canonical_app_wiring_operations")){if(this.duplicateTerminalOnInsert){this.duplicateTerminalOnInsert=false;this.row=this.claimRow(v,"COMPLETED");this.row.result_json='{"status":"OK"}';this.row.lease_token=null;this.row.lease_expires_time=null;throw Object.assign(new Error("Duplicate entry"),{code:"ER_DUP_ENTRY"});}this.row=this.claimRow(v,"CLAIMED");return this.ok();}
    if(sql.includes("SET claim_state='MUTATION_STARTED'")){if(this.row?.claim_state!=="CLAIMED"||!this.fence(v[2],v[3],v[4]))return this.no();Object.assign(this.row,{claim_state:"MUTATION_STARTED",recovery_status:"PENDING",recovery_code:"ACTIVE_MUTATION_IN_PROGRESS"});return this.ok();}
    if(sql.startsWith("INSERT INTO canonical_market_operations")){this.typedReceipts.set(String(v[0]),String(v[6]));this.domainWrites.push(sql);return this.ok();}
    if(sql.startsWith("INSERT INTO canonical_app_wiring_receipt_links")){assert.equal(v.length,18);if(this.ambiguousReceiptLinkDuplicate){this.ambiguousReceiptLinkDuplicate=false;throw Object.assign(new Error("Duplicate entry"),{code:"ER_DUP_ENTRY"});}if(this.receiptLinks.some(link=>link[0]===v[0]))throw Object.assign(new Error(`Duplicate entry '${String(v[0])}' for key 'PRIMARY'`),{code:"ER_DUP_ENTRY",constraint:"PRIMARY"});assert.equal(v.slice(4,14).filter(value=>value!==null).length,1);assert.equal(v[2],"MARKET");assert.equal(v[3],fingerprint);assert.equal(v[6],marketOperationId);this.receiptLinks.push(v);return this.ok();}
    if(sql.includes("SET claim_state='COMPLETED'")){if(this.failCompletionOnce){this.failCompletionOnce=false;throw new Error("TERMINAL_FAULT");}if(this.row?.claim_state!=="MUTATION_STARTED"&&!sql.includes("AND claim_state='CLAIMED'"))return this.no();if(!this.fence(v[3],v[4],v[5]))return this.no();Object.assign(this.row!,{claim_state:"COMPLETED",result_json:v[0],error_code:null,lease_token:null,lease_expires_time:null,recovery_status:"NONE",recovery_code:null});return this.ok();}
    if(sql.includes("SET claim_state='FAILED'")){if(this.row?.claim_state!=="CLAIMED"||!this.fence(v[3],v[4],v[5]))return this.no();Object.assign(this.row,{claim_state:"FAILED",result_json:null,error_code:v[0],lease_token:null,lease_expires_time:null,recovery_status:"NONE",recovery_code:null});return this.ok();}
    this.domainWrites.push(sql);return this.ok();
  }
  private claimRow(v:readonly unknown[],state:string):Row{return{app_wiring_operation_id:v[0],request_identity_fingerprint:v[1],request_namespace:v[2],entrypoint_kind:v[3],external_request_id:v[4],request_key:v[5],payload_fingerprint:v[6],route:v[9],reason_code:v[10],command_code:v[11],handler_key:v[12],claim_state:state,effect_mode:v[13],lease_token:v[14],lease_generation:1n,lease_expires_time:v[15],attempt_count:1n,recovery_status:"NONE",recovery_code:null,result_json:null,error_code:null};}
  private fence(id:unknown,token:unknown,generation:unknown){return this.row?.app_wiring_operation_id===id&&this.row?.lease_token===token&&BigInt(this.row?.lease_generation as bigint)===BigInt(generation as bigint);}
  private ok(){return{affectedRows:1n,insertId:0n};}private no(){return{affectedRows:0n,insertId:0n};}
}
const now=()=>new Date("2026-09-04T00:00:00Z");
async function provider(db:MemoryDatabase,generate:()=>string=()=>"a1234567",maxAttempts=1){const env=await verifyStartupDatabaseIdentity(db,createEnvironmentContext({environmentCode:"dev",databaseIdentity:"hoi_bot"}));return new MariaAppWiringOperationProvider(db,env,generate,maxAttempts,now,()=>"c".repeat(64));}
async function writeMarketReceipt(db:AppWiringMutationParticipant):Promise<void>{await db.execute("INSERT INTO canonical_market_operations(market_operation_id,player_id,operation_type,replay_namespace,request_key,payload_fingerprint,result_fingerprint,operation_status,INSERT_USER,INSERT_TIME,UPDATE_USER,UPDATE_TIME) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",[marketOperationId,"player01","TEST","test","request",fingerprint,fingerprint,"COMPLETED","test","2026-09-04 09:00:00","test","2026-09-04 09:00:00"]);}
function handlers(calls:string[]):AppWiringEntrypointHandlers<string>{
  const read=(name:string)=>async(db:{query<T>(sql:string):Promise<T>})=>{calls.push(name);assert.equal("execute" in db,false);await db.query("SELECT 1");return{value:name,receipt:{status:"OK"}};};
  const mutation=(name:string)=>async(db:AppWiringMutationParticipant)=>{calls.push(name);assert.equal("close" in db,false);await db.execute("UPDATE domain_table SET value=1");await writeMarketReceipt(db);return{value:name,receipt:{status:"OK",resultFingerprint:fingerprint},typedReceipt:{receiptKind:"MARKET" as const,marketOperationId,resultFingerprint:fingerprint}};};
  return{MODERN:{READ_ONLY:read("MODERN_READ"),MUTATION:mutation("MODERN_MUTATION")},LEGACY_FALLBACK:{READ_ONLY:read("LEGACY_READ"),MUTATION:mutation("LEGACY_MUTATION")},SHADOW:read("SHADOW"),REJECT:async()=>{calls.push("REJECT");return{value:"REJECT",receipt:{status:"REJECTED"}};}};
}
function request(route:AppWiringRoute,effectMode:AppWiringEffectMode,calls:string[],externalRequestId=`req-${route}-${effectMode}`){return{claim:{entrypointKind:"WEB" as const,externalRequestId,normalizedPayload:{},actor:"web"},resolveRoute:()=>({route,effectMode,reasonCode:"TEST",handlerKey:route==="REJECT"?undefined:"handler"}),handlers:handlers(calls),replayCompleted:async()=>"COMPLETED_REPLAY",replayFailed:async()=>"FAILED_REPLAY",errorCode:()=>"HANDLER_FAILED"};}

describe("executeAppWiringEntrypoint atomic coordinator",()=>{
  for(const[route,effect]of[["MODERN","MUTATION"],["MODERN","READ_ONLY"],["LEGACY_FALLBACK","MUTATION"],["LEGACY_FALLBACK","READ_ONLY"],["SHADOW","READ_ONLY"],["REJECT","READ_ONLY"]]as const)it(`executes ${route}/${effect} through its minimum capability`,async()=>{const db=new MemoryDatabase(),calls:string[]=[];const value=await executeAppWiringEntrypoint(await provider(db),request(route,effect,calls));assert.equal(db.row?.claim_state,"COMPLETED");assert.equal(value,calls[0]);assert.equal(db.domainWrites.length,effect==="MUTATION"?2:0);assert.equal(db.receiptLinks.length,effect==="MUTATION"?1:0);assert.equal(db.readSnapshots,effect==="READ_ONLY"&&route!=="REJECT"?1:0);});
  it("replays FAILED without invoking a handler",async()=>{const db=new MemoryDatabase(),calls:string[]=[];const p=await provider(db),input=request("MODERN","READ_ONLY",calls,"failed-replay");await assert.rejects(()=>executeAppWiringEntrypoint(p,{...input,handlers:{...input.handlers,MODERN:{...input.handlers.MODERN,READ_ONLY:async()=>{throw new Error("boom");}}}}),/boom/);assert.equal(await executeAppWiringEntrypoint(p,input),"FAILED_REPLAY");assert.deepEqual(calls,[]);});
  it("returns a duplicate-race terminal replay",async()=>{const db=new MemoryDatabase();db.duplicateTerminalOnInsert=true;const calls:string[]=[];assert.equal(await executeAppWiringEntrypoint(await provider(db),request("MODERN","READ_ONLY",calls,"race")),"COMPLETED_REPLAY");assert.deepEqual(calls,[]);});
  it("rolls back domain, typed receipt and link when terminal persistence faults, then fences FAILED",async()=>{const db=new MemoryDatabase();db.failCompletionOnce=true;const p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,request("MODERN","MUTATION",[],"terminal-fault")),/TERMINAL_FAULT/);assert.deepEqual(db.domainWrites,[]);assert.equal(db.typedReceipts.size,0);assert.equal(db.receiptLinks.length,0);assert.equal(db.row?.claim_state,"FAILED");});
  it("reconciles an uncertain but committed terminal without rerunning mutation",async()=>{const db=new MemoryDatabase();db.uncertainCommitOnce=true;const calls:string[]=[];const value=await executeAppWiringEntrypoint(await provider(db),request("MODERN","MUTATION",calls,"uncertain"));assert.equal(value,"MODERN_MUTATION");assert.deepEqual(calls,["MODERN_MUTATION"]);assert.equal(db.row?.claim_state,"COMPLETED");assert.equal(db.domainWrites.length,2);assert.equal(db.receiptLinks.length,1);});
  it("does not reconcile the same result from a different lease generation",async()=>{const db=new MemoryDatabase();db.uncertainCommitOnce=true;db.driftGenerationOnUncertain=true;const calls:string[]=[];const p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,request("MODERN","MUTATION",calls,"wrong-generation")),/APP_WIRING_ENTRYPOINT_FAILURE_TRANSITION_FAILED/);assert.deepEqual(calls,["MODERN_MUTATION"]);assert.equal(db.domainWrites.length,2);});
  it("reconciles an uncertain READ_ONLY terminal without rerunning the handler",async()=>{const db=new MemoryDatabase();db.uncertainCommitOnce=true;const calls:string[]=[];assert.equal(await executeAppWiringEntrypoint(await provider(db),request("MODERN","READ_ONLY",calls,"uncertain-read")),"MODERN_READ");assert.deepEqual(calls,["MODERN_READ"]);assert.equal(db.row?.claim_state,"COMPLETED");});
  it("reconciles only the exact T0 inserted claim after an uncertain claim commit",async()=>{const db=new MemoryDatabase();db.uncertainClaimCommitOnce=true;const calls:string[]=[];assert.equal(await executeAppWiringEntrypoint(await provider(db),request("MODERN","READ_ONLY",calls,"uncertain-claim")),"MODERN_READ");assert.deepEqual(calls,["MODERN_READ"]);});
  it("rejects an uncertain T0 commit when the visible operation identity differs",async()=>{const db=new MemoryDatabase();db.uncertainClaimCommitOnce=true;db.driftClaimIdentityOnUncertain=true;const calls:string[]=[];const p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,request("MODERN","READ_ONLY",calls,"uncertain-claim-drift")),/CLAIM_COMMIT_RESULT_UNKNOWN/);assert.deepEqual(calls,[]);});
  it("replays an all-null legacy terminal without selecting a handler",async()=>{const db=new MemoryDatabase(),calls:string[]=[];const p=await provider(db),base=request("MODERN","MUTATION",calls,"legacy-terminal");await p.prepare(base.claim,base.resolveRoute);Object.assign(db.row!,{claim_state:"COMPLETED",result_json:'{"status":"OK"}',effect_mode:null,lease_token:null,lease_generation:null,lease_expires_time:null,attempt_count:null,recovery_status:null,recovery_code:null});assert.equal(await executeAppWiringEntrypoint(p,base),"COMPLETED_REPLAY");assert.deepEqual(calls,[]);});
  it("re-establishes MUTATION_STARTED after a swallowed savepoint rollback",async()=>{const db=new MemoryDatabase();const base=request("MODERN","MUTATION",[],"savepoint");await executeAppWiringEntrypoint(await provider(db),{...base,handlers:{...base.handlers,MODERN:{...base.handlers.MODERN,MUTATION:async participant=>{try{await participant.withTransaction(async nested=>{await nested.execute("UPDATE rolled_back_domain SET value=1");throw new Error("swallowed");});}catch{}assert.equal(db.row?.claim_state,"CLAIMED");await participant.execute("UPDATE committed_domain SET value=1");assert.equal(db.row?.claim_state,"MUTATION_STARTED");await writeMarketReceipt(participant);return{value:"OK",receipt:{status:"OK",resultFingerprint:fingerprint},typedReceipt:{receiptKind:"MARKET",marketOperationId,resultFingerprint:fingerprint}};}}}});assert.equal(db.row?.claim_state,"COMPLETED");assert.equal(db.domainWrites.some(sql=>sql.includes("rolled_back_domain")),false);});
  it("rejects missing or mismatched typed receipt proof",async()=>{const missingDb=new MemoryDatabase(),missingBase=request("MODERN","MUTATION",[],"missing-receipt"),missingProvider=await provider(missingDb);await assert.rejects(()=>executeAppWiringEntrypoint(missingProvider,{...missingBase,handlers:{...missingBase.handlers,MODERN:{...missingBase.handlers.MODERN,MUTATION:async participant=>{await participant.execute("UPDATE domain_table SET value=1");return{value:"BAD",receipt:{status:"OK",resultFingerprint:fingerprint},typedReceipt:{receiptKind:"MARKET",marketOperationId,resultFingerprint:fingerprint}};}}}}),/APP_WIRING_TYPED_RECEIPT_NOT_FOUND/);assert.equal(missingDb.row?.claim_state,"FAILED");const mismatchDb=new MemoryDatabase(),mismatchBase=request("MODERN","MUTATION",[],"mismatch-receipt"),mismatchProvider=await provider(mismatchDb);await assert.rejects(()=>executeAppWiringEntrypoint(mismatchProvider,{...mismatchBase,handlers:{...mismatchBase.handlers,MODERN:{...mismatchBase.handlers.MODERN,MUTATION:async participant=>{await writeMarketReceipt(participant);return{value:"BAD",receipt:{status:"OK",resultFingerprint:fingerprint},typedReceipt:{receiptKind:"MARKET",marketOperationId,resultFingerprint:"e".repeat(64)}};}}}}),/APP_WIRING_RECEIPT_FINGERPRINT_MISMATCH/);assert.equal(mismatchDb.row?.claim_state,"FAILED");});
  it("rejects a mutation outcome without a result fingerprint at runtime",async()=>{const db=new MemoryDatabase(),base=request("MODERN","MUTATION",[],"missing-fingerprint"),p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,{...base,handlers:{...base.handlers,MODERN:{...base.handlers.MODERN,MUTATION:(async(participant:AppWiringMutationParticipant)=>{await writeMarketReceipt(participant);return{value:"BAD",receipt:{status:"OK"},typedReceipt:{receiptKind:"MARKET",marketOperationId,resultFingerprint:fingerprint}};}) as never}}}),/APP_WIRING_MUTATION_RESULT_FINGERPRINT_REQUIRED/);assert.equal(db.row?.claim_state,"FAILED");assert.equal(db.typedReceipts.size,0);});
  it("requires the typed operation receipt itself to be COMPLETED",async()=>{const db=new MemoryDatabase();db.typedOperationStatus="FAILED";const p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,request("MODERN","MUTATION",[],"typed-failed")),/APP_WIRING_TYPED_RECEIPT_NOT_COMPLETED/);assert.equal(db.row?.claim_state,"FAILED");assert.equal(db.receiptLinks.length,0);});
  it("retries only a receipt-link primary-key collision",async()=>{const db=new MemoryDatabase();db.receiptLinks.push(["link0001"]);const ids=["claim001","link0001","link0002"];await executeAppWiringEntrypoint(await provider(db,()=>ids.shift()!,3),request("MODERN","MUTATION",[],"link-collision"));assert.equal(db.receiptLinks.at(-1)?.[0],"link0002");});
  it("fails closed on an ambiguous receipt-link duplicate instead of inferring a primary-key collision",async()=>{const db=new MemoryDatabase();db.ambiguousReceiptLinkDuplicate=true;const ids=["claim001","link0001"];const p=await provider(db,()=>ids.shift()!,1);await assert.rejects(()=>executeAppWiringEntrypoint(p,request("MODERN","MUTATION",[],"ambiguous-link-duplicate")),/APP_WIRING_RECEIPT_LINK_BUSINESS_CONFLICT/);assert.equal(db.row?.claim_state,"FAILED");assert.equal(db.receiptLinks.length,0);});
  it("blocks SELECT INTO session variables in READ_ONLY handlers",async()=>{const db=new MemoryDatabase(),base=request("MODERN","READ_ONLY",[],"session-var"),p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,{...base,handlers:{...base.handlers,MODERN:{...base.handlers.MODERN,READ_ONLY:async participant=>{await participant.query("SELECT 1 INTO @captured");return{value:"BAD",receipt:{status:"OK"}};}}}}),/APP_WIRING_QUERY_NOT_READ_ONLY/);assert.equal(db.row?.claim_state,"FAILED");});
  it("blocks session-affecting and resource-amplifying SELECT builtins in SHADOW, including no-arg LAST_INSERT_ID",async()=>{const statements=["SELECT RELEASE_ALL_LOCKS()","SELECT LAST_INSERT_ID()","SELECT LAST_INSERT_ID(7)","SELECT GET_LOCK('x', 1)","SELECT RELEASE_LOCK('x')","SELECT SLEEP(1)","SELECT BENCHMARK(10, SHA2('x', 256))"];for(const[index,statement]of statements.entries()){const db=new MemoryDatabase(),base=request("SHADOW","READ_ONLY",[],`shadow-builtin-${index}`),p=await provider(db);await assert.rejects(()=>executeAppWiringEntrypoint(p,{...base,handlers:{...base.handlers,SHADOW:async participant=>{await participant.query(statement);return{value:"BAD",receipt:{status:"OK"}};}}}),/APP_WIRING_QUERY_NOT_READ_ONLY/);assert.equal(db.row?.claim_state,"FAILED");}});
  it("never exposes execute to SHADOW",async()=>{const db=new MemoryDatabase();let exposed=false;const base=request("SHADOW","READ_ONLY",[],"shadow");await executeAppWiringEntrypoint(await provider(db),{...base,handlers:{...base.handlers,SHADOW:async participant=>{exposed="execute" in participant;return{value:"SHADOW",receipt:{status:"OK"}};}}});assert.equal(exposed,false);});
});
