import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { DatabaseClient, DatabaseTransaction, DatabaseWriteResult } from "../src/database.js";
import { ApplicationError } from "../src/shared/application-error.js";
import { CarrotTemperatureTransferService, isCarrotTemperatureTransferCommand } from "../src/market/carrot-temperature-transfer-service.js";

// 온도기 전달 SQL과 mutation을 기록하는 테스트 DB를 만듭니다.
function scripted(queryResults: unknown[]) {const left=[...queryResults],sql:string[]=[];let id=1000n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);if(left.length===0)throw new Error(`Unexpected query: ${s}`);return left.shift()as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);id+=1n;return{affectedRows:1n,insertId:id};}};const database:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw new Error("non-tx query");},execute:async()=>{throw new Error("non-tx execute");},withTransaction:async<T>(work:(v:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined};return{database,sql};}
const normal=()=>[[{identity_id:11n,player_id:1n}],[],[{player_id:2n}],[{id:1n},{id:2n}],[{id:41n,display_name:"당근온도기"}],[{quantity:5n,version:2n}],[{value:4n}]];

describe("carrot temperature transfer command",()=>{
 it("accepts target names with an optional complete count",()=>{for(const m of["/온도 대상","/온도 대상 회원 2"])assert.equal(isCarrotTemperatureTransferCommand(m),true);for(const m of["/온도","/온도  대상 ","온도 대상"])assert.equal(isCarrotTemperatureTransferCommand(m),false);});
 it("rejects zero and overflow before database",async()=>{for(const m of["/온도 대상 0","/온도 대상 1000001"]){const s=scripted([]);await assert.rejects(()=>new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:m,message:m}),(e:unknown)=>e instanceof ApplicationError&&e.code==="TEMPERATURE_TRANSFER_LIMIT");assert.equal(s.sql.length,0);}});
});
describe("carrot temperature transfer service",()=>{
 it("consumes sender inventory and increments target temperature atomically",async()=>{const s=scripted(normal());const r=await new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:"e",message:"/온도 대상 2"});assert.deepEqual([r.senderItemQuantity,r.targetTemperature],["3","6"]);for(const f of["UPDATE inventory_stacks","UPDATE player_counters","INSERT INTO inventory_ledger","INSERT INTO command_audit","INSERT INTO command_executions","INSERT INTO outbox_messages"])assert.ok(s.sql.some(x=>x.includes(f)),f);});
 it("uses one item when the count is omitted",async()=>{const s=scripted(normal());const r=await new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:"e",message:"/온도 대상"});assert.equal(r.quantity,"1");assert.equal(r.senderItemQuantity,"4");});
 it("rejects self transfer before inventory mutation",async()=>{const s=scripted([[{identity_id:11n,player_id:1n}],[],[{player_id:1n}]]);await assert.rejects(()=>new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:"e",message:"/온도 나"}),(e:unknown)=>e instanceof ApplicationError&&e.code==="SELF_TEMPERATURE_TRANSFER");assert.equal(s.sql.some(x=>x.includes("inventory_stacks")),false);});
 it("replays the same request and rejects changed content",async()=>{const stored={status:"transferred",senderPlayerId:"1",targetPlayerId:"2",targetName:"대상",quantity:"2",senderItemQuantity:"3",targetTemperature:"6",outboxId:"9",auditId:"10",data:"완료"};let s=scripted([[{identity_id:11n,player_id:1n}],[{result_json:JSON.stringify(stored)}]]);const r=await new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:"e",message:"/온도 대상 2"});assert.equal(r.replayed,true);s=scripted([[{identity_id:11n,player_id:1n}],[{result_json:JSON.stringify(stored)}]]);await assert.rejects(()=>new CarrotTemperatureTransferService(s.database).execute({externalUserId:"a",channelId:"r",eventId:"e",message:"/온도 대상 3"}),(e:unknown)=>e instanceof ApplicationError&&e.code==="TEMPERATURE_TRANSFER_REPLAY_MISMATCH");});
});
