import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { CastleBattleSeasonStartService } from "../src/castle/castle-battle-season-start-service.js";

const enabled=process.env.RUN_MARIADB_INTEGRATION==="true",required=(name:string):string=>process.env[name]??"integration-not-configured";
describe("castle battle season start MariaDB integration",{skip:!enabled},()=>{
  let db:DatabaseClient,operatorExternal:string,userExternal:string,previousId:bigint,firstId:bigint,secondId:bigint;const room="990000000000332",prefix=`castle-season-start-${Date.now()}`;
  async function player(external:string,name:string):Promise<{playerId:bigint;identityId:bigint}>{await db.execute("INSERT INTO players(status,version) VALUES ('active',1)");const playerId=(await db.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!.id;await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[playerId,name]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[playerId,external,name]);const identityId=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[external]))[0]!.id;return{playerId,identityId};}
  async function event(id:string,user:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('c',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});operatorExternal=`${prefix}-operator`;userExternal=`${prefix}-user`;await db.execute("INSERT INTO admin_operators(login_id,display_name,password_hash,status) VALUES (?,?,'synthetic','active')",[prefix,"합성 시즌 관리자"]);const operatorId=(await db.query<Array<{id:bigint}>>("SELECT id FROM admin_operators WHERE login_id=?",[prefix]))[0]!.id,roleId=(await db.query<Array<{id:bigint}>>("SELECT id FROM admin_roles WHERE code='super_admin'"))[0]!.id;await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) VALUES (?,?)",[operatorId,roleId]);const operator=await player(operatorExternal,"합성 시즌 관리자");await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operatorId,operator.identityId]);firstId=operator.playerId;secondId=(await player(userExternal,"합성 시즌 사용자")).playerId;await db.execute("UPDATE castle_battle_seasons SET status='closed',ends_at=UTC_TIMESTAMP(3)");await db.execute("INSERT INTO castle_battle_seasons(season_key,status,starts_at,ends_at,version) VALUES (?,'closed',DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 DAY),DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 DAY),1)",[`${prefix}-previous`]);previousId=(await db.query<Array<{id:bigint}>>("SELECT id FROM castle_battle_seasons WHERE season_key=?",[`${prefix}-previous`]))[0]!.id;await db.execute("INSERT INTO castle_battle_player_states(season_id,player_id,score,win_count,loss_count,tier_point,last_battle_at,version) VALUES (?,?,500,7,3,8,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 DAY),1),(?,?,200,2,5,4,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 DAY),1)",[previousId,firstId,previousId,secondId]);});
  after(async()=>{if(db)await db.close();});
  it("preserves Shadow, RBAC, baseline, tier-only reset, active guard, concurrency, rollback and replay",async()=>{const service=new CastleBattleSeasonStartService(db),shadow=`${prefix}-shadow`;await event(shadow,operatorExternal);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"}),{status:"shadow"});await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='CASTLE_BATTLE_SEASON_START'");const changed=`${prefix}-changed`;await event(changed,operatorExternal);const dispatched=await new IrisAdminCommandService(db).changePlayerPoint({eventId:changed,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"});assert.equal(dispatched.status,"changed");const run=(await db.query<Array<{season_id:bigint;baseline_snapshot_id:bigint;initialized_player_count:bigint;reset_tier_count:bigint}>>("SELECT season_id,baseline_snapshot_id,initialized_player_count,reset_tier_count FROM castle_battle_season_start_runs WHERE request_key=?",[changed]))[0]!;assert.equal(run.initialized_player_count,2n);assert.equal(run.reset_tier_count,2n);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM castle_battle_rank_snapshot_entries WHERE snapshot_id=?",[run.baseline_snapshot_id]))[0]!.count_value,2n);const states=await db.query<Array<{player_id:bigint;score:bigint;win_count:bigint;loss_count:bigint;tier_point:number}>>("SELECT player_id,score,win_count,loss_count,tier_point FROM castle_battle_player_states WHERE season_id=? ORDER BY player_id",[run.season_id]);assert.deepEqual(states,[{player_id:firstId,score:500n,win_count:7n,loss_count:3n,tier_point:1},{player_id:secondId,score:200n,win_count:2n,loss_count:5n,tier_point:1}]);const replay=await service.start({eventId:changed,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"});assert.equal(replay.seasonId,run.season_id.toString());const denied=`${prefix}-denied`;await event(denied,userExternal);await assert.rejects(()=>service.start({eventId:denied,externalUserId:userExternal,channelId:room,message:"/캐슬대전시즌시작"}),/시즌 관리 권한/);const active=`${prefix}-active`;await event(active,operatorExternal);await assert.rejects(()=>service.start({eventId:active,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"}),/이미 진행 중/);
    await db.execute("UPDATE castle_battle_seasons SET status='closed',ends_at=UTC_TIMESTAMP(3) WHERE id=?",[run.season_id]);const same=`${prefix}-same`;await event(same,operatorExternal);const concurrent=await Promise.all([service.start({eventId:same,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"}),service.start({eventId:same,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"})]);assert.equal(concurrent[0].auditId,concurrent[1].auditId);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM castle_battle_season_start_runs WHERE request_key=?",[same]))[0]!.count_value,1n);
    await db.execute("UPDATE castle_battle_seasons SET status='closed',ends_at=UTC_TIMESTAMP(3) WHERE id=?",[concurrent[0].seasonId]);const rollback=`${prefix}-rollback`;await event(rollback,operatorExternal);await db.execute("CREATE TRIGGER fail_castle_season_start_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='castle.battle.season.start' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced castle season start audit failure'; END IF; END");const beforeCount=(await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM castle_battle_seasons"))[0]!.count_value;try{await assert.rejects(()=>service.start({eventId:rollback,externalUserId:operatorExternal,channelId:room,message:"/캐슬대전시즌시작"}),/forced castle season start audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_castle_season_start_audit");}assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM castle_battle_seasons"))[0]!.count_value,beforeCount);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM castle_battle_season_start_runs WHERE request_key=?",[rollback]))[0]!.count_value,0n);});
});
