import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { CommandDispatcher,MariaCommandDispatchRepository } from "../src/dispatch/command-dispatcher.js";
import { DataStatusService } from "../src/admin/data-status-service.js";
const integration=process.env.RUN_MARIADB_INTEGRATION==="true"?describe:describe.skip;
integration("admin data status MariaDB integration",()=>{
 let db:DatabaseClient;const user="integration-data-status-admin",room="integration-data-status-room",prefix=`integration-data-status-${Date.now()}`;
 before(async()=>{db=createDatabaseClient(loadConfig().database);const op=988700005;await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'integration-data-status','통합 데이터상태 관리자','integration','active') ON DUPLICATE KEY UPDATE status='active'",[op]);await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='super_admin' ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)",[op]);await db.execute("INSERT INTO external_identities(provider_code,external_user_id,status) VALUES ('kakao',?,'linked') ON DUPLICATE KEY UPDATE status='linked'",[user]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT ?,id FROM external_identities WHERE provider_code='kakao' AND external_user_id=? ON DUPLICATE KEY UPDATE operator_id=VALUES(operator_id)",[op,user]);await seedRevision(db,"prod",`${prefix}-revision`);});
 after(async()=>db.close());
 async function event(id:string,external=user){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('a',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,external]);}
 async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await db.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
 it("pins one revision and preserves Shadow, replay, permission and rollback",async()=>{const service=new DataStatusService(db);const shadowId=`${prefix}-shadow`;await event(shadowId);const shadow=await new CommandDispatcher(new MariaCommandDispatchRepository(db),{enabled:true,allowAllCanaries:true,canaryUserIds:new Set()}).resolve({eventId:shadowId,message:"/데이터상태",userId:user,hasTrustedDisplayName:true});assert.deepEqual([shadow.route,shadow.handlerKey],["SHADOW","admin_data_status"]);const readId=`${prefix}-read`;await event(readId);const result=await service.read({eventId:readId,externalUserId:user,destinationId:room,environment:"prod"});assert.ok(result!==null);assert.equal(result.objects.length,12);assert.equal((result.data.match(/: 정상/g)??[]).length,10);assert.match(result.data,/1차: 손상/);assert.match(result.data,/2차: 누락/);assert.deepEqual(await service.read({eventId:readId,externalUserId:user,destinationId:room,environment:"prod"}),result);const denied=`${prefix}-denied`;await event(denied,`${user}-denied`);assert.equal(await service.read({eventId:denied,externalUserId:`${user}-denied`,destinationId:room,environment:"prod"}),null);const rollback=`${prefix}-rollback`;await event(rollback);await assert.rejects(()=>new DataStatusService(failAudit(db)).read({eventId:rollback,externalUserId:user,destinationId:room,environment:"prod"}),/integration data status audit failure/);assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_key=?",[rollback]),0n);});
});
async function seedRevision(db:DatabaseClient,environment:string,revision:string){const generation=await db.execute("INSERT INTO backup_generations(environment_code,revision_key,generation_status,created_at,completed_at) VALUES (?,?,'complete',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[environment,revision]);const targets=["member","member_pet","petSkillData","petHomeActivityData"],slots=["original","backup1","backup2"];for(const target of targets)for(const slot of slots){const exists=!(target==="petHomeActivityData"&&slot==="backup2");const object=await db.execute("INSERT INTO backup_objects(generation_id,target_code,slot_code,object_exists,content_sha256,size_bytes,modified_at,storage_locator) VALUES (?,?,?,?,REPEAT('b',64),100,UTC_TIMESTAMP(3),'synthetic')",[generation.insertId,target,slot,exists]);await db.execute("INSERT INTO backup_health_checks(backup_object_id,valid_json,error_code,checked_at) VALUES (?,?,?,UTC_TIMESTAMP(3))",[object.insertId,!(target==="petSkillData"&&slot==="backup1"),target==="petSkillData"&&slot==="backup1"?"JSON_PARSE":null]);}}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(sql,v)=>inner.query(sql,v),execute:(sql,v)=>inner.execute(sql,v),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(tx:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(tx=>work({query:(sql,v)=>tx.query(sql,v),execute:async(sql,v)=>{if(sql.includes("INSERT INTO command_audit"))throw new Error("integration data status audit failure");return tx.execute(sql,v);}}))};}
