import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { GuildLegacyFundCleanupService } from "../src/guild/guild-legacy-fund-cleanup-service.js";

const enabled=process.env.RUN_MARIADB_INTEGRATION==="true";
const required=(name:string):string=>process.env[name]??"integration-not-configured";

describe("guild legacy fund cleanup MariaDB integration",{skip:!enabled},()=>{
  let db:DatabaseClient,operatorExternal:string,unauthorizedExternal:string,operatorId:bigint,itemId:bigint;const room="990000000000331",prefix=`guild-fund-cleanup-${Date.now()}`;
  async function player(external:string,name:string):Promise<{playerId:bigint;identityId:bigint}>{await db.execute("INSERT INTO players(status,version) VALUES ('active',1)");const playerId=(await db.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!.id;await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[playerId,name]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[playerId,external,name]);const identityId=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[external]))[0]!.id;return{playerId,identityId};}
  async function event(id:string,user:string):Promise<void>{await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('a',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
  async function guild(code:string,name:string):Promise<bigint>{await db.execute("INSERT INTO guilds(code,display_name,status,mark,version) VALUES (?,?,'active','T',1)",[code,name]);return (await db.query<Array<{id:bigint}>>("SELECT id FROM guilds WHERE code=?",[code]))[0]!.id;}
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});operatorExternal=`${prefix}-operator`;unauthorizedExternal=`${prefix}-user`;await db.execute("INSERT INTO admin_operators(login_id,display_name,password_hash,status) VALUES (?,?,'synthetic','active')",[prefix,"합성 길드정리 관리자"]);operatorId=(await db.query<Array<{id:bigint}>>("SELECT id FROM admin_operators WHERE login_id=?",[prefix]))[0]!.id;const role=(await db.query<Array<{id:bigint}>>("SELECT id FROM admin_roles WHERE code='super_admin'"))[0]!.id;await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) VALUES (?,?)",[operatorId,role]);const operator=await player(operatorExternal,"합성 길드정리 관리자");await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operatorId,operator.identityId]);await player(unauthorizedExternal,"합성 일반 사용자");itemId=(await db.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code='ITEM-TERRITORY-ATTACK'"))[0]!.id;const g1=await guild(`${prefix}-g1`,"합성 fund 길드1"),g2=await guild(`${prefix}-g2`,"합성 fund 길드2"),g3=await guild(`${prefix}-g3`,"합성 fund 길드3");for(const [id,value] of [[g1,"100.000"],[g2,"200.000"],[g3,"300.000"]] as const){await db.execute("INSERT INTO guild_resource_accounts(guild_id,currency_code,balance,version) VALUES (?,'point',?,1)",[id,value]);await db.execute("INSERT INTO guild_warehouse_stacks(guild_id,item_id,quantity,version) VALUES (?,?,7,1)",[id,itemId]);}await db.execute("INSERT INTO guild_legacy_fund_cleanup_sources(source_key,guild_id,source_version,row_state,legacy_fund_present,fund_origin_code,legacy_fund_json,non_fund_fields_checksum,version) VALUES ('G1',?,'synthetic-v1','guild',1,'OWN','0',REPEAT('1',64),1),('G2',?,'synthetic-v1','guild',1,'INHERITED',JSON_OBJECT('legacy',TRUE),REPEAT('2',64),1),('G3',?,'synthetic-v1','guild',0,NULL,NULL,REPEAT('3',64),1),('NULL_ROW',NULL,'synthetic-v1','null',0,NULL,NULL,REPEAT('4',64),1)",[g1,g2,g3]);});
  after(async()=>{if(db)await db.close();});
  it("preserves Shadow, permission, exact cleanup, replay, concurrency, rollback and normalized invariants",async()=>{const service=new GuildLegacyFundCleanupService(db),shadow=`${prefix}-shadow`;await event(shadow,operatorExternal);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"}),{status:"shadow"});await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_LEGACY_FUND_CLEANUP'");const changed=`${prefix}-changed`;await event(changed,operatorExternal);const result=await new IrisAdminCommandService(db).changePlayerPoint({eventId:changed,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"});assert.equal(result.status,"changed");const run=(await db.query<Array<{scanned_count:bigint;deleted_count:bigint;skipped_count:bigint}>>("SELECT scanned_count,deleted_count,skipped_count FROM guild_legacy_fund_cleanup_runs WHERE request_key=?",[changed]))[0]!;assert.deepEqual(run,{scanned_count:4n,deleted_count:2n,skipped_count:2n});const sources=await db.query<Array<{source_key:string;legacy_fund_present:number;legacy_fund_json:string|null}>>("SELECT source_key,legacy_fund_present,legacy_fund_json FROM guild_legacy_fund_cleanup_sources ORDER BY source_key");assert.equal(sources.filter(row=>row.legacy_fund_present===1).length,0);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_legacy_fund_cleanup_changes"))[0]!.count_value,2n);assert.equal((await db.query<Array<{total:string}>>("SELECT CAST(SUM(balance) AS CHAR) total FROM guild_resource_accounts"))[0]!.total,"600.000");assert.equal((await db.query<Array<{total:string}>>("SELECT CAST(SUM(quantity) AS CHAR) total FROM guild_warehouse_stacks"))[0]!.total,"21");const replay=await service.execute({eventId:changed,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"});assert.equal(replay.deletedCount,"2");const denied=`${prefix}-denied`;await event(denied,unauthorizedExternal);await assert.rejects(()=>service.execute({eventId:denied,externalUserId:unauthorizedExternal,channelId:room,message:"/길드fund삭제"}),/데이터 정리 권한/);
    await db.execute("UPDATE guild_legacy_fund_cleanup_sources SET legacy_fund_present=1,legacy_fund_json='null',version=version+1,cleaned_at=NULL WHERE source_key='G1'");const same=`${prefix}-same`;await event(same,operatorExternal);const concurrent=await Promise.all([service.execute({eventId:same,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"}),service.execute({eventId:same,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"})]);assert.equal(concurrent[0].auditId,concurrent[1].auditId);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_legacy_fund_cleanup_runs WHERE request_key=?",[same]))[0]!.count_value,1n);
    await db.execute("UPDATE guild_legacy_fund_cleanup_sources SET legacy_fund_present=1,legacy_fund_json='123',version=version+1,cleaned_at=NULL WHERE source_key='G2'");const rollback=`${prefix}-rollback`;await event(rollback,operatorExternal);await db.execute("CREATE TRIGGER fail_guild_fund_cleanup_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='guild.legacy_fund.cleanup' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced guild fund cleanup audit failure'; END IF; END");try{await assert.rejects(()=>service.execute({eventId:rollback,externalUserId:operatorExternal,channelId:room,message:"/길드fund삭제"}),/forced guild fund cleanup audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_guild_fund_cleanup_audit");}assert.equal((await db.query<Array<{present:number}>>("SELECT legacy_fund_present present FROM guild_legacy_fund_cleanup_sources WHERE source_key='G2'"))[0]!.present,1);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_legacy_fund_cleanup_runs WHERE request_key=?",[rollback]))[0]!.count_value,0n);});
});
