import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { GuildSubMasterAssignService } from "../src/guild/guild-sub-master-assign-service.js";

const enabled = process.env.RUN_MARIADB_INTEGRATION === "true";
const required = (name: string): string => process.env[name] ?? "integration-not-configured";

describe("guild sub-master assign MariaDB integration", { skip: !enabled }, () => {
  let db: DatabaseClient; const room = "990000000000330", prefix = `guild-sub-master-${Date.now()}`;
  async function event(id: string, user: string): Promise<void> { await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))", [id,id,room,user]); }
  async function member(guildId: string, externalId: string, name: string, role: string, contribution: bigint): Promise<string> { await db.execute("INSERT INTO players(status,version) VALUES ('active',1)"); const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!.id; await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[id,name]); await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[id,externalId,name]); await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES (?,?,?,UTC_TIMESTAMP(3))",[guildId,id,role]); await db.execute("INSERT INTO guild_member_profile_details(guild_id,player_id,contribution_value,version) VALUES (?,?,?,1)",[guildId,id,contribution]); return id.toString(); }
  async function guild(name: string, suffix: string): Promise<{id:string;actor:string;actorId:string;oldSub:string;oldSubId:string;high:string;highId:string;low:string;lowId:string}> { await db.execute("INSERT INTO guilds(code,display_name,status,mark,version) VALUES (?,?,'active','T',1)",[`${prefix}-${suffix}`,name]); const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM guilds ORDER BY id DESC LIMIT 1"))[0]!.id.toString(); const actor=`${prefix}-${suffix}-actor`,oldSub=`${prefix}-${suffix}-old`,high=`${prefix}-${suffix}-high`,low=`${prefix}-${suffix}-low`; const actorId=await member(id,actor,`${name} 마스터`,"master",0n),oldSubId=await member(id,oldSub,`${name} 기존부마`,"sub_master",1n),highId=await member(id,high,`${name} 공헌100`,"member",100n),lowId=await member(id,low,`${name} 공헌10`,"member",10n); return {id,actor,actorId,oldSub,oldSubId,high,highId,low,lowId}; }
  async function roles(guildId:string): Promise<Array<{player_id:bigint;role_code:string}>> { return db.query("SELECT player_id,role_code FROM guild_members WHERE guild_id=? ORDER BY player_id",[guildId]); }
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});});
  after(async()=>{if(db)await db.close();});
  it("preserves Shadow, authority, ordered one/two selection, replay, concurrency and rollback",async()=>{
    const service=new GuildSubMasterAssignService(db),g1=await guild("합성 부길마길드 1","g1"),shadow=`${prefix}-shadow`;await event(shadow,g1.actor);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:g1.actor,channelId:room,message:"/부길마 3 4"}),{status:"shadow"});
    await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_SUB_MASTER_ASSIGN'");const changed=`${prefix}-changed`;await event(changed,g1.actor);const dispatched=await new IrisAdminCommandService(db).changePlayerPoint({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/부길마 3 4"});assert.equal(dispatched.status,"changed");const afterAssign=await roles(g1.id);assert.equal(afterAssign.find(x=>x.player_id===BigInt(g1.oldSubId))!.role_code,"member");assert.deepEqual(afterAssign.filter(x=>x.role_code==="sub_master").map(x=>x.player_id),[BigInt(g1.highId),BigInt(g1.lowId)]);
    const replay=await service.assign({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/부길마 3 4"});assert.deepEqual(replay.selectedPlayerIds,[g1.highId,g1.lowId]);const denied=`${prefix}-denied`;await event(denied,g1.low);await assert.rejects(()=>service.assign({eventId:denied,externalUserId:g1.low,channelId:room,message:"/부길마 2"}),/길드마스터 또는 관리자/);const master=`${prefix}-master`;await event(master,g1.actor);await assert.rejects(()=>service.assign({eventId:master,externalUserId:g1.actor,channelId:room,message:"/부길마 1"}),/길드마스터는 부길마/);
    const g2=await guild("합성 부길마길드 2","g2"),same=`${prefix}-same`;await event(same,g2.actor);const concurrent=await Promise.all([service.assign({eventId:same,externalUserId:g2.actor,channelId:room,message:"/부길마 3 4"}),service.assign({eventId:same,externalUserId:g2.actor,channelId:room,message:"/부길마 3 4"})]);assert.equal(concurrent[0].auditId,concurrent[1].auditId);assert.equal((await roles(g2.id)).filter(x=>x.role_code==="sub_master").length,2);
    const g3=await guild("합성 부길마길드 3","g3"),rollback=`${prefix}-rollback`;await event(rollback,g3.actor);const beforeRoles=await roles(g3.id);await db.execute("CREATE TRIGGER fail_guild_sub_master_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='guild.sub_master.assign' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced guild sub-master audit failure'; END IF; END");try{await assert.rejects(()=>service.assign({eventId:rollback,externalUserId:g3.actor,channelId:room,message:"/부길마 3 4"}),/forced guild sub-master audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_guild_sub_master_audit");}assert.deepEqual(await roles(g3.id),beforeRoles);const ops=await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[`guild.sub-master:${g3.id}`,rollback]);assert.equal(ops[0]!.count_value,0n);
  });
});
