import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {createDatabaseClient,type DatabaseClient} from "../src/database.js";
import {GuildTerritoryWarFinishService} from "../src/guild/guild-territory-war-finish-service.js";

const enabled=process.env.RUN_MARIADB_INTEGRATION==="true",required=(name:string)=>process.env[name]??"integration-not-configured";
describe("guild territory war finish MariaDB integration",{skip:!enabled},()=>{
  let db:DatabaseClient;const prefix=`territory-finish-${Date.now()}`,room="synthetic-territory-finish-room",external=`${prefix}-operator`,loginId=`${prefix}-login`,guildCode=`SYN-FIN-${Date.now()}`,warKey=`${prefix}-war`;const base=BigInt(Date.now())*1_000n,operatorPlayer=base+1n,ownerPlayer=base+2n,operator=base+3n,guild=base+4n,war=base+5n,startOperation=base+6n;
  async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('2',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,external]);}
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1),(?,'active',1)",[operatorPlayer,ownerPlayer]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,'합성 총괄',0,1),(?,'합성 성주',0,1)",[operatorPlayer,ownerPlayer]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'합성 총괄','linked')",[operatorPlayer,external]);const identity=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[external]))[0]!.id;await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,?,'합성 총괄','synthetic','active')",[operator,loginId]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operator,identity]);await db.execute("INSERT INTO guild_territory_finish_operator_allowlist(operator_id,external_channel_id,active,source_label) VALUES (?,?,TRUE,'synthetic')",[operator,room]);await db.execute("INSERT INTO guilds(id,code,display_name,status,version) VALUES (?,?,'합성 점령길드','active',1)",[guild,guildCode]);await db.execute("INSERT INTO guild_profile_details(guild_id,territory_booster,tax_rate,version) VALUES (?,3,0,1)",[guild]);await db.execute("INSERT INTO operations(id,operation_key,idempotency_scope,idempotency_key,actor_type,source_code,status,created_at,completed_at) VALUES (?,UUID(),'synthetic.start',?,'system','synthetic','completed',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[startOperation,`${prefix}-start`]);await db.execute("INSERT INTO guild_territory_wars(id,war_key,active,lifecycle_state,start_ready,started_at,start_operation_id,rift_event_history_json,version) VALUES (?,?,TRUE,'ACTIVE_READY',TRUE,UTC_TIMESTAMP(3),?,JSON_ARRAY(),1)",[war,warKey,startOperation]);for(let n=1;n<=7;n++)await db.execute("INSERT INTO guild_territory_occupations(war_id,territory_no,territory_name,owner_guild_id,owner_player_id,version) VALUES (?,?,?,?,?,1)",[war,n,`영지${n}`,guild,ownerPlayer]);await db.execute("INSERT INTO guild_territory_start_scopes(scope_code,war_id,version) VALUES ('world',?,1) ON DUPLICATE KEY UPDATE war_id=VALUES(war_id),version=version+1",[war]);await db.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='GUILD_TERRITORY_WAR_FINISH'");});
  after(async()=>{if(db)await db.close();});
  it("settles one generation atomically and replays without duplicate rewards",async()=>{const service=new GuildTerritoryWarFinishService(db),id=`${prefix}-finish`;await event(id);const result=await service.finish({eventId:id,channelId:room,trigger:"manual",operatorId:operator});assert.equal(result.status,"finished");assert.equal(result.occupiedTerritories,7);assert.equal(result.rewardedGuilds,1);const replay=await service.finish({eventId:id,channelId:room,trigger:"manual",operatorId:operator});assert.equal(replay.auditId,result.auditId);const warState=(await db.query<Array<{active:number;lifecycle_state:string;version:bigint}>>("SELECT active,lifecycle_state,version FROM guild_territory_wars WHERE id=?",[war]))[0]!;assert.deepEqual(warState,{active:0,lifecycle_state:"READY",version:2n});const profile=(await db.query<Array<{territory_booster:bigint;tax_rate:string}>>("SELECT territory_booster,CAST(tax_rate AS CHAR) tax_rate FROM guild_profile_details WHERE guild_id=?",[guild]))[0]!;assert.deepEqual(profile,{territory_booster:0n,tax_rate:"15.000"});const resources=await db.query<Array<{currency_code:string;balance:string}>>("SELECT currency_code,CAST(balance AS CHAR) balance FROM guild_resource_accounts WHERE guild_id=? ORDER BY currency_code",[guild]);assert.deepEqual(resources,[{currency_code:"POINT",balance:"2000000000.000"},{currency_code:"diamond",balance:"20.000"}]);assert.equal((await db.query<Array<{score:bigint}>>("SELECT score FROM guild_territory_score_accounts WHERE guild_id=?",[guild]))[0]!.score,100n);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_territory_finish_entries WHERE finish_run_id=(SELECT id FROM guild_territory_finish_runs WHERE war_id=?)",[war]))[0]!.count_value,7n);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_warehouse_ledger WHERE operation_id=(SELECT operation_id FROM guild_territory_finish_runs WHERE war_id=?)",[war]))[0]!.count_value,4n);});
});
