import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { GuildSwordMasterAssignService } from "../src/guild/guild-sword-master-assign-service.js";

const enabled=process.env.RUN_MARIADB_INTEGRATION==="true",required=(name:string):string=>process.env[name]??"integration-not-configured";
describe("guild sword-master assign MariaDB integration",{skip:!enabled},()=>{
  let db:DatabaseClient;const room="990000000000350",prefix=`guild-sword-master-${Date.now()}`;
  async function event(id:string,user:string):Promise<void>{await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('5',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
  async function member(guildId:string,externalId:string,name:string,role:string,contribution:bigint):Promise<string>{await db.execute("INSERT INTO players(status,version) VALUES ('active',1)");const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!.id;await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[id,name]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[id,externalId,name]);await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES (?,?,?,UTC_TIMESTAMP(3))",[guildId,id,role]);await db.execute("INSERT INTO guild_member_profile_details(guild_id,player_id,contribution_value,version) VALUES (?,?,?,1)",[guildId,id,contribution]);return id.toString();}
  async function guild(name:string,suffix:string):Promise<{id:string;actor:string;actorId:string;sub:string;highId:string;midId:string;lowId:string}>{await db.execute("INSERT INTO guilds(code,display_name,status,mark,version) VALUES (?,?,'active','S',1)",[`${prefix}-${suffix}`,name]);const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM guilds ORDER BY id DESC LIMIT 1"))[0]!.id.toString(),actor=`${prefix}-${suffix}-actor`,sub=`${prefix}-${suffix}-sub`;const actorId=await member(id,actor,`${name} 마스터`,"master",0n);await member(id,sub,`${name} 부길마`,"sub_master",1n);const highId=await member(id,`${prefix}-${suffix}-high`,`${name} 공헌100`,"member",100n),midId=await member(id,`${prefix}-${suffix}-mid`,`${name} 공헌50`,"member",50n),lowId=await member(id,`${prefix}-${suffix}-low`,`${name} 공헌10`,"member",10n);return{id,actor,actorId,sub,highId,midId,lowId};}
  async function selected(guildId:string):Promise<string[]>{return(await db.query<Array<{player_id:bigint}>>("SELECT player_id FROM guild_territory_rift_authorizations WHERE guild_id=? AND authority_code='sword_master' AND active=TRUE ORDER BY player_id",[guildId])).map(row=>row.player_id.toString());}
  async function reinforcement(playerId:string):Promise<void>{await db.execute("INSERT INTO player_pets(player_id,display_name,version) VALUES (?,'증원 펫',1)",[playerId]);const pet=(await db.query<Array<{id:bigint}>>("SELECT id FROM player_pets WHERE player_id=?",[playerId]))[0]!.id,skill=(await db.query<Array<{id:bigint}>>("SELECT id FROM skill_definitions WHERE display_name='기사단 증원' AND active=TRUE LIMIT 1"))[0]!.id;await db.execute("INSERT INTO pet_skills(player_pet_id,slot_no,skill_id,level,equipped) VALUES (?,1,?,1,TRUE)",[pet,skill]);}
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});});after(async()=>{if(db)await db.close();});
  it("preserves Shadow, permission, capacity, replacement, replay, concurrency, war lock and rollback",async()=>{
    const service=new GuildSwordMasterAssignService(db),g1=await guild("합성 소드길드 1","g1"),shadow=`${prefix}-shadow`;await event(shadow,g1.actor);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:g1.actor,channelId:room,message:"/소드마스터 3 4 5"}),{status:"shadow"});
    await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_SWORD_MASTER_ASSIGN'");const changed=`${prefix}-changed`;await event(changed,g1.actor);const dispatched=await new IrisAdminCommandService(db).changePlayerPoint({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/소드마스터 3 4 5"});assert.equal(dispatched.status,"changed");assert.deepEqual((await selected(g1.id)).sort(),[g1.highId,g1.midId,g1.lowId].sort());const replay=await service.assign({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/소드마스터 3 4 5"});assert.equal(replay.assignmentCapacity,3);
    const denied=`${prefix}-denied`;await event(denied,`${prefix}-g1-low`);await assert.rejects(()=>service.assign({eventId:denied,externalUserId:`${prefix}-g1-low`,channelId:room,message:"/소드마스터 3 4 5"}),/길드마스터 또는 부길드마스터/);
    const g2=await guild("합성 소드길드 2","g2");await reinforcement(g2.actorId);const same=`${prefix}-same`;await event(same,g2.sub);const concurrent=await Promise.all([service.assign({eventId:same,externalUserId:g2.sub,channelId:room,message:"/소드마스터 2 3 4 5"}),service.assign({eventId:same,externalUserId:g2.sub,channelId:room,message:"/소드마스터 2 3 4 5"})]);assert.equal(concurrent[0].auditId,concurrent[1].auditId);assert.equal((await selected(g2.id)).length,4);const short=`${prefix}-short`;await event(short,g2.actor);await assert.rejects(()=>service.assign({eventId:short,externalUserId:g2.actor,channelId:room,message:"/소드마스터 3 4 5"}),/4명을 지정/);
    await db.execute("INSERT INTO guild_territory_wars(war_key,active,instability_adjust,rift_bias,rift_event_history_json,version) VALUES (?,TRUE,0,0,JSON_ARRAY(),1)",[`${prefix}-war`]);const war=(await db.query<Array<{id:bigint}>>("SELECT id FROM guild_territory_wars WHERE war_key=?",[`${prefix}-war`]))[0]!.id;await db.execute("INSERT INTO guild_territory_ready_guilds(war_id,guild_id,ready) VALUES (?,?,TRUE)",[war,g2.id]);const blocked=`${prefix}-blocked`;await event(blocked,g2.actor);await assert.rejects(()=>service.assign({eventId:blocked,externalUserId:g2.actor,channelId:room,message:"/소드마스터 2 3 4 5"}),/영지전 진행 중/);
    const g3=await guild("합성 소드길드 3","g3"),rollback=`${prefix}-rollback`;await event(rollback,g3.actor);await db.execute("CREATE TRIGGER fail_guild_sword_master_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='guild.sword_master.assign' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced guild sword-master audit failure'; END IF; END");try{await assert.rejects(()=>service.assign({eventId:rollback,externalUserId:g3.actor,channelId:room,message:"/소드마스터 3 4 5"}),/forced guild sword-master audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_guild_sword_master_audit");}assert.deepEqual(await selected(g3.id),[]);const ops=await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[`guild.sword-master:${g3.id}`,rollback]);assert.equal(ops[0]!.count_value,0n);
  });
});
