import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { GuildLeadershipTransferService } from "../src/guild/guild-leadership-transfer-service.js";

const enabled = process.env.RUN_MARIADB_INTEGRATION === "true";
const required = (name: string): string => process.env[name] ?? "integration-not-configured";

describe("guild leadership transfer MariaDB integration", { skip: !enabled }, () => {
  let db: DatabaseClient; const room = "990000000000329", prefix = `guild-transfer-${Date.now()}`;
  async function event(id: string, user: string): Promise<void> { await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))", [id,id,room,user]); }
  async function member(guildId: string, externalId: string, name: string, role: string): Promise<string> { await db.execute("INSERT INTO players(status,version) VALUES ('active',1)"); const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!.id; await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[id,name]); await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[id,externalId,name]); await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES (?,?,?,UTC_TIMESTAMP(3))",[guildId,id,role]); return id.toString(); }
  async function guild(name: string, suffix: string): Promise<{id:string; actor:string; actorId:string; target:string; targetId:string; other:string; otherId:string}> { await db.execute("INSERT INTO guilds(code,display_name,status,mark,version) VALUES (?,?,'active','T',1)",[`${prefix}-${suffix}`,name]); const id=(await db.query<Array<{id:bigint}>>("SELECT id FROM guilds ORDER BY id DESC LIMIT 1"))[0]!.id.toString(); const actor=`${prefix}-${suffix}-actor`,target=`${prefix}-${suffix}-target`,other=`${prefix}-${suffix}-other`; return {id,actor,actorId:await member(id,actor,`${name} 기존마스터`,"master"),target,targetId:await member(id,target,`${name} 새마스터`,"sub_master"),other,otherId:await member(id,other,`${name} 다른회원`,"member")}; }
  async function roles(guildId:string): Promise<Array<{player_id:bigint;role_code:string}>> { return db.query("SELECT player_id,role_code FROM guild_members WHERE guild_id=? ORDER BY player_id",[guildId]); }
  before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});});
  after(async()=>{if(db)await db.close();});
  it("preserves Shadow, authority, one-master transfer, replay, concurrency and rollback",async()=>{
    const service=new GuildLeadershipTransferService(db), g1=await guild("합성 위임길드 1","g1"), shadow=`${prefix}-shadow`; await event(shadow,g1.actor);
    assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:g1.actor,channelId:room,message:"/길드위임 합성 위임길드 1, 합성 위임길드 1 새마스터"}),{status:"shadow"});
    await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_LEADERSHIP_TRANSFER'");
    const changed=`${prefix}-changed`;await event(changed,g1.actor);const result=await new IrisAdminCommandService(db).changePlayerPoint({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/길드위임 합성 위임길드 1, 합성 위임길드 1 새마스터"});assert.equal(result.status,"changed");
    assert.deepEqual(await roles(g1.id),[{player_id:BigInt(g1.actorId),role_code:"member"},{player_id:BigInt(g1.targetId),role_code:"master"},{player_id:BigInt(g1.otherId),role_code:"member"}]);
    const replay=await service.transfer({eventId:changed,externalUserId:g1.actor,channelId:room,message:"/길드위임 합성 위임길드 1, 합성 위임길드 1 새마스터"});assert.equal(replay.masterPlayerId,g1.targetId);
    const denied=`${prefix}-denied`;await event(denied,g1.other);await assert.rejects(()=>service.transfer({eventId:denied,externalUserId:g1.other,channelId:room,message:"/길드위임 합성 위임길드 1, 합성 위임길드 1 다른회원"}),/길드장 또는 관리자/);
    const g2=await guild("합성 위임길드 2","g2"),c1=`${prefix}-c1`,c2=`${prefix}-c2`;await event(c1,g2.actor);await event(c2,g2.actor);const concurrent=await Promise.allSettled([service.transfer({eventId:c1,externalUserId:g2.actor,channelId:room,message:"/길드위임 합성 위임길드 2, 합성 위임길드 2 새마스터"}),service.transfer({eventId:c2,externalUserId:g2.actor,channelId:room,message:"/길드위임 합성 위임길드 2, 합성 위임길드 2 다른회원"})]);assert.equal(concurrent.filter(x=>x.status==="fulfilled").length,1);assert.equal((await roles(g2.id)).filter(x=>x.role_code==="master").length,1);
    const g3=await guild("합성 위임길드 3","g3"),rollback=`${prefix}-rollback`;await event(rollback,g3.actor);const before=await roles(g3.id);await db.execute("CREATE TRIGGER fail_guild_transfer_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='guild.leadership.transfer' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced guild transfer audit failure'; END IF; END");try{await assert.rejects(()=>service.transfer({eventId:rollback,externalUserId:g3.actor,channelId:room,message:"/길드위임 합성 위임길드 3, 합성 위임길드 3 새마스터"}),/forced guild transfer audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_guild_transfer_audit");}assert.deepEqual(await roles(g3.id),before);const ops=await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[`guild.leadership:${g3.id}`,rollback]);assert.equal(ops[0]!.count_value,0n);
  });
});
