import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { HomeBaseballPitchService } from "../src/home/home-baseball-pitch-service.js";

const enabled=process.env.DATABASE_INTEGRATION_ENABLED==="true";
const required=(name:string):string=>process.env[name]??"integration-not-configured";

describe("home baseball pitch MariaDB integration",{skip:!enabled},()=>{
  let database:DatabaseClient;
  const token="home-baseball-pitch-token",roomId="990000000000577",suffix=Date.now().toString(),externalId=`baseball-player-${suffix}`;
  let playerId="";
  before(async()=>{database=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:5,connectTimeoutMs:5_000});await database.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='HOME_BASEBALL_PITCH'");await database.execute("INSERT INTO players(status,version) VALUES ('active',1)");const player=(await database.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!;playerId=player.id.toString();await database.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (?,'합성 타자',1)",[player.id]);await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'합성 타자','linked')",[player.id,externalId]);await database.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES (?,'point',1000,1)",[player.id]);const ball=(await database.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code='ITEM-RWD-014'"))[0]!;await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,?,10,1)",[player.id,ball.id]);});
  after(async()=>{if(!database)return;try{await database.execute("DROP TRIGGER IF EXISTS fail_baseball_outbox");await database.close();}catch(error){const code=typeof error==="object"&&error!==null&&"code" in error?(error as{code?:unknown}).code:undefined;if(code!=="ER_POOL_ALREADY_CLOSED")throw error;}});
  it("routes, rewards stable objects, replays, shadows and rolls back",async()=>{const replies:Array<{room:string;data:string}>=[];const config=loadConfig({NODE_ENV:"test",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"baseball-pitch-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});process.env.HOME_BASEBALL_PITCH_COMMAND_ENABLED="true";process.env.PARTIAL_COMMAND_DISPATCH_ENABLED="true";const app=buildApp(config,{database,inspectIrisChannel:async()=>({mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}),sendIrisTextReply:async reply=>{replies.push(reply);}});const eventId=`baseball-app-${Date.now()}`,payload={msg:"/투수던집니다",room:"고도화운영테스트방",sender:"합성 타자",json:{_id:eventId,chat_id:roomId,user_id:externalId}};const active=await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload});assert.equal(active.statusCode,202,active.body);assert.equal(replies.length,2);assert.match(replies[0]!.data,/투수 던집니다/);assert.match(replies[1]!.data,/기본 지급 아이템/);
    const prepare=async(id:string)=>database.execute("INSERT INTO event_inbox(event_id,provider_code,provider_event_id,event_kind,event_origin,direction,payload_hash,parse_status,processing_status,received_at) VALUES (?,'iris',?,'message','test','incoming',REPEAT('b',64),'parsed','processing',UTC_TIMESTAMP(3))",[id,id]);const service=new HomeBaseballPitchService(database,()=>0);const directId=`baseball-direct-${Date.now()}`;await prepare(directId);const direct=await service.execute({eventId:directId,externalUserId:externalId,destinationId:roomId,message:"/투수던집니다 2"});assert.equal(direct.status,"applied");assert.equal(direct.counts.grandSlam,"2");assert.equal(direct.pointReward,"20000000000");const titles=await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM player_title_instances WHERE player_id=?",[playerId]);assert.equal(Number(titles[0]!.count_value),2);const replay=await service.execute({eventId:directId,externalUserId:externalId,destinationId:roomId,message:"/투수던집니다 2"});assert.equal(replay.replayed,true);const titlesAfter=await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM player_title_instances WHERE player_id=?",[playerId]);assert.equal(Number(titlesAfter[0]!.count_value),2);
    await database.execute("UPDATE command_registry SET rollout_state='SHADOW' WHERE command_code='HOME_BASEBALL_PITCH'");const beforeShadow=Number((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM baseball_pitch_operations"))[0]!.count_value);await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{...payload,json:{...payload.json,_id:`baseball-shadow-${Date.now()}`}}});const afterShadow=Number((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM baseball_pitch_operations"))[0]!.count_value);assert.equal(afterShadow,beforeShadow);
    await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='HOME_BASEBALL_PITCH'");const rollbackId=`baseball-rollback-${Date.now()}`;await prepare(rollbackId);const before=await database.query<Array<{quantity:bigint}>>("SELECT stack.quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='ITEM-RWD-014'",[playerId]);await database.execute("CREATE TRIGGER fail_baseball_outbox BEFORE INSERT ON outbox_messages FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic baseball outbox failure'");await assert.rejects(()=>service.execute({eventId:rollbackId,externalUserId:externalId,destinationId:roomId,message:"/투수던집니다"}),/synthetic baseball outbox failure/);await database.execute("DROP TRIGGER fail_baseball_outbox");const after=await database.query<Array<{quantity:bigint}>>("SELECT stack.quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='ITEM-RWD-014'",[playerId]);assert.equal(after[0]!.quantity.toString(),before[0]!.quantity.toString());const rollbackOp=await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM operations WHERE idempotency_scope='home.baseball.pitch' AND idempotency_key=?",[rollbackId]);assert.equal(Number(rollbackOp[0]!.count_value),0);delete process.env.HOME_BASEBALL_PITCH_COMMAND_ENABLED;await app.close();});
});
