import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { HomeProfileViewService } from "../src/home/home-profile-view-service.js";

const enabled=process.env.DATABASE_INTEGRATION_ENABLED==="true",required=(n:string)=>process.env[n]??"integration-not-configured";
describe("home profile view MariaDB integration",{skip:!enabled},()=>{let db:DatabaseClient;let actor:bigint,target:bigint;const suffix=Date.now().toString(),external=`profile-actor-${suffix}`,targetName=`프로필 대상 ${suffix}`,room="990000000000619";const open=()=>createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:5,connectTimeoutMs:5000});const event=async(id:string)=>db.execute("INSERT INTO event_inbox(event_id,provider_code,provider_event_id,event_kind,event_origin,direction,payload_hash,parse_status,processing_status,received_at) VALUES (?,'iris',?,'message','test','incoming',REPEAT('6',64),'parsed','processing',UTC_TIMESTAMP(3))",[id,id]);
before(async()=>{db=open();for(const [name,ext]of[[`프로필 사용자 ${suffix}`,external],[targetName,`profile-target-${suffix}`]]){const p=await db.execute("INSERT INTO players(status,version) VALUES('active',1)");await db.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES(?,?,1)",[p.insertId,name]);await db.execute("INSERT INTO player_homes(player_id,display_name,base_experience,floor_area,version) VALUES (?,?,10,20,1)",[p.insertId,`${name}의 집`]);await db.execute("INSERT INTO player_pets(player_id,display_name,version) VALUES(?,?,1)",[p.insertId,`${name}의 펫`]);await db.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES(?,'support',TRUE,TRUE)",[p.insertId]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES(?,'kakao',?,?,'linked')",[p.insertId,ext,name]);if(ext===external)actor=p.insertId;else target=p.insertId;}const def=await db.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES(?,?,3,TRUE)",[`profile-chair-${suffix}`,"합성 의자"]);await db.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,status) VALUES(?,?,3,'placed')",[target,def.insertId]);await db.execute("INSERT INTO home_feeds(home_player_id,feed_key,content,display_order,created_at_ms,source_code) VALUES(?,?,'합성 피드',1,1,'test')",[target,`profile-feed-${suffix}`]);const comment=await db.execute("INSERT INTO home_comments(home_player_id,author_player_id,body) VALUES(?,?,'합성 댓글')",[target,actor]);await db.execute("INSERT INTO home_comment_pins(pin_id,home_player_id,comment_id,display_order) VALUES(?,?,?,1)",[ `profile-pin-${suffix}`,target,comment.insertId]);});
after(async()=>{if(db){try{await db.execute("DROP TRIGGER IF EXISTS fail_profile_outbox");await db.close();}catch{}}});
it("projects, visits, replays, rolls back and reconnects",async()=>{const service=()=>new HomeProfileViewService(db),selfId=`profile-self-${suffix}`;await event(selfId);const self=await service().execute({eventId:selfId,externalUserId:external,destinationId:room,message:"/펫홈"});assert.equal(self.selfView,true);assert.equal(self.visitCount,"0");const visitId=`profile-visit-${suffix}`;await event(visitId);const visited=await service().execute({eventId:visitId,externalUserId:external,destinationId:room,message:`/펫홈 ${targetName}`});assert.equal(visited.messages.length,3);assert.equal(visited.visitCount,"1");const replay=await service().execute({eventId:visitId,externalUserId:external,destinationId:room,message:`/펫홈 ${targetName}`});assert.equal(replay.replayed,true);assert.equal((await db.query<Array<{visit_count:bigint}>>("SELECT visit_count FROM player_homes WHERE player_id=?",[target]))[0]!.visit_count,1n);assert.equal((await db.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM pet_home_recent_visitors WHERE owner_player_id=?",[target]))[0]!.count,1n);assert.equal((await db.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM pet_home_activity_alerts WHERE owner_player_id=? AND alert_type='home_visit'",[target]))[0]!.count,1n);const rollbackId=`profile-rollback-${suffix}`;await event(rollbackId);await db.execute("CREATE TRIGGER fail_profile_outbox BEFORE INSERT ON outbox_messages FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic profile rollback'");await assert.rejects(()=>service().execute({eventId:rollbackId,externalUserId:external,destinationId:room,message:`/펫홈 ${targetName}`}),/synthetic profile rollback/);await db.execute("DROP TRIGGER fail_profile_outbox");assert.equal((await db.query<Array<{visit_count:bigint}>>("SELECT visit_count FROM player_homes WHERE player_id=?",[target]))[0]!.visit_count,1n);assert.equal(await db.verifyRollback(),true);await db.close();db=open();assert.equal((await service().execute({eventId:visitId,externalUserId:external,destinationId:room,message:`/펫홈 ${targetName}`})).replayed,true);});});
