import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";

const enabled=process.env.DATABASE_INTEGRATION_ENABLED==="true",required=(n:string)=>process.env[n]??"integration-not-configured";
describe("home profile view SHADOW routing",{skip:!enabled},()=>{let db:DatabaseClient;const suffix=Date.now().toString(),external=`profile-shadow-${suffix}`,token="home-profile-shadow-token",room="990000000000620";
before(async()=>{db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:3,connectTimeoutMs:5000});const p=await db.execute("INSERT INTO players(status,version) VALUES('active',1)");await db.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (?,'SHADOW 사용자',1)",[p.insertId]);await db.execute("INSERT INTO player_homes(player_id,display_name,version) VALUES (?,'SHADOW 집',1)",[p.insertId]);await db.execute("INSERT INTO player_pets(player_id,display_name,version) VALUES (?,'SHADOW 펫',1)",[p.insertId]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'SHADOW 사용자','linked')",[p.insertId,external]);await db.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=TRUE WHERE command_code='HOME_PROFILE_VIEW'");});
after(async()=>{if(db)try{await db.close();}catch{}});
it("observes the command without profile mutation",async()=>{const beforeCount=(await db.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM operations WHERE idempotency_scope='home.profile_view'"))[0]!.count;const config=loadConfig({NODE_ENV:"test",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"home-profile-shadow-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});process.env.HOME_PROFILE_VIEW_COMMAND_ENABLED="true";process.env.PARTIAL_COMMAND_DISPATCH_ENABLED="true";const app=buildApp(config,{database:db,inspectIrisChannel:async()=>({mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}),sendIrisTextReply:async()=>{}});await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:"/펫홈",room:"고도화펫테스트방",sender:"SHADOW 사용자",json:{_id:`profile-shadow-event-${suffix}`,chat_id:room,user_id:external}}});assert.equal((await db.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM operations WHERE idempotency_scope='home.profile_view'"))[0]!.count,beforeCount);delete process.env.HOME_PROFILE_VIEW_COMMAND_ENABLED;await app.close();});});
