import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { calculateMatzangDiagnostic,formatMatzangTimeCheck,isMatzangTimeCheckCommandCandidate,parseMatzangTimeCheckCommand } from "../src/admin/matzang-time-check-service.js";

describe("matzang time check boundary",()=>{
  it("preserves usage and nickname command forms",()=>{assert.equal(isMatzangTimeCheckCommandCandidate("/맞짱시간체크"),true);assert.equal(parseMatzangTimeCheckCommand("/맞짱시간체크"),null);assert.deepEqual(parseMatzangTimeCheckCommand("/맞짱시간체크 합성 회원"),{targetName:"합성 회원"});assert.equal(isMatzangTimeCheckCommandCandidate("/맞짱시간체크안내"),false);});
  it("keeps legacy diagnostic math without castle/raid cube, tier skill or raid intimacy",()=>{const result=calculateMatzangDiagnostic({pet_experience:100n,pet_enhancement:10n,mini_grade:"창조",mini_raid:20n,mini_castle:30n,home_charm:1000n,arcana_count:5n,royal_placed_count:10n,intimacy_charm:500n,elemental_raid:40n,elemental_castle:50n,pendant_raid:60n,pendant_castle:70n,ring_raid:11n,ring_castle:13n,cube_castle:"0",cube_raid:"0",cube_pet_upgrade:"50",cube_explore:"0",premium_active:0n,attack_raid:999999n,attack_castle:200n,raid_bag:80n},[{rule_code:"overall-interior-master",display_name:"인테리어 장인",raid_charm:0n,castle_charm:0n,condition_code:null,condition_threshold:0n,home_charm_percent:"10"},{rule_code:"overall-creation-forest",display_name:"창조림",raid_charm:500000n,castle_charm:500000n,condition_code:"CREATION_MINI_PET",condition_threshold:1n,home_charm_percent:"0"},{rule_code:"overall-tier-phoenix",display_name:"티어",raid_charm:25000000n,castle_charm:25000000n,condition_code:null,condition_threshold:0n,home_charm_percent:"0"}]);assert.equal(result.castleEquipment,133n);assert.equal(result.raidEquipment,191n);assert.equal(result.castleTotal,502063n);assert.equal(result.raidTotal,501411n);assert.equal(result.upgradeBonus,15000n);assert.equal(result.total,1018474n);});
  it("applies full-cube 1.1 rounding, premium five points and all legacy elite labels",()=>{for(const mini_grade of["엘리트","엘리트급","ELITE"]){const result=calculateMatzangDiagnostic({pet_experience:0n,pet_enhancement:10n,mini_grade,mini_raid:0n,mini_castle:0n,home_charm:0n,arcana_count:0n,royal_placed_count:0n,intimacy_charm:0n,elemental_raid:0n,elemental_castle:0n,pendant_raid:0n,pendant_castle:0n,ring_raid:0n,ring_castle:0n,cube_castle:"20",cube_raid:"20",cube_pet_upgrade:"50",cube_explore:"10",premium_active:1n,attack_raid:0n,attack_castle:7n,raid_bag:0n},[{rule_code:"elite",display_name:"엘리트 박사",raid_charm:3n,castle_charm:4n,condition_code:"ELITE_MINI_PET",condition_threshold:1n,home_charm_percent:"0"}]);assert.equal(result.castleAttackItem,7n);assert.equal(result.castleSkill,4n);assert.equal(result.raidSkill,3n);assert.equal(result.upgradeBonus,16000n);assert.equal(result.total,16014n);}});
  it("renders exact fold headings and hides zero millisecond detail",()=>{const components={castleAttackItem:1n,castleEquipment:2n,castlePet:3n,castleMiniPet:4n,castleHome:5n,castleIntimacy:6n,castleSkill:7n,raidEquipment:8n,raidPet:9n,raidMiniPet:10n,raidHome:11n,raidSkill:12n,upgradeBonus:13n,castleTotal:28n,raidTotal:50n,total:91n};const data=formatMatzangTimeCheck({displayName:"🥇합성",totalCharm:"91",components},{total:8,branch:7,homeLoad:2,calculation:4,common:[{label:"member.json 로드",ms:0}],detail:[{label:"캐슬-공격아이템",value:1n,ms:0},{label:"레이드-펫스킬",value:12n,ms:4}]});assert.match(data,/종합매력: 91💕/);assert.match(data,new RegExp(`응답 공통 처리📋${"\u200b".repeat(500)}`));assert.match(data,new RegExp(`세부 계산📋${"\u200b".repeat(500)}`));assert.match(data,/레이드-펫스킬: 12💕 \/ 4ms/);assert.doesNotMatch(data,/캐슬-공격아이템: 1💕/);assert.match(data,/전투\/상대선정\/저장은 실행하지 않았습니다/);});
});
