import assert from "node:assert/strict";
import{describe,it}from"node:test";
import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";
import{isMemberCharacterCountCommand,MemberCharacterCountService,type MemberCharacterCountResult}from"../src/admin/member-character-count-service.js";
function scripted(results:unknown[]){const remaining=[...results],sql:string[]=[];let id=400n;const transaction:DatabaseTransaction={query:async<T>(statement:string):Promise<T>=>{sql.push(statement);return remaining.shift() as T;},execute:async(statement:string):Promise<DatabaseWriteResult>=>{sql.push(statement);id+=1n;return{affectedRows:1n,insertId:id};}};const database:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw new Error("unexpected query");},execute:async()=>{throw new Error("unexpected execute");},withTransaction:async<T>(work:(value:DatabaseTransaction)=>Promise<T>)=>work(transaction),close:async()=>undefined};return{database,sql};}
describe("member character count",()=>{
  it("accepts only the exact command",()=>{assert.equal(isMemberCharacterCountCommand("/멤버글자수"),true);assert.equal(isMemberCharacterCountCommand("/멤버글자수 해봐"),false);assert.equal(isMemberCharacterCountCommand("/펫멤버글자수"),false);});
  it("queues the stored member UTF-16 count",async()=>{const s=scripted([[],[{utf16_character_count:1234567n,content_sha256:"a".repeat(64),source_version:"fixture"}]]);const result=await new MemberCharacterCountService(s.database).count({idempotencyKey:"event",sourceEventId:"event",destinationId:"room",identityId:"9"});assert.equal(result.data,"총 글자 수 : 1,234,567");assert.equal(s.sql.filter(x=>x.includes("INSERT INTO outbox_messages")).length,1);assert.equal(s.sql.some(x=>x.includes("UPDATE player_")||x.includes("DELETE ")),false);});
  it("records no reply when the member snapshot is absent",async()=>{const s=scripted([[],[]]);const result=await new MemberCharacterCountService(s.database).count({idempotencyKey:"missing",sourceEventId:"missing",destinationId:"room",identityId:"9"});assert.equal(result.status,"missing");assert.equal(result.data,null);assert.equal(s.sql.some(x=>x.includes("INSERT INTO outbox_messages")),false);});
  it("replays without another snapshot read",async()=>{const prior:MemberCharacterCountResult={status:"counted",characterCount:"10",data:"총 글자 수 : 10",outboxId:"1",auditId:"2"},s=scripted([[{result_json:JSON.stringify(prior)}]]);assert.deepEqual(await new MemberCharacterCountService(s.database).count({idempotencyKey:"same",sourceEventId:"same",destinationId:"room",identityId:"9"}),prior);assert.equal(s.sql.some(x=>x.includes("pet_member_storage_snapshots")),false);});
});
