import assert from "node:assert/strict";
import {describe,it} from "node:test";
import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";
import{ApplicationError}from"../src/shared/application-error.js";
import{isMiniPetTitleSaleCommand,MiniPetTitleSaleService}from"../src/mini-pet/title-sale-service.js";
function scripted(results:unknown[]){const queue=[...results],sql:string[]=[];let insertId=200n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);return(queue.shift()??[])as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);insertId++;return{affectedRows:1n,insertId};}};return{sql,database:{ping:async()=>undefined,verifyRollback:async()=>true,query:tx.query,execute:tx.execute,withTransaction:async<T>(work:(v:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined}as DatabaseClient};}
const command={externalUserId:"seller",channelId:"room",eventId:"sale-event",message:"/미니펫타이틀판매 1",environmentCode:"dev"as const};
const first={title_id:10n,stable_owned_title_id:"00000000-0000-0000-0000-000000000010",display_order:1,display_name:"첫째",sale_price:"5000.000",selected:0};
const second={title_id:11n,stable_owned_title_id:"00000000-0000-0000-0000-000000000011",display_order:2,display_name:"둘째",sale_price:"7000.000",selected:1};
describe("mini-pet title sale",()=>{
 it("accepts only one complete positive title index",()=>{assert.equal(isMiniPetTitleSaleCommand("/미니펫타이틀판매 1"),true);for(const value of ["/미니펫타이틀판매","/미니펫타이틀판매 0","/미니펫타이틀판매 1 설명"])assert.equal(isMiniPetTitleSaleCommand(value),false);});
 it("sells the locked stable title and credits point atomically",async()=>{const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[first,second],[{balance:"1000.000",version:2n}]]);const result=await new MiniPetTitleSaleService(s.database).execute(command);assert.equal(result.status,"sold");assert.equal(result.stableOwnedTitleId,first.stable_owned_title_id);assert.equal(result.selectedStableOwnedTitleId,second.stable_owned_title_id);assert.equal(result.pointBalance,"6000");for(const token of ["DELETE FROM mini_pet_title_owned_states","currency_ledger","mini_pet_title_sale_events","command_audit","outbox_messages"])assert.equal(s.sql.some(x=>x.includes(token)),true);});
 it("blocks the selected title before operation or currency access",async()=>{const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[{...first,selected:1}]]);const result=await new MiniPetTitleSaleService(s.database).execute(command);assert.equal(result.status,"sale_blocked");assert.equal(s.sql.some(x=>x.includes("INSERT INTO operations")),false);});
 it("rejects malformed or fractional price snapshots without mutation",async()=>{for(const price of ["NaN","-1.000","1.500"]){const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[{...first,sale_price:price}]]);await assert.rejects(()=>new MiniPetTitleSaleService(s.database).execute(command),(e:unknown)=>e instanceof ApplicationError&&e.statusCode===409);assert.equal(s.sql.some(x=>x.includes("INSERT INTO operations")),false);}});
 it("replays the prior stable sale before selecting a newly compacted index",async()=>{const prior={status:"sold"as const,stableOwnedTitleId:first.stable_owned_title_id,pointBalance:"6000"};const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[{result_json:prior}]]);const result=await new MiniPetTitleSaleService(s.database).execute(command);assert.equal(result.replayed,true);assert.equal(s.sql.some(x=>x.includes("mini_pet_title_owned_states state")),false);});
 it("requires contiguous title order before sale",async()=>{const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[{...first,display_order:2}]]);const result=await new MiniPetTitleSaleService(s.database).execute(command);assert.equal(result.status,"snapshot_required");assert.equal(s.sql.some(x=>x.includes("INSERT INTO operations")),false);});
});
