import assert from "node:assert/strict";
import {describe,it} from "node:test";
import type {DatabaseClient,DatabaseTransaction,DatabaseWriteResult} from "../src/database.js";
import {ApplicationError} from "../src/shared/application-error.js";
import {isMiniPetTitleSelectCommand,MiniPetTitleSelectService} from "../src/mini-pet/title-select-service.js";
function scripted(results:unknown[]){const queue=[...results],sql:string[]=[];let insertId=90n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);return(queue.shift()??[])as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);insertId++;return{affectedRows:1n,insertId};}};return{sql,database:{ping:async()=>undefined,verifyRollback:async()=>true,query:tx.query,execute:tx.execute,withTransaction:async<T>(work:(v:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined}as DatabaseClient};}
const command={externalUserId:"title-user",channelId:"title-room",eventId:"title-event",message:"/미니펫타이틀 2",environmentCode:"dev"as const};
const titles=[{title_id:10n,stable_owned_title_id:"00000000-0000-0000-0000-000000000010",display_order:1,display_name:"첫째",equipped:1},{title_id:11n,stable_owned_title_id:"00000000-0000-0000-0000-000000000011",display_order:2,display_name:"둘째",equipped:0}];
describe("mini-pet title select",()=>{
 it("accepts only one positive integer and rejects zero before DB",async()=>{assert.equal(isMiniPetTitleSelectCommand("/미니펫타이틀 1"),true);assert.equal(isMiniPetTitleSelectCommand("/미니펫타이틀 0"),false);assert.equal(isMiniPetTitleSelectCommand("/미니펫타이틀 1 설명"),false);await assert.rejects(()=>new MiniPetTitleSelectService(scripted([]).database).execute({...command,message:"/미니펫타이틀 0"}),(e:unknown)=>e instanceof ApplicationError&&e.statusCode===422);});
 it("selects the locked stable owned title and keeps one compatibility flag",async()=>{const s=scripted([[{environment_code:"dev"}],[{identity_id:1n,player_id:2n}],[],titles,[{title_id:10n,version:1n}]]);const result=await new MiniPetTitleSelectService(s.database).execute(command);assert.equal(result.status,"selected");assert.equal(result.titleId,"11");assert.equal(result.stableOwnedTitleId,titles[1]!.stable_owned_title_id);for(const x of ["mini_pet_title_selections","UPDATE player_titles","mini_pet_title_selection_events","outbox_messages"])assert.equal(s.sql.some(q=>q.includes(x)),true);});
 it("returns snapshot-required for missing or noncontiguous owned ordering",async()=>{const s=scripted([[{environment_code:"dev"}],[{identity_id:1n,player_id:2n}],[],[{...titles[0],display_order:2}]]);const result=await new MiniPetTitleSelectService(s.database).execute({...command,message:"/미니펫타이틀 1"});assert.equal(result.status,"snapshot_required");assert.equal(s.sql.some(q=>q.includes("INSERT INTO operations")),false);});
 it("rejects an out-of-range positive index without mutation",async()=>{const s=scripted([[{environment_code:"dev"}],[{identity_id:1n,player_id:2n}],[],titles]);await assert.rejects(()=>new MiniPetTitleSelectService(s.database).execute({...command,message:"/미니펫타이틀 3"}),/보유한/);assert.equal(s.sql.some(q=>q.includes("INSERT INTO operations")),false);});
 it("replays the prior event without selecting a newly reordered row",async()=>{const prior={status:"selected"as const,titleId:"11",stableOwnedTitleId:titles[1]!.stable_owned_title_id,selectedIndex:2};const s=scripted([[{environment_code:"dev"}],[{identity_id:1n,player_id:2n}],[{result_json:prior}]]);const result=await new MiniPetTitleSelectService(s.database).execute(command);assert.equal(result.replayed,true);assert.equal(s.sql.some(q=>q.includes("mini_pet_title_owned_states state")),false);});
});
