import assert from "node:assert/strict";
import { describe,it } from "node:test";
import type { DatabaseClient,DatabaseTransaction,DatabaseWriteResult } from "../src/database.js";
import { MiniPetUpgradeService,isMiniPetUpgradeCommand,parseMiniPetUpgradeCommand,resolveMiniPetUpgradeAttempt } from "../src/mini-pet/mini-pet-upgrade-service.js";

function scriptedDatabase(queryResults:unknown[]){const remaining=[...queryResults],sql:string[]=[];let id=700n;const tx:DatabaseTransaction={query:async<T>(statement:string):Promise<T>=>{sql.push(statement);if(remaining.length===0)throw new Error(`Unexpected query: ${statement}`);return remaining.shift() as T;},execute:async(statement:string):Promise<DatabaseWriteResult>=>{sql.push(statement);id+=1n;return{affectedRows:1n,insertId:id};}};const database:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw new Error("Unexpected query");},execute:async()=>{throw new Error("Unexpected execute");},withTransaction:async<T>(work:(value:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined};return{database,sql};}
const owner={identity_id:11n,player_id:21n,display_name:"합성회원"};
const pet={id:31n,custom_name:null,custom_emoji:null,display_name:"합성미니",emoji_value:"🐹",grade_display_name:"일반",enhancement_level:0n,battle_experience:100n,castle_experience:200n,raid_experience:300n,version:1n};

describe("mini pet upgrade",()=>{
  it("accepts only the exact command boundary and caps the second argument",()=>{for(const value of ["/미니펫강화","/미니펫강화 0","/미니펫강화 3 101"])assert.equal(isMiniPetUpgradeCommand(value),true);for(const value of ["/미니펫강화 ","/미니펫강화 -1","/미니펫강화 1 2 해봐",undefined])assert.equal(isMiniPetUpgradeCommand(value),false);assert.deepEqual(parseMiniPetUpgradeCommand("/미니펫강화 3 101"),{targetBagSequence:3n,count:100,capped:true});assert.deepEqual(parseMiniPetUpgradeCommand("/미니펫강화 0 0"),{targetBagSequence:0n,count:0,capped:false});});
  it("adds the dog-master and highest boost rate before one captured roll",()=>{const result=resolveMiniPetUpgradeAttempt({baseRate:0.2,skillBonusRate:0.05,boostRate:0.8,random:()=>0.999});assert.deepEqual(result,{baseRate:0.2,skillBonusRate:0.05,boostRate:0.8,effectiveRate:1,successRoll:0.999,success:true});});
  it("keeps one stable owned ID and mutates currency, inventory, three charms and evidence atomically",async()=>{const stone={item_id:41n,code:"mini_pet_enhance_stone",display_name:"미니펫 강화석💫",quantity:10n,version:1n},boost={item_id:42n,code:"ITEM-RWD-019",display_name:"미니펫강화확률UP🐷(30%)",quantity:2n,version:1n};const scripted=scriptedDatabase([[],[owner],[],[pet],[{base_rate:"0.870915",max_level:300n,success_charm_delta:10000n}],[{min_target_level:1n,max_target_level:100n,point_cost:"10000000.000"}],[{balance:"100000000.000",version:1n}],[stone],[boost],[{bonus_pct:"5"}]]);const result=await new MiniPetUpgradeService(scripted.database,()=>0.5).handle({eventId:"upgrade-1",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫강화"});assert.deepEqual({status:result.status,id:result.ownedMiniPetId,level:result.level,point:result.pointSpent,stone:result.stoneSpent,boost:result.boostSpent},{status:"applied",id:"31",level:"1",point:"10000000",stone:"1",boost:1});for(const fragment of ["UPDATE currency_accounts","UPDATE inventory_stacks","UPDATE owned_mini_pets SET enhancement_level","INSERT INTO currency_ledger","INSERT INTO inventory_ledger","INSERT INTO mini_pet_upgrade_attempts","INSERT INTO command_executions","INSERT INTO command_audit","INSERT INTO outbox_messages"])assert.ok(scripted.sql.some(statement=>statement.includes(fragment)),fragment);});
  it("returns a stored event without a second resource lookup",async()=>{const stored={status:"applied" as const,ownedMiniPetId:"31",data:"stored",outboxId:"9",auditId:"10"};const scripted=scriptedDatabase([[],[owner],[{result_json:stored}]]);const result=await new MiniPetUpgradeService(scripted.database).handle({eventId:"same",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫강화"});assert.equal(result.replayed,true);assert.equal(scripted.sql.some(statement=>statement.includes("inventory_stacks")),false);});
  it("stays silent during an active siege before identity or mutation",async()=>{const scripted=scriptedDatabase([[{active:1}]]);assert.deepEqual(await new MiniPetUpgradeService(scripted.database).handle({eventId:"siege",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫강화"}),{status:"silent"});assert.equal(scripted.sql.some(statement=>statement.includes("external_identities")),false);});
});
