import assert from "node:assert/strict";
import { describe,it } from "node:test";
import type { DatabaseClient,DatabaseTransaction,DatabaseWriteResult } from "../src/database.js";
import { MiniPetEliteCombineService,isMiniPetEliteCombineCandidate,normalizeMiniPetEliteCombineDispatchMessage,parseMiniPetEliteCombineCommand,resolveMiniPetEliteCombineRoll } from "../src/mini-pet/mini-pet-elite-combine-service.js";

function scriptedDatabase(queryResults:unknown[]){const remaining=[...queryResults],sql:string[]=[];let id=800n;const tx:DatabaseTransaction={query:async<T>(statement:string):Promise<T>=>{sql.push(statement);if(remaining.length===0)throw new Error(`Unexpected query: ${statement}`);return remaining.shift() as T;},execute:async(statement:string):Promise<DatabaseWriteResult>=>{sql.push(statement);id+=1n;return{affectedRows:statement.includes("DELETE FROM owned_mini_pets")?2n:1n,insertId:id};}};const database:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw new Error("Unexpected query");},execute:async()=>{throw new Error("Unexpected execute");},withTransaction:async<T>(work:(value:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined};return{database,sql};}
const owner={identity_id:11n,player_id:21n,display_name:"합성회원"},recipe={id:31n,recipe_version:1,point_cost:"35000000000.000",success_rate:"0.10000000000000000",material_grade_name:"창조",material_min_enhancement:300n,excluded_material_name:"컬렉션창조 미니펫"};
const material=(id:bigint,sequence:bigint)=>({id,definition_id:id+100n,display_name:`재료${id}`,grade_display_name:"창조",enhancement_level:300n,bag_sequence:sequence,version:1n,reserved:0,protected_ref:0,pending_equip:0});
const reward={pool_sequence:1,definition_id:501n,display_name:"아프간 하운드",emoji_value:"𓂀",sale_price:"10000000000.000",battle_experience:63500n,castle_experience:63500n,raid_experience:63500n};

describe("mini pet elite combine",()=>{
  it("keeps the legacy outer guard but parses only two distinct uint64 indexes",()=>{assert.equal(isMiniPetEliteCombineCandidate("/미니펫조합엘리트 1 2"),true);assert.equal(isMiniPetEliteCombineCandidate("/미니펫조합엘리트abc 1 2"),false);assert.deepEqual(parseMiniPetEliteCombineCommand("/미니펫조합엘리트 1 2"),{firstIndex:1n,secondIndex:2n});for(const value of ["/미니펫조합엘리트","/미니펫조합엘리트 1 1","/미니펫조합엘리트 0 2","/미니펫조합엘리트 1 2 해봐"])assert.equal(parseMiniPetEliteCombineCommand(value),null);assert.equal(normalizeMiniPetEliteCombineDispatchMessage("/미니펫조합엘리트 1 2"),"/미니펫조합엘리트");});
  it("captures one success roll and a second uniform reward roll only after success",()=>{assert.deepEqual(resolveMiniPetEliteCombineRoll({successRate:0.1,rewardCount:12,random:(()=>{const values=[0.1];return()=>values.shift()!;})()}),{successRoll:0.1,success:false,rewardRoll:null,rewardIndex:null});const values=[0.01,0.5];assert.deepEqual(resolveMiniPetEliteCombineRoll({successRate:0.1,rewardCount:12,random:()=>values.shift()!}),{successRoll:0.01,success:true,rewardRoll:0.5,rewardIndex:6});});
  it("debits point, consumes two stable materials, grants one reward and records evidence atomically",async()=>{const scripted=scriptedDatabase([[owner],[{id:41n,result_json:null}],[recipe],[{balance:"100000000000.000",version:1n}],[material(61n,1n),material(62n,2n)],[reward],[]]);const values=[0.01,0];const result=await new MiniPetEliteCombineService(scripted.database,()=>values.shift()!).handle({eventId:"elite-success",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫조합엘리트 1 2"});assert.equal(result.status,"success");assert.equal(result.pointBalanceAfter,"65000000000");for(const fragment of ["UPDATE currency_accounts","INSERT INTO currency_ledger","DELETE FROM owned_mini_pets","INSERT INTO owned_mini_pets","INSERT INTO mini_pet_elite_combine_events","INSERT INTO command_executions","INSERT INTO command_audit","INSERT INTO outbox_messages"])assert.ok(scripted.sql.some(statement=>statement.includes(fragment)),fragment);});
  it("charges a failed roll while preserving both material rows",async()=>{const scripted=scriptedDatabase([[owner],[{id:41n,result_json:null}],[recipe],[{balance:"100000000000.000",version:1n}],[material(61n,1n),material(62n,2n)],[reward]]);const result=await new MiniPetEliteCombineService(scripted.database,()=>0.5).handle({eventId:"elite-fail",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫조합엘리트 1 2"});assert.equal(result.status,"failed");assert.equal(scripted.sql.some(statement=>statement.includes("DELETE FROM owned_mini_pets")),false);assert.ok(scripted.sql.some(statement=>statement.includes("UPDATE currency_accounts")));});
  it("replays a stored result before recipe, currency, pet or RNG lookup",async()=>{const stored={status:"success" as const,data:"stored",outboxId:"9",auditId:"10"};const scripted=scriptedDatabase([[owner],[{id:41n,result_json:stored}]]);const result=await new MiniPetEliteCombineService(scripted.database,()=>{throw new Error("rng should not run");}).handle({eventId:"same",externalUserId:"kakao-1",destinationId:"room-1",message:"/미니펫조합엘리트 1 2"});assert.equal(result.replayed,true);assert.equal(scripted.sql.some(statement=>statement.includes("mini_pet_elite_combine_recipes")),false);});
});
