import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, it } from "node:test";

const runtimeRoot=resolve(import.meta.dirname,".."),repoRoot=resolve(runtimeRoot,"../.."),harness=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave14-harness.mjs"),target=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave14-pet-skill-probability.mjs"),fixturePath=resolve(repoRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave14-pet-skill-probability-v1.json"),fixture=JSON.parse(readFileSync(fixturePath,"utf8")),hash=(path:string)=>createHash("sha256").update(readFileSync(path,"utf8").replace(/\r\n?/g,"\n")).digest("hex"),head=execFileSync("git",["rev-parse","HEAD"],{cwd:repoRoot,encoding:"utf8"}).trim();
function run(binding:any,payload=fixture.payload){const dir=mkdtempSync(join(tmpdir(),"hoibot-wave14-")),input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:payload,runtimeSourceHashes:fixture.runtimeSourceHashes,evidenceCommit:head,invocation:{targetPath:"개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave14-pet-skill-probability.mjs",targetSourceSha256:hash(target),exportName:"executeWave14PetSkillProbability"}}));let error:any;try{execFileSync(process.execPath,[harness,input,dir,target],{stdio:"pipe",timeout:60000,maxBuffer:8*1024*1024});}catch(value){error=value;}return{dir,error,trace:()=>JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),reply:()=>readFileSync(join(dir,"reply.raw"),"utf8")};}
describe("Wave14 pet-skill probability formal executable parity",()=>{
  it("executes all five required scenarios through actual buildApp.inject",()=>{assert.equal(fixture.bindings.length,5);for(const binding of fixture.bindings){const result=run(binding);try{assert.equal(result.error,undefined,binding.scenarioKind);const trace=result.trace();assert.equal(trace.sourceDomainDmlCount,0);assert.ok(trace.timeline.length>0);}finally{rmSync(result.dir,{recursive:true,force:true});}}});
  it("pins the independent legacy full bytes in dev and prod",()=>{for(const kind of["READ_POSITIVE","EXACT_OUTPUT"]){const result=run(fixture.bindings.find((entry:any)=>entry.scenarioKind===kind));try{assert.equal(result.error,undefined);const reply=result.reply();assert.equal(reply.length,2630);assert.equal(Buffer.byteLength(reply,"utf8"),5494);assert.equal(createHash("sha256").update(reply).digest("hex"),fixture.legacyOracle.replySha256);}finally{rmSync(result.dir,{recursive:true,force:true});}}});
  it("fails closed on oracle and route fixture drift",()=>{for(const mutate of[(value:any)=>value.cases[0].consumers[0].scenarioInputsByScenario.READ_POSITIVE.message="/펫스킬확률 ",(value:any)=>value.cases[0].consumers[0].scenarioInputsByScenario.READ_POSITIVE.replyCount=0]){const payload=structuredClone(fixture.payload);mutate(payload);const result=run(fixture.bindings[0],payload);try{assert.ok(result.error);}finally{rmSync(result.dir,{recursive:true,force:true});}}});
});
