import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "node:test";
import { assertTrustedWave26RocketVariantProjection } from "../src/data-migration/object-db-consumer-executable-parity-ledger.js";

const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>JSON.parse(readFileSync(resolve(root,path),"utf8"));
const fixture=read("개발환경_고도화/migration-control/contracts/object-db-consumer-executable-parity-wave26-rocket-v1.json"),bundle=read("개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave26-v1.json"),prior=read("개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave25-v1.json"),ledger=read("개발환경_고도화/migration-control/contracts/object-db-consumer-executable-parity-ledger.v1.json"),manifest=read("개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json");
const sha=(value:string)=>createHash("sha256").update(value.replace(/\r\n?/g,"\n")).digest("hex"),rocketIds=fixture.variants.map((variant:any)=>variant.consumerId).sort();

describe("Wave26 rocket strict equivalence",()=>{
  it("preserves Wave25 and seals exactly 70 Wave26 receipts",()=>{const prefix=JSON.stringify(bundle.receipts.slice(0,254));assert.equal(bundle.receipts.length,324);assert.deepEqual(bundle.receipts.slice(0,254),prior.receipts);assert.equal(Buffer.byteLength(prefix),999311);assert.equal(sha(prefix),"103338fbc49d17d47f0a04c3fa66e98575bf5a9ca7241ab7e878dd9a907131b5");const added=bundle.receipts.slice(254);assert.equal(new Set(added.map((receipt:any)=>receipt.receiptId)).size,70);assert.equal(added.filter((receipt:any)=>receipt.proofMode==="DIRECT").length,7);assert.equal(added.filter((receipt:any)=>receipt.proofMode==="EQUIVALENT").length,63)});
  it("binds one DIRECT consumer and nine strict variants to the final ledger",()=>{assert.equal(ledger.coverage.directPassConsumers,47);assert.equal(ledger.coverage.equivalentPassConsumers,9);assert.equal(ledger.coverage.verdicts.STATIC_ONLY,995);assert.equal(ledger.coverage.verdicts.BLOCKED_DYNAMIC,82);assert.equal(ledger.coverage.provenConsumers,56);assert.equal(ledger.coverage.unprovenConsumers,1077);for(const id of rocketIds){const entry=ledger.entries.find((candidate:any)=>candidate.consumerId===id);assert.equal(entry.verdict,id===fixture.representativeConsumerId?"DIRECT_PASS":"EQUIVALENT_PASS");assert.equal(entry.scenarios.length,7)}});
  it("fails closed when trigger, itemName, reply, or payload projection drifts",()=>{for(const variant of fixture.variants){const consumer=manifest.consumers.find((candidate:any)=>candidate.consumerId===variant.consumerId);assert.doesNotThrow(()=>assertTrustedWave26RocketVariantProjection(variant,consumer));for(const mutate of[(value:any)=>value.trigger="/로켓99,",(value:any)=>value.itemName+="변조",(value:any)=>value.reply+="변조",(value:any)=>value.payload.amount="2"]){const changed=structuredClone(variant);mutate(changed);assert.throws(()=>assertTrustedWave26RocketVariantProjection(changed,consumer),/drift/)}}});
  it("seals all isolated Maria scenarios and rollback-only Shadow",()=>{assert.deepEqual(fixture.scenarioKinds,["MUTATION_SUCCESS","DOMAIN_FAILURE_ROLLBACK","DUPLICATE_REPLAY_DML_ZERO","PAYLOAD_DRIFT_FAIL_CLOSED","RESTART_REPLAY","CONCURRENCY_SINGLE_WRITER","AUTH_DENIED"]);assert.equal(fixture.observations.length,7);assert.equal(fixture.shadowObservation.mode,"SHADOW");assert.equal(fixture.shadowObservation.committedRowCount,0);assert.equal(fixture.shadowObservation.beforeSha256,fixture.shadowObservation.afterSha256);assert.equal(fixture.wrongRoom.disposition,"NOT_APPLICABLE")});
});
