import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { after, before, beforeEach, describe, it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { HomeFurnitureInfoReadService } from "../src/home/home-furniture-info-read-service.js";
import { HomeFurnitureStatsReadService } from "../src/home/home-furniture-stats-read-service.js";
const enabled=process.env.WAVE11_ISOLATED_MARIADB_TEST==="true",required=(name:string)=>process.env[name]??"wave11-isolated-not-configured",delay=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
type Reader={read(input:{eventId:string;externalUserId:string;destinationId:string;message?:string}):Promise<any>};
const allsee="\u200b".repeat(500);
const expectedInfoReply=`[👑호이패스 프리미엄👑]\n[🥇대상가구유저] 가구 가방🛌 [6/15]\n별빛 하우스🏠(+3,345,678💕)[+100평]\n좋아홈💌x12345개\n현재 배치된 가구 (2/15)\n(매력 2,345,678💕 적용중)\n━━━━━━━━━━━━━━━\n\n※ 가구 장착: /가구장착 [번호]\n※ 가구 판매: /가구판매 [번호]\n※ 장착 가구판매: /집청소 [번호]\n※ 장착 귀속해제: /가구해제 [번호]\n━━━━━━━━━━━━━━\n✧━인벤토리 가구 목록🪑━✧\n1. 별빛 침대⭐(+1,234,567💕)[창조]\n2. 달빛 소파🌙(+500,000💕)[신화]\n3. 가나다 의자(+3,000💕)[A]\n4. 라마바 탁자(+2,000💕)[B]\n5. 사아자 램프💡(+1,000💕)[C]\n${allsee}6. 여섯번째 장롱🗄️(+999💕)[등급없음]\n`;
const expectedStatsReply=`📊 전체 가구 등급별 통계 📊\n\n총합: 10개\n\n${allsee}- A [30.0%]: 3개\n- B [20.0%]: 2개\n- C [20.0%]: 2개\n- 창조 [10.0%]: 1개\n- 신화 [10.0%]: 1개\n- 등급없음 [10.0%]: 1개\n`;
describe("Wave11 isolated MariaDB actual home-furniture ingress/lock/rollback",{skip:!enabled},()=>{
 let database:DatabaseClient;const token="wave11-isolated-token",admin="wave11-home-admin",ordinary="wave11-home-ordinary",gap="wave11-home-linkage-gap",roomId="990000000000311",destination="Wave11 가구방",targetPlayerId=203003n,replies:Array<{room:string;data:string}>=[];
 const openDatabase=()=>createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:16,connectTimeoutMs:5000});
 const consumers=[{name:"info",scope:"home.furniture_info_read",code:"HOME_FURNITURE_INFO_READ",message:"/가구정보 대상가구유저",create:(db=database):Reader=>new HomeFurnitureInfoReadService(db)},{name:"stats",scope:"home.furniture_stats_read",code:"HOME_FURNITURE_STATS_READ",message:"/가구통계",create:(db=database):Reader=>new HomeFurnitureStatsReadService(db)}] as const;
 before(async()=>{database=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:16,connectTimeoutMs:5000});await database.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=1");await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code IN ('HOME_FURNITURE_INFO_READ','HOME_FURNITURE_STATS_READ')");assert.deepEqual((await database.query<Array<{command_code:string}>>("SELECT command_code FROM command_registry WHERE rollout_state='ACTIVE' ORDER BY command_code")).map(row=>row.command_code),["HOME_FURNITURE_INFO_READ","HOME_FURNITURE_STATS_READ"]);
  await database.execute("INSERT INTO players(id,status,version) VALUES (203001,'active',1),(203002,'active',1),(203003,'active',1),(203004,'active',1)");await database.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (203001,'조회 관리자',1),(203002,'일반 회원',1),(203003,'대상가구유저',1),(203004,'통계 전용',1)");const ai=await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (203001,'kakao',?,'조회 관리자','linked')",[admin]);await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (203002,'kakao',?,'일반 회원','linked')",[ordinary]);await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (203901,'wave11-admin','조회 관리자','synthetic','active')");await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (203901,?)",[ai.insertId]);await database.execute("INSERT INTO player_homes(player_id,display_name,base_experience,like_count,floor_area) VALUES (203003,'별빛 하우스🏠',1000000,12345,100)");await database.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES (203003,'premium',TRUE,TRUE)");await database.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (203777,203003,'가구펫')");const skill=(await database.query<Array<{id:bigint}>>("SELECT id FROM skill_definitions WHERE code='pet_skill_building_owner'"))[0]!;await database.execute("INSERT INTO pet_skills(player_pet_id,slot_no,skill_id,level,equipped) VALUES (203777,1,?,1,TRUE)",[skill.id]);
  const bag=[['W11-BAG-1','별빛 침대⭐',1234567,'창조'],['W11-BAG-2','달빛 소파🌙',500000,'신화'],['W11-BAG-3','가나다 의자',3000,'A'],['W11-BAG-4','라마바 탁자',2000,'B'],['W11-BAG-5','사아자 램프💡',1000,'C'],['W11-BAG-6','여섯번째 장롱🗄️',999,'등급없음']] as const;for(const [code,name,charm,grade]of bag){const definition=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES (?,?,?,TRUE)",[code,name,charm]);await database.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (203003,?,?,?,'bag')",[definition.insertId,charm,grade]);}for(const [code,charm]of[['W11-PLACED-1',1234567],['W11-PLACED-2',1111111]]as const){const definition=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES (?,?,?,TRUE)",[code,code,charm]);await database.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (203003,?,?,'배치','placed')",[definition.insertId,charm]);}for(const [code,grade,status]of[['W11-STAT-A2','A','bag'],['W11-STAT-A3','A','bag'],['W11-STAT-B2','B','bag'],['W11-STAT-C2','C','bag'],['W11-STAT-X','무시','sold']]as const){const definition=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES (?,?,1,TRUE)",[code,code]);await database.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (203004,?,1,?,?)",[definition.insertId,grade,status]);}
  await database.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (203003,'🥇',203003)");await database.execute("UPDATE home_furniture_equip_policy SET large_floor_threshold=50,small_floor_divisor=10,small_floor_base_slots=3,large_floor_base_slots=8,large_floor_divisor=20,building_owner_bonus=2,god_building_owner_bonus=4,premium_bonus=3 WHERE policy_key='default'");
 });
 beforeEach(async()=>{try{await database.ping();}catch{database=openDatabase();}});
 after(async()=>{if(!database)return;await database.execute("DROP TRIGGER IF EXISTS wave11_hold_audit");await database.execute("DROP TRIGGER IF EXISTS wave11_fail_audit");await database.close();});
 it("runs actual HTTP ingress, exact bytes, admin/missing-linkage/wrong-room and inbox duplicate",async()=>{const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:"dev",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave11-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});let operational=true;const app=buildApp(config,{database,inspectIrisChannel:async()=>operational?{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async reply=>{replies.push(reply);}}),send=(id:string,user:string,message:string)=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:destination,sender:"Wave11",json:{_id:id,chat_id:roomId,user_id:user}}});
  const infoId=`wave11-http-info-${Date.now()}`,infoEvent=`iris:${infoId}`,beforeInfo=replies.length;assert.equal((await send(infoId,admin,"/가구정보 대상가구유저")).statusCode,202);assert.equal(replies.length,beforeInfo+1);const infoReply=replies.at(-1)!.data;for(const value of["1,234,567💕","3,345,678💕","6. 여섯번째 장롱🗄️","\u200b".repeat(500)])assert.ok(infoReply.includes(value));const firstInfo=await receipt(infoEvent,"home.furniture_info_read");assert.deepEqual(firstInfo,{operations:1n,outbox:1n,executions:1n,audit:1n});assert.equal((await send(infoId,admin,"/가구정보 대상가구유저")).statusCode,202);assert.equal(replies.length,beforeInfo+1);assert.deepEqual(await receipt(infoEvent,"home.furniture_info_read"),firstInfo);
  const statsId=`wave11-http-stats-${Date.now()}`,statsEvent=`iris:${statsId}`,beforeStats=replies.length;assert.equal((await send(statsId,gap,"/가구통계")).statusCode,202);assert.equal(replies.length,beforeStats+1);const statsReply=replies.at(-1)!.data;assert.ok(statsReply.includes("총합: 10개")&&statsReply.includes("A [30.0%]: 3개")&&statsReply.indexOf("B [20.0%]")<statsReply.indexOf("C [20.0%]")&&statsReply.includes("\u200b".repeat(500)));assert.deepEqual(await receipt(statsEvent,"home.furniture_stats_read"),{operations:1n,outbox:1n,executions:1n,audit:1n});
  const ordinaryId=`wave11-nonadmin-${Date.now()}`,beforeOrdinary=replies.length;assert.equal((await send(ordinaryId,ordinary,"/가구정보 대상가구유저")).statusCode,202);assert.equal(replies.length,beforeOrdinary);assert.deepEqual(await receipt(`iris:${ordinaryId}`,"home.furniture_info_read"),{operations:0n,outbox:0n,executions:0n,audit:0n});
  operational=false;const wrongId=`wave11-wrong-${Date.now()}`;assert.equal((await send(wrongId,admin,"/가구통계")).statusCode,202);assert.equal(replies.length,beforeOrdinary);assert.deepEqual(await receipt(`iris:${wrongId}`,"home.furniture_stats_read"),{operations:0n,outbox:0n,executions:0n,audit:0n});assert.equal(await count("SELECT COUNT(*) value FROM command_routing_decisions WHERE event_id=?",[`iris:${wrongId}`]),0n);await app.close();});
 for(const consumer of consumers){it(`${consumer.name}: operation replay is distinct from inbox duplicate`,async()=>{const eventId=`wave11-replay-${consumer.name}-${Date.now()}`;await createEvent(eventId,admin);const input={eventId,externalUserId:admin,destinationId:roomId,message:consumer.message},reader=consumer.create(),first=await reader.read(input),afterFirst=await receipt(eventId,consumer.scope),second=await reader.read(input);assert.deepEqual(second,first);assert.deepEqual(await receipt(eventId,consumer.scope),afterFirst);assert.deepEqual(afterFirst,{operations:1n,outbox:1n,executions:1n,audit:1n});});
  it(`${consumer.name}: same event blocks then both fulfill equal with one writer`,async()=>{const eventId=`wave11-lock-${consumer.name}-${Date.now()}`;await createEvent(eventId,admin);const input={eventId,externalUserId:admin,destinationId:roomId,message:consumer.message},signatures=await sourceSignatures();await database.execute("DROP TRIGGER IF EXISTS wave11_hold_audit");await database.execute("CREATE TRIGGER wave11_hold_audit BEFORE INSERT ON command_audit FOR EACH ROW DO SLEEP(3.0)");const reader=consumer.create(),first=reader.read(input);await waitForProcess("INSERT INTO command_audit");let settled=false;const second=reader.read(input).finally(()=>{settled=true;});await delay(100);assert.equal(settled,false);const outcomes=await Promise.allSettled([first,second]);await database.execute("DROP TRIGGER wave11_hold_audit");assert.equal(outcomes[0].status,"fulfilled");assert.equal(outcomes[1].status,"fulfilled");assert.deepEqual((outcomes[1] as PromiseFulfilledResult<any>).value,(outcomes[0] as PromiseFulfilledResult<any>).value);assert.deepEqual(await receipt(eventId,consumer.scope),{operations:1n,outbox:1n,executions:1n,audit:1n});assert.deepEqual(await sourceSignatures(),signatures);});
  it(`${consumer.name}: middle DML failure rolls back receipt4 and preserves every source signature`,async()=>{const eventId=`wave11-rollback-${consumer.name}-${Date.now()}`;await createEvent(eventId,admin);const input={eventId,externalUserId:admin,destinationId:roomId,message:consumer.message},beforeReceipt=await receipt(eventId,consumer.scope),beforeSource=await sourceSignatures();await database.execute("DROP TRIGGER IF EXISTS wave11_fail_audit");await database.execute("CREATE TRIGGER wave11_fail_audit BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='wave11 middle DML failure'");await assert.rejects(()=>consumer.create().read(input),/wave11 middle DML failure/);await database.execute("DROP TRIGGER wave11_fail_audit");assert.deepEqual(beforeReceipt,{operations:0n,outbox:0n,executions:0n,audit:0n});assert.deepEqual(await receipt(eventId,consumer.scope),beforeReceipt);assert.deepEqual(await sourceSignatures(),beforeSource);assert.equal(await database.verifyRollback(),true);});}
 it("matches independent full-byte replies and keeps negative guard at ingress-only DML",async()=>{const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:"dev",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave11-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});const app=buildApp(config,{database,inspectIrisChannel:async()=>({mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}),sendIrisTextReply:async reply=>{replies.push(reply);}}),send=(id:string,user:string,message:string)=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:destination,sender:"Wave11",json:{_id:id,chat_id:roomId,user_id:user}}});const before=replies.length,infoId=`wave11-exact-info-${Date.now()}`,statsId=`wave11-exact-stats-${Date.now()}`;await send(infoId,admin,"/가구정보 대상가구유저");assert.equal(replies.at(-1)?.data,expectedInfoReply);await send(statsId,gap,"/가구통계");assert.equal(replies.at(-1)?.data,expectedStatsReply);const invalidId=`wave11-negative-${Date.now()}`,beforeInvalid=replies.length;await send(invalidId,admin,"/가구통계 안내");assert.equal(replies.length,beforeInvalid);assert.deepEqual(await receipt(`iris:${invalidId}`,"home.furniture_stats_read"),{operations:0n,outbox:0n,executions:0n,audit:0n});assert.equal(await count("SELECT COUNT(*) value FROM event_inbox WHERE event_id=?",[`iris:${invalidId}`]),1n);assert.equal(await count("SELECT COUNT(*) value FROM command_routing_decisions WHERE event_id=?",[`iris:${invalidId}`]),0n);assert.equal(before+2,replies.length);await app.close();});
 for(const consumer of consumers)it(`${consumer.name}: persisted replay survives fresh DB client and service`,async()=>{const eventId=`wave11-restart-${consumer.name}-${Date.now()}`;await createEvent(eventId,admin);const input={eventId,externalUserId:admin,destinationId:roomId,message:consumer.message},open=()=>createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:2,connectTimeoutMs:5000});const firstDb=open();const first=await consumer.create(firstDb).read(input);const operationId=(await firstDb.query<Array<{id:string}>>("SELECT id FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[consumer.scope,eventId]))[0]!.id;await firstDb.close();const before=await receipt(eventId,consumer.scope),beforeRows=await receiptRowsSignature(eventId,consumer.scope),secondDb=open();const second=await consumer.create(secondDb).read(input);const replayOperationId=(await secondDb.query<Array<{id:string}>>("SELECT id FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[consumer.scope,eventId]))[0]!.id;await secondDb.close();assert.deepEqual(second,first);assert.equal(replayOperationId,operationId);assert.deepEqual(await receipt(eventId,consumer.scope),before);assert.deepEqual(await receiptRowsSignature(eventId,consumer.scope),beforeRows);assert.deepEqual(before,{operations:1n,outbox:1n,executions:1n,audit:1n});});
 it("rejects info negative guard before business DML on actual ingress",async()=>{const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:"dev",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave11-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")}),app=buildApp(config,{database,inspectIrisChannel:async()=>({mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}),sendIrisTextReply:async reply=>{replies.push(reply);}}),id=`wave11-negative-info-${Date.now()}`,before=replies.length;await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:"/가구 정보 대상가구유저",room:destination,sender:"Wave11",json:{_id:id,chat_id:roomId,user_id:admin}}});assert.equal(replies.length,before);assert.deepEqual(await receipt(`iris:${id}`,"home.furniture_info_read"),{operations:0n,outbox:0n,executions:0n,audit:0n});assert.equal(await count("SELECT COUNT(*) value FROM event_inbox WHERE event_id=?",[`iris:${id}`]),1n);assert.equal(await count("SELECT COUNT(*) value FROM command_routing_decisions WHERE event_id=?",[`iris:${id}`]),0n);await app.close();});
 async function createEvent(eventId:string,user:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('b',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,roomId,user]);}
 async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await database.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
 async function receipt(eventId:string,scope:string){return{operations:await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[scope,eventId]),outbox:await count("SELECT COUNT(*) value FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId]),executions:await count("SELECT COUNT(*) value FROM command_executions WHERE event_id=?",[eventId]),audit:await count("SELECT COUNT(*) value FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId])};}
 async function receiptRowsSignature(eventId:string,scope:string){const queries:[[string,readonly unknown[]],...Array<[string,readonly unknown[]]>]=[["SELECT * FROM operations WHERE idempotency_scope=? AND idempotency_key=? ORDER BY id",[scope,eventId]],["SELECT o.* FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=? ORDER BY o.id",[scope,eventId]],["SELECT * FROM command_executions WHERE event_id=? ORDER BY id",[eventId]],["SELECT a.* FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=? ORDER BY a.id",[scope,eventId]]],rows:Array<Array<Record<string,unknown>>>=[];for(const[sql,values]of queries)rows.push(await database.query<Array<Record<string,unknown>>>(sql,values));const canonical=JSON.stringify(rows.map(group=>group.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,canonicalValue(value)])))));return{rowCount:rows.reduce((sum,group)=>sum+group.length,0),sha256:createHash("sha256").update(canonical).digest("hex")};}
 async function sourceSignatures(){const specs=[['players','id'],['player_profiles','player_id'],['player_legacy_rank_profiles','player_id'],['furniture_definitions','id'],['furniture_inventory_instances','id'],['player_homes','player_id'],['player_passes','player_id,pass_code'],['player_pets','id'],['pet_skills','player_pet_id,slot_no'],['skill_definitions','id'],['home_furniture_equip_policy','policy_key']]as const,result:Record<string,{rowCount:number;sha256:string}>={};for(const[table,order]of specs){const rows=await database.query<Array<Record<string,unknown>>>(`SELECT * FROM ${table} ORDER BY ${order}`),canonical=JSON.stringify(rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,canonicalValue(value)]))));result[table]={rowCount:rows.length,sha256:createHash("sha256").update(canonical).digest("hex")};}return result;}
 function canonicalValue(value:unknown):unknown{if(typeof value==="bigint")return{$bigint:value.toString()};if(value instanceof Date)return{$date:value.toISOString()};if(Buffer.isBuffer(value))return{$buffer:value.toString("base64")};return value;}
 async function waitForProcess(fragment:string){for(let i=0;i<300;i++){if(await count("SELECT COUNT(*) value FROM information_schema.PROCESSLIST WHERE DB=? AND INFO LIKE ?",[required("DATABASE_NAME"),`%${fragment}%`])>0n)return;await delay(10);}throw new Error(`Wave11 process not observed: ${fragment}`);}
});
