import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient } from "../src/database.js";
import { PendantMarketInfoService } from "../src/market/pendant-market-info-service.js";
import { PendantInfoService } from "../src/pet/pendant-info-service.js";
import { PendantProbabilityService } from "../src/pet/pendant-probability-service.js";

const enabled=process.env.WAVE10_ISOLATED_MARIADB_TEST==="true";
const required=(name:string)=>process.env[name]??"wave10-isolated-not-configured";
const delay=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
type Reader={handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<any>};
const consumers=[
  {name:"market",scope:"market.pendant.info",command:"/펜던트거래정보",code:"PENDANT_MARKET_INFO",create:(db:DatabaseClient):Reader=>new PendantMarketInfoService(db)},
  {name:"info",scope:"pendant.info.read",command:"/펜던트정보",code:"PENDANT_INFO_READ",create:(db:DatabaseClient):Reader=>new PendantInfoService(db)},
  {name:"probability",scope:"pendant.probability.read",command:"/펜던트확률",code:"PENDANT_PROBABILITY_READ",create:(db:DatabaseClient):Reader=>new PendantProbabilityService(db)},
] as const;

describe("Wave10 isolated MariaDB actual ingress/lock/rollback",{skip:!enabled},()=>{
  let database:DatabaseClient;const token="wave10-isolated-token",externalUserId="wave10-pendant-user",roomId="990000000000310",destinationId="Wave10 펜던트방";const replies:Array<{room:string;data:string}>=[];
  before(async()=>{database=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:12,connectTimeoutMs:5000});await database.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code IN ('PENDANT_MARKET_INFO','PENDANT_INFO_READ','PENDANT_PROBABILITY_READ')");await database.execute("INSERT INTO players(status,version) VALUES ('active',1)");const player=(await database.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!;await database.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (?,'Wave10 검증자',1)",[player.id]);await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'Wave10 검증자','linked')",[player.id,externalUserId]);});
  after(async()=>{if(!database)return;await database.execute("DROP TRIGGER IF EXISTS wave10_hold_audit");await database.execute("DROP TRIGGER IF EXISTS wave10_fail_audit");await database.close();});

  it("executes real Fastify Iris HTTP→normalize/inbox/channel/dispatch→processing.replies and rejects duplicate/missing identity/wrong channel",async()=>{const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:"dev",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave10-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});let operational=true;const app=buildApp(config,{database,inspectIrisChannel:async()=>operational?{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async reply=>{replies.push(reply);}});const send=(id:string,user:string,message:string)=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:destinationId,sender:"Wave10 검증자",json:{_id:id,chat_id:roomId,user_id:user}}});for(const consumer of consumers){const id=`wave10-http-${consumer.name}-${Date.now()}`,eventId=`iris:${id}`;const beforeReply=replies.length;assert.equal((await send(id,externalUserId,consumer.command)).statusCode,202);assert.equal(replies.length,beforeReply+1);const beforeDuplicate=await snapshot(consumer.scope,eventId);assert.deepEqual(beforeDuplicate,{operations:1n,outbox:1n,executions:1n,audit:1n});assert.equal((await send(id,externalUserId,consumer.command)).statusCode,202);assert.equal(replies.length,beforeReply+1);assert.deepEqual(await snapshot(consumer.scope,eventId),beforeDuplicate);const route=(await database.query<Array<{command_code:string;route:string;reason_code:string}>>("SELECT command_code,route,reason_code FROM command_routing_decisions WHERE event_id=?",[eventId]))[0]!;assert.deepEqual(route,{command_code:consumer.code,route:"MODERN",reason_code:"MODERN_ROUTE_ALLOWED"});}const beforeReply=replies.length;const missingId=`wave10-missing-${Date.now()}`;assert.equal((await send(missingId,"missing-user","/펜던트확률")).statusCode,202);assert.equal(replies.length,beforeReply);assert.deepEqual(await snapshot("pendant.probability.read",`iris:${missingId}`),{operations:0n,outbox:0n,executions:0n,audit:0n});operational=false;const wrongRoomId=`wave10-room-${Date.now()}`;assert.equal((await send(wrongRoomId,externalUserId,"/펜던트확률")).statusCode,202);assert.equal(replies.length,beforeReply);assert.deepEqual(await snapshot("pendant.probability.read",`iris:${wrongRoomId}`),{operations:0n,outbox:0n,executions:0n,audit:0n});assert.equal(await count("SELECT COUNT(*) value FROM command_routing_decisions WHERE event_id=?",[`iris:${wrongRoomId}`]),0n);});

  for(const consumer of consumers){
    it(`${consumer.name}: proves real InnoDB FOR UPDATE blocking and one writer/replay`,async()=>{const eventId=`wave10-lock-${consumer.name}-${Date.now()}`;await createEvent(eventId);const input={eventId,externalUserId,destinationId,message:consumer.command};await database.execute("DROP TRIGGER IF EXISTS wave10_hold_audit");await database.execute("CREATE TRIGGER wave10_hold_audit BEFORE INSERT ON command_audit FOR EACH ROW DO SLEEP(3.0)");const reader=consumer.create(database),first=reader.handle(input);await waitForProcess("INSERT INTO command_audit");let settled=false;const second=reader.handle(input).finally(()=>{settled=true;});await delay(100);assert.equal(settled,false);const outcomes=await Promise.allSettled([first,second]);await database.execute("DROP TRIGGER wave10_hold_audit");assert.ok(outcomes.some(value=>value.status==="fulfilled"));if(outcomes.every(value=>value.status==="fulfilled"))assert.deepEqual((outcomes[1] as PromiseFulfilledResult<any>).value,(outcomes[0] as PromiseFulfilledResult<any>).value);assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[consumer.scope,eventId]),1n);assert.equal(await count("SELECT COUNT(*) value FROM command_executions WHERE event_id=?",[eventId]),1n);});
    it(`${consumer.name}: rolls all persisted evidence tables back on middle DML failure`,async()=>{const eventId=`wave10-rollback-${consumer.name}-${Date.now()}`;await createEvent(eventId);const input={eventId,externalUserId,destinationId,message:consumer.command};const before=await snapshot(consumer.scope,eventId);await database.execute("DROP TRIGGER IF EXISTS wave10_fail_audit");await database.execute("CREATE TRIGGER wave10_fail_audit BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='wave10 middle DML failure'");await assert.rejects(()=>consumer.create(database).handle(input),/wave10 middle DML failure/);await database.execute("DROP TRIGGER wave10_fail_audit");assert.deepEqual(await snapshot(consumer.scope,eventId),before);assert.deepEqual(before,{operations:0n,outbox:0n,executions:0n,audit:0n});assert.equal(await database.verifyRollback(),true);});
  }
  async function createEvent(eventId:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('a',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,roomId,externalUserId]);}
  async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await database.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
  async function snapshot(scope:string,eventId:string){return{operations:await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope=? AND idempotency_key=?",[scope,eventId]),outbox:await count("SELECT COUNT(*) value FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId]),executions:await count("SELECT COUNT(*) value FROM command_executions WHERE event_id=?",[eventId]),audit:await count("SELECT COUNT(*) value FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope=? AND p.idempotency_key=?",[scope,eventId])};}
  async function waitForProcess(fragment:string){for(let i=0;i<200;i++){if(await count("SELECT COUNT(*) value FROM information_schema.PROCESSLIST WHERE DB=? AND INFO LIKE ?",[required("DATABASE_NAME"),`%${fragment}%`])>0n)return;await delay(10);}throw new Error(`Wave10 process not observed: ${fragment}`);}
});
