import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, it } from "node:test";
import { assertTrustedWave11ConsumerFixtureMapping, assertTrustedWave11ExecutableHashes, executeObjectDbParityHarnessChild, OBJECT_DB_PARITY_WAVE11_CHILD_TIMEOUT_MS, objectDbParityHarnessTimeoutMs } from "../src/data-migration/object-db-consumer-executable-parity-ledger.js";
const runtimeRoot=resolve(import.meta.dirname,".."),repositoryRoot=resolve(runtimeRoot,"../.."),harnessPath=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave11-harness.mjs"),targetPath=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave11-home-furniture-read.mjs"),fixturePath=resolve(repositoryRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave11-home-furniture-read-v1.json"),fixture=JSON.parse(readFileSync(fixturePath,"utf8")),hash=(path:string)=>createHash("sha256").update(readFileSync(path,"utf8").replace(/\r\n?/g,"\n")).digest("hex"),consumers=()=>fixture.payload.cases.flatMap((entry:any)=>entry.consumers);
function run(binding:any,payload=fixture.payload){const dir=mkdtempSync(join(tmpdir(),"hoibot-wave11-")),input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:payload,invocation:{targetPath:"개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave11-home-furniture-read.mjs",targetSourceSha256:hash(targetPath),exportName:"executeWave11HomeFurnitureRead"}}));let error:any;try{execFileSync(process.execPath,[harnessPath,input,dir,targetPath],{stdio:"pipe",timeout:30_000});}catch(value){error=value;}return{dir,error,trace:()=>JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),reply:()=>readFileSync(join(dir,"reply.raw"),"utf8")};}
const table=(sql:string)=>/^(?:INSERT INTO|UPDATE)\s+([A-Za-z0-9_]+)/i.exec(sql)?.[1],codes:Record<string,string>={"runtime-dispatch-722afb15e9cbd92c":"HOME_FURNITURE_INFO_READ","runtime-dispatch-c3cb8d18613c2358":"HOME_FURNITURE_STATS_READ"};
describe("Wave11 home furniture executable parity",()=>{
 it("executes 10 receipts through actual HTTP/app/service/outbox delivery chain",()=>{for(const binding of fixture.bindings){const value=run(binding);try{assert.equal(value.error,undefined);const trace=value.trace();if(binding.scenarioKind==="NEGATIVE_GUARD"){assert.equal(trace.queryTrace.length,2);assert.equal(trace.dmlTrace.length,6);assert.deepEqual(trace.timeline,["BEGIN","COMMIT"]);continue;}const repeat=binding.scenarioKind==="RESTART_CONSISTENCY"?2:1;assert.equal(trace.dmlTrace.length,14*repeat);assert.ok(trace.dmlTrace.every((entry:any)=>new Set(["command_routing_decisions","channels","external_identities","channel_memberships","event_inbox","normalized_provider_events","operations","outbox_messages","command_executions","command_audit","delivery_attempts"]).has(table(entry.normalizedSql)!)));assert.deepEqual(trace.timeline,repeat===2?["CHILD_PROCESS_1:COMMIT","RESTART","CHILD_PROCESS_2:COMMIT"]:["BEGIN","COMMIT","BEGIN","COMMIT","BEGIN","COMMIT"]);assert.ok(trace.lockOrder.includes("operations"));assert.equal(trace.lockOrder.at(-1),"outbox_messages");const route=trace.dmlTrace.find((entry:any)=>table(entry.normalizedSql)==="command_routing_decisions");assert.deepEqual(route.values.slice(2),[codes[binding.consumerId],"MODERN","MODERN_ROUTE_ALLOWED"]);if(repeat===2){const keys=trace.dmlTrace.filter((entry:any)=>entry.normalizedSql.startsWith("INSERT INTO operations")).map((entry:any)=>entry.values[0]);assert.equal(keys.length,2);assert.notEqual(keys[0],keys[1]);for(const key of keys)assert.match(key,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);}}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("pins exact 6th bag allsee and stats tie/percentage/order output",()=>{const info=fixture.bindings.find((entry:any)=>entry.consumerId==="runtime-dispatch-722afb15e9cbd92c"&&entry.scenarioKind==="EXACT_OUTPUT"),stats=fixture.bindings.find((entry:any)=>entry.consumerId==="runtime-dispatch-c3cb8d18613c2358"&&entry.scenarioKind==="EXACT_OUTPUT");for(const[binding,fragments]of[[info,["1,234,567💕","3,345,678💕","6. 여섯번째 장롱🗄️","\u200b".repeat(500)]],[stats,["총합: 8개","A [37.5%]: 3개","B [25.0%]: 2개","C [25.0%]: 2개","\u200b".repeat(500)]]]as const){const value=run(binding);try{assert.equal(value.error,undefined);const reply=value.reply();for(const fragment of fragments)assert.ok(reply.includes(fragment));if(binding===stats)assert.ok(reply.indexOf("B [25.0%]")<reply.indexOf("C [25.0%]"));}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("separates inbox duplicate from operation replay and freezes identity/admin/linkage gaps",()=>{const byId=Object.fromEntries(consumers().map((entry:any)=>[entry.consumerId,entry]));for(const consumer of consumers()){assert.equal(consumer.mutationPlanByScenario.ROLLBACK.find((entry:any)=>entry.error)?.error.code,"ER_SIGNAL_EXCEPTION");assert.equal(consumer.httpOracleByScenario.APP_INBOX_DUPLICATE.serviceInvocationCount,0);assert.deepEqual(consumer.httpOracleByScenario.APP_INBOX_DUPLICATE.evidenceRowsAfter,consumer.httpOracleByScenario.APP_INBOX_DUPLICATE.evidenceRowsBefore);assert.equal(consumer.httpOracleByScenario.SAME_EVENT_REPLAY.serviceInvocationCount,1);assert.deepEqual(consumer.httpOracleByScenario.SAME_EVENT_REPLAY.evidenceRowsAfter,consumer.httpOracleByScenario.SAME_EVENT_REPLAY.evidenceRowsBefore);}assert.equal(byId["runtime-dispatch-722afb15e9cbd92c"].httpOracleByScenario.NON_ADMIN_INFO.serviceInvocationCount,1);assert.deepEqual(byId["runtime-dispatch-722afb15e9cbd92c"].httpOracleByScenario.NON_ADMIN_INFO.evidenceRowsAfter,{operations:0,outbox_messages:0,command_executions:0,command_audit:0});assert.equal(byId["runtime-dispatch-c3cb8d18613c2358"].httpOracleByScenario.VERIFIED_USER_LINKAGE_GAP.serviceInvocationCount,1);assert.equal(byId["runtime-dispatch-c3cb8d18613c2358"].httpOracleByScenario.VERIFIED_USER_LINKAGE_GAP.evidenceRowsAfter.operations,1);});
 it("executes rollback, duplicate, non-admin, wrong-room and linkage-gap risks",()=>{for(const binding of fixture.payload.riskBindings.filter((entry:any)=>["ROLLBACK","APP_INBOX_DUPLICATE","NON_ADMIN_INFO","WRONG_OPERATIONAL_CHANNEL","VERIFIED_USER_LINKAGE_GAP"].includes(entry.scenarioKind))){const value=run(binding);try{assert.equal(value.error,undefined);}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("rejects canonical production service callsite stack drift",()=>{const manifest=JSON.parse(readFileSync(resolve(repositoryRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"),"utf8"));for(const consumer of consumers()){const changed=structuredClone(consumer),source=manifest.consumers.find((entry:any)=>entry.consumerId===consumer.consumerId);changed.serviceCallsite.line+=1;assert.throws(()=>assertTrustedWave11ConsumerFixtureMapping(consumer.consumerId,changed,source),/contract drift/);}});
 it("preserves all 134 prior receipts by exact prefix/hash identity",()=>{const prior=JSON.parse(readFileSync(resolve(repositoryRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave10-v1.json"),"utf8")),current=JSON.parse(readFileSync(resolve(repositoryRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave11-v1.json"),"utf8"));assert.equal(prior.receipts.length,134);assert.equal(current.receipts.length,144);assert.deepEqual(current.receipts.slice(0,134),prior.receipts);assert.equal(new Set(current.receipts.map((entry:any)=>entry.receiptId)).size,144);});
 it("fails closed on canonical mappings, hashes, SQL/rows/output and timeout",()=>{const manifest=JSON.parse(readFileSync(resolve(repositoryRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"),"utf8"));for(const consumer of consumers()){const source=manifest.consumers.find((entry:any)=>entry.consumerId===consumer.consumerId);assert.doesNotThrow(()=>assertTrustedWave11ConsumerFixtureMapping(consumer.consumerId,consumer,source));for(const mutate of[(value:any)=>value.queryPlanByScenario.READ_POSITIVE[0].expectedNormalizedSql+=" ",(value:any)=>value.expectedResultsByScenario.EXACT_OUTPUT="{}",(value:any)=>value.sourceLocator.start+=1]){const changed=structuredClone(consumer);mutate(changed);assert.throws(()=>assertTrustedWave11ConsumerFixtureMapping(consumer.consumerId,changed,source),/contract drift/);}}assert.doesNotThrow(()=>assertTrustedWave11ExecutableHashes(hash(harnessPath),hash(targetPath)));assert.throws(()=>assertTrustedWave11ExecutableHashes("0".repeat(64),hash(targetPath)),/source hash drift/);const original=consumers()[0],payload=structuredClone(fixture.payload),changed=payload.cases.flatMap((entry:any)=>entry.consumers).find((entry:any)=>entry.consumerId===original.consumerId);changed.expectedResultsByScenario.READ_POSITIVE="{}";const binding=fixture.bindings.find((entry:any)=>entry.consumerId===original.consumerId&&entry.scenarioKind==="READ_POSITIVE"),result=run(binding,payload);try{assert.ok(result.error);}finally{rmSync(result.dir,{recursive:true,force:true});}assert.equal(objectDbParityHarnessTimeoutMs("개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave11-harness.mjs"),OBJECT_DB_PARITY_WAVE11_CHILD_TIMEOUT_MS);const dir=mkdtempSync(join(tmpdir(),"wave11-timeout-")),slow=join(dir,"slow.mjs");try{writeFileSync(slow,"await new Promise(resolve => setTimeout(resolve, 10_000));\n");assert.throws(()=>executeObjectDbParityHarnessChild([slow],25),(error:any)=>error?.code==="ETIMEDOUT");}finally{rmSync(dir,{recursive:true,force:true});}});
});
