import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";
import { describe,it } from "node:test";
const runtimeRoot=resolve(import.meta.dirname,".."),repoRoot=resolve(runtimeRoot,"../.."),harness=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave13-harness.mjs"),target=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave13-server-stats.mjs"),fixturePath=resolve(repoRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave13-server-stats-v1.json"),fixture=JSON.parse(readFileSync(fixturePath,"utf8")),hash=(path:string)=>createHash("sha256").update(readFileSync(path,"utf8").replace(/\r\n?/g,"\n")).digest("hex");
function run(binding:any,payload=fixture.payload){const dir=mkdtempSync(join(tmpdir(),"hoibot-wave13-")),input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:payload,invocation:{targetPath:"개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave13-server-stats.mjs",targetSourceSha256:hash(target),exportName:"executeWave13ServerStats"}}));let error:any;try{execFileSync(process.execPath,[harness,input,dir,target],{stdio:"pipe",timeout:30_000});}catch(value){error=value;}return{dir,error,trace:()=>JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),reply:()=>readFileSync(join(dir,"reply.raw"),"utf8")};}
describe("Wave13 server-stats corrective executable parity",()=>{
 it("executes only five corrective DIRECT scenarios through actual buildApp.inject",()=>{assert.equal(fixture.bindings.length,5);for(const binding of fixture.bindings){const value=run(binding);try{assert.equal(value.error,undefined,binding.scenarioKind);const trace=value.trace();assert.ok(trace.timeline.length>0);assert.ok(trace.dmlTrace.every((entry:any)=>!/(?:INSERT(?: IGNORE)? INTO|UPDATE|DELETE FROM)\s+(?:legacy_snapshot_environments|legacy_snapshot_sets|legacy_source_snapshots)\b/i.test(entry.normalizedSql)));if(binding.scenarioKind!=="NEGATIVE_GUARD")assert.ok(trace.lockOrder.includes("legacy_snapshot_environments"));}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("pins independent legacy full-byte output in dev and prod",()=>{const expected=fixture.payload.cases[0].consumers[0].expectedReplyByScenario;for(const scenario of["READ_POSITIVE","EXACT_OUTPUT"]){const binding=fixture.bindings.find((entry:any)=>entry.scenarioKind===scenario),value=run(binding);try{assert.equal(value.error,undefined);const reply=value.reply();assert.equal(reply,expected[scenario]);assert.ok(reply.startsWith("📊 서버유저 통계 📊\n\n서버 전체인원: 3명"));assert.ok(reply.includes(`${"\u200b".repeat(500)}가능 서버:\n- 가 서버: 2명\n- 나 서버: 1명`)&&reply.endsWith("※ 서버 미등록 인원: 2명"));}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("fails closed on SQL, source locator and expected-output drift",()=>{const binding=fixture.bindings[0];for(const mutate of[(value:any)=>value.cases[0].consumers[0].queryPlanByScenario.READ_POSITIVE[0].expectedNormalizedSql+=" ",(value:any)=>value.cases[0].consumers[0].sourceLocator.start+=1,(value:any)=>value.cases[0].consumers[0].expectedReplyByScenario.READ_POSITIVE="drift"]){const payload=structuredClone(fixture.payload);mutate(payload);const result=run(binding,payload);try{assert.ok(result.error);}finally{rmSync(result.dir,{recursive:true,force:true});}}});
});
