import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe,it } from "node:test";

const runtimeRoot=resolve(import.meta.dirname,".."),repoRoot=resolve(runtimeRoot,"../.."),harness=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave12-harness.mjs"),target=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave12-character-count.mjs"),fixturePath=resolve(repoRoot,"개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave12-character-count-v1.json"),fixture=JSON.parse(readFileSync(fixturePath,"utf8")),hash=(path:string)=>createHash("sha256").update(readFileSync(path,"utf8").replace(/\r\n?/g,"\n")).digest("hex");
function run(binding:any,payload=fixture.payload){const dir=mkdtempSync(join(tmpdir(),"hoibot-wave12-")),input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:payload,invocation:{targetPath:"개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave12-character-count.mjs",targetSourceSha256:hash(target),exportName:"executeWave12CharacterCount"}}));let error:any;try{execFileSync(process.execPath,[harness,input,dir,target],{stdio:"pipe",timeout:30_000});}catch(value){error=value;}return{dir,error,trace:()=>JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),reply:()=>readFileSync(join(dir,"reply.raw"),"utf8")};}

describe("Wave12 character-count executable parity",()=>{
 it("executes only five character-count DIRECT scenarios through actual buildApp.inject",()=>{assert.equal(fixture.bindings.length,5);for(const binding of fixture.bindings){const value=run(binding);try{assert.equal(value.error,undefined);const trace=value.trace();assert.ok(trace.timeline.length>0);assert.ok(trace.dmlTrace.every((entry:any)=>!/(?:INSERT(?: IGNORE)? INTO|UPDATE|DELETE FROM)\s+(?:legacy_snapshot_environments|legacy_snapshot_sets|legacy_source_snapshots)\b/i.test(entry.normalizedSql)));if(binding.scenarioKind!=="NEGATIVE_GUARD")assert.ok(trace.lockOrder.includes("legacy_snapshot_environments"));}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("pins the independent legacy full-byte output in dev and prod",()=>{const expected=fixture.payload.cases[0].consumers[0].expectedReplyByScenario;for(const scenario of["READ_POSITIVE","EXACT_OUTPUT"]){const binding=fixture.bindings.find((entry:any)=>entry.scenarioKind===scenario),value=run(binding);try{assert.equal(value.error,undefined);const reply=value.reply();assert.equal(reply,expected[scenario]);assert.ok(reply.startsWith("📊 글자수 통계\n\n[핵심 데이터]"));assert.ok(reply.includes("- 펜던트:")&&reply.includes("[칭호·성장 데이터]")&&reply.includes("[운영 데이터]")&&reply.endsWith("- 자유시장: 74자 / 3명"));}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("executes auth, wrong-room, inbox duplicate, replay, rollback and transient retry risks",()=>{const consumer=fixture.payload.cases[0].consumers[0];for(const binding of fixture.payload.riskBindings){const value=run(binding);try{assert.equal(value.error,undefined,binding.scenarioKind);const trace=value.trace();if(binding.scenarioKind==="ROLLBACK")assert.ok(trace.timeline.includes("ROLLBACK"));if(binding.scenarioKind==="TRANSIENT_1213_RETRY")assert.ok(consumer.transactionEventsByScenario.TRANSIENT_1213_RETRY.filter((event:string)=>event==="ROLLBACK").length===1);}finally{rmSync(value.dir,{recursive:true,force:true});}}});
 it("fails closed on SQL, source locator and expected-output drift",()=>{const binding=fixture.bindings[0];for(const mutate of[(value:any)=>value.cases[0].consumers[0].queryPlanByScenario.READ_POSITIVE[0].expectedNormalizedSql+=" ",(value:any)=>value.cases[0].consumers[0].sourceLocator.start+=1,(value:any)=>value.cases[0].consumers[0].expectedReplyByScenario.READ_POSITIVE="drift"]){const payload=structuredClone(fixture.payload);mutate(payload);const result=run(binding,payload);try{assert.ok(result.error);}finally{rmSync(result.dir,{recursive:true,force:true});}}});
});
