import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { PassCanonicalOwnershipService } from "../src/pass/pass-canonical-ownership-service.js";
import type { PassOwnershipMutation, PassOwnershipMutationResult } from "../src/pass/pass-canonical-ownership-provider.js";

const migration=fs.readFileSync(new URL("../migrations/411_pass_canonical_ownership_convergence.sql",import.meta.url),"utf8");
const rollback=fs.readFileSync(new URL("../../migration-control/rollback/411_pass_canonical_ownership_convergence.sql",import.meta.url),"utf8");
const fixture=JSON.parse(fs.readFileSync(new URL("../../migration-control/fixtures/synthetic-relational/pass-canonical-ownership-convergence-v1.json",import.meta.url),"utf8"));
const providerSource=fs.readFileSync(new URL("../src/pass/pass-canonical-ownership-provider.ts",import.meta.url),"utf8");

test("completes exactly six semantic definitions from the frozen typed policy",()=>{assert.equal(fixture.canonicalDefinitions,6);assert.deepEqual(fixture.semanticDefinitions,["contribution","diamond","oneday","hoi","newbie","premium"]);assert.match(migration,/PASS-SIX|migration\.411|support_pass_definitions/);for(const code of fixture.semanticDefinitions)assert.match(migration,new RegExp(`'${code}'`));});
test("backfills only typed compatibility identities without deleting player_passes",()=>{assert.deepEqual(fixture.compatibilityMappings,[{semanticCode:"hoi",compatibilityCode:"support"},{semanticCode:"newbie",compatibilityCode:"beginner"},{semanticCode:"premium",compatibilityCode:"premium"}]);assert.match(migration,/WHEN 'support' THEN 'hoi' WHEN 'beginner' THEN 'newbie' ELSE 'premium'/);assert.doesNotMatch(migration,/DELETE\s+FROM\s+player_passes|DROP\s+TABLE\s+player_passes/i);assert.match(migration,/ends_at IS NULL THEN 'permanent'/);});
test("keeps canonical truth dual-read write-through and evidence-only events",()=>{assert.match(providerSource,/readCanonical[\s\S]+readCompatibility/);assert.match(providerSource,/writeCompatibility/);assert.match(providerSource,/support_pass_change_events/);assert.equal(fixture.changeEventsRole,"EVIDENCE_ONLY");assert.match(providerSource,/PASS_OWNERSHIP_VERSION_CONFLICT/);assert.match(providerSource,/result_json/);});
test("service normalizes null expiry and delegates typed idempotent mutation",async()=>{const captured:PassOwnershipMutation[]=[];const result:PassOwnershipMutationResult={playerId:"1",semanticCode:"hoi",action:"grant",changed:true,status:"active",entitlementKind:"permanent",endDate:null,version:"1",replayed:false};const service=new PassCanonicalOwnershipService({mutate:async(input)=>{captured.push(input);return result;}});assert.equal((await service.execute({playerId:"1",semanticCode:"hoi",action:"grant",entitlementKind:"dated",endDate:null,expectedVersion:"0",idempotencyKey:"normal"})).status,"active");assert.equal(captured[0]!.entitlementKind,"permanent");assert.equal(captured[0]!.expectedVersion,0n);});
test("rollback preserves compatibility ownership and protected policy consumers",()=>{assert.match(rollback,/updated_operation_id=canonical_row\.created_operation_id/);assert.doesNotMatch(rollback,/DELETE\s+FROM\s+player_passes|DROP\s+TABLE/i);assert.doesNotMatch(migration,/reward|one_day_subscription_grants|admin|main\.js|web-shell/i);assert.deepEqual(fixture.protected,["reward_policy","one_day_grant","admin_generic_mutation","legacy_branch","player_passes_table","main.js","ui"]);});
