import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

const fixturePath=fileURLToPath(new URL("../../migration-control/fixtures/synthetic-relational/pass-six-identity-policy-snapshot-v1.json",import.meta.url));
const repoRoot=fileURLToPath(new URL("../../../",import.meta.url));
const migration=(name:string):string=>readFileSync(fileURLToPath(new URL("../migrations/"+name,import.meta.url)),"utf8");
const mainSource=readFileSync(repoRoot+"main.js","utf8");
const oneDaySource=readFileSync(fileURLToPath(new URL("../src/pass/one-day-pass-subscription-service.ts",import.meta.url)),"utf8");
const questSource=readFileSync(fileURLToPath(new URL("../src/quest/auto-daily-quest-orchestration-service.ts",import.meta.url)),"utf8");
const fixture=JSON.parse(readFileSync(fixturePath,"utf8")) as any;
const sha256=(value:string):string=>createHash("sha256").update(value,"utf8").digest("hex");
const extractRewards=(source:string,key:string):Array<{name:string;count:number}>=>{const marker=key+": [";const start=source.indexOf(marker);assert.notEqual(start,-1);const remainder=source.slice(start+marker.length);const end=remainder.search(/\r?\n\s*\]/);assert.notEqual(end,-1);return [...remainder.slice(0,end).matchAll(/\{\s*name:\s*"([^"]+)",\s*count:\s*(\d+)\s*\}/g)].map(row=>({name:row[1]!,count:Number(row[2])}));};

describe("Lease2409 pass six-identity policy snapshot",()=>{
 it("freezes six semantic identities, seven command names and newbie aliases2",()=>{assert.equal(fixture.counts.semanticIdentities,6);assert.equal(fixture.counts.commandNames,7);assert.equal(fixture.counts.newbieAliases,2);assert.deepEqual(fixture.policy.semanticIdentities.map((x:any)=>x.semanticCode),["contribution","diamond","hoi","newbie","oneday","premium"]);for(const identity of fixture.policy.semanticIdentities)for(const commandName of identity.commandNames)assert.ok(mainSource.includes('"'+commandName+'"'));});
 it("freezes current definitions3 and one exact duplicate oneday seed without conflict",()=>{const sources=[migration("240_contribution_pass_registry.sql"),migration("241_diamond_pass_registry.sql"),migration("244_one_day_pass_subscription.sql"),migration("245_one_day_pass_registry.sql")];const seeds=sources.flatMap(source=>[...source.matchAll(/support_pass_definitions\(pass_code,display_name,active\) VALUES\('([^']+)','([^']+)',TRUE\)/g)].map(m=>m[1]!));assert.deepEqual(seeds,["contribution","diamond","oneday","oneday"]);assert.deepEqual([...new Set(seeds)].sort(),fixture.policy.currentDefinitions);assert.equal(seeds.length-new Set(seeds).size,1);assert.equal(fixture.counts.conflicts,0);});
 it("pins contribution3 diamond1 hoi16 newbie13 premium18 and unified51",()=>{assert.deepEqual(extractRewards(mainSource,"contributionDailyRewards"),fixture.policy.rewardPolicies.contribution);assert.deepEqual(extractRewards(mainSource,"hoiDailyRewards"),fixture.policy.rewardPolicies.hoi);assert.deepEqual(extractRewards(mainSource,"newbieDailyRewards"),fixture.policy.rewardPolicies.newbie);const premiumSource=mainSource.slice(mainSource.indexOf("premium: {"));assert.deepEqual(extractRewards(premiumSource,"dailyRewards"),fixture.policy.rewardPolicies.premium);assert.match(mainSource,/diamondBoxCount:\s*20/);assert.match(mainSource,/diamondBoxName/);assert.deepEqual({contribution:3,diamond:1,hoi:16,newbie:13,premium:18,unified:51},{contribution:fixture.counts.contributionRewards,diamond:fixture.counts.diamondRewards,hoi:fixture.counts.hoiRewards,newbie:fixture.counts.newbieRewards,premium:fixture.counts.premiumRewards,unified:fixture.counts.unifiedRewards});});
 it("freezes one-day rewards2 as operation exactly-once rather than calendar daily",()=>{const source=migration("244_one_day_pass_subscription.sql");for(const reward of fixture.policy.rewardPolicies.oneday){assert.ok(source.includes("'"+reward.rewardCode+"'"));assert.ok(source.includes("'"+reward.itemCode+"'"));}assert.equal(fixture.counts.onedayRewards,2);assert.equal(fixture.policy.oneDaySemantics.calendarDaily,false);assert.match(source,/UNIQUE KEY uq_one_day_subscription_grant\(operation_id,player_id,item_id\)/);assert.match(oneDaySource,/idempotency_scope=\? AND idempotency_key=\?/);assert.match(oneDaySource,/support\.pass\.oneday\.subscription/);assert.doesNotMatch(oneDaySource,/dailyRewardLastDate|period_key/);});
 it("pins hoi-support, newbie-beginner and premium-premium code contracts",()=>{assert.deepEqual(fixture.policy.codeContracts,[{legacyCode:"hoi",canonicalCode:"support"},{legacyCode:"newbie",canonicalCode:"beginner"},{legacyCode:"premium",canonicalCode:"premium"}]);assert.match(mainSource,/key:\s*"hoi"/);assert.match(mainSource,/key:\s*"newbie"/);assert.match(mainSource,/key:\s*"premium"/);assert.match(questSource,/pass_code IN \('support','beginner'\)/);assert.match(questSource,/pass_code='premium'/);});
 it("derives policy version and hash from content with gaps0 and mutation-free source Shadow",()=>{const first=sha256(JSON.stringify(fixture.policy));const replay=sha256(JSON.stringify(fixture.policy));assert.equal(first,replay);assert.equal(first,fixture.policySha256);assert.equal(fixture.policyVersion,"PASS-SIX-v1-"+first.slice(0,16));assert.equal(fixture.counts.gaps,0);assert.equal(fixture.counts.duplicates,1);assert.equal(fixture.counts.conflicts,0);assert.deepEqual(fixture.scopeGuards,{providerChanges:0,resolverChanges:0,ownershipChanges:0,schemaChanges:0,migrationFilesAdded:0,runtimeChanges:0,retirementChanges:0,mainChanges:0,uiChanges:0,databaseWrites:0});});
});
