import assert from "node:assert/strict";import{createHash}from"node:crypto";import{describe,it}from"node:test";import{readFileSync}from"node:fs";import{ApplicationError}from"../src/shared/application-error.js";import{buildPetExploreSettlementInput,calculatePetExploreThreshold,createPetExploreSettlementSnapshotFingerprint,PET_EXPLORE_SETTLEMENT_POLICY_HASH,PET_EXPLORE_SETTLEMENT_POLICY_JSON}from"../src/pet/pet-explore-settlement-input-snapshot-provider.js";import{snapshotRequest,snapshotScenarios,sourceThreshold}from"./fixtures/pet-explore-settlement-input-snapshot.js";
const reward=(itemCode:string)=>[{itemCode,quantity:"1"}];const failure=[{itemCode:"pet_food",quantity:"2"}];const row=(destination:string,overrides:Record<string,unknown>={})=>({destination_code:destination,ticket_policy:"none" as const,ticket_item_code:null,fallback_destinations_json:null,success_rewards_json:reward("lucky_box"),failure_rewards_json:failure,source_gap_code:null,...overrides});
describe("pet explore settlement input snapshot",()=>{
 it("freezes the source policy hash, branch matrix and migration-only domain tables",()=>{assert.equal(createHash("sha256").update(PET_EXPLORE_SETTLEMENT_POLICY_JSON).digest("hex"),PET_EXPLORE_SETTLEMENT_POLICY_HASH);assert.equal(snapshotScenarios.length,10);const sql=readFileSync(new URL("../migrations/405_pet_explore_settlement_input_snapshot.sql",import.meta.url),"utf8");assert.match(sql,new RegExp(PET_EXPLORE_SETTLEMENT_POLICY_HASH));assert.equal((sql.match(/CREATE TABLE pet_explore_settlement_/g)??[]).length,6);assert.doesNotMatch(sql,/inventory_(stacks|ledger)|currency_|package_item_balances/);});
 it("calculates exact basis points without premium or implicit clamping",()=>{assert.equal(calculatePetExploreThreshold(sourceThreshold),1300);assert.throws(()=>calculatePetExploreThreshold({...sourceThreshold,premium:700}),(e:unknown)=>e instanceof ApplicationError&&e.code==="PET_EXPLORE_PREMIUM_POLICY_CONFLICT");assert.throws(()=>calculatePetExploreThreshold({...sourceThreshold,tier:10000}),(e:unknown)=>e instanceof ApplicationError&&e.details?.gapCode==="threshold_over_100_percent");});
 it("builds direct settlement input with published reward and fallback policy",()=>{const request=snapshotRequest();const input=buildPetExploreSettlementInput(request,PET_EXPLORE_SETTLEMENT_POLICY_HASH,new Map([["luck_mine",row("luck_mine")]]));assert.equal(input.plans[0]?.successThresholdBasisPoints,1300);assert.deepEqual(input.plans[0]?.failureRewards,failure);const dungeon=buildPetExploreSettlementInput(snapshotRequest({participants:[{...request.participants[0]!,destinationCode:"jeondor_dungeon"}]}),PET_EXPLORE_SETTLEMENT_POLICY_HASH,new Map([["jeondor_dungeon",row("jeondor_dungeon",{ticket_policy:"consume_or_regular_fallback",ticket_item_code:"ITEM-PET-DUNGEON-ENTRY-TICKET",fallback_destinations_json:["pet_enhancement_mine","intimacy_mine","luck_mine"],success_rewards_json:reward("ITEM-DUNGEON-JEONDOR-BOX")})]]));assert.equal(dungeon.plans[0]?.ticketPolicy,"consume_or_regular_fallback");assert.equal(dungeon.plans[0]?.successRewards[0]?.itemCode,"ITEM-DUNGEON-JEONDOR-BOX");});
 it("fails closed for event, archmage, premium and explicit source gaps",()=>{const base=snapshotRequest();for(const [destination,gap]of [["archmage_ruins","archmage_random_reward"],["belcar_maze","maze_ticket_canonical_binding"]]as const)assert.throws(()=>buildPetExploreSettlementInput(snapshotRequest({participants:[{...base.participants[0]!,destinationCode:destination}]}),PET_EXPLORE_SETTLEMENT_POLICY_HASH,new Map([[destination,row(destination,{source_gap_code:gap})]])),(e:unknown)=>e instanceof ApplicationError&&e.details?.gapCode===gap);assert.throws(()=>buildPetExploreSettlementInput(snapshotRequest({participants:[{...base.participants[0]!,sourceGapCodes:["event_dungeon_reroute"]}]}),PET_EXPLORE_SETTLEMENT_POLICY_HASH,new Map([["luck_mine",row("luck_mine")]])),/event_dungeon_reroute/);});
 it("keeps fingerprint deterministic across participant order and binds next-auto payload",()=>{const first=snapshotRequest({participants:[{...snapshotRequest().participants[0]!,participationId:"2"},{...snapshotRequest().participants[0]!,participationId:"1"}],nextAutoReservations:[{mode:"auto",roundKey:"next",playerId:"9",destinationCode:"luck_mine",expectedRoundVersion:"1",expectedParticipationVersion:null,idempotencyKey:"next-auto",reason:"next automatic reservation",sourceCode:"scheduler"}]});const second={...first,participants:[...first.participants].reverse()};assert.equal(createPetExploreSettlementSnapshotFingerprint(first),createPetExploreSettlementSnapshotFingerprint(second));});
 it("exposes command-ready load without caller policy components",()=>{const source=readFileSync(new URL("../src/pet/pet-explore-settlement-input-snapshot-provider.ts",import.meta.url),"utf8");assert.match(source,/load\(input:PetExploreSettlementSnapshotSourceInput\):Promise<PetExploreSettlementInput>/);assert.match(source,/pet_explore_settlement_participant_source_projections/);assert.match(source,/pet_explore_auto_fixed_configs/);assert.doesNotMatch(source,/load\(input:[^{]*PetExploreThresholdComponents/);});
});
