import assert from"node:assert/strict";import{describe,it}from"node:test";import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";import{ApplicationError}from"../src/shared/application-error.js";import{calculatePetTitleSalePrice,isPetTitleSaleCommand,PetTitleSaleService}from"../src/pet/title-sale-service.js";
function scripted(results:unknown[]){const queue=[...results],sql:string[]=[];let insertId=300n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);return(queue.shift()??[])as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);insertId++;return{affectedRows:1n,insertId};}};return{sql,database:{ping:async()=>undefined,verifyRollback:async()=>true,query:tx.query,execute:tx.execute,withTransaction:async<T>(work:(v:DatabaseTransaction)=>Promise<T>)=>work(tx),close:async()=>undefined}as DatabaseClient};}
const command={externalUserId:"seller",channelId:"room",eventId:"event",message:"/펫타이틀판매 1",environmentCode:"dev"as const};const first={assignment_id:10n,stable_assignment_id:"00000000-0000-0000-0000-000000000010",title_id:101n,display_order:1,source_price:"5000.000",display_name:"첫째",equipped:1,state_version:2n};const second={assignment_id:11n,stable_assignment_id:"00000000-0000-0000-0000-000000000011",title_id:102n,display_order:2,source_price:"20000.000",display_name:"둘째",equipped:0,state_version:2n};
describe("pet title sale",()=>{
 it("accepts only one complete positive index and preserves the legacy price bands",()=>{assert.equal(isPetTitleSaleCommand("/펫타이틀판매 1"),true);for(const value of ["/펫타이틀판매","/펫타이틀판매 0","/펫타이틀판매 1 설명"])assert.equal(isPetTitleSaleCommand(value),false);assert.equal(calculatePetTitleSalePrice("9999.000"),1000000n);assert.equal(calculatePetTitleSalePrice("10000.000"),3000n);assert.equal(calculatePetTitleSalePrice("20001.000"),6000n);});
 it("sells the stable assignment, unequips it, compacts order, and credits point",async()=>{const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[first,second],[{balance:"1000.000",version:3n}]]);const result=await new PetTitleSaleService(s.database).execute(command);assert.equal(result.status,"sold");assert.equal(result.stableAssignmentId,first.stable_assignment_id);assert.equal(result.wasEquipped,true);assert.equal(result.pointBalance,"1001000");for(const token of ["UPDATE player_title_state","DELETE FROM player_title_assignments","currency_ledger","pet_title_sale_events","command_audit","outbox_messages"])assert.equal(s.sql.some(x=>x.includes(token)),true);});
 it("replays before selecting the newly compacted assignment",async()=>{const prior={status:"sold"as const,stableAssignmentId:first.stable_assignment_id,pointBalance:"1001000"};const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[{result_json:prior}]]);const result=await new PetTitleSaleService(s.database).execute(command);assert.equal(result.replayed,true);assert.equal(s.sql.some(x=>x.includes("player_title_assignments assignment")),false);});
 it("blocks zero/fractional/negative source prices before operation",async()=>{for(const price of ["NaN","-1.000","1.500"]){const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[{...first,source_price:price}]]);await assert.rejects(()=>new PetTitleSaleService(s.database).execute(command),(e:unknown)=>e instanceof ApplicationError&&e.statusCode===409);assert.equal(s.sql.some(x=>x.includes("INSERT INTO operations")),false);}});
 it("requires a contiguous current assignment snapshot",async()=>{const s=scripted([[{environment_code:"dev"}],[],[{identity_id:1n,player_id:2n}],[],[{...first,display_order:2}]]);const result=await new PetTitleSaleService(s.database).execute(command);assert.equal(result.status,"snapshot_required");assert.equal(s.sql.some(x=>x.includes("INSERT INTO operations")),false);});
 it("keeps the active castle siege block silent before member lookup",async()=>{const s=scripted([[{environment_code:"dev"}],[{active:1}]]);const result=await new PetTitleSaleService(s.database).execute(command);assert.equal(result.status,"ignored_active_siege");assert.equal(s.sql.some(x=>x.includes("external_identities")),false);});
});
