import assert from "node:assert/strict";
import { it } from "node:test";
import mariadb from "mariadb";
import type { DatabaseClient, DatabaseTransaction, DatabaseWriteResult } from "../src/database.js";
import { PlayerAttributeAdjustService } from "../src/admin/player-attribute-adjust-service.js";
import { ApplicationError } from "../src/shared/application-error.js";

const enabled=process.env.HOIBOT_ISOLATED_MARIADB==="1";
it("adjusts level and point atomically and preserves replay",{skip:!enabled},async()=>{
 const pool=mariadb.createPool({host:process.env.MARIADB_HOST!,port:Number(process.env.MARIADB_PORT),user:process.env.MARIADB_USER!,password:process.env.MARIADB_PASSWORD!,database:process.env.MARIADB_DATABASE!,connectionLimit:2,bigIntAsNumber:false});
 const database={async withTransaction<T>(work:(tx:DatabaseTransaction)=>Promise<T>):Promise<T>{const c=await pool.getConnection();try{await c.beginTransaction();const tx={query:async<R>(s:string,p?:unknown[])=>c.query(s,p)as Promise<R>,execute:async(s:string,p?:unknown[]):Promise<DatabaseWriteResult>=>{const r=await c.query(s,p)as{affectedRows?:number|bigint;insertId?:number|bigint};return{affectedRows:BigInt(r.affectedRows??0),insertId:BigInt(r.insertId??0)};}}as DatabaseTransaction;const result=await work(tx);await c.commit();return result;}catch(e){await c.rollback();throw e;}finally{c.release();}}}as DatabaseClient;
 try{const c=await pool.getConnection();try{await c.query("INSERT INTO players(id) VALUES(1),(2)");await c.query("INSERT INTO player_profiles(player_id,current_display_name,level) VALUES(1,'관리자',1),(2,'대상',3)");await c.query("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES(2,'point',3,1)");await c.query("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES(91,1,'kakao','admin-user','linked')");await c.query("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES(7,'attribute-admin','속성관리자','fixture','active')");await c.query("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES(7,91)");await c.query("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 7,id FROM admin_roles WHERE code='super_admin'");for(const event of["attr-lv","attr-point"]){await c.query("INSERT INTO event_inbox(event_id,event_kind,processing_status,received_at) VALUES(?,'message','processed',UTC_TIMESTAMP(3))",[event]);}}finally{c.release();}
  const service=new PlayerAttributeAdjustService(database);const level=await service.execute({externalUserId:"admin-user",channelId:"room",eventId:"attr-lv",message:"/속성감소 대상 lv 5"});const point=await service.execute({externalUserId:"admin-user",channelId:"room",eventId:"attr-point",message:"/속성감소 대상 point 5"});const replay=await service.execute({externalUserId:"admin-user",channelId:"room",eventId:"attr-lv",message:"/속성감소 대상 lv 5"});assert.equal(level.afterValue,"-2");assert.equal(point.afterValue,"-2");assert.equal(replay.replayed,true);await assert.rejects(()=>service.execute({externalUserId:"admin-user",channelId:"room",eventId:"attr-lv",message:"/속성증가 대상 lv 5"}),(e:unknown)=>e instanceof ApplicationError&&e.code==="PLAYER_ATTRIBUTE_REPLAY_MISMATCH");
  const v=await pool.getConnection();try{const rows=await v.query<Array<{level:bigint;balance:string;ledgers:bigint;operations:bigint;outbox:bigint;audits:bigint}>>("SELECT p.level,a.balance,(SELECT COUNT(*) FROM currency_ledger WHERE reason_code='admin_player_attribute_adjust') ledgers,(SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'admin.player-attribute-adjust:%') operations,(SELECT COUNT(*) FROM outbox_messages) outbox,(SELECT COUNT(*) FROM command_audit WHERE action_code='player.attribute.adjust') audits FROM player_profiles p JOIN currency_accounts a ON a.player_id=p.player_id AND a.currency_code='point' WHERE p.player_id=2");assert.equal(rows[0]!.level,-2n);assert.equal(rows[0]!.balance,"-2.000");assert.deepEqual([Number(rows[0]!.ledgers),Number(rows[0]!.operations),Number(rows[0]!.outbox),Number(rows[0]!.audits)],[1,2,2,2]);}finally{v.release();}
 }finally{await pool.end();}
});
