import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {buildApp} from "../src/app.js";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient,type DatabaseClient} from "../src/database.js";
const enabled=process.env.DATABASE_INTEGRATION_ENABLED==="true",required=(name:string)=>process.env[name]??"integration-not-configured";
describe("player level rank read MariaDB integration",{skip:!enabled},()=>{
 let database:DatabaseClient;const token="player-level-rank-token",roomId="990000000000228",externalId="level-rank-requester";
 const open=()=>createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:required("DATABASE_PASSWORD"),name:required("DATABASE_NAME"),connectionLimit:5,connectTimeoutMs:5000});
 before(async()=>{database=open();await database.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='PLAYER_LEVEL_RANK_READ'");for(let i=0;i<12;i++){await database.execute("INSERT INTO players(status,version) VALUES('active',1)");const p=(await database.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!;await database.execute("INSERT INTO player_profiles(player_id,current_display_name,level,accumulated_level_offset,version) VALUES (?,?,?,?,1)",[p.id,`회원${i+1}`,i<2?100:100-i,0]);await database.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (?,?,?)",[p.id,i===0?"⭐":"",i+1]);if(i===0)await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'회원1','linked')",[p.id,externalId]);}await database.execute("INSERT INTO players(status,version) VALUES('suspended',1)");const x=(await database.query<Array<{id:bigint}>>("SELECT id FROM players ORDER BY id DESC LIMIT 1"))[0]!;await database.execute("INSERT INTO player_profiles(player_id,current_display_name,level,accumulated_level_offset,version) VALUES (?,'제외회원',999,0,1)",[x.id]);});
 after(async()=>{if(database)try{await database.close();}catch(e){if(!(typeof e==="object"&&e!==null&&"code" in e&&(e as {code?:unknown}).code==="ER_POOL_ALREADY_CLOSED"))throw e;}});
 it("orders current levels, snapshots top, rolls back evidence, replays, shadows and reconnects",async()=>{const replies:Array<{room:string;data:string}>=[],config=loadConfig({NODE_ENV:"test",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"level-rank-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});const deps={database,inspectIrisChannel:async()=>({mode:"operational" as const,channelClass:"open_group" as const,reason:"allowed" as const,evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}),sendIrisTextReply:async(r:{room:string;data:string})=>{replies.push(r);}};let app=buildApp(config,deps);const send=(id:string,msg:string)=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg,room:"고도화레벨순위방",sender:"회원1",json:{_id:id,chat_id:roomId,user_id:externalId}}});
 const event=`level-rank-${Date.now()}`;assert.equal((await send(event,"/레벨순위")).statusCode,202);assert.match(replies.at(-1)!.data,/🥇\. ⭐회원1 - LV\.100/);assert.equal((replies.at(-1)!.data.match(/\u200b/g)??[]).length,500);let snap=(await database.query<Array<{name:string;top_level:bigint}>>("SELECT profile.current_display_name name,snapshot.top_level FROM player_level_rank_snapshots snapshot JOIN player_profiles profile ON profile.player_id=snapshot.top_player_id"))[0]!;assert.deepEqual(snap,{name:"회원1",top_level:100n});await send(event,"/레벨순위");assert.equal(Number((await database.query<Array<{n:bigint}>>("SELECT COUNT(*) n FROM command_executions WHERE command_code='PLAYER_LEVEL_RANK_READ'"))[0]!.n),1);const before=replies.length;await send(`suffix-${Date.now()}`,"/레벨순위 1");assert.equal(replies.length,before);
 await database.execute("UPDATE command_registry SET rollout_state='SHADOW' WHERE command_code='PLAYER_LEVEL_RANK_READ'");await send(`shadow-${Date.now()}`,"/레벨순위");assert.equal(replies.length,before);await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='PLAYER_LEVEL_RANK_READ'");await database.execute("UPDATE player_profiles SET level=200 WHERE current_display_name='회원2'");await database.execute("CREATE TRIGGER synthetic_level_rank_audit_failure BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic audit failure'");assert.equal((await send(`failed-${Date.now()}`,"/레벨순위")).statusCode,500);await database.execute("DROP TRIGGER synthetic_level_rank_audit_failure");snap=(await database.query<Array<{name:string;top_level:bigint}>>("SELECT profile.current_display_name name,snapshot.top_level FROM player_level_rank_snapshots snapshot JOIN player_profiles profile ON profile.player_id=snapshot.top_player_id"))[0]!;assert.equal(snap.name,"회원1");assert.equal((await send(`retry-${Date.now()}`,"/레벨순위")).statusCode,202);await app.close();database=open();app=buildApp(config,{...deps,database});assert.equal((await send(`reconnect-${Date.now()}`,"/레벨순위")).statusCode,202);snap=(await database.query<Array<{name:string;top_level:bigint}>>("SELECT profile.current_display_name name,snapshot.top_level FROM player_level_rank_snapshots snapshot JOIN player_profiles profile ON profile.player_id=snapshot.top_player_id"))[0]!;assert.deepEqual(snap,{name:"회원2",top_level:200n});await app.close();});
});
