import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient,type DatabaseClient,type DatabaseTransaction} from "../src/database.js";
import {CommandDispatcher,MariaCommandDispatchRepository} from "../src/dispatch/command-dispatcher.js";
import {PreSignupAdminService} from "../src/admin/pre-signup-admin-service.js";
const integration=process.env.RUN_MARIADB_INTEGRATION==="true"?describe:describe.skip;
integration("pre-signup attendance admin MariaDB integration",()=>{
 let db:DatabaseClient;const user="integration-pre-signup-manager",room="integration-pre-signup-room",prefix=`integration-pre-signup-${Date.now()}`;let hoi1:bigint,hoi2:bigint;
 before(async()=>{db=createDatabaseClient(loadConfig().database);const operator=988700011;await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'integration-pre-signup','통합 미가입출첵 운영자','integration','active') ON DUPLICATE KEY UPDATE status='active'",[operator]);await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='manager' ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)",[operator]);await db.execute("INSERT INTO external_identities(provider_code,external_user_id,status) VALUES('kakao',?,'linked') ON DUPLICATE KEY UPDATE status='linked'",[user]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT ?,id FROM external_identities WHERE provider_code='kakao' AND external_user_id=? ON DUPLICATE KEY UPDATE operator_id=VALUES(operator_id)",[operator,user]);hoi1=await server("integration-hoi1","호1");hoi2=await server("integration-hoi2","호2");const player=await db.execute("INSERT INTO players(status,version,created_at,updated_at) VALUES('active',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");await db.execute("INSERT INTO player_profiles(player_id,current_display_name,joined_at,level,accumulated_level_offset,experience,rebirth_count,game_server_id,tier_code,terms_agreed,first_sponsor,version,updated_at) VALUES (?,'가나다 남',UTC_TIMESTAMP(3),1,0,0,1,?,'seedling',TRUE,FALSE,1,UTC_TIMESTAMP(3))",[player.insertId,hoi1]);const joinedIdentity=await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'가나다 남','linked')",[player.insertId,`${prefix}-joined`]);await attendance("가나다 남",joinedIdentity.insertId,hoi1,"today");await attendance("라마바 여",null,hoi2,"stale");await attendance("사아자 남",null,hoi1,"today");await attendance("차카타 여",null,hoi1,"today");await attendance("가나다 여",null,null,"today");});
 after(async()=>db.close());
 async function server(code:string,name:string){const row=await db.execute("INSERT INTO game_servers(code,display_name,active,version,created_at,updated_at) VALUES (?,?,TRUE,1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[code,name]);return row.insertId;}
 async function attendance(name:string,identity:bigint|null,serverId:bigint|null,date:"today"|"stale"){await db.execute(`INSERT INTO pre_signup_attendance(external_identity_id,legacy_display_name,normalized_display_name,attendance_count,last_attended_on,game_server_id,status,version,created_at,updated_at) VALUES (?,?,?,2,${date==="today"?"UTC_DATE()":"DATE_SUB(UTC_DATE(),INTERVAL 4 DAY)"},?,'active',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))`,[identity,name,name,serverId]);}
 async function event(id:string,external=user){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('b',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,external]);}
 async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await db.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
 it("cleans, resets and reads one locked snapshot with replay, Shadow and rollback",async()=>{
  const service=new PreSignupAdminService(db),shadowId=`${prefix}-shadow`;await event(shadowId);const shadow=await new CommandDispatcher(new MariaCommandDispatchRepository(db),{enabled:true,allowAllCanaries:true,canaryUserIds:new Set()}).resolve({eventId:shadowId,message:"/미가입출첵",userId:user,hasTrustedDisplayName:true});assert.deepEqual([shadow.route,shadow.handlerKey],["SHADOW","admin_pre_signup_cleanup"]);
  const lookupId=`${prefix}-lookup`;await event(lookupId);const lookup=await service.execute({eventId:lookupId,externalUserId:user,destinationId:room,command:{kind:"identity-lookup",name:"가나다"}});assert.equal(lookup?.matches.filter(row=>row.state==="joined").length,1);assert.equal(lookup?.matches.filter(row=>row.state==="pre-signup").length,2);
  const cleanupId=`${prefix}-cleanup`;await event(cleanupId);const cleanup=await service.execute({eventId:cleanupId,externalUserId:user,destinationId:room,command:{kind:"cleanup"}});assert.equal(cleanup?.removedCount,2);assert.equal(cleanup?.remainingCount,3);assert.equal(await count("SELECT COUNT(*) value FROM pre_signup_attendance WHERE status='removed_joined'"),1n);assert.equal(await count("SELECT COUNT(*) value FROM pre_signup_attendance WHERE status='removed_stale'"),1n);const mutations=await count("SELECT COUNT(*) value FROM pre_signup_attendance_mutations mutation JOIN pre_signup_attendance_runs run ON run.id=mutation.run_id JOIN operations operation_row ON operation_row.id=run.operation_id WHERE operation_row.idempotency_key=?",[cleanupId]);assert.equal(mutations,2n);assert.deepEqual(await service.execute({eventId:cleanupId,externalUserId:user,destinationId:room,command:{kind:"cleanup"}}),cleanup);assert.equal(await count("SELECT COUNT(*) value FROM pre_signup_attendance_mutations mutation JOIN pre_signup_attendance_runs run ON run.id=mutation.run_id JOIN operations operation_row ON operation_row.id=run.operation_id WHERE operation_row.idempotency_key=?",[cleanupId]),2n);
  const resetId=`${prefix}-reset`;await event(resetId);const reset=await service.execute({eventId:resetId,externalUserId:user,destinationId:room,command:{kind:"server-reset",server:"호1"}});assert.equal(reset?.resetCount,2);assert.equal(await count("SELECT COUNT(*) value FROM pre_signup_attendance WHERE status='active' AND game_server_id=?",[hoi1]),0n);assert.deepEqual(await service.execute({eventId:resetId,externalUserId:user,destinationId:room,command:{kind:"server-reset",server:"호1"}}),reset);
  const denied=`${prefix}-denied`;await event(denied,`${user}-denied`);assert.equal(await service.execute({eventId:denied,externalUserId:`${user}-denied`,destinationId:room,command:{kind:"cleanup"}}),null);
  await attendance("하거너 남",null,hoi2,"today");const rollback=`${prefix}-rollback`;await event(rollback);await assert.rejects(()=>new PreSignupAdminService(failAudit(db)).execute({eventId:rollback,externalUserId:user,destinationId:room,command:{kind:"server-reset",server:"호2"}}),/integration pre-signup audit failure/);assert.equal(await count("SELECT COUNT(*) value FROM pre_signup_attendance WHERE status='active' AND game_server_id=?",[hoi2]),1n);assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_key=?",[rollback]),0n);
 });
});
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,v)=>inner.query(s,v),execute:(s,v)=>inner.execute(s,v),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(tx:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(tx=>work({query:(s,v)=>tx.query(s,v),execute:async(s,v)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("integration pre-signup audit failure");return tx.execute(s,v);}}))};}
