import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { ServerStatsService } from "../src/admin/server-stats-service.js";

const integration=process.env.RUN_MARIADB_INTEGRATION==="true"?describe:describe.skip;
integration("admin server stats MariaDB integration",()=>{
  let db:DatabaseClient;const suffix=`${process.pid}-${Date.now()}`,actor=`server-stats-admin-${suffix}`,denied=`server-stats-denied-${suffix}`,room="server-stats-room",prefix=`server-stats-${suffix}`;
  before(async()=>{db=createDatabaseClient(loadConfig().database);await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (988930001,'server-stats-admin','서버 통계 관리자','integration','active') ON DUPLICATE KEY UPDATE status='active'");await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 988930001,id FROM admin_roles WHERE code='super_admin' ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)");await db.execute("INSERT INTO external_identities(provider_code,external_user_id,status) VALUES ('kakao',?,'linked'),('kakao',?,'linked')",[actor,denied]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT 988930001,id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[actor]);await db.execute("INSERT INTO game_servers(id,code,display_name,active) VALUES (988930001,'A','가 서버',1),(988930002,'B','나 서버',1),(988930003,'OLD','종료 서버',0)");for(const [id,name,server,status] of [[988931001,"가1",988930001,"active"],[988931002,"가2",988930001,"active"],[988931003,"나1",988930002,"active"],[988931004,"정지",988930002,"suspended"],[988931005,"미지정",null,"active"],[988931006,"종료",988930003,"active"]] as const){await db.execute("INSERT INTO players(id,status) VALUES (?,?)",[id,status]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,game_server_id) VALUES (?,?,?)",[id,name,server]);}});
  after(async()=>db.close());
  async function event(id:string,user=actor){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('5',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
  async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await db.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
  it("validates Shadow, active aggregation, permission, replay mismatch, rollback and snapshot pin",async()=>{const service=new ServerStatsService(db),shadow=`${prefix}-shadow`;await event(shadow);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:actor,channelId:room,message:"/서버통계"}),{status:"shadow"});await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='ADMIN_SERVER_STATS'");const success=`${prefix}-success`;await event(success);const result=await new IrisAdminCommandService(db).changePlayerPoint({eventId:success,externalUserId:actor,channelId:room,message:"/서버통계"});assert.equal(result.status,"changed");if(result.status==="changed"){assert.match(result.data,/가 서버: 2명/);assert.match(result.data,/나 서버: 1명/);assert.match(result.data,/미지정: 2명/);assert.doesNotMatch(result.data,/종료 서버/);assert.match(result.data,/전체 활성 회원: 5명/);}const replay=await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"});assert.ok(replay!==null);assert.deepEqual(await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"}),replay);await assert.rejects(()=>service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"dev"}),/요청 내용이 다릅니다/);const deniedEvent=`${prefix}-denied`;await event(deniedEvent,denied);assert.equal(await service.read({eventId:deniedEvent,externalUserId:denied,destinationId:room,environment:"prod"}),null);const rollback=`${prefix}-rollback`;await event(rollback);await db.execute("CREATE TRIGGER fail_server_stats_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='stats.server.read' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced server stats audit failure'; END IF; END");try{await assert.rejects(()=>service.read({eventId:rollback,externalUserId:actor,destinationId:room,environment:"prod"}),/forced server stats audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_server_stats_audit");}assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_key=?",[rollback]),0n);assert.deepEqual({operations:await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope='stats.server.read'"),outboxes:await count("SELECT COUNT(*) value FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope='stats.server.read'"),audits:await count("SELECT COUNT(*) value FROM command_audit WHERE action_code='stats.server.read'"),snapshots:await count("SELECT COUNT(*) value FROM admin_server_stat_snapshot_sets")},{operations:1n,outboxes:1n,audits:1n,snapshots:1n});});
});
