import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { after,before,describe,it } from "node:test";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { ServerStatsService } from "../src/admin/server-stats-service.js";

const integration=process.env.RUN_MARIADB_INTEGRATION==="true"?describe:describe.skip;
integration("admin server stats MariaDB integration",()=>{
  let db:DatabaseClient;const suffix=`${process.pid}-${Date.now()}`,actor=`server-stats-admin-${suffix}`,denied=`server-stats-denied-${suffix}`,room="server-stats-room",prefix=`server-stats-${suffix}`;
  before(async()=>{db=createDatabaseClient(loadConfig().database);await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (988930001,'server-stats-admin','서버 통계 관리자','integration','active') ON DUPLICATE KEY UPDATE status='active'");await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 988930001,id FROM admin_roles WHERE code='super_admin' ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)");await db.execute("INSERT INTO external_identities(provider_code,external_user_id,status) VALUES ('kakao',?,'linked'),('kakao',?,'linked')",[actor,denied]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT 988930001,id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[actor]);const raw=JSON.stringify({member:{가1:{server:"가 서버"},가2:{server:"가 서버"},나1:{server:"나 서버"},미등록:{server:""},미등록2:{}}});const snapshot=await db.execute("INSERT INTO legacy_snapshot_sets(environment_code,database_identity,snapshot_version,snapshot_at,snapshot_status) VALUES ('prod','hoibot-prod',315001,UTC_TIMESTAMP(3),'ready')");await db.execute("INSERT INTO legacy_source_snapshots(snapshot_set_id,source_code,raw_json,content_sha256,utf16_code_unit_count,entity_count,read_status,captured_at) VALUES (?,'member',?,?,?,5,'valid',UTC_TIMESTAMP(3))",[snapshot.insertId,raw,createHash('sha256').update(raw).digest('hex'),raw.length]);await db.execute("UPDATE legacy_snapshot_environments SET active_snapshot_set_id=? WHERE environment_code='prod'",[snapshot.insertId]);});
  after(async()=>db.close());
  async function event(id:string,user=actor){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('5',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
  async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await db.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}
  it("validates Shadow, legacy snapshot aggregation, permission, replay mismatch and rollback",async()=>{const runtime={environmentCode:"prod" as const,databaseIdentity:"hoibot-prod"},service=new ServerStatsService(db,runtime),shadow=`${prefix}-shadow`;await event(shadow);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:actor,channelId:room,message:"/서버통계"}),{status:"shadow"});await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='ADMIN_SERVER_STATS'");const success=`${prefix}-success`;await event(success);const result=await new IrisAdminCommandService(db,[],undefined,runtime).changePlayerPoint({eventId:success,externalUserId:actor,channelId:room,message:"/서버통계"});assert.equal(result.status,"changed");if(result.status==="changed"){assert.match(result.data,/^📊 서버유저 통계 📊/);assert.match(result.data,/- 가 서버: 2명/);assert.match(result.data,/- 나 서버: 1명/);assert.match(result.data,/서버 미등록 인원: 2명/);assert.match(result.data,/서버 전체인원: 3명/);}const replay=await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"});assert.ok(replay!==null);assert.deepEqual(await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"}),replay);await assert.rejects(()=>service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"dev"}),/요청 내용이 다릅니다/);const deniedEvent=`${prefix}-denied`;await event(deniedEvent,denied);assert.equal(await service.read({eventId:deniedEvent,externalUserId:denied,destinationId:room,environment:"prod"}),null);const rollback=`${prefix}-rollback`;await event(rollback);await db.execute("CREATE TRIGGER fail_server_stats_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='stats.server.read' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced server stats audit failure'; END IF; END");try{await assert.rejects(()=>service.read({eventId:rollback,externalUserId:actor,destinationId:room,environment:"prod"}),/forced server stats audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_server_stats_audit");}assert.equal(await count("SELECT COUNT(*) value FROM operations WHERE idempotency_key=?",[rollback]),0n);});
});
