import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { after,before,describe,it } from "node:test";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { ServerStatsService } from "../src/admin/server-stats-service.js";

const enabled=process.env.WAVE13_ISOLATED_MARIADB_TEST==="true",required=(name:string)=>process.env[name]??"wave13-not-configured";
describe("Wave13 server stats actual HTTP ingress",{skip:!enabled},()=>{
  let database:DatabaseClient;const apps=new Set<ReturnType<typeof buildApp>>(),statements:string[]=[],token="wave13-isolated-token",admin="wave13-http-admin",ordinary="wave13-http-ordinary",roomId="990000000000513",roomName="Wave13 서버통계방",replies:Array<{room:string;data:string}>=[];
  const raw=JSON.stringify({member:{가:{server:"나 서버"},나:{server:"가 서버"},다:{server:"가 서버"},라:{server:""},마:{}}});
  before(async()=>{database=createDatabaseClient(loadConfig().database);await database.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=1");await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='ADMIN_SERVER_STATS'");
    await database.execute("INSERT INTO players(id,status,version) VALUES (513001,'active',1),(513002,'active',1)");await database.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (513001,'Wave13 관리자',1),(513002,'Wave13 일반',1)");const identity=await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (513001,'kakao',?,'Wave13 관리자','linked')",[admin]);await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (513002,'kakao',?,'Wave13 일반','linked')",[ordinary]);await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (513901,'wave13-http-admin','Wave13 관리자','synthetic','active')");await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (513901,?)",[identity.insertId]);await database.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 513901,id FROM admin_roles WHERE code='super_admin'");
    for(const [environment,databaseIdentity]of[["dev","hoibot-dev"],["prod","hoibot-prod"]]as const){const snapshot=await database.execute("INSERT INTO legacy_snapshot_sets(environment_code,database_identity,snapshot_version,snapshot_at,snapshot_status) VALUES (?,?,13001,'2026-09-07 07:46:00','ready')",[environment,databaseIdentity]);await database.execute("INSERT INTO legacy_source_snapshots(snapshot_set_id,source_code,raw_json,content_sha256,utf16_code_unit_count,entity_count,read_status,captured_at) VALUES (?,'member',?,?,?,5,'valid','2026-09-07 07:46:00')",[snapshot.insertId,raw,createHash("sha256").update(raw).digest("hex"),raw.length]);await database.execute("UPDATE legacy_snapshot_environments SET active_snapshot_set_id=? WHERE environment_code=?",[snapshot.insertId,environment]);}
  });
  after(async()=>{for(const app of apps)await app.close();await database.close();});
  it("covers exact output, prod/dev, deny/wrong-room, duplicate/concurrency/restart, drift and rollback without source DML",async()=>{let operational=true;const dev=appWithRoom(()=>operational,"dev"),send=(app:ReturnType<typeof buildApp>,id:string,user=admin,message="/서버통계")=>app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:roomName,sender:"Wave13",json:{_id:id,chat_id:roomId,user_id:user}}});
    const beforeSource=await sourceEvidence(),event=`wave13-http-success-${Date.now()}`,beforeReplies=replies.length;assert.equal((await send(dev,event)).statusCode,202);assert.equal(replies.length,beforeReplies+1);assert.equal(replies.at(-1)!.data,oracle(raw));assert.deepEqual(await receipt(`iris:${event}`),[1n,1n,1n,1n,1n]);assert.equal((await send(dev,event)).statusCode,202);assert.equal(replies.length,beforeReplies+1);
    const fresh=appWithRoom(()=>true,"dev");assert.equal((await send(fresh,event)).statusCode,202);assert.equal(replies.length,beforeReplies+1);assert.deepEqual(await receipt(`iris:${event}`),[1n,1n,1n,1n,1n]);
    const concurrent=`wave13-http-concurrent-${Date.now()}`,other=appWithRoom(()=>true,"dev"),responses=await Promise.all([send(dev,concurrent),send(other,concurrent)]);assert.deepEqual(responses.map(response=>response.statusCode),[202,202]);assert.deepEqual(await receipt(`iris:${concurrent}`),[1n,1n,1n,1n,1n]);
    const prod=appWithRoom(()=>true,"prod"),prodEvent=`wave13-http-prod-${Date.now()}`;await send(prod,prodEvent);const stored=await operationResult(`iris:${prodEvent}`);assert.equal(stored.environment,"prod");assert.equal(stored.data,oracle(raw));
    const deniedEvent=`wave13-http-denied-${Date.now()}`;await send(dev,deniedEvent,ordinary);assert.deepEqual(await receipt(`iris:${deniedEvent}`),[0n,0n,0n,0n,0n]);await database.execute("INSERT INTO admin_operator_permission_overrides(operator_id,permission_code,effect,granted_by,reason) VALUES (513901,'stats.server.read','deny',513901,'wave13 synthetic deny')");const overrideEvent=`wave13-http-override-${Date.now()}`;await send(dev,overrideEvent);assert.deepEqual(await receipt(`iris:${overrideEvent}`),[0n,0n,0n,0n,0n]);await database.execute("DELETE FROM admin_operator_permission_overrides WHERE operator_id=513901 AND permission_code='stats.server.read'");
    operational=false;const wrongRoom=`wave13-http-room-${Date.now()}`;await send(dev,wrongRoom);assert.deepEqual(await receipt(`iris:${wrongRoom}`),[0n,0n,0n,0n,0n]);operational=true;
    await assert.rejects(()=>new ServerStatsService(database,{environmentCode:"dev",databaseIdentity:"hoibot-dev"}).read({eventId:`iris:${event}`,externalUserId:admin,channelId:"other-channel",destinationId:roomId,environment:"dev",requestText:"/서버통계"}),/요청 내용이 다릅니다/);
    const rollback=`wave13-http-rollback-${Date.now()}`;await database.execute("CREATE TRIGGER wave13_fail_server_stats_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='stats.server.read' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced wave13 rollback'; END IF; END");try{assert.equal((await send(dev,rollback)).statusCode,500);}finally{await database.execute("DROP TRIGGER IF EXISTS wave13_fail_server_stats_audit");}assert.deepEqual(await receipt(`iris:${rollback}`),[0n,0n,0n,0n,0n]);assert.deepEqual(await sourceEvidence(),beforeSource);assertNoLegacySnapshotDml(statements);for(const table of["legacy_snapshot_environments","legacy_snapshot_sets","legacy_source_snapshots"])assert.throws(()=>assertNoLegacySnapshotDml([`UPDATE ${table} SET id=1`]),new RegExp(table));
  });
  function appWithRoom(isOperational:()=>boolean,environment:"prod"|"dev"){const config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:environment,IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave13-isolated-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:required("DATABASE_HOST"),DATABASE_PORT:required("DATABASE_PORT"),DATABASE_USER:required("DATABASE_USER"),DATABASE_PASSWORD:required("DATABASE_PASSWORD"),DATABASE_NAME:required("DATABASE_NAME")});const app=buildApp(config,{database:tracedDatabase(createDatabaseClient(config.database),statements),inspectIrisChannel:async()=>isOperational()?{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async reply=>{replies.push(reply);}});apps.add(app);return app;}
  async function count(sql:string,values:readonly unknown[]=[]){return BigInt((await database.query<Array<{value:bigint|string}>>(sql,values))[0]?.value??0);}async function receipt(id:string){return[await count("SELECT COUNT(*) value FROM operations WHERE idempotency_scope='stats.server.read' AND idempotency_key=?",[id]),await count("SELECT COUNT(*) value FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='stats.server.read' AND p.idempotency_key=?",[id]),await count("SELECT COUNT(*) value FROM command_executions WHERE event_id=?",[id]),await count("SELECT COUNT(*) value FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope='stats.server.read' AND p.idempotency_key=?",[id]),await count("SELECT COUNT(*) value FROM admin_server_stat_read_executions e JOIN operations p ON p.id=e.operation_id WHERE p.idempotency_scope='stats.server.read' AND p.idempotency_key=?",[id])];}async function operationResult(id:string){const row=(await database.query<Array<{result_json:string}>>("SELECT result_json FROM operations WHERE idempotency_scope='stats.server.read' AND idempotency_key=?",[id]))[0]!;return typeof row.result_json==="string"?JSON.parse(row.result_json)as{environment:string;data:string}:row.result_json;}async function sourceEvidence(){return database.query<Array<{environment_code:string;row_count:bigint;hashes:string}>>("SELECT set_row.environment_code,COUNT(*) row_count,GROUP_CONCAT(source.content_sha256 ORDER BY source.id) hashes FROM legacy_snapshot_environments set_row JOIN legacy_source_snapshots source ON source.snapshot_set_id=set_row.active_snapshot_set_id WHERE source.source_code='member' GROUP BY set_row.environment_code ORDER BY set_row.environment_code");}
});
function oracle(raw:string):string{const parsed=JSON.parse(raw)as{member:Record<string,{server?:unknown}>},counts:Record<string,number>={},names=Object.keys(parsed.member);let total=0,unknown=0;for(const name of names){const server=parsed.member[name]?.server;if(!server||server===""){unknown+=1;continue;}const key=String(server);counts[key]=(counts[key]??0)+1;total+=1;}if(names.length===0)return"📭 등록된 유저가 없습니다.";let out=`📊 서버유저 통계 📊\n\n서버 전체인원: ${total}명\n\n${"\u200b".repeat(500)}가능 서버:\n`;for(const name of Object.keys(counts).sort((a,b)=>a.localeCompare(b,"ko")))out+=`- ${name}: ${counts[name]}명\n`;if(unknown>0)out+=`\n※ 서버 미등록 인원: ${unknown}명`;return out;}
function tracedDatabase(base:DatabaseClient,statements:string[]):DatabaseClient{return{ping:()=>base.ping(),verifyRollback:()=>base.verifyRollback(),query:<T>(sql:string,values?:readonly unknown[])=>{statements.push(sql);return base.query<T>(sql,values);},execute:(sql:string,values?:readonly unknown[])=>{statements.push(sql);return base.execute(sql,values);},withTransaction:<T>(work:(transaction:DatabaseTransaction)=>Promise<T>)=>base.withTransaction(transaction=>work({query:<R>(sql:string,values?:readonly unknown[])=>{statements.push(sql);return transaction.query<R>(sql,values);},execute:(sql:string,values?:readonly unknown[])=>{statements.push(sql);return transaction.execute(sql,values);}})),close:()=>base.close()};}
function assertNoLegacySnapshotDml(statements:string[]):void{for(const sql of statements){const normalized=sql.replace(/\s+/g," ").trim();const match=/^(?:INSERT\s+INTO|UPDATE|DELETE\s+FROM)\s+(legacy_snapshot_environments|legacy_snapshot_sets|legacy_source_snapshots)\b/i.exec(normalized);if(match!==null)throw new Error(`forbidden source DML: ${match[1]}`);}}
