import assert from "node:assert/strict";import{describe,it}from"node:test";
import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";
import{isTrialTowerSeasonResetCommand,TrialTowerSeasonResetService}from"../src/trial/trial-tower-season-reset-service.js";
function scripted(results:unknown[]){const left=[...results],sql:string[]=[];let id=10n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);return left.shift() as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);return{affectedRows:1n,insertId:++id};}};const db:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw 0;},execute:async()=>{throw 0;},withTransaction:async<T>(w:(v:DatabaseTransaction)=>Promise<T>)=>w(tx),close:async()=>undefined};return{db,sql};}
describe("trial tower season reset",()=>{
 it("accepts only the exact reset command",()=>{assert.equal(isTrialTowerSeasonResetCommand("/시련의탑시즌초기화"),true);assert.equal(isTrialTowerSeasonResetCommand("/시련의탑시즌초기화 해봐"),false);});
 it("snapshots every progress row before deleting all progress",async()=>{const s=scripted([[],[{season_key:"current",player_id:1n,floor:12n,last_win_at:null,version:2n},{season_key:"old",player_id:2n,floor:8n,last_win_at:null,version:1n}]]),r=await new TrialTowerSeasonResetService(s.db).reset({idempotencyKey:"reset",sourceEventId:"reset",operatorId:"1",destinationId:"room"});assert.equal(r.resetCount,2);assert.equal(s.sql.filter(x=>x.includes("trial_tower_reset_snapshots")).length,2);assert.ok(s.sql.indexOf("DELETE FROM trial_tower_progress")>s.sql.findIndex(x=>x.includes("trial_tower_reset_snapshots")));});
 it("replays the stored result without a second delete",async()=>{const prior={status:"changed" as const,data:"시련의탑데이터가 초기화 되었습니다",outboxId:"11",auditId:"12",resetCount:1},s=scripted([[{result_json:JSON.stringify(prior)}]]),r=await new TrialTowerSeasonResetService(s.db).reset({idempotencyKey:"reset",sourceEventId:"reset",operatorId:"1",destinationId:"room"});assert.deepEqual(r,prior);assert.equal(s.sql.some(x=>x.includes("DELETE FROM trial_tower_progress")),false);});
});
