import assert from "node:assert/strict";import{describe,it}from"node:test";
import type{DatabaseClient,DatabaseTransaction,DatabaseWriteResult}from"../src/database.js";
import{isTrialTowerSeasonLifecycleCommand,TrialTowerSeasonLifecycleService}from"../src/trial/trial-tower-season-lifecycle-service.js";
function scripted(results:unknown[]){const left=[...results],sql:string[]=[];let id=10n;const tx:DatabaseTransaction={query:async<T>(s:string):Promise<T>=>{sql.push(s);return left.shift() as T;},execute:async(s:string):Promise<DatabaseWriteResult>=>{sql.push(s);return{affectedRows:1n,insertId:++id};}};const db:DatabaseClient={ping:async()=>undefined,verifyRollback:async()=>true,query:async()=>{throw 0;},execute:async()=>{throw 0;},withTransaction:async<T>(w:(v:DatabaseTransaction)=>Promise<T>)=>w(tx),close:async()=>undefined};return{db,sql};}
describe("trial tower season lifecycle",()=>{
 it("accepts only exact start and end commands",()=>{assert.equal(isTrialTowerSeasonLifecycleCommand("/시련의탑시즌시작"),true);assert.equal(isTrialTowerSeasonLifecycleCommand("/시련의탑시즌종료"),true);assert.equal(isTrialTowerSeasonLifecycleCommand("/시련의탑시즌시작 해봐"),false);});
 it("starts the current season and broadcasts the exact legacy notice once per room",async()=>{const s=scripted([[],[{active:0}]]),r=await new TrialTowerSeasonLifecycleService(s.db,["room-a","room-b","room-a"]).change({message:"/시련의탑시즌시작",idempotencyKey:"start",sourceEventId:"start",operatorId:"1"});assert.equal(r.active,true);assert.equal(r.replies.length,2);assert.match(r.data,/게이트/);assert.ok(s.sql.some(x=>x.includes("trial_tower_season_transitions")));});
 it("ends without settlement or progress deletion",async()=>{const s=scripted([[],[{active:1}]]),r=await new TrialTowerSeasonLifecycleService(s.db,["room"]).change({message:"/시련의탑시즌종료",idempotencyKey:"end",sourceEventId:"end",operatorId:"1"});assert.equal(r.active,false);assert.match(r.data,/고생하셨습니다/);assert.equal(s.sql.some(x=>x.includes("trial_tower_progress")),false);});
});
