import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient } from "../database.js";
import { ApplicationError } from "../shared/application-error.js";
import { parseDiamondPassCommand } from "./diamond-pass-command.js";

type Operator={operator_id:bigint;display_name:string}; type Target={player_id:bigint;display_name:string};
type PassRow={id:bigint;entitlement_kind:"permanent"|"dated";end_date:Date|string|null;status:"active"|"revoked"|"expired";version:bigint};
export type DiamondPassResult={status:"changed"|"unchanged";action:"add"|"delete";target:string;data:string;outboxId:string;auditId:string;replayed:boolean};
const scope="support.pass.diamond.registry", code="DIAMOND_PASS_REGISTRY";
const key=(v:string)=>v.length<=191?v:`sha256:${createHash("sha256").update(v).digest("hex")}`;
const stored=(v:string|DiamondPassResult)=>typeof v==="string"?JSON.parse(v) as DiamondPassResult:v;
const dateText=(v:Date|string|null)=>v===null?null:(v instanceof Date?v.toISOString().slice(0,10):String(v).slice(0,10));
function todayKst():string{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),get=(t:string)=>p.find(x=>x.type===t)!.value;return `${get("year")}-${get("month")}-${get("day")}`;}

// 다이아패스 추가·갱신·삭제를 stable player entitlement와 원장에 원자 반영합니다.
export class DiamondPassService{
 public constructor(private readonly database:DatabaseClient){}
 public async execute(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<DiamondPassResult>{
  const command=parseDiamondPassCommand(input.message);if(!command)throw new ApplicationError("DIAMOND_PASS_COMMAND_INVALID","다이아패스 명령 형식을 확인해 주세요.",422);
  const operator=(await this.database.query<Operator[]>(`SELECT mapping.operator_id,operator.display_name FROM external_identities identity JOIN admin_operator_external_identities mapping ON mapping.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=mapping.operator_id AND operator.status='active' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' ORDER BY mapping.operator_id LIMIT 1`,[input.externalUserId]))[0];
  if(operator?.display_name!=="호이 남")throw new ApplicationError("DIAMOND_PASS_FORBIDDEN","다이아패스 관리 권한이 없습니다.",403);
  const targets=await this.database.query<Target[]>(`SELECT player.id player_id,profile.current_display_name display_name FROM player_profiles profile JOIN players player ON player.id=profile.player_id AND player.status='active' WHERE profile.current_display_name=? LIMIT 2`,[command.target]);
  if(targets.length!==1)throw new ApplicationError("DIAMOND_PASS_TARGET_NOT_FOUND","❌ 해당 유저를 찾을 수 없습니다.",404);const target=targets[0]!;
  if(command.action==="add"&&command.endDate!==null&&command.endDate<todayKst())throw new ApplicationError("DIAMOND_PASS_PAST_DATE",`❌ 지난 날짜로 패스를 추가할 수 없습니다.\n오늘 이후 날짜를 입력해주세요.\n예) /호이패스추가, ${command.target} 26.06.21`,422);
  return this.database.withTransaction(async tx=>{const idKey=key(input.eventId),prior=(await tx.query<Array<{result_json:string|DiamondPassResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,idKey]))[0];if(prior?.result_json!=null)return {...stored(prior.result_json),replayed:true};
   const op=(await tx.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,?,?,'admin_operator',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),scope,idKey,operator.operator_id])).insertId;
   const before=(await tx.query<PassRow[]>("SELECT id,entitlement_kind,end_date,status,version FROM player_support_passes WHERE player_id=? AND pass_code='diamond' FOR UPDATE",[target.player_id]))[0];let changed=false,data="",passId:bigint;
   if(command.action==="add"){const kind=command.option,existing=before?.status==="active";await tx.execute(`INSERT INTO player_support_passes(player_id,pass_code,entitlement_kind,end_date,status,version,created_operation_id,updated_operation_id,created_at,updated_at) VALUES (?,'diamond',?,?,'active',1,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE entitlement_kind=VALUES(entitlement_kind),end_date=VALUES(end_date),status='active',version=version+1,updated_operation_id=VALUES(updated_operation_id),updated_at=UTC_TIMESTAMP(3)`,[target.player_id,kind,command.endDate,op,op]);passId=(await tx.query<Array<{id:bigint}>>("SELECT id FROM player_support_passes WHERE player_id=? AND pass_code='diamond'",[target.player_id]))[0]!.id;changed=!existing||before!.entitlement_kind!==kind||dateText(before!.end_date)!==command.endDate;data=`${existing?"⚠️ 이미 해당 패스를 보유 중입니다.\n기존 종료일을 새 종료일로 갱신합니다.":`${target.display_name} 사용자에게 패스가 추가되었습니다.`}\n패스 기간: ${command.option==="permanent"?"영구권":`${command.rawEndDate}까지`}\n저장 확인: 다이아패스 활성`;}
   else{if(before?.status!=="active"){passId=before?.id??0n;data="❌ 해당 유저는 해당 패스를 보유하고 있지 않습니다.";}else{passId=before.id;await tx.execute("UPDATE player_support_passes SET status='revoked',version=version+1,updated_operation_id=?,updated_at=UTC_TIMESTAMP(3) WHERE id=? AND version=?",[op,before.id,before.version]);changed=true;data=`${target.display_name} 사용자의 패스가 삭제되었습니다.\n저장 확인: 다이아패스 비활성`;}}
   await tx.execute("INSERT INTO support_pass_change_events(operation_id,pass_id,player_id,pass_code,action_code,previous_status,previous_kind,previous_end_date,next_status,next_kind,next_end_date,changed,created_at) VALUES (?,?,?,'diamond',?,?,?,?,?,?,?, ?,UTC_TIMESTAMP(3))",[op,passId===0n?null:passId,target.player_id,command.action,before?.status??null,before?.entitlement_kind??null,dateText(before?.end_date??null),command.action==="add"?"active":before?.status==="active"?"revoked":before?.status??"missing",command.action==="add"?command.option:before?.entitlement_kind??null,command.action==="add"?command.endDate:dateText(before?.end_date??null),changed]);
   const audit=await tx.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'admin_operator',?,'player',?,'support.pass.diamond.registry',?,'Iris 다이아패스 관리',?,UTC_TIMESTAMP(3))",[op,operator.operator_id,target.player_id,changed?"changed":"unchanged",JSON.stringify({action:command.action,target:target.display_name,changed})]);await tx.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,?,?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,code,op,changed?"changed":"unchanged"]);const out=await tx.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[op,input.destinationId,JSON.stringify({data})]);const result:DiamondPassResult={status:changed?"changed":"unchanged",action:command.action,target:target.display_name,data,outboxId:out.insertId.toString(),auditId:audit.insertId.toString(),replayed:false};await tx.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),op]);return result;});
 }
}
