-- 29개 독립 패키지의 실제 보상 정의. 검증 전까지 package_catalog.enabled=0을 유지한다.
START TRANSACTION;

INSERT INTO package_item_definitions (item_id,item_type,item_name,stackable,metadata_json,enabled,row_version) VALUES
('ITEM-RWD-001','STACK','펫스윗홈인테리어샵🖼️(/샵오픈)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-002','STACK','탐험확률UP🗻(20%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-003','STACK','길드공헌훈장🌟(/길드공헌 숫자)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-004','STACK','길드창고패키지🧳(/길드창고패키지오픈',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"레거시 원문 품목명 괄호 누락 보존"}',0,1),
('ITEM-RWD-005','STACK','확성기📢(/알림 내용 30자)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-006','GUILD_RESOURCE','길드자금',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-007','GUILD_RESOURCE','펫스킬북',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-008','GUILD_RESOURCE','펜던트',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-009','GUILD_RESOURCE','펫',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-010','GUILD_RESOURCE','미니펫',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-011','POINT','포인트',1,'{"source":"legacy-main.js","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 잉어"}',0,1),
('ITEM-RWD-012','STACK','미니펫뽑기',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-013','STACK','가구상점',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-014','STACK','야구공',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-015','STACK','환생버섯',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-016','STACK','강화확률뽑기',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-017','FURNITURE','고대서적📘',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=로열 루미에르; exp=140000; rate=0.00001"}',0,1),
('ITEM-RWD-018','STACK','미니펫 강화석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-019','STACK','미니펫강화확률UP(30%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-020','MINI_PET','미니펫 등급표 기반 무작위',0,'{"source":"legacy-main.js","definitionStatus":"RULE_REQUIRED","note":"miniPetData.gradeTable + miniPetData.miniPet; 최대 3000; 성공 수만 소비"}',0,1),
('ITEM-RWD-021','MINI_PET','호이빛💖',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=창조; battleExp=1350000; castleExp=1350000; raidExp=1350000"}',0,1),
('ITEM-RWD-022','STACK','티어티켓',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-023','STACK','영혼석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-024','STACK','특별사료',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-025','STACK','우유',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-026','STACK','펫강화석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-027','STACK','행운상자',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-028','MINI_PET','컬렉션창세',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=창세; exp=1; price=1"}',0,1),
('ITEM-RWD-029','MINI_PET','컬렉션창조',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=창조; exp=1; price=1"}',0,1),
('ITEM-RWD-030','STACK','탐험확률UP(50%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-031','STACK','탐험확률UP(40%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-032','STACK','탐험확률UP(30%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-033','STACK','던전티켓',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-034','STACK','지도',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-035','STACK','미니펫뽑기4',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-036','STACK','솔로레이드초기화',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-037','STACK','슬롯코인',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-038','STACK','시련탑부스터',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-039','STACK','토지문서',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-040','PET_APPEARANCE','🎃|💀|🍬|🍭|🤡|👻|🕯',0,'{"source":"legacy-main.js","definitionStatus":"RULE_REQUIRED","note":"보유 펫 외형 7종 중 1종; 사전 보유 검증 및 원자 처리"}',0,1),
('ITEM-RWD-041','STACK','강화석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-042','STACK','성코인',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-043','STACK','레이드인장',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-044','STACK','당근',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-045','FURNITURE','샤넬 컬렉션',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=시그니엘; exp=56050"}',0,1),
('ITEM-RWD-046','STACK','미니펫강화석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-047','STACK','경찰과도둑',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-048','STACK','주간상자',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-049','STACK','월간상자',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-050','STACK','길드공헌훈장',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-051','STACK','확성기',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-052','STACK','전설강화석',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-053','STACK','다이아상자',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-054','MEMBER_TITLE','황제 칭호',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"price=100000000; 레거시 전체 칭호 문자열은 DB metadata에 보존"}',0,1),
('ITEM-RWD-055','MINI_PET','태초꼬치🍢',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-056','MINI_PET','태초야키🔥',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-057','MINI_PET','태초숯불꼬치♨️',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-058','MINI_PET','태초한판꼬치🥢',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-059','MINI_PET','태초꼬치집🏮',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-060','MINI_PET','태초닭꼬치🐔',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-061','MINI_PET','태초불향꼬치🔥',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-062','MINI_PET','태초한잔꼬치🍶',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-063','MINI_PET','태초꼬치포차🍻',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-064','MINI_PET','태초직화꼬치🔥',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1"}',0,1),
('ITEM-RWD-065','STACK','펫강화확률UP(30%)',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-066','STACK','대형슬롯상자',1,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":null}',0,1),
('ITEM-RWD-067','MINI_PET','샤넬 햄스터',0,'{"source":"legacy-main.js","definitionStatus":"DB_SEED_READY","note":"grade=전설; battleExp=30000000; price=999"}',0,1)
ON DUPLICATE KEY UPDATE item_type=VALUES(item_type),item_name=VALUES(item_name),stackable=VALUES(stackable),metadata_json=VALUES(metadata_json),enabled=0,row_version=row_version+1;

DELETE FROM package_rewards WHERE package_id IN ('PKG-078','PKG-088','PKG-093','PKG-097','PKG-098','PKG-100','PKG-103','PKG-105','PKG-156','PKG-157','PKG-158','PKG-159','PKG-160','PKG-161','PKG-162','PKG-165','PKG-166','PKG-186','PKG-188','PKG-201','PKG-203','PKG-204','PKG-206','PKG-207','PKG-208','PKG-209','PKG-210','PKG-211','PKG-212');

INSERT INTO package_rewards (package_id,reward_order,item_id,quantity,probability,target_selector,metadata_override_json) VALUES
('PKG-078',1,'ITEM-RWD-001',20000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-078',2,'ITEM-RWD-002',20,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-078',3,'ITEM-RWD-003',30,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-078',4,'ITEM-RWD-004',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"레거시 원문 품목명 괄호 누락 보존","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-078',5,'ITEM-RWD-005',5,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-088',1,'ITEM-RWD-006',50000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-088',2,'ITEM-RWD-007',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-088',3,'ITEM-RWD-008',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-088',4,'ITEM-RWD-009',15,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-088',5,'ITEM-RWD-010',5,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',2,'ITEM-RWD-011',9000000,0.1,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 잉어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',3,'ITEM-RWD-011',3000000,0.08,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 연어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',4,'ITEM-RWD-011',9000000,0.08,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 고등어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',5,'ITEM-RWD-011',9000000,0.07,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 은갈치","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',6,'ITEM-RWD-011',30000000,0.06,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 광어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',7,'ITEM-RWD-011',9000000,0.06,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 오징어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',8,'ITEM-RWD-011',6000000,0.06,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 새우","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',9,'ITEM-RWD-011',6000000,0.05,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 문어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',10,'ITEM-RWD-011',36000000,0.05,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 게","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',11,'ITEM-RWD-011',45000000,0.05,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 조개","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',12,'ITEM-RWD-011',75000000,0.03,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 전복","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',13,'ITEM-RWD-011',90000000,0.03,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 장어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',14,'ITEM-RWD-011',84000000,0.03,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 방어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',15,'ITEM-RWD-011',54000000,0.025,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 복어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',16,'ITEM-RWD-011',120000000,0.02,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 참치","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',17,'ITEM-RWD-011',135000000,0.02,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 대게","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',18,'ITEM-RWD-011',60000000,0.02,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 해마","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',19,'ITEM-RWD-011',150000000,0.015,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 랍스터","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',20,'ITEM-RWD-011',90000000,0.01,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 참돔","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-093',21,'ITEM-RWD-011',10000000000,0.001,'WEIGHTED_ADD','{"effect":"WEIGHTED_ADD","definitionStatus":"RULE_REQUIRED","note":"성공 70% 내부 가중치; 보상 결과 황금잉어","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-097',1,'ITEM-RWD-012',5000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-097',2,'ITEM-RWD-013',10000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-097',3,'ITEM-RWD-014',150,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-098',1,'ITEM-RWD-012',4000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-098',2,'ITEM-RWD-013',7000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-098',3,'ITEM-RWD-014',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-098',4,'ITEM-RWD-015',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-098',5,'ITEM-RWD-016',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-100',1,'ITEM-RWD-017',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=로열 루미에르; exp=140000; rate=0.00001","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-103',1,'ITEM-RWD-018',1000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-103',2,'ITEM-RWD-019',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-105',1,'ITEM-RWD-020',3000,1,'DYNAMIC_DRAW_UP_TO_BAG_CAPACITY','{"effect":"DYNAMIC_DRAW_UP_TO_BAG_CAPACITY","definitionStatus":"RULE_REQUIRED","note":"miniPetData.gradeTable + miniPetData.miniPet; 최대 3000; 성공 수만 소비","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-156',1,'ITEM-RWD-021',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=창조; battleExp=1350000; castleExp=1350000; raidExp=1350000","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-157',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-157',2,'ITEM-RWD-023',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-157',3,'ITEM-RWD-024',30,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-157',4,'ITEM-RWD-025',700,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-157',5,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-158',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-158',2,'ITEM-RWD-023',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-158',3,'ITEM-RWD-024',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-158',4,'ITEM-RWD-025',700,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-158',5,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',2,'ITEM-RWD-026',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',3,'ITEM-RWD-023',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',4,'ITEM-RWD-024',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',5,'ITEM-RWD-025',700,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-159',6,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-160',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-160',2,'ITEM-RWD-026',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-160',3,'ITEM-RWD-023',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-160',4,'ITEM-RWD-024',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-160',5,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',2,'ITEM-RWD-026',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',3,'ITEM-RWD-023',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',4,'ITEM-RWD-024',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',5,'ITEM-RWD-025',1000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-161',6,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',1,'ITEM-RWD-022',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',2,'ITEM-RWD-027',30,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',3,'ITEM-RWD-026',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',4,'ITEM-RWD-023',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',5,'ITEM-RWD-024',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',6,'ITEM-RWD-025',1000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-162',7,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-165',1,'ITEM-RWD-012',1500,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-165',2,'ITEM-RWD-028',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=창세; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-166',1,'ITEM-RWD-012',2000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-166',2,'ITEM-RWD-029',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=창조; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-186',1,'ITEM-RWD-030',20,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-186',2,'ITEM-RWD-031',35,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-186',3,'ITEM-RWD-032',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-186',4,'ITEM-RWD-033',40,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-186',5,'ITEM-RWD-034',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',1,'ITEM-RWD-035',300,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',2,'ITEM-RWD-036',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',3,'ITEM-RWD-024',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',4,'ITEM-RWD-037',1000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',5,'ITEM-RWD-038',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',6,'ITEM-RWD-039',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-188',7,'ITEM-RWD-040',1,1,'UNIFORM_RANDOM_REPLACE','{"effect":"UNIFORM_RANDOM_REPLACE","definitionStatus":"RULE_REQUIRED","note":"보유 펫 외형 7종 중 1종; 사전 보유 검증 및 원자 처리","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',1,'ITEM-RWD-013',220,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',2,'ITEM-RWD-039',2,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',3,'ITEM-RWD-041',3000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',4,'ITEM-RWD-042',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',5,'ITEM-RWD-043',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-201',6,'ITEM-RWD-011',200000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',1,'ITEM-RWD-013',350,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',2,'ITEM-RWD-039',3,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',3,'ITEM-RWD-041',3000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',4,'ITEM-RWD-044',60,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',5,'ITEM-RWD-016',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',6,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-203',7,'ITEM-RWD-045',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=시그니엘; exp=56050","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',1,'ITEM-RWD-012',50000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',2,'ITEM-RWD-013',50000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',3,'ITEM-RWD-046',10000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',4,'ITEM-RWD-047',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',5,'ITEM-RWD-024',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',6,'ITEM-RWD-048',10,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',7,'ITEM-RWD-049',3,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',8,'ITEM-RWD-050',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',9,'ITEM-RWD-039',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',10,'ITEM-RWD-042',200,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',11,'ITEM-RWD-051',30,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',12,'ITEM-RWD-030',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',13,'ITEM-RWD-033',100,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',14,'ITEM-RWD-044',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',15,'ITEM-RWD-026',5000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',16,'ITEM-RWD-016',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',17,'ITEM-RWD-023',7000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',18,'ITEM-RWD-025',100000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',19,'ITEM-RWD-052',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',20,'ITEM-RWD-053',500,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',21,'ITEM-RWD-011',3000000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',22,'ITEM-RWD-029',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=창조; exp=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-204',23,'ITEM-RWD-054',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"price=100000000; 레거시 전체 칭호 문자열은 DB metadata에 보존","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',1,'ITEM-RWD-012',2500,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',2,'ITEM-RWD-055',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',3,'ITEM-RWD-056',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',4,'ITEM-RWD-057',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',5,'ITEM-RWD-058',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',6,'ITEM-RWD-059',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',7,'ITEM-RWD-060',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',8,'ITEM-RWD-061',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',9,'ITEM-RWD-062',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',10,'ITEM-RWD-063',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-206',11,'ITEM-RWD-064',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=태초; exp=1; price=1","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-207',1,'ITEM-RWD-011',1000000,1,'UNIFORM_RANDOM_ADD','{"effect":"UNIFORM_RANDOM_ADD","definitionStatus":"RULE_REQUIRED","note":"1,000,000~10,000,000; 1,000,000 단위","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-208',1,'ITEM-RWD-011',1000000,1,'UNIFORM_RANDOM_ADD_OR_REMOVE','{"effect":"UNIFORM_RANDOM_ADD_OR_REMOVE","definitionStatus":"RULE_REQUIRED","note":"-10,000,000~19,000,000; 1,000,000 단위; 음수는 REMOVE","sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-209',1,'ITEM-RWD-042',120,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-209',2,'ITEM-RWD-065',4,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-209',3,'ITEM-RWD-026',1300,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-210',1,'ITEM-RWD-042',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-210',2,'ITEM-RWD-065',2,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-210',3,'ITEM-RWD-026',500,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-211',1,'ITEM-RWD-042',250,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-211',2,'ITEM-RWD-065',7,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-211',3,'ITEM-RWD-026',2700,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',1,'ITEM-RWD-012',25,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',2,'ITEM-RWD-066',5,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',3,'ITEM-RWD-044',20,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',4,'ITEM-RWD-036',50,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',5,'ITEM-RWD-011',100000000,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":null,"sourceEvidence":"main.js 현재 로직 추출"}'),
('PKG-212',6,'ITEM-RWD-067',1,1,'ADD','{"effect":"ADD","definitionStatus":"DB_SEED_READY","note":"grade=전설; battleExp=30000000; price=999","sourceEvidence":"main.js 현재 로직 추출"}');

UPDATE package_catalog SET definition_status='REWARD_SEEDED_DRAFT',enabled=0,row_version=row_version+1 WHERE package_id IN ('PKG-078','PKG-088','PKG-093','PKG-097','PKG-098','PKG-100','PKG-103','PKG-105','PKG-156','PKG-157','PKG-158','PKG-159','PKG-160','PKG-161','PKG-162','PKG-165','PKG-166','PKG-186','PKG-188','PKG-201','PKG-203','PKG-204','PKG-206','PKG-207','PKG-208','PKG-209','PKG-210','PKG-211','PKG-212');
COMMIT;

