START TRANSACTION;

-- 레거시 nonItems 원본을 DB seed로 보존하고 runtime 판정은 item_id FK 정책만 사용한다.
CREATE TABLE IF NOT EXISTS legacy_non_sellable_item_seed (
  legacy_item_name VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  source_code VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (legacy_item_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_sale_policies (
  item_id BIGINT UNSIGNED NOT NULL,
  sellable BOOLEAN NOT NULL DEFAULT FALSE,
  unit_price DECIMAL(30,3) NOT NULL DEFAULT 100000.000,
  source_code VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (item_id),
  CONSTRAINT fk_item_sale_policy_item FOREIGN KEY (item_id) REFERENCES item_definitions(id) ON DELETE RESTRICT,
  CONSTRAINT chk_item_sale_policy_price CHECK (unit_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO legacy_non_sellable_item_seed (legacy_item_name,source_code,active) VALUES
  ('파워냉방패키지👨‍🦲(/잔말말고파워냉방으로틀어)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[10](/호팡오픈10)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[9](/호팡오픈9)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[8](/호팡오픈8)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[7](/호팡오픈7)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[6](/호팡오픈6)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[5](/호팡오픈5)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[4](/호팡오픈4)','data/itemList.json',TRUE),
  ('럭키박스🍀(/럭키오픈)','data/itemList.json',TRUE),
  ('어이~미대리🐹(/미대리오픈)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[3](/호팡오픈3)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[2](/호팡오픈2)','data/itemList.json',TRUE),
  ('이건 첫번째 레슨☝️(/좋은건너만알기)','data/itemList.json',TRUE),
  ('미니펫대전리셋권🐹','data/itemList.json',TRUE),
  ('미니펫 시즌2🐹[1](/미니펫시즌1)','data/itemList.json',TRUE),
  ('펫타이틀권🦊(/펫타이틀이름)','data/itemList.json',TRUE),
  ('티어 승급티켓🎟','data/itemList.json',TRUE),
  ('고급 티어 승급티켓🎫','data/itemList.json',TRUE),
  ('정령 강화석🥀️','data/itemList.json',TRUE),
  ('반지 강화석💍','data/itemList.json',TRUE),
  ('전설의 돌맹이🗿','data/itemList.json',TRUE),
  ('펫 강화석⭐','data/itemList.json',TRUE),
  ('미니펫 시즌2🐹[1](/미니펫시즌2)','data/itemList.json',TRUE),
  ('펫 이름변경권🎫','data/itemList.json',TRUE),
  ('정령패키지🥀(/정령패키지오픈)','data/itemList.json',TRUE),
  ('탈모 패키지🧑‍🦲(/자라나라모리모리)','data/itemList.json',TRUE),
  ('크라운 패키지🦷(/충치멈춰)','data/itemList.json',TRUE),
  ('환생버섯🍄','data/itemList.json',TRUE),
  ('하트💝','data/itemList.json',TRUE),
  ('우표💌','data/itemList.json',TRUE),
  ('정령조각🥀','data/itemList.json',TRUE),
  ('정령상자🥀','data/itemList.json',TRUE),
  ('양념치킨🐔','data/itemList.json',TRUE),
  ('치킨상자🐔','data/itemList.json',TRUE),
  ('잡템☠️','data/itemList.json',TRUE),
  ('잡템상자☠','data/itemList.json',TRUE),
  ('랜덤박스💝','data/itemList.json',TRUE),
  ('선물상자🎁','data/itemList.json',TRUE),
  ('극락상자👹','data/itemList.json',TRUE),
  ('나락상자👹','data/itemList.json',TRUE),
  ('슬롯상자🧳','data/itemList.json',TRUE),
  ('캐슬대전리셋권🐶','data/itemList.json',TRUE),
  ('레이드타격대인장👑(+600👾)','data/itemList.json',TRUE),
  ('캐슬코인🥇','data/itemList.json',TRUE),
  ('캐슬기습공격권🔥(40%)','data/itemList.json',TRUE),
  ('캐슬절대방어권🛡(100%)','data/itemList.json',TRUE),
  ('캐슬고급유닛🧙🏼‍♂(+50💕)','data/itemList.json',TRUE),
  ('캐슬레어유닛⭐(+100💕)','data/itemList.json',TRUE),
  ('캐슬유니크유닛👑(+200💕)','data/itemList.json',TRUE),
  ('캐슬영웅유닛💠(+300💕)','data/itemList.json',TRUE),
  ('캐슬전설유닛🧝🏻‍♀(+500💕유닛🧝🏻‍♀(+500💕)','data/itemList.json',TRUE),
  ('캐슬신화유닛🧚🏻‍♀(+1000💕)','data/itemList.json',TRUE),
  ('캐슬불멸유닛🐉(+1500💕)','data/itemList.json',TRUE),
  ('캐슬불사조유닛🐦‍🔥(+6000💕)','data/itemList.json',TRUE),
  ('계엄령패키지🪖(/여친구함)','data/itemList.json',TRUE),
  ('슬롯가방💼(+10)','data/itemList.json',TRUE),
  ('복주머니🧧','data/itemList.json',TRUE),
  ('꼬츈쿠키🐢','data/itemList.json',TRUE),
  ('월간상자🌸(/월간오픈)','data/itemList.json',TRUE),
  ('주간상자🦋(/주간오픈)','data/itemList.json',TRUE),
  ('초보티켓패키지🎟(/티켓오픈)','data/itemList.json',TRUE),
  ('초보티켓패키지2🎟(/티켓오픈2)','data/itemList.json',TRUE),
  ('초보티켓패키지3🎟(/티켓오픈3)','data/itemList.json',TRUE),
  ('슬롯초보패키지🪙(/슬롯초보오픈)','data/itemList.json',TRUE),
  ('슬롯초보패키지2🪙(/슬롯초보오픈2)','data/itemList.json',TRUE),
  ('슬롯초보패키지3🪙(/슬롯초보오픈3)','data/itemList.json',TRUE),
  ('슬롯초보패키지4🪙(/슬롯초보오픈4)','data/itemList.json',TRUE),
  ('슬롯가방🎒패키지2(/슬롯가방오픈2)','data/itemList.json',TRUE),
  ('슬롯가방🎒패키지(/슬롯가방오픈)','data/itemList.json',TRUE),
  ('캐슬패키지🏰(/캐슬패키지오픈)','data/itemList.json',TRUE),
  ('정규시즌10 패키지🏆(/시즌오픈)','data/itemList.json',TRUE),
  ('레이드패키지👾(/레이드오픈)','data/itemList.json',TRUE),
  ('빼빼로데이 패키지🍭(/내꺼내꺼니꺼내꺼)','data/itemList.json',TRUE),
  ('금괴털러갈래3🚨(/철컹철컹오픈)','data/itemList.json',TRUE),
  ('장드방패키지🛡(/장드방오픈)','data/itemList.json',TRUE),
  ('🪬올마이티 상자(/올마이티오픈)','data/itemList.json',TRUE),
  ('🪽엠퍼러 상자(/엠퍼러오픈)','data/itemList.json',TRUE),
  ('🔮마스터 상자(/마스터오픈)','data/itemList.json',TRUE),
  ('💎다이아 상자(/다이아오픈)','data/itemList.json',TRUE),
  ('👑크라운 상자(/크라운오픈)','data/itemList.json',TRUE),
  ('💠루비 상자(/루비오픈)','data/itemList.json',TRUE),
  ('🔥에이스 상자(/에이스오픈)','data/itemList.json',TRUE),
  ('👻루키 상자(/루키오픈)','data/itemList.json',TRUE),
  ('설날패키지1🍡(/용돈주세요)','data/itemList.json',TRUE),
  ('설날패키지2🍡(/용돈달라고)','data/itemList.json',TRUE),
  ('설날패키지VIP🍡(/용돈내가줄게)','data/itemList.json',TRUE),
  ('정령 이름변경권📝(/정령이름)','data/itemList.json',TRUE),
  ('반지 이름변경권🗯(/반지이름)','data/itemList.json',TRUE),
  ('컴퓨터후원패키지💻(/고마워)','data/itemList.json',TRUE),
  ('발렌타인 패키지🍫(/전X의선물)','data/itemList.json',TRUE),
  ('금괴털러갈래4🚨(/철컹철컹오픈)','data/itemList.json',TRUE),
  ('삼일절 패키지🇰🇷(/대한독립만세)','data/itemList.json',TRUE),
  ('벚꽃소개팅🌸(/소개팅오픈)','data/itemList.json',TRUE),
  ('탈모 패키지2🧑‍🦲(/모리모리자라나라)','data/itemList.json',TRUE),
  ('다이소 패키지📕[1](/다이소오픈1)','data/itemList.json',TRUE),
  ('다이소 패키지📕[2](/다이소오픈2)','data/itemList.json',TRUE),
  ('다이소 패키지📕[3](/다이소오픈3)','data/itemList.json',TRUE),
  ('다이소 패키지📕[4](/다이소오픈4)','data/itemList.json',TRUE),
  ('다이소 패키지📕[5](/다이소오픈5)','data/itemList.json',TRUE),
  ('화이트데이 패키지🍬(/마지막선물)','data/itemList.json',TRUE),
  ('마정석상자🔮','data/itemList.json',TRUE),
  ('마정석🔮','data/itemList.json',TRUE),
  ('시탑 부스터🔮','data/itemList.json',TRUE),
  ('시탑 공략서📜','data/itemList.json',TRUE),
  ('시련의탑리셋권😈','data/itemList.json',TRUE),
  ('시련의탑오픈기념패키지😈(/시련기념오픈)','data/itemList.json',TRUE),
  ('부방상여패키지🤫(/아이고호이님감사힙니다저희에게일용할상여를주시다니감사할따름니다굽십굽신)','data/itemList.json',TRUE),
  ('신입패키지(/3일출석체크안하면계정삭제)매','data/itemList.json',TRUE),
  ('시련의상자😈(/시련오픈)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸(/봄바람휘뚜루마뚜루)','data/itemList.json',TRUE),
  ('다이소 패키지📕[7](/다이소오픈7)','data/itemList.json',TRUE),
  ('다이소 패키지📕[8](/다이소오픈8)','data/itemList.json',TRUE),
  ('현충일 패키지🇰🇷(/평화)','data/itemList.json',TRUE),
  ('호이패키지1🤪(/1줄요약)','data/itemList.json',TRUE),
  ('호이패키지2🤪(/2줄요약)','data/itemList.json',TRUE),
  ('호이패키지3🤪(/3줄요약)','data/itemList.json',TRUE),
  ('호이패키지4🤪(/4줄요약)','data/itemList.json',TRUE),
  ('호이패키지5🤪(/5줄요약)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🎁[13](/초보오픈13)','data/itemList.json',TRUE),
  ('시탑부스터패키지2🔮(/부스터오픈2)','data/itemList.json',TRUE),
  ('전설뽑기패키지🧝🏻‍♀(/전설오픈)','data/itemList.json',TRUE),
  ('🥕당근이세요?','data/itemList.json',TRUE),
  ('🌡️당근온도기(/온도 아이디)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🎁[14](/초보오픈14)','data/itemList.json',TRUE),
  ('슬롯대용량상자🧳','data/itemList.json',TRUE),
  ('당근이지🥕(/당근당근)','data/itemList.json',TRUE),
  ('미니펫외형변경권😺(/미니펫외형)','data/itemList.json',TRUE),
  ('미니펫이름변경권🙀(/미니펫이름)','data/itemList.json',TRUE),
  ('미니펫귀속해제권🐰(/귀속해제)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹[1](/미니오픈1)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹[2](/미니오픈2)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹[3](/미니오픈3)','data/itemList.json',TRUE),
  ('한국전쟁패키지🇰🇷(/한국오픈)','data/itemList.json',TRUE),
  ('확성기📢(/알림 내용 30자)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🎁[16](/초보오픈16)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🎁[15](/초보오픈15)','data/itemList.json',TRUE),
  ('다이소 패키지📕[9](/다이소오픈9)','data/itemList.json',TRUE),
  ('다이소 패키지📕[10](/다이소오픈10)','data/itemList.json',TRUE),
  ('여름휴가패키지😎[1](/여름오픈1)','data/itemList.json',TRUE),
  ('여름휴가패키지😎[2](/여름오픈2)','data/itemList.json',TRUE),
  ('여름휴가패키지😎[3](/여름오픈3)','data/itemList.json',TRUE),
  ('여름휴가패키지😎[4](/여름오픈4)','data/itemList.json',TRUE),
  ('여름휴가패키지😎[5](/여름오픈5)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹[4](/미니오픈4)','data/itemList.json',TRUE),
  ('호이이사영혼참석해키지👷🏻(/이사가즈아)','data/itemList.json',TRUE),
  ('당근이지2🥕(/당근당근2)','data/itemList.json',TRUE),
  ('시탑부스터패키지3🔮(/부스터오픈3)','data/itemList.json',TRUE),
  ('슬롯가방🎒패키지3(/슬롯가방오픈3)','data/itemList.json',TRUE),
  ('어이~미과장🐹(/미과장오픈)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[1000층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[900층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[800층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[700층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[600층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[500층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[400층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[300층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[200층](/타임머신)','data/itemList.json',TRUE),
  ('시련의탑타임머신권⏱️[100층](/타임머신)','data/itemList.json',TRUE),
  ('슬롯패키지🪙[5](/코인오픈5)','data/itemList.json',TRUE),
  ('슬롯패키지🪙[4](/코인오픈4)','data/itemList.json',TRUE),
  ('슬롯패키지🪙[3](/코인오픈3)','data/itemList.json',TRUE),
  ('슬롯패키지🪙[2](/코인오픈2)','data/itemList.json',TRUE),
  ('슬롯패키지🪙[1](/코인오픈1)','data/itemList.json',TRUE),
  ('1달러스토어🤑 패키지(/1일1후원)','data/itemList.json',TRUE),
  ('1달러스토어🤑(/1일1후원)','data/itemList.json',TRUE),
  ('한여름1:1헌팅😎(/저기요멀리서봤는데)','data/itemList.json',TRUE),
  ('파워냉방패키지2👨‍🦲(/잔말말고파워냉방으로틀어2)','data/itemList.json',TRUE),
  ('호상청패키지☀️(/오늘의날씨알려드리겠습니다)','data/itemList.json',TRUE),
  ('로켓배송패키지🚀[1](/호팡오픈1)','data/itemList.json',TRUE),
  ('광복절 패키지🇰🇷(/815)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[1](/돈키1)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[1](/돈키오픈1)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(50%)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(60%)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(70%)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(80%)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(90%)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(100%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(50%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(60%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(70%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(80%)','data/itemList.json',TRUE),
  ('반 강화확률UP💍(90%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(100%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(25%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(30%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(35%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(40%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(45%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(50%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(55%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(60%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(65%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(70%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(75%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(80%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(95%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(100%)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹[5](/미니오픈5)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[3](/돈키오픈3)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[2](/돈키오픈2)','data/itemList.json',TRUE),
  ('펫특성🃏패키지2(/특성패키지오픈)','data/itemList.json',TRUE),
  ('미니펫 강화석💫','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(35%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(40%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(45%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(50%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(55%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(60%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(65%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(70%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(75%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(80%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(85%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(90%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(95%)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(100%)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[4](/돈키오픈4)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[5](/돈키오픈5)','data/itemList.json',TRUE),
  ('냄새나는 💩','data/itemList.json',TRUE),
  ('간바레 호이상🍾[1](/간빠이1)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[2](/간빠이2)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[3](/간빠이3)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[4](/간빠이4)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[5](/간빠이5)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[6](/간빠이6)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[7](/간빠이7)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[8](/간빠이8)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[9](/간빠이9)','data/itemList.json',TRUE),
  ('간바레 호이상🍾[10](/간빠이10)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[6](/돈키오픈6)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[1](/초보오픈1)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[1](/정령패키지오픈1)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[2](/정령패키지오픈2)','data/itemList.json',TRUE),
  ('반지강화패키지💍[1](/반지패키지오픈1)','data/itemList.json',TRUE),
  ('반지강화패키지💍[2](/반지패키지오픈2)','data/itemList.json',TRUE),
  ('반지강화패키지💍[3](/반지패키지오픈3)','data/itemList.json',TRUE),
  ('반지강화패키지💍[4](/반지패키지오픈4)','data/itemList.json',TRUE),
  ('반지강화패키지💍[5](/반지패키지오픈5)','data/itemList.json',TRUE),
  ('반지강화패키지💍[6](/반지패키지오픈6)','data/itemList.json',TRUE),
  ('반지강화패키지💍[7](/반지패키지오픈7)','data/itemList.json',TRUE),
  ('반지강화패키지💍[8](/반지패키지오픈8)','data/itemList.json',TRUE),
  ('반지강화패키지💍[9](/반지패키지오픈9)','data/itemList.json',TRUE),
  ('반지강화패키지💍[10](/반지패키지오픈10)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[2](/초보오픈2)','data/itemList.json',TRUE),
  ('🥀💍⭐️💫UP패키지(/확률업오픈)','data/itemList.json',TRUE),
  ('크라운 패키지2🦷(/충치멈춰2)','data/itemList.json',TRUE),
  ('시탑부스터패키지4🔮(/부스터오픈4)','data/itemList.json',TRUE),
  ('당근이지3🥕(/당근당근3)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[3](/초보오픈3)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[7](/돈키오픈7)','data/itemList.json',TRUE),
  ('돌멩이🪨','data/itemList.json',TRUE),
  ('미니펫🐹 시즌3[1](/시즌3오픈)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[3](/정령패키지오픈3)','data/itemList.json',TRUE),
  ('전도르 익스펙토 패트로넘🧙(/전도르오픈)','data/itemList.json',TRUE),
  ('크라운 패키지3🦷(/충치멈춰3)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[4](/정령패키지오픈4)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[8](/돈키오픈8)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[4](/초보오픈4)','data/itemList.json',TRUE),
  ('티켓뽑기패키지🎟️(/티켓오픈)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[5](/초보오픈5)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/십자군오픈)','data/itemList.json',TRUE),
  ('어이~미차장🐹(/미차장오픈)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[6](/초보오픈6)','data/itemList.json',TRUE),
  ('미니펫🐹 시즌3[2](/시즌3오픈2)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/날씨오픈)','data/itemList.json',TRUE),
  ('추석 한우🥩 선물세트 패키지(상급)(/상급오픈)','data/itemList.json',TRUE),
  ('추석 한우🥩 선물세트 패키지(중급)(/중급오픈)','data/itemList.json',TRUE),
  ('추석 한우🥩 선물세트 패키지(하급)(/하급오픈)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/다크오픈)','data/itemList.json',TRUE),
  ('강화확률뽑기⚒️(/강화뽑기)','data/itemList.json',TRUE),
  ('땅문서📜','data/itemList.json',TRUE),
  ('호이의 편지💌(/읽어본다)','data/itemList.json',TRUE),
  ('당근이지4🥕(/당근당근4)','data/itemList.json',TRUE),
  ('정규시즌11 패키지🏆(/시즌오픈)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/스파오픈)','data/itemList.json',TRUE),
  ('결혼해듀호이🤵👰(/딴딴따라)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[5](/정령패키지오픈5)','data/itemList.json',TRUE),
  ('한글패키지✍️[초급](/한글초급오픈)','data/itemList.json',TRUE),
  ('한글패키지✍️[고급](/한글고급오픈)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[7](/초보오픈7)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[9](/돈키오픈9)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/이단오픈)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[6](/정령패키지오픈6)','data/itemList.json',TRUE),
  ('미니펫🐹 시즌3[3](/시즌3오픈3)','data/itemList.json',TRUE),
  ('시탑부스터패키지5🔮(/부스터오픈5)','data/itemList.json',TRUE),
  ('귀칼한정판패키지⛩️(/귀칼오픈)','data/itemList.json',TRUE),
  ('1호선 빌런패키지🚆(/단소오픈)','data/itemList.json',TRUE),
  ('돈키호테🛒 패키지[10](/돈키오픈10)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[1](/이보게주인장)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[8](/초보오픈8)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[4](/이보게주인장4)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[5](/이보게주인장5)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[6](/이보게주인장6)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[7](/이보게주인장7)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[8](/이보게주인장8)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[9](/이보게주인장9)','data/itemList.json',TRUE),
  ('씁쓸함 가득한 패키지🍂[10](/이보게주인장10)','data/itemList.json',TRUE),
  ('파워난방패키지🥵(/잔말말고파워난방으로틀어1)','data/itemList.json',TRUE),
  ('펫스윗홈인테리어샵🖼️(/샵오픈)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[9](/초보오픈9)','data/itemList.json',TRUE),
  ('할로윈패키지🎃2(/할로윈오픈)','data/itemList.json',TRUE),
  ('할로윈패키지🎃3(/할로윈오픈3)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[10](/초보오픈10)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[7](/정령패키지오픈7)','data/itemList.json',TRUE),
  ('정규시즌12 패키지🏆(/시즌오픈)','data/itemList.json',TRUE),
  ('파워난방패키지🥵(/잔말말고파워난방으로틀어2)','data/itemList.json',TRUE),
  ('호이지갑👛(/지갑털기)','data/itemList.json',TRUE),
  ('카드캡터호이💘(/호이오픈)','data/itemList.json',TRUE),
  ('카드캡터호이💘2(/호이오픈2)','data/itemList.json',TRUE),
  ('파워난방패키지🥵(/잔말말고파워난방으로틀어3)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[11](/초보오픈11)','data/itemList.json',TRUE),
  ('펫스윗홈패키지🏡[1](/홈패키지오픈1)','data/itemList.json',TRUE),
  ('정령 조각🥀','data/itemList.json',TRUE),
  ('덤프트럭패키지🚛[1](/덤프오픈1)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(85%)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[8](/정령패키지오픈8)','data/itemList.json',TRUE),
  ('펫스윗홈패키지🏡[2](/홈패키지오픈2)','data/itemList.json',TRUE),
  ('도레미파솔로시죠?🎶(/크리스마솔로시죠?)','data/itemList.json',TRUE),
  ('덤프트럭패키지🚛[2](/덤프오픈2)','data/itemList.json',TRUE),
  ('펫스윗홈패키지🏡[3](/홈패키지오픈3)','data/itemList.json',TRUE),
  ('파워난방패키지🥵(/잔말말고파워난방으로틀어4)','data/itemList.json',TRUE),
  ('정령강화패키지🥀[9](/정령패키지오픈9)','data/itemList.json',TRUE),
  ('과로패키지😓(/과로오픈)','data/itemList.json',TRUE),
  ('무료패키지5(/호이월드활동에감사드립니다.)','data/itemList.json',TRUE),
  ('호이패키지💩(/똥오픈)','data/itemList.json',TRUE),
  ('맹구패키지👟(/넘어지면좋겠다오픈)','data/itemList.json',TRUE),
  ('리리패키지👸🏻(/뭐든오픈)','data/itemList.json',TRUE),
  ('벨라패키지🦄(/우리벨붕이들오픈)','data/itemList.json',TRUE),
  ('티모패키지🍄(/ㅋㅋㅗㅗ오픈)','data/itemList.json',TRUE),
  ('감자패키지🍟(/대머리감자오픈)','data/itemList.json',TRUE),
  ('진주패키지🐚(/뭔말인지알지오픈)','data/itemList.json',TRUE),
  ('칠가오픈7️⃣(/ㅗㅗㅋㅋ오픈)','data/itemList.json',TRUE),
  ('부방상여패키지3(/고생하셨습니다)','data/itemList.json',TRUE),
  ('덤프트럭패키지🚛[3](/덤프오픈3)','data/itemList.json',TRUE),
  ('파워한파패키지1🥶(/잔말말고패딩입어1)','data/itemList.json',TRUE),
  ('파워한파패키지2🥶(/잔말말고패딩입어1)','data/itemList.json',TRUE),
  ('파워한파패키지2🥶(/잔말말고패딩입어2)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[12](/초보오픈12)','data/itemList.json',TRUE),
  ('파워한파패키지3🥶(/잔말말고패딩입어3)','data/itemList.json',TRUE),
  ('파워한파패키지4🥶(/잔말말고패딩입어4)','data/itemList.json',TRUE),
  ('혼레릿고상자😝(/혼레릿고오픈)','data/itemList.json',TRUE),
  ('택배패키지🚛[1](/택배오픈1)','data/itemList.json',TRUE),
  ('미니펫🐹 시즌4[1](/시즌4오픈1)','data/itemList.json',TRUE),
  ('미니펫🐹엘리트확정패키지(/미니펫엘리트오픈)','data/itemList.json',TRUE),
  ('가구산타컬렉션🎅(/산타오픈)','data/itemList.json',TRUE),
  ('미니펫강화확률UP🐷(30%)','data/itemList.json',TRUE),
  ('택배패키지🚛[2](/택배오픈2)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[13](/초보오픈13)','data/itemList.json',TRUE),
  ('파워솔크패키지1🎄(/잔말말고솔크보내1)','data/itemList.json',TRUE),
  ('택배패키지🚛[3](/택배오픈3)','data/itemList.json',TRUE),
  ('파워솔크패키지2🎄(/잔말말고솔크보내2)','data/itemList.json',TRUE),
  ('가구산타컬렉션2🎅(/산타오픈2)','data/itemList.json',TRUE),
  ('크리스마스패키지🎄(/크리스마스오픈)','data/itemList.json',TRUE),
  ('메리크리스마스패키지🎄(/메리크리스마스 오픈)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[1](/펫강화패키지오픈1)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[2](/펫강화패키지오픈2)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[3](/펫강화패키지오픈3)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[4](/펫강화패키지오픈4)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[5](/펫강화패키지오픈5)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(90%)','data/itemList.json',TRUE),
  ('레이드막타패키지👾(/막타오픈)','data/itemList.json',TRUE),
  ('파워솔크패키지3🎄(/잔말말고솔크보내3)','data/itemList.json',TRUE),
  ('파워한파패키지5🥶(/잔말말고패딩입어5)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[14](/초보오픈14)','data/itemList.json',TRUE),
  ('확률UP패키지🥀💍🌟🐷(/확률업오픈)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(90%)','data/itemList.json',TRUE),
  ('무료신년패키지🌅(/2026년)','data/itemList.json',TRUE),
  ('신년패키지🌅(/2026년병오년)','data/itemList.json',TRUE),
  ('메리크리스마스패키지🎄(/메리크리스마스오픈)','data/itemList.json',TRUE),
  ('캐슬전설유닛🧝🏻‍♀(+500💕)','data/itemList.json',TRUE),
  ('당근을흔들어줘🥕[1](/흔들흔들1)','data/itemList.json',TRUE),
  ('택배패키지🚛[4](/택배오픈4)','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[6](/펫강화패키지오픈6)','data/itemList.json',TRUE),
  ('가구 부띠끄상자🧳(/부띠끄오픈)','data/itemList.json',TRUE),
  ('가구새복컬렉션1🧧(/새복오픈1)','data/itemList.json',TRUE),
  ('파워새복패키지1🧧(/잔말말고새복보내1)','data/itemList.json',TRUE),
  ('시탑부스터패키지5🔮(/부스터오픈6)','data/itemList.json',TRUE),
  ('마법사패키지🧙🏼‍♂(/막타오픈3)','data/itemList.json',TRUE),
  ('시탑부스터패키지6🔮(/부스터오픈6)','data/itemList.json',TRUE),
  ('도둑빼찌🥷','data/itemList.json',TRUE),
  ('경찰빼찌👮','data/itemList.json',TRUE),
  ('펫강화패키지2⭐️[7](/펫강화패키지오픈7)','data/itemList.json',TRUE),
  ('파워새복패키지2🧧(/잔말말고새복보내2)','data/itemList.json',TRUE),
  ('광산패키지🪨[1](/광산오픈1)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[15](/초보오픈15)','data/itemList.json',TRUE),
  ('미니펫 엘리트상자👝(/엘리트상자오픈)','data/itemList.json',TRUE),
  ('3주년 참여자패키지(/3주년벙참여자)','data/itemList.json',TRUE),
  ('3주년 찬조패키지(/3주년벙찬조자)','data/itemList.json',TRUE),
  ('택배패키지🚛[5](/택배오픈5)','data/itemList.json',TRUE),
  ('파워개추워패키지1🥶(/잔말말고내복입어1)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[16](/초보오픈16)','data/itemList.json',TRUE),
  ('파워개추워패키지2🥶(/잔말말고내복입어2)','data/itemList.json',TRUE),
  ('호이 남','data/itemList.json',TRUE),
  ('광산패키지🪨[2](/광산오픈2)','data/itemList.json',TRUE),
  ('미니펫 시즌5🐹[1](/미니펫시즌5)','data/itemList.json',TRUE),
  ('파워개추워패키지3🥶(/잔말말고내복입어3)','data/itemList.json',TRUE),
  ('파워개추워패키지4🥶(/잔말말고내복입어4)','data/itemList.json',TRUE),
  ('강화박스⭐(/강화박스오픈)','data/itemList.json',TRUE),
  ('이벤트박스✡️(/이벤박스오픈)','data/itemList.json',TRUE),
  ('전도르던전박스🗿(/전도르박스오픈)','data/itemList.json',TRUE),
  ('펫던전 입장권🌋','data/itemList.json',TRUE),
  ('광산패키지🪨[3](/광산오픈3)','data/itemList.json',TRUE),
  ('보물지도🗺️','data/itemList.json',TRUE),
  ('탐험확률UP🗻(10%)','data/itemList.json',TRUE),
  ('탐험확률UP🗻(50%)','data/itemList.json',TRUE),
  ('매력던전박스💕(/매력박스오픈)','data/itemList.json',TRUE),
  ('먼치킨막타패키지🌟(/막타오픈3)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[17](/초보오픈17)','data/itemList.json',TRUE),
  ('자동탐험권🌄','data/itemList.json',TRUE),
  ('펫먹이🍼','data/itemList.json',TRUE),
  ('펫탐험패키지⛰️[1](/조아탐험1)','data/itemList.json',TRUE),
  ('탐험확률UP🗻(20%)','data/itemList.json',TRUE),
  ('탐험확률UP🗻(30%)','data/itemList.json',TRUE),
  ('탐험확률UP🗻(40%)','data/itemList.json',TRUE),
  ('미니펫던전박스🐹(/미니펫던전박스오픈)','data/itemList.json',TRUE),
  ('펫먹이상자📦(/상자오픈)','data/itemList.json',TRUE),
  ('펫 친밀도🐾','data/itemList.json',TRUE),
  ('펫먹이특식🥡(/특식오픈)','data/itemList.json',TRUE),
  ('형욱이패키지🍼(/주인탓입니다)','data/itemList.json',TRUE),
  ('미니펫🐹엘리트확정패키지2(/미니펫엘리트오픈2)','data/itemList.json',TRUE),
  ('형욱이패키지2🍼(/주인탓입니다2)','data/itemList.json',TRUE),
  ('설날패키지1🍡(/용돈주세요2)','data/itemList.json',TRUE),
  ('설날패키지2🍡🍡(/용돈달라고2)','data/itemList.json',TRUE),
  ('설날패키지VIP🍡🍡(/용돈내가줄게2)','data/itemList.json',TRUE),
  ('설날패키지1🍡🍡(/용돈주세요2)','data/itemList.json',TRUE),
  ('양계장던전박스🐓(/양계장박스오픈)','data/itemList.json',TRUE),
  ('경찰과 도둑🚨(/삐뽀삐뽀)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[18](/초보오픈18)','data/itemList.json',TRUE),
  ('행운의박스🍀(/행운의박스오픈)','data/itemList.json',TRUE),
  ('파워독립만세패키지1🇰🇷(/잔말말고대한독립만세1)','data/itemList.json',TRUE),
  ('황제패키지👑[1](/황제패키지오픈1)','data/itemList.json',TRUE),
  ('정령강화확률UP🥀(30%)','data/itemList.json',TRUE),
  ('반지강화확률UP💍(30%)','data/itemList.json',TRUE),
  ('펫강화확률UP🌟(20%)','data/itemList.json',TRUE),
  ('파워독립만세패키지2🇰🇷(/잔말말고대한독립만세2)','data/itemList.json',TRUE),
  ('오톡사람들완전히멘탈이나가버렸습니다😱(/멘탈오픈)','data/itemList.json',TRUE),
  ('파워독립만세패키지3🇰🇷(/잔말말고대한독립만세3)','data/itemList.json',TRUE),
  ('펫탐험패키지⛰️[2](/조아탐험2)','data/itemList.json',TRUE),
  ('파워독립만세패키지4🇰🇷(/잔말말고대한독립만세4)','data/itemList.json',TRUE),
  ('길드공헌훈장🌟(/길드공헌 숫자)','data/itemList.json',TRUE),
  ('형욱이패키지3🍼(/주인탓입니다3)','data/itemList.json',TRUE),
  ('길드창고패키지🧳(/길드창고패키지오픈)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[20](/초보오픈20)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[19](/초보오픈20)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[19](/초보오픈19)','data/itemList.json',TRUE),
  ('길드탈퇴권👋(/길드탈퇴 길드명)','data/itemList.json',TRUE),
  ('길드자원분배🫂(/길드분배)','data/itemList.json',TRUE),
  ('길드마크변경권🔖(/길드마크변경 이모지)','data/itemList.json',TRUE),
  ('파워독립만세패키지5🇰🇷(/잔말말고대한독립만세5)','data/itemList.json',TRUE),
  ('길드이름변경권🪧(/길드이름변경 이름)','data/itemList.json',TRUE),
  ('팬던트 강화석📿','data/itemList.json',TRUE),
  ('길드공헌스타터패키지🎖️[1](/길드스타터오픈1)','data/itemList.json',TRUE),
  ('길드가입권🍭(/길드가입 길드명','data/itemList.json',TRUE),
  ('길드가입권🍭(/길드가입 숫자)','data/itemList.json',TRUE),
  ('파워벚꽃패키지1🌸(/잔말말고벚꽃보러가지마1)','data/itemList.json',TRUE),
  ('미니펫뽑기🐹(/미니펫오픈)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[1](/봄이그렇게)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[2](/도좋냐)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[3](/멍퉁이들아)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[4](/버꼬치)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[5](/그렇게도)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[6](/좋냐멍퉁이들아)','data/itemList.json',TRUE),
  ('길드공헌스타터패키지🎖️[2](/길드스타터오픈2)','data/itemList.json',TRUE),
  ('미니펫 패키지🐹(/미니펫패키지오픈)','data/itemList.json',TRUE),
  ('미니펫강화석패키지💫(/미강오픈)','data/itemList.json',TRUE),
  ('미니펫 패키지🐹[2](/미니펫패키지오픈2)','data/itemList.json',TRUE),
  ('길드공헌스타터패키지🎖️[3](/길드스타터오픈3)','data/itemList.json',TRUE),
  ('낚시패키지🎣[1](/낚시오픈)','data/itemList.json',TRUE),
  ('파워벚꽃패키지2🌸(/잔말말고벚꽃보러가지마2)','data/itemList.json',TRUE),
  ('컬렉션창조패키지🐹(/컬렉션창조오픈)','data/itemList.json',TRUE),
  ('컬렉션창세패키지🐹(/컬렉션창세오픈)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[7](/어차피)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[8](/다시오톡으로)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[9](/돌아온다)','data/itemList.json',TRUE),
  ('벚꽃패키지🌸[10](/만카이)','data/itemList.json',TRUE),
  ('파워벚꽃패키지3🌸(/잔말말고벚꽃보러가지마3)','data/itemList.json',TRUE),
  ('벚꽃슈파라이트슬림0.1미리🍭(/이쁜걸로주세요)','data/itemList.json',TRUE),
  ('호월🐹(/호월오픈)','data/itemList.json',TRUE),
  ('길드공헌스타터패키지🎖️[4](/길드스타터오픈4)','data/itemList.json',TRUE),
  ('파워벚꽃패키지4🌸(/잔말말고벚꽃보러가지마4)','data/itemList.json',TRUE),
  ('황제패키지👑[2](/황제패키지오픈2)','data/itemList.json',TRUE),
  ('광산패키지🪨[4](/광산오픈4)','data/itemList.json',TRUE),
  ('태초야키토리 10세트🥩(/이랏싸이마쎄)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[21](/초보오픈21)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[22](/초보오픈22)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[23](/초보오픈23)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[24](/초보오픈24)','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[25](/초보오픈25)','data/itemList.json',TRUE),
  ('파워벚꽃패키지5🌸(/잔말말고벚꽃보러가지마5)','data/itemList.json',TRUE),
  ('광산패키지🪨[5](/광산오픈5)','data/itemList.json',TRUE),
  ('가구귀속해제권🛋️(/가구해제 숫자)','data/itemList.json',TRUE),
  ('타이틀선물권💝(/타이틀선물 닉네임 내용)','data/itemList.json',TRUE),
  ('정령박스🥀(/정령박스오픈)','data/itemList.json',TRUE),
  ('반지박스💍(/반지박스오픈)','data/itemList.json',TRUE),
  ('펫스킬북📙(/펫스킬오픈)','data/itemList.json',TRUE),
  ('영지절대방어권🛡(50%)','data/itemList.json',TRUE),
  ('영지기습공격권🔥(60%)','data/itemList.json',TRUE),
  ('영지절대방어권🛡(80%)','data/itemList.json',TRUE),
  ('영지기습공격권🔥(90%)','data/itemList.json',TRUE),
  ('펫스킬소멸권🧙‍♂️(/펫스킬소멸 번호)','data/itemList.json',TRUE),
  ('호이베이스볼⚾️(/투수던집니다)','data/itemList.json',TRUE),
  ('형욱이패키지4🍼(/주인탓입니다4)','data/itemList.json',TRUE),
  ('길드공헌스타터패키지🎖️[5](/길드스타터오픈5)','data/itemList.json',TRUE),
  ('노동절패키지🪏(/일어나돈벌어야지)','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[1](/나한테잘하자1)','data/itemList.json',TRUE),
  ('🌋 대균열 유도권(/대균열)','data/itemList.json',TRUE),
  ('🌌 균열 유도권(/균열)','data/itemList.json',TRUE),
  ('🌪️ 전쟁불안정 증폭권(/불안정)','data/itemList.json',TRUE),
  ('🚑 전쟁불안정 감소권(/안정)','data/itemList.json',TRUE),
  ('어린이날패키지🚸(/오픈하면어린이가됩니다)','data/itemList.json',TRUE),
  ('도판민패키지🤩[1](/도파민오픈1)','data/itemList.json',TRUE),
  ('길드영지전쟁패키지🏰[1](/길드영지오픈1)','data/itemList.json',TRUE),
  ('도파민패키지🤩[1](/도파민오픈1)','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[2](/나한테잘하자2)','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[3](/나한테잘하자3)','data/itemList.json',TRUE),
  ('부처님오신날🇰🇷(/오픈하면부처가됩니다)','data/itemList.json',TRUE),
  ('어버이날패키지🧧(/오픈하면어른이됩니다)','data/itemList.json',TRUE),
  ('나랑 소풍 갈사람✋(/소풍오픈)','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[4](/나한테잘하자4)','data/itemList.json',TRUE),
  ('무료패키지12(/호이월드활동에감사드립니다.)','data/itemList.json',TRUE),
  ('길드영지전쟁패키지🏰[2](/길드영지오픈2)','data/itemList.json',TRUE),
  ('도파민패키지🤩[2](/도파민오픈2)','data/itemList.json',TRUE),
  ('오톡소개팅💘(/안녕하세요?)','data/itemList.json',TRUE),
  ('자유시장회원권🏪','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[26](/초보오픈26)','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[5](/나한테잘하자5)','data/itemList.json',TRUE),
  ('펫탐험패키지⛰️[1](/펫탐험오픈1)','data/itemList.json',TRUE),
  ('회의명예표창🎖️','data/itemList.json',TRUE),
  ('핵꿀밤🥊(/펀치)','data/itemList.json',TRUE),
  ('도파민패키지🤩[3]','data/itemList.json',TRUE),
  ('미니펫강화석패키지💫','data/itemList.json',TRUE),
  ('초보자 스타터패키지🌟[1-26]','data/itemList.json',TRUE),
  ('파워가정의달패키지🧑‍🧑‍🧒‍🧒[6]','data/itemList.json',TRUE),
  ('자유시장회원권🏪+주간🦋 20개','data/itemList.json',TRUE),
  ('미니펫강화석대용량패키지💫','data/itemList.json',TRUE)
ON DUPLICATE KEY UPDATE source_code=VALUES(source_code),active=VALUES(active);

INSERT INTO item_sale_policies (item_id,sellable,unit_price,source_code,row_version)
SELECT item.id,IF(seed.legacy_item_name IS NULL,TRUE,FALSE),100000.000,'data/itemList.json',1
FROM item_definitions item
LEFT JOIN legacy_non_sellable_item_seed seed ON seed.legacy_item_name=item.display_name AND seed.active=TRUE
ON DUPLICATE KEY UPDATE sellable=VALUES(sellable),unit_price=VALUES(unit_price),source_code=VALUES(source_code),row_version=row_version+1;

INSERT INTO command_registry (command_code,handler_key,auth_scope,rollout_state,enabled,version)
VALUES ('INVENTORY_BULK_SELL','inventory_bulk_sell','VERIFIED_USER','SHADOW',1,1)
ON DUPLICATE KEY UPDATE handler_key=VALUES(handler_key),auth_scope=VALUES(auth_scope),version=VALUES(version);

INSERT INTO command_aliases (command_text,command_code,active)
VALUES ('/전체판매','INVENTORY_BULK_SELL',1)
ON DUPLICATE KEY UPDATE command_code=VALUES(command_code),active=VALUES(active);

COMMIT;
