START TRANSACTION;
CREATE TABLE pet_skill_bulk_grant_operations (operation_id BIGINT UNSIGNED NOT NULL,command_mode ENUM('single','bulk') NOT NULL,requested_count INT UNSIGNED NOT NULL,success_count INT UNSIGNED NOT NULL,failure_count INT UNSIGNED NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(operation_id),CONSTRAINT fk_pet_skill_bulk_grant_operation FOREIGN KEY(operation_id) REFERENCES operations(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE pet_skill_bulk_grant_lines (operation_id BIGINT UNSIGNED NOT NULL,line_no INT UNSIGNED NOT NULL,raw_line TEXT NOT NULL,line_status ENUM('success','failure') NOT NULL,reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,target_player_id BIGINT UNSIGNED NULL,target_pet_id BIGINT UNSIGNED NULL,skill_id BIGINT UNSIGNED NULL,requested_quantity BIGINT UNSIGNED NULL,bag_quantity_before BIGINT UNSIGNED NULL,bag_quantity_after BIGINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(operation_id,line_no),KEY idx_pet_skill_bulk_grant_target(target_player_id,created_at),KEY idx_pet_skill_bulk_grant_skill(skill_id,created_at),CONSTRAINT fk_pet_skill_bulk_grant_line_operation FOREIGN KEY(operation_id) REFERENCES pet_skill_bulk_grant_operations(operation_id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_bulk_grant_line_player FOREIGN KEY(target_player_id) REFERENCES players(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_bulk_grant_line_pet FOREIGN KEY(target_pet_id) REFERENCES player_pets(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_bulk_grant_line_skill FOREIGN KEY(skill_id) REFERENCES skill_definitions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE pet_skill_inventory_ledger (operation_id BIGINT UNSIGNED NOT NULL,sequence_no INT UNSIGNED NOT NULL,player_id BIGINT UNSIGNED NOT NULL,player_pet_id BIGINT UNSIGNED NOT NULL,skill_id BIGINT UNSIGNED NOT NULL,quantity_delta BIGINT NOT NULL,reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(operation_id,sequence_no),KEY idx_pet_skill_inventory_ledger_player(player_id,created_at),KEY idx_pet_skill_inventory_ledger_pet(player_pet_id,created_at),KEY idx_pet_skill_inventory_ledger_skill(skill_id,created_at),CONSTRAINT fk_pet_skill_inventory_ledger_operation FOREIGN KEY(operation_id) REFERENCES operations(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_inventory_ledger_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_inventory_ledger_pet FOREIGN KEY(player_pet_id) REFERENCES player_pets(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_inventory_ledger_skill FOREIGN KEY(skill_id) REFERENCES skill_definitions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO admin_permissions(code,display_name) VALUES('pet.skill.grant','펫스킬 가방 지급') ON DUPLICATE KEY UPDATE display_name=VALUES(display_name);
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT id,'pet.skill.grant' FROM admin_roles WHERE code='super_admin' ON DUPLICATE KEY UPDATE permission_code=VALUES(permission_code);
INSERT INTO command_registry(command_code,handler_key,auth_scope,rollout_state,enabled,version) VALUES('PET_SKILL_BAG_GRANT','pet_skill_bulk_grant','VERIFIED_USER','SHADOW',TRUE,1),('PET_SKILL_BULK_GRANT','pet_skill_bulk_grant','VERIFIED_USER','SHADOW',TRUE,1) ON DUPLICATE KEY UPDATE handler_key=VALUES(handler_key),auth_scope=VALUES(auth_scope),rollout_state=VALUES(rollout_state),enabled=TRUE,version=version+1;
INSERT INTO command_aliases(command_text,command_code,active) VALUES('/펫스킬가방추가','PET_SKILL_BAG_GRANT',TRUE),('/펫스킬일괄지급','PET_SKILL_BULK_GRANT',TRUE) ON DUPLICATE KEY UPDATE command_code=VALUES(command_code),active=TRUE;
COMMIT;
