START TRANSACTION;
CREATE TABLE pet_skill_equip_policy(policy_key VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,intimacy_per_slot BIGINT UNSIGNED NOT NULL,base_slot_limit BIGINT UNSIGNED NOT NULL,textbook_bonus BIGINT UNSIGNED NOT NULL,premium_bonus BIGINT UNSIGNED NOT NULL,bag_limit BIGINT UNSIGNED NOT NULL,PRIMARY KEY(policy_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO pet_skill_equip_policy VALUES('default',100,30,3,7,100);
CREATE TABLE pet_skill_tier_order(tier_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,display_name VARCHAR(64) NOT NULL,tier_order INT UNSIGNED NOT NULL,PRIMARY KEY(tier_code),UNIQUE KEY uq_pet_skill_tier_display(display_name),UNIQUE KEY uq_pet_skill_tier_order(tier_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO pet_skill_tier_order(tier_code,display_name,tier_order) VALUES
(CONCAT('tier_',LEFT(SHA2('새싹',256),16)),'새싹',0),(CONCAT('tier_',LEFT(SHA2('브론즈',256),16)),'브론즈',1),(CONCAT('tier_',LEFT(SHA2('실버',256),16)),'실버',2),(CONCAT('tier_',LEFT(SHA2('골드',256),16)),'골드',3),(CONCAT('tier_',LEFT(SHA2('플레티넘',256),16)),'플레티넘',4),(CONCAT('tier_',LEFT(SHA2('에메랄드',256),16)),'에메랄드',5),(CONCAT('tier_',LEFT(SHA2('다이아',256),16)),'다이아',6),(CONCAT('tier_',LEFT(SHA2('마스터',256),16)),'마스터',7),(CONCAT('tier_',LEFT(SHA2('그랜드마스터',256),16)),'그랜드마스터',8),(CONCAT('tier_',LEFT(SHA2('챌린저',256),16)),'챌린저',9),(CONCAT('tier_',LEFT(SHA2('킹',256),16)),'킹',10),(CONCAT('tier_',LEFT(SHA2('엠퍼러',256),16)),'엠퍼러',11),(CONCAT('tier_',LEFT(SHA2('올마이티',256),16)),'올마이티',12),(CONCAT('tier_',LEFT(SHA2('하얀하트',256),16)),'하얀하트',13),(CONCAT('tier_',LEFT(SHA2('하늘하트',256),16)),'하늘하트',14),(CONCAT('tier_',LEFT(SHA2('노랑하트',256),16)),'노랑하트',15),(CONCAT('tier_',LEFT(SHA2('보라하트',256),16)),'보라하트',16),(CONCAT('tier_',LEFT(SHA2('빨강하트',256),16)),'빨강하트',17);
CREATE TABLE pet_skill_equip_operations(operation_id BIGINT UNSIGNED NOT NULL,player_id BIGINT UNSIGNED NOT NULL,player_pet_id BIGINT UNSIGNED NOT NULL,skill_id BIGINT UNSIGNED NOT NULL,slot_no INT UNSIGNED NOT NULL,inventory_before BIGINT UNSIGNED NOT NULL,inventory_after BIGINT UNSIGNED NOT NULL,slot_limit BIGINT UNSIGNED NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(operation_id),CONSTRAINT fk_pet_skill_equip_op FOREIGN KEY(operation_id) REFERENCES operations(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_equip_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_equip_pet FOREIGN KEY(player_pet_id) REFERENCES player_pets(id) ON DELETE RESTRICT,CONSTRAINT fk_pet_skill_equip_skill FOREIGN KEY(skill_id) REFERENCES skill_definitions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
UPDATE skill_definitions SET rules_json=JSON_SET(COALESCE(rules_json,JSON_OBJECT()),'$.guildLeaderOnly',TRUE) WHERE display_name IN('전투형 지휘관','기사단 증원','징집명령');
UPDATE skill_definitions SET rules_json=JSON_SET(COALESCE(rules_json,JSON_OBJECT()),'$.tierExclusive',TRUE,'$.requiredTier',CASE WHEN display_name LIKE '%엠퍼러의 천공 날개%' THEN '엠퍼러' WHEN display_name LIKE '%올마이티의 전능 부적%' THEN '올마이티' WHEN display_name LIKE '%하얀하트의 순백 반지%' THEN '하얀하트' WHEN display_name LIKE '%하늘하트의 창공 목걸이%' THEN '하늘하트' WHEN display_name LIKE '%노랑하트의 황금 팔찌%' THEN '노랑하트' WHEN display_name LIKE '%보라하트의 환상 보주%' THEN '보라하트' ELSE '빨강하트' END) WHERE display_name REGEXP '엠퍼러의 천공 날개|올마이티의 전능 부적|하얀하트의 순백 반지|하늘하트의 창공 목걸이|노랑하트의 황금 팔찌|보라하트의 환상 보주|빨강하트의 맹세검';
INSERT INTO command_registry(command_code,handler_key,auth_scope,rollout_state,enabled,version) VALUES('PET_SKILL_EQUIP','pet_skill_equip','VERIFIED_USER','SHADOW',TRUE,1) ON DUPLICATE KEY UPDATE handler_key=VALUES(handler_key),auth_scope=VALUES(auth_scope),rollout_state=VALUES(rollout_state),enabled=TRUE,version=version+1;
INSERT INTO command_aliases(command_text,command_code,active) VALUES('/펫스킬장착','PET_SKILL_EQUIP',TRUE) ON DUPLICATE KEY UPDATE command_code=VALUES(command_code),active=TRUE;
COMMIT;
