START TRANSACTION;
CREATE TABLE furniture_inventory_instances(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,player_id BIGINT UNSIGNED NOT NULL,furniture_definition_id BIGINT UNSIGNED NOT NULL,charm_snapshot BIGINT UNSIGNED NOT NULL,grade_display_name VARCHAR(128) NOT NULL DEFAULT '등급없음',status ENUM('bag','placed','sold','removed') NOT NULL DEFAULT 'bag',version BIGINT UNSIGNED NOT NULL DEFAULT 1,acquired_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(id),KEY idx_furniture_instance_bag(player_id,status,charm_snapshot,id),CONSTRAINT fk_furniture_instance_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE RESTRICT,CONSTRAINT fk_furniture_instance_definition FOREIGN KEY(furniture_definition_id) REFERENCES furniture_definitions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE furniture_inventory_ledger(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,operation_id BIGINT UNSIGNED NOT NULL,sequence_no INT UNSIGNED NOT NULL,player_id BIGINT UNSIGNED NOT NULL,furniture_instance_id BIGINT UNSIGNED NOT NULL,status_before VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,status_after VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,reason_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uq_furniture_ledger_operation_sequence(operation_id,sequence_no),CONSTRAINT fk_furniture_ledger_op FOREIGN KEY(operation_id) REFERENCES operations(id) ON DELETE RESTRICT,CONSTRAINT fk_furniture_ledger_instance FOREIGN KEY(furniture_instance_id) REFERENCES furniture_inventory_instances(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE home_furniture_bag_policy(policy_key VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,base_bag_limit BIGINT UNSIGNED NOT NULL,premium_bag_bonus BIGINT UNSIGNED NOT NULL,cleanup_point_per_item DECIMAL(30,3) NOT NULL,PRIMARY KEY(policy_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO home_furniture_bag_policy VALUES('default',10,5,100000);
CREATE TABLE home_furniture_cleanup_operations(operation_id BIGINT UNSIGNED NOT NULL,player_id BIGINT UNSIGNED NOT NULL,charm_limit BIGINT UNSIGNED NOT NULL,removed_count BIGINT UNSIGNED NOT NULL,total_reward DECIMAL(30,3) NOT NULL,point_before DECIMAL(30,3) NOT NULL,point_after DECIMAL(30,3) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(operation_id),CONSTRAINT fk_home_furniture_cleanup_op FOREIGN KEY(operation_id) REFERENCES operations(id) ON DELETE RESTRICT,CONSTRAINT fk_home_furniture_cleanup_player FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO command_registry(command_code,handler_key,auth_scope,rollout_state,enabled,version) VALUES('HOME_FURNITURE_BAG','home_furniture_bag_lifecycle','VERIFIED_USER','SHADOW',TRUE,1),('HOME_FURNITURE_BAG_CLEANUP','home_furniture_bag_lifecycle','VERIFIED_USER','SHADOW',TRUE,1) ON DUPLICATE KEY UPDATE handler_key=VALUES(handler_key),auth_scope=VALUES(auth_scope),rollout_state=VALUES(rollout_state),enabled=TRUE,version=version+1;
INSERT INTO command_aliases(command_text,command_code,active) VALUES('/가구가방','HOME_FURNITURE_BAG',TRUE),('/가구가방정리','HOME_FURNITURE_BAG_CLEANUP',TRUE) ON DUPLICATE KEY UPDATE command_code=VALUES(command_code),active=TRUE;
COMMIT;
