START TRANSACTION;
INSERT INTO support_pass_definitions(pass_code,display_name,active) VALUES('oneday','원데이패스',TRUE) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),active=TRUE;
INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,metadata_json,active,version) VALUES
('one_dollar_store_package','1달러스토어🤑(/1일1후원)','STACK',TRUE,JSON_OBJECT('legacyKey','1달러스토어🤑(/1일1후원)','sourceCommand','/원데이패스구독'),TRUE,1),
('pet_food_special','펫먹이특식🥡(/특식오픈)','STACK',TRUE,JSON_OBJECT('legacyKey','펫먹이특식🥡(/특식오픈)','sourceCommand','/원데이패스구독'),TRUE,1)
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),stackable=TRUE,active=TRUE,version=version+1;
CREATE TABLE one_day_subscription_reward_definitions(reward_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,item_id BIGINT UNSIGNED NOT NULL,quantity BIGINT UNSIGNED NOT NULL,display_order INT UNSIGNED NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(reward_code),UNIQUE KEY uq_one_day_subscription_reward_item(item_id),CONSTRAINT fk_one_day_subscription_reward_item FOREIGN KEY(item_id) REFERENCES item_definitions(id),CONSTRAINT chk_one_day_subscription_reward_quantity CHECK(quantity>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO one_day_subscription_reward_definitions(reward_code,item_id,quantity,display_order,active) SELECT 'ONE_DOLLAR_STORE',id,1,1,TRUE FROM item_definitions WHERE code='one_dollar_store_package' ON DUPLICATE KEY UPDATE item_id=VALUES(item_id),quantity=1,display_order=1,active=TRUE;
INSERT INTO one_day_subscription_reward_definitions(reward_code,item_id,quantity,display_order,active) SELECT 'SPECIAL_PET_FOOD',id,1,2,TRUE FROM item_definitions WHERE code='pet_food_special' ON DUPLICATE KEY UPDATE item_id=VALUES(item_id),quantity=1,display_order=2,active=TRUE;
CREATE TABLE one_day_subscription_grants(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,operation_id BIGINT UNSIGNED NOT NULL,player_id BIGINT UNSIGNED NOT NULL,item_id BIGINT UNSIGNED NOT NULL,quantity BIGINT UNSIGNED NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uq_one_day_subscription_grant(operation_id,player_id,item_id),CONSTRAINT fk_one_day_subscription_grant_operation FOREIGN KEY(operation_id) REFERENCES operations(id),CONSTRAINT fk_one_day_subscription_grant_player FOREIGN KEY(player_id) REFERENCES players(id),CONSTRAINT fk_one_day_subscription_grant_item FOREIGN KEY(item_id) REFERENCES item_definitions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO command_registry(command_code,handler_key,auth_scope,rollout_state,enabled,version) VALUES('ONE_DAY_PASS_SUBSCRIPTION','one_day_pass_subscription','VERIFIED_USER','SHADOW',TRUE,1) ON DUPLICATE KEY UPDATE handler_key=VALUES(handler_key),auth_scope=VALUES(auth_scope),rollout_state=VALUES(rollout_state),enabled=TRUE,version=version+1;
INSERT INTO command_aliases(command_text,command_code,active) VALUES('/원데이패스구독','ONE_DAY_PASS_SUBSCRIPTION',TRUE) ON DUPLICATE KEY UPDATE command_code=VALUES(command_code),active=TRUE;
COMMIT;
