CREATE TABLE IF NOT EXISTS player_mini_pet_collection_title_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id BIGINT UNSIGNED NOT NULL,
  source_scope VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MINI_PET_COLLECTION',
  source_row SMALLINT UNSIGNED NOT NULL,
  legacy_list_index INT UNSIGNED NOT NULL,
  legacy_name VARCHAR(255) NOT NULL,
  legacy_in_date VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_price_json VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  title_id BIGINT UNSIGNED NOT NULL,
  title_catalog_entry_id BIGINT UNSIGNED NOT NULL,
  canonical_instance_id BIGINT UNSIGNED NULL,
  lifecycle_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'OWNED',
  selected TINYINT(1) NOT NULL DEFAULT 0,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  source_operation_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_player_mini_pet_collection_title_source (player_id, source_scope, source_row),
  UNIQUE KEY uq_player_mini_pet_collection_title_instance (canonical_instance_id),
  KEY ix_player_mini_pet_collection_title_order (player_id, lifecycle_code, legacy_list_index, id),
  CONSTRAINT fk_player_mini_pet_collection_title_player FOREIGN KEY (player_id) REFERENCES players(id),
  CONSTRAINT fk_player_mini_pet_collection_title_definition FOREIGN KEY (title_id) REFERENCES title_definitions(id),
  CONSTRAINT fk_player_mini_pet_collection_title_catalog FOREIGN KEY (title_catalog_entry_id) REFERENCES title_definition_catalog_entries(id),
  CONSTRAINT fk_player_mini_pet_collection_title_instance FOREIGN KEY (canonical_instance_id) REFERENCES player_title_instances(id),
  CONSTRAINT fk_player_mini_pet_collection_title_operation FOREIGN KEY (source_operation_id) REFERENCES operations(id),
  CONSTRAINT ck_player_mini_pet_collection_title_scope CHECK (source_scope = 'MINI_PET_COLLECTION'),
  CONSTRAINT ck_player_mini_pet_collection_title_row CHECK (source_row BETWEEN 1 AND 100),
  CONSTRAINT ck_player_mini_pet_collection_title_lifecycle CHECK (lifecycle_code IN ('OWNED', 'REMOVED')),
  CONSTRAINT ck_player_mini_pet_collection_title_selected CHECK (selected IN (0, 1))
) ENGINE=InnoDB;

