CREATE TABLE IF NOT EXISTS data_migration_common_staging_runs (
  common_staging_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  raw_bundle_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  snapshot_manifest_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  extraction_manifest_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  staging_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expected_file_count INT UNSIGNED NOT NULL,
  expected_total_bytes BIGINT UNSIGNED NOT NULL,
  expected_record_count INT UNSIGNED NOT NULL,
  projected_file_count INT UNSIGNED NOT NULL,
  ignored_file_count INT UNSIGNED NOT NULL,
  run_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (common_staging_run_id),
  UNIQUE KEY uq_common_staging_run_source (raw_bundle_sha256, extraction_manifest_sha256),
  CONSTRAINT chk_common_staging_run_status CHECK (run_status IN ('STAGING','COMPLETE')),
  CONSTRAINT chk_common_staging_raw_bundle_hash CHECK (raw_bundle_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_snapshot_hash CHECK (snapshot_manifest_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_manifest_hash CHECK (extraction_manifest_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_result_hash CHECK (staging_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_file_counts CHECK (projected_file_count + ignored_file_count = expected_file_count),
  CONSTRAINT chk_common_staging_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'),
  CONSTRAINT chk_common_staging_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_migration_common_staging_records (
  common_staging_record_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  common_staging_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_system VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_path_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  logical_source_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  source_pointer VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  identity_pointer VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  source_locator_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  owner_locator_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  occurrence_index INT UNSIGNED NOT NULL,
  projection_locator VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  record_domain VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  record_kind VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  projection_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quarantine_reason VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  quantity_value DECIMAL(65,0) NULL,
  observed_time CHAR(19) NULL,
  payload_json JSON NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (common_staging_record_id),
  UNIQUE KEY uq_common_staging_record_locator (common_staging_run_id, source_locator_sha256),
  CONSTRAINT fk_common_staging_record_run FOREIGN KEY (common_staging_run_id)
    REFERENCES data_migration_common_staging_runs(common_staging_run_id) ON DELETE CASCADE,
  CONSTRAINT chk_common_staging_quantity CHECK (quantity_value IS NULL OR quantity_value >= 0),
  CONSTRAINT chk_common_staging_source_path_hash CHECK (source_path_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_source_content_hash CHECK (source_content_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_source_locator_hash CHECK (source_locator_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_owner_locator_hash CHECK (owner_locator_sha256 IS NULL OR owner_locator_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_payload_hash CHECK (payload_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_common_staging_observed_time CHECK (observed_time IS NULL OR observed_time REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'),
  CONSTRAINT chk_common_staging_record_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'),
  CONSTRAINT chk_common_staging_record_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'),
  CONSTRAINT chk_common_staging_projection_status CHECK (
    (projection_status = 'PROJECT' AND quarantine_reason IS NULL) OR
    (projection_status = 'QUARANTINE' AND quarantine_reason IS NOT NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
