-- WBS743 Gate 2 additive object DB transition provider.
-- Requires existing migrations through 460_data_migration_object_domain_import.sql.
-- CREATE TABLE IF NOT EXISTS permits safe re-entry after an unrecorded partial multi-statement run.

CREATE TABLE IF NOT EXISTS canonical_daily_prayer_operations (
  daily_prayer_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reward_quantity BIGINT UNSIGNED NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (daily_prayer_operation_id),
  UNIQUE KEY uq_odbt_463_01_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_01_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_01_02 FOREIGN KEY (item_id) REFERENCES canonical_item_definitions (item_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_01_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_01_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_01_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_home_aggregate_operations (
  home_aggregate_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (home_aggregate_operation_id),
  UNIQUE KEY uq_odbt_463_02_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_02_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_02_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_02_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_02_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_market_operations (
  market_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (market_operation_id),
  UNIQUE KEY uq_odbt_463_03_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_03_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_03_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_03_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_03_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_member_title_operations (
  member_title_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  member_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_member_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (member_title_operation_id),
  UNIQUE KEY uq_odbt_463_04_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_04_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_04_02 FOREIGN KEY (member_title_id) REFERENCES canonical_member_title_definitions (member_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_04_03 FOREIGN KEY (owned_member_title_id) REFERENCES canonical_owned_member_title_instances (owned_member_title_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_04_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_04_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_04_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_mini_pet_title_operations (
  mini_pet_title_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mini_pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_mini_pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_mini_pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (mini_pet_title_operation_id),
  UNIQUE KEY uq_odbt_463_05_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_05_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_05_02 FOREIGN KEY (mini_pet_title_id) REFERENCES canonical_mini_pet_title_definitions (mini_pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_05_03 FOREIGN KEY (owned_mini_pet_title_id) REFERENCES canonical_owned_mini_pet_title_instances (owned_mini_pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_05_04 FOREIGN KEY (owned_mini_pet_id) REFERENCES canonical_owned_mini_pet_instances (owned_mini_pet_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_05_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_05_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_05_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_package_use_operations (
  package_use_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  package_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (package_use_operation_id),
  UNIQUE KEY uq_odbt_463_06_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_06_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_06_02 FOREIGN KEY (package_id) REFERENCES canonical_package_definitions (package_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_06_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_06_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_06_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_pet_explore_operations (
  pet_explore_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  owned_pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reward_quantity BIGINT UNSIGNED NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (pet_explore_operation_id),
  UNIQUE KEY uq_odbt_463_07_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_07_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_07_02 FOREIGN KEY (owned_pet_id) REFERENCES canonical_owned_pet_instances (owned_pet_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_07_03 FOREIGN KEY (item_id) REFERENCES canonical_item_definitions (item_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_07_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_07_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_07_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_pet_title_operations (
  pet_title_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (pet_title_operation_id),
  UNIQUE KEY uq_odbt_463_08_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_08_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_08_02 FOREIGN KEY (pet_title_id) REFERENCES canonical_pet_title_definitions (pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_08_03 FOREIGN KEY (owned_pet_title_id) REFERENCES canonical_owned_pet_title_instances (owned_pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_08_04 FOREIGN KEY (owned_pet_id) REFERENCES canonical_owned_pet_instances (owned_pet_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_08_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_08_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_08_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_player_identity_operations (
  player_identity_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  canonical_player_identity_crosswalk_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  operation_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  replay_namespace VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  payload_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (player_identity_operation_id),
  UNIQUE KEY uq_odbt_463_09_01 (replay_namespace, player_id, request_key),
  CONSTRAINT fk_odbt_463_09_01 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_463_09_02 FOREIGN KEY (canonical_player_identity_crosswalk_id) REFERENCES canonical_player_identity_crosswalks (canonical_player_identity_crosswalk_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_463_09_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_09_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_463_09_status CHECK (operation_status IN ('COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

