-- WBS743 Gate 2 additive object DB transition provider.
-- Requires existing migrations through 460_data_migration_object_domain_import.sql.
-- CREATE TABLE IF NOT EXISTS permits safe re-entry after an unrecorded partial multi-statement run.

CREATE TABLE IF NOT EXISTS canonical_market_transfer_ledger_entries (
  market_transfer_ledger_entry_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  market_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  line_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  transfer_direction VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  currency_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_furniture_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_equipment_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_mini_pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  owned_pet_skill_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  quantity_delta BIGINT NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (market_transfer_ledger_entry_id),
  UNIQUE KEY uq_odbt_464_01_01 (market_operation_id, line_key),
  CONSTRAINT fk_odbt_464_01_01 FOREIGN KEY (market_operation_id) REFERENCES canonical_market_operations (market_operation_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_02 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_03 FOREIGN KEY (item_id) REFERENCES canonical_item_definitions (item_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_04 FOREIGN KEY (currency_id) REFERENCES canonical_currency_definitions (currency_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_05 FOREIGN KEY (owned_furniture_id) REFERENCES object_owned_furniture_instances (owned_furniture_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_06 FOREIGN KEY (owned_equipment_id) REFERENCES canonical_owned_equipment_instances (owned_equipment_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_07 FOREIGN KEY (owned_mini_pet_id) REFERENCES canonical_owned_mini_pet_instances (owned_mini_pet_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_01_08 FOREIGN KEY (owned_pet_skill_id) REFERENCES canonical_owned_pet_skill_stacks (owned_pet_skill_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_464_01_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_464_01_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_464_01_rule_01 CHECK (transfer_direction IN ('DEBIT','CREDIT')),
  CONSTRAINT chk_odbt_464_01_rule_02 CHECK (asset_type IN ('ITEM','CURRENCY','OWNED_FURNITURE','OWNED_EQUIPMENT','OWNED_MINI_PET','OWNED_PET_SKILL')),
  CONSTRAINT chk_odbt_464_01_rule_03 CHECK ((item_id IS NOT NULL) + (currency_id IS NOT NULL) + (owned_furniture_id IS NOT NULL) + (owned_equipment_id IS NOT NULL) + (owned_mini_pet_id IS NOT NULL) + (owned_pet_skill_id IS NOT NULL) = 1),
  CONSTRAINT chk_odbt_464_01_rule_04 CHECK ((asset_type='ITEM' AND item_id IS NOT NULL) OR (asset_type='CURRENCY' AND currency_id IS NOT NULL) OR (asset_type='OWNED_FURNITURE' AND owned_furniture_id IS NOT NULL) OR (asset_type='OWNED_EQUIPMENT' AND owned_equipment_id IS NOT NULL) OR (asset_type='OWNED_MINI_PET' AND owned_mini_pet_id IS NOT NULL) OR (asset_type='OWNED_PET_SKILL' AND owned_pet_skill_id IS NOT NULL)),
  CONSTRAINT chk_odbt_464_01_rule_05 CHECK ((transfer_direction='DEBIT' AND quantity_delta < 0) OR (transfer_direction='CREDIT' AND quantity_delta > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_package_use_reward_ledger_entries (
  package_use_reward_ledger_entry_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  package_use_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reward_sequence INT UNSIGNED NOT NULL,
  asset_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  currency_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  furniture_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  equipment_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  mini_pet_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  member_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  mini_pet_title_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  pet_skill_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  package_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  quantity_delta BIGINT NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY (package_use_reward_ledger_entry_id),
  UNIQUE KEY uq_odbt_464_02_01 (package_use_operation_id, reward_sequence),
  CONSTRAINT fk_odbt_464_02_01 FOREIGN KEY (package_use_operation_id) REFERENCES canonical_package_use_operations (package_use_operation_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_02 FOREIGN KEY (player_id) REFERENCES canonical_players (player_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_03 FOREIGN KEY (item_id) REFERENCES canonical_item_definitions (item_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_04 FOREIGN KEY (currency_id) REFERENCES canonical_currency_definitions (currency_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_05 FOREIGN KEY (furniture_id) REFERENCES object_furniture_definitions (furniture_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_06 FOREIGN KEY (equipment_id) REFERENCES canonical_equipment_definitions (equipment_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_07 FOREIGN KEY (pet_id) REFERENCES canonical_pet_definitions (pet_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_08 FOREIGN KEY (mini_pet_id) REFERENCES canonical_mini_pet_definitions (mini_pet_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_09 FOREIGN KEY (member_title_id) REFERENCES canonical_member_title_definitions (member_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_10 FOREIGN KEY (pet_title_id) REFERENCES canonical_pet_title_definitions (pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_11 FOREIGN KEY (mini_pet_title_id) REFERENCES canonical_mini_pet_title_definitions (mini_pet_title_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_12 FOREIGN KEY (pet_skill_id) REFERENCES canonical_pet_skill_definitions (pet_skill_id) ON DELETE RESTRICT,
  CONSTRAINT fk_odbt_464_02_13 FOREIGN KEY (package_id) REFERENCES canonical_package_definitions (package_id) ON DELETE RESTRICT,
  CONSTRAINT chk_odbt_464_02_insert_time CHECK (INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_464_02_update_time CHECK (UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_odbt_464_02_rule_01 CHECK (reward_sequence > 0),
  CONSTRAINT chk_odbt_464_02_rule_02 CHECK (asset_type IN ('ITEM','CURRENCY','FURNITURE','EQUIPMENT','PET','MINI_PET','MEMBER_TITLE','PET_TITLE','MINI_PET_TITLE','PET_SKILL','PACKAGE')),
  CONSTRAINT chk_odbt_464_02_rule_03 CHECK ((item_id IS NOT NULL) + (currency_id IS NOT NULL) + (furniture_id IS NOT NULL) + (equipment_id IS NOT NULL) + (pet_id IS NOT NULL) + (mini_pet_id IS NOT NULL) + (member_title_id IS NOT NULL) + (pet_title_id IS NOT NULL) + (mini_pet_title_id IS NOT NULL) + (pet_skill_id IS NOT NULL) + (package_id IS NOT NULL) = 1),
  CONSTRAINT chk_odbt_464_02_rule_04 CHECK ((asset_type='ITEM' AND item_id IS NOT NULL) OR (asset_type='CURRENCY' AND currency_id IS NOT NULL) OR (asset_type='FURNITURE' AND furniture_id IS NOT NULL) OR (asset_type='EQUIPMENT' AND equipment_id IS NOT NULL) OR (asset_type='PET' AND pet_id IS NOT NULL) OR (asset_type='MINI_PET' AND mini_pet_id IS NOT NULL) OR (asset_type='MEMBER_TITLE' AND member_title_id IS NOT NULL) OR (asset_type='PET_TITLE' AND pet_title_id IS NOT NULL) OR (asset_type='MINI_PET_TITLE' AND mini_pet_title_id IS NOT NULL) OR (asset_type='PET_SKILL' AND pet_skill_id IS NOT NULL) OR (asset_type='PACKAGE' AND package_id IS NOT NULL)),
  CONSTRAINT chk_odbt_464_02_rule_05 CHECK (quantity_delta > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
