-- WBS767 Gate 2: reusable private-chat denial counter, attempt receipt, and notification destination schema.
-- Notification destinations are operational configuration and are intentionally not seeded here.

CREATE TABLE private_chat_denial_counters (
  private_chat_denial_counter_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  environment_code VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  database_identity VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  external_user_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  attempt_count BIGINT UNSIGNED NOT NULL,
  last_event_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY(private_chat_denial_counter_id),
  UNIQUE KEY uq_private_chat_denial_counter_environment_identity(environment_code,database_identity,provider_code,external_user_id),
  UNIQUE KEY uq_private_chat_denial_counter_environment_ref(private_chat_denial_counter_id,environment_code,database_identity),
  CONSTRAINT fk_private_chat_denial_counter_identity FOREIGN KEY(provider_code,external_user_id) REFERENCES external_identities(provider_code,external_user_id) ON DELETE RESTRICT,
  CONSTRAINT chk_private_chat_denial_counter_environment CHECK(environment_code IN ('dev','prod')),
  CONSTRAINT chk_private_chat_denial_counter_database CHECK(CHAR_LENGTH(database_identity)>0),
  CONSTRAINT chk_private_chat_denial_counter_attempt_count CHECK(attempt_count>=1),
  CONSTRAINT chk_private_chat_denial_counter_insert_time CHECK(INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_private_chat_denial_counter_update_time CHECK(UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE private_chat_denial_notification_channels (
  private_chat_denial_notification_channel_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  environment_code VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  database_identity VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  external_channel_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  delivery_enabled BOOLEAN NOT NULL,
  configuration_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY(private_chat_denial_notification_channel_id),
  UNIQUE KEY uq_private_chat_denial_notification_environment(environment_code,database_identity),
  CONSTRAINT fk_private_chat_denial_notification_channel FOREIGN KEY(provider_code,external_channel_id) REFERENCES channels(provider_code,external_channel_id) ON DELETE RESTRICT,
  CONSTRAINT chk_private_chat_denial_notification_environment CHECK(environment_code IN ('dev','prod')),
  CONSTRAINT chk_private_chat_denial_notification_database CHECK(CHAR_LENGTH(database_identity)>0),
  CONSTRAINT chk_private_chat_denial_notification_enabled CHECK(delivery_enabled IN (0,1)),
  CONSTRAINT chk_private_chat_denial_notification_configuration CHECK(configuration_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_private_chat_denial_notification_insert_time CHECK(INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_private_chat_denial_notification_update_time CHECK(UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE private_chat_denial_attempts (
  private_chat_denial_attempt_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  private_chat_denial_counter_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  environment_code VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  database_identity VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  app_wiring_operation_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  command_code VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  attempt_ordinal BIGINT UNSIGNED NOT NULL,
  denial_reason VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  display_name_snapshot VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  private_room_name_snapshot VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  message_preview_snapshot VARCHAR(103) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  notification_disposition VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  notification_destination_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  result_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY(private_chat_denial_attempt_id),
  UNIQUE KEY uq_private_chat_denial_attempt_event(event_id),
  UNIQUE KEY uq_private_chat_denial_attempt_operation(app_wiring_operation_id),
  UNIQUE KEY uq_private_chat_denial_attempt_ordinal(private_chat_denial_counter_id,attempt_ordinal),
  CONSTRAINT fk_private_chat_denial_attempt_counter_environment FOREIGN KEY(private_chat_denial_counter_id,environment_code,database_identity) REFERENCES private_chat_denial_counters(private_chat_denial_counter_id,environment_code,database_identity) ON DELETE RESTRICT,
  CONSTRAINT fk_private_chat_denial_attempt_event FOREIGN KEY(event_id) REFERENCES event_inbox(event_id) ON DELETE RESTRICT,
  CONSTRAINT fk_private_chat_denial_attempt_app_wiring_operation FOREIGN KEY(app_wiring_operation_id) REFERENCES canonical_app_wiring_operations(app_wiring_operation_id) ON DELETE RESTRICT,
  CONSTRAINT chk_private_chat_denial_attempt_ordinal CHECK(attempt_ordinal>=1),
  CONSTRAINT chk_private_chat_denial_attempt_environment CHECK(environment_code IN ('dev','prod')),
  CONSTRAINT chk_private_chat_denial_attempt_database CHECK(CHAR_LENGTH(database_identity)>0),
  CONSTRAINT chk_private_chat_denial_attempt_reason CHECK(denial_reason IN ('PRIVATE_HOI_PASS_REQUIRED','PRIVATE_CHAT_BLOCKED')),
  CONSTRAINT chk_private_chat_denial_attempt_disposition CHECK(notification_disposition IN ('NOT_DUE','QUEUED','DISABLED')),
  CONSTRAINT chk_private_chat_denial_attempt_destination CHECK((notification_disposition='QUEUED' AND notification_destination_fingerprint REGEXP '^[0-9a-f]{64}$') OR (notification_disposition<>'QUEUED' AND notification_destination_fingerprint IS NULL)),
  CONSTRAINT chk_private_chat_denial_attempt_result CHECK(result_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_private_chat_denial_attempt_insert_time CHECK(INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_private_chat_denial_attempt_update_time CHECK(UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
