-- WBS778: immutable RAW evidence that legacy checkRank/getMyGuildInfo performs no JSON write.
CREATE TABLE legacy_rank_label_validation_runs (
  legacy_rank_label_validation_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  raw_landing_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  common_staging_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  object_domain_import_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  projection_version VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  member_source_path_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  member_source_content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  guild_source_path_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  guild_source_content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  rank_marker_source_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_runtime_source_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  membership_semantic_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  certificate_set_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  validation_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expected_subject_count INT UNSIGNED NOT NULL,
  no_write_count INT UNSIGNED NOT NULL,
  would_delete_count INT UNSIGNED NOT NULL,
  unmapped_count INT UNSIGNED NOT NULL,
  run_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  active_flag BOOLEAN NOT NULL DEFAULT FALSE,
  active_scope_guard VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin
    GENERATED ALWAYS AS (CASE WHEN active_flag THEN 'CHECK_RANK' ELSE NULL END) STORED,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY(legacy_rank_label_validation_run_id),
  UNIQUE KEY uq_legacy_rank_label_validation_input(raw_landing_run_id,object_domain_import_run_id,projection_version),
  UNIQUE KEY uq_legacy_rank_label_validation_active(active_scope_guard),
  CONSTRAINT fk_legacy_rank_label_validation_raw_run FOREIGN KEY(raw_landing_run_id) REFERENCES data_migration_raw_runs(raw_landing_run_id) ON DELETE RESTRICT,
  CONSTRAINT fk_legacy_rank_label_validation_staging_run FOREIGN KEY(common_staging_run_id) REFERENCES data_migration_common_staging_runs(common_staging_run_id) ON DELETE RESTRICT,
  CONSTRAINT fk_legacy_rank_label_validation_import_run FOREIGN KEY(object_domain_import_run_id) REFERENCES data_migration_object_domain_import_runs(object_domain_import_run_id) ON DELETE RESTRICT,
  CONSTRAINT chk_legacy_rank_label_validation_version CHECK(projection_version='LEGACY_RANK_LABEL_SIDE_EFFECT_V1'),
  CONSTRAINT chk_legacy_rank_label_validation_counts CHECK(expected_subject_count=no_write_count+would_delete_count+unmapped_count),
  CONSTRAINT chk_legacy_rank_label_validation_status CHECK(run_status IN ('COMPLETE','REJECTED')),
  CONSTRAINT chk_legacy_rank_label_validation_active CHECK(active_flag=FALSE OR (run_status='COMPLETE' AND would_delete_count=0 AND unmapped_count=0 AND no_write_count=expected_subject_count)),
  CONSTRAINT chk_legacy_rank_label_validation_member_hash CHECK(member_source_content_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_member_path CHECK(member_source_path_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_guild_hash CHECK(guild_source_content_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_guild_path CHECK(guild_source_path_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_marker_hash CHECK(rank_marker_source_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_runtime_source_hash CHECK(legacy_runtime_source_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_semantic_hash CHECK(membership_semantic_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_set_hash CHECK(certificate_set_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_fingerprint CHECK(validation_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_validation_insert_time CHECK(INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_legacy_rank_label_validation_update_time CHECK(UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE legacy_rank_label_side_effect_certificates (
  legacy_rank_label_side_effect_certificate_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_rank_label_validation_run_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  player_id CHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
  source_player_key_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  member_presence_state VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  guild_pointer_state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  side_effect_decision VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  guild_pointer_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  membership_evidence_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  certificate_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  INSERT_USER VARCHAR(100) NOT NULL,
  INSERT_TIME CHAR(19) NOT NULL,
  UPDATE_USER VARCHAR(100) NOT NULL,
  UPDATE_TIME CHAR(19) NOT NULL,
  PRIMARY KEY(legacy_rank_label_side_effect_certificate_id),
  UNIQUE KEY uq_legacy_rank_label_certificate_source(legacy_rank_label_validation_run_id,source_player_key_sha256),
  UNIQUE KEY uq_legacy_rank_label_certificate_player(legacy_rank_label_validation_run_id,player_id),
  CONSTRAINT fk_legacy_rank_label_certificate_run FOREIGN KEY(legacy_rank_label_validation_run_id) REFERENCES legacy_rank_label_validation_runs(legacy_rank_label_validation_run_id) ON DELETE CASCADE,
  CONSTRAINT fk_legacy_rank_label_certificate_player FOREIGN KEY(player_id) REFERENCES canonical_players(player_id) ON DELETE RESTRICT,
  CONSTRAINT chk_legacy_rank_label_certificate_presence CHECK(member_presence_state IN ('PRESENT','ABSENT')),
  CONSTRAINT chk_legacy_rank_label_certificate_guild CHECK(guild_pointer_state IN ('NONE','VALID','STALE_GUILD','MEMBER_MISMATCH')),
  CONSTRAINT chk_legacy_rank_label_certificate_decision CHECK(side_effect_decision IN ('NO_WRITE','WOULD_DELETE','UNMAPPED')),
  CONSTRAINT chk_legacy_rank_label_certificate_source_hash CHECK(source_player_key_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_certificate_pointer_hash CHECK(guild_pointer_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_certificate_membership_hash CHECK(membership_evidence_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_certificate_fingerprint CHECK(certificate_fingerprint REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_legacy_rank_label_certificate_insert_time CHECK(INSERT_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'),
  CONSTRAINT chk_legacy_rank_label_certificate_update_time CHECK(UPDATE_TIME REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
