import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient, DatabaseTransaction } from "../database.js";

const COMMAND_CODE="ADMIN_FULL_SYNC";
const PERMISSION="admin.full_sync.execute";
type Id=string|number|bigint;
export interface AdminFullSyncInput{eventId:string;externalUserId:string;channelId:string;message:string}
export interface AdminFullSyncResult{syncedCount:number;missingMembers:string[];duplicatedMembers:string[];petRemovedCount:number;petTitleMemberCount:number;petTitleRemovedCount:number;trialUserCount:number;trialProgressRemovedCount:number;sourceReused:boolean;data?:string;outboxId?:string}
interface Registry{rollout_state:"LEGACY_ONLY"|"SHADOW"|"CANARY"|"ACTIVE";enabled:number|boolean}
interface Operation{id:Id;result_json:string|AdminFullSyncResult|null}
interface Player{id:Id;status:string;version:Id}
interface Profile{player_id:Id;current_display_name:string;version:Id}
interface Guild{id:Id;status:string;version:Id}
interface Member{guild_id:Id;player_id:Id;role_code:string;version:Id}
interface Projection{player_id:Id;guild_id:Id|null}
interface Pet{id:Id;player_id:Id;display_name:string|null;pet_type_code:string|null;version:Id;member_key:string}
interface Title{title_id:Id;equipped:number|boolean}
interface Trial{season_key:string;player_id:Id;floor:Id;last_win_at:Date|string|null;version:Id;member_key:string}
export const isAdminFullSyncCommand=(message:string):boolean=>message==="/전체동기화";
export function formatAdminFullSyncResult(r:AdminFullSyncResult):string{return ["전체동기화 완료",`길드 동기화: ${r.syncedCount}명`,`길드 누락: ${r.missingMembers.length}명`,`길드 중복: ${r.duplicatedMembers.length}명`,`펫 정리: ${r.petRemovedCount}건`,`펫타이틀 정리: ${r.petTitleRemovedCount}건`,`시련의탑 정리: ${r.trialProgressRemovedCount}건`].join("\n")}
const num=(v:Id):number=>Number(v);
const parse=(v:string|AdminFullSyncResult|null):AdminFullSyncResult|undefined=>v===null?undefined:typeof v==="string"?JSON.parse(v) as AdminFullSyncResult:v;
const hashSource=(p:Player[],f:Profile[],g:Guild[],m:Member[]):string=>createHash("sha256").update(JSON.stringify({p:p.map(x=>[String(x.id),x.status,String(x.version)]),f:f.map(x=>[String(x.player_id),x.current_display_name,String(x.version)]),g:g.map(x=>[String(x.id),x.status,String(x.version)]),m:m.map(x=>[String(x.guild_id),String(x.player_id),x.role_code,String(x.version)])})).digest("hex");

export class AdminFullSyncService{
 constructor(private readonly database:DatabaseClient){}
 async handleIris(input:AdminFullSyncInput):Promise<{status:"changed";data:string;outboxId:string}|{status:"shadow"|"legacy_fallback"}>{
  if(!isAdminFullSyncCommand(input.message))return{status:"legacy_fallback"};
  const rows=await this.database.query<Registry[]>(`SELECT rollout_state,enabled FROM command_registry WHERE command_code=? LIMIT 1`,[COMMAND_CODE]);
  const route=rows[0]?.enabled&&rows[0].rollout_state==="ACTIVE"?"MODERN":rows[0]?.enabled&&rows[0].rollout_state==="SHADOW"?"SHADOW":"LEGACY_FALLBACK";
  await this.database.execute(`INSERT INTO command_routing_decisions(event_id,message_hash,command_code,route,reason_code) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE routing_decision_id=routing_decision_id`,[input.eventId,createHash("sha256").update(input.message).digest("hex"),COMMAND_CODE,route,`registry_${route.toLowerCase()}`]);
  if(route==="SHADOW")return{status:"shadow"};if(route!=="MODERN")return{status:"legacy_fallback"};
  const result=await this.sync(input);return result?{status:"changed",data:result.data!,outboxId:result.outboxId!}:{status:"legacy_fallback"};
 }
 async sync(input:AdminFullSyncInput):Promise<AdminFullSyncResult|undefined>{return this.database.withTransaction(async tx=>{
  await tx.query(`SELECT scope_key FROM admin_full_sync_locks WHERE scope_key='global' FOR UPDATE`);
  const operators=await tx.query<Array<{id:Id}>>(`SELECT o.id FROM admin_operators o JOIN admin_operator_external_identities l ON l.operator_id=o.id JOIN external_identities e ON e.id=l.external_identity_id WHERE e.provider_code='kakao' AND e.external_user_id=? AND e.status='linked' AND o.status='active' AND NOT EXISTS(SELECT 1 FROM admin_operator_permission_overrides d WHERE d.operator_id=o.id AND d.permission_code=? AND d.effect='deny') AND (EXISTS(SELECT 1 FROM admin_operator_permission_overrides a WHERE a.operator_id=o.id AND a.permission_code=? AND a.effect='allow') OR EXISTS(SELECT 1 FROM admin_operator_roles ar JOIN admin_roles r ON r.id=ar.role_id AND r.active=1 JOIN admin_role_permissions rp ON rp.role_id=r.id WHERE ar.operator_id=o.id AND rp.permission_code=?)) LIMIT 1 FOR UPDATE`,[input.externalUserId,PERMISSION,PERMISSION,PERMISSION]);
  if(!operators[0])return undefined;const operatorId=num(operators[0].id),scope=`admin.full-sync:${operatorId}`;
  const old=await tx.query<Operation[]>(`SELECT id,result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? LIMIT 1 FOR UPDATE`,[scope,input.eventId]);const prior=parse(old[0]?.result_json??null);if(prior)return prior;
  const op=await tx.execute(`INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status) VALUES(?,?,?,'admin_operator',?,?,'processing')`,[randomUUID(),scope,input.eventId,operatorId,COMMAND_CODE]);const operationId=Number(op.insertId);
  const players=await tx.query<Player[]>(`SELECT id,status,version FROM players ORDER BY id FOR UPDATE`),guilds=await tx.query<Guild[]>(`SELECT id,status,version FROM guilds ORDER BY id FOR UPDATE`),members=await tx.query<Member[]>(`SELECT guild_id,player_id,role_code,version FROM guild_members ORDER BY guild_id,player_id FOR UPDATE`),profiles=await tx.query<Profile[]>(`SELECT player_id,current_display_name,version FROM player_profiles ORDER BY player_id FOR UPDATE`),projections=await tx.query<Projection[]>(`SELECT player_id,guild_id FROM guild_membership_projections ORDER BY player_id FOR UPDATE`);
  const pmap=new Map(players.map(x=>[String(x.id),x])),fmap=new Map(profiles.map(x=>[String(x.player_id),x])),gmap=new Map(guilds.map(x=>[String(x.id),x])),mmap=new Map<string,Member>(),counts=new Map<string,number>();for(const m of members){const k=String(m.player_id);counts.set(k,(counts.get(k)??0)+1);if(!mmap.has(k))mmap.set(k,m)}
  const label=(id:string)=>fmap.get(id)?.current_display_name??`player:${id}`;const missing=[...new Set(members.filter(m=>pmap.get(String(m.player_id))?.status!=="active"||!fmap.has(String(m.player_id))||gmap.get(String(m.guild_id))?.status!=="active").map(m=>label(String(m.player_id))))],duplicates=[...counts].filter(([,c])=>c>1).map(([id])=>label(id));const sourceHash=hashSource(players,profiles,guilds,members);
  let sourceReused=false,guildRunId:number;const existing=await tx.query<Array<{id:Id}>>(`SELECT id FROM guild_membership_reconciliation_runs WHERE source_hash=? LIMIT 1 FOR UPDATE`,[sourceHash]);
  if(existing[0]){sourceReused=true;guildRunId=num(existing[0].id)}else{const before=new Map(projections.map(x=>[String(x.player_id),x.guild_id===null?null:String(x.guild_id)]));const changed=players.filter(x=>(before.get(String(x.id))??null)!==(mmap.get(String(x.id))?String(mmap.get(String(x.id))!.guild_id):null)).length;const run=await tx.execute(`INSERT INTO guild_membership_reconciliation_runs(operation_id,source_hash,player_count,membership_count,assigned_count,unassigned_count,missing_profile_count,changed_count) VALUES(?,?,?,?,?,?,?,?)`,[operationId,sourceHash,players.length,members.length,mmap.size,players.length-mmap.size,players.filter(x=>!fmap.has(String(x.id))).length,changed]);guildRunId=Number(run.insertId);for(const player of players){const m=mmap.get(String(player.id));await tx.execute(`INSERT INTO guild_membership_reconciliation_snapshots(run_id,player_id,guild_id,profile_missing) VALUES(?,?,?,?)`,[guildRunId,player.id,m?.guild_id??null,fmap.has(String(player.id))?0:1]);const b=before.get(String(player.id))??null,a=m?String(m.guild_id):null;if(b!==a)await tx.execute(`INSERT INTO guild_membership_reconciliation_deltas(run_id,player_id,before_guild_id,after_guild_id,change_type) VALUES(?,?,?,?,?)`,[guildRunId,player.id,b,m?.guild_id??null,b===null?"assigned":a===null?"unassigned":"changed"])}}
  for(const player of players){const m=mmap.get(String(player.id));await tx.execute(`INSERT INTO guild_membership_projections(player_id,guild_id,source_run_id,version,updated_at) VALUES(?,?,?,1,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE guild_id=VALUES(guild_id),source_run_id=VALUES(source_run_id),version=version+IF(NOT(guild_id<=>VALUES(guild_id)),1,0),updated_at=UTC_TIMESTAMP(3)`,[player.id,m?.guild_id??null,guildRunId])}
  const pets=await tx.query<Pet[]>(`SELECT pet.id,pet.player_id,pet.display_name,pet.pet_type_code,pet.version,COALESCE(profile.current_display_name,CONCAT('player:',pet.player_id)) member_key FROM player_pets pet JOIN players player ON player.id=pet.player_id LEFT JOIN player_profiles profile ON profile.player_id=pet.player_id WHERE player.status<>'active' OR profile.player_id IS NULL ORDER BY pet.id FOR UPDATE`);let titleMembers=0,titleCount=0;
  for(const pet of pets){await tx.execute(`INSERT INTO admin_full_sync_pet_removals(operation_id,player_pet_id,player_id,member_key,pet_snapshot_json) VALUES(?,?,?,?,?)`,[operationId,pet.id,pet.player_id,pet.member_key,JSON.stringify({id:String(pet.id),playerId:String(pet.player_id),displayName:pet.display_name,petTypeCode:pet.pet_type_code,version:String(pet.version)})]);const titles=await tx.query<Title[]>(`SELECT title_id,equipped FROM pet_titles WHERE player_pet_id=? ORDER BY title_id FOR UPDATE`,[pet.id]);if(titles.length){titleMembers++;titleCount+=titles.length;await tx.execute(`INSERT INTO admin_full_sync_pet_title_removals(operation_id,player_pet_id,player_id,member_key,title_count,title_assignments_json) VALUES(?,?,?,?,?,?)`,[operationId,pet.id,pet.player_id,pet.member_key,titles.length,JSON.stringify(titles.map(x=>({titleId:String(x.title_id),equipped:Boolean(x.equipped)})))])}for(const table of ["pet_skills","pet_equipment","player_pet_elementals","pet_skill_inventory","player_pet_pendants","player_pet_intimacy","pet_expedition_runs"])await tx.execute(`DELETE FROM ${table} WHERE player_pet_id=?`,[pet.id])}
  for(const pet of pets)await tx.execute(`DELETE FROM pet_titles WHERE player_pet_id=?`,[pet.id]);for(const pet of pets)await tx.execute(`DELETE FROM player_pets WHERE id=?`,[pet.id]);
  const trials=await tx.query<Trial[]>(`SELECT t.season_key,t.player_id,t.floor,t.last_win_at,t.version,COALESCE(profile.current_display_name,CONCAT('player:',t.player_id)) member_key FROM trial_tower_progress t JOIN players player ON player.id=t.player_id LEFT JOIN player_profiles profile ON profile.player_id=t.player_id WHERE player.status<>'active' OR profile.player_id IS NULL ORDER BY t.season_key,t.player_id FOR UPDATE`);for(const t of trials){await tx.execute(`INSERT INTO trial_tower_sync_removals(operation_id,season_key,player_id,member_key,floor,last_win_at,progress_version) VALUES(?,?,?,?,?,?,?)`,[operationId,t.season_key,t.player_id,t.member_key,t.floor,t.last_win_at,t.version]);await tx.execute(`DELETE FROM trial_tower_progress WHERE season_key=? AND player_id=?`,[t.season_key,t.player_id])}
  const result:AdminFullSyncResult={syncedCount:mmap.size,missingMembers:missing,duplicatedMembers:duplicates,petRemovedCount:pets.length,petTitleMemberCount:titleMembers,petTitleRemovedCount:titleCount,trialUserCount:new Set(trials.map(x=>String(x.player_id))).size,trialProgressRemovedCount:trials.length,sourceReused};const phases:[[number,string,unknown],[number,string,unknown],[number,string,unknown],[number,string,unknown],[number,string,unknown]]=[[1,"member",{syncedCount:result.syncedCount,missingMembers:missing,duplicatedMembers:duplicates}],[2,"guild",{reconciliationRunId:guildRunId,sourceHash,sourceReused}],[3,"pet",{removedCount:pets.length}],[4,"petTitle",{memberCount:titleMembers,removedCount:titleCount}],[5,"trialTower",{userCount:result.trialUserCount,removedCount:trials.length}]];for(const [seq,phase,value]of phases)await tx.execute(`INSERT INTO admin_full_sync_phase_results(operation_id,sequence_no,phase_code,result_json) VALUES(?,?,?,?)`,[operationId,seq,phase,JSON.stringify(value)]);
  await tx.execute(`INSERT INTO admin_full_sync_runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(3))`,[operationId,guildRunId,sourceHash,result.syncedCount,missing.length,duplicates.length,pets.length,titleMembers,titleCount,result.trialUserCount,trials.length,JSON.stringify(result)]);await tx.execute(`INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,completed_at) VALUES(?,?,?,'completed','ADMIN_FULL_SYNC_COMPLETED',UTC_TIMESTAMP(3))`,[input.eventId,COMMAND_CODE,operationId]);await tx.execute(`INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,action_code,result_code,change_summary_json) VALUES(?,'admin_operator',?,'system',?,'success',?)`,[operationId,operatorId,COMMAND_CODE,JSON.stringify(result)]);const data=formatAdminFullSyncResult(result),outbox=await tx.execute(`INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json) VALUES(?,'iris',?,'command_reply',?)`,[operationId,input.channelId,JSON.stringify({data})]);result.data=data;result.outboxId=outbox.insertId.toString();await tx.execute(`UPDATE admin_full_sync_runs SET result_json=? WHERE operation_id=?`,[JSON.stringify(result),operationId]);await tx.execute(`UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?`,[JSON.stringify(result),operationId]);return result;
 })}
}

