import { createHash,randomUUID } from "node:crypto";
import type { DatabaseClient,DatabaseTransaction } from "../database.js";
import { ApplicationError } from "../shared/application-error.js";
const USAGE="사용법: /경매등록 [아이템명] [분]",MAX_MINUTES=5_256_000n;
export interface AuctionRegisterCommand{itemName:string;durationMinutes:bigint}
export interface AuctionRegisterResult{status:"registered"|"usage"|"reward_not_found";data:string;listingId?:string;rewardCode?:string;legacyOriginalIndex?:string;endsAt?:string;outboxId:string;replayed?:boolean}
interface Operator{id:bigint;identity_id:bigint;display_name:string}
// 경매등록 exact 사용법과 아이템명·분 전체 형식만 후보로 허용합니다.
export function isAuctionRegisterCandidate(message:string|undefined):boolean{return message==="/경매등록"||(message!==undefined&&/^\/경매등록\s+.+\s+\d+$/.test(message));}
// 마지막 정수 토큰을 분으로, 앞의 공백 포함 문자열을 아이템명으로 해석합니다.
export function parseAuctionRegisterCommand(message:string):AuctionRegisterCommand|null{const match=/^\/경매등록\s+(.+)\s+(\d+)$/.exec(message);if(match===null)return null;const itemName=match[1]!.trim(),duration=BigInt(match[2]!);return itemName===""||duration>MAX_MINUTES?null:{itemName,durationMinutes:duration};}
function key(value:string):string{return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;}
function normalized(value:string):string{return value.trim().replace(/\s+/g," ").toLocaleLowerCase("ko-KR");}
function stored(value:string|AuctionRegisterResult):AuctionRegisterResult{return typeof value==="string"?JSON.parse(value) as AuctionRegisterResult:value;}
function retryable(error:unknown):boolean{const code=(error as{code?:string}).code;return code==="ER_LOCK_DEADLOCK"||code==="ER_LOCK_WAIT_TIMEOUT";}
async function complete(t:DatabaseTransaction,input:{operationId:bigint;eventId:string;destinationId:string;operator:Operator;status:AuctionRegisterResult["status"];data:string;listingId:bigint|null;rewardCode:string|null;legacyIndex:bigint|null;endsAt:string|null;summary:Record<string,unknown>}):Promise<AuctionRegisterResult>{const outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES(?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.operationId,input.destinationId,JSON.stringify({data:input.data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES(?,'STORE_AUCTION_REGISTER',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,input.operationId,input.status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES(?,'admin_operator',?,'auction_listing',?,'auction.register',?,'Iris /경매등록',?,UTC_TIMESTAMP(3))",[input.operationId,input.operator.id,input.listingId,input.status,JSON.stringify(input.summary)]);const result:AuctionRegisterResult={status:input.status,data:input.data,outboxId:outbox.insertId.toString(),replayed:false,...(input.listingId===null?{}:{listingId:input.listingId.toString()}),...(input.rewardCode===null?{}:{rewardCode:input.rewardCode}),...(input.legacyIndex===null?{}:{legacyOriginalIndex:input.legacyIndex.toString()}),...(input.endsAt===null?{}:{endsAt:input.endsAt})};await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),input.operationId]);return result;}
// 코드형 보상 경매를 권한·활성 이름 유일성·원장·응답과 함께 원자 등록합니다.
export class AuctionRegisterService{constructor(private readonly db:DatabaseClient){}async handle(input:{eventId:string;externalUserId:string;channelId:string;message:string}):Promise<AuctionRegisterResult|null>{if(!isAuctionRegisterCandidate(input.message))return null;let last:unknown;for(let attempt=0;attempt<3;attempt+=1){try{return await this.db.withTransaction(t=>this.execute(t,input));}catch(error){last=error;if(!retryable(error)||attempt===2)throw error;}}throw last;}
 private async execute(t:DatabaseTransaction,input:{eventId:string;externalUserId:string;channelId:string;message:string}):Promise<AuctionRegisterResult|null>{const operator=(await t.query<Operator[]>(`SELECT operator.id,identity.id identity_id,operator.display_name FROM external_identities identity JOIN admin_operator_external_identities mapping ON mapping.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=mapping.operator_id AND operator.status='active' JOIN admin_operator_roles assignment ON assignment.operator_id=operator.id JOIN admin_roles role ON role.id=assignment.role_id AND role.active=TRUE JOIN admin_role_permissions permission ON permission.role_id=role.id AND permission.permission_code='auction.register' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' AND NOT EXISTS(SELECT 1 FROM admin_operator_permission_overrides denied WHERE denied.operator_id=operator.id AND denied.permission_code='auction.register' AND denied.effect='deny') ORDER BY role.code='super_admin' DESC,operator.id LIMIT 1 FOR UPDATE`,[input.externalUserId]))[0];if(operator===undefined)return null;
  const claim=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES(?,'auction.register',?,'admin_operator',?,'iris','processing',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)",[randomUUID(),key(input.eventId),operator.id]);const prior=(await t.query<Array<{result_json:string|AuctionRegisterResult|null}>>("SELECT result_json FROM operations WHERE id=? FOR UPDATE",[claim.insertId]))[0]!;if(prior.result_json!==null)return{...stored(prior.result_json),replayed:true};const command=parseAuctionRegisterCommand(input.message);if(command===null)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.channelId,operator,status:"usage",data:USAGE,listingId:null,rewardCode:null,legacyIndex:null,endsAt:null,summary:{mutation:false,reason:"invalid_format_or_duration",maxMinutes:MAX_MINUTES.toString()}});
  await t.query("SELECT lock_code FROM admin_global_locks WHERE lock_code IN ('auction_settlement','auction_register') ORDER BY lock_code FOR UPDATE");const rewards=await t.query<Array<{reward_code:string;display_name:string}>>("SELECT reward_code,display_name FROM auction_reward_catalog WHERE active=TRUE AND (display_name=? OR BINARY reward_code=BINARY ?) ORDER BY reward_code LIMIT 2 FOR UPDATE",[command.itemName,command.itemName]);if(rewards.length!==1)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.channelId,operator,status:"reward_not_found",data:"등록 가능한 코드형 경매 보상을 찾을 수 없습니다.",listingId:null,rewardCode:null,legacyIndex:null,endsAt:null,summary:{mutation:false,itemName:command.itemName,rewardMatches:rewards.length}});const reward=rewards[0]!,itemKey=normalized(command.itemName),legacyIndex=(await t.query<Array<{value:bigint}>>("SELECT COALESCE(MAX(legacy_original_index),0)+1 value FROM auction_listings FOR UPDATE"))[0]?.value??1n;
  try{const listing=await t.execute("INSERT INTO auction_listings(item_name,reward_code,normalized_item_key,highest_bidder_player_id,highest_bid,ends_at,legacy_original_index,duration_minutes,created_by_operator_id,status,version) VALUES(?,?,?,NULL,0,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL ? MINUTE),?,?,?,'active',1)",[reward.display_name,reward.reward_code,itemKey,command.durationMinutes,legacyIndex,command.durationMinutes,operator.id]);await t.execute("INSERT INTO auction_listing_reward_rules(listing_id,sequence_no,reward_code) VALUES(?,1,?)",[listing.insertId,reward.reward_code]);await t.execute("INSERT INTO auction_registration_events(operation_id,listing_id,operator_id,reward_code,item_name,normalized_item_key,duration_minutes,legacy_original_index,listing_version) VALUES(?,?,?,?,?,?,?,?,1)",[claim.insertId,listing.insertId,operator.id,reward.reward_code,reward.display_name,itemKey,command.durationMinutes,legacyIndex]);const ends=(await t.query<Array<{value:string}>>("SELECT DATE_FORMAT(ends_at,'%Y-%m-%d %H:%i:%s') value FROM auction_listings WHERE id=?",[listing.insertId]))[0]!.value,data=`🏪 경매 등록 완료\n상품: ${reward.display_name}\n보상 코드: ${reward.reward_code}\n진행 시간: ${command.durationMinutes}분\n경매 번호: ${legacyIndex}`;return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.channelId,operator,status:"registered",data,listingId:listing.insertId,rewardCode:reward.reward_code,legacyIndex,endsAt:ends,summary:{mutation:true,itemName:reward.display_name,rewardCode:reward.reward_code,normalizedItemKey:itemKey,durationMinutes:command.durationMinutes.toString(),legacyOriginalIndex:legacyIndex.toString()}});}catch(error){if((error as{code?:string}).code==="ER_DUP_ENTRY")throw new ApplicationError("AUCTION_ACTIVE_ITEM_DUPLICATE","같은 상품의 진행 중인 경매가 이미 있습니다.",409);throw error;}
 }
}
