import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient, DatabaseTransaction } from "../database.js";
import { MariaCommandDispatchRepository, type RolloutState } from "../dispatch/command-dispatcher.js";
import { MariaPetInfoRepository } from "../pet/maria-pet-info-repository.js";
import type { PetInfoView } from "../pet/pet-info.js";

export type MatzangTimeCheckCommand={targetName:string}|null;
export type MatzangTimeCheckResult={status:"diagnosed"|"usage"|"missing_user"|"missing_pet";data:string;outboxId:string;auditId:string;totalCharm?:string};
export function isMatzangTimeCheckCommandCandidate(message:string|undefined):boolean{return message==="/맞짱시간체크"||/^\/맞짱시간체크\s+.+$/.test(message??"");}
export function parseMatzangTimeCheckCommand(message:string):MatzangTimeCheckCommand{const match=/^\/맞짱시간체크\s+(.+)$/.exec(message);return match===null?null:{targetName:match[1]!.trim()};}
const key=(value:string)=>value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;
const commas=(value:string)=>value.replace(/\B(?=(\d{3})+(?!\d))/g,",");
export function formatMatzangTimeCheck(view:PetInfoView,t:{total:number;branch:number;lookup:number;projection:number;detail:Array<{label:string;ms:number}>}):string{return["👊 맞짱 시간체크 👊",`기준: [${view.displayName}]`,`━━━━━━━━━━━━`,`전체(응답진입): ${t.total}ms`,`진단분기: ${t.branch}ms`,`홈데이터 로드: ${t.lookup}ms`,`종합매력 계산: ${t.projection}ms`,`━━━━━━━━━━━━`,`종합매력: ${commas(view.charm.total)}💕`,``,`세부 계산📋`,...t.detail.filter(x=>x.ms>0).map(x=>`${x.label}: ${x.ms}ms`),"※ 전투/상대선정/저장은 실행하지 않았습니다."].join("\n");}

// 운영자 맞짱 종합매력 진단을 기존 펫정보 projection과 읽기 전용 원장으로 처리합니다.
export class MatzangTimeCheckService{
 constructor(private readonly db:DatabaseClient,private readonly now:()=>number=Date.now){}
 async handleIris(input:{externalUserId:string;channelId:string;message:string;eventId:string}):Promise<{status:"changed";data:string;outboxId:string}|{status:"shadow"|"legacy_fallback"|"handled_no_reply"}>{
  const code="ADMIN_MATZZANG_TIME_CHECK",definition=(await this.db.query<Array<{rollout_state:RolloutState;enabled:number}>>("SELECT rollout_state,enabled FROM command_registry WHERE command_code=? LIMIT 1",[code]))[0],dispatch=new MariaCommandDispatchRepository(this.db);
  if(definition===undefined||definition.enabled!==1||definition.rollout_state==="LEGACY_ONLY"){await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"LEGACY_FALLBACK",reasonCode:"ROLLOUT_LEGACY_ONLY",commandCode:code,handlerKey:"admin_matzang_time_check"});return{status:"legacy_fallback"};}
  if(definition.rollout_state!=="ACTIVE"){await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"SHADOW",reasonCode:"ROLLOUT_SHADOW",commandCode:code,handlerKey:"admin_matzang_time_check"});return{status:"shadow"};}
  const operator=(await this.db.query<Array<{operator_id:bigint;identity_id:bigint}>>(`SELECT operator.id operator_id,identity.id identity_id FROM external_identities identity JOIN admin_operator_external_identities map ON map.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=map.operator_id AND operator.status='active' JOIN admin_operator_roles ar ON ar.operator_id=operator.id JOIN admin_role_permissions rp ON rp.role_id=ar.role_id AND rp.permission_code='diagnostic.matzang_charm.read' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1`,[input.externalUserId]))[0];if(operator===undefined)return{status:"handled_no_reply"};
  await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"MODERN",reasonCode:"MODERN_ROUTE_ALLOWED",commandCode:code,handlerKey:"admin_matzang_time_check"});
  const started=this.now(),command=parseMatzangTimeCheckCommand(input.message);if(command===null){const result=await this.persist(input,operator,"usage","사용법: /맞짱시간체크 닉네임");return{status:"changed",data:result.data,outboxId:result.outboxId};}
  const lookupStart=this.now(),target=(await this.db.query<Array<{provider_code:string;external_user_id:string}>>(`SELECT identity.provider_code,identity.external_user_id FROM player_profiles profile JOIN players player ON player.id=profile.player_id AND player.status='active' LEFT JOIN external_identities identity ON identity.player_id=player.id AND identity.status='linked' WHERE profile.current_display_name=? ORDER BY identity.id LIMIT 2`,[command.targetName]))[0],lookupMs=this.now()-lookupStart;
  if(target===undefined||target.external_user_id===null){const result=await this.persist(input,operator,"missing_user","존재하지 않는 사용자입니다.");return{status:"changed",data:result.data,outboxId:result.outboxId};}
  const projectionStart=this.now(),view=await new MariaPetInfoRepository(this.db).findByExternalIdentity(target.provider_code,target.external_user_id),projectionMs=this.now()-projectionStart;
  if(view===null){const result=await this.persist(input,operator,"missing_pet",`[${command.targetName}] 님은 펫을 먼저 생성해야 합니다.`);return{status:"changed",data:result.data,outboxId:result.outboxId};}
  const branch=this.now()-started,data=formatMatzangTimeCheck(view,{total:branch,branch,lookup:lookupMs,projection:projectionMs,detail:[{label:"회원·펫·홈 projection",ms:projectionMs}]});const result=await this.persist(input,operator,"diagnosed",data,view.charm.total);return{status:"changed",data:result.data,outboxId:result.outboxId};
 }
 private async persist(input:{eventId:string;channelId:string},operator:{operator_id:bigint;identity_id:bigint},status:MatzangTimeCheckResult["status"],data:string,totalCharm?:string){return this.db.withTransaction(t=>this.write(t,input,operator,status,data,totalCharm));}
 private async write(t:DatabaseTransaction,input:{eventId:string;channelId:string},operator:{operator_id:bigint;identity_id:bigint},status:MatzangTimeCheckResult["status"],data:string,totalCharm?:string):Promise<MatzangTimeCheckResult>{const scope=`admin.matzang_time_check:${operator.operator_id}`,eventKey=key(input.eventId),prior=await t.query<Array<{result_json:string|MatzangTimeCheckResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,eventKey]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status) VALUES (?,?,?,'admin_operator',?,'iris','processing')",[randomUUID(),scope,eventKey,operator.operator_id]);const out=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status) VALUES (?,'iris',?,'text',?,'pending')",[op.insertId,input.channelId,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'ADMIN_MATZZANG_TIME_CHECK',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,op.insertId,status]);const audit=await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json) VALUES (?,'admin_operator',?,'player',NULL,'diagnostic.matzang_charm.read',?,'Iris /맞짱시간체크',?)",[op.insertId,operator.operator_id,status,JSON.stringify({status,totalCharm:totalCharm??null,mutation:false})]);const result:MatzangTimeCheckResult={status,data,outboxId:out.insertId.toString(),auditId:audit.insertId.toString(),...(totalCharm?{totalCharm}:{})};await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),op.insertId]);return result;}
}
