import { createHash,randomUUID } from "node:crypto";
import type { DatabaseClient } from "../database.js";
import { MariaCommandDispatchRepository,type RolloutState } from "../dispatch/command-dispatcher.js";

const COMMAND_CODE="ADMIN_PET_RESET",HANDLER_KEY="admin_pet_reset";
export interface PetResetCommand{targetName:string;}
export interface PetResetResult{status:"changed"|"missing_pet"|"usage"|"ambiguous_target";data:string;targetPlayerId:string|null;targetPetId:string|null;previousVersion:string|null;version:string|null;cleared:Record<string,string>;operationId:string;executionId:string;auditId:string;outboxId:string;}

// 레거시 startsWith guard와 동일하게 `/펫제거 ` 뒤에 대상이 있는 메시지만 후보로 허용합니다.
export function isPetResetCommandCandidate(message:string|undefined):boolean{return message!==undefined&&message.startsWith("/펫제거 ");}

// 공백을 포함한 대상 전체를 보존하되 빈 대상은 실행하지 않습니다.
export function parsePetResetCommand(message:string):PetResetCommand|null{const match=/^\/펫제거\s+([^]+)$/.exec(message);if(match===null||match[1]!.length===0)return null;return{targetName:match[1]!};}
function key(value:string):string{return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;}
function stored<T>(value:string|T):T{return typeof value==="string"?JSON.parse(value) as T:value;}

// stable pet ID와 이력은 보존하고 레거시 펫 객체 교체 범위의 현재 상태만 원자 초기화합니다.
export class PetResetService{
  constructor(private readonly database:DatabaseClient){}
  async handleIris(input:{externalUserId:string;channelId:string;message:string;eventId:string}):Promise<{status:"changed";data:string;outboxId:string}|{status:"shadow"|"legacy_fallback"|"handled_no_reply"}>{
    const definitions=await this.database.query<Array<{rollout_state:RolloutState;enabled:number}>>("SELECT rollout_state,enabled FROM command_registry WHERE command_code=? LIMIT 1",[COMMAND_CODE]),definition=definitions[0],dispatch=new MariaCommandDispatchRepository(this.database);
    if(definition===undefined||definition.enabled!==1||definition.rollout_state==="LEGACY_ONLY"){await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"LEGACY_FALLBACK",reasonCode:"ROLLOUT_LEGACY_ONLY",commandCode:COMMAND_CODE,handlerKey:HANDLER_KEY});return{status:"legacy_fallback"};}
    if(definition.rollout_state==="SHADOW"||definition.rollout_state==="CANARY"){await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"SHADOW",reasonCode:"ROLLOUT_SHADOW",commandCode:COMMAND_CODE,handlerKey:HANDLER_KEY});return{status:"shadow"};}
    const operators=await this.database.query<Array<{operator_id:bigint}>>(`SELECT operator.id operator_id FROM external_identities identity JOIN admin_operator_external_identities mapping ON mapping.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=mapping.operator_id JOIN admin_operator_roles operator_role ON operator_role.operator_id=operator.id JOIN admin_roles role ON role.id=operator_role.role_id JOIN admin_role_permissions permission ON permission.role_id=role.id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' AND operator.status='active' AND role.code='super_admin' AND role.active=TRUE AND permission.permission_code='pet.reset' LIMIT 1`,[input.externalUserId]);
    if(operators[0]===undefined)return{status:"handled_no_reply"};
    await dispatch.record({eventId:input.eventId,message:input.message,userId:input.externalUserId,hasTrustedDisplayName:true},{route:"MODERN",reasonCode:"MODERN_ROUTE_ALLOWED",commandCode:COMMAND_CODE,handlerKey:HANDLER_KEY});
    const result=await this.reset({message:input.message,idempotencyKey:input.eventId,sourceEventId:input.eventId,destinationId:input.channelId,operatorId:operators[0]!.operator_id.toString()});return{status:"changed",data:result.data,outboxId:result.outboxId};
  }
  async reset(input:{message:string;idempotencyKey:string;sourceEventId:string;destinationId:string;operatorId:string}):Promise<PetResetResult>{return this.database.withTransaction(async transaction=>{
    const scope=`admin.pet.reset:${input.operatorId}`,idempotencyKey=key(input.idempotencyKey);
    await transaction.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,?,?,'admin_operator',?,'iris','processing',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)",[randomUUID(),scope,idempotencyKey,input.operatorId]);
    const operations=await transaction.query<Array<{id:bigint;result_json:string|PetResetResult|null}>>("SELECT id,result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,idempotencyKey]),operation=operations[0];if(operation===undefined)throw new Error("Pet reset operation claim failed.");if(operation.result_json!==null)return stored(operation.result_json);
    const command=parsePetResetCommand(input.message),targets=command===null?[]:await transaction.query<Array<{player_id:bigint;pet_id:bigint|null;display_name:string|null;version:bigint|null;rank_emoji:string|null}>>(`SELECT profile.player_id,pet.id pet_id,pet.display_name,pet.version,rank_profile.rank_emoji FROM player_profiles profile JOIN players player ON player.id=profile.player_id AND player.status='active' LEFT JOIN player_pets pet ON pet.player_id=player.id LEFT JOIN player_legacy_rank_profiles rank_profile ON rank_profile.player_id=player.id WHERE profile.current_display_name=? ORDER BY profile.player_id LIMIT 2 FOR UPDATE`,[command.targetName]);
    let status:PetResetResult["status"]=command===null?"usage":"missing_pet",data=command===null?"":"",target=targets.length===1?targets[0]:undefined;const cleared:Record<string,string>={};if(targets.length>1)status="ambiguous_target";
    if(command!==null&&target?.pet_id!=null&&target.display_name!=null&&target.display_name!==""&&target.version!=null){status="changed";const run=async(name:string,sql:string,parameters:unknown[])=>{const result=await transaction.execute(sql,parameters);cleared[name]=result.affectedRows.toString();};
      await run("miniPetTitles","DELETE title_row FROM mini_pet_title_assignments title_row JOIN owned_mini_pets mini ON mini.id=title_row.owned_mini_pet_id WHERE mini.player_id=?",[target.player_id]);
      await run("ownedMiniPets","DELETE FROM owned_mini_pets WHERE player_id=?",[target.player_id]);await run("miniPetCollection","DELETE FROM mini_pet_collection_entries WHERE player_id=?",[target.player_id]);await run("petTitles","DELETE FROM pet_titles WHERE player_pet_id=?",[target.pet_id]);await run("petElemental","DELETE FROM player_pet_elementals WHERE player_pet_id=?",[target.pet_id]);await run("petPendant","DELETE FROM player_pet_pendants WHERE player_pet_id=?",[target.pet_id]);await run("petIntimacy","DELETE FROM player_pet_intimacy WHERE player_pet_id=?",[target.pet_id]);await run("petEquipment","DELETE FROM pet_equipment WHERE player_pet_id=?",[target.pet_id]);await run("petDaily","DELETE FROM player_pet_daily_records WHERE player_id=?",[target.player_id]);
      const update=await transaction.execute("UPDATE player_pets SET display_name='',pet_type_code='',image_value='',joined_on=DATE(DATE_ADD(UTC_TIMESTAMP(),INTERVAL 9 HOUR)),personality_label=NULL,experience=0,enhancement_level=0,enhancement_updated_at=NULL,version=version+1 WHERE id=? AND version=?",[target.pet_id,target.version]);if(update.affectedRows!==1n)throw new Error("Pet reset version conflict.");data=`[${target.rank_emoji??""}${command.targetName}] 님의 펫 정보가 제거되었습니다.`;
    }else if(command!==null)data=`${command.targetName}님은 펫을 가지고 있지 않습니다.`;
    const execution=await transaction.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'ADMIN_PET_RESET',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.sourceEventId,operation.id,status]),previousVersion=target?.version?.toString()??null,version=status==="changed"&&target?.version!=null?(target.version+1n).toString():previousVersion;
    const audit=await transaction.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'admin_operator',?,'player_pet',?,'pet.reset',?,'Iris /펫제거',?,UTC_TIMESTAMP(3))",[operation.id,input.operatorId,target?.pet_id??null,status,JSON.stringify({targetName:command?.targetName??null,playerId:target?.player_id.toString()??null,petId:target?.pet_id?.toString()??null,previousVersion,version,cleared,preserved:["player_pet_id","pet_skill_inventory","pet_expedition_runs","pet_upgrade_attempts"]})]);
    const outbox=await transaction.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[operation.id,input.destinationId,JSON.stringify({data})]);const result:PetResetResult={status,data,targetPlayerId:target?.player_id.toString()??null,targetPetId:target?.pet_id?.toString()??null,previousVersion,version,cleared,operationId:operation.id.toString(),executionId:execution.insertId.toString(),auditId:audit.insertId.toString(),outboxId:outbox.insertId.toString()};await transaction.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),operation.id]);return result;
  });}
}
