import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient, DatabaseTransaction } from "../database.js";
import { CommandDispatcher, MariaCommandDispatchRepository } from "../dispatch/command-dispatcher.js";
export type PreSignupAdminCommand={kind:"cleanup"}|{kind:"server-reset";server:string|null}|{kind:"identity-lookup";name:string|null};
export interface PreSignupRow{displayName:string;serverName:string|null;attendanceCount:string;lastAttendedOn:string|null}
export interface PreSignupIdentityMatch{state:"joined"|"pre-signup";displayName:string;serverName:string|null;lastAttendedOn:string|null}
export interface PreSignupAdminResult{kind:PreSignupAdminCommand["kind"];removedCount:number;resetCount:number;remainingCount:number;server:string|null;name:string|null;rows:PreSignupRow[];matches:PreSignupIdentityMatch[];data:string;outboxId:string}
const SERVER_PATTERN=/^(호[1-7]|벨[1-2]|GM|서버장)$/;
// 세 관리 명령의 exact/full-pattern 경계만 공용 dispatch 후보로 허용합니다.
export function parsePreSignupAdminCommand(message:string|undefined):PreSignupAdminCommand|null{
 if(message==="/미가입출첵")return{kind:"cleanup"};
 if(message==="/미가입출첵서버초기화")return{kind:"server-reset",server:null};
 const reset=message?.match(/^\/미가입출첵서버초기화[ \t]+(\S+)$/);if(reset&&SERVER_PATTERN.test(reset[1]!))return{kind:"server-reset",server:reset[1]!};
 if(message==="/미정")return{kind:"identity-lookup",name:null};
 const lookup=message?.match(/^\/미정[ \t]+([^\r\n]+)$/);if(lookup){const name=lookup[1]!.trim();if(name.length>0&&name.length<=191)return{kind:"identity-lookup",name};}
 return null;
}
export function isPreSignupAdminCommandCandidate(message:string|undefined){return parsePreSignupAdminCommand(message)!==null}
// 미가입 출첵 정리 결과를 날짜·서버·이름 고정 순서로 표시합니다.
export function formatPreSignupCleanup(input:{removedCount:number;rows:PreSignupRow[]}):string{
 const lines=["📋 미가입 출첵",`자동 삭제: ${input.removedCount}명`,`남은 인원: ${input.rows.length}명`];
 for(const row of input.rows)lines.push(`- ${row.lastAttendedOn??"-"} | ${row.serverName??"미확인"} / ${row.displayName} (${row.attendanceCount}회)`);
 return lines.join("\n");
}
// 서버 초기화 결과와 남은 미가입 출첵 목록을 함께 표시합니다.
export function formatPreSignupServerReset(input:{server:string|null;resetCount:number;rows:PreSignupRow[]}):string{
 if(input.server===null)return"사용법: /미가입출첵서버초기화 [호1-호7|벨1-벨2|GM|서버장]";
 return[`✅ 미가입 출첵 서버 초기화: ${input.server}`,`초기화: ${input.resetCount}명`,formatPreSignupCleanup({removedCount:0,rows:input.rows})].join("\n");
}
// 가입·미가입 identity를 base name 기준으로 함께 표시합니다.
export function formatPreSignupIdentityLookup(input:{name:string|null;matches:PreSignupIdentityMatch[]}):string{
 if(input.name===null)return"사용법: /미정 [이름]";
 const lines=[`🔎 신규 ID 확인: ${input.name}`];if(input.matches.length===0){lines.push("동일한 기본 이름의 가입·미가입 기록이 없습니다.");return lines.join("\n");}
 for(const match of input.matches){const state=match.state==="joined"?"가입":"미가입";lines.push(`- ${state}: ${match.displayName} / ${match.serverName??"(서버정보 없음)"}${match.lastAttendedOn===null?"":` / ${match.lastAttendedOn}`}`);}return lines.join("\n");
}
// pre-signup attendance를 version lock으로 조회·정리하고 감사와 응답을 원자 기록합니다.
export class PreSignupAdminService{
 constructor(private readonly database:DatabaseClient){}
 async handleIris(input:{externalUserId:string;channelId:string;message:string;eventId:string}):Promise<{status:"changed";data:string;outboxId:string}|{status:"shadow"|"legacy_fallback"|"handled_no_reply"}>{
  const command=parsePreSignupAdminCommand(input.message);if(command===null)return{status:"legacy_fallback"};
  const normalized=command.kind==="cleanup"?"/미가입출첵":command.kind==="server-reset"?"/미가입출첵서버초기화":"/미정";
  const decision=await new CommandDispatcher(new MariaCommandDispatchRepository(this.database),{enabled:true,allowAllCanaries:false,canaryUserIds:new Set()}).resolve({eventId:input.eventId,message:normalized,userId:input.externalUserId,hasTrustedDisplayName:true});
  if(decision.route==="SHADOW")return{status:"shadow"};if(decision.route!=="MODERN")return{status:"legacy_fallback"};
  const result=await this.execute({eventId:input.eventId,externalUserId:input.externalUserId,destinationId:input.channelId,command});if(result===null)return{status:"handled_no_reply"};return{status:"changed",data:result.data,outboxId:result.outboxId};
 }
 async execute(input:{eventId:string;externalUserId:string;destinationId:string;command:PreSignupAdminCommand}):Promise<PreSignupAdminResult|null>{
  const operator=await this.findOperator(input.externalUserId);if(operator===undefined)return null;
  const scope=`pre_signup.${input.command.kind.replaceAll("-","_")}`;const key=input.eventId.length<=191?input.eventId:`sha256:${createHash("sha256").update(input.eventId).digest("hex")}`;
  return withDeadlockRetry(()=>this.database.withTransaction(async tx=>{
   const previous=(await tx.query<Array<{result_json:string|PreSignupAdminResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,key]))[0];
   if(previous?.result_json!=null)return typeof previous.result_json==="string"?JSON.parse(previous.result_json):previous.result_json;
   if(input.command.kind==="cleanup")return this.cleanup(tx,operator.id,key,scope,input as typeof input&{command:{kind:"cleanup"}});
   if(input.command.kind==="server-reset")return this.resetServer(tx,operator.id,key,scope,input as typeof input&{command:{kind:"server-reset";server:string|null}});
   return this.lookupIdentity(tx,operator.id,key,scope,input as typeof input&{command:{kind:"identity-lookup";name:string|null}});
  }));
 }
 private async findOperator(externalUserId:string){return(await this.database.query<Array<{id:bigint}>>(`SELECT operator.id FROM external_identities identity JOIN admin_operator_external_identities mapping ON mapping.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=mapping.operator_id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' AND operator.status='active' AND NOT EXISTS (SELECT 1 FROM admin_operator_permission_overrides denied WHERE denied.operator_id=operator.id AND denied.permission_code='pre_signup_attendance.manage' AND denied.effect='deny') AND (EXISTS (SELECT 1 FROM admin_operator_permission_overrides allowed WHERE allowed.operator_id=operator.id AND allowed.permission_code='pre_signup_attendance.manage' AND allowed.effect='allow') OR EXISTS (SELECT 1 FROM admin_operator_roles operator_role JOIN admin_roles role ON role.id=operator_role.role_id AND role.active=TRUE JOIN admin_role_permissions permission ON permission.role_id=role.id AND permission.permission_code='pre_signup_attendance.manage' WHERE operator_role.operator_id=operator.id)) LIMIT 1`,[externalUserId]))[0]}
 private async cleanup(tx:DatabaseTransaction,operatorId:bigint,key:string,scope:string,input:{eventId:string;destinationId:string;command:{kind:"cleanup"}}){
  const candidates=await tx.query<Array<{id:bigint;game_server_id:bigint|null;version:bigint;joined:number;stale:number}>>(`SELECT attendance.id,attendance.game_server_id,attendance.version,identity.player_id IS NOT NULL joined,attendance.last_attended_on IS NULL OR attendance.last_attended_on<=DATE_SUB(UTC_DATE(),INTERVAL 4 DAY) stale FROM pre_signup_attendance attendance LEFT JOIN external_identities identity ON identity.id=attendance.external_identity_id WHERE attendance.status='active' ORDER BY attendance.id FOR UPDATE`);
  const removed=candidates.filter(row=>row.joined===1||row.stale===1);const operation=await this.createOperation(tx,operatorId,key,scope);const run=await tx.execute("INSERT INTO pre_signup_attendance_runs(operation_id,command_code,affected_count,remaining_count,run_status,created_at) VALUES (?,'cleanup',?,0,'processing',UTC_TIMESTAMP(3))",[operation,removed.length]);
  for(const row of removed){const action=row.joined===1?"cleanup_joined":"cleanup_stale",status=row.joined===1?"removed_joined":"removed_stale";await tx.execute("INSERT INTO pre_signup_attendance_mutations(run_id,attendance_id,action_code,before_status,after_status,before_game_server_id,after_game_server_id,before_version,after_version) VALUES (?,?,?,'active',?,?,?,?,?)",[run.insertId,row.id,action,status,row.game_server_id,row.game_server_id,row.version,row.version+1n]);await tx.execute("UPDATE pre_signup_attendance SET status=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=? AND status='active' AND version=?",[status,row.id,row.version]);}
  const rows=await this.readRemaining(tx);const base={kind:"cleanup" as const,removedCount:removed.length,resetCount:0,remainingCount:rows.length,server:null,name:null,rows,matches:[]};return this.finish(tx,operatorId,operation,run.insertId,input.eventId,input.destinationId,base,formatPreSignupCleanup(base),"ADMIN_PRE_SIGNUP_CLEANUP");
 }
 private async resetServer(tx:DatabaseTransaction,operatorId:bigint,key:string,scope:string,input:{eventId:string;destinationId:string;command:{kind:"server-reset";server:string|null}}){
  const operation=await this.createOperation(tx,operatorId,key,scope);if(input.command.server===null){const base={kind:"server-reset" as const,removedCount:0,resetCount:0,remainingCount:0,server:null,name:null,rows:[],matches:[]};return this.finish(tx,operatorId,operation,null,input.eventId,input.destinationId,base,formatPreSignupServerReset(base),"ADMIN_PRE_SIGNUP_SERVER_RESET");}
  const server=(await tx.query<Array<{id:bigint}>>("SELECT id FROM game_servers WHERE display_name=? AND active=TRUE LIMIT 1 FOR UPDATE",[input.command.server]))[0];const targets=server===undefined?[]:await tx.query<Array<{id:bigint;version:bigint;game_server_id:bigint}>>("SELECT id,version,game_server_id FROM pre_signup_attendance WHERE status='active' AND game_server_id=? ORDER BY id FOR UPDATE",[server.id]);
  const run=await tx.execute("INSERT INTO pre_signup_attendance_runs(operation_id,command_code,game_server_id,affected_count,remaining_count,run_status,created_at) VALUES (?,'server_reset',?,?,0,'processing',UTC_TIMESTAMP(3))",[operation,server?.id??null,targets.length]);
  for(const row of targets){await tx.execute("INSERT INTO pre_signup_attendance_mutations(run_id,attendance_id,action_code,before_status,after_status,before_game_server_id,after_game_server_id,before_version,after_version) VALUES (?,?,'server_reset','active','active',?,NULL,?,?)",[run.insertId,row.id,row.game_server_id,row.version,row.version+1n]);await tx.execute("UPDATE pre_signup_attendance SET game_server_id=NULL,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=? AND status='active' AND version=?",[row.id,row.version]);}
  const rows=await this.readRemaining(tx);const base={kind:"server-reset" as const,removedCount:0,resetCount:targets.length,remainingCount:rows.length,server:input.command.server,name:null,rows,matches:[]};return this.finish(tx,operatorId,operation,run.insertId,input.eventId,input.destinationId,base,formatPreSignupServerReset(base),"ADMIN_PRE_SIGNUP_SERVER_RESET");
 }
 private async lookupIdentity(tx:DatabaseTransaction,operatorId:bigint,key:string,scope:string,input:{eventId:string;destinationId:string;command:{kind:"identity-lookup";name:string|null}}){
  const operation=await this.createOperation(tx,operatorId,key,scope);const matches:PreSignupIdentityMatch[]=input.command.name===null?[]:(await tx.query<Array<{state:"joined"|"pre-signup";display_name:string;server_name:string|null;last_attended_on:string|null}>>(`SELECT result.state,result.display_name,result.server_name,result.last_attended_on FROM (SELECT 'joined' state,profile.current_display_name display_name,server.display_name server_name,NULL last_attended_on,0 state_order FROM player_profiles profile JOIN players player ON player.id=profile.player_id AND player.status='active' LEFT JOIN game_servers server ON server.id=profile.game_server_id WHERE TRIM(CASE WHEN RIGHT(profile.current_display_name,2) IN (' 남',' 여') THEN LEFT(profile.current_display_name,CHAR_LENGTH(profile.current_display_name)-2) ELSE profile.current_display_name END)=? UNION ALL SELECT 'pre-signup',attendance.legacy_display_name,server.display_name,DATE_FORMAT(attendance.last_attended_on,'%Y-%m-%d'),1 FROM pre_signup_attendance attendance LEFT JOIN game_servers server ON server.id=attendance.game_server_id WHERE attendance.status='active' AND TRIM(CASE WHEN RIGHT(attendance.normalized_display_name,2) IN (' 남',' 여') THEN LEFT(attendance.normalized_display_name,CHAR_LENGTH(attendance.normalized_display_name)-2) ELSE attendance.normalized_display_name END)=?) result ORDER BY result.state_order,result.display_name`,[input.command.name,input.command.name])).map(row=>({state:row.state,displayName:row.display_name,serverName:row.server_name,lastAttendedOn:row.last_attended_on}));
  const run=await tx.execute("INSERT INTO pre_signup_attendance_runs(operation_id,command_code,affected_count,remaining_count,run_status,created_at) VALUES (?,'identity_lookup',0,?,'processing',UTC_TIMESTAMP(3))",[operation,matches.length]);const base={kind:"identity-lookup" as const,removedCount:0,resetCount:0,remainingCount:matches.length,server:null,name:input.command.name,rows:[],matches};return this.finish(tx,operatorId,operation,run.insertId,input.eventId,input.destinationId,base,formatPreSignupIdentityLookup(base),"ADMIN_PRE_SIGNUP_IDENTITY_LOOKUP");
 }
 private async readRemaining(tx:DatabaseTransaction):Promise<PreSignupRow[]>{const rows=await tx.query<Array<{display_name:string;server_name:string|null;attendance_count:bigint;last_attended_on:string|null}>>(`SELECT attendance.legacy_display_name display_name,server.display_name server_name,attendance.attendance_count,DATE_FORMAT(attendance.last_attended_on,'%Y-%m-%d') last_attended_on FROM pre_signup_attendance attendance LEFT JOIN game_servers server ON server.id=attendance.game_server_id WHERE attendance.status='active' ORDER BY attendance.last_attended_on,CASE server.display_name WHEN '호1' THEN 1 WHEN '호2' THEN 2 WHEN '호3' THEN 3 WHEN '호4' THEN 4 WHEN '호5' THEN 5 WHEN '호6' THEN 6 WHEN '호7' THEN 7 WHEN '벨1' THEN 8 WHEN '벨2' THEN 9 WHEN 'GM' THEN 10 WHEN '서버장' THEN 11 ELSE 99 END,attendance.normalized_display_name,attendance.id`);return rows.map(row=>({displayName:row.display_name,serverName:row.server_name,attendanceCount:row.attendance_count.toString(),lastAttendedOn:row.last_attended_on}))}
 private async createOperation(tx:DatabaseTransaction,operatorId:bigint,key:string,scope:string){return(await tx.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,?,?,'admin_operator',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),scope,key,operatorId])).insertId}
 private async finish(tx:DatabaseTransaction,operatorId:bigint,operationId:bigint,runId:bigint|null,eventId:string,destinationId:string,base:Omit<PreSignupAdminResult,"data"|"outboxId">,data:string,commandCode:string):Promise<PreSignupAdminResult>{
  if(runId!==null)await tx.execute("UPDATE pre_signup_attendance_runs SET remaining_count=?,run_status='complete',completed_at=UTC_TIMESTAMP(3) WHERE id=?",[base.remainingCount,runId]);
  const outbox=await tx.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[operationId,destinationId,JSON.stringify({data})]);await tx.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,?,?,'completed','reply_queued',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[eventId,commandCode,operationId]);await tx.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'admin_operator',?,'pre_signup_attendance_run',?,'pre_signup_attendance.manage','success','Iris 미가입 출첵 관리',?,UTC_TIMESTAMP(3))",[operationId,operatorId,runId,JSON.stringify({kind:base.kind,removedCount:base.removedCount,resetCount:base.resetCount,remainingCount:base.remainingCount,server:base.server,name:base.name})]);const result={...base,data,outboxId:outbox.insertId.toString()};await tx.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),operationId]);return result;
 }
}
async function withDeadlockRetry<T>(work:()=>Promise<T>):Promise<T>{for(let attempt=0;attempt<3;attempt+=1){try{return await work()}catch(error){const dbError=error as{code?:unknown;errno?:unknown};if(attempt===2||(dbError.code!=="ER_LOCK_DEADLOCK"&&dbError.errno!==1213))throw error}}throw new Error("Pre-signup attendance deadlock retry exhausted.")}
