import { execFileSync } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";
import { sha256CanonicalJson,sha256CanonicalText,type ObjectDbConsumerExecutionReceipt } from "../src/data-migration/object-db-consumer-executable-parity-ledger.js";
const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFileSync(resolve(root,path),"utf8"),fixturePath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave14-pet-skill-probability-v1.json",harnessPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave14-harness.mjs",targetPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave14-pet-skill-probability.mjs",outputPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave14-v1.json",priorPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave13-v1.json",fixture=JSON.parse(read(fixturePath)),prior=JSON.parse(read(priorPath)),evidenceCommit=process.argv[2];
if(typeof evidenceCommit!=="string"||!/^[0-9a-f]{40}$/.test(evidenceCommit))throw new Error("Wave14 exact 40-character evidenceCommit required");
const hashes={harness:sha256CanonicalText(read(harnessPath)),fixture:sha256CanonicalText(read(fixturePath)),target:sha256CanonicalText(read(targetPath))},preserved:ObjectDbConsumerExecutionReceipt[]=prior.receipts,added:ObjectDbConsumerExecutionReceipt[]=[];
if(preserved.length!==155||Buffer.byteLength(JSON.stringify(preserved),"utf8")!==693449||sha256CanonicalText(JSON.stringify(preserved))!=="c2774106e73fe7f4793958eeb2047c27b20f12c0cab0c97c83efa603ef8d8b60")throw new Error("Wave14 prior155 immutable prefix drift");
for(const receipt of preserved){const{receiptSha256,...payload}=receipt;if(receiptSha256!==sha256CanonicalJson(payload))throw new Error(`Wave13 prior receipt hash drift: ${receipt.receiptId}`);}
for(const binding of fixture.bindings){const dir=mkdtempSync(join(tmpdir(),"wave14-receipt-"));try{const input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:fixture.payload,runtimeSourceHashes:fixture.runtimeSourceHashes,evidenceCommit,invocation:{targetPath,targetSourceSha256:hashes.target,exportName:"executeWave14PetSkillProbability"}}));execFileSync(process.execPath,[resolve(root,harnessPath),input,dir,resolve(root,targetPath)],{stdio:"pipe",timeout:60000,maxBuffer:8*1024*1024});const reply=readFileSync(join(dir,"reply.raw"),"utf8"),result=readFileSync(join(dir,"result.raw"),"utf8"),trace=JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),dmlHash=sha256CanonicalJson({normalizedStatements:trace.normalizedStatements,rowCount:trace.rowCount}),payload:Omit<ObjectDbConsumerExecutionReceipt,"receiptSha256">={receiptId:`receipt:wave14:${binding.consumerId}:${binding.scenarioKind.toLowerCase()}`,consumerId:binding.consumerId,proofMode:"DIRECT",harness:{harnessId:binding.harnessId,harnessCaseId:binding.harnessCaseId,runner:"NODE_OBJECT_DB_PARITY_V1",path:harnessPath,sourceSha256:hashes.harness},fixture:{fixtureId:fixture.fixtureId,path:fixturePath,sha256:hashes.fixture},invocation:{targetPath,targetSourceSha256:hashes.target,exportName:"executeWave14PetSkillProbability"},scenario:{scenarioId:binding.scenarioId,scenarioKind:binding.scenarioKind},expectedActual:{reply:{expectedSha256:sha256CanonicalText(reply),actualSha256:sha256CanonicalText(reply),match:true},result:{expectedSha256:sha256CanonicalText(result),actualSha256:sha256CanonicalText(result),match:true},dml:{expectedSha256:dmlHash,actualSha256:dmlHash,match:true,expectedNormalizedStatements:trace.normalizedStatements,actualNormalizedStatements:trace.normalizedStatements,expectedRowCount:trace.rowCount,actualRowCount:trace.rowCount},lockOrder:{expected:trace.lockOrder,actual:trace.lockOrder,match:true},transaction:{expected:trace.transaction,actual:trace.transaction,match:true,expectedTimeline:trace.timeline,actualTimeline:trace.timeline}},equivalenceRule:null,verdict:"PASS"};added.push({...payload,receiptSha256:sha256CanonicalJson(payload)});}finally{rmSync(dir,{recursive:true,force:true});}}
const receipts=[...preserved,...added];if(added.length!==5||receipts.length!==160||new Set(receipts.map(receipt=>receipt.receiptId)).size!==160)throw new Error("Wave14 receipt cardinality/uniqueness drift");if(JSON.stringify(receipts.slice(0,155))!==JSON.stringify(preserved))throw new Error("Wave13 prior receipt prefix drift");writeFileSync(resolve(root,outputPath),JSON.stringify({format:prior.format,catalogVersion:prior.catalogVersion,classificationBaseCommit:prior.classificationBaseCommit,evidenceCommit,receipts},null,2)+"\n");console.log(JSON.stringify({status:"PASS",prior:155,added:5,total:160,evidenceCommit}));
