import { execFileSync } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";
import { sha256CanonicalJson,sha256CanonicalText,type ObjectDbConsumerExecutionReceipt } from "../src/data-migration/object-db-consumer-executable-parity-ledger.js";
const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFileSync(resolve(root,path),"utf8"),fixturePath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave14-pet-skill-probability-v1.json",harnessPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave14-harness.mjs",targetPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave14-pet-skill-probability.mjs",outputPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave14-v1.json",priorPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave13-v1.json",prior=JSON.parse(read(priorPath)),evidenceCommit=process.argv[2];
if(typeof evidenceCommit!=="string"||!/^[0-9a-f]{40}$/.test(evidenceCommit))throw new Error("Wave14 exact 40-character evidenceCommit required");
const committed=(path:string)=>{const listing=execFileSync("git",["ls-tree",evidenceCommit,"--",path],{cwd:root,encoding:"utf8"}),match=/^[0-9]+ blob ([0-9a-f]{40})\t/.exec(listing);if(match?.[1]===undefined)throw new Error(`Wave14 committed blob missing: ${path}`);return execFileSync("git",["cat-file","blob",match[1]],{cwd:root,encoding:"utf8",maxBuffer:8*1024*1024});},fixture=JSON.parse(committed(fixturePath));
const hashes={harness:sha256CanonicalText(committed(harnessPath)),fixture:sha256CanonicalText(committed(fixturePath)),target:sha256CanonicalText(committed(targetPath))},preserved:ObjectDbConsumerExecutionReceipt[]=prior.receipts,added:ObjectDbConsumerExecutionReceipt[]=[];
for(const [path,hash] of [[harnessPath,hashes.harness],[fixturePath,hashes.fixture],[targetPath,hashes.target]] as const)if(sha256CanonicalText(read(path))!==hash)throw new Error(`Wave14 committed evidence/worktree drift: ${path}`);
if(preserved.length!==155||Buffer.byteLength(JSON.stringify(preserved),"utf8")!==693449||sha256CanonicalText(JSON.stringify(preserved))!=="c2774106e73fe7f4793958eeb2047c27b20f12c0cab0c97c83efa603ef8d8b60")throw new Error("Wave14 prior155 immutable prefix drift");
for(const receipt of preserved){const{receiptSha256,...payload}=receipt;if(receiptSha256!==sha256CanonicalJson(payload))throw new Error(`Wave13 prior receipt hash drift: ${receipt.receiptId}`);}
for(const binding of fixture.bindings){const dir=mkdtempSync(join(tmpdir(),"wave14-receipt-"));try{
  const expected=fixture.expectedEvidence.scenarios[binding.scenarioKind],template=fixture.expectedEvidence.dmlTemplates[expected.dmlTemplate];
  if(expected===undefined||!Array.isArray(template)||!Number.isInteger(expected.dmlRepeat)||expected.dmlRepeat<1)throw new Error(`Wave14 independent expected contract missing: ${binding.scenarioKind}`);
  const expectedStatements=Array.from({length:expected.dmlRepeat},()=>template).flat(),expectedResult=JSON.stringify(expected.result),expectedDmlHash=sha256CanonicalJson({normalizedStatements:expectedStatements,rowCount:expected.rowCount});
  const input=join(dir,"input.json");writeFileSync(input,JSON.stringify({binding,fixturePayload:fixture.payload,runtimeSourceHashes:fixture.runtimeSourceHashes,evidenceCommit,invocation:{targetPath,targetSourceSha256:hashes.target,exportName:"executeWave14PetSkillProbability"}}));
  execFileSync(process.execPath,[resolve(root,harnessPath),input,dir,resolve(root,targetPath)],{stdio:"pipe",timeout:60000,maxBuffer:8*1024*1024});
  const reply=readFileSync(join(dir,"reply.raw"),"utf8"),result=readFileSync(join(dir,"result.raw"),"utf8"),trace=JSON.parse(readFileSync(join(dir,"trace.json"),"utf8")),actualReplyHash=sha256CanonicalText(reply),actualResultHash=sha256CanonicalText(result),actualDmlHash=sha256CanonicalJson({normalizedStatements:trace.normalizedStatements,rowCount:trace.rowCount});
  if(actualReplyHash!==expected.replySha256||result!==expectedResult||actualDmlHash!==expectedDmlHash||JSON.stringify(trace.normalizedStatements)!==JSON.stringify(expectedStatements)||trace.rowCount!==expected.rowCount||JSON.stringify(trace.lockOrder)!==JSON.stringify(expected.lockOrder)||trace.transaction!==expected.transaction||JSON.stringify(trace.timeline)!==JSON.stringify(expected.timeline))throw new Error(`Wave14 independent expected/actual drift: ${binding.scenarioKind}`);
  const payload:Omit<ObjectDbConsumerExecutionReceipt,"receiptSha256">={receiptId:`receipt:wave14:${binding.consumerId}:${binding.scenarioKind.toLowerCase()}`,consumerId:binding.consumerId,proofMode:"DIRECT",harness:{harnessId:binding.harnessId,harnessCaseId:binding.harnessCaseId,runner:"NODE_OBJECT_DB_PARITY_V1",path:harnessPath,sourceSha256:hashes.harness},fixture:{fixtureId:fixture.fixtureId,path:fixturePath,sha256:hashes.fixture},invocation:{targetPath,targetSourceSha256:hashes.target,exportName:"executeWave14PetSkillProbability"},scenario:{scenarioId:binding.scenarioId,scenarioKind:binding.scenarioKind},expectedActual:{reply:{expectedSha256:expected.replySha256,actualSha256:actualReplyHash,match:true},result:{expectedSha256:sha256CanonicalText(expectedResult),actualSha256:actualResultHash,match:true},dml:{expectedSha256:expectedDmlHash,actualSha256:actualDmlHash,match:true,expectedNormalizedStatements:expectedStatements,actualNormalizedStatements:trace.normalizedStatements,expectedRowCount:expected.rowCount,actualRowCount:trace.rowCount},lockOrder:{expected:expected.lockOrder,actual:trace.lockOrder,match:true},transaction:{expected:expected.transaction,actual:trace.transaction,match:true,expectedTimeline:expected.timeline,actualTimeline:trace.timeline}},equivalenceRule:null,verdict:"PASS"};added.push({...payload,receiptSha256:sha256CanonicalJson(payload)});
}finally{rmSync(dir,{recursive:true,force:true});}}
const receipts=[...preserved,...added];if(added.length!==5||receipts.length!==160||new Set(receipts.map(receipt=>receipt.receiptId)).size!==160)throw new Error("Wave14 receipt cardinality/uniqueness drift");if(JSON.stringify(receipts.slice(0,155))!==JSON.stringify(preserved))throw new Error("Wave13 prior receipt prefix drift");writeFileSync(resolve(root,outputPath),JSON.stringify({format:prior.format,catalogVersion:prior.catalogVersion,classificationBaseCommit:prior.classificationBaseCommit,evidenceCommit,receipts},null,2)+"\n");console.log(JSON.stringify({status:"PASS",prior:155,added:5,total:160,evidenceCommit}));
