import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CommandDispatcher, MariaCommandRouteReader } from "../src/dispatch/command-dispatcher.js";
import { PendantMarketInfoService } from "../src/market/pendant-market-info-service.js";
import { PendantInfoService } from "../src/pet/pendant-info-service.js";
import { PendantProbabilityService } from "../src/pet/pendant-probability-service.js";

const root=resolve(import.meta.dirname,"../../..");
const read=(path:string)=>readFileSync(resolve(root,path),"utf8").replace(/\r\n?/g,"\n");
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const normalize=(sql:string)=>sql.replace(/\s+/g," ").trim();
const manifest=JSON.parse(read("개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"));
const output="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave10-pendant-read-v1.json";
const receiptScenarios=["READ_POSITIVE","NEGATIVE_GUARD","EXACT_OUTPUT","SOURCE_DOMAIN_DML_ZERO","RESTART_CONSISTENCY"];
const riskScenarios=["ROLLBACK","SAME_EVENT_REPLAY","APP_INBOX_DUPLICATE","MISSING_IDENTITY","WRONG_OPERATIONAL_CHANNEL","PAYLOAD_DESTINATION_DRIFT"];
const definitions=[
  {consumerId:"runtime-dispatch-36d6721ade0707a6",caseId:"case:pendant-market-info",message:"/펜던트거래정보 3",invalid:"/펜던트거래정보3",commandCode:"PENDANT_MARKET_INFO",handlerKey:"pendant_market_info",serviceFile:"개발환경_고도화/runtime/src/market/pendant-market-info-service.ts",service:PendantMarketInfoService},
  {consumerId:"runtime-dispatch-8c6c3c3d598fe078",caseId:"case:pendant-info",message:"/펜던트정보 1",invalid:"/펜던트정보1",commandCode:"PENDANT_INFO_READ",handlerKey:"pendant_info_read",serviceFile:"개발환경_고도화/runtime/src/pet/pendant-info-service.ts",service:PendantInfoService},
  {consumerId:"runtime-dispatch-19076db78c2eefb9",caseId:"case:pendant-probability",message:"/펜던트확률",invalid:"/펜던트확률 안내",commandCode:"PENDANT_PROBABILITY_READ",handlerKey:"pendant_probability_read",serviceFile:"개발환경_고도화/runtime/src/pet/pendant-probability-service.ts",service:PendantProbabilityService},
] as const;
const safe=(value:any):any=>typeof value==="bigint"?{$bigint:value.toString()}:Array.isArray(value)?value.map(safe):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,child])=>[key,safe(child)])):value;
function locate(file:string,needle:string){const source=read(file);if(!source.includes(needle))throw new Error(`${file} missing ${needle}`);return{file,start:0,end:source.length,sha256:sha(source),needle};}
function locateAppBranch(handlerKey:string){const file="개발환경_고도화/runtime/src/app.ts",source=read(file),anchor=`partialDispatchDecision.handlerKey === "${handlerKey}"`,compact=`partialDispatchDecision.handlerKey==="${handlerKey}"`,index=Math.max(source.indexOf(anchor),source.indexOf(compact));if(index<0)throw new Error(`app missing ${handlerKey}`);const start=Math.max(source.lastIndexOf("      if (isOperationalChannel",index),source.lastIndexOf("      if(isOperationalChannel",index));const endMarker=source.indexOf("\n      }",index);const end=endMarker<0?source.indexOf("\n\n",index):endMarker+8;if(start<0||end<=start)throw new Error(`app span missing ${handlerKey}`);const span=source.slice(start,end);return{file,start,end,sha256:sha(span),needle:handlerKey};}
function replayResult(def:typeof definitions[number]){if(def.handlerKey==="pendant_probability_read")return{status:"replied",data:"저장된 펜던트 확률",outboxId:"601",rowCount:13,rateTotal:100};return{status:"found",data:"저장된 펜던트 정보",outboxId:"601",...(def.handlerKey==="pendant_market_info"?{listingId:"9223372036854775806",instanceId:"9223372036854775805"}:{instanceId:"9223372036854775805"})};}
const probabilityRows=[["조약돌","🪨","최하급","31",1],["동빛","🔸","하급","20",2],["은빛","⚪","하급+","15",3],["금빛","🟡","중급","10",4],["청옥","🔹","중급+","7",5],["홍옥","🔴","상급","5",6],["별빛","⭐","상급+","4",7],["달빛","🌙","최상급","3",8],["햇빛","☀️","최상급+","2",9],["신화","🌀","신화","1.5",10],["초월","🌌","초월","1",11],["창세","🌠","창세","0.4",12],["창조","✨","창조","0.1",13]].map(([name,icon,grade,rate,drawOrder])=>({name,icon,grade,rate,drawOrder}));
function rowsFor(def:typeof definitions[number],scenario:string,sql:string){
  if(sql.includes("FROM command_aliases"))return[{command_code:def.commandCode,handler_key:def.handlerKey,auth_scope:"VERIFIED_USER",rollout_state:"ACTIVE"}];
  if(sql.includes("FROM external_identities identity")&&scenario==="MISSING_IDENTITY")return[];
  if(def.handlerKey==="pendant_market_info"&&sql.includes("SELECT identity.id identity_id,identity.player_id"))return[{identity_id:42n,player_id:1n}];
  if(def.handlerKey==="pendant_info_read"&&sql.includes("SELECT identity.id identity_id,profile.player_id"))return[{identity_id:42n,player_id:1n,pet_id:2n,rank_display:"🥇호이"}];
  if(def.handlerKey==="pendant_probability_read"&&sql.includes("SELECT identity.id identity_id"))return[{identity_id:42n}];
  if(sql.startsWith("SELECT result_json FROM operations"))return["SAME_EVENT_REPLAY","PAYLOAD_DESTINATION_DRIFT"].includes(scenario)?[{result_json:replayResult(def)}]:[];
  if(sql.includes("FROM market_listings listing"))return[{listing_id:9223372036854775806n,asset_type_code:"ITEM",inventory_instance_id:9223372036854775805n,object_type:"pendant",item_name:"별빛 펜던트⭐",name_value:"별빛 펜던트",icon_value:"⭐",grade_value:"창조",durability_value:"4",max_durability_value:"5",upgrade_value:"30"}];
  if(sql.includes("FROM inventory_instances instance"))return[{instance_id:9223372036854775805n,item_name:"별빛 펜던트⭐",name_value:"별빛 펜던트",icon_value:"⭐",grade_value:"창조",durability_value:"4",max_durability_value:"5",upgrade_value:"30"},{instance_id:11n,item_name:"조약돌 펜던트🪨",name_value:"조약돌 펜던트",icon_value:"🪨",grade_value:"최하급",durability_value:"5",max_durability_value:"5",upgrade_value:"0"}];
  if(sql.includes("FROM item_definitions WHERE code LIKE 'ITEM-PENDANT-DRAW-%'"))return probabilityRows;
  throw new Error(`${def.consumerId}/${scenario} unhandled query: ${sql}`);
}
function insertId(sql:string){if(sql.startsWith("INSERT INTO operations"))return 501n;if(sql.startsWith("INSERT INTO outbox_messages"))return 601n;if(sql.startsWith("INSERT INTO command_executions"))return 701n;if(sql.startsWith("INSERT INTO command_audit"))return 801n;return 0n;}
async function capture(def:typeof definitions[number],scenario:string){
  const input:any={eventId:`wave10-${def.consumerId}-${scenario.toLowerCase()}`,externalUserId:"pendant-user",destinationId:"pendant-room",message:scenario==="NEGATIVE_GUARD"?def.invalid:def.message};
  if(scenario==="NEGATIVE_GUARD")return{queries:[],mutations:[],result:"INVALID_COMMAND_NO_CALL",input};
  if(scenario==="APP_INBOX_DUPLICATE")input.duplicate=true;if(scenario==="WRONG_OPERATIONAL_CHANNEL")input.isOperationalChannel=false;if(scenario==="PAYLOAD_DESTINATION_DRIFT")input.destinationId="changed-room";
  const queries:any[]=[],mutations:any[]=[];
  const db:any={withTransaction:async(work:any)=>work(db),query:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),rows=rowsFor(def,scenario,normalized);queries.push({expectedNormalizedSql:normalized,expectedValues:safe(values),rows:safe(rows)});return rows;},execute:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),id=insertId(normalized),step:any={expectedNormalizedSql:normalized,expectedValues:safe(values).map((value:any,index:number)=>index===0&&normalized.startsWith("INSERT INTO operations")?{matcher:"UUID_V4"}:value),affectedRows:1,insertId:id.toString()};if(scenario==="ROLLBACK"&&normalized.startsWith("INSERT INTO command_executions"))step.error={message:"wave10 forced middle-DML rollback",code:"ER_SIGNAL_EXCEPTION",errno:1644};mutations.push(step);if(step.error){const error:any=new Error(step.error.message);Object.assign(error,step.error);throw error;}return{affectedRows:1n,insertId:id};}};
  const dispatcher=new CommandDispatcher(new MariaCommandRouteReader(db),{enabled:true,allowAllCanaries:false,canaryUserIds:new Set()},undefined);const decision=await dispatcher.resolveReadOnly({eventId:input.eventId,message:def.message,userId:input.externalUserId,hasTrustedDisplayName:true});if(decision.route!=="MODERN"||decision.handlerKey!==def.handlerKey)throw new Error(`${def.consumerId} dispatch drift`);
  if(["APP_INBOX_DUPLICATE","WRONG_OPERATIONAL_CHANNEL"].includes(scenario))return{queries,mutations,result:"APP_GATE_REJECTED_NO_CALL",input};
  try{return{queries,mutations,result:JSON.stringify(await new def.service(db).handle(input)),input};}catch(error){if(scenario!=="ROLLBACK")throw error;const caught=error as any;return{queries,mutations,result:`ERROR:${caught.code??caught.message}`,input};}
}
const cases:any[]=[],bindings:any[]=[],riskBindings:any[]=[];
for(const def of definitions){const source=manifest.consumers.find((entry:any)=>entry.consumerId===def.consumerId);if(!source)throw new Error(`missing ${def.consumerId}`);const captured:Record<string,any>={};for(const scenario of [...receiptScenarios,...riskScenarios])captured[scenario]=await capture(def,scenario);const consumer={consumerId:def.consumerId,sourceLocator:{...locateAppBranch(def.handlerKey),symbol:source.symbol,triggerOrPredicate:source.triggerOrPredicate,interfaceId:source.interfaceId,catalogSourceSpanSha256:source.sourceSpan.sha256,catalogSourceSpanStatus:"STALE_RELOCATED_AT_WAVE10"},frozenSourceCommit:"15abb95203e7eb375c9f0bd4294a0ec7100aa1a6",chainLocators:[locate("개발환경_고도화/runtime/src/app.ts","/api/v1/integrations/iris/events"),locate("개발환경_고도화/runtime/src/integration/event-processing-service.ts","export class ProcessIrisEventService"),locate("개발환경_고도화/runtime/src/dispatch/command-dispatcher.ts","async resolveReadOnly("),locate(def.serviceFile,"withTransaction")],errorScenarios:["ROLLBACK"],scenarioInputsByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].input])),queryPlanByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].queries])),mutationPlanByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].mutations])),expectedResultsByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].result]))};cases.push({caseId:def.caseId,executablePath:"Iris HTTP event→normalize/process inbox→app outer gates→partial dispatch→CommandDispatcher→production pendant read service→processing.replies",transactionPath:"actual pendant read service transaction/outbox; external sender/network excluded",requiredScenarios:receiptScenarios,riskScenarios,consumers:[consumer]});for(const scenario of receiptScenarios)bindings.push({consumerId:def.consumerId,harnessId:"harness:object-db-executable-parity:wave10",harnessCaseId:def.caseId,fixtureId:"fixture:object-db-executable-parity:wave10:pendant-read:v1",scenarioId:`scenario:${scenario.toLowerCase().replaceAll("_","-")}`,scenarioKind:scenario});for(const scenario of riskScenarios)riskBindings.push({consumerId:def.consumerId,harnessId:"harness:object-db-executable-parity:wave10",harnessCaseId:def.caseId,fixtureId:"fixture:object-db-executable-parity:wave10:pendant-read:v1",scenarioId:`scenario:${scenario.toLowerCase().replaceAll("_","-")}`,scenarioKind:scenario});}
writeFileSync(resolve(root,output),JSON.stringify({format:"hoibot-object-db-consumer-parity-case-fixture-v1",fixtureId:"fixture:object-db-executable-parity:wave10:pendant-read:v1",bindings,payload:{cases,riskBindings,riskNotes:["펜던트 상세 계산의 등급·강화 수치가 서비스에 하드코딩되어 정의 DB 변경과 불일치할 위험이 있습니다.","펜던트 확률 조회는 기존 item_definitions.code에 의존합니다. 이미 적용된 migration/provider는 Wave10에서 수정하지 않습니다.","세 서비스 모두 재시도 정책 없이 FOR UPDATE를 사용하며 lock 순서를 변경하지 않습니다.","eventId만 멱등성 키이므로 payload·destination 변경은 기존 결과를 재사용합니다.","오픈톡 identity 누락과 비운영 채널은 app/service 경계에서 reply와 DML 없이 종료합니다."]}},null,2)+"\n");console.log(JSON.stringify({status:"PASS",consumers:definitions.length,bindings:bindings.length,risks:riskBindings.length}));
