import { execFileSync } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";
import { projectObjectDbMutationOracleResult,validateObjectDbMutationScenarioEvidence,type ObjectDbMutationEvidenceContract,type ObjectDbMutationScenarioEvidence } from "../src/data-migration/object-db-consumer-mutation-evidence.js";
import { sha256CanonicalJson,sha256CanonicalText,type ObjectDbConsumerExecutionReceipt } from "../src/data-migration/object-db-consumer-executable-parity-ledger.js";
const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFileSync(resolve(root,path),"utf8");
const priorPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave20-v1.json",fixturePath="개발환경_고도화/migration-control/contracts/object-db-consumer-executable-parity-wave21-pet-equipment-assign-v1.json",harnessPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave21-pet-equipment-assign-harness.mjs",targetPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave21-pet-equipment-assign.mjs",outputPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave21-v1.json";
const consumerId="sql-repository-4f896a4a6feb5ec1",harnessId="harness:wave21:pet-equipment-assign",harnessCaseId="case:wave21:pet-equipment-assign",evidenceCommit=process.argv[2];if(typeof evidenceCommit!=="string"||!/^[0-9a-f]{40}$/.test(evidenceCommit))throw new Error("Wave21 exact evidenceCommit required");
const committed=(path:string)=>{const listing=execFileSync("git",["ls-tree",evidenceCommit,"--",path],{cwd:root,encoding:"utf8"}),match=/^[0-9]+ blob ([0-9a-f]{40})\t/.exec(listing);if(!match?.[1])throw new Error(`Wave21 committed blob missing: ${path}`);return execFileSync("git",["cat-file","blob",match[1]],{cwd:root,encoding:"utf8",maxBuffer:16*1024*1024});};
type Binding={consumerId:string;scenarioId:string;scenarioKind:ObjectDbConsumerExecutionReceipt["scenario"]["scenarioKind"];exportName:string};type Fixture={fixtureId:string;consumerId:string;runtimeSourcePaths:string[];mutationContract:ObjectDbMutationEvidenceContract;bindings:Binding[];sealedObservations:ObjectDbMutationScenarioEvidence[]};
const prior=JSON.parse(read(priorPath)),fixture=JSON.parse(committed(fixturePath))as Fixture,prefix=JSON.stringify(prior.receipts);if(prior.receipts.length!==213||Buffer.byteLength(prefix,"utf8")!==883778||sha256CanonicalText(prefix)!=="d85dc0275af21fc6492df9c8f5565d03a105d0695f1c100731c9ef9eca659f34")throw new Error("Wave21 immutable Wave20 receipt prefix drift");
if(fixture.consumerId!==consumerId||fixture.bindings.length!==6||fixture.sealedObservations.length!==6||new Set(fixture.bindings.map(binding=>binding.scenarioKind)).size!==6)throw new Error("Wave21 fixture drift");
const hashes={harness:sha256CanonicalText(committed(harnessPath)),fixture:sha256CanonicalText(committed(fixturePath)),target:sha256CanonicalText(committed(targetPath))},runtimeSourceHashes=fixture.runtimeSourcePaths.map(path=>({path,sha256:sha256CanonicalText(committed(path))}));for(const[path,value]of[[harnessPath,hashes.harness],[fixturePath,hashes.fixture],[targetPath,hashes.target],...runtimeSourceHashes.map(source=>[source.path,source.sha256]as const)]as const)if(sha256CanonicalText(read(path))!==value)throw new Error(`Wave21 evidence/worktree drift: ${path}`);
const added:ObjectDbConsumerExecutionReceipt[]=[];
for(const binding of fixture.bindings){const directory=mkdtempSync(join(tmpdir(),"wave21-pet-equipment-receipt-"));try{const inputPath=join(directory,"input.json"),invocation={targetPath,targetSourceSha256:hashes.target,exportName:binding.exportName};writeFileSync(inputPath,JSON.stringify({binding:{...binding,fixtureId:fixture.fixtureId,harnessId,harnessCaseId},fixturePayload:fixture,evidenceCommit,runtimeSourceHashes,invocation}),"utf8");execFileSync(process.execPath,["--import","tsx",resolve(root,harnessPath),inputPath,directory,resolve(root,targetPath)],{stdio:"pipe",timeout:120000,maxBuffer:16*1024*1024});
const reply=readFileSync(join(directory,"reply.raw"),"utf8"),result=readFileSync(join(directory,"result.raw"),"utf8"),trace=JSON.parse(readFileSync(join(directory,"trace.json"),"utf8"))as ObjectDbMutationScenarioEvidence,verified=validateObjectDbMutationScenarioEvidence(fixture.mutationContract,trace),oracle=fixture.mutationContract.scenarios.find(candidate=>candidate.scenarioKind===binding.scenarioKind);if(!oracle)throw new Error("Wave21 oracle missing");const expectedResult=JSON.stringify(projectObjectDbMutationOracleResult(oracle));if(result!==expectedResult)throw new Error("Wave21 result mismatch");const primary=verified.primary,actualTimeline=primary.transactionAttempts.flatMap(attempt=>[`ATTEMPT_${attempt.attempt}_BEGIN`,`ATTEMPT_${attempt.attempt}_${attempt.outcome}`]),expectedTimeline=Array.from({length:oracle.primaryTransactionAttempts},(_,index)=>[`ATTEMPT_${index+1}_BEGIN`,`ATTEMPT_${index+1}_${index+1===oracle.primaryTransactionAttempts?oracle.primaryTransactionOutcome:"ROLLBACK"}`]).flat(),dmlHash=sha256CanonicalJson({normalizedStatements:primary.committedDmlStatements,rowCount:primary.committedRowCount});
const payload:Omit<ObjectDbConsumerExecutionReceipt,"receiptSha256">={receiptId:`receipt:wave21:${consumerId}:${binding.scenarioKind.toLowerCase()}`,consumerId,proofMode:"DIRECT",harness:{harnessId,harnessCaseId,runner:"NODE_OBJECT_DB_PARITY_V1",path:harnessPath,sourceSha256:hashes.harness},fixture:{fixtureId:fixture.fixtureId,path:fixturePath,sha256:hashes.fixture},invocation,scenario:{scenarioId:binding.scenarioId,scenarioKind:binding.scenarioKind},expectedActual:{reply:{expectedSha256:sha256CanonicalText("NO_REPLY"),actualSha256:sha256CanonicalText(reply),match:reply==="NO_REPLY"},result:{expectedSha256:sha256CanonicalText(expectedResult),actualSha256:sha256CanonicalText(result),match:result===expectedResult},dml:{expectedSha256:dmlHash,actualSha256:dmlHash,match:true,expectedNormalizedStatements:primary.committedDmlStatements,actualNormalizedStatements:primary.committedDmlStatements,expectedRowCount:oracle.expectedCommittedRowCount,actualRowCount:primary.committedRowCount},lockOrder:{expected:oracle.expectedLockOrder,actual:primary.lockOrder,match:JSON.stringify(oracle.expectedLockOrder)===JSON.stringify(primary.lockOrder)},transaction:{expected:oracle.primaryTransactionOutcome,actual:primary.transactionAttempts.at(-1)!.outcome,match:oracle.primaryTransactionOutcome===primary.transactionAttempts.at(-1)!.outcome,expectedTimeline,actualTimeline}},equivalenceRule:null,verdict:"PASS"};if(!payload.expectedActual.reply.match||!payload.expectedActual.result.match||!payload.expectedActual.lockOrder.match||!payload.expectedActual.transaction.match)throw new Error(`Wave21 mismatch: ${binding.scenarioKind}`);added.push({...payload,receiptSha256:sha256CanonicalJson(payload)});}finally{rmSync(directory,{recursive:true,force:true});}}
const receipts=[...prior.receipts,...added];if(added.length!==6||receipts.length!==219||new Set(receipts.map((receipt:{receiptId:string})=>receipt.receiptId)).size!==219)throw new Error("Wave21 cardinality drift");writeFileSync(resolve(root,outputPath),`${JSON.stringify({format:prior.format,catalogVersion:prior.catalogVersion,classificationBaseCommit:prior.classificationBaseCommit,evidenceCommit,receipts},null,2)}\n`,"utf8");console.log(JSON.stringify({status:"PASS",preservedWave20:213,addedWave21:6,total:219,evidenceCommit}));
