import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { CharacterCountStatsService } from "../src/admin/character-count-stats-service.js";

const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFileSync(resolve(root,path),"utf8").replace(/\r\n?/g,"\n"),sha=(value:string)=>createHash("sha256").update(value).digest("hex"),normalize=(sql:string)=>sql.replace(/\s+/g," ").trim();
const output="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave12-character-count-v1.json",consumerId="admin-command-96dcd3753578c56c",caseId="case:admin-character-count",handlerKey="admin_character_count_stats";
const receiptScenarios=["READ_POSITIVE","NEGATIVE_GUARD","EXACT_OUTPUT","SOURCE_DOMAIN_DML_ZERO","RESTART_CONSISTENCY"],riskScenarios=["AUTH_DENIED","WRONG_OPERATIONAL_CHANNEL","APP_INBOX_DUPLICATE","SAME_EVENT_REPLAY","ROLLBACK","TRANSIENT_1213_RETRY"];
const sourceCodes=["member","pet_home","equipped_furniture","member_pet","pet_skill","member_title","pet_title","mini_pet_title","mini_pet_collection","trial_tower","pet_explore","guild","attendance_light","board","free_market"];
const rawByCode=Object.fromEntries(sourceCodes.map(code=>[code,oracleRaw(code)]));
const sourceRows=sourceCodes.map(source_code=>{const raw_json=rawByCode[source_code]!;return{source_code,raw_json,content_sha256:sha(raw_json),utf16_code_unit_count:BigInt(raw_json.length),entity_count:0n,read_status:"valid"};});
const independentReply=oracleReply();
const safe=(value:any):any=>typeof value==="bigint"?{$bigint:value.toString()}:Array.isArray(value)?value.map(safe):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,child])=>[key,safe(child)])):value;
const evidenceZero=()=>({operations:0,outbox_messages:0,command_executions:0,command_audit:0,admin_character_count_stat_executions:0});
const storedResult=(environment:"dev"|"prod",fingerprint:string)=>({status:"counted",requestFingerprint:fingerprint,environment,databaseIdentity:`hoibot-${environment}`,snapshotVersion:"12001",snapshotAt:"2026-09-07 05:18:00",sourceCount:15,projectionCount:16,stats:[],data:independentReply,outboxId:"601",auditId:"801"});

function locate(file:string,needle:string){const source=read(file),start=source.indexOf(needle);if(start<0)throw new Error(`${file} missing ${needle}`);const end=start+needle.length;return{file,start,end,sha256:sha(source.slice(start,end)),needle};}
function rowsFor(scenario:string,sql:string,environment:"dev"|"prod",fingerprint:string){
 if(sql.includes("FROM command_aliases"))return[{command_code:"ADMIN_CHARACTER_COUNT_STATS",handler_key:handlerKey,auth_scope:"ADMIN",rollout_state:"ACTIVE"}];
 if(sql==="SELECT id FROM channels WHERE provider_code = ? AND external_channel_id = ?")return[{id:11n}];
 if(sql==="SELECT id FROM external_identities WHERE provider_code = 'kakao' AND external_user_id = ?")return[{id:42n}];
 if(sql.startsWith("SELECT attempt_count + 1 AS next_attempt FROM outbox_messages"))return[{next_attempt:1n}];
 if(sql.includes("FROM external_identities identity JOIN admin_operator_external_identities"))return scenario==="AUTH_DENIED"?[]:[{id:412901n}];
 if(sql.startsWith("SELECT id,status,result_json,TIMESTAMPDIFF"))return scenario==="SAME_EVENT_REPLAY"?[{id:501n,status:"completed",result_json:storedResult(environment,fingerprint),age_seconds:0n}]:[{id:501n,status:"processing",result_json:{requestFingerprint:fingerprint},age_seconds:0n}];
 if(sql.startsWith("SELECT database_identity,active_snapshot_set_id FROM legacy_snapshot_environments"))return[{database_identity:`hoibot-${environment}`,active_snapshot_set_id:71n}];
 if(sql.startsWith("SELECT id,database_identity,snapshot_version"))return[{id:71n,database_identity:`hoibot-${environment}`,snapshot_version:12001n,snapshot_at:"2026-09-07 05:18:00"}];
 if(sql.startsWith("SELECT source_code,raw_json,content_sha256"))return sourceRows;
 throw new Error(`${scenario} unhandled query: ${sql}`);
}
function insertId(sql:string){if(sql.startsWith("INSERT IGNORE INTO operations"))return 501n;if(sql.startsWith("INSERT INTO outbox_messages"))return 601n;if(sql.startsWith("INSERT INTO command_executions"))return 701n;if(sql.startsWith("INSERT INTO admin_character_count_stat_executions"))return 751n;if(sql.startsWith("INSERT INTO command_audit"))return 801n;if(sql.startsWith("INSERT INTO delivery_attempts"))return 901n;return 0n;}
async function capture(scenario:string){
 const environment=scenario==="EXACT_OUTPUT"||scenario==="RESTART_CONSISTENCY"?"prod":"dev",providerEventId=`wave12-character-${scenario.toLowerCase()}`,eventId=`iris:${providerEventId}`,externalUserId=scenario==="AUTH_DENIED"?"wave12-denied":"wave12-admin",destinationId="wave12-character-room",message=scenario==="NEGATIVE_GUARD"?"/글자수통계 안내":"/글자수통계",fingerprint=sha([environment,eventId,externalUserId,destinationId,message].join("\n"));
 const queries:any[]=[],mutations:any[]=[],transactionEvents:string[]=[],evidenceRows=scenario==="SAME_EVENT_REPLAY"?{operations:1,outbox_messages:1,command_executions:1,command_audit:1,admin_character_count_stat_executions:1}:evidenceZero(),before={...evidenceRows},tables=new Set(Object.keys(evidenceRows));let transactionAttempt=0;
 const db:any={ping:async()=>undefined,close:async()=>undefined,verifyRollback:async()=>true,withTransaction:async(work:any)=>{const characterEntry=(new Error().stack??"").includes("CharacterCountStatsService.read");if(characterEntry)transactionAttempt+=1;transactionEvents.push("BEGIN");if(scenario==="TRANSIENT_1213_RETRY"&&characterEntry&&transactionAttempt===1){transactionEvents.push("ROLLBACK");const error:any=new Error("wave12 transient deadlock");error.code="ER_LOCK_DEADLOCK";error.errno=1213;throw error;}const state={...evidenceRows};try{const value=await work(db);transactionEvents.push("COMMIT");return value;}catch(error){Object.assign(evidenceRows,state);transactionEvents.push("ROLLBACK");throw error;}},query:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),rows=rowsFor(scenario,normalized,environment,fingerprint);queries.push({expectedNormalizedSql:normalized,expectedValues:safe(values),rows:safe(rows)});return rows;},execute:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),id=insertId(normalized),affectedRows=scenario==="SAME_EVENT_REPLAY"&&normalized.startsWith("INSERT IGNORE INTO operations")?0:1,step:any={expectedNormalizedSql:normalized,expectedValues:safe(values).map((value:any,index:number)=>index===0&&normalized.startsWith("INSERT IGNORE INTO operations")?{matcher:"UUID_V4"}:value),affectedRows,insertId:id.toString()};if(scenario==="APP_INBOX_DUPLICATE"&&normalized.startsWith("INSERT INTO event_inbox"))step.error={message:"wave12 duplicate inbox",code:"ER_DUP_ENTRY",errno:1062};if(scenario==="ROLLBACK"&&normalized.startsWith("INSERT INTO command_audit"))step.error={message:"wave12 forced audit failure",code:"ER_SIGNAL_EXCEPTION",errno:1644};mutations.push(step);if(step.error){const error:any=new Error(step.error.message);Object.assign(error,step.error);throw error;}const table=/^(?:INSERT(?: IGNORE)? INTO|UPDATE)\s+([A-Za-z0-9_]+)/i.exec(normalized)?.[1];if(table!==undefined&&tables.has(table))evidenceRows[table]+=affectedRows;return{affectedRows:BigInt(affectedRows),insertId:id};}};
 const replies:Array<{room:string;data:string}>=[];let serviceInvocationCount=0;const original=CharacterCountStatsService.prototype.read;CharacterCountStatsService.prototype.read=async function(...args:any[]){serviceInvocationCount+=1;return original.apply(this,args as never);};const token="wave12-fixture-token",wrong=scenario==="WRONG_OPERATIONAL_CHANNEL",config=loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:environment,IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave12-fixture-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:"127.0.0.1",DATABASE_PORT:"3306",DATABASE_USER:"unused",DATABASE_PASSWORD:"unused",DATABASE_NAME:"unused"}),app=buildApp(config,{database:db,inspectIrisChannel:async()=>wrong?{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async reply=>{replies.push(reply);}});
 let response;try{response=await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:message,room:"Wave12 글자수방",json:{_id:providerEventId,chat_id:destinationId,user_id:externalUserId}}});}finally{CharacterCountStatsService.prototype.read=original;await app.close();}
 const body=JSON.parse(response.body),noReply=scenario==="NEGATIVE_GUARD"?"INVALID_COMMAND_NO_CALL":scenario==="AUTH_DENIED"?"AUTH_DENIED_NO_REPLY":scenario==="WRONG_OPERATIONAL_CHANNEL"?"WRONG_ROOM_NO_CALL":scenario==="APP_INBOX_DUPLICATE"?"APP_INBOX_DUPLICATE_NO_CALL":scenario==="ROLLBACK"?"ROLLBACK_NO_REPLY":"NO_REPLY",reply=replies[0]?.data??noReply,result=JSON.stringify({statusCode:response.statusCode,accepted:body.accepted??false,ignored:body.ignored??false,channelMode:body.channelMode??null,duplicate:body.duplicate??false,environment,serviceInvocationCount,evidenceRowsBefore:before,evidenceRowsAfter:{...evidenceRows},sentReplies:replies});
 if(["READ_POSITIVE","EXACT_OUTPUT","SOURCE_DOMAIN_DML_ZERO","RESTART_CONSISTENCY","TRANSIENT_1213_RETRY"].includes(scenario)&&reply!==independentReply)throw new Error(`${scenario} independent oracle drift`);if(scenario==="ROLLBACK"&&(!transactionEvents.includes("ROLLBACK")||Object.values(evidenceRows).some(value=>value!==0)))throw new Error("rollback evidence drift");
 return{input:{providerEventId,eventId,externalUserId,destinationId,message,environment},queries,mutations,transactionEvents,httpOracle:{statusCode:response.statusCode,accepted:body.accepted??false,ignored:body.ignored??false,channelMode:body.channelMode??null,duplicate:body.duplicate??false,environment,serviceInvocationCount,evidenceRowsBefore:before,evidenceRowsAfter:{...evidenceRows},sentReplies:replies,noReplyCode:noReply},reply,result};
}
const manifest=JSON.parse(read("개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json")),source=manifest.consumers.find((entry:any)=>entry.consumerId===consumerId);if(!source)throw new Error("Wave12 consumer missing");const captured:Record<string,any>={};for(const scenario of[...receiptScenarios,...riskScenarios])captured[scenario]=await capture(scenario);
const sourceLocator={...locate(source.file,"isCharacterCountStatsCommand(message)"),symbol:source.symbol,triggerOrPredicate:source.triggerOrPredicate,interfaceId:source.interfaceId,catalogSourceSpanSha256:source.sourceSpan.sha256,catalogSourceSpanStatus:"STALE_RELOCATED_AT_WAVE12"},consumer={consumerId,sourceLocator,frozenSourceCommit:process.argv[2]??"SOURCE_COMMIT_REQUIRED",chainLocators:[locate("개발환경_고도화/runtime/src/app.ts","new IrisAdminCommandService"),locate("개발환경_고도화/runtime/src/integration/event-processing-service.ts","export class ProcessIrisEventService"),locate("개발환경_고도화/runtime/src/dispatch/command-dispatcher.ts","async resolveReadOnly("),locate("개발환경_고도화/runtime/src/admin/character-count-stats-service.ts","class CharacterCountStatsService")],serviceCallsite:locate("개발환경_고도화/runtime/src/admin/character-count-stats-service.ts","withDeadlockRetry(()=>this.database.withTransaction"),errorScenarios:["ROLLBACK"],scenarioInputsByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.input])),queryPlanByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.queries])),mutationPlanByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.mutations])),expectedResultsByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.result])),expectedReplyByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.reply])),httpOracleByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.httpOracle])),transactionEventsByScenario:Object.fromEntries(Object.entries(captured).map(([key,value])=>[key,value.transactionEvents]))};
const bindings=receiptScenarios.map(scenarioKind=>({consumerId,harnessId:"harness:object-db-executable-parity:wave12",harnessCaseId:caseId,fixtureId:"fixture:object-db-executable-parity:wave12:character-count:v1",scenarioId:`scenario:${scenarioKind.toLowerCase().replaceAll("_","-")}`,scenarioKind})),riskBindings=riskScenarios.map(scenarioKind=>({consumerId,harnessId:"harness:object-db-executable-parity:wave12",harnessCaseId:caseId,fixtureId:"fixture:object-db-executable-parity:wave12:character-count:v1",scenarioId:`scenario:${scenarioKind.toLowerCase().replaceAll("_","-")}`,scenarioKind}));
const fixture={format:"hoibot-object-db-consumer-parity-case-fixture-v1",fixtureId:"fixture:object-db-executable-parity:wave12:character-count:v1",bindings,payload:{cases:[{caseId,executablePath:"buildApp().inject Iris HTTP event→token→normalize→operational channel→ProcessIrisEventService inbox→partial dispatch→production character-count service→outbox delivery callback",transactionPath:"actual ProcessIrisEventService and CharacterCountStatsService transactions; callback stub only; external sender/network excluded",requiredScenarios:receiptScenarios,riskScenarios,consumers:[consumer]}],riskBindings,riskNotes:["오직 admin-command-96dcd3753578c56c만 DIRECT 승격한다.","맞짱시간체크는 checkRank/공통 timing 미증명, 상태전체는 production writer 부재로 미증명 상태를 유지한다.","fingerprint는 environment/event/actor/channel/message를 모두 결합하며 실제 MariaDB 테스트에서 각 drift를 fail closed 검증한다.","source domain DML은 legacy snapshot 세 테이블 explicit allowlist에 대한 statement trace 0건으로 검증한다."]}};
writeFileSync(resolve(root,output),JSON.stringify(fixture,null,2)+"\n","utf8");console.log(JSON.stringify({status:"PASS",cases:1,receipts:bindings.length,risks:riskBindings.length,output}));

function oracleRaw(code:string):string{if(code==="member")return JSON.stringify({member:{가:{},나:{}}});if(code==="member_pet")return JSON.stringify({가:{pendant:{}},나:{pendantBag:[]},다:{pendantBag:{}}});if(["member_title","pet_title","mini_pet_title","mini_pet_collection"].includes(code))return JSON.stringify({member:{가:{}}});if(code==="trial_tower")return JSON.stringify({user:{가:{}}});if(code==="pet_explore")return JSON.stringify({userBet:{가:{}},autoFixedDungeon:{나:{}},record:{다:{}},bet:{x:[{user:"라"}]}});if(code==="guild")return JSON.stringify({guilds:{g1:{members:{가:{},나:{}}},g2:{members:{나:{},다:{}}}}});if(code==="attendance_light")return JSON.stringify({users:{가:{},나:{}}});if(code==="board")return JSON.stringify({memo:[{user:"가"}],record:[{user:"나"},{user:"가"}]});if(code==="free_market")return JSON.stringify({listings:[{seller:"가"}],completedLogs:[{seller:"나",buyer:"다"}]});return JSON.stringify({가:{}});}
function oracleReply():string{const pendant=JSON.stringify({가:{pendant:{},pendantBag:[]},나:{pendant:null,pendantBag:[]},다:{pendant:null,pendantBag:{}}}),definitions=[["member","멤버","핵심 데이터",2,["/길드데이터동기화","/전체동기화"]],["pet_home","펫홈","핵심 데이터",1,["/장착가구동기화"]],["equipped_furniture","장착가구","핵심 데이터",1,["/장착가구동기화"]],["member_pet","펫멤버","핵심 데이터",3,["/펫데이터동기화","/전체동기화"]],["pet_skill","펫스킬","핵심 데이터",1,[]],["pendant","펜던트","핵심 데이터",3,[]],["member_title","회원칭호","칭호·성장 데이터",1,[]],["pet_title","펫칭호","칭호·성장 데이터",1,["/펫타이틀동기화","/전체동기화"]],["mini_pet_title","미니펫칭호","칭호·성장 데이터",1,[]],["mini_pet_collection","미니펫도감","칭호·성장 데이터",1,[]],["trial_tower","시련의탑","칭호·성장 데이터",1,["/시련의탑동기화","/전체동기화"]],["pet_explore","펫탐험","운영 데이터",4,[]],["guild","길드","운영 데이터",3,["/길드데이터동기화","/전체동기화"]],["attendance_light","경량출석","운영 데이터",2,[]],["board","게시판","운영 데이터",2,[]],["free_market","자유시장","운영 데이터",3,[]]]as const,lines=["📊 글자수 통계"];for(const section of["핵심 데이터","칭호·성장 데이터","운영 데이터"]){lines.push("",`[${section}]`);for(const[code,label,rowSection,count,sync]of definitions.filter(row=>row[2]===section)){const raw=code==="pendant"?pendant:rawByCode[code]!;lines.push(`- ${label}: ${raw.length.toLocaleString("en-US")}자 / ${count}명`);if(sync.length)lines.push(`  ↳ 동기화: ${sync.join(", ")}`);}}return lines.join("\n");}
