import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildApp } from "../src/app.js";
import { loadConfig } from "../src/config.js";
import { HomeFurnitureInfoReadService, isHomeFurnitureInfoReadCandidate } from "../src/home/home-furniture-info-read-service.js";
import { HomeFurnitureStatsReadService, isHomeFurnitureStatsReadCommand } from "../src/home/home-furniture-stats-read-service.js";

const root=resolve(import.meta.dirname,"../../..");
const read=(path:string)=>readFileSync(resolve(root,path),"utf8").replace(/\r\n?/g,"\n");
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const normalize=(sql:string)=>sql.replace(/\s+/g," ").trim();
const safe=(value:any):any=>typeof value==="bigint"?{$bigint:value.toString()}:Array.isArray(value)?value.map(safe):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,child])=>[key,safe(child)])):value;
const manifest=JSON.parse(read("개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"));
const output="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave11-home-furniture-read-v1.json";
const receiptScenarios=["READ_POSITIVE","NEGATIVE_GUARD","EXACT_OUTPUT","SOURCE_DOMAIN_DML_ZERO","RESTART_CONSISTENCY"];
const riskScenarios=["ROLLBACK","SAME_EVENT_REPLAY","APP_INBOX_DUPLICATE","MISSING_IDENTITY","NON_ADMIN_INFO","WRONG_OPERATIONAL_CHANNEL","VERIFIED_USER_LINKAGE_GAP"];
const definitions=[
 {consumerId:"runtime-dispatch-722afb15e9cbd92c",caseId:"case:home-furniture-info",message:"/가구정보 대상가구유저",invalid:"/가구 정보 대상가구유저",commandCode:"HOME_FURNITURE_INFO_READ",handlerKey:"home_furniture_info_read",serviceFile:"개발환경_고도화/runtime/src/home/home-furniture-info-read-service.ts",service:HomeFurnitureInfoReadService,guard:isHomeFurnitureInfoReadCandidate,scope:"home.furniture_info_read"},
 {consumerId:"runtime-dispatch-c3cb8d18613c2358",caseId:"case:home-furniture-stats",message:"/가구통계",invalid:"/가구통계 안내",commandCode:"HOME_FURNITURE_STATS_READ",handlerKey:"home_furniture_stats_read",serviceFile:"개발환경_고도화/runtime/src/home/home-furniture-stats-read-service.ts",service:HomeFurnitureStatsReadService,guard:isHomeFurnitureStatsReadCommand,scope:"home.furniture_stats_read"},
] as const;
type Definition=typeof definitions[number];
const zero=()=>({operations:0,outbox_messages:0,command_executions:0,command_audit:0});
function locate(file:string,needle:string){const source=read(file);if(!source.includes(needle))throw new Error(`${file} missing ${needle}`);return{file,start:0,end:source.length,sha256:sha(source),needle};}
function locateAppBranch(handlerKey:string){const file="개발환경_고도화/runtime/src/app.ts",source=read(file),anchor=`partialDispatchDecision.handlerKey === "${handlerKey}"`,compact=`partialDispatchDecision.handlerKey==="${handlerKey}"`,index=Math.max(source.indexOf(anchor),source.indexOf(compact));if(index<0)throw new Error(`app missing ${handlerKey}`);const start=Math.max(source.lastIndexOf("      if (isOperationalChannel",index),source.lastIndexOf("      if(isOperationalChannel",index));const marker=source.indexOf("\n      }",index),end=marker<0?source.indexOf("\n\n",index):marker+8;if(start<0||end<=start)throw new Error(`app span missing ${handlerKey}`);const span=source.slice(start,end);return{file,start,end,sha256:sha(span),needle:handlerKey};}
function replayResult(def:Definition){return def.handlerKey==="home_furniture_info_read"?{status:"read",targetPlayerId:"203003",bagCount:6,reply:"저장된 가구정보",outboxId:"601"}:{data:"저장된 가구통계",outboxId:"601",gradeCount:4,totalCount:"8"};}
const infoBag=[
 {id:11n,display_name:"별빛 침대⭐",charm_snapshot:1234567n,grade_display_name:"창조"},
 {id:12n,display_name:"달빛 소파🌙",charm_snapshot:500000n,grade_display_name:"신화"},
 {id:13n,display_name:"가나다 의자",charm_snapshot:3000n,grade_display_name:"A"},
 {id:14n,display_name:"라마바 탁자",charm_snapshot:2000n,grade_display_name:"B"},
 {id:15n,display_name:"사아자 램프💡",charm_snapshot:1000n,grade_display_name:"C"},
 {id:16n,display_name:"여섯번째 장롱🗄️",charm_snapshot:999n,grade_display_name:"등급없음"},
];
const statsRows=[{grade_name:"A",count_value:3n,first_id:11n},{grade_name:"B",count_value:2n,first_id:20n},{grade_name:"C",count_value:2n,first_id:30n},{grade_name:"기타",count_value:1n,first_id:40n}];
function rowsFor(def:Definition,scenario:string,sql:string){
 if(sql.includes("FROM command_aliases"))return[{command_code:def.commandCode,handler_key:def.handlerKey,auth_scope:"VERIFIED_USER",rollout_state:"ACTIVE"}];
 if(sql==="SELECT id FROM channels WHERE provider_code = ? AND external_channel_id = ?")return[{id:11n}];
 if(sql==="SELECT id FROM external_identities WHERE provider_code = 'kakao' AND external_user_id = ?")return scenario==="VERIFIED_USER_LINKAGE_GAP"?[]:[{id:42n}];
 if(sql.startsWith("SELECT attempt_count + 1 AS next_attempt FROM outbox_messages"))return[{next_attempt:1n}];
 if(def.handlerKey==="home_furniture_info_read"&&sql.includes("FROM external_identities identity")&&sql.includes("admin_operator_external_identities"))return["MISSING_IDENTITY","NON_ADMIN_INFO","VERIFIED_USER_LINKAGE_GAP"].includes(scenario)?[]:[{operator_id:203901n}];
 if(sql.startsWith("SELECT result_json FROM operations"))return scenario==="SAME_EVENT_REPLAY"?[{result_json:replayResult(def)}]:[];
 if(def.handlerKey==="home_furniture_info_read"){
  if(sql.includes("FROM players player JOIN player_profiles"))return[{player_id:203003n,display_name:"대상가구유저",rank_emoji:"🥇",home_name:"별빛 하우스🏠",base_experience:1000000n,like_count:12345n,floor_area:100n}];
  if(sql.includes("FROM player_passes"))return[{count_value:1n}];
  if(sql.includes("FROM furniture_inventory_instances instance JOIN furniture_definitions"))return infoBag;
  if(sql.includes("COUNT(*) count_value,COALESCE(SUM(charm_snapshot),0)"))return[{count_value:2n,charm_value:2345678n}];
  if(sql.includes("FROM player_pets WHERE"))return[{id:203777n}];
  if(sql.includes("FROM pet_skills owned JOIN skill_definitions"))return[{code:"pet_skill_building_owner"}];
  if(sql.includes("FROM home_furniture_equip_policy"))return[{large_floor_threshold:50n,small_floor_divisor:10n,small_floor_base_slots:3n,large_floor_base_slots:8n,large_floor_divisor:20n,building_owner_bonus:2n,god_building_owner_bonus:4n,premium_bonus:3n}];
 }
 if(def.handlerKey==="home_furniture_stats_read"&&sql.includes("FROM furniture_inventory_instances WHERE status='bag' GROUP BY"))return statsRows;
 throw new Error(`${def.consumerId}/${scenario} unhandled query: ${sql}`);
}
function insertId(sql:string){if(sql.startsWith("INSERT INTO operations"))return 501n;if(sql.startsWith("INSERT INTO outbox_messages"))return 601n;if(sql.startsWith("INSERT INTO command_executions"))return 701n;if(sql.startsWith("INSERT INTO command_audit"))return 801n;if(sql.startsWith("INSERT INTO delivery_attempts"))return 901n;return 0n;}
async function capture(def:Definition,scenario:string){
 const providerEventId=`wave11-${def.consumerId}-${scenario.toLowerCase()}`,linkageGap=scenario==="VERIFIED_USER_LINKAGE_GAP";
 const input:any={providerEventId,eventId:`iris:${providerEventId}`,externalUserId:["MISSING_IDENTITY","NON_ADMIN_INFO"].includes(scenario)?"unlinked-home-user":linkageGap?"stats-linkage-gap":"home-admin",destinationId:"home-room",message:scenario==="NEGATIVE_GUARD"?def.invalid:def.message};
 const queries:any[]=[],mutations:any[]=[],transactionEvents:string[]=[];
 const replay=["SAME_EVENT_REPLAY","APP_INBOX_DUPLICATE"].includes(scenario),evidenceRows:Record<string,number>=replay?{operations:1,outbox_messages:1,command_executions:1,command_audit:1}:zero(),before={...evidenceRows},tables=new Set(Object.keys(evidenceRows));
 const db:any={ping:async()=>undefined,close:async()=>undefined,verifyRollback:async()=>true,withTransaction:async(work:any)=>{transactionEvents.push("BEGIN");const state={...evidenceRows};try{const value=await work(db);transactionEvents.push("COMMIT");return value;}catch(error){Object.assign(evidenceRows,state);transactionEvents.push("ROLLBACK");throw error;}},query:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),rows=rowsFor(def,scenario,normalized);queries.push({expectedNormalizedSql:normalized,expectedValues:safe(values),rows:safe(rows)});return rows;},execute:async(sql:string,values:any[]=[])=>{const normalized=normalize(sql),id=insertId(normalized),step:any={expectedNormalizedSql:normalized,expectedValues:safe(values).map((value:any,index:number)=>index===0&&normalized.startsWith("INSERT INTO operations")?{matcher:"UUID_V4"}:value),affectedRows:1,insertId:id.toString()};if(scenario==="APP_INBOX_DUPLICATE"&&normalized.startsWith("INSERT INTO event_inbox"))step.error={message:"wave11 duplicate inbox",code:"ER_DUP_ENTRY",errno:1062};if(scenario==="ROLLBACK"&&normalized.startsWith("INSERT INTO command_audit")&&normalized.includes(`'${def.commandCode}'`))step.error={message:"wave11 forced middle-DML rollback",code:"ER_SIGNAL_EXCEPTION",errno:1644};mutations.push(step);if(step.error){const error:any=new Error(step.error.message);Object.assign(error,step.error);throw error;}const table=/^INSERT INTO\s+([A-Za-z0-9_]+)/i.exec(normalized)?.[1];if(table!==undefined&&tables.has(table))evidenceRows[table]+=1;return{affectedRows:1n,insertId:id};}};
 const sentReplies:Array<{room:string;data:string}>=[];let serviceInvocationCount=0;const original=def.service.prototype.read;def.service.prototype.read=async function(...args:any[]){serviceInvocationCount+=1;return original.apply(this,args as never);};
 const token="wave11-in-memory-token",wrong=scenario==="WRONG_OPERATIONAL_CHANNEL";const app=buildApp(loadConfig({NODE_ENV:"test",HOIBOT_ENVIRONMENT_CODE:"dev",IRIS_SHARED_TOKEN:token,USER_VERIFICATION_PEPPER:"wave11-in-memory-pepper",DATABASE_ENABLED:"true",DATABASE_HOST:"127.0.0.1",DATABASE_PORT:"3306",DATABASE_USER:"unused",DATABASE_PASSWORD:"unused",DATABASE_NAME:"unused"}),{database:db,inspectIrisChannel:async()=>wrong?{mode:"denied",channelClass:"open_group",reason:"not_designated",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}}:{mode:"operational",channelClass:"open_group",reason:"allowed",evidence:{roomType:"OM",openLinkActive:true,openLinkExpired:false}},sendIrisTextReply:async(reply)=>{sentReplies.push(reply);},sendIrisImageReply:async()=>{throw new Error("Wave11 unexpected image reply");}});
 let response;try{response=await app.inject({method:"POST",url:`/api/v1/integrations/iris/events?token=${token}`,payload:{msg:input.message,room:"Wave11 가구방",json:{_id:input.providerEventId,chat_id:input.destinationId,user_id:input.externalUserId}}});}finally{def.service.prototype.read=original;await app.close();}
 const body=JSON.parse(response.body),statsGapExec=def.handlerKey==="home_furniture_stats_read"&&linkageGap,noReplyCode=scenario==="NEGATIVE_GUARD"?"INVALID_COMMAND_NO_CALL":scenario==="APP_INBOX_DUPLICATE"?"APP_INBOX_DUPLICATE_NO_CALL":scenario==="WRONG_OPERATIONAL_CHANNEL"?"WRONG_OPERATIONAL_CHANNEL_NO_CALL":scenario==="ROLLBACK"?"SERVICE_ROLLBACK_NO_REPLY":(["MISSING_IDENTITY","NON_ADMIN_INFO","VERIFIED_USER_LINKAGE_GAP"].includes(scenario)&&!statsGapExec)?"IDENTITY_OR_ADMIN_GAP_NO_REPLY":"NO_REPLY";
 const httpOracle={statusCode:response.statusCode,accepted:body.accepted??false,ignored:body.ignored??false,channelMode:body.channelMode??null,duplicate:body.duplicate??false,serviceInvocationCount,evidenceRowsBefore:before,evidenceRowsAfter:{...evidenceRows},sentReplies,noReplyCode};
 const reply=sentReplies[0]?.data??noReplyCode,result=JSON.stringify({statusCode:response.statusCode,accepted:body.accepted,ignored:body.ignored,channelMode:body.channelMode??null,duplicate:body.duplicate??false,serviceInvocationCount,evidenceRowsBefore:before,evidenceRowsAfter:{...evidenceRows},sentReplies});
 return{input,queries,mutations,transactionEvents,httpOracle,reply,result};
}
const cases:any[]=[],bindings:any[]=[],riskBindings:any[]=[];
for(const def of definitions){const source=manifest.consumers.find((entry:any)=>entry.consumerId===def.consumerId);if(!source)throw new Error(`missing ${def.consumerId}`);const captured:Record<string,any>={};for(const scenario of [...receiptScenarios,...riskScenarios])captured[scenario]=await capture(def,scenario);const consumer={consumerId:def.consumerId,sourceLocator:{...locateAppBranch(def.handlerKey),symbol:source.symbol,triggerOrPredicate:source.triggerOrPredicate,interfaceId:source.interfaceId,catalogSourceSpanSha256:source.sourceSpan.sha256,catalogSourceSpanStatus:"STALE_RELOCATED_AT_WAVE11"},frozenSourceCommit:"4ce4fd91a001abf2a16f5fe8b3a7098321e733f7",chainLocators:[locate("개발환경_고도화/runtime/src/app.ts","/api/v1/integrations/iris/events"),locate("개발환경_고도화/runtime/src/integration/event-processing-service.ts","export class ProcessIrisEventService"),locate("개발환경_고도화/runtime/src/dispatch/command-dispatcher.ts","async resolveReadOnly("),locate(def.serviceFile,"withTransaction")],errorScenarios:["ROLLBACK"],scenarioInputsByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].input])),queryPlanByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].queries])),mutationPlanByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].mutations])),expectedResultsByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].result])),expectedReplyByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].reply])),httpOracleByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].httpOracle])),transactionEventsByScenario:Object.fromEntries([...receiptScenarios,...riskScenarios].map(s=>[s,captured[s].transactionEvents]))};cases.push({caseId:def.caseId,executablePath:"buildApp().inject Iris HTTP event→token→normalize→operational channel→ProcessIrisEventService inbox→partial dispatch→production home furniture read service→outbox delivery callback",transactionPath:"actual ProcessIrisEventService, home furniture read service and recordOutboxDelivery transactions; callback stub only; external sender/network excluded",requiredScenarios:receiptScenarios,riskScenarios,consumers:[consumer]});for(const scenario of receiptScenarios)bindings.push({consumerId:def.consumerId,harnessId:"harness:object-db-executable-parity:wave11",harnessCaseId:def.caseId,fixtureId:"fixture:object-db-executable-parity:wave11:home-furniture-read:v1",scenarioId:`scenario:${scenario.toLowerCase().replaceAll("_","-")}`,scenarioKind:scenario});for(const scenario of riskScenarios)riskBindings.push({consumerId:def.consumerId,harnessId:"harness:object-db-executable-parity:wave11",harnessCaseId:def.caseId,fixtureId:"fixture:object-db-executable-parity:wave11:home-furniture-read:v1",scenarioId:`scenario:${scenario.toLowerCase().replaceAll("_","-")}`,scenarioKind:scenario});}
const actual={format:"hoibot-object-db-consumer-parity-case-fixture-v1",fixtureId:"fixture:object-db-executable-parity:wave11:home-furniture-read:v1",bindings,payload:{cases,riskBindings,riskNotes:["가구정보는 admin identity 연결이 없거나 비관리자면 ignored이며 가구통계는 VERIFIED_USER 라우팅에도 identity/player linkage를 서비스에서 확인하지 않아 외부 user id만으로 실행됩니다.","가구정보는 적용 완료된 legacy generic id/code/charm_snapshot projection을 읽습니다. Wave11은 기존 migration을 수정하지 않습니다.","inbox duplicate는 app processor에서 service 호출 전 차단되고 operation replay는 service transaction에서 저장 result를 반환하는 별도 멱등 경계입니다.","두 서비스 모두 eventId만 멱등 키로 사용하며 payload·destination 결합은 검증하지 않습니다.","조회 transaction은 source domain을 변경하지 않지만 operation/outbox/execution/audit와 delivery evidence는 기록합니다."]}};
const canonical=JSON.parse(read(output));if(JSON.stringify(actual)!==JSON.stringify(canonical))throw new Error("Wave11 independent canonical HTTP/SQL/row/output vector drift");console.log(JSON.stringify({status:"PASS",cases:cases.length,receipts:bindings.length,risks:riskBindings.length}));
