import{execFileSync}from"node:child_process";
import{mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";
import{tmpdir}from"node:os";
import{join,resolve}from"node:path";
import{sha256CanonicalJson,sha256CanonicalText,type ObjectDbConsumerExecutionReceipt}from"../src/data-migration/object-db-consumer-executable-parity-ledger.js";
const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFileSync(resolve(root,path),"utf8");
const priorPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave18-v1.json",fixturePath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-executable-parity-wave19-package-wizard-status-v1.json",harnessPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave19-package-wizard-status-harness.mjs",targetPath="개발환경_고도화/runtime/test/fixtures/object-db-executable-parity-wave19-package-wizard-status.mjs",outputPath="개발환경_고도화/migration-control/fixtures/synthetic-relational/object-db-consumer-execution-receipts-wave19-v1.json";
const consumerId="runtime-dispatch-79ff58fea52c7457",harnessId="harness:wave19:package-wizard-status",harnessCaseId="case:wave19:package-wizard-status",evidenceCommit=process.argv[2];
if(typeof evidenceCommit!=="string"||!/^[0-9a-f]{40}$/.test(evidenceCommit))throw new Error("Wave19 exact 40-character evidenceCommit required");
const committed=(path:string)=>{const listing=execFileSync("git",["ls-tree",evidenceCommit,"--",path],{cwd:root,encoding:"utf8"}),match=/^[0-9]+ blob ([0-9a-f]{40})\t/.exec(listing);if(match?.[1]===undefined)throw new Error(`Wave19 committed blob missing: ${path}`);return execFileSync("git",["cat-file","blob",match[1]],{cwd:root,encoding:"utf8",maxBuffer:16*1024*1024});};
type Binding={consumerId:string;scenarioId:string;scenarioKind:ObjectDbConsumerExecutionReceipt["scenario"]["scenarioKind"];exportName:string;expectedResultSha256:string};
const prior=JSON.parse(read(priorPath)),fixture=JSON.parse(committed(fixturePath))as{fixtureId:string;consumerId:string;runtimeSourcePaths:string[];bindings:Binding[]},prefix=JSON.stringify(prior.receipts);
if(prior.receipts.length!==202||Buffer.byteLength(prefix,"utf8")!==838358||sha256CanonicalText(prefix)!=="9d2772842555871d2b96c8c80c7029549b5d5f9a6f5d8d7e0aebcb1c0e7e9b7b")throw new Error("Wave19 immutable Wave18 receipt prefix drift");
if(fixture.consumerId!==consumerId||fixture.bindings.length!==5||new Set(fixture.bindings.map(binding=>binding.scenarioKind)).size!==5||fixture.bindings.some(binding=>binding.consumerId!==consumerId||binding.exportName!=="executeWave19PackageWizardStatus"))throw new Error("Wave19 fixture consumer/scenario drift");
const hashes={harness:sha256CanonicalText(committed(harnessPath)),fixture:sha256CanonicalText(committed(fixturePath)),target:sha256CanonicalText(committed(targetPath))},runtimeSourceHashes=fixture.runtimeSourcePaths.map(path=>({path,sha256:sha256CanonicalText(committed(path))}));
for(const[path,hash]of[[harnessPath,hashes.harness],[fixturePath,hashes.fixture],[targetPath,hashes.target],...runtimeSourceHashes.map(source=>[source.path,source.sha256]as const)]as const)if(sha256CanonicalText(read(path))!==hash)throw new Error(`Wave19 committed evidence/worktree drift: ${path}`);
const added:ObjectDbConsumerExecutionReceipt[]=[];
for(const sourceBinding of fixture.bindings){const dir=mkdtempSync(join(tmpdir(),"wave19-package-status-receipt-"));try{const binding={...sourceBinding,fixtureId:fixture.fixtureId,harnessId,harnessCaseId},input=join(dir,"input.json"),invocation={targetPath,targetSourceSha256:hashes.target,exportName:sourceBinding.exportName};writeFileSync(input,JSON.stringify({binding,evidenceCommit,runtimeSourceHashes,invocation}));execFileSync(process.execPath,["--import","tsx",resolve(root,harnessPath),input,dir,resolve(root,targetPath)],{stdio:"pipe",timeout:60000,maxBuffer:16*1024*1024});const reply=readFileSync(join(dir,"reply.raw"),"utf8"),result=readFileSync(join(dir,"result.raw"),"utf8"),trace=JSON.parse(readFileSync(join(dir,"trace.json"),"utf8"));if(sha256CanonicalText(result)!==sourceBinding.expectedResultSha256)throw new Error(`Wave19 independent output drift: ${sourceBinding.scenarioKind}`);if(trace.transaction!=="READ_ONLY"||trace.sourceDomainDmlCount!==0||trace.rowCount!==0||trace.normalizedStatements.length!==0)throw new Error(`Wave19 READ_ONLY/DML0 drift: ${sourceBinding.scenarioKind}`);const replyHash=sha256CanonicalText(reply),resultHash=sha256CanonicalText(result),dmlHash=sha256CanonicalJson({normalizedStatements:[],rowCount:0});const payload:Omit<ObjectDbConsumerExecutionReceipt,"receiptSha256">={receiptId:`receipt:wave19:${consumerId}:${sourceBinding.scenarioKind.toLowerCase()}`,consumerId,proofMode:"DIRECT",harness:{harnessId,harnessCaseId,runner:"NODE_OBJECT_DB_PARITY_V1",path:harnessPath,sourceSha256:hashes.harness},fixture:{fixtureId:fixture.fixtureId,path:fixturePath,sha256:hashes.fixture},invocation,scenario:{scenarioId:sourceBinding.scenarioId,scenarioKind:sourceBinding.scenarioKind},expectedActual:{reply:{expectedSha256:replyHash,actualSha256:replyHash,match:true},result:{expectedSha256:resultHash,actualSha256:resultHash,match:true},dml:{expectedSha256:dmlHash,actualSha256:dmlHash,match:true,expectedNormalizedStatements:[],actualNormalizedStatements:[],expectedRowCount:0,actualRowCount:0},lockOrder:{expected:[],actual:[],match:true},transaction:{expected:"READ_ONLY",actual:"READ_ONLY",match:true,expectedTimeline:["READ_ONLY"],actualTimeline:["READ_ONLY"]}},equivalenceRule:null,verdict:"PASS"};added.push({...payload,receiptSha256:sha256CanonicalJson(payload)});}finally{rmSync(dir,{recursive:true,force:true});}}
const receipts=[...prior.receipts,...added];if(added.length!==5||receipts.length!==207||new Set(receipts.map(receipt=>receipt.receiptId)).size!==207)throw new Error("Wave19 active receipt cardinality drift");writeFileSync(resolve(root,outputPath),JSON.stringify({format:prior.format,catalogVersion:prior.catalogVersion,classificationBaseCommit:prior.classificationBaseCommit,evidenceCommit,receipts},null,2)+"\n");console.log(JSON.stringify({status:"PASS",preservedWave18:202,addedWave19:5,total:207,evidenceCommit}));
