import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetBattleLeaderboardReadService } from "../src/mini-pet/mini-pet-battle-leaderboard-read-service.js";

const config=loadConfig();if(!config.database.enabled||config.database.name!=="hoibot_minipet_battle_leaderboard_g7")throw new Error(`Blocked database: ${config.database.name}`);
const database=createDatabaseClient(config.database),service=new MiniPetBattleLeaderboardReadService(database),base=process.env.MINIPET_LEADERBOARD_EVENT_ID??"minipet-leaderboard-fixed",restart=process.argv.includes("--verify-restart");
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-minipet-rank-room','minipet-rank-viewer','message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id]);}
async function read(id:string,message:string){return service.handle({externalUserId:"minipet-rank-viewer",channelId:"synthetic-minipet-rank-room",message,eventId:id});}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(sql,params)=>inner.query(sql,params),execute:(sql,params)=>inner.execute(sql,params),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(transaction:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(transaction=>work({query:(sql,params)=>transaction.query(sql,params),execute:async(sql,params)=>{if(sql.includes("INSERT INTO command_audit"))throw new Error("synthetic minipet leaderboard audit failure");return transaction.execute(sql,params);}}))};}
async function snapshot(){return(await database.query<Array<{operations:bigint;snapshots:bigint;entries:bigint;outboxes:bigint;audits:bigint;executions:bigint;wins:string}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'mini-pet.battle.leaderboard.read:%') operations,(SELECT COUNT(*) FROM mini_pet_battle_leaderboard_snapshots) snapshots,(SELECT COUNT(*) FROM mini_pet_battle_leaderboard_entries) entries,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope LIKE 'mini-pet.battle.leaderboard.read:%') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='mini_pet.battle.leaderboard.read') audits,(SELECT COUNT(*) FROM command_executions WHERE command_code='mini_pet_battle_leaderboard_read') executions,(SELECT CAST(win_count AS CHAR) FROM mini_pet_battle_states WHERE player_id=988800001) wins`))[0]!;}
try{
 if(restart){const before=await snapshot();assert.equal((await read(`${base}-wins`,"/미니펫대전순위")).replayed,true);assert.deepEqual(await snapshot(),before);process.stdout.write(`${JSON.stringify({mode:"verify-restart",operations:Number(before.operations),additionalSnapshot:false,operationalDataTouched:false})}\n`);}
 else{
  for(let index=1;index<=12;index+=1){const id=988800000+index,name=`합성회원${String(index).padStart(2,"0")}`;await database.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name,level,experience) VALUES (?,?,10,0)",[id,name]);await database.execute("INSERT INTO mini_pet_battle_states(player_id,win_count,loss_count,version) VALUES (?,?,?,1)",[id,70-index,index]);}
  await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (988800001,'kakao','minipet-rank-viewer','합성회원01','linked')");
  const registry=await database.query<Array<{command_code:string;rollout_state:string}>>("SELECT command_code,rollout_state FROM command_registry WHERE handler_key='mini_pet_battle_leaderboard_read' ORDER BY command_code");assert.equal(registry.length,2);assert.equal(registry.every(row=>row.rollout_state==="SHADOW"),true);
  await event(`${base}-wins`);const wins=await read(`${base}-wins`,"/미니펫대전순위");assert.match(wins.data,/11위\./);assert.equal(wins.data.includes("​".repeat(500)),true);assert.deepEqual(await read(`${base}-wins`,"/미니펫대전순위"),{...wins,replayed:true});
  await event(`${base}-rate`);const rate=await read(`${base}-rate`,"/미니펫대전승률");assert.match(rate.data,/승률 순위/);
  const expected={operations:2n,snapshots:2n,entries:24n,outboxes:2n,audits:2n,executions:2n,wins:"69"};assert.deepEqual(await snapshot(),expected);
  await event(`${base}-rollback`);await assert.rejects(()=>new MiniPetBattleLeaderboardReadService(failAudit(database)).handle({externalUserId:"minipet-rank-viewer",channelId:"synthetic-minipet-rank-room",message:"/미니펫대전순위",eventId:`${base}-rollback`}),/synthetic minipet leaderboard audit failure/);assert.deepEqual(await snapshot(),expected);assert.equal(await database.verifyRollback(),true);
  process.stdout.write(`${JSON.stringify({mode:"probe",migrationCount:266,scenarios:["two-exact","50-win","50-game","rounded-rate","Korean-tie","allsee","rollback","replay","restart-shadow"],effects:{operations:2,snapshots:2,entries:24,outboxes:2,audits:2,executions:2},operationalDataTouched:false})}\n`);
 }
}finally{await database.close();}
