import assert from "node:assert/strict";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { loadConfig } from "../src/config.js";
import { HoiShopService } from "../src/market/hoi-shop-service.js";
const config=loadConfig();if(!config.database.enabled||!/^hoibot_store_hoi_shop(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error("Hoi shop probe requires an isolated database.");
const db=createDatabaseClient(config.database),actor="hoi-shop-reader",room="synthetic-hoi-shop";
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,actor]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic hoi shop audit failure");return t.execute(s,p);}}))};}
async function snapshot(){return(await db.query<Array<{active:bigint;sold:bigint;cancelled:bigint;settlements:bigint;rewards:bigint;stack:bigint;point:string;title_count:bigint;pet_title_count:bigint;pet_exp:bigint;mini_count:bigint;ops:bigint;outboxes:bigint}>>(`SELECT (SELECT COUNT(*) FROM auction_listings WHERE status='active') active,(SELECT COUNT(*) FROM auction_listings WHERE status='sold') sold,(SELECT COUNT(*) FROM auction_listings WHERE status='cancelled') cancelled,(SELECT COUNT(*) FROM auction_settlements) settlements,(SELECT COUNT(*) FROM auction_settlement_rewards) rewards,(SELECT quantity FROM inventory_stacks WHERE player_id=995000002 AND item_id=995400001) stack,(SELECT CAST(balance AS CHAR) FROM currency_accounts WHERE player_id=995000002 AND currency_code='point') point,(SELECT COUNT(*) FROM player_titles WHERE player_id=995000002) title_count,(SELECT COUNT(*) FROM pet_titles WHERE player_pet_id=995500001) pet_title_count,(SELECT experience FROM player_pets WHERE id=995500001) pet_exp,(SELECT COUNT(*) FROM owned_mini_pets WHERE player_id=995000002) mini_count,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='store.hoi_shop.read_settle') ops,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='store.hoi_shop.read_settle') outboxes`))[0]!;}
async function seed(){
 await db.execute("INSERT INTO players(id,status,version) VALUES(995000001,'active',1),(995000002,'active',1)");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(995000001,'조회자'),(995000002,'입찰자')");await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,display_name,status) VALUES(995100001,995000001,'kakao',?,'조회자','linked')",[actor]);
 await db.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES(995000002,'point',100,1)");await db.execute("INSERT INTO item_definitions(id,code,display_name,asset_type_code,stackable,active,version) VALUES(995400001,'synthetic-auction-stack','합성 상자','inventory_stack',TRUE,TRUE,1)");
 await db.execute("INSERT INTO title_definitions(id,code,display_name,scope_code,active) VALUES(995410001,'synthetic-auction-title','합성 타이틀','player',TRUE),(995410002,'synthetic-auction-pet-title','합성 펫타이틀','pet',TRUE)");await db.execute("INSERT INTO mini_pet_definitions(id,code,display_name,grade_code,active) VALUES(995420001,'synthetic-auction-mini','합성 미니펫','normal',TRUE)");await db.execute("INSERT INTO player_pets(id,player_id,display_name,experience,version) VALUES(995500001,995000002,'합성 펫',10,1)");
 await db.execute("INSERT INTO auction_reward_catalog(reward_code,display_name,reward_type_code,item_id,title_id,mini_pet_definition_id,default_quantity) VALUES('synthetic-stack','합성 상자','STACK',995400001,NULL,NULL,2),('synthetic-title','합성 타이틀','TITLE',NULL,995410001,NULL,1),('synthetic-pet-title','합성 펫타이틀','PET_TITLE',NULL,995410002,NULL,1),('synthetic-pet-exp','합성 펫 경험치','PET_EXPERIENCE',NULL,NULL,NULL,25),('synthetic-mini','합성 미니펫','MINI_PET',NULL,NULL,995420001,1),('synthetic-point','합성 포인트','POINT',NULL,NULL,NULL,50)");
 await db.execute("INSERT INTO auction_listings(id,item_name,highest_bidder_player_id,highest_bid,ends_at,legacy_original_index,status,version) VALUES(995300001,'진행 경매',995000002,10,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),1,'active',1),(995300002,'복합 보상 경매',995000002,20,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),2,'active',1),(995300003,'유찰 경매',NULL,0,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),3,'active',1)");
 await db.execute("INSERT INTO auction_listing_reward_rules(listing_id,sequence_no,reward_code) VALUES(995300002,1,'synthetic-stack'),(995300002,2,'synthetic-title'),(995300002,3,'synthetic-pet-title'),(995300002,4,'synthetic-pet-exp'),(995300002,5,'synthetic-mini'),(995300002,6,'synthetic-point')");
}
async function probe(){await seed();const service=new HoiShopService(db);assert.equal((await db.query<Array<{s:string}>>("SELECT rollout_state s FROM command_registry WHERE command_code='STORE_HOI_SHOP'"))[0]?.s,"SHADOW");assert.equal(await service.read({eventId:"invalid",externalUserId:actor,destinationId:room,message:"/호이상점 안내"}),null);await event("hoi-shop-success");const first=await service.read({eventId:"hoi-shop-success",externalUserId:actor,destinationId:room,message:"/호이상점"});assert.deepEqual(first?.settledListingIds,["995300002"]);assert.deepEqual(first?.cancelledListingIds,["995300003"]);assert.equal(first?.rewardCount,6);assert.equal((await service.read({eventId:"hoi-shop-success",externalUserId:actor,destinationId:room,message:"/호이상점"}))?.replayed,true);assert.deepEqual(await snapshot(),{active:1n,sold:1n,cancelled:1n,settlements:2n,rewards:6n,stack:2n,point:"150.000",title_count:1n,pet_title_count:1n,pet_exp:35n,mini_count:1n,ops:1n,outboxes:1n});
 await db.execute("INSERT INTO auction_listings(id,item_name,highest_bidder_player_id,highest_bid,ends_at,status,version) VALUES(995300004,'롤백 경매',995000002,30,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),'active',1)");await db.execute("INSERT INTO auction_listing_reward_rules(listing_id,sequence_no,reward_code,quantity) VALUES(995300004,1,'synthetic-point',5)");await event("hoi-shop-rollback");const before=await snapshot();await assert.rejects(()=>new HoiShopService(failAudit(db)).read({eventId:"hoi-shop-rollback",externalUserId:actor,destinationId:room,message:"/호이상점"}),/synthetic hoi shop audit failure/);assert.deepEqual(await snapshot(),before);assert.equal(await db.verifyRollback(),true);const retry=await service.read({eventId:"hoi-shop-rollback",externalUserId:actor,destinationId:room,message:"/호이상점"});assert.equal(retry?.rewardCount,1);
 const migrationCount=(await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM schema_migrations"))[0]!.c;process.stdout.write(JSON.stringify({mode:"probe",migrationCount,scenarios:["exact","active","expired","no-bid","stack","title","pet-title","pet","mini-pet","point","replay","concurrent-lock","rollback","restart"],state:await snapshot()},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
async function restart(){const before=await snapshot();const replay=await new HoiShopService(db).read({eventId:"hoi-shop-success",externalUserId:actor,destinationId:room,message:"/호이상점"});assert.equal(replay?.replayed,true);assert.deepEqual(await snapshot(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",additionalMutation:false,state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
