import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { FreeMarketBuyService } from "../src/market/free-market-buy-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_free_market_buy(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic free-market-buy probe blocked: ${config.database.name}`);
let db=createDatabaseClient(config.database);const seller=996100001,buyer=996100002,sellerPet=996200001,buyerPet=996200002,room="synthetic-free-market-buy",sellerUser="free-market-buy-seller",buyerUser="free-market-buy-buyer";
async function event(id:string,user=buyerUser){await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
async function operation(key:string){return(await db.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at,completed_at) VALUES (UUID(),'synthetic.buy.registration',?,'system',NULL,'system','completed',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[key])).insertId;}
function failedAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("free market buy audit failure");return t.execute(s,p);}}))};}
async function listing(type:string,item:bigint|null,instance:bigint|null,quantity=1n,price=100n){return(await db.execute("INSERT INTO market_listings(seller_player_id,asset_type_code,item_id,inventory_instance_id,quantity,price_currency_code,price_amount,status,created_at,expires_at) VALUES (?,?,?,?,?,'point',?,'open',UTC_TIMESTAMP(3),DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 DAY))",[seller,type,item,instance,quantity,price.toString()])).insertId;}
async function buy(id:string,message:string,client:DatabaseClient=db){await event(id);return new FreeMarketBuyService(client).handle({eventId:id,externalUserId:buyerUser,destinationId:room,message});}
async function purchase(prefix:string){const pending=await buy(`${prefix}-start`,"/자유시장구매 1");assert.equal(pending?.status,"pending");const result=await buy(`${prefix}-confirm`,"자유시장거래");assert.equal(result?.status,"purchased");return result!;}
async function seed(){await db.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active')",[seller,buyer]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,tier_code) VALUES (?,'판매자','king'),(?,'구매자','king')",[seller,buyer]);await db.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (?,'👑',996100001),(?,'👑',996100002)",[seller,buyer]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?, 'kakao',?,'linked'),(?,?, 'kakao',?,'linked')",[seller,seller,sellerUser,buyer,buyer,buyerUser]);await db.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES (?,'point',0,1),(?,'point',1000000,1)",[seller,buyer]);await db.execute("INSERT INTO item_definitions(id,code,display_name,asset_type_code,stackable,metadata_json,active) VALUES (996400001,'SYNTHETIC-BUY-STACK','합성가방아이템','item',TRUE,JSON_OBJECT(),TRUE),(996400002,'SYNTHETIC-BUY-PENDANT','합성펜던트','item',FALSE,JSON_OBJECT('objectType','pendant'),TRUE)");await db.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (?,?, '판매펫'),(?,?, '구매펫')",[sellerPet,seller,buyerPet,buyer]);await db.execute("INSERT INTO skill_definitions(id,code,display_name,rules_json,active) VALUES (996500001,'SYNTHETIC-BUY-SKILL','합성스킬',JSON_OBJECT(),TRUE)");await db.execute("INSERT INTO furniture_definitions(id,code,display_name) VALUES (996600001,'SYNTHETIC-BUY-FURNITURE','합성가구')");await db.execute("INSERT INTO mini_pet_definitions(id,code,display_name,active) VALUES (996700001,'SYNTHETIC-BUY-MINI','합성미니펫',TRUE)");}
async function counts(){return(await db.query<Array<{sold:bigint;settlements:bigint;buy_events:bigint;ops:bigint;audits:bigint;outboxes:bigint;buyer_point:string;seller_point:string;foundation:string}>>(`SELECT (SELECT COUNT(*) FROM market_listings WHERE status='sold') sold,(SELECT COUNT(*) FROM market_settlements) settlements,(SELECT COUNT(*) FROM free_market_buy_events) buy_events,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='market.free_market.buy') ops,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_scope='market.free_market.buy') audits,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_scope='market.free_market.buy') outboxes,(SELECT CAST(balance AS CHAR) FROM currency_accounts WHERE player_id=996100002 AND currency_code='point') buyer_point,(SELECT CAST(balance AS CHAR) FROM currency_accounts WHERE player_id=996100001 AND currency_code='point') seller_point,(SELECT CAST(total_amount AS CHAR) FROM foundation_states WHERE foundation_code='happy') foundation`))[0]!;}
async function probe(){await seed();assert.equal((await db.query<Array<{state:string}>>("SELECT rollout_state state FROM command_registry WHERE command_code='MARKET_FREE_MARKET_BUY'"))[0]!.state,"SHADOW");
const stack=await listing("stack",996400001n,null,3n);await purchase("stack");assert.equal((await db.query<Array<{q:bigint}>>("SELECT quantity q FROM inventory_stacks WHERE player_id=? AND item_id=996400001",[buyer]))[0]!.q,3n);
await db.execute("INSERT INTO inventory_instances(id,player_id,item_id,status,attributes_json,version) VALUES (996800001,?,996400002,'reserved',JSON_OBJECT('objectType','pendant'),2)",[seller]);await listing("instance",996400002n,996800001n);await purchase("pendant");assert.equal((await db.query<Array<{p:bigint;s:string}>>("SELECT player_id p,status s FROM inventory_instances WHERE id=996800001"))[0]!.p,BigInt(buyer));
const skillListing=await listing("pet_skill",null,null,4n),skillOp=await operation("skill");await db.execute("INSERT INTO market_skill_registration_ledger(operation_id,listing_id,player_id,player_pet_id,skill_id,source_index,quantity,price_amount,carrot_item_id,carrot_fee,skill_quantity_before,skill_quantity_after,source_version_before,source_version_after,carrot_version_before,carrot_version_after) VALUES (?,?,?,?,996500001,1,4,100,996400001,0,4,0,1,2,1,2)",[skillOp,skillListing,seller,sellerPet]);await purchase("skill");assert.equal((await db.query<Array<{q:bigint}>>("SELECT quantity q FROM pet_skill_inventory WHERE player_pet_id=? AND skill_id=996500001",[buyerPet]))[0]!.q,4n);
await db.execute("INSERT INTO furniture_inventory_instances(id,player_id,furniture_definition_id,charm_snapshot,grade_display_name,status,version) VALUES (996610001,?,996600001,10,'합성','listed',2)",[seller]);const furnitureListing=await listing("furniture",null,null),furnitureOp=await operation("furniture");await db.execute("INSERT INTO market_furniture_registration_ledger(operation_id,listing_id,player_id,furniture_definition_id,source_index,quantity,price_amount,carrot_item_id,carrot_fee,carrot_version_before,carrot_version_after) VALUES (?,?,?,?,1,1,100,996400001,0,1,2)",[furnitureOp,furnitureListing,seller,996600001]);await db.execute("INSERT INTO market_furniture_registration_items(operation_id,sequence_no,furniture_instance_id,source_version_before,source_version_after) VALUES (?,1,996610001,1,2)",[furnitureOp]);await purchase("furniture");assert.equal((await db.query<Array<{p:bigint}>>("SELECT player_id p FROM furniture_inventory_instances WHERE id=996610001"))[0]!.p,BigInt(buyer));
await db.execute("INSERT INTO owned_mini_pets(id,player_id,mini_pet_definition_id,custom_name,equipped,bag_sequence,version) VALUES (996710001,?,996700001,'합성미니',FALSE,1,1)",[seller]);const miniListing=await listing("mini_pet",null,null);await db.execute("INSERT INTO market_mini_pet_reservations(listing_id,owned_mini_pet_id,player_id) VALUES (?,996710001,?)",[miniListing,seller]);await purchase("mini");assert.equal((await db.query<Array<{p:bigint}>>("SELECT player_id p FROM owned_mini_pets WHERE id=996710001"))[0]!.p,BigInt(buyer));
const concurrentListing=await listing("stack",996400001n,null,1n);assert.equal((await buy("concurrent-start","/자유시장구매 1"))?.status,"pending");await Promise.allSettled([buy("concurrent-confirm","자유시장거래"),buy("concurrent-confirm","자유시장거래")]);assert.equal((await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM market_settlements WHERE listing_id=?",[concurrentListing]))[0]!.c,1n);
const rollbackListing=await listing("stack",996400001n,null,2n);assert.equal((await buy("rollback-start","/자유시장구매 1"))?.status,"pending");const before=await counts();await assert.rejects(()=>buy("rollback-confirm","자유시장거래",failedAudit(db)),/free market buy audit failure/);assert.deepEqual(await counts(),before);assert.equal(await db.verifyRollback(),true);assert.equal((await buy("rollback-after","자유시장거래"))?.status,"purchased");const state=await counts();assert.equal(state.sold,7n);assert.equal(state.settlements,7n);assert.equal(state.buy_events,7n);assert.equal((await new FreeMarketBuyService(db).handle({eventId:"stack-confirm",externalUserId:buyerUser,destinationId:room,message:"자유시장거래"}))?.replayed,true);const migrationCount=(await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM schema_migrations"))[0]?.c;process.stdout.write(JSON.stringify({mode:"probe",migrationCount,scenarios:["shadow","stack","pendant","pet-skill","furniture","mini-pet","tier","balance","capacity","confirmation","concurrent","rollback","restart"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
async function restart(){const state=await counts();assert.equal(state.sold,7n);assert.equal(state.settlements,7n);assert.equal(state.buy_events,7n);const stable=(value:unknown)=>JSON.stringify(value,(_key,item)=>typeof item==="bigint"?item.toString():item);const before=stable(state);const replay=await new FreeMarketBuyService(db).handle({eventId:"stack-confirm",externalUserId:buyerUser,destinationId:room,message:"자유시장거래"});assert.equal(replay?.replayed,true);assert.equal(stable(await counts()),before);process.stdout.write(stable({mode:"verify-restart",state,additionalMutation:false,operationalDataTouched:false})+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
