import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetUpgradeService,isMiniPetUpgradeCommand,parseMiniPetUpgradeCommand } from "../src/mini-pet/mini-pet-upgrade-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_mini_pet_upgrade_/i.test(config.database.name))throw new Error(`Synthetic probe blocked for ${config.database.name}`);
const database=createDatabaseClient(config.database),restart=process.argv.includes("--restart"),player=998000012,identity=998200012,external="synthetic-mini-pet-upgrade",room="synthetic-mini-pet-room",successEvent="mini-pet-upgrade-success";
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('e',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,external]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic mini pet upgrade audit failure");return t.execute(s,p);}}))};}
async function state(){const row=(await database.query<Array<{point:string;stone:string|bigint;boost:string|bigint;level:bigint;battle:bigint;castle:bigint;raid:bigint;attempts:bigint;operations_count:bigint;audits:bigint;outboxes:bigint}>>(`SELECT CAST(account.balance AS CHAR) point,COALESCE((SELECT stack.quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='mini_pet_enhance_stone'),0) stone,COALESCE((SELECT stack.quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='ITEM-RWD-019'),0) boost,pet.enhancement_level level,pet.battle_experience battle,pet.castle_experience castle,pet.raid_experience raid,(SELECT COUNT(*) FROM mini_pet_upgrade_attempts WHERE player_id=?) attempts,(SELECT COUNT(*) FROM operations WHERE idempotency_scope=?) operations_count,(SELECT COUNT(*) FROM command_audit WHERE action_code='mini_pet.upgrade') audits,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope=?) outboxes FROM currency_accounts account JOIN owned_mini_pets pet ON pet.player_id=account.player_id AND pet.equipped=TRUE WHERE account.player_id=? AND account.currency_code='point'`,[player,player,player,`mini-pet.upgrade:${identity}`,`mini-pet.upgrade:${identity}`,player]))[0]!;return{...row,stone:BigInt(row.stone),boost:BigInt(row.boost)};}
async function seed(){await database.execute("INSERT INTO players(id,status,version) VALUES(?,'active',1)",[player]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(?,'합성회원')",[player]);await database.execute("INSERT INTO external_identities(id,provider_code,external_user_id,player_id,status) VALUES(?,'kakao',?,?,'linked')",[identity,external,player]);await database.execute("INSERT INTO player_pets(player_id,display_name,pet_type_code) VALUES(?,'합성펫','synthetic')",[player]);await database.execute("INSERT INTO pet_skills(player_pet_id,slot_no,skill_id,level,equipped) SELECT pet.id,1,skill.id,1,TRUE FROM player_pets pet JOIN skill_definitions skill ON skill.code='SKILL-MINI-PET-DOG-MASTER' WHERE pet.player_id=?",[player]);await database.execute("INSERT INTO mini_pet_definitions(code,display_name,grade_code,grade_display_name,emoji_value,active) VALUES('synthetic-mini-upgrade','합성미니','normal','일반','🐹',TRUE)");await database.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,equipped,bag_sequence,enhancement_level,battle_experience,castle_experience,raid_experience,version) SELECT ?,id,TRUE,NULL,0,100,200,300,1 FROM mini_pet_definitions WHERE code='synthetic-mini-upgrade'",[player]);await database.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES(?,'point',100000000,1)",[player]);await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,10,1 FROM item_definitions WHERE code='mini_pet_enhance_stone'",[player]);await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,2,1 FROM item_definitions WHERE code='ITEM-RWD-019'",[player]);}
async function run(){const service=(random:()=>number=()=>0.5)=>new MiniPetUpgradeService(database,random);if(restart){const before=await state(),result=await service().handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫강화"});assert.equal(result.replayed,true);assert.deepEqual(await state(),before);process.stdout.write(JSON.stringify({mode:"restart",additionalMutation:false,state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");return;}
  await seed();assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MINI_PET_UPGRADE'"))[0]?.rollout_state,"SHADOW");assert.equal(isMiniPetUpgradeCommand("/미니펫강화 0 101"),true);assert.equal(parseMiniPetUpgradeCommand("/미니펫강화 0 101")?.count,100);await database.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='MINI_PET_UPGRADE'");
  await event(successEvent);const pair=await Promise.all([service().handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫강화"}),service().handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫강화"})]);assert.equal(pair.every(result=>result.status==="applied"),true);assert.equal(pair.filter(result=>result.replayed===true).length,1);let current=await state();assert.deepEqual(current,{point:"90000000.000",stone:9n,boost:1n,level:1n,battle:10100n,castle:10200n,raid:10300n,attempts:1n,operations_count:1n,audits:1n,outboxes:1n});
  await database.execute("UPDATE pet_skills SET equipped=FALSE WHERE player_pet_id=(SELECT id FROM player_pets WHERE player_id=?)",[player]);await database.execute("UPDATE inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id SET stack.quantity=0,stack.version=stack.version+1 WHERE stack.player_id=? AND item.code='ITEM-RWD-019'",[player]);const failEvent="mini-pet-upgrade-failure";await event(failEvent);const failed=await service(()=>0.999999).handle({eventId:failEvent,externalUserId:external,destinationId:room,message:"/미니펫강화"});assert.equal(failed.failed,1);current=await state();assert.deepEqual({point:current.point,stone:current.stone,level:current.level,battle:current.battle,attempts:current.attempts},{point:"80000000.000",stone:7n,level:1n,battle:10100n,attempts:2n});
  await database.execute("UPDATE currency_accounts SET balance=15000000,version=version+1 WHERE player_id=? AND currency_code='point'",[player]);const partialEvent="mini-pet-upgrade-partial";await event(partialEvent);const partial=await service(()=>0).handle({eventId:partialEvent,externalUserId:external,destinationId:room,message:"/미니펫강화 0 2"});assert.deepEqual({attempted:partial.attempted,stop:partial.stopReason,level:partial.level},{attempted:1,stop:"insufficient_point",level:"2"});
  await database.execute("UPDATE currency_accounts SET balance=50000000,version=version+1 WHERE player_id=? AND currency_code='point'",[player]);const rollbackEvent="mini-pet-upgrade-rollback";await event(rollbackEvent);const before=await state();await assert.rejects(()=>new MiniPetUpgradeService(failAudit(database),()=>0).handle({eventId:rollbackEvent,externalUserId:external,destinationId:room,message:"/미니펫강화"}),/synthetic mini pet upgrade audit failure/);assert.deepEqual(await state(),before);assert.equal(await database.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",scenarios:["shadow-registry","exact-boundary","equipped-stable-id","skill-highest-boost","success-three-charms","failure-resource-consumption","partial-batch","concurrent-replay","rollback","restart-replay"],state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{await run();}finally{await database.close();}
