import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { SocialOwnHeartService } from "../src/social/social-own-heart-service.js";

const config=loadConfig();if(!config.database.enabled||!/^hoibot_social_own_heart(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic social own heart probe blocked: ${config.database.name}`);
let database=createDatabaseClient(config.database);const service=()=>new SocialOwnHeartService(database),base=process.env.SOCIAL_OWN_HEART_PROBE_EVENT_ID??"social-own-heart-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),room="synthetic-social-own-heart-room",successEvent=`${base}-success`;
async function event(suffix:string,user:string){const id=`${base}-${suffix}`;await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('9',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,user]);return id;}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic social own heart audit failure");return t.execute(s,p);}}))};}
async function state(){return(await database.query<Array<{used_value:string|null;usage_rows:bigint;read_count:bigint;operation_count:bigint;outbox_count:bigint;audit_count:bigint;execution_count:bigint;follow_hash:string|null}>>(`SELECT (SELECT CAST(used_count AS CHAR) FROM player_pet_home_heart_usage WHERE player_id=209001 ORDER BY usage_date DESC LIMIT 1) used_value,(SELECT COUNT(*) FROM player_pet_home_heart_usage) usage_rows,(SELECT COUNT(*) FROM social_own_heart_reads) read_count,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='social.own_heart') operation_count,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='social.own_heart') outbox_count,(SELECT COUNT(*) FROM command_audit WHERE action_code='social.own_heart.read') audit_count,(SELECT COUNT(*) FROM command_executions WHERE command_code='SOCIAL_OWN_HEART') execution_count,(SELECT GROUP_CONCAT(CONCAT(follower_player_id,':',followed_player_id,':',active,':',version) ORDER BY follower_player_id,followed_player_id SEPARATOR '|') FROM pet_home_follows) follow_hash`))[0]!;}
try{if(restart){const before=await state(),replay=await service().handle({eventId:successEvent,externalUserId:"own-heart-user",destinationId:room,message:"/내마음"});assert.equal(replay.status,"shown");assert.deepEqual(await state(),before);process.stdout.write(JSON.stringify({mode:"restart",scenarios:["restart-replay"],state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}else{
await database.execute("INSERT INTO players(id,status) VALUES (209001,'active'),(209002,'active'),(209003,'active'),(209004,'active')");
await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (209001,'마음 사용자'),(209002,'활성 맞팔'),(209003,'패스 없는 맞팔'),(209004,'패스 없는 사용자')");
await database.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (209001,'🌱',1)");
await database.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (209001,209001,'kakao','own-heart-user','linked'),(209004,209004,'kakao','own-heart-no-pass','linked')");
await database.execute("INSERT INTO player_homes(player_id,last_heart_expression_date) VALUES (209001,DATE(DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 9 HOUR)))");
await database.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES (209001,'hoi',TRUE,TRUE),(209001,'premium',TRUE,TRUE),(209002,'newbie',TRUE,TRUE)");
await database.execute("INSERT INTO pet_home_follows(follower_player_id,followed_player_id,active) VALUES (209001,209002,TRUE),(209002,209001,TRUE),(209001,209003,TRUE),(209003,209001,TRUE)");
const pet=await database.execute("INSERT INTO player_pets(player_id,display_name) VALUES (209001,'마음 펫')"),skill=await database.execute("INSERT INTO skill_definitions(code,display_name,rules_json,active) VALUES ('synthetic-heart-bonus','망므',JSON_OBJECT('heartBonus',5),TRUE)");await database.execute("INSERT INTO pet_skills(player_pet_id,slot_no,skill_id,level,equipped) VALUES (?,1,?,1,TRUE)",[pet.insertId,skill.insertId]);
assert.deepEqual((await database.query<Array<{rollout_state:string;alias_count:bigint}>>("SELECT registry.rollout_state,(SELECT COUNT(*) FROM command_aliases alias WHERE alias.command_code=registry.command_code AND alias.command_text='/내마음' AND alias.active=TRUE) alias_count FROM command_registry registry WHERE registry.command_code='SOCIAL_OWN_HEART'"))[0],{rollout_state:"SHADOW",alias_count:1n});
const deniedEvent=await event("no-pass","own-heart-no-pass"),denied=await service().handle({eventId:deniedEvent,externalUserId:"own-heart-no-pass",destinationId:room,message:"/내마음"});assert.equal(denied.status,"pass_required");assert.match(denied.reply,/호이패스·초보패스 이용자만/);
await event("success","own-heart-user");const result=await service().handle({eventId:successEvent,externalUserId:"own-heart-user",destinationId:room,message:"/내마음"});assert.deepEqual({status:result.status,base:result.base,mutualBonus:result.mutualBonus,premiumBonus:result.premiumBonus,skillBonus:result.skillBonus,used:result.used,remaining:result.remaining,limit:result.limit},{status:"shown",base:"1",mutualBonus:"1",premiumBonus:"15",skillBonus:"5",used:"1",remaining:"21",limit:"22"});assert.match(result.reply,/\[👑호이패스 프리미엄👑\]/);assert.match(result.reply,/\[🌱마음 사용자\] 님/);assert.deepEqual(await service().handle({eventId:successEvent,externalUserId:"own-heart-user",destinationId:room,message:"/내마음"}),result);
const rollbackEvent=await event("rollback","own-heart-user"),rollbackBefore=await state();await assert.rejects(()=>new SocialOwnHeartService(failAudit(database)).handle({eventId:rollbackEvent,externalUserId:"own-heart-user",destinationId:room,message:"/내마음"}),/synthetic social own heart audit failure/);assert.deepEqual(await state(),rollbackBefore);assert.equal(await database.verifyRollback(),true);
await database.close();database=createDatabaseClient(config.database);assert.deepEqual(await service().handle({eventId:successEvent,externalUserId:"own-heart-user",destinationId:room,message:"/내마음"}),result);const finalState=await state();assert.deepEqual({used_value:finalState.used_value,usage_rows:finalState.usage_rows,read_count:finalState.read_count,operation_count:finalState.operation_count},{used_value:"1",usage_rows:1n,read_count:2n,operation_count:2n});const signature=createHash("sha256").update(String(finalState.follow_hash)).digest("hex");process.stdout.write(JSON.stringify({mode:"probe",migrationCount:209,scenarios:["shadow-registry","exact-boundary","pass-required","legacy-date-fallback","active-mutual-only","premium-bonus","equipped-skill-bonus","idempotent-replay","audit-rollback","restart-replay"],state:finalState,relationshipSignature:signature,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}}finally{await database.close();}
