import assert from "node:assert/strict";
import { createDatabaseClient } from "../src/database.js";
import { GuildMarkMutateService } from "../src/guild/guild-mark-mutate-service.js";

const required=(name:string):string=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;};
const databaseName=required("DATABASE_NAME");
if(!/^hoibot_guild_mark_mutate_g7(?:_[a-z0-9_]+)?$/i.test(databaseName))throw new Error("isolated guild-mark-mutate database is required");
const db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:process.env.DATABASE_PASSWORD??"",name:databaseName,connectionLimit:8,connectTimeoutMs:5_000});
const verify=process.argv.includes("--verify-restart"),room="990000000000357",ticketCode="ITEM-GUILD-MARK-CHANGE-TICKET",normalEvent="guild-mark-mutate-normal";
const service=new GuildMarkMutateService(db);

async function event(eventId:string,externalUserId:string):Promise<void>{await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,room,externalUserId]);}
async function fixture(index:number,name:string,role="master",tickets=1):Promise<{guildId:bigint;playerId:bigint;externalId:string}>{
  const guildId=357000n+BigInt(index),playerId=358000n+BigInt(index),externalId=`guild-mark-user-${index}`;
  await db.execute("INSERT INTO guilds(id,code,display_name,status,mark,version) VALUES (?,?,?,'active','OLD',1)",[guildId,`GUILD-MARK-${index}`,name]);
  await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1)",[playerId]);
  await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[playerId,`합성회원${index}`]);
  await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[playerId,externalId,`합성회원${index}`]);
  await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES (?,?,?,UTC_TIMESTAMP(3))",[guildId,playerId,role]);
  if(tickets>0)await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,?,1 FROM item_definitions WHERE code=?",[playerId,tickets,ticketCode]);
  return {guildId,playerId,externalId};
}
async function identityFixture(index:number):Promise<string>{const playerId=359000n+BigInt(index),externalId=`guild-mark-no-guild-${index}`;await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1)",[playerId]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1)",[playerId,`미가입회원${index}`]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[playerId,externalId,`미가입회원${index}`]);return externalId;}
async function grantAdmin(externalId:string,index:number):Promise<void>{const identity=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[externalId]))[0]!.id;const operator=await db.execute("INSERT INTO admin_operators(login_id,display_name,password_hash,status) VALUES (?,?,REPEAT('a',60),'active')",[`guild-mark-admin-${index}`,`합성 관리자${index}`]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operator.insertId,identity]);await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='super_admin'",[operator.insertId]);}
async function state():Promise<Record<string,string>>{const one=async(sql:string,params:unknown[]=[])=>(await db.query<Array<{count_value:bigint}>>(sql,params))[0]!.count_value.toString();return{runs:await one("SELECT COUNT(*) count_value FROM guild_mark_mutation_runs"),ledgers:await one("SELECT COUNT(*) count_value FROM inventory_ledger WHERE reason_code='GUILD_MARK_CHANGE_TICKET_CONSUME'"),operations:await one("SELECT COUNT(*) count_value FROM operations WHERE idempotency_scope LIKE 'guild.mark.mutate:%'"),executions:await one("SELECT COUNT(*) count_value FROM command_executions WHERE command_code='GUILD_MARK_MUTATE'"),audits:await one("SELECT COUNT(*) count_value FROM command_audit WHERE action_code='guild.mark.change'"),outboxes:await one("SELECT COUNT(*) count_value FROM outbox_messages WHERE operation_id IN (SELECT operation_id FROM guild_mark_mutation_runs)"),tickets:await one("SELECT COALESCE(SUM(stack.quantity),0) count_value FROM inventory_stacks stack JOIN item_definitions definition ON definition.id=stack.item_id WHERE definition.code=?",[ticketCode])};}

try{
  if(!verify){
    const normal=await fixture(1,"마크길드일",undefined,2),admin=await fixture(2,"마크길드이","member",1),noTicket=await fixture(3,"마크길드삼",undefined,0),member=await fixture(4,"마크길드사","member",1),concurrent=await fixture(5,"마크길드오",undefined,2),rollback=await fixture(6,"마크길드육",undefined,1),noGuild=await identityFixture(7);await grantAdmin(admin.externalId,2);
    await event("guild-mark-mutate-shadow",normal.externalId);assert.deepEqual(await service.handleIris({eventId:"guild-mark-mutate-shadow",externalUserId:normal.externalId,channelId:room,message:"/길드마크변경 🌑"}),{status:"shadow"});
    await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_MARK_MUTATE'");
    await event(normalEvent,normal.externalId);const result=await service.change({eventId:normalEvent,externalUserId:normal.externalId,channelId:room,message:"/길드마크변경 🌟"});const replay=await service.change({eventId:normalEvent,externalUserId:normal.externalId,channelId:room,message:"/길드마크변경 🌟"});assert.equal(replay.outboxId,result.outboxId);
    await event("guild-mark-mutate-admin",admin.externalId);await service.change({eventId:"guild-mark-mutate-admin",externalUserId:admin.externalId,channelId:room,message:"/길드마크변경 👑"});
    await event("guild-mark-mutate-no-ticket",noTicket.externalId);await assert.rejects(()=>service.change({eventId:"guild-mark-mutate-no-ticket",externalUserId:noTicket.externalId,channelId:room,message:"/길드마크변경 🧾"}),/변경권/);
    await event("guild-mark-mutate-no-guild",noGuild);await assert.rejects(()=>service.change({eventId:"guild-mark-mutate-no-guild",externalUserId:noGuild,channelId:room,message:"/길드마크변경 🚫"}),/길드 정보를/);
    await event("guild-mark-mutate-member",member.externalId);await assert.rejects(()=>service.change({eventId:"guild-mark-mutate-member",externalUserId:member.externalId,channelId:room,message:"/길드마크변경 🙅"}),/길드장 또는 관리자/);
    await event("guild-mark-mutate-concurrent",concurrent.externalId);const concurrentResults=await Promise.all([service.change({eventId:"guild-mark-mutate-concurrent",externalUserId:concurrent.externalId,channelId:room,message:"/길드마크변경 ⚔️"}),service.change({eventId:"guild-mark-mutate-concurrent",externalUserId:concurrent.externalId,channelId:room,message:"/길드마크변경 ⚔️"})]);assert.equal(concurrentResults[0].outboxId,concurrentResults[1].outboxId);
    await event("guild-mark-mutate-rollback",rollback.externalId);await db.execute("CREATE TRIGGER fail_guild_mark_mutate_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='guild.mark.change' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced guild mark audit failure'; END IF; END");try{await assert.rejects(()=>service.change({eventId:"guild-mark-mutate-rollback",externalUserId:rollback.externalId,channelId:room,message:"/길드마크변경 🔁"}),/forced guild mark audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_guild_mark_mutate_audit");}assert.equal((await db.query<Array<{mark:string}>>("SELECT mark FROM guilds WHERE id=?",[rollback.guildId]))[0]!.mark,"OLD");await service.change({eventId:"guild-mark-mutate-rollback",externalUserId:rollback.externalId,channelId:room,message:"/길드마크변경 🔁"});
    const snapshot=await state();assert.deepEqual(snapshot,{runs:"4",ledgers:"4",operations:"4",executions:"4",audits:"4",outboxes:"4",tickets:"3"});console.log(JSON.stringify({mode:"probe",migrationCount:357,scenarios:["shadow","broad-boundary","leader","admin-override","no-guild","ticket-required","member-denied","atomic-mark-ticket-ledger","same-event-concurrency","rollback","retry","restart"],effects:snapshot,operationalDataTouched:false}));
  }else{const before=await state();await service.change({eventId:normalEvent,externalUserId:"guild-mark-user-1",channelId:room,message:"/길드마크변경 🌟"});assert.deepEqual(await state(),before);console.log(JSON.stringify({mode:"verify-restart",effects:before,additionalMutation:false,operationalDataTouched:false}));}
}finally{await db.close();}
