import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { PendantMarketInfoService } from "../src/market/pendant-market-info-service.js";
const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_pendant_market_info(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic pendant info probe blocked: ${config.database.name}`);
const db=createDatabaseClient(config.database),user="pendant-info-user",room="synthetic-pendant-info-room",base="pendant-market-info-g7-20260827-r1";
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic pendant info audit failure");return t.execute(s,p);}}))};}
async function counts(){return db.query<Array<{listings:bigint;reserved:bigint;operations:bigint;outboxes:bigint}>>(`SELECT (SELECT COUNT(*) FROM market_listings) listings,(SELECT COUNT(*) FROM inventory_instances WHERE status='reserved') reserved,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='market.pendant.info') operations,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='market.pendant.info') outboxes`);}
try{
 await db.execute("INSERT INTO players(id,status) VALUES(991000001,'active')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(991000001,'조회 남')");await db.execute("INSERT INTO external_identities(id,provider_code,external_user_id,player_id,status) VALUES(991200001,'kakao',?,991000001,'linked')",[user]);
 await db.execute("INSERT INTO item_definitions(id,code,display_name,asset_type_code,stackable,metadata_json,active,version) VALUES(991400001,'PENDANT-INFO-SYNTHETIC','합성정보펜던트','ITEM',0,JSON_OBJECT('objectType','pendant'),1,1),(991400002,'STACK-INFO-SYNTHETIC','합성일반아이템','ITEM',1,NULL,1,1)");
 await db.execute("INSERT INTO inventory_instances(id,player_id,item_id,status,attributes_json,version) VALUES(991100001,991000001,991400001,'reserved',JSON_OBJECT('objectType','pendant','name','합성정보펜던트','icon','💎','grade','하급','durability',4,'maxDurability',5,'upgrade',3),1)");
 await db.execute("INSERT INTO market_listings(id,seller_player_id,asset_type_code,item_id,inventory_instance_id,quantity,price_currency_code,price_amount,status,created_at,expires_at) VALUES(991500001,991000001,'instance',991400001,991100001,1,'point',5000000,'open',DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 MINUTE),DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 DAY)),(991500002,991000001,'stack',991400002,NULL,1,'point',1000,'open',DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 MINUTE),DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 DAY))");
 assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='PENDANT_MARKET_INFO'"))[0]!.rollout_state,"SHADOW");const service=new PendantMarketInfoService(db);
 for(const [suffix,message,status] of [["usage","/펜던트거래정보","usage"],["invalid","/펜던트거래정보 안내","invalid"],["stack","/펜던트거래정보 1","not_pendant"],["pendant","/펜던트거래정보 2","found"],["missing","/펜던트거래정보 3","not_found"]] as const){const id=`${base}-${suffix}`;await event(id);const result=await service.handle({eventId:id,externalUserId:user,destinationId:room,message});assert.equal(result.status,status);if(status==="found")assert.match(result.data!,/총 종합매력👑: 530,000💞/);}
 const replayId=`${base}-pendant`;const beforeReplay=await counts();await service.handle({eventId:replayId,externalUserId:user,destinationId:room,message:"/펜던트거래정보 2"});assert.deepEqual(await counts(),beforeReplay);
 const rollbackId=`${base}-rollback`;await event(rollbackId);const beforeRollback=await counts();await assert.rejects(()=>new PendantMarketInfoService(failAudit(db)).handle({eventId:rollbackId,externalUserId:user,destinationId:room,message:"/펜던트거래정보 2"}),/synthetic pendant info audit failure/);assert.deepEqual(await counts(),beforeRollback);assert.equal(await db.verifyRollback(),true);
 process.stdout.write(JSON.stringify({mode:"probe",migrationCount:122,scenarios:["usage","invalid","global-display-order","non-pendant","pendant-detail","not-found","replay","rollback"],operationalDataTouched:false})+"\n");
}finally{await db.close();}
