import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { MiniPetBattleResetTicketCraftService } from "../src/mini-pet/mini-pet-battle-reset-ticket-craft-service.js";
import { ApplicationError } from "../src/shared/application-error.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_mini_pet_battle_reset_ticket_craft_/i.test(config.database.name))throw new Error(`Synthetic probe blocked for ${config.database.name}`);
const database=createDatabaseClient(config.database),restart=process.argv.includes("--restart");
const player=998000001,identity=998200001,externalUserId="synthetic-mini-pet-reset-craft",room="synthetic-mini-pet-room",successEvent="mini-pet-reset-craft-success";
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('c',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,externalUserId]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic craft audit failure");return t.execute(s,p);}}))};}
async function state(){return(await database.query<Array<{material:bigint;ticket:bigint;events_count:bigint;ledger_count:bigint;operations_count:bigint;audits_count:bigint;outboxes_count:bigint}>>(`SELECT MAX(CASE WHEN item.code='legacy-seasoned-chicken' THEN stack.quantity END) material,MAX(CASE WHEN item.code='legacy-mini-pet-record-reset-ticket' THEN stack.quantity END) ticket,(SELECT COUNT(*) FROM mini_pet_battle_reset_ticket_craft_events) events_count,(SELECT COUNT(*) FROM inventory_ledger ledger JOIN operations operation_row ON operation_row.id=ledger.operation_id WHERE operation_row.idempotency_scope LIKE 'mini_pet.battle-reset-ticket.craft:%') ledger_count,(SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'mini_pet.battle-reset-ticket.craft:%') operations_count,(SELECT COUNT(*) FROM command_audit WHERE action_code='mini_pet.battle_reset_ticket.craft') audits_count,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope LIKE 'mini_pet.battle-reset-ticket.craft:%') outboxes_count FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code IN ('legacy-seasoned-chicken','legacy-mini-pet-record-reset-ticket')`,[player]))[0]!;}
async function seed(){await database.execute("INSERT INTO players(id,status,version) VALUES(?,'active',1)",[player]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(?,'합성회원')",[player]);await database.execute("INSERT INTO external_identities(id,provider_code,external_user_id,player_id,status) VALUES(?,'kakao',?,?,'linked')",[identity,externalUserId,player]);await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,CASE code WHEN 'legacy-seasoned-chicken' THEN 99 ELSE 0 END,1 FROM item_definitions WHERE code IN ('legacy-seasoned-chicken','legacy-mini-pet-record-reset-ticket')",[player]);}
async function run(){const service=()=>new MiniPetBattleResetTicketCraftService(database);if(restart){const before=await state(),result=await service().handle({externalUserId,channelId:room,message:"/미니펫전적조합",eventId:successEvent});assert.equal(result.status,"crafted");assert.deepEqual(await state(),before);process.stdout.write(JSON.stringify({mode:"restart",additionalMutation:false,state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");return;}await seed();assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MINI_PET_BATTLE_RESET_TICKET_CRAFT'"))[0]?.rollout_state,"SHADOW");const shortage="mini-pet-reset-craft-shortage";await event(shortage);await assert.rejects(()=>service().handle({externalUserId,channelId:room,message:"/미니펫전적조합",eventId:shortage}),(error:unknown)=>error instanceof ApplicationError&&error.code==="SEASONED_CHICKEN_REQUIRED");await database.execute("UPDATE inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id SET stack.quantity=100,stack.version=stack.version+1 WHERE stack.player_id=? AND item.code='legacy-seasoned-chicken'",[player]);await event(successEvent);const pair=await Promise.all([service().handle({externalUserId,channelId:room,message:"/미니펫전적조합",eventId:successEvent}),service().handle({externalUserId,channelId:room,message:"/미니펫전적조합",eventId:successEvent})]);assert.deepEqual(pair[0],pair[1]);let current=await state();assert.deepEqual(current,{material:0n,ticket:1n,events_count:1n,ledger_count:2n,operations_count:1n,audits_count:1n,outboxes_count:1n});await database.execute("UPDATE inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id SET stack.quantity=100,stack.version=stack.version+1 WHERE stack.player_id=? AND item.code='legacy-seasoned-chicken'",[player]);const rollback="mini-pet-reset-craft-rollback";await event(rollback);const before=await state();await assert.rejects(()=>new MiniPetBattleResetTicketCraftService(failAudit(database)).handle({externalUserId,channelId:room,message:"/미니펫전적조합",eventId:rollback}),/synthetic craft audit failure/);assert.deepEqual(await state(),before);assert.equal(await database.verifyRollback(),true);current=await state();process.stdout.write(JSON.stringify({mode:"probe",scenarios:["shadow-registry","exact-boundary","open-member","shortage","atomic-ledger","craft-event","concurrent-replay","rollback","restart-replay"],state:current},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{await run();}finally{await database.close();}
