import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { GuildTerritoryWarProvider } from "../src/guild/guild-territory-war-provider.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");
if(!/^hoibot_guild_territory_war(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic guild territory probe blocked: ${config.database.name}`);
const restart=process.argv.includes("--verify-restart"),base=process.env.GUILD_TERRITORY_PROBE_EVENT_ID??"guild-territory-provider-g7-20260827-r1",db=createDatabaseClient(config.database),provider=new GuildTerritoryWarProvider(db,{random:()=>0.75,now:()=>new Date("2026-08-26T13:00:00.000Z")});
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-guild-territory-room','provider-user','message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic guild territory audit failure");return t.execute(s,p);}}))};}
async function snap(){return db.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;events:bigint;rng:bigint;owned:bigint;eliminated:bigint;count:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'guild.territory.force_rift:%') operations,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope LIKE 'guild.territory.force_rift:%') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='guild.territory.force_rift') audits,(SELECT COUNT(*) FROM guild_territory_rift_events) events,(SELECT COUNT(*) FROM rng_events WHERE event_code='guild_territory_great_rift') rng,(SELECT COUNT(*) FROM guild_territory_occupations WHERE owner_guild_id IS NOT NULL) owned,(SELECT COUNT(*) FROM guild_territory_ready_guilds WHERE eliminated_reason='GREAT_RIFT') eliminated,(SELECT rift_event_count FROM guild_territory_wars WHERE war_key='synthetic-current') count");}
try{const expected={operations:4n,outboxes:4n,audits:4n,events:2n,rng:1n,owned:0n,eliminated:1n,count:2n},great=`${base}-great`;
if(restart){const before=await snap();await provider.force({eventId:great,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"greatRift"});assert.deepEqual(await snap(),before);assert.deepEqual(before[0],expected);process.stdout.write(JSON.stringify({mode:"verify-restart",operations:4,additionalMutation:false,operationalDataTouched:false})+"\n");}
else{await db.execute("INSERT INTO players(id,status) VALUES (989100001,'active'),(989100002,'active')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (989100001,'공용개발자'),(989100002,'성주')");await db.execute("INSERT INTO guilds(id,code,display_name,status) VALUES (989110001,'SYN-GUILD-A','테스트A','active'),(989110002,'SYN-GUILD-B','테스트B','active')");await db.execute("INSERT INTO guild_territory_wars(id,war_key,active,turn_count,instability_adjust,rift_bias,rift_event_history_json,castle_lord_player_id,castle_earnings,castle_defense_count) VALUES (989120001,'synthetic-current',TRUE,9,5,-10,JSON_ARRAY(),989100002,100,2),(989120002,'synthetic-inactive',FALSE,0,0,0,JSON_ARRAY(),NULL,0,0)");await db.execute("INSERT INTO guild_territory_ready_guilds(war_id,guild_id,ready) VALUES (989120001,989110001,TRUE),(989120001,989110002,TRUE)");await db.execute("INSERT INTO guild_territory_occupations(war_id,territory_no,territory_name,owner_guild_id,owner_player_id) VALUES (989120001,1,'성',989110001,989100002),(989120001,2,'광산',989110002,989100002)");
const rift=`${base}-rift`;await event(rift);const r=await provider.force({eventId:rift,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"rift"});assert.equal(r.status,"rift");assert.match(r.data,/점령 상태가 초기화/);assert.deepEqual(await provider.force({eventId:rift,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"rift"}),r);
await event(great);const g=await provider.force({eventId:great,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"greatRift"});assert.equal(g.status,"great_rift");assert.equal(g.targetGuildId,"989110002");assert.match(g.data,/\[테스트B\] 길드/);
await db.execute("UPDATE guild_territory_ready_guilds SET eliminated_reason=COALESCE(eliminated_reason,'TEST'),eliminated_at=COALESCE(eliminated_at,UTC_TIMESTAMP(3)) WHERE war_id=989120001");const stable=`${base}-stable`;await event(stable);assert.equal((await provider.force({eventId:stable,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"greatRift"})).status,"stable");const inactive=`${base}-inactive`;await event(inactive);assert.equal((await provider.force({eventId:inactive,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-inactive",kind:"rift"})).status,"inactive");
const rollback=`${base}-rollback`;await event(rollback);const before=await snap();await assert.rejects(()=>new GuildTerritoryWarProvider(failAudit(db),{now:()=>new Date("2026-08-26T13:00:00Z")}).force({eventId:rollback,actorPlayerId:"989100001",destinationId:"synthetic-guild-territory-room",warKey:"synthetic-current",kind:"rift"}),/synthetic guild territory audit failure/);assert.deepEqual(await snap(),before);assert.deepEqual(before[0],expected);assert.equal(await db.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:135,scenarios:["inactive","rift-reset","great-rift-rng","no-target-stable","replay","rollback"],effects:{operations:4,outboxes:4,audits:4,events:2,rng:1,owned:0,eliminated:1,eventCount:2},operationalDataTouched:false})+"\n");}}
finally{await db.close();}
