import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { FreeMarketCancelService } from "../src/market/free-market-cancel-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_free_market_cancel(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic free-market-cancel probe blocked: ${config.database.name}`);
let db=createDatabaseClient(config.database);const seller=995100001,other=995100002,pet=995200001,room="synthetic-free-market-cancel",sellerUser="free-market-cancel-seller",otherUser="free-market-cancel-other";
async function event(id:string,user=sellerUser){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
async function operation(key:string){return(await db.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at,completed_at) VALUES (UUID(),'synthetic.registration',?,'system',NULL,'system','completed',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[key])).insertId;}
function failedAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("free market cancel audit failure");return t.execute(s,p);}}))};}
async function listing(type:string,item:bigint|null,instance:bigint|null,quantity=1n){return(await db.execute("INSERT INTO market_listings(seller_player_id,asset_type_code,item_id,inventory_instance_id,quantity,price_currency_code,price_amount,status,created_at,expires_at) VALUES (?,?,?,?,?,'point',100,'open',UTC_TIMESTAMP(3),DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 DAY))",[seller,type,item,instance,quantity])).insertId;}
async function cancel(id:string,user=sellerUser){await event(id,user);return new FreeMarketCancelService(db).handle({eventId:id,externalUserId:user,destinationId:room,message:"/자유시장취소 1"});}
async function counts(){return(await db.query<Array<{cancelled:bigint;open_count:bigint;ops:bigint;audits:bigint;outboxes:bigint;carrots:bigint}>>("SELECT (SELECT COUNT(*) FROM market_listing_cancellations) cancelled,(SELECT COUNT(*) FROM market_listings WHERE status='open') open_count,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='market.free_market.cancel') ops,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_scope='market.free_market.cancel') audits,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_scope='market.free_market.cancel') outboxes,(SELECT quantity FROM inventory_stacks WHERE player_id=995100001 AND item_id=995400001) carrots"))[0]!;}
async function seed(){await db.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active')",[seller,other]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'판매자'),(?,'다른사람')",[seller,other]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?, 'kakao',?,'linked'),(?,?, 'kakao',?,'linked')",[seller,seller,sellerUser,other,other,otherUser]);await db.execute("INSERT INTO item_definitions(id,code,display_name,asset_type_code,stackable,active) VALUES (995400001,'SYNTHETIC-MARKET-CARROT','합성당근🥕','item',TRUE,TRUE),(995400002,'SYNTHETIC-MARKET-PASS','자유시장회원권🏪','item',TRUE,TRUE),(995400003,'SYNTHETIC-STACK','합성가방아이템','item',TRUE,TRUE),(995400004,'SYNTHETIC-PENDANT','합성펜던트','item',FALSE,TRUE)");await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,995400001,0,1),(?,995400002,1,1),(?,995400003,0,1)",[seller,seller,seller]);await db.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (?,?, '합성펫')",[pet,seller]);await db.execute("INSERT INTO skill_definitions(id,code,display_name,rules_json,active) VALUES (995500001,'SYNTHETIC-MARKET-SKILL','합성스킬',JSON_OBJECT(),TRUE)");await db.execute("INSERT INTO pet_skill_inventory(player_pet_id,skill_id,quantity,version) VALUES (?,995500001,0,2)",[pet]);await db.execute("INSERT INTO furniture_definitions(id,code,display_name) VALUES (995600001,'SYNTHETIC-MARKET-FURNITURE','합성가구')");await db.execute("INSERT INTO furniture_inventory_instances(id,player_id,furniture_definition_id,charm_snapshot,grade_display_name,status,version) VALUES (995610001,?,995600001,10,'합성','listed',2)",[seller]);await db.execute("INSERT INTO mini_pet_definitions(id,code,display_name,active) VALUES (995700001,'SYNTHETIC-MARKET-MINI','합성미니펫',TRUE)");await db.execute("INSERT INTO owned_mini_pets(id,player_id,mini_pet_definition_id,custom_name) VALUES (995710001,?,995700001,'합성미니')",[seller]);await db.execute("INSERT INTO inventory_instances(id,player_id,item_id,status,attributes_json,version) VALUES (995800001,?,995400004,'reserved',JSON_OBJECT('objectType','pendant'),2)",[seller]);}
async function addFee(listingId:bigint,fee=2n){await db.execute("INSERT INTO market_listing_registration_fees(listing_id,carrot_item_id,carrot_fee,source_code) VALUES (?,995400001,?,'synthetic')",[listingId,fee]);}
async function probe(){await seed();assert.equal((await db.query<Array<{state:string}>>("SELECT rollout_state state FROM command_registry WHERE command_code='MARKET_FREE_MARKET_CANCEL'"))[0]!.state,"SHADOW");const stack=await listing("stack",995400003n,null,3n);await addFee(stack);const first=await cancel("cancel-stack");assert.equal(first?.status,"cancelled");assert.equal(first?.refundedCarrot,"2");assert.equal((await db.query<Array<{q:bigint}>>("SELECT quantity q FROM inventory_stacks WHERE player_id=? AND item_id=995400003",[seller]))[0]!.q,3n);assert.equal((await new FreeMarketCancelService(db).handle({eventId:"cancel-stack",externalUserId:sellerUser,destinationId:room,message:"/자유시장취소 1"}))?.replayed,true);
const pendant=await listing("instance",995400004n,995800001n);await addFee(pendant);assert.equal((await cancel("cancel-pendant"))?.status,"cancelled");assert.equal((await db.query<Array<{s:string}>>("SELECT status s FROM inventory_instances WHERE id=995800001"))[0]!.s,"owned");
const skill=await listing("pet_skill",null,null,4n),skillOp=await operation("skill");await db.execute("INSERT INTO market_skill_registration_ledger(operation_id,listing_id,player_id,player_pet_id,skill_id,source_index,quantity,price_amount,carrot_item_id,carrot_fee,skill_quantity_before,skill_quantity_after,source_version_before,source_version_after,carrot_version_before,carrot_version_after) VALUES (?,?,?,?,995500001,1,4,100,995400001,2,4,0,1,2,1,2)",[skillOp,skill,seller,pet]);await addFee(skill);assert.equal((await cancel("cancel-skill"))?.status,"cancelled");assert.equal((await db.query<Array<{q:bigint}>>("SELECT quantity q FROM pet_skill_inventory WHERE player_pet_id=? AND skill_id=995500001",[pet]))[0]!.q,4n);
const furniture=await listing("furniture",null,null),furnitureOp=await operation("furniture");await db.execute("INSERT INTO market_furniture_registration_ledger(operation_id,listing_id,player_id,furniture_definition_id,source_index,quantity,price_amount,carrot_item_id,carrot_fee,carrot_version_before,carrot_version_after) VALUES (?,?,?,?,1,1,100,995400001,2,1,2)",[furnitureOp,furniture,seller,995600001]);await db.execute("INSERT INTO market_furniture_registration_items(operation_id,sequence_no,furniture_instance_id,source_version_before,source_version_after) VALUES (?,1,995610001,1,2)",[furnitureOp]);await addFee(furniture);assert.equal((await cancel("cancel-furniture"))?.status,"cancelled");assert.equal((await db.query<Array<{s:string}>>("SELECT status s FROM furniture_inventory_instances WHERE id=995610001"))[0]!.s,"bag");
const mini=await listing("mini_pet",null,null);await db.execute("INSERT INTO market_mini_pet_reservations(listing_id,owned_mini_pet_id,player_id) VALUES (?,995710001,?)",[mini,seller]);await addFee(mini);assert.equal((await cancel("cancel-mini"))?.status,"cancelled");assert.equal((await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM market_mini_pet_reservations WHERE listing_id=?",[mini]))[0]!.c,0n);
const foreign=await listing("stack",995400003n,null);assert.equal((await cancel("cancel-foreign",otherUser))?.status,"not_owner");await db.execute("UPDATE market_listings SET status='cancelled',closed_at=UTC_TIMESTAMP(3) WHERE id=?",[foreign]);assert.equal((await cancel("cancel-missing"))?.status,"not_found");
const rollbackListing=await listing("stack",995400003n,null,2n);await addFee(rollbackListing);await event("cancel-rollback");const before=await counts();await assert.rejects(()=>new FreeMarketCancelService(failedAudit(db)).handle({eventId:"cancel-rollback",externalUserId:sellerUser,destinationId:room,message:"/자유시장취소 1"}),/free market cancel audit failure/);assert.deepEqual(await counts(),before);assert.equal(await db.verifyRollback(),true);assert.equal((await cancel("cancel-after-rollback"))?.status,"cancelled");const state=await counts();assert.deepEqual([state.cancelled,state.open_count,state.ops,state.audits,state.outboxes,state.carrots],[6n,0n,8n,8n,8n,12n]);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:257,scenarios:["shadow","stack","pendant","pet-skill","furniture","mini-pet","fee-refund","not-owner","not-found","replay","rollback","restart"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
async function restart(){const state=await counts();assert.deepEqual([state.cancelled,state.open_count,state.ops,state.audits,state.outboxes,state.carrots],[6n,0n,8n,8n,8n,12n]);process.stdout.write(JSON.stringify({mode:"verify-restart",state,additionalMutation:false,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
