import { createDatabaseClient } from "../src/database.js";
import { GuildTerritoryWarReadyService } from "../src/guild/guild-territory-war-ready-service.js";
const required=(name:string):string=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;};
const db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:process.env.DATABASE_PASSWORD??"",name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5_000});
const verify=process.argv.includes("--verify-restart"),room="990000000000344",guildId=989344001n,masterId=989344002n,subMasterId=989344003n,memberId=989344004n,warId=989344100n,activeWarId=989344101n,masterExternal="territory-ready-probe-master",subExternal="territory-ready-probe-sub",memberExternal="territory-ready-probe-member",restartEvent="territory-ready-recovery";
const seedEvent=async(eventId:string,external=masterExternal)=>db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('4',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,room,external]);
const errorCode=async(work:()=>Promise<unknown>):Promise<string>=>{try{await work();return"NO_ERROR";}catch(error){return String((error as{code?:unknown}).code??(error as Error).message);}};
try{const service=new GuildTerritoryWarReadyService(db);if(!verify){
  await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=1 WHERE command_code='GUILD_TERRITORY_WAR_READY'");
  await db.execute("DELETE FROM guild_territory_wars WHERE id IN (?,?)",[warId,activeWarId]);
  await db.execute("INSERT INTO guilds(id,code,display_name,status,mark,version) VALUES (?,'GUILD-TERRITORY-READY-PROBE','영지준비 합성길드','active','R',1) ON DUPLICATE KEY UPDATE status='active',version=1",[guildId]);
  for(const[id,name,external,role]of[[masterId,"합성길드마스터",masterExternal,"master"],[subMasterId,"합성부길드마스터",subExternal,"sub_master"],[memberId,"합성일반길드원",memberExternal,"member"]]as const){await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1) ON DUPLICATE KEY UPDATE status='active',version=1",[id]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1) ON DUPLICATE KEY UPDATE current_display_name=VALUES(current_display_name),version=1",[id,name]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked') ON DUPLICATE KEY UPDATE player_id=VALUES(player_id),display_name=VALUES(display_name),status='linked'",[id,external,name]);await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES (?,?,?,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE guild_id=VALUES(guild_id),role_code=VALUES(role_code)",[guildId,id,role]);}
  await db.execute("INSERT INTO guild_territory_rift_authorizations(guild_id,player_id,authority_code,active,version) VALUES (?,?,'combat_commander',TRUE,1) ON DUPLICATE KEY UPDATE active=TRUE,version=1",[guildId,masterId]);
  await db.execute("INSERT INTO guild_territory_wars(id,war_key,active,lifecycle_state,start_ready,rift_event_history_json,version) VALUES (?,'territory-ready-probe',FALSE,'READY',FALSE,'[]',1)",[warId]);
  for(const[event,external]of[["territory-ready-member-denied",memberExternal],["territory-ready-no-attacker",masterExternal],["territory-ready-active-war",masterExternal],["territory-ready-first",subExternal],["territory-ready-duplicate",masterExternal],["territory-ready-concurrent-a",masterExternal],["territory-ready-concurrent-b",subExternal],[restartEvent,masterExternal]]as const)await seedEvent(event,external);
  const memberDenied=await errorCode(()=>service.prepare({eventId:"territory-ready-member-denied",externalUserId:memberExternal,channelId:room,message:"/길드영지준비"}));
  await db.execute("UPDATE guild_territory_rift_authorizations SET active=FALSE WHERE guild_id=?",[guildId]);const noAttacker=await errorCode(()=>service.prepare({eventId:"territory-ready-no-attacker",externalUserId:masterExternal,channelId:room,message:"/길드영지준비"}));await db.execute("UPDATE guild_territory_rift_authorizations SET active=TRUE WHERE guild_id=?",[guildId]);
  await db.execute("INSERT INTO guild_territory_wars(id,war_key,active,lifecycle_state,start_ready,rift_event_history_json,version) VALUES (?,'territory-ready-active-probe',TRUE,'ACTIVE_READY',TRUE,'[]',1)",[activeWarId]);const activeBlocked=await errorCode(()=>service.prepare({eventId:"territory-ready-active-war",externalUserId:masterExternal,channelId:room,message:"/길드영지준비"}));await db.execute("DELETE FROM guild_territory_wars WHERE id=?",[activeWarId]);
  const first=await service.prepare({eventId:"territory-ready-first",externalUserId:subExternal,channelId:room,message:"/길드영지준비"});const replay=await service.prepare({eventId:"territory-ready-first",externalUserId:subExternal,channelId:room,message:"/길드영지준비"});const duplicate=await service.prepare({eventId:"territory-ready-duplicate",externalUserId:masterExternal,channelId:room,message:"/길드영지준비"});
  await db.execute("DELETE FROM guild_territory_ready_guilds WHERE war_id=? AND guild_id=?",[warId,guildId]);const concurrent=await Promise.all([service.prepare({eventId:"territory-ready-concurrent-a",externalUserId:masterExternal,channelId:room,message:"/길드영지준비"}),service.prepare({eventId:"territory-ready-concurrent-b",externalUserId:subExternal,channelId:room,message:"/길드영지준비"})]);
  await db.execute("DELETE FROM guild_territory_ready_guilds WHERE war_id=? AND guild_id=?",[warId,guildId]);const beforeRollback=(await db.query<Array<{guild_version:bigint;war_version:bigint}>>("SELECT guild.version guild_version,war.version war_version FROM guilds guild JOIN guild_territory_wars war ON war.id=? WHERE guild.id=?",[warId,guildId]))[0]!;const rollbackError=await errorCode(()=>service.prepare({eventId:"territory-ready-rollback",externalUserId:masterExternal,channelId:"X".repeat(300),message:"/길드영지준비"}));const rollbackReady=Number((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_territory_ready_guilds WHERE war_id=? AND guild_id=?",[warId,guildId]))[0]!.count_value);const afterRollback=(await db.query<Array<{guild_version:bigint;war_version:bigint}>>("SELECT guild.version guild_version,war.version war_version FROM guilds guild JOIN guild_territory_wars war ON war.id=? WHERE guild.id=?",[warId,guildId]))[0]!;
  const recovery=await service.prepare({eventId:restartEvent,externalUserId:masterExternal,channelId:room,message:"/길드영지준비"});console.log(JSON.stringify({mode:"probe",migrationCount:Number((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM schema_migrations"))[0]!.count_value),scenarios:["exact","leader-subleader","combat-commander-master","attacker-required","active-block","pending-ready","duplicate","concurrency","rollback","restart"],memberDenied,noAttacker,activeBlocked,firstStatus:first.status,replaySame:first.outboxId===replay.outboxId,duplicateStatus:duplicate.status,concurrentStatuses:concurrent.map(value=>value.status).sort(),rollbackError,rollbackReady,rollbackVersionsPreserved:beforeRollback.guild_version===afterRollback.guild_version&&beforeRollback.war_version===afterRollback.war_version,recoveryStatus:recovery.status,operationalDataTouched:false}));
}else{const before=(await db.query<Array<{guild_version:bigint;war_version:bigint;ready_version:bigint}>>("SELECT guild.version guild_version,war.version war_version,ready.version ready_version FROM guilds guild JOIN guild_territory_wars war ON war.id=? JOIN guild_territory_ready_guilds ready ON ready.war_id=war.id AND ready.guild_id=guild.id WHERE guild.id=?",[warId,guildId]))[0]!;const replay=await service.prepare({eventId:restartEvent,externalUserId:masterExternal,channelId:room,message:"/길드영지준비"});const after=(await db.query<Array<{guild_version:bigint;war_version:bigint;ready_version:bigint;prepared_by_player_id:bigint}>>("SELECT guild.version guild_version,war.version war_version,ready.version ready_version,ready.prepared_by_player_id FROM guilds guild JOIN guild_territory_wars war ON war.id=? JOIN guild_territory_ready_guilds ready ON ready.war_id=war.id AND ready.guild_id=guild.id WHERE guild.id=?",[warId,guildId]))[0]!;console.log(JSON.stringify({mode:"verify-restart",status:replay.status,preparedByPlayerId:after.prepared_by_player_id.toString(),additionalMutation:before.guild_version!==after.guild_version||before.war_version!==after.war_version||before.ready_version!==after.ready_version,operationalDataTouched:false}));}}finally{await db.close();}
