import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetEliteCombineService } from "../src/mini-pet/mini-pet-elite-combine-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_minipet_elite_combine$/i.test(config.database.name))throw new Error(`Synthetic probe blocked for ${config.database.name}`);
const database=createDatabaseClient(config.database),restart=process.argv.includes("--verify-restart"),player=987000013,identity=987200013,external="synthetic-mini-pet-elite-combine",room="synthetic-mini-pet-elite-room",successEvent="elite-combine-success";
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('e',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,external]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic elite combine audit failure");return t.execute(s,p);}}))};}
async function seed(){await database.execute("INSERT INTO players(id,status,version) VALUES(?,'active',1)",[player]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(?,'합성회원')",[player]);await database.execute("INSERT INTO external_identities(id,provider_code,external_user_id,player_id,status) VALUES(?,'kakao',?,?,'linked')",[identity,external,player]);for(let i=1;i<=3;i++){await database.execute("INSERT INTO mini_pet_definitions(code,display_name,grade_code,grade_display_name,emoji_value,active) VALUES(?,?,'creation','창조','🐹',TRUE)",[`synthetic-elite-material-${i}`,`합성창조${i}`]);await database.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,equipped,sale_price,is_elite,bag_sequence,enhancement_level,battle_experience,castle_experience,raid_experience,version) SELECT ?,id,FALSE,1000000,FALSE,?,300,1,1,1,1 FROM mini_pet_definitions WHERE code=?",[player,i,`synthetic-elite-material-${i}`]);}await database.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES(?,'point',150000000000,1)",[player]);}
async function state(){const row=(await database.query<Array<{point:string;pets:bigint;elite:bigint;events:bigint;operations_count:bigint;audits:bigint;outboxes:bigint;executions:bigint}>>(`SELECT CAST(account.balance AS CHAR) point,(SELECT COUNT(*) FROM owned_mini_pets WHERE player_id=?) pets,(SELECT COUNT(*) FROM owned_mini_pets pet JOIN mini_pet_definitions definition ON definition.id=pet.mini_pet_definition_id WHERE pet.player_id=? AND definition.grade_display_name='엘리트') elite,(SELECT COUNT(*) FROM mini_pet_elite_combine_events WHERE player_id=?) events,(SELECT COUNT(*) FROM operations WHERE idempotency_scope=?) operations_count,(SELECT COUNT(*) FROM command_audit WHERE action_code='mini_pet.elite.combine') audits,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope=?) outboxes,(SELECT COUNT(*) FROM command_executions WHERE command_code='MINI_PET_ELITE_COMBINE') executions FROM currency_accounts account WHERE account.player_id=? AND account.currency_code='point'`,[player,player,player,`mini-pet.elite.combine:${identity}`,`mini-pet.elite.combine:${identity}`,player]))[0]!;return row;}
async function run(){const service=(values:number[])=>new MiniPetEliteCombineService(database,()=>{const value=values.shift();if(value===undefined)throw new Error("synthetic RNG exhausted");return value;});if(restart){const before=await state(),result=await service([]).handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫조합엘리트 1 2"});assert.equal(result.replayed,true);assert.deepEqual(await state(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",state:before,additionalMutation:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");return;}
  await seed();const registry=(await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MINI_PET_ELITE_COMBINE'"))[0];assert.equal(registry?.rollout_state,"SHADOW");assert.equal((await database.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM mini_pet_elite_combine_rewards reward JOIN mini_pet_elite_combine_recipes recipe ON recipe.id=reward.recipe_id WHERE recipe.recipe_code='ELITE-COMBINE' AND recipe.recipe_version=1 AND reward.active=TRUE"))[0]?.count,12n);
  await event("elite-combine-fail");const failed=await service([0.5]).handle({eventId:"elite-combine-fail",externalUserId:external,destinationId:room,message:"/미니펫조합엘리트 1 2"});assert.equal(failed.status,"failed");assert.deepEqual(await state(),{point:"115000000000.000",pets:3n,elite:0n,events:1n,operations_count:1n,audits:1n,outboxes:1n,executions:1n});
  await event(successEvent);const pair=await Promise.all([service([0.01,0]).handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫조합엘리트 1 2"}),service([0.01,0]).handle({eventId:successEvent,externalUserId:external,destinationId:room,message:"/미니펫조합엘리트 1 2"})]);assert.equal(pair.every(result=>result.status==="success"),true);assert.equal(pair.filter(result=>result.replayed===true).length,1);const after=await state();assert.deepEqual(after,{point:"80000000000.000",pets:2n,elite:1n,events:2n,operations_count:2n,audits:2n,outboxes:2n,executions:2n});
  await event("elite-combine-rollback");const beforeRollback=await state();await assert.rejects(()=>new MiniPetEliteCombineService(failAudit(database),()=>0.01).handle({eventId:"elite-combine-rollback",externalUserId:external,destinationId:room,message:"/미니펫조합엘리트 1 2"}),/synthetic elite combine audit failure/);assert.deepEqual(await state(),beforeRollback);assert.equal(await database.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:293,scenarios:["shadow-registry","recipe-v1","reward-pool-12","strict-two-index","stable-owned-id","point-35b","failure-keeps-materials","success-consumes-two","uniform-reward","concurrent-replay","rollback","audit-outbox","restart-ready"],state:after,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{await run();}finally{await database.close();}
