import assert from"node:assert/strict";
import{loadConfig}from"../src/config.js";
import{createDatabaseClient,type DatabaseClient,type DatabaseTransaction}from"../src/database.js";
import{HomeFurnitureAddService}from"../src/home/home-furniture-add-service.js";
const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_home_furniture_add(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic home furniture add probe blocked: ${config.database.name}`);
const database=createDatabaseClient(config.database),service=new HomeFurnitureAddService(database),base=process.env.HOME_FURNITURE_ADD_PROBE_EVENT_ID??"home-furniture-add-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),room="synthetic-home-furniture-add-room",activeExternal="home-furniture-add-active-admin",inactiveExternal="home-furniture-add-inactive-admin",ordinaryExternal="home-furniture-add-ordinary-user";
async function event(suffix:string,external:string){const id=`${base}-${suffix}`;await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('a',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,external]);return id;}
async function player(id:number,external:string,name:string){await database.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[id,name]);return(await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,?,'linked')",[id,external,name])).insertId;}
async function effects(){const p=`${base}-%`;return(await database.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint;summaries:bigint;ledgers:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='home.furniture_add' AND idempotency_key LIKE ?) operations,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_scope='home.furniture_add' AND o.idempotency_key LIKE ?) outboxes,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_scope='home.furniture_add' AND o.idempotency_key LIKE ?) audits,(SELECT COUNT(*) FROM command_executions WHERE event_id LIKE ?) executions,(SELECT COUNT(*) FROM home_furniture_add_operations s JOIN operations o ON o.id=s.operation_id WHERE o.idempotency_key LIKE ?) summaries,(SELECT COUNT(*) FROM furniture_inventory_ledger l JOIN operations o ON o.id=l.operation_id WHERE o.idempotency_scope='home.furniture_add' AND o.idempotency_key LIKE ?) ledgers",[p,p,p,p,p,p]))[0]!;}
async function state(){return(await database.query<Array<{definitions:bigint;bag:bigint;placed:bigint;listed:bigint;signature:string}>>("SELECT (SELECT COUNT(*) FROM furniture_definitions WHERE code LIKE 'admin-%') definitions,(SELECT COUNT(*) FROM furniture_inventory_instances i JOIN furniture_definitions d ON d.id=i.furniture_definition_id WHERE d.code LIKE 'admin-%' AND i.status='bag') bag,(SELECT COUNT(*) FROM furniture_inventory_instances i JOIN furniture_definitions d ON d.id=i.furniture_definition_id WHERE d.code LIKE 'PROBE-ADD-BASE-%' AND i.status='placed') placed,(SELECT COUNT(*) FROM furniture_inventory_instances i JOIN furniture_definitions d ON d.id=i.furniture_definition_id WHERE d.code LIKE 'PROBE-ADD-BASE-%' AND i.status='listed') listed,(SELECT GROUP_CONCAT(CONCAT(i.id,':',i.status,':',i.version) ORDER BY i.id SEPARATOR '|') FROM furniture_inventory_instances i JOIN furniture_definitions d ON d.id=i.furniture_definition_id WHERE d.code LIKE 'admin-%' OR d.code LIKE 'PROBE-ADD-BASE-%') signature"))[0]!;}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic home furniture add audit failure");return t.execute(s,p);}}))};}
try{const successEvent=`${base}-success`;if(restart){const beforeEffects=await effects(),beforeState=await state();const replay=await service.handle({eventId:successEvent,externalUserId:activeExternal,destinationId:room,message:"/가구추가 대상 긴이름 샤넬 컬렉션💎 56050 시그니엘"});assert.equal(replay.status,"added");assert.deepEqual(await effects(),beforeEffects);assert.deepEqual(await state(),beforeState);process.stdout.write(JSON.stringify({mode:"restart",scenarios:["restart-replay"],effects:beforeEffects},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}else{
 assert.deepEqual((await database.query<Array<{handler_key:string;rollout_state:string;alias_count:bigint}>>("SELECT registry.handler_key,registry.rollout_state,(SELECT COUNT(*) FROM command_aliases a WHERE a.command_code=registry.command_code AND a.command_text='/가구추가' AND a.active=TRUE) alias_count FROM command_registry registry WHERE registry.command_code='HOME_FURNITURE_ADD'"))[0],{handler_key:"home_furniture_add",rollout_state:"SHADOW",alias_count:1n});
 const activeIdentity=await player(205001,activeExternal,"추가 운영자"),inactiveIdentity=await player(205002,inactiveExternal,"비활성 운영자");await player(205003,ordinaryExternal,"일반 사용자");await player(205004,"home-furniture-add-short","대상");await player(205005,"home-furniture-add-long","대상 긴이름");await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (205901,'add-active','추가 운영자','synthetic','active'),(205902,'add-inactive','비활성 운영자','synthetic','inactive')");await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (205901,?),(205902,?)",[activeIdentity,inactiveIdentity]);
 for(const [suffix,external]of[["ordinary",ordinaryExternal],["inactive",inactiveExternal]]as const){const id=await event(suffix,external);assert.deepEqual(await service.handle({eventId:id,externalUserId:external,destinationId:room,message:"/가구추가 대상 긴이름 의자 100 일반"}),{status:"ignored"});}assert.deepEqual(await effects(),{operations:0n,outboxes:0n,audits:0n,executions:0n,summaries:0n,ledgers:0n});
 for(const [suffix,message,fragment]of[["usage","/가구추가 ","사용법:"],["target","/가구추가 없는 대상 의자 100 일반","대상 닉네임"],["format","/가구추가 대상 긴이름 의자 일반 등급","가구이름 / 매력 / 등급"],["charm","/가구추가 대상 긴이름 의자 -1 일반","매력수치는 숫자"]]as const){const id=await event(suffix,activeExternal),result=await service.handle({eventId:id,externalUserId:activeExternal,destinationId:room,message});assert.equal(result.status,"rejected");assert.ok(result.reply?.includes(fragment));}
 const placedDef=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value) VALUES ('PROBE-ADD-BASE-PLACED','기존배치',1)"),listedDef=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value) VALUES ('PROBE-ADD-BASE-LISTED','기존등록',1)");await database.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (205005,?,1,'기존','placed'),(205005,?,1,'기존','listed')",[placedDef.insertId,listedDef.insertId]);
 await event("success",activeExternal);const added=await service.handle({eventId:successEvent,externalUserId:activeExternal,destinationId:room,message:"/가구추가 대상 긴이름 샤넬 컬렉션💎 56050 시그니엘"});assert.equal(added.status,"added");assert.ok(added.reply?.includes("👤 대상: 대상 긴이름"));const row=(await database.query<Array<{display_name:string;charm_snapshot:bigint;grade_display_name:string;status:string;code:string}>>("SELECT d.display_name,i.charm_snapshot,i.grade_display_name,i.status,d.code FROM furniture_inventory_instances i JOIN furniture_definitions d ON d.id=i.furniture_definition_id WHERE i.id=?",[added.furnitureInstanceId]))[0]!;assert.equal(row.display_name,"샤넬 컬렉션💎");assert.equal(row.charm_snapshot,56050n);assert.equal(row.grade_display_name,"시그니엘");assert.equal(row.status,"bag");assert.match(row.code,/^admin-[a-f0-9]{64}$/);assert.deepEqual(await effects(),{operations:5n,outboxes:5n,audits:5n,executions:5n,summaries:1n,ledgers:1n});assert.deepEqual(await service.handle({eventId:successEvent,externalUserId:activeExternal,destinationId:room,message:"/가구추가 대상 긴이름 샤넬 컬렉션💎 56050 시그니엘"}),added);
 const rollbackBefore=await state(),rollbackEvent=await event("rollback",activeExternal);await assert.rejects(()=>new HomeFurnitureAddService(failAudit(database)).handle({eventId:rollbackEvent,externalUserId:activeExternal,destinationId:room,message:"/가구추가 대상 긴이름 롤백 가구 777 특별"}),/synthetic home furniture add audit failure/);assert.deepEqual(await state(),rollbackBefore);assert.deepEqual(await effects(),{operations:5n,outboxes:5n,audits:5n,executions:5n,summaries:1n,ledgers:1n});assert.equal(await database.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:205,scenarios:["shadow-registry","active-admin-only","unauthorized-silent","longest-target-name","legacy-first-number-parser","stable-definition-key","single-bag-instance","placed-listed-immutable","summary-ledger-audit-outbox","idempotent-rollback-restart"],effects:await effects(),operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}}
finally{await database.close();}
