import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { PetDuelEmoteService } from "../src/pet/pet-duel-emote-service.js";

const config=loadConfig();if(!config.database.enabled||!/^hoibot_pet_duel_emote(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Blocked database: ${config.database.name}`);
const db=createDatabaseClient(config.database),base=process.env.PET_DUEL_EMOTE_EVENT_ID??"pet-duel-emote-g7-20260827-r1",room="duel-origin",restart=process.argv.includes("--verify-restart");
const input=(suffix:string,user:string,message:string)=>({eventId:`${base}-${suffix}`,externalUserId:user,destinationId:room,message});
async function event(suffix:string,user:string){const id=`${base}-${suffix}`;await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
function sequence(values:number[]){return()=>values.shift()??0;}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(tx:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(tx=>work({query:(s,p)=>tx.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic duel audit failure");return tx.execute(s,p);}}))};}
async function snapshot(){return(await db.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint;events:bigint;successes:bigint;failures:bigint}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_key LIKE ?) operations,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_key LIKE ?) outboxes,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_key LIKE ?) audits,(SELECT COUNT(*) FROM command_executions WHERE event_id LIKE ?) executions,(SELECT COUNT(*) FROM pet_duel_emote_events e JOIN operations o ON o.id=e.operation_id WHERE o.idempotency_key LIKE ?) events,(SELECT COUNT(*) FROM pet_duel_emote_events e JOIN operations o ON o.id=e.operation_id WHERE o.idempotency_key LIKE ? AND e.outcome_code='success') successes,(SELECT COUNT(*) FROM pet_duel_emote_events e JOIN operations o ON o.id=e.operation_id WHERE o.idempotency_key LIKE ? AND e.outcome_code='failure') failures`,Array(7).fill(`${base}-%`)))[0]!;}
const expected={operations:3n,outboxes:3n,audits:3n,executions:3n,events:2n,successes:1n,failures:1n};
try{if(!restart){
 for(const [id,user,name]of[[989810001,"duel-user","결투 남"],[989810002,"duel-target","대상 남"],[989810003,"duel-no-skill","무장착 남"]]as const){await db.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[id,name]);await db.execute("INSERT INTO external_identities(provider_code,external_user_id,player_id,status) VALUES ('kakao',?,?,'linked')",[user,id]);}
 const pet=await db.execute("INSERT INTO player_pets(player_id,display_name) VALUES (989810001,'검증 펫')");const skill=await db.execute("INSERT INTO skill_definitions(code,display_name,active) VALUES ('synthetic-zero-conduct','품행제로',TRUE)");await db.execute("INSERT INTO pet_skills(player_pet_id,slot_no,skill_id,level,equipped) VALUES (?,1,?,1,TRUE)",[pet.insertId,skill.insertId]);
 for(const [suffix,user]of[["usage","duel-user"],["success","duel-user"],["failure","duel-user"],["rollback","duel-user"],["no-skill","duel-no-skill"],["self","duel-user"]]as const)await event(suffix,user);
 assert.equal((await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM command_registry WHERE handler_key='pet_duel_emote' AND rollout_state='SHADOW'"))[0]!.c,1n);
 const usage=await new PetDuelEmoteService(db).handle(input("usage","duel-user","/결투"));assert.equal(usage.status,"usage");
 const successService=new PetDuelEmoteService(db,sequence([0.1,0]));const success=await successService.handle(input("success","duel-user","/결투 대상 남"));assert.equal(success.outcome,"success");assert.deepEqual(await successService.handle(input("success","duel-user","/결투 대상 남")),success);
 const failure=await new PetDuelEmoteService(db,sequence([0.9,0.9])).handle(input("failure","duel-user","/결투 대상 남"));assert.equal(failure.outcome,"failure");
 await assert.rejects(()=>new PetDuelEmoteService(db).handle(input("no-skill","duel-no-skill","/결투 대상 남")),/품행제로/);await assert.rejects(()=>new PetDuelEmoteService(db).handle(input("self","duel-user","/결투 결투 남")),/자기 자신/);
 await assert.rejects(()=>new PetDuelEmoteService(failAudit(db),sequence([0.1,0])).handle(input("rollback","duel-user","/결투 대상 남")),/synthetic duel audit failure/);assert.deepEqual(await snapshot(),expected);assert.equal(await db.verifyRollback(),true);
 }else{const before=await snapshot();await new PetDuelEmoteService(db,sequence([0.9,0.9])).handle(input("success","duel-user","/결투 대상 남"));assert.deepEqual(await snapshot(),before);assert.deepEqual(before,expected);}
 process.stdout.write(JSON.stringify({mode:restart?"verify-restart":"probe",migrationCount:174,scenarios:["shadow-registry","usage","equipped-skill","success-70","failure-30","target-validation","no-gameplay-mutation","replay","rollback","restart"],effects:await snapshot(),operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v)+"\n");
}finally{await db.close();}
