import assert from "node:assert/strict";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { loadConfig } from "../src/config.js";
import { AdminAuctionResetService } from "../src/admin/admin-auction-reset-service.js";

const config=loadConfig();
if(!config.database.enabled||!/^hoibot_admin_auction_reset(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error("Admin auction reset probe requires an isolated database.");
const db=createDatabaseClient(config.database),actor="auction-reset-actor",denied="auction-reset-denied",room="synthetic-auction-reset";
async function event(id:string,user=actor){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('9',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic auction reset audit failure");return t.execute(s,p);}}))};}
async function snapshot(){return (await db.query<Array<{active:bigint;reset:bigint;sold:bigint;runs:bigint;reset_lines:bigint;ops:bigint;audits:bigint;executions:bigint;outboxes:bigint;bidder_point:string}>>(`SELECT (SELECT COUNT(*) FROM auction_listings WHERE status IN ('active','expired')) active,(SELECT COUNT(*) FROM auction_listings WHERE status='reset') reset,(SELECT COUNT(*) FROM auction_listings WHERE status='sold') sold,(SELECT COUNT(*) FROM auction_reset_runs) runs,(SELECT COUNT(*) FROM auction_reset_lines) reset_lines,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='admin.auction.reset') ops,(SELECT COUNT(*) FROM command_audit WHERE action_code='admin.auction.reset') audits,(SELECT COUNT(*) FROM command_executions WHERE command_code='ADMIN_AUCTION_RESET') executions,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='admin.auction.reset') outboxes,(SELECT CAST(balance AS CHAR) FROM currency_accounts WHERE player_id=994000003 AND currency_code='point') bidder_point`))[0]!;}
async function seed(){
 await db.execute("INSERT INTO players(id,status,version) VALUES(994000001,'active',1),(994000002,'active',1),(994000003,'active',1)");
 await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(994000001,'경매 운영자'),(994000002,'판매자'),(994000003,'입찰자')");
 await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,display_name,status) VALUES(994100001,994000001,'kakao',?,'경매 운영자','linked'),(994100002,NULL,'kakao',?,'미권한','linked')",[actor,denied]);
 await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES(994200001,'auction-reset-master','경매 운영자','synthetic','active'),(994200002,'auction-reset-denied','미권한','synthetic','active')");
 await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES(994200001,994100001),(994200002,994100002)");
 await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 994200001,id FROM admin_roles WHERE code='super_admin'");
 await db.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES(994000003,'point',777,1)");
 await db.execute("INSERT INTO auction_listings(id,seller_player_id,item_name,highest_bidder_player_id,highest_bid,ends_at,legacy_timeout_key,legacy_original_index,status,version) VALUES(994300001,994000002,'활성 아이템',994000003,100,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),'timeout-active',1,'active',2),(994300002,994000002,'만료 아이템',994000003,200,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),'timeout-expired',2,'expired',3),(994300003,994000002,'판매 완료',994000003,300,UTC_TIMESTAMP(3),NULL,3,'sold',4)");
}
async function probe(){
 await seed();const service=new AdminAuctionResetService(db);assert.equal((await db.query<Array<{s:string}>>("SELECT rollout_state s FROM command_registry WHERE command_code='ADMIN_AUCTION_RESET'"))[0]?.s,"SHADOW");assert.equal(await service.handle({eventId:"invalid",externalUserId:actor,channelId:room,message:"/경매초기화 안내"}),null);await event("denied",denied);assert.equal(await service.handle({eventId:"denied",externalUserId:denied,channelId:room,message:"/경매초기화"}),null);
 const success="auction-reset-success";await event(success);const first=await service.handle({eventId:success,externalUserId:actor,channelId:room,message:"/경매초기화"});assert.equal(first?.resetListingCount,2);assert.equal(first?.data,"호이상점이 초기화가 되었습니다");assert.deepEqual(first?.resetListingIds,["994300001","994300002"]);assert.equal((await service.handle({eventId:success,externalUserId:actor,channelId:room,message:"/경매초기화"}))?.replayed,true);
 let state=await snapshot();assert.deepEqual(state,{active:0n,reset:2n,sold:1n,runs:1n,reset_lines:2n,ops:1n,audits:1n,executions:1n,outboxes:1n,bidder_point:"777.000"});
 const concurrent="auction-reset-concurrent";await event(concurrent);const pair=await Promise.all([service.handle({eventId:concurrent,externalUserId:actor,channelId:room,message:"/경매초기화"}),service.handle({eventId:concurrent,externalUserId:actor,channelId:room,message:"/경매초기화"})]);assert.equal(pair[0]?.resetRunId,pair[1]?.resetRunId);assert.deepEqual(pair.map(x=>x?.replayed).sort(),[false,true]);
 await db.execute("INSERT INTO auction_listings(id,seller_player_id,item_name,highest_bidder_player_id,highest_bid,ends_at,status,version) VALUES(994300004,994000002,'롤백 아이템',994000003,400,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 HOUR),'active',1)");const rollback="auction-reset-rollback";await event(rollback);const before=await snapshot();await assert.rejects(()=>new AdminAuctionResetService(failAudit(db)).handle({eventId:rollback,externalUserId:actor,channelId:room,message:"/경매초기화"}),/synthetic auction reset audit failure/);assert.deepEqual(await snapshot(),before);assert.equal(await db.verifyRollback(),true);const retried=await service.handle({eventId:rollback,externalUserId:actor,channelId:room,message:"/경매초기화"});assert.equal(retried?.resetListingCount,1);
 state=await snapshot();assert.deepEqual(state,{active:0n,reset:3n,sold:1n,runs:3n,reset_lines:3n,ops:3n,audits:3n,executions:3n,outboxes:3n,bidder_point:"777.000"});const migrationCount=(await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM schema_migrations"))[0]!.c;process.stdout.write(JSON.stringify({mode:"probe",migrationCount,scenarios:["shadow","exact","permission","empty","active-expired","sold-preserved","bidder-point","replay","concurrent","rollback","restart"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");
}
async function restart(){const before=await snapshot();const replay=await new AdminAuctionResetService(db).handle({eventId:"auction-reset-success",externalUserId:actor,channelId:room,message:"/경매초기화"});assert.equal(replay?.replayed,true);assert.deepEqual(await snapshot(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",additionalMutation:false,bidderPointsChanged:false,state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
