import assert from "node:assert/strict";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { loadConfig } from "../src/config.js";
import { CastleKingdomStatusReadService } from "../src/castle/castle-kingdom-status-read-service.js";

const config=loadConfig();
if(!config.database.enabled||!/^hoibot_castle_kingdom_status(?:_[a-z0-9_]+)?$/i.test(config.database.name)) throw new Error("Castle kingdom probe requires an isolated database.");
const database=createDatabaseClient(config.database),viewer="synthetic-kingdom-viewer",room="synthetic-kingdom-room",base="kingdom-g7-r1";
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('9',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,viewer]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic kingdom audit failure");return t.execute(s,p);}}))};}
async function effects(){return database.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint;castle_version:bigint;guild_version:bigint;pet_experience:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'castle.kingdom.status.read:%') operations,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope LIKE 'castle.kingdom.status.read:%') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='castle.kingdom.status.read') audits,(SELECT COUNT(*) FROM command_executions WHERE command_code='CASTLE_KINGDOM_STATUS_READ') executions,(SELECT version FROM castle_state WHERE state_code='HOI_CASTLE') castle_version,(SELECT version FROM guilds WHERE id=991400001) guild_version,(SELECT experience FROM player_pets WHERE player_id=991000002) pet_experience");}
async function seed(){await database.execute("INSERT INTO players(id,status,version) VALUES(991000001,'active',1),(991000002,'active',1)");await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(991000001,'조회자'),(991000002,'영주')");await database.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,display_name,status) VALUES(991200001,991000001,'kakao',?,'조회자','linked')",[viewer]);await database.execute("INSERT INTO player_pets(id,player_id,display_name,experience) VALUES(991300001,991000002,'영주펫',1000)");await database.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES(991000002,'👑',1)");await database.execute("INSERT INTO guilds(id,code,display_name,status,version,mark,server_code) VALUES(991400001,'KINGDOM-GUILD','호이길드','active',1,'⭐',NULL)");await database.execute("INSERT INTO guild_profile_details(guild_id,level_value,experience,territory_booster,join_condition_experience,recruitment_closed,mark_text,server_display_name,tax_rate,charm_value) VALUES(991400001,1,0,0,0,FALSE,'⭐','호1',12.5,200)");await database.execute("INSERT INTO guild_members(guild_id,player_id,role_code,joined_at) VALUES(991400001,991000002,'master',UTC_TIMESTAMP(3))");await database.execute("INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,active,version) VALUES('SYNTHETIC-CASTLE-CHARM','캐슬장식','consumable',TRUE,TRUE,1)");await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT 991000002,id,2,1 FROM item_definitions WHERE code='SYNTHETIC-CASTLE-CHARM'");await database.execute("INSERT INTO castle_battle_item_bonus_definitions(item_id,charm_per_unit,active,version) SELECT id,50,TRUE,1 FROM item_definitions WHERE code='SYNTHETIC-CASTLE-CHARM'");await database.execute("UPDATE castle_state SET lord_guild_name='호이길드',lord_player_id=991000002,tax_rate_basis_points=1250,earnings=5000,version=2 WHERE state_code='HOI_CASTLE'");}
async function probe(){await seed();assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='CASTLE_KINGDOM_STATUS_READ'"))[0]?.rollout_state,"SHADOW");const service=new CastleKingdomStatusReadService(database),success=`${base}-success`;await event(success);const first=await service.handle({eventId:success,externalUserId:viewer,channelId:room,message:"/호월킹덤"});assert.equal(first?.status,"active");assert.match(first!.data,/영주: 👑영주/);assert.match(first!.data,/캐슬 매력: 1,300💕/);assert.match(first!.data,/세율: 12.5%/);assert.deepEqual(await service.handle({eventId:success,externalUserId:viewer,channelId:room,message:"/호월킹덤"}),{...first!,replayed:true});const concurrent=`${base}-concurrent`;await event(concurrent);const pair=await Promise.all([service.handle({eventId:concurrent,externalUserId:viewer,channelId:room,message:"/호월킹덤"}),service.handle({eventId:concurrent,externalUserId:viewer,channelId:room,message:"/호월킹덤"})]);assert.equal(pair[0]?.status,pair[1]?.status);assert.equal(pair[0]?.data,pair[1]?.data);assert.equal(pair[0]?.outboxId,pair[1]?.outboxId);assert.deepEqual(pair.map(result=>result?.replayed).sort(),[false,true]);const noLord=`${base}-no-lord`;await database.execute("UPDATE castle_state SET lord_player_id=NULL,version=version+1 WHERE state_code='HOI_CASTLE'");await event(noLord);assert.equal((await service.handle({eventId:noLord,externalUserId:viewer,channelId:room,message:"/호월킹덤"}))?.status,"no_lord");await database.execute("UPDATE castle_state SET lord_player_id=991000002,version=version+1 WHERE state_code='HOI_CASTLE'");const rollback=`${base}-rollback`;await event(rollback);const before=await effects();await assert.rejects(()=>new CastleKingdomStatusReadService(failAudit(database)).handle({eventId:rollback,externalUserId:viewer,channelId:room,message:"/호월킹덤"}),/synthetic kingdom audit failure/);assert.deepEqual(await effects(),before);assert.equal(await database.verifyRollback(),true);assert.deepEqual((await effects())[0],{operations:3n,outboxes:3n,audits:3n,executions:3n,castle_version:4n,guild_version:1n,pet_experience:1000n});process.stdout.write(JSON.stringify({mode:"probe",migrationCount:276,scenarios:["shadow","exact","consistent-projection","bigint","missing-lord","replay","concurrent-read","rollback"],effects:{operations:3,outboxes:3,audits:3,executions:3},domainMutation:false,repairMutation:false})+"\n");}
async function restart(){const before=await effects(),result=await new CastleKingdomStatusReadService(database).handle({eventId:`${base}-success`,externalUserId:viewer,channelId:room,message:"/호월킹덤"});assert.equal(result?.replayed,true);assert.deepEqual(await effects(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",replayStable:true,additionalMutation:false,domainMutation:false})+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await database.close();}
