import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { CarrotTradeService } from "../src/market/carrot-trade-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_market_carrot_trade(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic carrot-trade probe blocked: ${config.database.name}`);
const db=createDatabaseClient(config.database),sender=997100001n,recipient=997100002n,lowTier=997100003n,room="synthetic-carrot-trade",senderUser="carrot-trade-sender";
let targetItem=0n,bannedItem=0n,carrotItem=0n,thermometerItem=0n;
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,senderUser]);}
async function run(id:string,message:string){await event(id);return new CarrotTradeService(db).handle({eventId:id,externalUserId:senderUser,destinationId:room,message});}
function failedAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("carrot trade audit failure");return t.execute(s,p);}}))};}
async function itemId(code:string){return(await db.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code=?",[code]))[0]!.id;}
async function state(){return(await db.query<Array<{trades:bigint;ops:bigint;audits:bigint;outboxes:bigint;sender_item:bigint;sender_carrot:bigint;recipient_item:bigint;recipient_thermometer:bigint;counter_value:bigint}>>(`SELECT
 (SELECT COUNT(*) FROM market_carrot_trade_events) trades,
 (SELECT COUNT(*) FROM operations WHERE idempotency_scope='market.carrot.trade') ops,
 (SELECT COUNT(*) FROM command_audit audit JOIN operations operation ON operation.id=audit.operation_id WHERE operation.idempotency_scope='market.carrot.trade') audits,
 (SELECT COUNT(*) FROM outbox_messages message JOIN operations operation ON operation.id=message.operation_id WHERE operation.idempotency_scope='market.carrot.trade') outboxes,
 (SELECT quantity FROM inventory_stacks WHERE player_id=997100001 AND item_id=?) sender_item,
 (SELECT quantity FROM inventory_stacks WHERE player_id=997100001 AND item_id=?) sender_carrot,
 (SELECT quantity FROM inventory_stacks WHERE player_id=997100002 AND item_id=?) recipient_item,
 (SELECT quantity FROM inventory_stacks WHERE player_id=997100002 AND item_id=?) recipient_thermometer,
 COALESCE((SELECT value FROM player_counters WHERE player_id=997100001 AND counter_code='carrot_given' AND period_key='lifetime'),0) counter_value`,[targetItem,carrotItem,targetItem,thermometerItem]))[0]!;}
async function seed(){await db.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active'),(?,'active')",[sender,recipient,lowTier]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,tier_code) VALUES (?,'보내는 사람','king'),(?,'받는 사람','king'),(?,'낮은 사람','silver')",[sender,recipient,lowTier]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?, 'kakao',?,'linked')",[sender,sender,senderUser]);await db.execute("INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,active,metadata_json) VALUES ('SYNTHETIC-CARROT-TRADE-ITEM','가방물품','item',TRUE,TRUE,JSON_OBJECT('legacyBagOrder',1)),('SYNTHETIC-CARROT-TRADE-BANNED','금지물품','item',TRUE,TRUE,JSON_OBJECT('legacyBagOrder',2)),('ITEM-RWD-044','당근','item',TRUE,TRUE,JSON_OBJECT('legacyBagOrder',3)),('pet_skill_carrot_thermometer','당근온도기🌡️','item',TRUE,TRUE,JSON_OBJECT('legacyBagOrder',4)) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),active=TRUE,stackable=TRUE");targetItem=await itemId('SYNTHETIC-CARROT-TRADE-ITEM');bannedItem=await itemId('SYNTHETIC-CARROT-TRADE-BANNED');carrotItem=await itemId('ITEM-RWD-044');thermometerItem=await itemId('pet_skill_carrot_thermometer');await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,?,10,1),(?,?,5,1),(?,?,20,1)",[sender,targetItem,sender,bannedItem,sender,carrotItem]);await db.execute("INSERT INTO item_restrictions(restriction_kind,item_code,display_name,source_order,active) VALUES ('carrot_trade','SYNTHETIC-CARROT-TRADE-BANNED','금지물품',9971,TRUE)");}
async function probe(){await seed();assert.equal((await db.query<Array<{state:string}>>("SELECT rollout_state state FROM command_registry WHERE command_code='MARKET_CARROT_TRADE'"))[0]!.state,'SHADOW');const first=await run('carrot-success','/당근 받는 사람 1 3');assert.equal(first?.status,'traded');assert.equal(first?.carrotFee,'3');assert.equal(first?.thermometerReward,'2');assert.equal((await new CarrotTradeService(db).handle({eventId:'carrot-success',externalUserId:senderUser,destinationId:room,message:'/당근 받는 사람 1 3'}))?.replayed,true);
assert.equal((await run('carrot-banned','/당근 받는 사람 2 1'))?.status,'rejected');assert.equal((await run('carrot-low-tier','/당근 낮은 사람 1 1'))?.status,'rejected');await db.execute("UPDATE inventory_stacks SET quantity=0,version=version+1 WHERE player_id=? AND item_id=?",[sender,carrotItem]);assert.equal((await run('carrot-no-fee','/당근 받는 사람 1 1'))?.status,'rejected');await db.execute("UPDATE inventory_stacks SET quantity=10,version=version+1 WHERE player_id=? AND item_id=?",[sender,carrotItem]);assert.equal((await run('carrot-self','/당근 보내는 사람 1 1'))?.status,'rejected');
await event('carrot-rollback');const before=await state();await assert.rejects(()=>new CarrotTradeService(failedAudit(db)).handle({eventId:'carrot-rollback',externalUserId:senderUser,destinationId:room,message:'/당근 받는 사람 1 2'}),/carrot trade audit failure/);assert.deepEqual(await state(),before);assert.equal(await db.verifyRollback(),true);assert.equal((await run('carrot-after-rollback','/당근 받는 사람 1 2'))?.status,'traded');const final=await state();assert.deepEqual([final.trades,final.ops,final.audits,final.outboxes,final.sender_item,final.sender_carrot,final.recipient_item,final.recipient_thermometer,final.counter_value],[2n,6n,6n,6n,5n,8n,5n,4n,2n]);process.stdout.write(JSON.stringify({mode:'probe',latestMigration:366,scenarios:['shadow-registry','spaced-target','stable-bag-index','king-tier','item-restriction','fee-per-unit','thermometer','counter','self-trade','event-replay','rollback','restart'],state:final},(_k,v)=>typeof v==='bigint'?v.toString():v)+'\n');}
async function restart(){targetItem=await itemId('SYNTHETIC-CARROT-TRADE-ITEM');carrotItem=await itemId('ITEM-RWD-044');thermometerItem=await itemId('pet_skill_carrot_thermometer');const current=await state();assert.deepEqual([current.trades,current.ops,current.audits,current.outboxes,current.sender_item,current.sender_carrot,current.recipient_item,current.recipient_thermometer,current.counter_value],[2n,6n,6n,6n,5n,8n,5n,4n,2n]);process.stdout.write(JSON.stringify({mode:'verify-restart',state:current,additionalMutation:false,operationalDataTouched:false},(_k,v)=>typeof v==='bigint'?v.toString():v)+'\n');}
try{if(process.argv.includes('--verify-restart'))await restart();else await probe();}finally{await db.close();}
