import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient } from "../src/database.js";
import { HomeProfileViewService } from "../src/home/home-profile-view-service.js";

const config=loadConfig();if(!config.database.enabled||!/^hoibot_home_profile_view(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic home profile probe blocked: ${config.database.name}`);
const db=createDatabaseClient(config.database),base=process.env.HOME_PROFILE_VIEW_PROBE_EVENT_ID??"home-profile-g7-20260829-r1",eventId=`${base}-visit`,room="synthetic-home-profile-room",restart=process.argv.includes("--verify-restart");
const state=async()=>(await db.query<Array<{visits:bigint;recent:bigint;alerts:bigint;events:bigint;operations:bigint;outboxes:bigint}>>(`SELECT (SELECT visit_count FROM player_homes WHERE player_id=319002) visits,(SELECT COUNT(*) FROM pet_home_recent_visitors WHERE owner_player_id=319002) recent,(SELECT COUNT(*) FROM pet_home_activity_alerts WHERE owner_player_id=319002 AND alert_type='home_visit') alerts,(SELECT COUNT(*) FROM home_profile_visit_events WHERE actor_player_id=319001) events,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='home.profile_view' AND idempotency_key=?) operations,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='home.profile_view' AND operation_row.idempotency_key=?) outboxes`,[eventId,eventId]))[0]!;
try{const service=new HomeProfileViewService(db);if(restart){const before=await state(),replay=await service.execute({eventId,externalUserId:"home-profile-probe-actor",destinationId:room,message:"/펫홈 합성 프로필 대상"});assert.equal(replay.replayed,true);assert.deepEqual(await state(),before);process.stdout.write(JSON.stringify({mode:"restart",scenarios:["actual-restart-replay"],state:before},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}else{await db.execute("INSERT INTO players(id,status,version) VALUES(319001,'active',1),(319002,'active',1)");await db.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES(319001,'합성 프로필 사용자',1),(319002,'합성 프로필 대상',1)");await db.execute("INSERT INTO player_homes(player_id,display_name,version) VALUES(319001,'합성 사용자 집',1),(319002,'합성 대상 집',1)");await db.execute("INSERT INTO player_pets(player_id,display_name,version) VALUES(319001,'합성 사용자 펫',1),(319002,'합성 대상 펫',1)");await db.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES(319001,'support',TRUE,TRUE),(319002,'support',TRUE,TRUE)");await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,display_name,status) VALUES(319001,319001,'kakao','home-profile-probe-actor','합성 프로필 사용자','linked')");await db.execute("INSERT INTO event_inbox(event_id,provider_code,provider_event_id,event_kind,event_origin,direction,payload_hash,parse_status,processing_status,received_at) VALUES(?,'iris',?,'message','synthetic','incoming',REPEAT('5',64),'parsed','processing',UTC_TIMESTAMP(3))",[eventId,eventId]);const result=await service.execute({eventId,externalUserId:"home-profile-probe-actor",destinationId:room,message:"/펫홈 합성 프로필 대상"});assert.equal(result.visitCount,"1");assert.equal(result.messages.length,3);assert.deepEqual(await service.execute({eventId,externalUserId:"home-profile-probe-actor",destinationId:room,message:"/펫홈 합성 프로필 대상"}),{...result,replayed:true});const final=await state();assert.deepEqual(final,{visits:1n,recent:1n,alerts:1n,events:1n,operations:1n,outboxes:3n});process.stdout.write(JSON.stringify({mode:"probe",migrationCount:319,scenarios:["stable-target","atomic-visit","recent-unique","badge-alert","ordered-three-part-outbox","idempotent-replay"],state:final,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}}finally{await db.close();}
