import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient } from "../src/database.js";
import { PetExploreSettlementProvider } from "../src/pet/pet-explore-settlement-provider.js";
import { settlementPlan } from "../test/fixtures/pet-explore-settlement-provider.js";
const config = loadConfig(); if (!config.database.enabled || config.database.name !== "hoibot_pet_explore_settlement_lease2429") throw new Error(`Blocked database: ${config.database.name}`);
let db = createDatabaseClient(config.database); const prefix = `lease2429-${Date.now()}`; const players = [984731001,984731002,984731003];
try {
  await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1),(?,'active',1),(?,'active',1)", players);
  for (const [code,name] of [["ITEM-PET-DUNGEON-TICKET","펫던전 입장권🌋"],["ITEM-AUTO-EXPLORE-TICKET","자동탐험권🌄"],["ITEM-PET-FOOD","펫먹이🍼"]]) { await db.execute("INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,active,version) VALUES (?,?,'item',TRUE,TRUE,1) ON DUPLICATE KEY UPDATE code=VALUES(code)",[code,name]); await db.execute("INSERT INTO package_item_definitions(item_id,item_type,item_name,stackable,metadata_json,enabled) VALUES (?,'STACK',?,TRUE,JSON_OBJECT(),TRUE) ON DUPLICATE KEY UPDATE enabled=TRUE",[code,name]); }
  const current=(await db.execute("INSERT INTO pet_explore_rounds(round_key,state_code,version) VALUES (?,'open',2)",[`${prefix}-current`])).insertId;
  const next=(await db.execute("INSERT INTO pet_explore_rounds(round_key,state_code,version) VALUES (?,'open',1)",[`${prefix}-next`])).insertId;
  const part=(await db.execute("INSERT INTO pet_explore_participations(participation_key,round_id,player_id,destination_code,state_code,version) VALUES (?,?,?,'jeondor_dungeon','active',1)",[`${prefix}-part`,current,players[0]])).insertId;
  await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,1,1 FROM item_definitions WHERE code='ITEM-AUTO-EXPLORE-TICKET'",[players[1]]);
  const input={roundKey:`${prefix}-current`,expectedRoundVersion:"2",source:"scheduler" as const,actorId:String(players[2]),idempotencyKey:`${prefix}-settle`,policyHash:"c".repeat(64),reason:"source transaction Shadow 정산",destinationId:"internal",plans:[settlementPlan(part.toString(),{ticketPolicy:"consume_or_regular_fallback",ticketItemCode:"ITEM-PET-DUNGEON-TICKET",fallbackDestinations:["pet_enhancement_mine","intimacy_mine","luck_mine"]})],nextAutoReservations:[{mode:"auto" as const,roundKey:`${prefix}-next`,playerId:String(players[1]),destinationCode:"luck_mine" as const,expectedRoundVersion:"1",expectedParticipationVersion:null,idempotencyKey:`${prefix}-next-auto`,reason:"Shadow 다음 round 자동 참가",sourceCode:"scheduler" as const}]};
  const result=await new PetExploreSettlementProvider(db).settle(input); assert.equal(result.participants[0]?.fallbackApplied,true); assert.equal(result.nextAutoResults.length,1); assert.equal((await new PetExploreSettlementProvider(db).settle(input)).replayed,true);
  await db.close(); db=createDatabaseClient(config.database); assert.equal((await new PetExploreSettlementProvider(db).settle(input)).replayed,true);
  const state=(await db.query<Array<{roundState:string;ticketLedgers:bigint;autoTicket:string;nextCount:bigint;rewards:bigint;records:bigint;rng:bigint;audits:bigint;outboxes:bigint}>>(`SELECT (SELECT state_code FROM pet_explore_rounds WHERE id=${current.toString()}) roundState,(SELECT COUNT(*) FROM inventory_ledger ledger JOIN item_definitions item ON item.id=ledger.item_id WHERE item.code='ITEM-PET-DUNGEON-TICKET') ticketLedgers,CAST((SELECT quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=${players[1]} AND item.code='ITEM-AUTO-EXPLORE-TICKET') AS CHAR) autoTicket,(SELECT COUNT(*) FROM pet_explore_participations WHERE round_id=${next.toString()}) nextCount,(SELECT COUNT(*) FROM pet_explore_settlement_reward_results) rewards,(SELECT COUNT(*) FROM pet_explore_player_records) records,(SELECT COUNT(*) FROM pet_explore_settlement_rng_evidence) rng,(SELECT COUNT(*) FROM command_audit WHERE action_code='pet_explore.settlement') audits,(SELECT COUNT(*) FROM outbox_messages WHERE message_type='pet_explore.settlement') outboxes`))[0]!;
  assert.deepEqual(state,{roundState:"closed",ticketLedgers:0n,autoTicket:"1",nextCount:1n,rewards:1n,records:1n,rng:2n,audits:1n,outboxes:1n});
  process.stdout.write(JSON.stringify({scenarios:["ticket-shortage-fallback","deterministic-rng","canonical-reward","record","scheduler","next-auto-atomic","exact-replay","reconnect-replay","auto-ticket-read-only","audit-outbox"],state},(_key,value)=>typeof value==="bigint"?value.toString():value)+"\n");
} finally { await db.close(); }
