import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { PendantInfoService } from "../src/pet/pendant-info-service.js";

const config=loadConfig(); if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true."); if(!/^hoibot_pendant_info(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic pendant info probe blocked: ${config.database.name}`);
const base=process.env.PENDANT_INFO_PROBE_EVENT_ID??"pendant-info-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),db=createDatabaseClient(config.database),service=new PendantInfoService(db);
async function event(id:string,user="pendant-info-user"){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-pendant-info-room',?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic pendant info audit failure");return t.execute(s,p);}}))};}
try{
 const bagEvent=`${base}-bag`;
 if(restart){const before=await db.query("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='pendant.info.read') ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='pendant.info.read') outboxes,(SELECT COUNT(*) FROM inventory_instances) instances");await service.handle({eventId:bagEvent,externalUserId:"pendant-info-user",destinationId:"synthetic-pendant-info-room",message:"/펜던트정보 1"});const after=await db.query("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='pendant.info.read') ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='pendant.info.read') outboxes,(SELECT COUNT(*) FROM inventory_instances) instances");assert.deepEqual(after,before);process.stdout.write(JSON.stringify({mode:"verify-restart",operations:5,outboxes:5,instances:3,additionalMutation:false,operationalDataTouched:false})+"\n");}
 else{
  await db.execute("INSERT INTO players(id,status) VALUES (987000001,'active')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (987000001,'정보유저 남')");await db.execute("INSERT INTO external_identities(provider_code,external_user_id,player_id,status) VALUES ('kakao','pendant-info-user',987000001,'linked')");await db.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (987000001,987000001,'정보펫')");await db.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (987000001,'⭐',1)");
  for(const [code,name,grade,status] of [["INFO-EQ","장착","창세","equipped"],["INFO-B1","나","하급","owned"],["INFO-B2","가","창조","owned"]]){await db.execute("INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,metadata_json,active,version) VALUES (?,?,'ITEM',0,JSON_OBJECT('objectType','pendant'),1,1)",[code,name]);await db.execute("INSERT INTO inventory_instances(player_id,item_id,status,attributes_json) SELECT 987000001,id,?,JSON_OBJECT('objectType','pendant','name',?,'icon','💎','grade',?,'durability',4,'maxDurability',5,'upgrade',2) FROM item_definitions WHERE code=?",[status,name,grade,code]);}
  await db.execute("INSERT INTO player_pet_pendants(player_pet_id,inventory_instance_id,display_name,grade_code,grade_display_name,durability,max_durability,enhancement_level,raid_charm,castle_charm,version) SELECT 987000001,id,'장착펜던트','SYNTHETIC','창세',4,5,2,7500000,7500000,1 FROM inventory_instances WHERE player_id=987000001 AND status='equipped'");
  assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='PENDANT_INFO_READ'"))[0]!.rollout_state,"SHADOW");
  const cases=[["usage","/펜던트정보"],["equipped","/펜던트정보 0"],["invalid","/펜던트정보 안내"],["missing","/펜던트정보 9"]] as const;for(const [name,message]of cases){const id=`${base}-${name}`;await event(id);const result=await service.handle({eventId:id,externalUserId:"pendant-info-user",destinationId:"synthetic-pendant-info-room",message});assert.notEqual(result.status,"silent");}
  await event(bagEvent);const bag=await service.handle({eventId:bagEvent,externalUserId:"pendant-info-user",destinationId:"synthetic-pendant-info-room",message:"/펜던트정보 1"});assert.equal(bag.status,"found");assert.match(bag.data!,/가💎\[창조\]/);assert.deepEqual(await service.handle({eventId:bagEvent,externalUserId:"pendant-info-user",destinationId:"synthetic-pendant-info-room",message:"/펜던트정보 1"}),bag);
  const rollback=`${base}-rollback`;await event(rollback);await assert.rejects(()=>new PendantInfoService(failAudit(db)).handle({eventId:rollback,externalUserId:"pendant-info-user",destinationId:"synthetic-pendant-info-room",message:"/펜던트정보 1"}),/synthetic pendant info audit failure/);
  const effects=await db.query<Array<{ops:bigint;outboxes:bigint;audits:bigint;rollbackOps:bigint;instances:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='pendant.info.read') ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='pendant.info.read') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='pendant.info.read') audits,(SELECT COUNT(*) FROM operations WHERE idempotency_key=?) rollbackOps,(SELECT COUNT(*) FROM inventory_instances) instances",[rollback]);assert.deepEqual(effects[0],{ops:5n,outboxes:5n,audits:5n,rollbackOps:0n,instances:3n});assert.equal(await db.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:131,scenarios:["shadow-registry","usage","equipped-zero","stable-bag-index","invalid-usage","not-found","replay","rollback"],effects:{operations:5,outboxes:5,audits:5,instances:3},operationalDataTouched:false})+"\n");
 }
}finally{await db.close();}
