import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { HomeFurnitureSellService } from "../src/home/home-furniture-sell-service.js";

const config=loadConfig();
if(!config.database.enabled||!/^hoibot_home_furniture_sell(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic home furniture sell probe blocked: ${config.database.name}`);
let database=createDatabaseClient(config.database);
const service=()=>new HomeFurnitureSellService(database),base=process.env.HOME_FURNITURE_SELL_PROBE_EVENT_ID??"home-furniture-sell-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),room="synthetic-home-furniture-sell-room";
async function event(suffix:string,user:string){const id=`${base}-${suffix}`;await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('c',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,user]);return id;}
async function state(){return(await database.query<Array<{bag:bigint;placed:bigint;sold:bigint;point:string;furniture_ledgers:bigint;currency_ledgers:bigint;sell_ops:bigint;signature:string}>>("SELECT (SELECT COUNT(*) FROM furniture_inventory_instances WHERE player_id=207001 AND status='bag') bag,(SELECT COUNT(*) FROM furniture_inventory_instances WHERE player_id=207001 AND status='placed') placed,(SELECT COUNT(*) FROM furniture_inventory_instances WHERE player_id=207001 AND status='sold') sold,CAST((SELECT balance FROM currency_accounts WHERE player_id=207001 AND currency_code='point') AS CHAR) point,(SELECT COUNT(*) FROM furniture_inventory_ledger WHERE reason_code='HOME_FURNITURE_SELL') furniture_ledgers,(SELECT COUNT(*) FROM currency_ledger WHERE reason_code='HOME_FURNITURE_SELL_REWARD') currency_ledgers,(SELECT COUNT(*) FROM home_furniture_sell_operations) sell_ops,(SELECT GROUP_CONCAT(CONCAT(id,':',status,':',version) ORDER BY id SEPARATOR '|') FROM furniture_inventory_instances WHERE player_id=207001) signature"))[0]!;}
async function effects(){const pattern=`${base}-%`;return(await database.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='home.furniture_sell' AND idempotency_key LIKE ?) operations,(SELECT COUNT(*) FROM outbox_messages message JOIN operations operation ON operation.id=message.operation_id WHERE operation.idempotency_scope='home.furniture_sell' AND operation.idempotency_key LIKE ?) outboxes,(SELECT COUNT(*) FROM command_audit audit JOIN operations operation ON operation.id=audit.operation_id WHERE operation.idempotency_scope='home.furniture_sell' AND operation.idempotency_key LIKE ?) audits,(SELECT COUNT(*) FROM command_executions WHERE event_id LIKE ?) executions",[pattern,pattern,pattern,pattern]))[0]!;}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(sql,params)=>inner.query(sql,params),execute:(sql,params)=>inner.execute(sql,params),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(transaction:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(transaction=>work({query:(sql,params)=>transaction.query(sql,params),execute:async(sql,params)=>{if(sql.includes("INSERT INTO command_audit"))throw new Error("synthetic furniture sell audit failure");return transaction.execute(sql,params);}}))};}
async function addFurniture(player:number,code:string,name:string,charm:number,status:"bag"|"placed"){const definition=await database.execute("INSERT INTO furniture_definitions(code,display_name,charm_value) VALUES (?,?,?)",[code,name,charm]);return(await database.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status,version) VALUES (?,?,?,'테스트',?,1)",[player,definition.insertId,charm,status])).insertId;}

try{
  const successEvent=`${base}-success`;
  if(restart){
    const before=await state(),beforeEffects=await effects();
    const replay=await service().handle({eventId:successEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 2"});
    assert.equal(replay.status,"sold");assert.equal(replay.rewardPoint,"100000");assert.deepEqual(await state(),before);assert.deepEqual(await effects(),beforeEffects);
    process.stdout.write(JSON.stringify({mode:"restart",scenarios:["restart-replay"],state:before,effects:beforeEffects},(_key,value)=>typeof value==="bigint"?value.toString():value)+"\n");
  }else{
    await database.execute("INSERT INTO players(id,status) VALUES (207001,'active'),(207002,'active')");
    await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (207001,'가구 판매자'),(207002,'빈 가구 사용자')");
    await database.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (207001,207001,'kakao','furniture-seller','linked'),(207002,207002,'kakao','empty-furniture-seller','linked')");
    await database.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES (207001,'point',500,0)");
    const low=await addFurniture(207001,"sell-low","낮은 의자",100,"bag");
    const middle=await addFurniture(207001,"sell-middle","중간 탁자",500,"bag");
    const high=await addFurniture(207001,"sell-high","높은 침대",1000,"bag");
    await addFurniture(207001,"sell-placed","배치 가구",5000,"placed");
    assert.deepEqual((await database.query<Array<{handler_key:string;rollout_state:string;alias_count:bigint}>>("SELECT registry.handler_key,registry.rollout_state,(SELECT COUNT(*) FROM command_aliases alias WHERE alias.command_code=registry.command_code AND alias.command_text='/가구판매' AND alias.active=TRUE) alias_count FROM command_registry registry WHERE registry.command_code='HOME_FURNITURE_SELL'"))[0],{handler_key:"home_furniture_sell",rollout_state:"SHADOW",alias_count:1n});
    const usageEvent=await event("usage","furniture-seller"),usage=await service().handle({eventId:usageEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매"});assert.match(usage.reply,/사용법: \/가구판매 번호/);
    const emptyEvent=await event("empty","empty-furniture-seller"),empty=await service().handle({eventId:emptyEvent,externalUserId:"empty-furniture-seller",destinationId:room,message:"/가구판매 1"});assert.match(empty.reply,/판매 가능한 가구가 없습니다/);
    const missingEvent=await event("missing","furniture-seller"),missing=await service().handle({eventId:missingEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 4"});assert.match(missing.reply,/해당 번호의 가구가 없습니다/);
    const before=await state();await event("success","furniture-seller");const sold=await service().handle({eventId:successEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 2"});assert.equal(sold.status,"sold");assert.equal(sold.furnitureInstanceId,middle.toString());assert.equal(sold.rewardPoint,"100000");assert.match(sold.reply,/중간 탁자\(\+500💕\)/);assert.match(sold.reply,/🅟100,000/);
    const after=await state();assert.deepEqual({bag:after.bag,placed:after.placed,sold:after.sold,point:after.point,furniture_ledgers:after.furniture_ledgers,currency_ledgers:after.currency_ledgers,sell_ops:after.sell_ops},{bag:2n,placed:1n,sold:1n,point:"100500.000",furniture_ledgers:1n,currency_ledgers:1n,sell_ops:1n});assert.notEqual(after.signature,before.signature);assert.equal((await database.query<Array<{id:bigint}>>("SELECT id FROM furniture_inventory_instances WHERE status='sold'"))[0]!.id,middle);assert.ok(low!==high);
    assert.deepEqual(await service().handle({eventId:successEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 2"}),sold);
    const rollbackBefore=await state(),rollbackEffects=await effects(),rollbackEvent=await event("rollback","furniture-seller");await assert.rejects(()=>new HomeFurnitureSellService(failAudit(database)).handle({eventId:rollbackEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 1"}),/synthetic furniture sell audit failure/);assert.deepEqual(await state(),rollbackBefore);assert.deepEqual(await effects(),rollbackEffects);assert.equal(await database.verifyRollback(),true);
    await database.close();database=createDatabaseClient(config.database);assert.deepEqual(await service().handle({eventId:successEvent,externalUserId:"furniture-seller",destinationId:room,message:"/가구판매 2"}),sold);
    process.stdout.write(JSON.stringify({mode:"probe",migrationCount:207,scenarios:["shadow-registry","exact-command","usage-empty-boundaries","stable-bag-order","single-instance-sale","fixed-point-reward","dual-ledger-evidence","idempotent-replay","rollback","restart-replay"],state:await state(),effects:await effects(),operationalDataTouched:false},(_key,value)=>typeof value==="bigint"?value.toString():value)+"\n");
  }
}finally{await database.close();}
