import assert from"node:assert/strict";
import{loadConfig}from"../src/config.js";
import{createDatabaseClient,type DatabaseClient,type DatabaseTransaction}from"../src/database.js";
import{MiniPetDrawGrantService}from"../src/admin/mini-pet-draw-grant-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_pet_mini_grant(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic mini pet draw grant probe blocked: ${config.database.name}`);
const base=process.env.MINI_PET_DRAW_GRANT_PROBE_EVENT_ID??"mini-pet-draw-grant-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),database=createDatabaseClient(config.database),service=new MiniPetDrawGrantService(database),success=`${base}-success`;
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-mini-pet-draw-room','grant-master','message','incoming',REPEAT('5',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(sql,parameters)=>inner.query(sql,parameters),execute:(sql,parameters)=>inner.execute(sql,parameters),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(transaction:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(transaction=>work({query:(sql,parameters)=>transaction.query(sql,parameters),execute:async(sql,parameters)=>{if(sql.includes("INSERT INTO command_audit"))throw new Error("synthetic mini pet draw audit failure");return transaction.execute(sql,parameters);}}))};}
async function snapshot(){return(await database.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;stacks:string;ledgers:bigint}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='admin.mini_pet_draw.grant') operations,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_scope='admin.mini_pet_draw.grant') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='inventory.mini_pet_draw.grant') audits,(SELECT CAST(COALESCE(SUM(stack.quantity),0) AS CHAR) FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE item.code='mini_pet_draw') stacks,(SELECT COUNT(*) FROM inventory_ledger ledger JOIN operations operation_row ON operation_row.id=ledger.operation_id WHERE operation_row.idempotency_scope='admin.mini_pet_draw.grant') ledgers`))[0]!;}
try{const expected={operations:4n,outboxes:4n,audits:4n,stacks:"8",ledgers:2n};if(restart){const before=await snapshot();await service.grant({eventId:success,destinationId:"synthetic-mini-pet-draw-room",operatorId:"998300001",message:"/펫미니7, 대상 회원"});assert.deepEqual(await snapshot(),before);assert.deepEqual(before,expected);process.stdout.write(JSON.stringify({mode:"verify-restart",operations:4,quantity:8,additionalMutation:false,operationalDataTouched:false})+"\n");}else{await database.execute("INSERT INTO players(id,status) VALUES (988300001,'active')");await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (988300001,'대상 회원')");assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='ADMIN_MINI_PET_DRAW_GRANT'"))[0]!.rollout_state,"SHADOW");for(const[id,message]of[[success,"/펫미니7, 대상 회원"],[`${base}-default`,"/펫미니, 대상 회원"],[`${base}-zero`,"/펫미니0, 대상 회원"],[`${base}-missing`,"/펫미니2, 없는 회원"]]as const){await event(id);await service.grant({eventId:id,destinationId:"synthetic-mini-pet-draw-room",operatorId:"998300001",message});}const prior=await service.grant({eventId:success,destinationId:"synthetic-mini-pet-draw-room",operatorId:"998300001",message:"/펫미니7, 대상 회원"});assert.deepEqual(await service.grant({eventId:success,destinationId:"synthetic-mini-pet-draw-room",operatorId:"998300001",message:"/펫미니7, 대상 회원"}),prior);const rollback=`${base}-rollback`;await event(rollback);await assert.rejects(()=>new MiniPetDrawGrantService(failAudit(database)).grant({eventId:rollback,destinationId:"synthetic-mini-pet-draw-room",operatorId:"998300001",message:"/펫미니2, 대상 회원"}),/synthetic mini pet draw audit failure/);assert.deepEqual(await snapshot(),expected);assert.equal(await database.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",scenarios:["shadow-registry","legacy-default","explicit-quantity","zero","missing-target","shared-stack-provider","replay","rollback"],effects:{operations:4,outboxes:4,audits:4,quantity:8,ledgers:2},operationalDataTouched:false})+"\n");}}finally{await database.close();}
