import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetDuelResetGrantService } from "../src/admin/mini-pet-duel-reset-grant-service.js";

const config=loadConfig();
if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");
if(!/^hoibot_mini_pet_duel_reset(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic mini pet duel reset probe blocked: ${config.database.name}`);
const base=process.env.MINI_PET_DUEL_RESET_PROBE_EVENT_ID??"mini-pet-duel-reset-g7-20260826-r1",restart=process.argv.includes("--verify-restart"),database=createDatabaseClient(config.database),service=new MiniPetDuelResetGrantService(database),success=`${base}-success`;
async function event(id:string,user:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-mini-pet-duel-room',?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic mini pet duel reset audit failure");return t.execute(s,p);}}))};}
async function snapshot(){return database.query<Array<{ops:bigint;outboxes:bigint;audits:bigint;stacks:string;ledgers:bigint}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='admin.mini_pet_duel_reset.grant') ops,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='admin.mini_pet_duel_reset.grant') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='inventory.mini_pet_duel_reset.grant') audits,(SELECT CAST(COALESCE(SUM(s.quantity),0) AS CHAR) FROM inventory_stacks s JOIN item_definitions d ON d.id=s.item_id WHERE d.code='ITEM-MINI-PET-DUEL-RESET-TICKET') stacks,(SELECT COUNT(*) FROM inventory_ledger l JOIN operations p ON p.id=l.operation_id WHERE p.idempotency_scope='admin.mini_pet_duel_reset.grant') ledgers`);}
try{const expected={ops:4n,outboxes:4n,audits:4n,stacks:"4",ledgers:2n};if(restart){const before=(await snapshot())[0]!;await service.grant({eventId:success,destinationId:"synthetic-mini-pet-duel-room",operatorId:"998100001",message:"/대전3, 대상 회원"});assert.deepEqual((await snapshot())[0],before);assert.deepEqual(before,expected);process.stdout.write(JSON.stringify({mode:"verify-restart",operations:4,quantity:4,additionalMutation:false,operationalDataTouched:false})+"\n");}else{for(const[id,name]of[[988100001,"대상 회원"],[988100002,"다른 회원"]]as const){await database.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[id,name]);}assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='ADMIN_MINI_PET_DUEL_RESET_GRANT'"))[0]!.rollout_state,"SHADOW");for(const[id,message]of[[success,"/대전3, 대상 회원"],[`${base}-default`,"/대전, 대상 회원"],[`${base}-zero`,"/대전0, 대상 회원"],[`${base}-missing`,"/대전2, 없는 회원"]]as const){await event(id,"grant-master");await service.grant({eventId:id,destinationId:"synthetic-mini-pet-duel-room",operatorId:"998100001",message});}assert.deepEqual(await service.grant({eventId:success,destinationId:"synthetic-mini-pet-duel-room",operatorId:"998100001",message:"/대전3, 대상 회원"}),await service.grant({eventId:success,destinationId:"synthetic-mini-pet-duel-room",operatorId:"998100001",message:"/대전3, 대상 회원"}));const rollback=`${base}-rollback`;await event(rollback,"grant-master");await assert.rejects(()=>new MiniPetDuelResetGrantService(failAudit(database)).grant({eventId:rollback,destinationId:"synthetic-mini-pet-duel-room",operatorId:"998100001",message:"/대전2, 대상 회원"}),/synthetic mini pet duel reset audit failure/);assert.deepEqual((await snapshot())[0],expected);assert.equal(await database.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:137,scenarios:["shadow-registry","legacy-default","explicit-quantity","zero","missing-target","stack-ledger","replay","rollback"],effects:{operations:4,outboxes:4,audits:4,quantity:4,ledgers:2},operationalDataTouched:false})+"\n");}}finally{await database.close();}
