import assert from "node:assert/strict";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient,type DatabaseClient,type DatabaseTransaction} from "../src/database.js";
import {CarrotBoardReadService} from "../src/market/carrot-board-read-service.js";
const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_carrot_board_read(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic carrot board probe blocked: ${config.database.name}`);
const db=createDatabaseClient(config.database),user="carrot-board-viewer",room="synthetic-carrot-board-room",base="carrot-board-g7-20260828-r1";
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic carrot board audit failure");return t.execute(s,p);}}))};}
async function counts(){return db.query<Array<{posts:bigint;operations:bigint;executions:bigint;outboxes:bigint;audits:bigint}>>(`SELECT (SELECT COUNT(*) FROM carrot_board_posts) posts,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='market.carrot_board.read') operations,(SELECT COUNT(*) FROM command_executions WHERE command_code='MARKET_CARROT_BOARD_READ') executions,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='market.carrot_board.read') outboxes,(SELECT COUNT(*) FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope='market.carrot_board.read') audits`);}
async function restart(){const c=(await counts())[0]!;assert.deepEqual({posts:c.posts,operations:c.operations},{posts:6n,operations:2n});process.stdout.write(JSON.stringify({mode:"verify-restart",posts:6,operations:2,additionalMutation:false,operationalDataTouched:false})+"\n");}
async function probe(){await db.execute("INSERT INTO players(id,status) VALUES(993000001,'active'),(993000002,'active'),(993000003,'inactive')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(993000001,'조회자'),(993000002,'작성자'),(993000003,'탈퇴자')");await db.execute("INSERT INTO external_identities(id,provider_code,external_user_id,player_id,status) VALUES(993200001,'kakao',?,993000001,'linked')",[user]);await db.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES(993000002,'👑',1),(993000003,'🌙',2)");
 await db.execute("INSERT INTO carrot_board_posts(id,author_player_id,author_name_snapshot,body,legacy_date,source_order,status) VALUES(993500001,993000002,'작성자','첫 글','20260821',1,'published'),(993500002,993000003,'탈퇴자','둘째 글','20260822',2,'published'),(993500003,993000002,'작성자','셋째 글','20260823',3,'published'),(993500004,993000002,'작성자','넷째 글','20260824',4,'published'),(993500005,993000002,'작성자','다섯째 글','20260825',5,'published'),(993500006,993000002,'작성자','여섯째 글','20260826',6,'published')");assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MARKET_CARROT_BOARD_READ'"))[0]!.rollout_state,"SHADOW");const service=new CarrotBoardReadService(db);
 const id=`${base}-primary`;await event(id);const first=await service.read({eventId:id,externalUserId:user,destinationId:room});assert.equal(first?.count,6);assert.deepEqual(first?.postIds,["993500001","993500002","993500003","993500004","993500005","993500006"]);assert.equal((first!.data.match(/\u200b/g)||[]).length,500);assert.match(first!.data,/👑작성자/);assert.doesNotMatch(first!.data,/🌙탈퇴자/);const before=await counts();assert.deepEqual(await service.read({eventId:id,externalUserId:user,destinationId:room}),first);assert.deepEqual(await counts(),before);
 const concurrentId=`${base}-concurrent`;await event(concurrentId);const pair=await Promise.all([service.read({eventId:concurrentId,externalUserId:user,destinationId:room}),service.read({eventId:concurrentId,externalUserId:user,destinationId:room})]);assert.deepEqual(pair[0],pair[1]);const rollbackId=`${base}-rollback`;await event(rollbackId);const beforeRollback=await counts();await assert.rejects(()=>new CarrotBoardReadService(failAudit(db)).read({eventId:rollbackId,externalUserId:user,destinationId:room}),/synthetic carrot board audit failure/);assert.deepEqual(await counts(),beforeRollback);assert.equal(await db.verifyRollback(),true);const c=(await counts())[0]!;assert.deepEqual({operations:c.operations,executions:c.executions,outboxes:c.outboxes,audits:c.audits},{operations:2n,executions:2n,outboxes:2n,audits:2n});process.stdout.write(JSON.stringify({mode:"probe",migrationCount:247,scenarios:["shadow","exact","order","rank","inactive-author","allsee-500","replay","concurrent-read","redacted-audit","rollback"],effects:{operations:2,executions:2,outboxes:2,audits:2},posts:6,operationalDataTouched:false})+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
