import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { PetSkillBulkGrantService } from "../src/pet/pet-skill-bulk-grant-service.js";
const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true");if(!/^hoibot_pet_skill_bulk_grant/i.test(config.database.name))throw new Error(`blocked: isolated pet skill bulk grant database required: ${config.database.name}`);let database=createDatabaseClient(config.database);const service=()=>new PetSkillBulkGrantService(database),destinationId="pet-skill-bulk-grant-room",bulkEvent="pet-skill-bulk-grant-g7-bulk";
async function addEvent(eventId:string,user:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,destinationId,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(sql,params)=>inner.query(sql,params),execute:(sql,params)=>inner.execute(sql,params),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(transaction:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(transaction=>work({query:(sql,params)=>transaction.query(sql,params),execute:async(sql,params)=>{if(sql.includes("INSERT INTO command_audit"))throw new Error("forced pet skill grant rollback");return transaction.execute(sql,params);}}))};}
async function snapshot(){return(await database.query<Array<{operations:bigint;line_count:bigint;inventory:string;ledgers:bigint;audits:bigint;outbox:bigint}>>(`SELECT (SELECT COUNT(*) FROM pet_skill_bulk_grant_operations) operations,(SELECT COUNT(*) FROM pet_skill_bulk_grant_lines) line_count,(SELECT COALESCE(SUM(quantity),0) FROM pet_skill_inventory WHERE player_pet_id IN (989400003,989400004)) inventory,(SELECT COUNT(*) FROM pet_skill_inventory_ledger WHERE reason_code='PET_SKILL_ADMIN_GRANT') ledgers,(SELECT COUNT(*) FROM command_audit WHERE action_code='pet.skill.bulk_grant') audits,(SELECT COUNT(*) FROM outbox_messages WHERE operation_id IN (SELECT operation_id FROM pet_skill_bulk_grant_operations)) outbox`))[0]!;}
try{
  for(const[id,external,name]of[[989400001,"pet-skill-grant-master","지급 마스터"],[989400002,"pet-skill-grant-manager","지급 매니저"],[989400003,"pet-skill-grant-target-a","대상 가"],[989400004,"pet-skill-grant-target-b","대상 나"]]as const){await database.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[id,name]);await database.execute("INSERT INTO external_identities(provider_code,external_user_id,player_id,status) VALUES ('kakao',?,?,'linked')",[external,id]);await database.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (?,?,?)",[id,id,`${name}의 펫`]);}
  for(const[id,login,external,role]of[[999400001,"pet-skill-grant-master","pet-skill-grant-master","super_admin"],[999400002,"pet-skill-grant-manager","pet-skill-grant-manager","manager"]]as const){await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,?,?,'synthetic','active')",[id,login,login]);await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT ?,id FROM external_identities WHERE external_user_id=?",[id,external]);await database.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code=?",[id,role]);}
  await database.execute("INSERT INTO skill_definitions(code,display_name,rules_json,active) VALUES ('probe-bulk-grant-alpha','알파 지급📙',JSON_OBJECT('grade','S'),TRUE),('probe-bulk-grant-beta','베타 지급📙',JSON_OBJECT('grade','A'),TRUE)");
  assert.deepEqual((await database.query<Array<{command_code:string;rollout_state:string}>>("SELECT command_code,rollout_state FROM command_registry WHERE handler_key='pet_skill_bulk_grant' ORDER BY command_code")).map(row=>[row.command_code,row.rollout_state]),[["PET_SKILL_BAG_GRANT","SHADOW"],["PET_SKILL_BULK_GRANT","SHADOW"]]);
  await addEvent(bulkEvent,"pet-skill-grant-master");const bulkMessage="/펫스킬일괄지급\n대상 가, 알파 지급 2\n없는 대상, 알파 지급 1\n대상 가, 없는 스킬 1\n대상 가, 베타 지급 99\n대상 나, 베타 지급 3\n형식 오류";const bulk=await service().handle({eventId:bulkEvent,externalUserId:"pet-skill-grant-master",destinationId,message:bulkMessage});assert.equal(bulk.status,"completed");assert.equal(bulk.successCount,2);assert.equal(bulk.failureCount,4);assert.match(bulk.reply!,/✅ 성공: 2건/);assert.match(bulk.reply!,/❌ 실패: 4건/);assert.deepEqual(await service().handle({eventId:bulkEvent,externalUserId:"pet-skill-grant-master",destinationId,message:bulkMessage}),bulk);
  const singleEvent="pet-skill-bulk-grant-g7-single";await addEvent(singleEvent,"pet-skill-grant-master");const single=await service().handle({eventId:singleEvent,externalUserId:"pet-skill-grant-master",destinationId,message:"/펫스킬가방추가 대상 가, 베타 지급 1"});assert.equal(single.status,"completed");assert.match(single.reply!,/펫스킬가방 추가 완료/);
  const deniedEvent="pet-skill-bulk-grant-g7-denied";await addEvent(deniedEvent,"pet-skill-grant-manager");assert.equal((await service().handle({eventId:deniedEvent,externalUserId:"pet-skill-grant-manager",destinationId,message:"/펫스킬가방추가 대상 가, 알파 지급 1"})).status,"silent");
  const beforeRollback=await snapshot(),rollbackEvent="pet-skill-bulk-grant-g7-rollback";await addEvent(rollbackEvent,"pet-skill-grant-master");await assert.rejects(new PetSkillBulkGrantService(failAudit(database)).handle({eventId:rollbackEvent,externalUserId:"pet-skill-grant-master",destinationId,message:"/펫스킬가방추가 대상 나, 알파 지급 1"}),/forced pet skill grant rollback/);assert.deepEqual(await snapshot(),beforeRollback);assert.equal(await database.verifyRollback(),true);
  await database.close();database=createDatabaseClient(config.database);assert.deepEqual(await service().handle({eventId:bulkEvent,externalUserId:"pet-skill-grant-master",destinationId,message:bulkMessage}),bulk);const finalState=await snapshot();assert.deepEqual(finalState,{operations:2n,line_count:7n,inventory:"6",ledgers:3n,audits:2n,outbox:2n});process.stdout.write(JSON.stringify({scenarios:["shadow-registry","super-admin-only","single-grant","bulk-partial-result","capacity","skill-key-normalization","idempotent-replay","forced-audit-rollback","restart-replay"],state:finalState},(_key,value)=>typeof value==="bigint"?value.toString():value)+"\n");
}finally{await database.close();}
