import assert from "node:assert/strict";
import{loadConfig}from"../src/config.js";import{createDatabaseClient}from"../src/database.js";import{IrisAdminCommandService}from"../src/admin/iris-admin-command-service.js";import{MariaCommandDispatchRepository}from"../src/dispatch/command-dispatcher.js";import{TrialTowerSeasonResetService}from"../src/trial/trial-tower-season-reset-service.js";
const config=loadConfig();if(!config.database.enabled||!/^hoibot_trial_tower_reset(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Blocked database: ${config.database.name}`);
const db=createDatabaseClient(config.database),base=process.env.TRIAL_TOWER_RESET_EVENT_ID??"trial-tower-reset-g7-r1",external="synthetic-trial-reset-owner",room="synthetic-reset-room",restart=process.argv.includes("--verify-restart");
try{let operatorId:bigint;
 if(!restart){const operator=await db.execute("INSERT INTO admin_operators(login_id,display_name,password_hash,status) VALUES (?,'호이 남','synthetic','active')",[`trial-reset-${base}`]);operatorId=operator.insertId;const identityPlayer=await db.execute("INSERT INTO players(status) VALUES ('active')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'호이 남')",[identityPlayer.insertId]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'호이 남','linked')",[identityPlayer.insertId,external]);const identity=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE external_user_id=?",[external]))[0]!;await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operatorId,identity.id]);await db.execute("INSERT INTO trial_tower_seasons(season_key,active) VALUES ('old',0)");for(const [season,floor]of[["current",12],["old",8]] as const){const player=await db.execute("INSERT INTO players(status) VALUES ('active')");await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[player.insertId,`reset-${season}`]);await db.execute("INSERT INTO trial_tower_progress(season_key,player_id,floor) VALUES (?,?,?)",[season,player.insertId,floor]);}for(const event of["shadow","active"])await db.execute("INSERT INTO event_inbox(event_id,event_kind,processing_status,received_at,provider_code,provider_event_id,external_channel_id,external_user_id,event_origin,direction,payload_hash,parse_status) VALUES (?,'message','processed',UTC_TIMESTAMP(3),'iris',?,?,?,'kakao','incoming',SHA2(?,256),'parsed')",[`${base}-${event}`,`${base}-${event}`,room,external,`${base}-${event}`]);}
 else operatorId=(await db.query<Array<{id:bigint}>>("SELECT id FROM admin_operators WHERE login_id=?",[`trial-reset-${base}`]))[0]!.id;
 const dispatch=new MariaCommandDispatchRepository(db);assert.equal((await dispatch.findExact("/시련의탑시즌초기화"))?.handlerKey,"trial_tower_season_reset");assert.equal(await dispatch.findExact("/시련의탑시즌초기화 해봐"),undefined);const input={idempotencyKey:`${base}-active`,sourceEventId:`${base}-active`,operatorId:operatorId.toString(),destinationId:room};let result;
 if(!restart){const admin=new IrisAdminCommandService(db),shadow=await admin.changePlayerPoint({externalUserId:external,channelId:room,message:"/시련의탑시즌초기화",eventId:`${base}-shadow`});assert.equal(shadow.status,"shadow");assert.equal(Number((await db.query<Array<{count:bigint}>>("SELECT COUNT(*) count FROM trial_tower_progress"))[0]!.count),2);await db.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='ADMIN_TRIAL_TOWER_SEASON_RESET'");result=await admin.changePlayerPoint({externalUserId:external,channelId:room,message:"/시련의탑시즌초기화",eventId:input.sourceEventId});assert.equal(result.status,"changed");}
 else result=await new TrialTowerSeasonResetService(db).reset(input);
 const replay=await new TrialTowerSeasonResetService(db).reset(input);assert.equal(replay.outboxId,result.outboxId);const counts=(await db.query<Array<{operations:bigint;snapshots:bigint;progress:bigint;outboxes:bigint;audits:bigint;executions:bigint;routes:bigint}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_key=?) operations,(SELECT COUNT(*) FROM trial_tower_reset_snapshots s JOIN operations o ON o.id=s.operation_id WHERE o.idempotency_key=?) snapshots,(SELECT COUNT(*) FROM trial_tower_progress) progress,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_key=?) outboxes,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_key=?) audits,(SELECT COUNT(*) FROM command_executions WHERE event_id=?) executions,(SELECT COUNT(*) FROM command_routing_decisions WHERE event_id IN (?,?)) routes`,[input.idempotencyKey,input.idempotencyKey,input.idempotencyKey,input.idempotencyKey,input.sourceEventId,`${base}-shadow`,input.sourceEventId]))[0]!;assert.deepEqual(Object.values(counts).map(Number),[1,2,0,1,1,1,2]);assert.equal(await db.verifyRollback(),true);console.log(JSON.stringify({mode:restart?"restart":"probe",counts},(_k,v)=>typeof v==="bigint"?v.toString():v));
}finally{await db.close();}
