import assert from "node:assert/strict";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient,type DatabaseClient,type DatabaseTransaction} from "../src/database.js";
import {SpiritRankService} from "../src/pet/spirit-rank-service.js";
const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_spirit_rank(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic spirit rank probe blocked: ${config.database.name}`);
const base=process.env.SPIRIT_RANK_PROBE_EVENT_ID??"spirit-rank-g7-20260827-r1",restart=process.argv.includes("--verify-restart"),db=createDatabaseClient(config.database),service=new SpiritRankService(db);
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-spirit-rank-room','rank-viewer','message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic spirit rank audit failure");return t.execute(s,p);}}))};}
try{const success=`${base}-success`;if(restart){const before=await db.query<Array<{ops:bigint;outboxes:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='spirit.rank_read' AND idempotency_key=?) ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_key=?) outboxes",[success,success]);await service.read({eventId:success,externalUserId:"rank-viewer",destinationId:"synthetic-spirit-rank-room"});const after=await db.query<Array<{ops:bigint;outboxes:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='spirit.rank_read' AND idempotency_key=?) ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_key=?) outboxes",[success,success]);assert.deepEqual(after,before);assert.deepEqual(after[0],{ops:1n,outboxes:1n});process.stdout.write(JSON.stringify({mode:"verify-restart",operationCount:1,outboxCount:1,additionalMutation:false,operationalDataTouched:false})+"\n");}else{
for(let i=1;i<=12;i++){const id=983000000+i;await db.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,?)",[id,`순위유저${i}`]);await db.execute("INSERT INTO player_pets(id,player_id,display_name) VALUES (?,?, '합성정령펫')",[id,id]);await db.execute("INSERT INTO player_pet_elementals(player_pet_id,display_name,grade_code,grade_display_name,enhancement_level) VALUES (?,?,'ELEMENTAL-GRADE-002','최하급',?)",[id,`합성정령${i}`,i===1||i===2?5:17-i]);await db.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (?,'⭐',?)",[id,i===1?2:i===2?1:i]);}
assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='SPIRIT_RANK_READ'"))[0]!.rollout_state,"SHADOW");await event(success);const result=await service.read({eventId:success,externalUserId:"rank-viewer",destinationId:"synthetic-spirit-rank-room"});assert.equal(result.rowCount,12);assert.ok(result.data.indexOf("⭐순위유저2 -")<result.data.indexOf("⭐순위유저1 -"));const replay=await service.read({eventId:success,externalUserId:"rank-viewer",destinationId:"synthetic-spirit-rank-room"});assert.deepEqual(replay,result);const rollback=`${base}-rollback`;await event(rollback);await assert.rejects(()=>new SpiritRankService(failAudit(db)).read({eventId:rollback,externalUserId:"rank-viewer",destinationId:"synthetic-spirit-rank-room"}),/synthetic spirit rank audit failure/);const effects=await db.query<Array<{ops:bigint;outboxes:bigint;rollbackOps:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_key=?) ops,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation_row ON operation_row.id=outbox.operation_id WHERE operation_row.idempotency_key=?) outboxes,(SELECT COUNT(*) FROM operations WHERE idempotency_key=?) rollbackOps",[success,success,rollback]);assert.deepEqual(effects[0],{ops:1n,outboxes:1n,rollbackOps:0n});assert.equal(await db.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:113,scenarios:["shadow-registry","score-order","tie-source-order","allsee","replay","rollback"],effects:{rows:12,operation:1,outbox:1,rollbackOperation:0},operationalDataTouched:false})+"\n");}}
finally{await db.close();}
