import assert from "node:assert/strict";
import { createDatabaseClient } from "../src/database.js";
import { PunchActionService } from "../src/battle/punch-action-service.js";

const required=(name:string):string=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;};
const db=createDatabaseClient({enabled:true,host:required("DATABASE_HOST"),port:Number(required("DATABASE_PORT")),user:required("DATABASE_USER"),password:process.env.DATABASE_PASSWORD??"",name:required("DATABASE_NAME"),connectionLimit:8,connectTimeoutMs:5000});
const run=required("PUNCH_ACTION_PROBE_RUN_ID"),restart=process.argv.includes("--verify-restart"),player=BigInt(required("PUNCH_ACTION_PROBE_PLAYER_ID")),identity=player+1n,room=`punch-action-room-${run}`,external=`punch-action-user-${run}`,base=`punch-action-${run}`;
const service=new PunchActionService(db,{tierRandom:()=>0,scoreRandom:()=>0});

// command execution FK를 갖춘 합성 incoming event를 준비합니다.
async function event(id:string,user=external):Promise<void>{await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
// 핵꿀밤·포인트·보상 stack을 시나리오 값으로 재설정합니다.
async function resources(ticket:bigint,point:bigint):Promise<void>{await db.execute("INSERT INTO currency_accounts(player_id,currency_code,balance,version) VALUES (?,'point',?,1) ON DUPLICATE KEY UPDATE balance=VALUES(balance),version=currency_accounts.version+1",[player,point]);for(const [code,quantity] of [["punch_ticket",ticket],["mini_pet_draw",0n]] as const)await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) SELECT ?,id,?,1 FROM item_definitions WHERE code=? ON DUPLICATE KEY UPDATE quantity=VALUES(quantity),version=inventory_stacks.version+1",[player,quantity,code]);}
// 현재 합성 player의 펀치 자원·증거 수를 조회합니다.
async function snapshot():Promise<Record<string,bigint|string>>{return(await db.query<Array<Record<string,bigint|string>>>(`SELECT (SELECT quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='punch_ticket') tickets,(SELECT quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='mini_pet_draw') rewards,(SELECT CAST(balance AS CHAR) FROM currency_accounts WHERE player_id=? AND currency_code='point') points,(SELECT COUNT(*) FROM punch_action_runs WHERE player_id=? AND request_key LIKE ?) runs,(SELECT COUNT(*) FROM punch_action_rounds round_row JOIN punch_action_runs run_row ON run_row.operation_id=round_row.operation_id WHERE run_row.player_id=? AND run_row.request_key LIKE ?) rounds,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope=? OR operation.idempotency_scope LIKE ?) outboxes,(SELECT COUNT(*) FROM command_audit audit JOIN operations operation ON operation.id=audit.operation_id WHERE operation.idempotency_scope=? OR operation.idempotency_scope LIKE ?) audits`,[player,player,player,player,`${base}%`,player,`${base}%`,SCOPE(),`${SCOPE()}%`,SCOPE(),`${SCOPE()}%`]))[0]!;}
function SCOPE():string{return `punch.action:${player}`;}

try{
 if(restart){const before=await snapshot();for(const id of [`${base}-normal`,`${base}-concurrent`])await service.execute({eventId:id,externalUserId:external,channelId:room,message:"/펀치 4"});assert.deepEqual(await snapshot(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",additionalMutation:false,counts:before,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v)+"\n");}
 else{
  await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1) ON DUPLICATE KEY UPDATE status='active'",[player]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,version) VALUES (?,CONCAT('합성 펀치 ',?),1) ON DUPLICATE KEY UPDATE current_display_name=VALUES(current_display_name)",[player,run]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?,'kakao',?,'linked') ON DUPLICATE KEY UPDATE player_id=VALUES(player_id),external_user_id=VALUES(external_user_id),status='linked'",[identity,player,external]);
  await db.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=TRUE WHERE command_code='PUNCH_ACTION'");await event(`${base}-shadow`);assert.deepEqual(await service.handleIris({eventId:`${base}-shadow`,externalUserId:external,channelId:room,message:"/펀치"}),{status:"shadow"});await db.execute("UPDATE command_registry SET rollout_state='ACTIVE',enabled=TRUE WHERE command_code='PUNCH_ACTION'");assert.deepEqual(await service.handleIris({eventId:`${base}-auth`,externalUserId:`missing-${run}`,channelId:room,message:"/펀치"}),{status:"handled_no_reply"});
  await resources(3n,1000000n);await event(`${base}-normal`);const normal=await service.execute({eventId:`${base}-normal`,externalUserId:external,channelId:room,message:"/펀치 5"});assert.equal(normal.executedCount,"3");assert.equal(normal.rewardQuantity,"9");assert.equal(normal.pointBalanceAfter,"700000");assert.deepEqual(await service.execute({eventId:`${base}-normal`,externalUserId:external,channelId:room,message:"/펀치 5"}),normal);
  await resources(2n,199999n);await event(`${base}-point`);const point=await service.execute({eventId:`${base}-point`,externalUserId:external,channelId:room,message:"/펀치 2"});assert.equal(point.reasonCode,"point_required");assert.equal((await snapshot()).tickets,2n);
  await resources(1n,100000n);await event(`${base}-legend`);const legend=await new PunchActionService(db,{tierRandom:()=>0.9995,scoreRandom:()=>0.5}).execute({eventId:`${base}-legend`,externalUserId:external,channelId:room,message:"/펀치"});assert.equal(legend.bestScore,"2000");assert.equal(legend.rewardQuantity,"1000");assert.equal(legend.titleGranted,true);
  await resources(120n,10000000n);await event(`${base}-bulk`);const bulk=await service.execute({eventId:`${base}-bulk`,externalUserId:external,channelId:room,message:"/펀치 999"});assert.equal(bulk.executedCount,"100");assert.equal(bulk.rewardQuantity,"300");
  await resources(2n,200000n);await event(`${base}-rollback`);const rollbackBefore=await snapshot();await db.execute("CREATE TRIGGER fail_punch_action_audit BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='punch.action' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced punch action audit failure'; END IF; END");try{await assert.rejects(()=>service.execute({eventId:`${base}-rollback`,externalUserId:external,channelId:room,message:"/펀치 2"}),/forced punch action audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_punch_action_audit");}assert.deepEqual(await snapshot(),rollbackBefore);
  await resources(4n,400000n);await event(`${base}-concurrent`);const concurrent=await Promise.all([1,2,3,4].map(()=>service.execute({eventId:`${base}-concurrent`,externalUserId:external,channelId:room,message:"/펀치 4"})));concurrent.forEach((value)=>assert.deepEqual(value,concurrent[0]));assert.equal(concurrent[0]!.executedCount,"4");const final=await snapshot();process.stdout.write(JSON.stringify({mode:"probe",migrationCount:Number((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM schema_migrations"))[0]!.count_value),scenarios:["shadow","auth","trimmed-boundary","ticket-clamp","point-all-reject","legend-2000","title-first-only","bulk-100","four-way-concurrency","rollback","replay","restart-ready"],normal:{requested:5,executed:3,reward:9,pointAfter:700000},legend:{storedScore:2000,publicScore:1000,reward:1000,titleGranted:true},bulk:{requested:999,executed:100,reward:300},concurrent:{callers:4,executedOnce:4},counts:final,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v)+"\n");
 }
}finally{await db.execute("UPDATE command_registry SET rollout_state='SHADOW' WHERE command_code='PUNCH_ACTION'");await db.close();}
