import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient, type DatabaseClient, type DatabaseTransaction } from "../src/database.js";
import { PetRebirthService } from "../src/pet/pet-rebirth-service.js";

const config=loadConfig();if(!config.database.enabled||!/^hoibot_pet_rebirth(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Blocked database: ${config.database.name}`);
const db=createDatabaseClient(config.database),service=new PetRebirthService(db),base=process.env.PET_REBIRTH_EVENT_ID??"pet-rebirth-g7-20260827-r1",room="rebirth-origin",broadcast=["rebirth-room-a","rebirth-room-b"],restart=process.argv.includes("--verify-restart");
const input=(suffix:string,user:string,message:string)=>({eventId:`${base}-${suffix}`,externalUserId:user,destinationId:room,message,broadcastDestinationIds:broadcast});
async function event(suffix:string,user:string){const id=`${base}-${suffix}`;await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('9',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(tx:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(tx=>work({query:(s,p)=>tx.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic rebirth audit failure");return tx.execute(s,p);}}))};}
async function snapshot(){return(await db.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint;events:bigint;ledgers:bigint;user_level:bigint;user_acc:bigint;user_rebirth:bigint;target_level:bigint;target_acc:bigint;target_rebirth:bigint;mushrooms:bigint}>>(`SELECT
 (SELECT COUNT(*) FROM operations WHERE idempotency_key LIKE ?) operations,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_key LIKE ?) outboxes,
 (SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_key LIKE ?) audits,(SELECT COUNT(*) FROM command_executions WHERE event_id LIKE ?) executions,
 (SELECT COUNT(*) FROM player_rebirth_events e JOIN operations o ON o.id=e.operation_id WHERE o.idempotency_key LIKE ?) events,(SELECT COUNT(*) FROM inventory_ledger l JOIN operations o ON o.id=l.operation_id WHERE o.idempotency_key LIKE ?) ledgers,
 (SELECT level FROM player_profiles WHERE player_id=989800002) user_level,(SELECT accumulated_level_offset FROM player_profiles WHERE player_id=989800002) user_acc,(SELECT rebirth_count FROM player_profiles WHERE player_id=989800002) user_rebirth,
 (SELECT level FROM player_profiles WHERE player_id=989800003) target_level,(SELECT accumulated_level_offset FROM player_profiles WHERE player_id=989800003) target_acc,(SELECT rebirth_count FROM player_profiles WHERE player_id=989800003) target_rebirth,
 (SELECT quantity FROM inventory_stacks WHERE player_id=989800002 LIMIT 1) mushrooms`,Array(6).fill(`${base}-%`)))[0]!;}
const expected={operations:3n,outboxes:7n,audits:3n,executions:3n,events:2n,ledgers:1n,user_level:1n,user_acc:100n,user_rebirth:1n,target_level:1n,target_acc:787n,target_rebirth:3n,mushrooms:1n};
try{if(!restart){
 for(const [id,user,name,level,acc,rebirth]of[[989800001,"rebirth-master","호이 남",1,0,0],[989800002,"rebirth-user","일반 남",100,0,0],[989800003,"rebirth-target","대상 남",777,10,2],[989800004,"rebirth-denied","부족 남",20,5,0]]as const){await db.execute("INSERT INTO players(id,status) VALUES (?,'active')",[id]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,level,accumulated_level_offset,rebirth_count) VALUES (?,?,?,?,?)",[id,name,level,acc,rebirth]);await db.execute("INSERT INTO external_identities(provider_code,external_user_id,player_id,status) VALUES ('kakao',?,?,'linked')",[user,id]);}
 await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (989830001,'rebirth-master','호이 남','synthetic','active')");await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT 989830001,id FROM external_identities WHERE external_user_id='rebirth-master'");await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 989830001,id FROM admin_roles WHERE code='super_admin'");
 const item=await db.execute("INSERT INTO item_definitions(code,display_name,asset_type_code,stackable,active) VALUES ('synthetic-rebirth-mushroom','환생버섯🍄','legacy_bag_item',TRUE,TRUE)");await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (989800002,?,2,1)",[item.insertId]);
 for(const [suffix,user]of[["self","rebirth-user"],["denied","rebirth-denied"],["admin","rebirth-master"],["rollback","rebirth-master"]]as const)await event(suffix,user);
 assert.equal((await db.query<Array<{c:bigint}>>("SELECT COUNT(*) c FROM command_registry WHERE handler_key='pet_rebirth' AND rollout_state='SHADOW'"))[0]!.c,2n);
 const self=await service.handle(input("self","rebirth-user","/환생"));assert.equal(self.status,"reborn");assert.equal(self.mushroomConsumed,true);assert.equal(self.replies.length,3);assert.deepEqual(await service.handle(input("self","rebirth-user","/환생")),self);
 const denied=await service.handle(input("denied","rebirth-denied","/환생"));assert.equal(denied.status,"requirement_missing");assert.equal(denied.replies.length,1);
 const admin=await service.handle(input("admin","rebirth-master","/환생 대상 남"));assert.equal(admin.status,"reborn");assert.equal(admin.mushroomConsumed,false);
 await assert.rejects(()=>new PetRebirthService(failAudit(db)).handle(input("rollback","rebirth-master","/환생 대상 남")),/synthetic rebirth audit failure/);assert.deepEqual(await snapshot(),expected);assert.equal(await db.verifyRollback(),true);
 }else{const before=await snapshot();await service.handle(input("self","rebirth-user","/환생"));assert.deepEqual(await snapshot(),before);assert.deepEqual(before,expected);}
 process.stdout.write(JSON.stringify({mode:restart?"verify-restart":"probe",migrationCount:173,scenarios:["shadow-registry","self-mushroom","requirement-denied","super-admin-force","bigint-profile","multi-room-outbox","replay","rollback","restart"],effects:await snapshot(),operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v)+"\n");
}finally{await db.close();}
