import assert from "node:assert/strict";
import fs from "node:fs";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient} from "../src/database.js";
const fixture=JSON.parse(fs.readFileSync(new URL("../../migration-control/fixtures/synthetic-relational/tower-reward-target-parity-v2438.json",import.meta.url),"utf8"));
const config=loadConfig();if(!config.database.enabled||!/^hoibot_asset_tower_reward(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`UNSAFE_TOWER_REWARD_PARITY_DATABASE:${config.database.name}`);
let database=createDatabaseClient(config.database);const checks:string[]=[];
try{
 const catalogs=await database.query<Array<{id:bigint;trial_source_sha256:string;event_source_sha256:string;boss_count:bigint;reward_count:bigint;event_floor_count:bigint}>>("SELECT id,trial_source_sha256,event_source_sha256,boss_count,reward_count,event_floor_count FROM tower_reward_policy_catalog_versions WHERE version_code=? AND active=TRUE",[fixture.catalogVersion]);assert.equal(catalogs.length,1);assert.deepEqual([catalogs[0]!.trial_source_sha256,catalogs[0]!.event_source_sha256,Number(catalogs[0]!.boss_count),Number(catalogs[0]!.reward_count),Number(catalogs[0]!.event_floor_count)],[fixture.sources.trial.operationalSha256,fixture.sources.event.operationalSha256,127,384,368]);checks.push("active immutable catalog");
 const bosses=await database.query<Array<{source_kind:string;boss_sequence:bigint;precedence_rank:bigint;match_strategy:string;display_name:string;pet_type_name:string|null;min_floor:bigint|null;max_floor:bigint|null;identity_hash:string;reward_count:bigint}>>("SELECT source_kind,boss_sequence,precedence_rank,match_strategy,display_name,pet_type_name,min_floor,max_floor,identity_hash,reward_count FROM tower_reward_policy_bosses WHERE catalog_version_id=? ORDER BY precedence_rank,boss_sequence",[catalogs[0]!.id]);assert.deepEqual(bosses.map(row=>[row.source_kind,Number(row.boss_sequence),Number(row.precedence_rank),row.match_strategy,row.display_name,row.pet_type_name,row.min_floor===null?null:Number(row.min_floor),row.max_floor===null?null:Number(row.max_floor),row.identity_hash,Number(row.reward_count)]),[...fixture.bosses].sort((a:{precedenceRank:number;bossSequence:number},b:{precedenceRank:number;bossSequence:number})=>a.precedenceRank-b.precedenceRank||a.bossSequence-b.bossSequence).map((row:Record<string,unknown>)=>[row.sourceKind,row.bossSequence,row.precedenceRank,row.matchStrategy,row.displayName,row.petTypeName,row.minFloor,row.maxFloor,row.identityHash,row.rewardCount]));checks.push("127 ordered bosses");
 const floors=await database.query<Array<{boss_sequence:bigint;floor_sequence:bigint;floor_value:bigint}>>("SELECT boss_sequence,floor_sequence,floor_value FROM tower_event_floor_occurrences WHERE catalog_version_id=? ORDER BY boss_sequence,floor_sequence",[catalogs[0]!.id]);assert.deepEqual(floors.map(row=>[Number(row.boss_sequence),Number(row.floor_sequence),Number(row.floor_value)]),fixture.eventFloors.map((row:Record<string,unknown>)=>[row.bossSequence,row.floorSequence,row.floorValue]));checks.push("368 event floors");
 const rewards=await database.query<Array<{source_kind:string;boss_sequence:bigint;reward_sequence:bigint;code:string;source_item_name:string;quantity:bigint;resolution_mode:string;reward_hash:string}>>(`SELECT reward_row.source_kind,reward_row.boss_sequence,reward_row.reward_sequence,item_row.code,reward_row.source_item_name,reward_row.quantity,reward_row.resolution_mode,reward_row.reward_hash FROM tower_reward_target_occurrences reward_row JOIN item_definitions item_row ON item_row.id=reward_row.item_definition_id WHERE reward_row.catalog_version_id=? ORDER BY reward_row.source_kind,reward_row.boss_sequence,reward_row.reward_sequence`,[catalogs[0]!.id]);assert.deepEqual(rewards.map(row=>[row.source_kind,Number(row.boss_sequence),Number(row.reward_sequence),row.code,row.source_item_name,Number(row.quantity),row.resolution_mode,row.reward_hash]),[...fixture.rewards].sort((a:{sourceKind:string;bossSequence:number;rewardSequence:number},b:{sourceKind:string;bossSequence:number;rewardSequence:number})=>a.sourceKind.localeCompare(b.sourceKind)||a.bossSequence-b.bossSequence||a.rewardSequence-b.rewardSequence).map((row:Record<string,unknown>)=>[row.sourceKind,row.bossSequence,row.rewardSequence,row.itemCode,row.sourceItemName,row.quantity,row.resolutionMode,row.rewardHash]));checks.push("384 typed rewards");
 const newTargets=await database.query<Array<{code:string;display_name:string}>>("SELECT code,display_name FROM item_definitions WHERE code IN('tower_newbie_support_fund','pet_title_ticket') ORDER BY code");assert.deepEqual(newTargets.map(row=>[row.code,row.display_name]),[["pet_title_ticket","펫타이틀권🦊(/펫타이틀이름)"],["tower_newbie_support_fund","신입지원금"]]);checks.push("two new STACK targets");
 const before=rewards[0]!.reward_hash;await assert.rejects(database.withTransaction(async transaction=>{await transaction.execute("UPDATE tower_reward_target_occurrences SET reward_hash=REPEAT('0',64) WHERE catalog_version_id=? AND source_kind=? AND boss_sequence=? AND reward_sequence=?",[catalogs[0]!.id,rewards[0]!.source_kind,rewards[0]!.boss_sequence,rewards[0]!.reward_sequence]);throw new Error("ROLLBACK_SENTINEL");}),/ROLLBACK_SENTINEL/);assert.equal((await database.query<Array<{value:string}>>("SELECT reward_hash value FROM tower_reward_target_occurrences WHERE catalog_version_id=? AND source_kind=? AND boss_sequence=? AND reward_sequence=?",[catalogs[0]!.id,rewards[0]!.source_kind,rewards[0]!.boss_sequence,rewards[0]!.reward_sequence]))[0]!.value,before);checks.push("transaction rollback");
 await database.close();database=createDatabaseClient(config.database);assert.equal(Number((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM tower_reward_target_occurrences WHERE catalog_version_id=?",[catalogs[0]!.id]))[0]!.count_value),384);checks.push("reconnect read");
 console.log(JSON.stringify({result:"passed",checks,total:checks.length,bosses:127,rewards:384,eventFloors:368,uniqueTargets:24,newTargets:2,providerAdded:false,consumerChanged:false,ownershipRowsMutated:0,operationalDataTouched:false,gate8:false}));
}finally{await database.close();}
