import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient } from "../src/database.js";
import { IrisAdminCommandService } from "../src/admin/iris-admin-command-service.js";
import { GuildTerritoryWarStateStartService } from "../src/guild/guild-territory-war-state-start-service.js";

const config=loadConfig(),db=createDatabaseClient(config.database),verify=process.argv.includes("--verify-restart"),base=process.env.GUILD_TERRITORY_START_PROBE_EVENT_ID??"guild-territory-start-g7-20260829";
const operatorPlayer=989343001n,first=989343002n,second=989343003n,unauthorized=989343004n,guildA=989343101n,guildB=989343102n,war=989343201n,noReadyWar=989343202n,rollbackWar=989343203n,operator=989343301n,room="synthetic-territory-command",notice="synthetic-territory-notice",castle="synthetic-territory-castle",external="synthetic-territory-operator",unauthorizedExternal="synthetic-territory-unauthorized";
const service=new GuildTerritoryWarStateStartService(db,{random:(()=>{const values=[0.75,0.25,0.5,0.1];let index=0;return()=>values[index++%values.length]!;})(),now:()=>new Date("2026-08-29T00:00:00.000Z"),token:()=>"synthetic-territory-start-token"});

// 합성 Iris 수신 event를 중복 안전하게 등록합니다.
async function event(id:string,user=external){await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('e',64),'processed',UTC_TIMESTAMP(3))",[id,id,room,user]);}
// 영지전 시작 aggregate의 검증 핵심 수량을 한 번에 조회합니다.
async function snapshot(){return(await db.query<Array<{runs:bigint;operations:bigint;turns:bigint;transitions:bigint;outboxes:bigint;audits:bigint}>>("SELECT (SELECT COUNT(*) FROM guild_territory_start_runs) runs,(SELECT COUNT(*) FROM operations WHERE idempotency_scope='guild.territory.start:world') operations,(SELECT COUNT(*) FROM guild_territory_turns) turns,(SELECT COUNT(*) FROM guild_territory_scheduled_transitions) transitions,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope='guild.territory.start:world') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code IN ('guild.territory.start','guild.territory.start.transition')) audits"))[0]!;}

try{
  if(!verify){
    await db.execute("UPDATE command_registry SET rollout_state='SHADOW',enabled=TRUE WHERE command_code='GUILD_TERRITORY_WAR_STATE_START'");
    for(const [id,name] of [[operatorPlayer,"합성 영지 관리자"],[first,"첫 공격자"],[second,"둘 공격자"],[unauthorized,"권한없는 사용자"]] as const){await db.execute("INSERT INTO players(id,status,version) VALUES (?,'active',1) ON DUPLICATE KEY UPDATE status='active'",[id]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name,experience,version) VALUES (?,?,0,1) ON DUPLICATE KEY UPDATE current_display_name=VALUES(current_display_name)",[id,name]);}
    await db.execute("INSERT INTO player_legacy_rank_profiles(player_id,rank_emoji,source_order) VALUES (?,'🥇',1),(?,'🥈',2) ON DUPLICATE KEY UPDATE rank_emoji=VALUES(rank_emoji),source_order=VALUES(source_order)",[first,second]);
    await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (?,'kakao',?,'합성 영지 관리자','linked'),(?,'kakao',?,'권한없는 사용자','linked') ON DUPLICATE KEY UPDATE player_id=VALUES(player_id),status='linked'",[operatorPlayer,external,unauthorized,unauthorizedExternal]);
    const identity=(await db.query<Array<{id:bigint}>>("SELECT id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[external]))[0]!.id;
    await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'territory-start-probe','합성 영지 관리자','synthetic','active') ON DUPLICATE KEY UPDATE status='active'",[operator]);
    await db.execute("INSERT IGNORE INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operator,identity]);
    await db.execute("INSERT INTO guild_territory_start_operator_allowlist(operator_id,active,source_label) VALUES (?,TRUE,'synthetic') ON DUPLICATE KEY UPDATE active=TRUE",[operator]);
    await db.execute("INSERT INTO guilds(id,code,display_name,mark,status,version) VALUES (?,'SYN-START-A','첫길드','A','active',1),(?,'SYN-START-B','둘길드','B','active',1) ON DUPLICATE KEY UPDATE status='active'",[guildA,guildB]);
    await db.execute("INSERT INTO guild_members(guild_id,player_id,role_code) VALUES (?,?,'member'),(?,?,'member') ON DUPLICATE KEY UPDATE role_code=VALUES(role_code)",[guildA,first,guildB,second]);
    await db.execute("INSERT INTO guild_territory_rift_authorizations(guild_id,player_id,authority_code,active) VALUES (?,?,'sword_master',TRUE),(?,?,'sword_master',TRUE) ON DUPLICATE KEY UPDATE active=TRUE",[guildA,first,guildB,second]);
    await db.execute("INSERT INTO guild_territory_wars(id,war_key,active,lifecycle_state,start_ready,rift_event_history_json,version) VALUES (?,'synthetic-start',FALSE,'READY',FALSE,JSON_ARRAY(),1),(?,'synthetic-no-ready',FALSE,'READY',FALSE,JSON_ARRAY(),1),(?,'synthetic-rollback',FALSE,'READY',FALSE,JSON_ARRAY(),1) ON DUPLICATE KEY UPDATE active=FALSE,lifecycle_state='READY',start_ready=FALSE,pending_start_token=NULL,opening_token=NULL,current_turn_no=0,version=1",[war,noReadyWar,rollbackWar]);
    await db.execute("INSERT INTO guild_territory_ready_guilds(war_id,guild_id,ready) VALUES (?,?,TRUE),(?,?,TRUE),(?,?,TRUE) ON DUPLICATE KEY UPDATE ready=TRUE,eliminated_reason=NULL,eliminated_at=NULL",[war,guildA,war,guildB,rollbackWar,guildA]);
    await db.execute("INSERT INTO guild_territory_occupations(war_id,territory_no,territory_name,owner_guild_id,owner_player_id) VALUES (?,1,'호월킹덤🏰',?,?),(?,2,'펫스킬광산📙',NULL,NULL) ON DUPLICATE KEY UPDATE territory_name=VALUES(territory_name),owner_guild_id=VALUES(owner_guild_id),owner_player_id=VALUES(owner_player_id)",[war,guildA,first,war]);
    await db.execute("INSERT INTO guild_territory_start_scopes(scope_code,war_id,version) VALUES ('world',?,1) ON DUPLICATE KEY UPDATE war_id=VALUES(war_id),version=version+1",[noReadyWar]);
    await db.execute("INSERT INTO guild_territory_start_destinations(destination_id,destination_kind,position_no,active) VALUES (?,'NOTICE',1,TRUE),(?,'CASTLE',1,TRUE) ON DUPLICATE KEY UPDATE active=TRUE",[notice,castle]);
    const shadow=`${base}-shadow`;await event(shadow);assert.deepEqual(await service.handleIris({eventId:shadow,externalUserId:external,channelId:room,message:"/길드영지시작"}),{status:"shadow"});
    await db.execute("UPDATE command_registry SET rollout_state='ACTIVE' WHERE command_code='GUILD_TERRITORY_WAR_STATE_START'");
    const noReady=`${base}-no-ready`;await event(noReady);await assert.rejects(()=>service.start({eventId:noReady,externalUserId:external,channelId:room,message:"/길드영지시작"}),/준비한 공격자/);
    await db.execute("UPDATE guild_territory_start_scopes SET war_id=? WHERE scope_code='world'",[rollbackWar]);const rollback=`${base}-rollback`;await event(rollback);const before=await snapshot();
    await db.execute("DROP TRIGGER IF EXISTS synthetic_guild_territory_start_audit_fail");await db.execute("CREATE TRIGGER synthetic_guild_territory_start_audit_fail BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic guild territory start audit failure'");
    await assert.rejects(()=>service.start({eventId:rollback,externalUserId:external,channelId:room,message:"/길드영지시작"}),/synthetic guild territory start audit failure/);await db.execute("DROP TRIGGER synthetic_guild_territory_start_audit_fail");assert.deepEqual(await snapshot(),before);
    await db.execute("UPDATE guild_territory_start_scopes SET war_id=? WHERE scope_code='world'",[war]);const denied=`${base}-denied`;await event(denied,unauthorizedExternal);await assert.rejects(()=>service.start({eventId:denied,externalUserId:unauthorizedExternal,channelId:room,message:"/길드영지시작"}),/권한/);
    const start=`${base}-start`;await event(start);const [firstResult,secondResult]=await Promise.all([service.start({eventId:start,externalUserId:external,channelId:room,message:"/길드영지시작"}),service.start({eventId:start,externalUserId:external,channelId:room,message:"/길드영지시작"})]);assert.deepEqual(secondResult,firstResult);assert.equal(firstResult.attackerCount,2);
    const dispatched=await new IrisAdminCommandService(db).changePlayerPoint({eventId:start,externalUserId:external,channelId:room,message:"/길드영지시작"});assert.equal(dispatched.status,"changed");
    assert.deepEqual(await service.runDueTransitions(10,new Date("2026-08-29T00:00:20.000Z")),{processed:1,skipped:0});const opening=(await db.query<Array<{lifecycle_state:string;start_ready:number;version:bigint}>>("SELECT lifecycle_state,start_ready,version FROM guild_territory_wars WHERE id=?",[war]))[0]!;assert.deepEqual(opening,{lifecycle_state:"ACTIVE_OPENING",start_ready:0,version:3n});
    const active=`${base}-active`;await event(active);await assert.rejects(()=>service.start({eventId:active,externalUserId:external,channelId:room,message:"/길드영지시작"}),/진행 또는 시작 대기/);
    const counts=await snapshot();process.stdout.write(JSON.stringify({mode:"probe",migrationCount:Number((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM schema_migrations"))[0]!.count_value),scenarios:["exact","shadow","allowlist","no-ready","recorded-rng","same-event-concurrency","rollback","opening","active-guard","restart-pending"],state:"ACTIVE_OPENING",effects:Object.fromEntries(Object.entries(counts).map(([key,value])=>[key,(value as bigint).toString()])),operationalDataTouched:false})+"\n");
  }else{
    const recovered=await service.runDueTransitions(10,new Date("2026-08-29T00:00:26.000Z"));assert.deepEqual(recovered,{processed:1,skipped:0});const start=`${base}-start`,replay=await service.start({eventId:start,externalUserId:external,channelId:room,message:"/길드영지시작"});const state=(await db.query<Array<{lifecycle_state:string;active:number;start_ready:number;current_turn_no:number;turn_deadline_at:string|null;version:bigint}>>("SELECT lifecycle_state,active,start_ready,current_turn_no,turn_deadline_at,version FROM guild_territory_wars WHERE id=?",[war]))[0]!,completed=(await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_territory_scheduled_transitions WHERE war_id=? AND status='COMPLETED'",[war]))[0]!.count_value,activeTurns=(await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM guild_territory_turns WHERE war_id=? AND turn_state='ACTIVE'",[war]))[0]!.count_value;assert.equal(state.lifecycle_state,"ACTIVE_READY");assert.equal(state.active,1);assert.equal(state.start_ready,1);assert.equal(state.current_turn_no,1);assert.equal(completed,2n);assert.equal(activeTurns,1n);process.stdout.write(JSON.stringify({mode:"verify-restart",status:replay.status,state:state.lifecycle_state,completedTransitions:completed.toString(),activeTurns:activeTurns.toString(),turnDeadlinePersisted:state.turn_deadline_at!==null,replayPreserved:true,additionalMutation:false,operationalDataTouched:false})+"\n");
  }
}finally{await db.execute("DROP TRIGGER IF EXISTS synthetic_guild_territory_start_audit_fail").catch(()=>undefined);await db.close();}
