import assert from "node:assert/strict";
import {loadConfig} from "../src/config.js";
import {createDatabaseClient,type DatabaseClient,type DatabaseTransaction} from "../src/database.js";
import {HomeFurnitureInfoReadService} from "../src/home/home-furniture-info-read-service.js";
const config=loadConfig();if(!config.database.enabled||!/^hoibot_home_furniture_info_read(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error("isolated info database required");
let db=createDatabaseClient(config.database),service=()=>new HomeFurnitureInfoReadService(db);const base=process.env.HOME_FURNITURE_INFO_READ_PROBE_EVENT_ID??"home-furniture-info-read-g7-20260827-r1",room="info-room",admin="info-admin",ordinary="info-user",targetId=203003n;
async function event(s:string,u:string){const id=base+"-"+s;await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('3',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status='processed'",[id,id,room,u]);return id;}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("forced info rollback");return t.execute(s,p);}}))};}
async function effects(){return(await db.query<Array<{ops:bigint;outbox:bigint;audit:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='home.furniture_info_read' AND idempotency_key LIKE ?) ops,(SELECT COUNT(*) FROM outbox_messages o JOIN operations p ON p.id=o.operation_id WHERE p.idempotency_scope='home.furniture_info_read' AND p.idempotency_key LIKE ?) outbox,(SELECT COUNT(*) FROM command_audit a JOIN operations p ON p.id=a.operation_id WHERE p.idempotency_scope='home.furniture_info_read' AND p.idempotency_key LIKE ?) audit",[base+"-%",base+"-%",base+"-%"]))[0]!;}
async function state(){return(await db.query<Array<{bag:bigint;placed:bigint;versions:string;home_version:bigint}>>("SELECT (SELECT COUNT(*) FROM furniture_inventory_instances WHERE player_id=? AND status='bag') bag,(SELECT COUNT(*) FROM furniture_inventory_instances WHERE player_id=? AND status='placed') placed,(SELECT GROUP_CONCAT(CONCAT(id,':',status,':',version) ORDER BY id) FROM furniture_inventory_instances WHERE player_id=?) versions,(SELECT version FROM player_homes WHERE player_id=?) home_version",[targetId,targetId,targetId,targetId]))[0]!;}
try{const success=base+"-success";if(process.argv.includes("--verify-restart")){const before=await state(),e=await effects(),result=await service().read({eventId:success,externalUserId:admin,destinationId:room,message:"/가구정보 대상 회원"});assert.equal(result.status,"read");assert.deepEqual(await state(),before);assert.deepEqual(await effects(),e);process.stdout.write(JSON.stringify({mode:"restart",scenarios:["restart-replay"],effects:e},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}else{
 await db.execute("INSERT INTO players(id,status) VALUES (203001,'active'),(203002,'active'),(203003,'active')");
 await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (203001,'조회 관리자'),(203002,'일반 회원'),(203003,'대상 회원')");
 const ai=await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (203001,'kakao',?,'조회 관리자','linked')",[admin]);await db.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (203002,'kakao',?,'일반 회원','linked')",[ordinary]);
 await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (203901,'info-admin','조회 관리자','synthetic','active')");await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (203901,?)",[ai.insertId]);
 await db.execute("INSERT INTO player_homes(player_id,display_name,base_experience,like_count,floor_area) VALUES (203003,'정보 홈',1000,7,100)");await db.execute("INSERT INTO player_passes(player_id,pass_code,enabled,permanent) VALUES (203003,'premium',TRUE,TRUE)");
 for(let i=0;i<9;i++){const d=await db.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES (?,?,?,TRUE)",["PROBE-INFO-"+i,"정보가구"+i,100-i]);await db.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (203003,?,?,?,'bag')",[d.insertId,100-i,"S"]);}
 for(let i=0;i<2;i++){const d=await db.execute("INSERT INTO furniture_definitions(code,display_name,charm_value,active) VALUES (?,?,?,TRUE)",["PROBE-INFO-P-"+i,"배치가구"+i,500-i]);await db.execute("INSERT INTO furniture_inventory_instances(player_id,furniture_definition_id,charm_snapshot,grade_display_name,status) VALUES (203003,?,?,?,'placed')",[d.insertId,500-i,"A"]);}
 assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='HOME_FURNITURE_INFO_READ'"))[0]!.rollout_state,"SHADOW");
 const ignored=await service().read({eventId:await event("ignored",ordinary),externalUserId:ordinary,destinationId:room,message:"/가구정보 대상 회원"});assert.deepEqual(ignored,{status:"ignored"});assert.deepEqual(await effects(),{ops:0n,outbox:0n,audit:0n});
 const usage=await service().read({eventId:await event("usage",admin),externalUserId:admin,destinationId:room,message:"/가구정보"});assert.equal(usage.status,"usage");
 const missing=await service().read({eventId:await event("missing",admin),externalUserId:admin,destinationId:room,message:"/가구정보 없음"});assert.equal(missing.status,"not_found");
 const before=await state();await event("success",admin);const result=await service().read({eventId:success,externalUserId:admin,destinationId:room,message:"/가구정보 대상 회원"});assert.equal(result.status,"read");assert.match(result.reply??"",/정보 홈\(\+1,999💕\)\[\+100평\]/);assert.match(result.reply??"",/가구 가방🛌 \[9\/15\]/);assert.ok((result.reply??"").includes("\u200b".repeat(500)));assert.deepEqual(await state(),before);assert.deepEqual(await service().read({eventId:success,externalUserId:admin,destinationId:room,message:"/가구정보 대상 회원"}),result);
 const rollback=await event("rollback",admin);await assert.rejects(new HomeFurnitureInfoReadService(failAudit(db)).read({eventId:rollback,externalUserId:admin,destinationId:room,message:"/가구정보 대상 회원"}),/forced info rollback/);assert.deepEqual(await state(),before);assert.equal(await db.verifyRollback(),true);
 process.stdout.write(JSON.stringify({mode:"probe",scenarios:["shadow-registry","legacy-prefix","admin-only","usage","not-found","stable-bag-order","allsee-index5","home-placed-slot-projection","read-only-replay","rollback-restart"],effects:await effects(),operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}}
finally{await db.close();}
