import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient } from "../src/database.js";
import { AutoDailyQuestOrchestrationService } from "../src/quest/auto-daily-quest-orchestration-service.js";

const restart=process.argv.includes("--verify-restart"),database=createDatabaseClient(loadConfig().database),externalId="synthetic-auto-daily-user",eventId="synthetic-auto-daily-event";
async function scalar(sql:string,values:readonly unknown[]=[]):Promise<bigint>{const row=(await database.query<Array<{value:bigint|string}>>(sql,values))[0];return BigInt(row?.value??0);}
function failingOnAudit(base:DatabaseClient):DatabaseClient{return{...base,withTransaction:work=>base.withTransaction(async tx=>work({...tx,execute:async(sql,values=[])=>{if(sql.includes("INSERT INTO command_audit")&&sql.includes("auto.daily.quest"))throw new Error("synthetic auto daily audit failure");return tx.execute(sql,values);}}))};}

try{
  if(!restart){
    await database.execute("DELETE FROM external_identities WHERE external_user_id IN (?,?)",[externalId,`${externalId}-rollback`]);
    for(const [id,ext] of [[988600001,externalId],[988600002,`${externalId}-rollback`]] as const){await database.execute("INSERT INTO players(id,status) VALUES (?,'active') ON DUPLICATE KEY UPDATE status='active'",[id]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name,tier_code) VALUES (?,?, 'seed') ON DUPLICATE KEY UPDATE current_display_name=VALUES(current_display_name)",[id,`자동일퀘합성${id}`]);await database.execute("INSERT INTO external_identities(provider_code,external_user_id,player_id,status) VALUES ('kakao',?,?,'linked')",[ext,id]);await database.execute("INSERT INTO player_pet_daily_records(player_id,record_date,tower_attempts,castle_battle_attempts,mini_battle_attempts,explore_attempts,weekly_quest_count) VALUES (?,DATE(DATE_ADD(UTC_TIMESTAMP(),INTERVAL 9 HOUR)),20,20,20,10,6) ON DUPLICATE KEY UPDATE tower_attempts=20,castle_battle_attempts=20,mini_battle_attempts=20,explore_attempts=10,weekly_quest_count=6,daily_quest_rewarded=FALSE,pass_daily_quest_rewarded=FALSE,premium_daily_quest_rewarded=FALSE",[id]);await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity) SELECT ?,id,1 FROM item_definitions WHERE code='auto_daily_quest_ticket' ON DUPLICATE KEY UPDATE quantity=1",[id]);}
    for(const id of[eventId,`${eventId}-rollback`])await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-auto-daily-room',?,'message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,id===eventId?externalId:`${externalId}-rollback`]);
    const service=new AutoDailyQuestOrchestrationService(database),result=await service.handle({externalUserId:externalId,channelId:"synthetic-auto-daily-room",message:"/자동일퀘",eventId});assert.equal(result.status,"completed");assert.deepEqual(result.runs,{towerRuns:0,castleRuns:0,miniRuns:0});assert.deepEqual(result.claimedScopes,["DAILY","WEEKLY"]);const replay=await service.handle({externalUserId:externalId,channelId:"synthetic-auto-daily-room",message:"/자동일퀘",eventId});assert.equal(replay.replayed,true);
    await assert.rejects(()=>new AutoDailyQuestOrchestrationService(failingOnAudit(database)).handle({externalUserId:`${externalId}-rollback`,channelId:"synthetic-auto-daily-room",message:"ㅇㅋㅋ",eventId:`${eventId}-rollback`}),/synthetic auto daily audit failure/);
    const effects={operations:await scalar("SELECT COUNT(*) value FROM operations WHERE idempotency_scope LIKE 'auto.daily.quest:%'"),runs:await scalar("SELECT COUNT(*) value FROM auto_daily_quest_runs"),rewarded:await scalar("SELECT COUNT(*) value FROM player_pet_daily_records WHERE player_id=988600001 AND daily_quest_rewarded=TRUE"),weekly:await scalar("SELECT weekly_quest_count value FROM player_pet_daily_records WHERE player_id=988600001"),rollbackRewarded:await scalar("SELECT COUNT(*) value FROM player_pet_daily_records WHERE player_id=988600002 AND daily_quest_rewarded=TRUE"),rollbackOps:await scalar("SELECT COUNT(*) value FROM operations WHERE idempotency_scope='auto.daily.quest:988600002'")};assert.deepEqual(effects,{operations:1n,runs:1n,rewarded:1n,weekly:0n,rollbackRewarded:0n,rollbackOps:0n});console.log(JSON.stringify({mode:"probe",scenarios:["shadow-registry","daily-weekly-reward","deterministic-replay","atomic-rollback"],effects,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v));
  }else{const effects={operations:await scalar("SELECT COUNT(*) value FROM operations WHERE idempotency_scope LIKE 'auto.daily.quest:%'"),runs:await scalar("SELECT COUNT(*) value FROM auto_daily_quest_runs")};assert.deepEqual(effects,{operations:1n,runs:1n});console.log(JSON.stringify({mode:"verify-restart",...effects,additionalRun:false,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?Number(v):v));}
}finally{await database.close();}
