import assert from "node:assert/strict";
import { createDatabaseClient } from "../src/database.js";
import { RecordBoardService } from "../src/social/record-board-service.js";

const db=createDatabaseClient({enabled:true,host:req("DATABASE_HOST"),port:Number(req("DATABASE_PORT")),user:req("DATABASE_USER"),password:req("DATABASE_PASSWORD"),name:req("DATABASE_NAME"),connectionLimit:5,connectTimeoutMs:5000});
const player=998100001n,other=998100002n,identity=998200001n,otherIdentity=998200002n,operator=998300001n,external="998400001",otherExternal="998400002",room="고도화기록테스트방",broadcast="고도화기록방송";
async function seed(){await db.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active')",[player,other]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'기록운영자'),(?,'일반회원')",[player,other]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?,'kakao',?,'linked'),(?,?,'kakao',?,'linked')",[identity,player,external,otherIdentity,other,otherExternal]);await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'synthetic-record-admin','기록운영자','synthetic-password-hash','active')",[operator]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operator,identity]);await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='super_admin'",[operator]);await db.execute("UPDATE community_record_board_settings SET broadcast_destination_id=?,version=version+1",[broadcast]);}
async function event(id:string,user=external,identityId=identity){await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_code,provider_event_id,external_user_id,external_identity_id,event_kind,processing_status,received_at) VALUES (?,'iris',?,?,?,'message','processing',UTC_TIMESTAMP(3))",[id,id,user,identityId]);}
async function run(id:string,message:string,user=external,identityId=identity){await event(id,user,identityId);return new RecordBoardService(db).handle({eventId:id,externalUserId:user,destinationId:room,message});}
async function counts(){return(await db.query<Array<{published:bigint;deleted_count:bigint;important_count:bigint;entries:bigint;record_ops:bigint;ops:bigint;audits:bigint;executions:bigint;outboxes:bigint}>>("SELECT (SELECT COUNT(*) FROM community_record_entries WHERE status='published') published,(SELECT COUNT(*) FROM community_record_entries WHERE status='deleted') deleted_count,(SELECT COUNT(*) FROM community_record_entries WHERE status='published' AND important=TRUE) important_count,(SELECT COUNT(*) FROM community_record_entries) entries,(SELECT COUNT(*) FROM community_record_operations) record_ops,(SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'social.record_board.%') ops,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_scope LIKE 'social.record_board.%') audits,(SELECT COUNT(*) FROM command_executions e JOIN operations o ON o.id=e.operation_id WHERE o.idempotency_scope LIKE 'social.record_board.%') executions,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_scope LIKE 'social.record_board.%') outboxes"))[0]!;}
async function probe(){await seed();assert.equal((await run("record-add-1","/기록 첫 기록"))?.status,"added");assert.equal((await run("record-add-2","/기록 凸 둘째 기록"))?.important,false);assert.equal((await run("record-read","/기록실"))?.count,2);assert.equal((await run("record-important","/빌런 1"))?.status,"important_set");assert.equal((await run("record-important","/빌런 1"))?.replayed,true);assert.equal((await run("record-delete","/기록삭제 2"))?.status,"deleted");assert.equal((await run("record-delete","/기록삭제 2"))?.replayed,true);assert.equal((await run("record-invalid","/빌런"))?.status,"invalid");assert.equal(await run("record-unauthorized","/기록실",otherExternal,otherIdentity),null);const before=await counts();await db.execute("CREATE TRIGGER synthetic_record_audit_failure BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='record audit failure'");await assert.rejects(()=>run("record-rollback","/기록 롤백"),/record audit failure/);await db.execute("DROP TRIGGER synthetic_record_audit_failure");assert.deepEqual(await counts(),before);assert.equal(await db.verifyRollback(),true);assert.equal((await run("record-after-rollback","/기록 복구"))?.status,"added");const state=await counts();assert.deepEqual([state.published,state.deleted_count,state.important_count,state.entries,state.record_ops,state.ops,state.audits,state.executions,state.outboxes],[2n,1n,1n,3n,7n,7n,7n,7n,10n]);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:260,scenarios:["add","read","important","delete","auth","replay","rollback","restart","shadow","ordered-outbox"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
async function restart(){const state=await counts();assert.deepEqual([state.published,state.deleted_count,state.important_count,state.entries,state.record_ops,state.ops,state.audits,state.executions,state.outboxes],[2n,1n,1n,3n,7n,7n,7n,7n,10n]);process.stdout.write(JSON.stringify({mode:"verify-restart",state,additionalMutation:false,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
function req(name:string){const value=process.env[name];if(!value)throw new Error(`${name} required`);return value;}try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
