import assert from "node:assert/strict";
import { createDatabaseClient } from "../src/database.js";
import { LetterBoardService } from "../src/social/letter-board-service.js";

const db=createDatabaseClient({enabled:true,host:req("DATABASE_HOST"),port:Number(req("DATABASE_PORT")),user:req("DATABASE_USER"),password:req("DATABASE_PASSWORD"),name:req("DATABASE_NAME"),connectionLimit:5,connectTimeoutMs:5000});
const player=997100001n,identity=997200001n,operator=997300001n,other=997100002n,otherIdentity=997200002n,external="997400001",otherExternal="997400002",room="고도화편지방";
async function seed(){await db.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active')",[player,other]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'편지회원'),(?,'일반회원')",[player,other]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?,'kakao',?,'linked'),(?,?,'kakao',?,'linked')",[identity,player,external,otherIdentity,other,otherExternal]);await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'synthetic-letter-admin','편지운영자','synthetic-password-hash','active')",[operator]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[operator,identity]);await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='super_admin'",[operator]);const stamp=(await db.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code='LETTER_STAMP'"))[0]!;await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,?,12,1)",[player,stamp.id]);}
async function event(id:string,user=external,identityId=identity){await db.execute("INSERT IGNORE INTO event_inbox(event_id,provider_code,provider_event_id,external_user_id,external_identity_id,event_kind,processing_status,received_at) VALUES (?,'iris',?,?,?,'message','processing',UTC_TIMESTAMP(3))",[id,id,user,identityId]);}
async function run(id:string,message:string,user=external,identityId=identity){await event(id,user,identityId);return new LetterBoardService(db).handle({eventId:id,externalUserId:user,destinationId:room,message});}
async function counts(){return(await db.query<Array<{published:bigint;deleted_count:bigint;evicted:bigint;posts:bigint;post_ops:bigint;clear_ops:bigint;clear_lines:bigint;ops:bigint;audits:bigint;outboxes:bigint;stamps:bigint}>>("SELECT (SELECT COUNT(*) FROM community_posts WHERE status='published') published,(SELECT COUNT(*) FROM community_posts WHERE status='deleted') deleted_count,(SELECT COUNT(*) FROM community_posts WHERE status='evicted') evicted,(SELECT COUNT(*) FROM community_posts) posts,(SELECT COUNT(*) FROM community_post_operations) post_ops,(SELECT COUNT(*) FROM community_board_clear_operations) clear_ops,(SELECT COUNT(*) FROM community_board_clear_lines) clear_lines,(SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'social.letter_board.%') ops,(SELECT COUNT(*) FROM command_audit a JOIN operations o ON o.id=a.operation_id WHERE o.idempotency_scope LIKE 'social.letter_board.%') audits,(SELECT COUNT(*) FROM outbox_messages m JOIN operations o ON o.id=m.operation_id WHERE o.idempotency_scope LIKE 'social.letter_board.%') outboxes,(SELECT quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=997100001 AND item.code='LETTER_STAMP') stamps"))[0]!;}
async function probe(){await seed();for(let i=1;i<=12;i++)assert.equal((await run(`letter-${i}`,`/편지 내용 ${i}`))?.status,"posted");let state=await counts();assert.deepEqual([state.published,state.evicted,state.stamps],[10n,2n,0n]);assert.equal(await run("letter-clear-unauthorized","/편지삭제",otherExternal,otherIdentity),null);assert.equal((await run("letter-clear","/편지삭제"))?.clearedCount,10);assert.equal((await run("letter-clear","/편지삭제"))?.replayed,true);assert.equal((await run("letter-no-stamp","/편지 다시"))?.status,"stamp_required");const stamp=(await db.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code='LETTER_STAMP'"))[0]!;await db.execute("UPDATE inventory_stacks SET quantity=1,version=version+1 WHERE player_id=? AND item_id=?",[player,stamp.id]);const before=await counts();await db.execute("CREATE TRIGGER synthetic_letter_audit_failure BEFORE INSERT ON command_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='letter audit failure'");await assert.rejects(()=>run("letter-rollback","/편지 롤백"),/letter audit failure/);await db.execute("DROP TRIGGER synthetic_letter_audit_failure");assert.deepEqual(await counts(),before);assert.equal(await db.verifyRollback(),true);assert.equal((await run("letter-after-rollback","/편지 복구"))?.status,"posted");state=await counts();assert.deepEqual([state.published,state.deleted_count,state.evicted,state.posts,state.post_ops,state.clear_ops,state.clear_lines,state.ops,state.audits,state.outboxes,state.stamps],[1n,10n,2n,13n,13n,1n,10n,15n,15n,15n,0n]);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:259,scenarios:["post","stamp","retention10","clear-auth","clear-snapshot","replay","rollback","restart","shadow"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
async function restart(){const state=await counts();assert.deepEqual([state.published,state.deleted_count,state.evicted,state.posts,state.post_ops,state.clear_ops,state.clear_lines,state.ops,state.audits,state.outboxes,state.stamps],[1n,10n,2n,13n,13n,1n,10n,15n,15n,15n,0n]);process.stdout.write(JSON.stringify({mode:"verify-restart",state,additionalMutation:false,operationalDataTouched:false},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}
function req(n:string){const v=process.env[n];if(!v)throw new Error(`${n} required`);return v;}try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await db.close();}
