import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetAdminOwnedDeleteService } from "../src/mini-pet/mini-pet-admin-owned-delete-service.js";
const config=loadConfig();if(!config.database.enabled||!/^hoibot_mini_pet_admin_owned_delete/i.test(config.database.name))throw new Error("isolated mini pet admin owned delete db required");
let database=createDatabaseClient(config.database);const room="mini-pet-admin-delete-room",actorId=990000001,targetPlayerId=990000002,service=()=>new MiniPetAdminOwnedDeleteService(database);
async function registerEvent(eventId:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,'mini-pet-delete-admin','message','incoming',REPEAT('9',64),'processed',UTC_TIMESTAMP(3))",[eventId,eventId,room]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,v)=>inner.query(s,v),execute:(s,v)=>inner.execute(s,v),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,v)=>t.query(s,v),execute:async(s,v)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("forced mini pet admin delete rollback");return t.execute(s,v);}}))};}
async function addOwned(code:string,name:string,sequence:number,equipped=false){await database.execute("INSERT INTO mini_pet_definitions(code,display_name,grade_code,grade_display_name,emoji_value,active) VALUES (?,?,?,'일반','🐣',TRUE)",[code,name,"NORMAL"]);const definition=(await database.query<Array<{id:bigint}>>("SELECT id FROM mini_pet_definitions WHERE code=?",[code]))[0]!.id;return(await database.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,custom_name,progress,equipped,bag_sequence,version) VALUES (?,?,NULL,0,?,?,1)",[targetPlayerId,definition,equipped,sequence])).insertId;}
try{
  await database.execute("INSERT INTO players(id,status) VALUES (?,'active'),(?,'active')",[actorId,targetPlayerId]);await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'호이 남'),(?,'삭제 대상')",[actorId,targetPlayerId]);await database.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?,'kakao','mini-pet-delete-admin','linked')",[actorId,actorId]);await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (?,'mini-pet-delete-master','호이 남','synthetic','active')",[actorId]);await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES (?,?)",[actorId,actorId]);await database.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT ?,id FROM admin_roles WHERE code='super_admin'",[actorId]);
  const deletable=await addOwned("probe-mini-delete-a","삭제 병아리",1);await addOwned("probe-mini-delete-equipped","장착 병아리",2,true);const reserved=await addOwned("probe-mini-delete-reserved","예약 병아리",3);await database.execute("INSERT INTO title_definitions(code,display_name,scope_code,active) VALUES ('probe-mini-title','삭제 타이틀','mini_pet',TRUE)");const titleId=(await database.query<Array<{id:bigint}>>("SELECT id FROM title_definitions WHERE code='probe-mini-title'"))[0]!.id;await database.execute("INSERT INTO mini_pet_title_assignments(owned_mini_pet_id,title_id,acquired_at,equipped) VALUES (?,?,UTC_TIMESTAMP(3),TRUE)",[deletable,titleId]);await database.execute("INSERT INTO currency_definitions(code,display_name,scale_digits,active) VALUES ('PROBE','검증',0,TRUE) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name)");const listing=await database.execute("INSERT INTO market_listings(seller_player_id,asset_type_code,quantity,price_currency_code,price_amount,status) VALUES (?,'mini_pet',1,'PROBE',1,'open')",[targetPlayerId]);await database.execute("INSERT INTO market_mini_pet_reservations(listing_id,owned_mini_pet_id,player_id) VALUES (?,?,?)",[listing.insertId,reserved,targetPlayerId]);
  assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MINI_PET_ADMIN_OWNED_DELETE'"))[0]!.rollout_state,"SHADOW");assert.deepEqual(await service().handle({eventId:"unauthorized",externalUserId:"unknown",destinationId:room,message:"/미니펫삭제 삭제 대상 1"}),{status:"silent"});
  await registerEvent("mini-pet-delete-ok");const deleted=await service().handle({eventId:"mini-pet-delete-ok",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 1"});assert.equal(deleted.status,"deleted");assert.equal(deleted.ownedMiniPetId,deletable.toString());assert.equal(deleted.removedTitleCount,"1");assert.deepEqual(await service().handle({eventId:"mini-pet-delete-ok",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 1"}),deleted);assert.equal((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM mini_pet_title_assignments WHERE owned_mini_pet_id=?",[deletable]))[0]!.count_value,0n);
  await registerEvent("mini-pet-delete-equipped");assert.equal((await service().handle({eventId:"mini-pet-delete-equipped",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 1"})).status,"equipped");await registerEvent("mini-pet-delete-reserved");assert.equal((await service().handle({eventId:"mini-pet-delete-reserved",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 2"})).status,"reserved");
  const rollbackPet=await addOwned("probe-mini-delete-rollback","롤백 병아리",3);await registerEvent("mini-pet-delete-rollback");await assert.rejects(new MiniPetAdminOwnedDeleteService(failAudit(database)).handle({eventId:"mini-pet-delete-rollback",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 3"}),/forced mini pet admin delete rollback/);assert.equal((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM owned_mini_pets WHERE id=?",[rollbackPet]))[0]!.count_value,1n);
  const concurrentPet=await addOwned("probe-mini-delete-concurrent","동시 병아리",4);await registerEvent("mini-pet-delete-concurrent");const concurrentInput={eventId:"mini-pet-delete-concurrent",externalUserId:"mini-pet-delete-admin",destinationId:room,message:"/미니펫삭제 삭제 대상 4"};const concurrent=await Promise.all([service().handle(concurrentInput),service().handle(concurrentInput)]);assert.deepEqual(concurrent[0],concurrent[1]);assert.equal(concurrent[0].ownedMiniPetId,concurrentPet.toString());assert.equal((await database.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM mini_pet_admin_deletions WHERE owned_mini_pet_id=?",[concurrentPet]))[0]!.count_value,1n);
  await database.close();database=createDatabaseClient(config.database);assert.deepEqual(await service().handle(concurrentInput),concurrent[0]);const state=(await database.query<Array<{owned_count:bigint;deletion_count:bigint;audit_count:bigint;outbox_count:bigint}>>("SELECT (SELECT COUNT(*) FROM owned_mini_pets WHERE player_id=?) owned_count,(SELECT COUNT(*) FROM mini_pet_admin_deletions) deletion_count,(SELECT COUNT(*) FROM command_audit WHERE action_code='mini_pet.admin_owned.delete') audit_count,(SELECT COUNT(*) FROM outbox_messages WHERE destination_id=?) outbox_count",[targetPlayerId,room]))[0]!;process.stdout.write(JSON.stringify({scenarios:["shadow-registry","operator-permission","stable-id-delete","title-cleanup","bag-reindex","equipped-reject","reservation-reject","same-event-concurrency","rollback","restart-replay"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");
}finally{await database.close();}
