import assert from "node:assert/strict";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { loadConfig } from "../src/config.js";
import { CastleStateResetService } from "../src/castle/castle-state-reset-service.js";

const config=loadConfig();
if(!config.database.enabled||!/^hoibot_castle_state_reset(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error("Castle state reset probe requires an isolated database.");
const database=createDatabaseClient(config.database),base="synthetic-castle-state-reset",actor="castle-reset-actor",denied="castle-reset-denied";
async function event(id:string,user:string=actor){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES(?,?,?,?,'message','incoming',REPEAT('8',64),'processed',UTC_TIMESTAMP(3))",[id,id,"synthetic-castle-reset-room",user]);}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic castle reset audit failure");return t.execute(s,p);}}))};}
async function snapshot(){return database.query<Array<{operations:bigint;runs:bigint;audits:bigint;executions:bigint;outboxes:bigint;lord:string|null;guild:string|null;tax:number;earnings:string;defense:bigint;version:bigint;guild_version:bigint}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='castle.state.reset') operations,(SELECT COUNT(*) FROM castle_state_reset_runs) runs,(SELECT COUNT(*) FROM command_audit WHERE action_code='castle.state.reset') audits,(SELECT COUNT(*) FROM command_executions WHERE command_code='CASTLE_STATE_RESET') executions,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope='castle.state.reset') outboxes,CAST(state.lord_player_id AS CHAR) lord,state.lord_guild_name guild,state.tax_rate_basis_points tax,CAST(state.earnings AS CHAR) earnings,state.defense_count defense,state.version,(SELECT version FROM guilds WHERE id=993400001) guild_version FROM castle_state state WHERE state.state_code='HOI_CASTLE'`);}
async function seed(){
  await database.execute("INSERT INTO players(id,status,version) VALUES(993000001,'active',1),(993000002,'active',1),(993000003,'active',1)");
  await database.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES(993000001,'호이 남'),(993000002,'이전 영주'),(993000003,'일반 운영자')");
  await database.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,display_name,status) VALUES(993200001,993000001,'kakao',?,'호이 남','linked'),(993200002,993000003,'kakao',?,'일반 운영자','linked')",[actor,denied]);
  await database.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES(993300001,'castle-reset-master','호이 남','synthetic','active'),(993300002,'castle-reset-denied','일반 운영자','synthetic','active')");
  await database.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) VALUES(993300001,993200001),(993300002,993200002)");
  await database.execute("INSERT INTO guilds(id,code,display_name,status,version) VALUES(993400001,'SYNTHETIC-CASTLE-RESET','보존 길드','active',7)");
  await database.execute("UPDATE castle_state SET lord_player_id=993000002,lord_guild_name='이전 길드',tax_rate_basis_points=2500,earnings=999,defense_count=7,version=3 WHERE state_code='HOI_CASTLE'");
}
async function probe(){
  await seed();assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='CASTLE_STATE_RESET'"))[0]?.rollout_state,"SHADOW");
  const service=new CastleStateResetService(database);assert.equal(await service.handle({eventId:"invalid",externalUserId:actor,message:"/캐슬초기화 1"}),null);await event(`${base}-denied`,denied);assert.equal(await service.handle({eventId:`${base}-denied`,externalUserId:denied,message:"/캐슬초기화"}),null);
  const success=`${base}-success`;await event(success);const first=await service.handle({eventId:success,externalUserId:actor,message:"/캐슬초기화"});assert.equal(first?.silent,true);assert.equal(first?.previousVersion,"3");assert.equal(first?.resetVersion,"4");assert.equal(first?.previousState.lordGuildName,"이전 길드");assert.deepEqual(await service.handle({eventId:success,externalUserId:actor,message:"/캐슬초기화"}),{...first!,replayed:true});
  let state=(await snapshot())[0]!;assert.deepEqual(state,{operations:1n,runs:1n,audits:1n,executions:1n,outboxes:0n,lord:"993000001",guild:null,tax:1200,earnings:"0",defense:0n,version:4n,guild_version:7n});
  const concurrent=`${base}-concurrent`;await event(concurrent);const pair=await Promise.all([service.handle({eventId:concurrent,externalUserId:actor,message:"/캐슬초기화"}),service.handle({eventId:concurrent,externalUserId:actor,message:"/캐슬초기화"})]);assert.equal(pair[0]?.resetRunId,pair[1]?.resetRunId);assert.deepEqual(pair.map(value=>value?.replayed).sort(),[false,true]);
  const rollback=`${base}-rollback`;await event(rollback);const before=await snapshot();await assert.rejects(()=>new CastleStateResetService(failAudit(database)).handle({eventId:rollback,externalUserId:actor,message:"/캐슬초기화"}),/synthetic castle reset audit failure/);assert.deepEqual(await snapshot(),before);assert.equal(await database.verifyRollback(),true);
  state=(await snapshot())[0]!;assert.deepEqual(state,{operations:2n,runs:2n,audits:2n,executions:2n,outboxes:0n,lord:"993000001",guild:null,tax:1200,earnings:"0",defense:0n,version:5n,guild_version:7n});
  process.stdout.write(JSON.stringify({mode:"probe",migrationCount:279,scenarios:["shadow","exact","fixed-operator","state-version","old-new-snapshot","silent","replay","concurrent","rollback","other-domain-preserved"],effects:{operations:2,runs:2,audits:2,executions:2,outboxes:0,stateVersion:5},domainMutation:{castleState:true,otherDomains:false}})+"\n");
}
async function restart(){const before=await snapshot(),result=await new CastleStateResetService(database).handle({eventId:`${base}-success`,externalUserId:actor,message:"/캐슬초기화"});assert.equal(result?.replayed,true);assert.deepEqual(await snapshot(),before);process.stdout.write(JSON.stringify({mode:"verify-restart",replayStable:true,additionalMutation:false,otherDomainsMutated:false})+"\n");}
try{if(process.argv.includes("--verify-restart"))await restart();else await probe();}finally{await database.close();}
