import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient } from "../src/database.js";
import { CharacterCountStatsService } from "../src/admin/character-count-stats-service.js";

const config=loadConfig();if(!config.database.enabled)throw new Error("DATABASE_ENABLED must be true.");if(!/^hoibot_character_count_stats(?:_[a-z0-9_]+)?$/i.test(config.database.name))throw new Error(`Synthetic character count probe blocked: ${config.database.name}`);
const db=createDatabaseClient(config.database),restart=process.argv.includes("--verify-restart"),base=process.env.CHARACTER_COUNT_STATS_PROBE_EVENT_ID??"character-count-stats-g7-20260828-r1",success=`${base}-success`,actor="character-count-stats-admin",room="synthetic-character-count-room",codes=["member","pet_home","equipped_furniture","member_pet","pet_skill","member_title","pet_title","mini_pet_title","mini_pet_collection","trial_tower","pet_explore","guild","attendance_light","board","free_market"];
async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,?,'message','incoming',REPEAT('6',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id,room,actor]);}
async function snapshot(){return (await db.query<Array<{operations:bigint;outboxes:bigint;audits:bigint;executions:bigint}>>("SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope='stats.character_count.read') operations,(SELECT COUNT(*) FROM outbox_messages outbox JOIN operations operation ON operation.id=outbox.operation_id WHERE operation.idempotency_scope='stats.character_count.read') outboxes,(SELECT COUNT(*) FROM command_audit WHERE action_code='stats.character_count.read') audits,(SELECT COUNT(*) FROM admin_character_count_stat_executions) executions"))[0]!;}
try{const expected={operations:1n,outboxes:1n,audits:1n,executions:1n},service=new CharacterCountStatsService(db);if(restart){const before=await snapshot(),result=await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"});assert.ok(result!==null);assert.equal(result.projectionCount,16);assert.deepEqual(await snapshot(),before);assert.deepEqual(before,expected);process.stdout.write(JSON.stringify({mode:"verify-restart",sourceCount:15,projectionCount:16,additionalMutation:false,operationalDataTouched:false})+"\n");}else{
await db.execute("INSERT INTO admin_operators(id,login_id,display_name,password_hash,status) VALUES (988920001,'character-count-probe','글자수 통계 probe','probe','active')");await db.execute("INSERT INTO admin_operator_roles(operator_id,role_id) SELECT 988920001,id FROM admin_roles WHERE code='super_admin'");await db.execute("INSERT INTO external_identities(provider_code,external_user_id,status) VALUES ('kakao',?,'linked')",[actor]);await db.execute("INSERT INTO admin_operator_external_identities(operator_id,external_identity_id) SELECT 988920001,id FROM external_identities WHERE provider_code='kakao' AND external_user_id=?",[actor]);const set=await db.execute("INSERT INTO legacy_snapshot_sets(environment_code,database_identity,snapshot_version,snapshot_at,snapshot_status) VALUES ('prod','hoibot-prod',8001,UTC_TIMESTAMP(3),'ready')");for(const code of codes){const raw=code==="member_pet"?JSON.stringify({"가":{pendant:{name:"달"}},"나":{pendantBag:[]},"다":{pendantBag:[{name:"별"}]}}):JSON.stringify({[`${code}-user`]:{value:code}});await db.execute("INSERT INTO legacy_source_snapshots(snapshot_set_id,source_code,raw_json,content_sha256,utf16_code_unit_count,entity_count,read_status,captured_at) VALUES (?,?,?,?,?,1,'valid',UTC_TIMESTAMP(3))",[set.insertId,code,raw,createHash("sha256").update(raw).digest("hex"),raw.length]);}await db.execute("UPDATE legacy_snapshot_environments SET active_snapshot_set_id=? WHERE environment_code='prod'",[set.insertId]);assert.equal((await db.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='ADMIN_CHARACTER_COUNT_STATS'"))[0]!.rollout_state,"SHADOW");await event(success);const result=await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"});assert.ok(result!==null);assert.deepEqual([result.sourceCount,result.projectionCount],[15,16]);assert.equal(result.stats.find(stat=>stat.sourceCode==="pendant")?.entityCount,"2");assert.deepEqual(await service.read({eventId:success,externalUserId:actor,destinationId:room,environment:"prod"}),result);
const rollback=`${base}-rollback`;await event(rollback);await db.execute("CREATE TRIGGER fail_character_count_probe BEFORE INSERT ON command_audit FOR EACH ROW BEGIN IF NEW.action_code='stats.character_count.read' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic character count audit failure'; END IF; END");try{await assert.rejects(()=>service.read({eventId:rollback,externalUserId:actor,destinationId:room,environment:"prod"}),/synthetic character count audit failure/);}finally{await db.execute("DROP TRIGGER IF EXISTS fail_character_count_probe");}assert.deepEqual(await snapshot(),expected);assert.equal(await db.verifyRollback(),true);process.stdout.write(JSON.stringify({mode:"probe",migrationCount:314,scenarios:["shadow-registry","permission","15-source-exact-set","16-projection","pendant-derived","utf16-code-unit","snapshot-pin","replay","audit-outbox-rollback"],effects:expected,operationalDataTouched:false},(_key,value)=>typeof value==="bigint"?Number(value):value)+"\n");}}
finally{await db.close();}
