import assert from"node:assert/strict";import{loadConfig}from"../src/config.js";import{createDatabaseClient,type DatabaseClient,type DatabaseTransaction}from"../src/database.js";import{MiniPetEquippedCustomizeService}from"../src/mini-pet/mini-pet-equipped-customize-service.js";
const c=loadConfig();if(!c.database.enabled||!/^hoibot_mini_pet_equipped_customize/i.test(c.database.name))throw new Error("isolated mini pet customize db required");let db=createDatabaseClient(c.database),svc=()=>new MiniPetEquippedCustomizeService(db),room="mini-pet-customize-room",player=990100001,identity=990100001;async function event(id:string){await db.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,?,'mini-custom-user','message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3))",[id,id,room]);}function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,v)=>inner.query(s,v),execute:(s,v)=>inner.execute(s,v),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(w:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>w({query:(s,v)=>t.query(s,v),execute:async(s,v)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("forced mini pet customize rollback");return t.execute(s,v);}}))};}
async function quantity(code:string){return(await db.query<Array<{quantity:bigint}>>("SELECT stack.quantity FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code=?",[player,code]))[0]!.quantity;}
try{await db.execute("INSERT INTO players(id,status) VALUES (?,'active')",[player]);await db.execute("INSERT INTO player_profiles(player_id,current_display_name) VALUES (?,'커스텀 대상')",[player]);await db.execute("INSERT INTO external_identities(id,player_id,provider_code,external_user_id,status) VALUES (?,?,'kakao','mini-custom-user','linked')",[identity,player]);await db.execute("INSERT INTO mini_pet_definitions(code,display_name,grade_code,grade_display_name,emoji_value,active) VALUES ('probe-custom-mini','기본이름','NORMAL','일반','🐣',TRUE)");const definition=(await db.query<Array<{id:bigint}>>("SELECT id FROM mini_pet_definitions WHERE code='probe-custom-mini'"))[0]!.id;const owned=(await db.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,equipped,bag_sequence,version) VALUES (?,?,TRUE,1,1)",[player,definition])).insertId;await db.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity) SELECT ?,id,2 FROM item_definitions WHERE code IN ('legacy-mini-pet-appearance-change-ticket','legacy-mini-pet-name-change-ticket')",[player]);
 assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM command_registry WHERE handler_key='mini_pet_equipped_customize' AND rollout_state='SHADOW'"))[0]!.count_value,2n);
 await event("custom-appearance");const appearance=await svc().handle({eventId:"custom-appearance",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫외형 😺"});assert.equal(appearance.status,"changed");assert.equal(await quantity("legacy-mini-pet-appearance-change-ticket"),1n);assert.deepEqual(await svc().handle({eventId:"custom-appearance",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫외형 😺"}),appearance);
 await event("custom-name");const name=await svc().handle({eventId:"custom-name",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 호이봇"});assert.equal(name.status,"changed");assert.equal(await quantity("legacy-mini-pet-name-change-ticket"),1n);
 await event("custom-same");assert.equal((await svc().handle({eventId:"custom-same",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 호이봇"})).status,"unchanged");assert.equal(await quantity("legacy-mini-pet-name-change-ticket"),1n);
 await event("custom-invalid");assert.equal((await svc().handle({eventId:"custom-invalid",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 abcde"})).status,"usage");assert.equal(await quantity("legacy-mini-pet-name-change-ticket"),1n);
 await db.execute("UPDATE owned_mini_pets SET equipped=FALSE,version=version+1 WHERE id=?",[owned]);await event("custom-no-equipped");assert.equal((await svc().handle({eventId:"custom-no-equipped",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 새이름"})).status,"no_equipped");await db.execute("UPDATE owned_mini_pets SET equipped=TRUE,version=version+1 WHERE id=?",[owned]);
 await db.execute("UPDATE inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id SET stack.quantity=0,stack.version=stack.version+1 WHERE stack.player_id=? AND item.code='legacy-mini-pet-name-change-ticket'",[player]);await event("custom-no-ticket");assert.equal((await svc().handle({eventId:"custom-no-ticket",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 새이름"})).status,"missing_ticket");await db.execute("UPDATE inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id SET stack.quantity=2,stack.version=stack.version+1 WHERE stack.player_id=? AND item.code='legacy-mini-pet-name-change-ticket'",[player]);
 const before=(await db.query("SELECT custom_emoji,version FROM owned_mini_pets WHERE id=?",[owned]))[0],ticketBefore=await quantity("legacy-mini-pet-appearance-change-ticket");await event("custom-rollback");await assert.rejects(new MiniPetEquippedCustomizeService(failAudit(db)).handle({eventId:"custom-rollback",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫외형 🐶"}),/forced mini pet customize rollback/);assert.deepEqual((await db.query("SELECT custom_emoji,version FROM owned_mini_pets WHERE id=?",[owned]))[0],before);assert.equal(await quantity("legacy-mini-pet-appearance-change-ticket"),ticketBefore);
 await event("custom-concurrent");const concurrentInput={eventId:"custom-concurrent",externalUserId:"mini-custom-user",channelId:room,message:"/미니펫이름 동시"};const concurrent=await Promise.all([svc().handle(concurrentInput),svc().handle(concurrentInput)]);assert.deepEqual(concurrent[0],concurrent[1]);assert.equal(await quantity("legacy-mini-pet-name-change-ticket"),1n);assert.equal((await db.query<Array<{count_value:bigint}>>("SELECT COUNT(*) count_value FROM mini_pet_customization_ledger WHERE operation_id=(SELECT id FROM operations WHERE idempotency_scope=? AND idempotency_key='custom-concurrent')",[`mini_pet.equipped.customize:${identity}`]))[0]!.count_value,1n);
 assert.equal(await db.verifyRollback(),true);await db.close();db=createDatabaseClient(c.database);assert.deepEqual(await svc().handle(concurrentInput),concurrent[0]);const state=(await db.query<Array<{custom_name:string;custom_emoji:string;ledger_count:bigint;inventory_ledger_count:bigint}>>("SELECT custom_name,custom_emoji,(SELECT COUNT(*) FROM mini_pet_customization_ledger) ledger_count,(SELECT COUNT(*) FROM inventory_ledger WHERE reason_code LIKE 'MINI_PET_%_CUSTOMIZE') inventory_ledger_count FROM owned_mini_pets WHERE id=?",[owned]))[0]!;process.stdout.write(JSON.stringify({scenarios:["shadow-registry","appearance","name","same-value","invalid-before-cost","no-equipped","missing-ticket","concurrent","rollback","verify-rollback","restart-replay"],state},(_k,v)=>typeof v==="bigint"?v.toString():v)+"\n");}finally{await db.close();}
