import assert from "node:assert/strict";
import { loadConfig } from "../src/config.js";
import { createDatabaseClient,type DatabaseClient,type DatabaseTransaction } from "../src/database.js";
import { MiniPetBattleExecuteService } from "../src/mini-pet/mini-pet-battle-execute-service.js";

const config=loadConfig();if(!config.database.enabled||config.database.name!=="hoibot_mini_pet_battle_g7")throw new Error(`Blocked database: ${config.database.name}`);
const base=process.env.MINI_PET_BATTLE_EVENT_ID??"mini-pet-battle-fixed",restart=process.argv.includes("--verify-restart"),database=createDatabaseClient(config.database),service=new MiniPetBattleExecuteService(database);
async function event(id:string){await database.execute("INSERT INTO event_inbox(event_id,provider_event_id,external_channel_id,external_user_id,event_kind,direction,payload_hash,processing_status,received_at) VALUES (?,?,'synthetic-mini-room','mini-attacker','message','incoming',REPEAT('7',64),'processed',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE processing_status=VALUES(processing_status)",[id,id]);}
async function battle(id:string){return service.handle({externalUserId:"mini-attacker",channelId:"synthetic-mini-room",message:"/미니펫대전",eventId:id});}
function failAudit(inner:DatabaseClient):DatabaseClient{return{ping:()=>inner.ping(),query:(s,p)=>inner.query(s,p),execute:(s,p)=>inner.execute(s,p),verifyRollback:()=>inner.verifyRollback(),close:async()=>undefined,withTransaction:<T>(work:(t:DatabaseTransaction)=>Promise<T>)=>inner.withTransaction(t=>work({query:(s,p)=>t.query(s,p),execute:async(s,p)=>{if(s.includes("INSERT INTO command_audit"))throw new Error("synthetic mini battle audit failure");return t.execute(s,p);}}))};}
async function snapshot(){return(await database.query<Array<{operations:bigint;settlements:bigint;attempts:string;tickets:string;rewards:string}>>(`SELECT (SELECT COUNT(*) FROM operations WHERE idempotency_scope LIKE 'mini-pet.battle.execute:%') operations,(SELECT COUNT(*) FROM mini_pet_battle_settlements) settlements,(SELECT CAST(mini_battle_attempts AS CHAR) FROM player_pet_daily_records WHERE player_id=988700001 AND record_date=DATE(DATE_ADD(UTC_TIMESTAMP(),INTERVAL 9 HOUR))) attempts,(SELECT CAST(stack.quantity AS CHAR) FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=988700001 AND item.code='ITEM-MINI-PET-DUEL-RESET-TICKET') tickets,(SELECT CAST(SUM(stack.quantity) AS CHAR) FROM inventory_stacks stack JOIN mini_pet_battle_reward_definitions reward ON reward.item_id=stack.item_id WHERE stack.player_id=988700001) rewards`))[0]!;}
try{
 if(restart){const before=await snapshot();assert.equal((await battle(`${base}-free`)).replayed,true);assert.deepEqual(await snapshot(),before);process.stdout.write(`${JSON.stringify({mode:"verify-restart",operations:Number(before.operations),additionalSettlement:false,operationalDataTouched:false})}\n`);}
 else{
  await database.execute("INSERT INTO players(id,status) VALUES (988700001,'active'),(988700002,'active')");
  await database.execute("INSERT INTO player_profiles(player_id,current_display_name,level,experience) VALUES (988700001,'합성 공격자',10,0),(988700002,'합성 방어자',10,0)");
  await database.execute("INSERT INTO external_identities(player_id,provider_code,external_user_id,display_name,status) VALUES (988700001,'kakao','mini-attacker','합성 공격자','linked'),(988700002,'kakao','mini-defender','합성 방어자','linked')");
  await database.execute("INSERT INTO player_pets(id,player_id,display_name,pet_type_code,image_value,experience,enhancement_level) VALUES (988710001,988700001,'공격펫',NULL,'🐶',1000,0),(988710002,988700002,'방어펫',NULL,'🐱',1000,0)");
  await database.execute("INSERT INTO mini_pet_definitions(id,code,display_name,grade_code,grade_display_name,emoji_value,active) VALUES (988720001,'synthetic-mini-a','합성미니A','A','A','🐹',TRUE),(988720002,'synthetic-mini-b','합성미니B','B','B','🐭',TRUE)");
  for(const player of [988700001,988700002]){const definition=player===988700001?988720001:988720002;await database.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,custom_name,battle_experience,equipped) VALUES (?,?,?,2000,TRUE)",[player,definition,`장착${player}`]);for(let i=0;i<5;i++)await database.execute("INSERT INTO owned_mini_pets(player_id,mini_pet_definition_id,custom_name,battle_experience,equipped) VALUES (?,?,?,1000,FALSE)",[player,definition,`가방${player}-${i}`]);}
  await database.execute("INSERT INTO currency_accounts(player_id,currency_code,balance) VALUES (988700001,'point',0),(988700002,'point',0)");
  await database.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity) SELECT 988700001,id,2 FROM item_definitions WHERE code='ITEM-MINI-PET-DUEL-RESET-TICKET'");
  assert.equal((await database.query<Array<{rollout_state:string}>>("SELECT rollout_state FROM command_registry WHERE command_code='MINI_PET_BATTLE_EXECUTE'"))[0]!.rollout_state,"SHADOW");
  await event(`${base}-free`);const first=await battle(`${base}-free`);assert.equal(first.replayed,false);assert.deepEqual(await battle(`${base}-free`),{...first,replayed:true});
  await event(`${base}-ticket`);await battle(`${base}-ticket`);const expected={operations:2n,settlements:2n,attempts:"2",tickets:"1",rewards:"2"};assert.deepEqual(await snapshot(),expected);
  const rollbackId=`${base}-rollback`;await event(rollbackId);await assert.rejects(()=>new MiniPetBattleExecuteService(failAudit(database)).handle({externalUserId:"mini-attacker",channelId:"synthetic-mini-room",message:"/미니펫대전",eventId:rollbackId}),/synthetic mini battle audit failure/);assert.deepEqual(await snapshot(),expected);assert.equal(await database.verifyRollback(),true);
  process.stdout.write(`${JSON.stringify({mode:"probe",scenarios:["shadow-registry","free-battle","ticket-battle","deterministic-replay","atomic-rollback"],effects:{operations:2,settlements:2,attempts:2,tickets:1,rewards:2},operationalDataTouched:false})}\n`);
 }
}finally{await database.close();}
