$ErrorActionPreference="Stop"
$runtimeRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."));$worktreeRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot "..\.."));$temporaryRoot=[IO.Path]::GetFullPath((Join-Path $worktreeRoot ".tmp\wave23-mutations-mariadb"));$dataDirectory=Join-Path $temporaryRoot "data"
$mariaBin="C:\Program Files\MariaDB 12.2\bin";$installDatabase=Join-Path $mariaBin "mariadb-install-db.exe";$serverBinary=Join-Path $mariaBin "mariadbd.exe";$clientBinary=Join-Path $mariaBin "mariadb.exe";$port=3351;$password="wave23-isolated-root-only";$serverProcess=$null
$databases=@{furniture="hoibot_wbs787_furniture_place_2615_wave23";mini="hoibot_wave23_mini_pet_acquire_2619";skill="hoibot_wbs789_pet_skill_grant_2617_wave23"}
$productionBefore=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique)
$names=@("DATABASE_ENABLED","DATABASE_HOST","DATABASE_PORT","DATABASE_USER","DATABASE_PASSWORD","DATABASE_NAME","HOIBOT_ENVIRONMENT_CODE","IRIS_SHARED_TOKEN","USER_VERIFICATION_PEPPER");$saved=@{};foreach($name in $names){$saved[$name]=[Environment]::GetEnvironmentVariable($name,"Process")}
function Assert-SafeRoot{if(-not$temporaryRoot.StartsWith($worktreeRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Unsafe Wave23 temporary temporary path"}}
function Invoke-Checked([scriptblock]$command){&$command;if($LASTEXITCODE-ne 0){throw "Wave23 child command failed: $LASTEXITCODE"}}
function Start-Isolated{$script:serverProcess=Start-Process -FilePath $serverBinary -ArgumentList @("--no-defaults","--datadir=$dataDirectory","--port=$port","--bind-address=127.0.0.1","--skip-networking=0","--pid-file=$(Join-Path $temporaryRoot 'mariadbd.pid')","--log-error=$(Join-Path $temporaryRoot 'mariadbd.err')") -PassThru -WindowStyle Hidden;for($attempt=0;$attempt-lt 150;$attempt+=1){if($script:serverProcess.HasExited){throw "Wave23 MariaDB exited early"};if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){return};Start-Sleep -Milliseconds 200};throw "Wave23 MariaDB startup timeout"}
function Stop-Isolated{if($null-ne$script:serverProcess-and-not$script:serverProcess.HasExited){Stop-Process -Id $script:serverProcess.Id;$script:serverProcess.WaitForExit(10000)|Out-Null}}
function New-Database([string]$name,[string[]]$migrations){Invoke-Checked{&$clientBinary --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--execute=CREATE DATABASE $name CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"};foreach($migration in $migrations){$migrationPath=(Join-Path $runtimeRoot "migrations\$migration").Replace("\","/");Invoke-Checked{&$clientBinary --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--database=$name" "--execute=SOURCE $migrationPath"}}}
try{
  Assert-SafeRoot;if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){throw "Wave23 port already in use"};if(Test-Path -LiteralPath $temporaryRoot){Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};New-Item -ItemType Directory -Path $temporaryRoot|Out-Null
  Invoke-Checked{&$installDatabase "--datadir=$dataDirectory" "--password=$password" "--port=$port" --allow-remote-root-access --silent};Start-Isolated
  New-Database $databases.furniture @("443_object_identity_audit_provider.sql","444_canonical_item_inventory.sql","445_object_furniture_home_canonical_model.sql")
  New-Database $databases.mini @("443_object_identity_audit_provider.sql","444_canonical_item_inventory.sql","447_canonical_mini_pet.sql")
  New-Database $databases.skill @("443_object_identity_audit_provider.sql","444_canonical_item_inventory.sql","446_canonical_pet_equipment.sql","449_canonical_pet_skill.sql")
  $env:DATABASE_ENABLED="true";$env:DATABASE_HOST="127.0.0.1";$env:DATABASE_PORT=[string]$port;$env:DATABASE_USER="root";$env:DATABASE_PASSWORD=$password;$env:DATABASE_NAME=$databases.mini;$env:HOIBOT_ENVIRONMENT_CODE="dev";$env:IRIS_SHARED_TOKEN="wave23-isolated-token";$env:USER_VERIFICATION_PEPPER="wave23-isolated-pepper"
  Push-Location $runtimeRoot;try{Invoke-Checked{&node --import tsx scripts/build-object-db-consumer-executable-parity-wave23-fixture.ts};Invoke-Checked{&node --import tsx scripts/seal-object-db-consumer-executable-parity-wave23-mutations.ts}}finally{Pop-Location}
  $productionAfter=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique);if(Compare-Object $productionBefore $productionAfter){throw "Production 3306 listener changed"}
  Write-Output "WAVE23_ISOLATED_MARIADB_PASS consumers=3 scenarios=18 migrations=443+444+445/447/446+449 restartDistinctPid=true concurrencySingleWriter=true production3306Unchanged=true"
}finally{Stop-Isolated;$remaining=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($null-eq$remaining-and(Test-Path -LiteralPath $temporaryRoot)){Assert-SafeRoot;Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};foreach($name in $names){if($null-eq$saved[$name]){Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath "Env:$name" -Value $saved[$name]}};if($null-ne$remaining){throw "Wave23 listener remained"}}
