$ErrorActionPreference="Stop"
$runtimeRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."));$worktreeRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot "..\.."));$temporaryRoot=[IO.Path]::GetFullPath((Join-Path $worktreeRoot ".tmp\wave13-server-stats-mariadb"));$expectedRoot=$temporaryRoot;$dataDirectory=Join-Path $temporaryRoot "data"
$mariaBin="C:\Program Files\MariaDB 12.2\bin";$installDatabase=Join-Path $mariaBin "mariadb-install-db.exe";$serverBinary=Join-Path $mariaBin "mariadbd.exe";$clientBinary=Join-Path $mariaBin "mariadb.exe";$port=3330;$databaseName="hoibot_wave13_server_stats";$password="wave13-isolated-root-only";$serverProcess=$null;$productionBefore=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique)
$names=@("DATABASE_ENABLED","DATABASE_HOST","DATABASE_PORT","DATABASE_USER","DATABASE_PASSWORD","DATABASE_NAME","HOIBOT_ENVIRONMENT_CODE","IRIS_SHARED_TOKEN","USER_VERIFICATION_PEPPER","WAVE13_ISOLATED_MARIADB_TEST");$saved=@{};foreach($name in $names){$saved[$name]=[Environment]::GetEnvironmentVariable($name,"Process")}
function Assert-SafeRoot{if($temporaryRoot-ne$expectedRoot-or-not$temporaryRoot.StartsWith($worktreeRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Unsafe Wave13 temporary path: $temporaryRoot"}}
function Invoke-Checked([scriptblock]$command){&$command;if($LASTEXITCODE-ne 0){throw "Wave13 child command failed: $LASTEXITCODE"}}
function Start-Isolated{$script:serverProcess=Start-Process -FilePath $serverBinary -ArgumentList @("--no-defaults","--datadir=$dataDirectory","--port=$port","--bind-address=127.0.0.1","--skip-networking=0","--pid-file=$(Join-Path $temporaryRoot 'mariadbd.pid')","--log-error=$(Join-Path $temporaryRoot 'mariadbd.err')") -PassThru -WindowStyle Hidden;for($attempt=0;$attempt-lt 150;$attempt+=1){if($script:serverProcess.HasExited){throw "Wave13 MariaDB exited early"};$listener=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($null-ne$listener){$owners=@($listener|Select-Object -ExpandProperty OwningProcess -Unique);if($owners.Count-ne 1-or$owners[0]-ne$script:serverProcess.Id){throw "Wave13 listener ownership mismatch"};return};Start-Sleep -Milliseconds 200};throw "Wave13 MariaDB startup timeout"}
function Stop-Isolated{if($null-eq$script:serverProcess){return};if(-not$script:serverProcess.HasExited){Stop-Process -Id $script:serverProcess.Id;$script:serverProcess.WaitForExit(10000)|Out-Null};for($attempt=0;$attempt-lt 50;$attempt+=1){if($null-eq(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue)){return};Start-Sleep -Milliseconds 200};throw "Wave13 listener did not clear"}
try{Assert-SafeRoot;if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){throw "Wave13 port already in use"};foreach($binary in @($installDatabase,$serverBinary,$clientBinary)){if(-not(Test-Path -LiteralPath $binary -PathType Leaf)){throw "Missing MariaDB binary: $binary"}};if(Test-Path -LiteralPath $temporaryRoot){Assert-SafeRoot;Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};New-Item -ItemType Directory -Path $temporaryRoot|Out-Null;Invoke-Checked{&$installDatabase "--datadir=$dataDirectory" "--password=$password" "--port=$port" --allow-remote-root-access --silent};Start-Isolated;Invoke-Checked{&$clientBinary --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--execute=CREATE DATABASE $databaseName CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"};$env:DATABASE_ENABLED="true";$env:DATABASE_HOST="127.0.0.1";$env:DATABASE_PORT=[string]$port;$env:DATABASE_USER="root";$env:DATABASE_PASSWORD=$password;$env:DATABASE_NAME=$databaseName;$env:HOIBOT_ENVIRONMENT_CODE="dev";$env:IRIS_SHARED_TOKEN="wave13-isolated-token";$env:USER_VERIFICATION_PEPPER="wave13-isolated-pepper";$env:WAVE13_ISOLATED_MARIADB_TEST="true";Push-Location $runtimeRoot;try{Invoke-Checked{&node --import tsx scripts/migrate.ts};Invoke-Checked{&node --import tsx --test test/server-stats-wave13-http-mariadb.integration.test.ts}}finally{Pop-Location};$productionAfter=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique);if(Compare-Object $productionBefore $productionAfter){throw "Production 3306 listener changed"};Write-Output "WAVE13_ISOLATED_MARIADB_PASS consumer=admin-command-5e04d0767d4c2abc migrations=all replay=true rollback=true production3306Unchanged=true"}
finally{$errors=[Collections.Generic.List[string]]::new();try{Stop-Isolated}catch{$errors.Add($_.Exception.Message)};$remaining=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($null-ne$remaining){$errors.Add("Wave13 listener remained")};if($null-eq$remaining){try{Assert-SafeRoot;if(Test-Path -LiteralPath $temporaryRoot){Remove-Item -LiteralPath $temporaryRoot -Recurse -Force}}catch{$errors.Add($_.Exception.Message)}};foreach($name in $names){if($null-eq$saved[$name]){Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath "Env:$name" -Value $saved[$name]}};if($errors.Count-gt 0){throw "Wave13 cleanup failed: $($errors-join ' | ')"}}
