$ErrorActionPreference="Stop"
$runtimeRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."));$worktreeRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot "..\.."));$temporaryRoot=[IO.Path]::GetFullPath((Join-Path $worktreeRoot ".tmp\wave21-pet-equipment-assign-mariadb"));$dataDirectory=Join-Path $temporaryRoot "data"
$mariaBin="C:\Program Files\MariaDB 12.2\bin";$installDatabase=Join-Path $mariaBin "mariadb-install-db.exe";$serverBinary=Join-Path $mariaBin "mariadbd.exe";$clientBinary=Join-Path $mariaBin "mariadb.exe";$port=3343;$databaseName="hoibot_wave21_pet_equipment_assign_2613";$password="wave21-isolated-root-only";$serverProcess=$null;$productionBefore=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique)
$names=@("DATABASE_ENABLED","DATABASE_HOST","DATABASE_PORT","DATABASE_USER","DATABASE_PASSWORD","DATABASE_NAME","HOIBOT_ENVIRONMENT_CODE","IRIS_SHARED_TOKEN","USER_VERIFICATION_PEPPER");$saved=@{};foreach($name in $names){$saved[$name]=[Environment]::GetEnvironmentVariable($name,"Process")}
function Assert-SafeRoot{if(-not$temporaryRoot.StartsWith($worktreeRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Unsafe Wave21 temporary path"}}
function Invoke-Checked([scriptblock]$command){&$command;if($LASTEXITCODE-ne 0){throw "Wave21 child command failed: $LASTEXITCODE"}}
function Start-Isolated{$script:serverProcess=Start-Process -FilePath $serverBinary -ArgumentList @("--no-defaults","--datadir=$dataDirectory","--port=$port","--bind-address=127.0.0.1","--skip-networking=0","--pid-file=$(Join-Path $temporaryRoot 'mariadbd.pid')","--log-error=$(Join-Path $temporaryRoot 'mariadbd.err')") -PassThru -WindowStyle Hidden;for($attempt=0;$attempt-lt 150;$attempt+=1){if($script:serverProcess.HasExited){throw "Wave21 MariaDB exited early"};$listener=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($null-ne$listener){return};Start-Sleep -Milliseconds 200};throw "Wave21 MariaDB startup timeout"}
function Stop-Isolated{if($null-ne$script:serverProcess-and-not$script:serverProcess.HasExited){Stop-Process -Id $script:serverProcess.Id;$script:serverProcess.WaitForExit(10000)|Out-Null}}
try{Assert-SafeRoot;if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){throw "Wave21 port already in use"};if(Test-Path -LiteralPath $temporaryRoot){Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};New-Item -ItemType Directory -Path $temporaryRoot|Out-Null;Invoke-Checked{&$installDatabase "--datadir=$dataDirectory" "--password=$password" "--port=$port" --allow-remote-root-access --silent};Start-Isolated;Invoke-Checked{&$clientBinary --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--execute=CREATE DATABASE $databaseName CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"};foreach($migration in @("443_object_identity_audit_provider.sql","444_canonical_item_inventory.sql","446_canonical_pet_equipment.sql")){$migrationPath=(Join-Path $runtimeRoot "migrations\$migration").Replace("\","/");Invoke-Checked{&$clientBinary --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--database=$databaseName" "--execute=SOURCE $migrationPath"}};$env:DATABASE_ENABLED="true";$env:DATABASE_HOST="127.0.0.1";$env:DATABASE_PORT=[string]$port;$env:DATABASE_USER="root";$env:DATABASE_PASSWORD=$password;$env:DATABASE_NAME=$databaseName;$env:HOIBOT_ENVIRONMENT_CODE="dev";$env:IRIS_SHARED_TOKEN="wave21-isolated-token";$env:USER_VERIFICATION_PEPPER="wave21-isolated-pepper";Push-Location $runtimeRoot;try{Invoke-Checked{&node --import tsx scripts/seal-object-db-consumer-executable-parity-wave21-pet-equipment-assign.ts}}finally{Pop-Location};$productionAfter=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique);if(Compare-Object $productionBefore $productionAfter){throw "Production 3306 listener changed"};Write-Output "WAVE21_ISOLATED_MARIADB_PASS consumer=sql-repository-4f896a4a6feb5ec1 migrations=443+444+446 scenarios=6 successCommittedRows=6 rollbackAffectedRows=4 restartDistinctPid=true concurrencySingleWriter=true production3306Unchanged=true"}
finally{Stop-Isolated;$remaining=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($null-eq$remaining-and(Test-Path -LiteralPath $temporaryRoot)){Assert-SafeRoot;Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};foreach($name in $names){if($null-eq$saved[$name]){Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath "Env:$name" -Value $saved[$name]}};if($null-ne$remaining){throw "Wave21 listener remained"}}
