$ErrorActionPreference='Stop'
$runtimeRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$worktreeRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot '../..'))
$temporaryRoot=[IO.Path]::GetFullPath((Join-Path $worktreeRoot '.tmp/wave26-rocket-lease2625'));$evidenceRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot '../migration-control/evidence/object-db-executable-parity-ledger-wave26-wbs793-lease2625'));$dataDirectory=Join-Path $temporaryRoot 'data'
$mariaBin='C:/Program Files/MariaDB 12.2/bin';$port=3360;$password='wave26-isolated-root-only';$databaseName='hoibot_wave26_rocket_2625';$server=$null;$started=@();$protectedBefore=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique)
$names=@('DATABASE_ENABLED','DATABASE_HOST','DATABASE_PORT','DATABASE_USER','DATABASE_PASSWORD','DATABASE_NAME','HOIBOT_ENVIRONMENT_CODE','IRIS_SHARED_TOKEN','USER_VERIFICATION_PEPPER');$saved=@{};foreach($name in $names){$saved[$name]=[Environment]::GetEnvironmentVariable($name,'Process')}
function Run([scriptblock]$command,[string]$log){&$command 2>&1|Tee-Object -FilePath (Join-Path $evidenceRoot $log);if($LASTEXITCODE-ne 0){throw "Wave26 child failed: $log"}}
function Start-Db{$script:server=Start-Process -FilePath (Join-Path $mariaBin 'mariadbd.exe') -ArgumentList @('--no-defaults',"--datadir=$dataDirectory","--port=$port",'--bind-address=127.0.0.1','--skip-networking=0','--innodb-lock-wait-timeout=2',"--pid-file=$temporaryRoot/mariadbd.pid","--log-error=$temporaryRoot/mariadbd.err") -PassThru -WindowStyle Hidden;$script:started+=$script:server.Id;for($i=0;$i-lt 160;$i++){if($script:server.HasExited){throw 'Wave26 MariaDB exited'};if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){return};Start-Sleep -Milliseconds 250};throw 'Wave26 startup timeout'}
function Stop-Db{if($null-ne$script:server-and-not$script:server.HasExited){Stop-Process -Id $script:server.Id;$script:server.WaitForExit(10000)|Out-Null}}
try{if(-not$temporaryRoot.StartsWith($worktreeRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Unsafe Wave26 path'};if(Test-Path $temporaryRoot){Remove-Item -LiteralPath $temporaryRoot -Recurse -Force};New-Item -ItemType Directory $temporaryRoot,$evidenceRoot -Force|Out-Null;&(Join-Path $mariaBin 'mariadb-install-db.exe') "--datadir=$dataDirectory" "--password=$password" "--port=$port" --silent;if($LASTEXITCODE-ne 0){throw 'Wave26 install failed'};Start-Db;&(Join-Path $mariaBin 'mariadb.exe') --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--execute=CREATE DATABASE $databaseName CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";if($LASTEXITCODE-ne 0){throw 'Wave26 create failed'};$env:DATABASE_ENABLED='true';$env:DATABASE_HOST='127.0.0.1';$env:DATABASE_PORT=[string]$port;$env:DATABASE_USER='root';$env:DATABASE_PASSWORD=$password;$env:DATABASE_NAME=$databaseName;$env:HOIBOT_ENVIRONMENT_CODE='dev';$env:IRIS_SHARED_TOKEN='wave26-no-network';$env:USER_VERIFICATION_PEPPER='wave26-no-network-pepper';Push-Location $runtimeRoot;try{Run {&node --import tsx scripts/migrate.ts} 'migration-first.txt';Run {&node --import tsx scripts/migrate.ts} 'migration-replay.txt';Run {&node --import tsx scripts/seal-object-db-consumer-executable-parity-wave26-rocket.ts} 'fixture-seal.txt'}finally{Pop-Location}}finally{Stop-Db;$remaining=@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue);$protectedAfter=@(Get-NetTCPConnection -State Listen -LocalPort 3306 -ErrorAction SilentlyContinue|Select-Object -ExpandProperty OwningProcess -Unique);if(Test-Path $evidenceRoot){@{port=$port;database=$databaseName;startedPids=$started;listenerRemoved=($remaining.Count-eq 0);production3306Unchanged=([string]$protectedBefore-eq[string]$protectedAfter)}|ConvertTo-Json|Set-Content -Encoding utf8 (Join-Path $evidenceRoot 'lifecycle.json')};foreach($name in $names){[Environment]::SetEnvironmentVariable($name,$saved[$name],'Process')};if($remaining.Count-ne 0){throw 'Wave26 listener remained'};if([string]$protectedBefore-ne[string]$protectedAfter){throw 'Wave26 production listener changed'}}
