import { createHash } from "node:crypto";
import { execFileSync,spawn } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";

const runtimeRoot=resolve(import.meta.dirname,".."),repoRoot=resolve(runtimeRoot,"../.."),target=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave26-rocket-target.ts"),runRoot=mkdtempSync(join(tmpdir(),"wave26-rocket-"));
const fixturePath=resolve(repoRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-executable-parity-wave26-rocket-v1.json"),manifest=JSON.parse(readFileSync(resolve(repoRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"),"utf8"));
const source=readFileSync(resolve(repoRoot,"main.js"),"utf8").replace(/\r\n?/g,"\n"),sha=(v:string)=>createHash("sha256").update(v).digest("hex");
const consumers=manifest.consumers.filter((x:any)=>/^\/로켓\d+,$/.test(x.triggerOrPredicate)).map((x:any)=>({...x,rocketNo:Number(/\d+/.exec(x.triggerOrPredicate)![0])})).sort((a:any,b:any)=>a.rocketNo-b.rocketNo);
if(consumers.length!==10||consumers.some((x:any)=>x.status!=="IN_SCOPE"||x.interfaceId!=="item.admin-grant.execute"||x.sourceSpan.start!==469110||x.sourceSpan.end!==470441||x.sourceSpan.sha256!=="2b7d993d0112180779b2f2e0f37958b5fa590a23b4bac0075b2367cb01f1714f"))throw new Error("Wave26 frozen rocket cohort drift");
const run=(name:string,payload:any)=>{const input=join(runRoot,`${name}.in.json`),output=join(runRoot,`${name}.out.json`);writeFileSync(input,JSON.stringify(payload));execFileSync(process.execPath,["--import","tsx",target,input,output],{cwd:runtimeRoot,env:process.env,stdio:"pipe",timeout:120000});return JSON.parse(readFileSync(output,"utf8"));};
const concurrent=(name:string,payload:any)=>new Promise<any>((ok,fail)=>{const input=join(runRoot,`${name}.in.json`),output=join(runRoot,`${name}.out.json`);writeFileSync(input,JSON.stringify(payload));const child=spawn(process.execPath,["--import","tsx",target,input,output],{cwd:runtimeRoot,env:process.env,stdio:"pipe"});let stderr="";child.stderr.on("data",x=>stderr+=x);child.on("error",fail);child.on("close",code=>code===0?ok(JSON.parse(readFileSync(output,"utf8"))):fail(new Error(stderr)));});
const reset=()=>run(`reset-${Date.now()}`,{mode:"RESET"}),message=(n:number)=>`/로켓${n}, 대상 회원`;
try{
  const observations:any[]=[];
  reset();observations.push({scenarioKind:"MUTATION_SUCCESS",traces:[run("success",{mode:"EXEC",role:"PRIMARY",eventId:"wave26-success",message:message(1)})]});
  reset();run("fail-setup",{mode:"FAIL_ON_AUDIT"});observations.push({scenarioKind:"DOMAIN_FAILURE_ROLLBACK",traces:[run("failure",{mode:"EXEC",role:"PRIMARY",eventId:"wave26-failure",message:message(1)})]});
  reset();observations.push({scenarioKind:"DUPLICATE_REPLAY_DML_ZERO",traces:[run("duplicate-seed",{mode:"EXEC",role:"SEED",eventId:"wave26-duplicate",message:message(1)}),run("duplicate-replay",{mode:"EXEC",role:"REPLAY",eventId:"wave26-duplicate",message:message(1)})]});
  reset();observations.push({scenarioKind:"PAYLOAD_DRIFT_FAIL_CLOSED",traces:[run("drift-seed",{mode:"EXEC",role:"SEED",eventId:"wave26-drift",message:message(1)}),run("drift-primary",{mode:"EXEC",role:"PRIMARY",eventId:"wave26-drift",message:message(2)})]});
  reset();observations.push({scenarioKind:"RESTART_REPLAY",traces:[run("restart-seed",{mode:"EXEC",role:"SEED",eventId:"wave26-restart",message:message(1)}),run("restart-replay",{mode:"EXEC",role:"REPLAY",eventId:"wave26-restart",message:message(1)})]});
  reset();const pair=await Promise.all([concurrent("concurrent-a",{mode:"EXEC",role:"CONCURRENT",eventId:"wave26-concurrency",message:message(1)}),concurrent("concurrent-b",{mode:"EXEC",role:"CONCURRENT",eventId:"wave26-concurrency",message:message(1)})]);const writer=pair.find(x=>x.committedRowCount>0),replay=pair.find(x=>x!==writer);if(!writer||!replay||!replay.replayed)throw new Error("Wave26 concurrency single-writer drift");writer.role="PRIMARY";observations.push({scenarioKind:"CONCURRENCY_SINGLE_WRITER",traces:[writer,replay]});
  reset();observations.push({scenarioKind:"AUTH_DENIED",traces:[run("auth",{mode:"AUTH",role:"PRIMARY",eventId:"wave26-auth",message:message(1)})]});
  reset();const shadow=run("shadow",{mode:"SHADOW",role:"PRIMARY",eventId:"wave26-shadow",message:message(1)});if(shadow.errorCode!=="WAVE26_SHADOW_ROLLBACK"||shadow.committedRowCount!==0||shadow.beforeSha256!==shadow.afterSha256)throw new Error("Wave26 Shadow invariant drift");
  const representative=consumers[0],variants=consumers.map((x:any)=>({consumerId:x.consumerId,trigger:x.triggerOrPredicate,rocketNo:x.rocketNo,itemName:`로켓배송패키지🚀[${x.rocketNo}](/호팡오픈${x.rocketNo})`,reply:`[대상 회원]님에게 로켓배송패키지🚀[${x.rocketNo}](/호팡오픈${x.rocketNo})가 지급되었습니다.`,payload:{amount:"1",targetLegacyKey:"대상 회원",reasonType:"ADMIN_ROCKET_PACKAGE_GRANT",itemName:`로켓배송패키지🚀[${x.rocketNo}](/호팡오픈${x.rocketNo})`}}));
  const cohortProjectionSha256=sha(JSON.stringify(variants));
  const fixture={format:"hoibot-object-db-consumer-parity-case-fixture-v1",fixtureId:"fixture:object-db-executable-parity:wave26:rocket:v1",sliceId:"WBS793",cohortId:"ITEM-ROCKET-ADMIN-GRANT-01",representativeConsumerId:representative.consumerId,source:{path:"main.js",sha256:sha(source),spanStart:469110,spanEnd:470441,spanSha256:sha(source.slice(469110,470441))},runtimeSourcePaths:["개발환경_고도화/runtime/src/admin/admin-stack-grant-service.ts","개발환경_고도화/runtime/src/admin/rocket-package-grant-service.ts","개발환경_고도화/runtime/src/admin/iris-admin-command-service.ts","개발환경_고도화/runtime/src/inventory/canonical-item-inventory-repository.ts","개발환경_고도화/runtime/src/database.ts","개발환경_고도화/runtime/migrations/491_admin_rocket_package_grant.sql"],allowedTables:["operations","outbox_messages","command_executions","command_audit","canonical_owned_item_stacks","canonical_item_inventory_operations","canonical_item_inventory_ledger_entries"],variants,cohortProjectionSha256,scenarioKinds:["MUTATION_SUCCESS","DOMAIN_FAILURE_ROLLBACK","DUPLICATE_REPLAY_DML_ZERO","PAYLOAD_DRIFT_FAIL_CLOSED","RESTART_REPLAY","CONCURRENCY_SINGLE_WRITER","AUTH_DENIED"],observations,wrongRoom:{disposition:"NOT_APPLICABLE",ruleId:"SOURCE_CLASSIFICATION_HAS_NO_ROOM_GUARD_V1",sourceSpanSha256:representative.sourceSpan.sha256},shadowObservation:shadow};
  if(fixture.source.spanSha256!=="2b7d993d0112180779b2f2e0f37958b5fa590a23b4bac0075b2367cb01f1714f")throw new Error("Wave26 live source span drift");
  writeFileSync(fixturePath,JSON.stringify(fixture,null,2)+"\n");console.log(JSON.stringify({status:"PASS",consumers:10,scenarios:7,cohortProjectionSha256,shadow:{rollback:true,committed:0},pids:new Set(observations.flatMap(x=>x.traces.map((t:any)=>t.processId))).size}));
}finally{rmSync(runRoot,{recursive:true,force:true});}
