import { createHash } from "node:crypto";
import { execFileSync,spawn } from "node:child_process";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,resolve } from "node:path";

const runtimeRoot=resolve(import.meta.dirname,".."),repoRoot=resolve(runtimeRoot,"../.."),target=resolve(runtimeRoot,"test/fixtures/object-db-executable-parity-wave27-slot-newbie-target.ts"),runRoot=mkdtempSync(join(tmpdir(),"wave27-slot-newbie-"));
const fixturePath=resolve(repoRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-executable-parity-wave27-slot-newbie-v1.json"),manifest=JSON.parse(readFileSync(resolve(repoRoot,"개발환경_고도화/migration-control/contracts/object-db-consumer-manifest.v1.json"),"utf8"));
const source=readFileSync(resolve(repoRoot,"main.js"),"utf8").replace(/\r\n?/g,"\n"),sha=(value:string)=>createHash("sha256").update(value).digest("hex"),ids=["legacy-36588f6a2db3277d","legacy-02d447882f335ea1","legacy-ac46db2ac0deedf4","legacy-f51202b9335997d8"];
const consumers=manifest.consumers.filter((candidate:any)=>ids.includes(candidate.consumerId)).map((candidate:any)=>{const suffix=/슬롯초보([2-4])?,/.exec(candidate.triggerOrPredicate)?.[1];return{...candidate,variantNo:suffix===undefined?1:Number(suffix)}}).sort((left:any,right:any)=>left.variantNo-right.variantNo);
if(consumers.length!==4||consumers.some((candidate:any)=>candidate.status!=="IN_SCOPE"||candidate.access!=="READ_WRITE"||candidate.interfaceId!=="item.admin-grant.execute"||candidate.transactionOwnerInterfaceId!=="item.admin-grant.execute"||JSON.stringify(candidate.transactionParticipantInterfaceIds)!==JSON.stringify(["item.inventory.mutate"])))throw new Error("Wave27 frozen slot newbie cohort drift");
const run=(name:string,payload:any)=>{const input=join(runRoot,`${name}.in.json`),output=join(runRoot,`${name}.out.json`);writeFileSync(input,JSON.stringify(payload));execFileSync(process.execPath,["--import","tsx",target,input,output],{cwd:runtimeRoot,env:process.env,stdio:"pipe",timeout:120000});return JSON.parse(readFileSync(output,"utf8"));};
const concurrent=(name:string,payload:any)=>new Promise<any>((resolvePromise,rejectPromise)=>{const input=join(runRoot,`${name}.in.json`),output=join(runRoot,`${name}.out.json`);writeFileSync(input,JSON.stringify(payload));const child=spawn(process.execPath,["--import","tsx",target,input,output],{cwd:runtimeRoot,env:process.env,stdio:"pipe"});let stderr="";child.stderr.on("data",chunk=>stderr+=chunk);child.on("error",rejectPromise);child.on("close",code=>code===0?resolvePromise(JSON.parse(readFileSync(output,"utf8"))):rejectPromise(new Error(stderr)));});
const reset=()=>run(`reset-${Date.now()}`,{mode:"RESET"}),message=(variantNo:number)=>`/슬롯초보${variantNo===1?"":variantNo}, 대상 회원`;
try{
  const observations:any[]=[];
  reset();observations.push({scenarioKind:"MUTATION_SUCCESS",traces:[run("success",{mode:"EXEC",role:"PRIMARY",eventId:"wave27-success",message:message(1)})]});
  reset();run("fail-setup",{mode:"FAIL_ON_AUDIT"});observations.push({scenarioKind:"DOMAIN_FAILURE_ROLLBACK",traces:[run("failure",{mode:"EXEC",role:"PRIMARY",eventId:"wave27-failure",message:message(1)})]});
  reset();observations.push({scenarioKind:"DUPLICATE_REPLAY_DML_ZERO",traces:[run("duplicate-seed",{mode:"EXEC",role:"SEED",eventId:"wave27-duplicate",message:message(1)}),run("duplicate-replay",{mode:"EXEC",role:"REPLAY",eventId:"wave27-duplicate",message:message(1)})]});
  reset();observations.push({scenarioKind:"PAYLOAD_DRIFT_FAIL_CLOSED",traces:[run("drift-seed",{mode:"EXEC",role:"SEED",eventId:"wave27-drift",message:message(1)}),run("drift-primary",{mode:"EXEC",role:"PRIMARY",eventId:"wave27-drift",message:message(2)})]});
  reset();observations.push({scenarioKind:"RESTART_REPLAY",traces:[run("restart-seed",{mode:"EXEC",role:"SEED",eventId:"wave27-restart",message:message(1)}),run("restart-replay",{mode:"EXEC",role:"REPLAY",eventId:"wave27-restart",message:message(1)})]});
  reset();const pair=await Promise.all([concurrent("concurrent-a",{mode:"EXEC",role:"CONCURRENT",eventId:"wave27-concurrency",message:message(1)}),concurrent("concurrent-b",{mode:"EXEC",role:"CONCURRENT",eventId:"wave27-concurrency",message:message(1)})]);const writer=pair.find(trace=>trace.committedRowCount>0),replay=pair.find(trace=>trace!==writer);if(!writer||!replay||!replay.replayed)throw new Error("Wave27 concurrency single-writer drift");writer.role="PRIMARY";observations.push({scenarioKind:"CONCURRENCY_SINGLE_WRITER",traces:[writer,replay]});
  reset();observations.push({scenarioKind:"AUTH_DENIED",traces:[run("auth",{mode:"AUTH",role:"PRIMARY",eventId:"wave27-auth",message:message(1)})]});
  reset();const shadow=run("shadow",{mode:"SHADOW",role:"PRIMARY",eventId:"wave27-shadow",message:message(1)});if(shadow.errorCode!=="WAVE27_SHADOW_ROLLBACK"||shadow.committedRowCount!==0||shadow.beforeSha256!==shadow.afterSha256)throw new Error("Wave27 Shadow invariant drift");
  const representative=consumers[0],variants=consumers.map((candidate:any)=>{const suffix=candidate.variantNo===1?"":String(candidate.variantNo),trigger=`/슬롯초보${suffix},`,itemName=`슬롯초보패키지${suffix}🪙(/슬롯초보오픈${suffix})`;return{consumerId:candidate.consumerId,trigger,predicate:`msg.startsWith(\"${trigger}\") && isMaster(sender)`,variantNo:candidate.variantNo,itemName,reply:`대상 회원님에게 슬롯초보패키지${suffix}(/슬롯초보오픈${suffix})🪙를 지급했습니다.`,payload:{amount:"1",targetLegacyKey:"대상 회원",reasonType:"ADMIN_SLOT_NEWBIE_PACKAGE_GRANT",itemName},sourceSpan:candidate.sourceSpan}});
  const cohortProjectionSha256=sha(JSON.stringify(variants)),spanStart=400947,spanEnd=403777;
  const fixture={format:"hoibot-object-db-consumer-parity-case-fixture-v1",fixtureId:"fixture:object-db-executable-parity:wave27:slot-newbie:v1",sliceId:"WBS794",cohortId:"PACKAGE-SLOT-NEWBIE-ADMIN-GRANT-01",representativeConsumerId:representative.consumerId,source:{path:"main.js",sha256:sha(source),spanStart,spanEnd,spanSha256:sha(source.slice(spanStart,spanEnd))},runtimeSourcePaths:["개발환경_고도화/runtime/src/admin/admin-stack-grant-service.ts","개발환경_고도화/runtime/src/admin/slot-newbie-package-grant-service.ts","개발환경_고도화/runtime/src/admin/iris-admin-command-service.ts","개발환경_고도화/runtime/src/inventory/canonical-item-inventory-repository.ts","개발환경_고도화/runtime/src/database.ts","개발환경_고도화/runtime/migrations/492_admin_slot_newbie_package_grant.sql"],allowedTables:["operations","outbox_messages","command_executions","command_audit","canonical_owned_item_stacks","canonical_item_inventory_operations","canonical_item_inventory_ledger_entries"],variants,cohortProjectionSha256,scenarioKinds:["MUTATION_SUCCESS","DOMAIN_FAILURE_ROLLBACK","DUPLICATE_REPLAY_DML_ZERO","PAYLOAD_DRIFT_FAIL_CLOSED","RESTART_REPLAY","CONCURRENCY_SINGLE_WRITER","AUTH_DENIED"],observations,wrongRoom:{disposition:"NOT_APPLICABLE",ruleId:"SOURCE_CLASSIFICATION_HAS_NO_ROOM_GUARD_V1",sourceSpanSha256:representative.sourceSpan.sha256},shadowObservation:shadow};
  if(fixture.source.spanSha256!=="b8116501b20b58b9050854d6a2b885e164f6534d8660a8f72a0bef1aa784b9bf")throw new Error("Wave27 live source span drift");
  writeFileSync(fixturePath,JSON.stringify(fixture,null,2)+"\n");console.log(JSON.stringify({status:"PASS",consumers:4,scenarios:7,cohortProjectionSha256,shadow:{rollback:true,committed:0},pids:new Set(observations.flatMap(entry=>entry.traces.map((trace:any)=>trace.processId))).size}));
}finally{rmSync(runRoot,{recursive:true,force:true});}
