import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const runtimeRoot = resolve(import.meta.dirname, "..");
const fixture = resolve(runtimeRoot, "test/fixtures/canonical-pet-skill-grant-targeted.mjs");
const temp = resolve(runtimeRoot, ".wbs789-targeted");
const evidencePath = resolve(runtimeRoot, "../migration-control/evidence/wbs789-pet-skill-grant/targeted-evidence.json");
interface Trace { processId:number; scenario:string; attempts:Array<{outcome:string;lockOrder:string[]}>; committedDml:string[]; committedRows:number; rolledBackAffectedRows:number; replayed:boolean|null; resultingQuantity:string|null; operationId:string|null; errorCode:string|null; beforeRows:{canonical_owned_pet_skill_stacks:Array<{quantity:string}>}; afterRows:{canonical_owned_pet_skill_stacks:Array<{quantity:string}>}; beforeSha256:string; afterSha256:string; externalNetworkCalls:number; replyCalls:number; }
function run(request:Record<string,unknown>,name:string):Trace { const input=resolve(temp,`${name}.in.json`),output=resolve(temp,`${name}.out.json`); writeFileSync(input,JSON.stringify(request)); execFileSync(process.execPath,["--import","tsx",fixture,input,output],{cwd:runtimeRoot,stdio:"pipe",timeout:120_000}); return JSON.parse(readFileSync(output,"utf8")) as Trace; }
async function concurrent(request:Record<string,unknown>,name:string):Promise<Trace> { const input=resolve(temp,`${name}.in.json`),output=resolve(temp,`${name}.out.json`); writeFileSync(input,JSON.stringify(request)); await new Promise<void>((ok,fail)=>{const child=spawn(process.execPath,["--import","tsx",fixture,input,output],{cwd:runtimeRoot,stdio:"pipe"});let stderr="";child.stderr.on("data",v=>stderr+=String(v));child.once("error",fail);child.once("close",code=>code===0?ok():fail(new Error(`WBS789 child ${code}: ${stderr}`)));}); return JSON.parse(readFileSync(output,"utf8")) as Trace; }
const reset=(name:string)=>run({mode:"RESET"},`${name}-reset`);
const noEffects=(trace:Trace)=>{assert.equal(trace.externalNetworkCalls,0);assert.equal(trace.replyCalls,0);};
async function collect() {
  mkdirSync(temp,{recursive:true});
  reset("success"); const success=run({scenario:"success"},"success"); assert.equal(success.committedRows,2); assert.deepEqual(success.attempts[0]?.lockOrder,["canonical_pet_skill_operation_replays","canonical_players","canonical_pet_skill_definitions","canonical_owned_pet_skill_stacks","object_identity_crosswalks:petSkillOperation","object_identity_crosswalks:ownedPetSkill"]); assert.deepEqual(success.committedDml.map(sql=>/^(?:INSERT INTO|UPDATE)\s+(\w+)/i.exec(sql)?.[1]),["canonical_owned_pet_skill_stacks","canonical_pet_skill_operation_replays"]);
  reset("rollback"); run({mode:"FAIL_REPLAY"},"rollback-trigger"); const rollback=run({scenario:"rollback"},"rollback"); assert.equal(rollback.committedRows,0); assert.equal(rollback.rolledBackAffectedRows,1); assert.equal(rollback.beforeSha256,rollback.afterSha256); assert.match(rollback.errorCode??"",/WBS789 forced replay failure/);
  reset("replay"); const replaySeed=run({scenario:"replay"},"replay-seed"), replay=run({scenario:"replay"},"replay"); assert.equal(replaySeed.committedRows,2); assert.equal(replay.committedRows,0); assert.equal(replay.replayed,true); assert.equal(replay.beforeSha256,replay.afterSha256);
  reset("drift"); const driftSeed=run({scenario:"drift",quantity:3},"drift-seed"), drift=run({scenario:"drift",quantity:4},"drift"); assert.equal(driftSeed.committedRows,2); assert.equal(drift.committedRows,0); assert.match(drift.errorCode??"",/REQUEST_PAYLOAD_CONFLICT/); assert.equal(drift.beforeSha256,drift.afterSha256);
  reset("restart"); const restartSeed=run({scenario:"restart"},"restart-seed"),restart=run({scenario:"restart"},"restart-replay"); assert.notEqual(restartSeed.processId,restart.processId); assert.equal(restart.committedRows,0); assert.equal(restart.replayed,true);
  reset("same-key"); const same=await Promise.all([concurrent({scenario:"same-key"},"same-a"),concurrent({scenario:"same-key"},"same-b")]); assert.deepEqual(same.map(t=>t.committedRows).sort(),[0,2]); assert.equal(same.filter(t=>t.replayed).length,1);
  reset("different-key"); const different=await Promise.all([concurrent({scenario:"different-key",keySuffix:"-a",quantity:3},"different-a"),concurrent({scenario:"different-key",keySuffix:"-b",quantity:5},"different-b")]); assert.equal(different.every(t=>t.replayed===false),true); assert.equal(different.every(t=>t.committedRows===2),true); assert.equal(different.some(t=>t.resultingQuantity==="8"),true); assert.notEqual(different[0]?.operationId,different[1]?.operationId); const differentFinal=run({scenario:"different-key",keySuffix:"-a",quantity:3},"different-final"); assert.equal(differentFinal.committedRows,0); assert.equal(differentFinal.replayed,true); assert.equal(differentFinal.afterRows.canonical_owned_pet_skill_stacks[0]?.quantity,"8");
  for(const trace of [success,rollback,replaySeed,replay,driftSeed,drift,restartSeed,restart,...same,...different,differentFinal]) noEffects(trace);
  const evidence={contractVersion:"WBS789_PET_SKILL_GRANT_TARGETED_V1",consumerId:"sql-repository-31c4099080d9c9c1",sliceId:"SL-PET-SKILL-GRANT-MUTATION-PARITY-01",executionId:"펫스킬지급DB-SL-PET-SKILL-GRANT-MUTATION-PARITY-01-20260909083514",leaseRow:2617,baselineCommit:"2304dd0fc30984b5e31d58df3fbb36f5f77167a1",migrationClosure:["443_object_identity_audit_provider.sql","444_canonical_item_inventory.sql","446_canonical_pet_equipment.sql","449_canonical_pet_skill.sql"],scenarios:{success,rollback,replay:[replaySeed,replay],drift:[driftSeed,drift],restart:[restartSeed,restart],sameKeyConcurrency:same,differentKeyConcurrency:[...different,differentFinal]}};
  mkdirSync(dirname(evidencePath),{recursive:true}); writeFileSync(evidencePath,`${JSON.stringify(evidence,null,2)}\n`); console.log(JSON.stringify({status:"PASS",scenarios:7,evidencePath}));
}
try { await collect(); } finally { rmSync(temp,{recursive:true,force:true}); }
