param([switch]$ValidateTranscriptOnly)
$ErrorActionPreference="Stop"
if ($PSVersionTable.PSEdition -ne "Core" -or $PSVersionTable.PSVersion.Major -lt 7) { throw "ITEM25_PREREQUISITE_PWSH_CORE_7_REQUIRED: run with pwsh 7+, not Windows PowerShell 5.1" }
$runtimeRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\..\..\runtime"));$worktreeRoot=[IO.Path]::GetFullPath((Join-Path $runtimeRoot "..\.."));$temporaryRoot=[IO.Path]::GetFullPath((Join-Path $worktreeRoot ".tmp\lease2556-review-mariadb"));$transcriptPath=Join-Path $PSScriptRoot "mariadb-transcript.json"
$port=3337;$databaseName="hoibot_rehearsal_item25_review2556";$password=[Guid]::NewGuid().ToString("N");$mariaBin="C:\Program Files\MariaDB 12.2\bin";$commands=[Collections.Generic.List[object]]::new()
$environmentNames=@("RUN_ITEM25_CANONICAL_MARIADB_INTEGRATION","HOIBOT_ENVIRONMENT_CODE","DATABASE_ENABLED","DATABASE_HOST","DATABASE_PORT","DATABASE_USER","DATABASE_PASSWORD","DATABASE_NAME","IRIS_SHARED_TOKEN");$savedEnvironment=@{};foreach($name in $environmentNames){$savedEnvironment[$name]=[Environment]::GetEnvironmentVariable($name,"Process")}
function Get-Sha([string]$path){(Get-FileHash -Algorithm SHA256 -LiteralPath $path).Hash.ToLowerInvariant()}
function Get-TextSha([string]$text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text)))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
function Assert-SafeTemporaryPath{if($temporaryRoot -ne [IO.Path]::GetFullPath((Join-Path $worktreeRoot ".tmp\lease2556-review-mariadb")) -or -not $temporaryRoot.StartsWith($worktreeRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "Unsafe temporary path"}}
function Invoke-Recorded([string]$name,[string]$command,[scriptblock]$operation){$started=(Get-Date).ToUniversalTime().ToString("o");$output=@(& $operation 2>&1|ForEach-Object{[string]$_});$exit=[int]$LASTEXITCODE;$commands.Add([ordered]@{name=$name;command=$command;startedAtUtc=$started;exitCode=$exit;outputSha256=Get-TextSha($output-join"`n")});if($exit-ne 0){throw "$name failed with exit $exit"};$output}
function Parse-FocusedTapSummary([string[]]$lines) {
  $summary=@{};$marker=[regex]::Escape([string][char]0x2139)
  foreach($line in $lines){if($line-match"^\s*$marker\s+(tests|pass|fail)\s+([0-9]+)\s*$"){if($summary.ContainsKey($Matches[1])){throw "FOCUSED_TAP_DUPLICATE_SUMMARY"};$summary[$Matches[1]]=[int]$Matches[2]}}
  if($summary.Count-ne3-or$summary.tests-ne26-or$summary.pass-ne26-or$summary.fail-ne0){throw "FOCUSED_TAP_EXACT_SUMMARY_INVALID"}
  [ordered]@{testCount=$summary.tests;pass=$summary.pass;fail=$summary.fail;status="PASS"}
}
function Parse-ObjectValidatorSummary([string[]]$lines) {
  $summaryLines=@($lines|Where-Object{$_-match'^valid object data model contract: .+ \(등록 대상 ([0-9]+)개\)$'})
  if($summaryLines.Count-ne1){throw "OBJECT_VALIDATOR_EXACT_SUMMARY_MISSING"};$null=$summaryLines[0]-match'^valid object data model contract: .+ \(등록 대상 ([0-9]+)개\)$';$registered=[int]$Matches[1]
  if($registered-ne98){throw "OBJECT_VALIDATOR_REGISTERED_TARGET_DRIFT"};[ordered]@{registeredTargets=$registered;pass=$registered;fail=0;status="PASS"}
}
function Get-ArtifactHashes{$relative=@("개발환경_고도화/migration-control/contracts/item25-canonical-definition-binding.v1.json","개발환경_고도화/runtime/src/data-migration/item25-canonical-definition-provider.ts","개발환경_고도화/runtime/test/item25-canonical-definition-provider.test.ts","개발환경_고도화/runtime/test/item25-canonical-definition-provider-mariadb.integration.test.ts","개발환경_고도화/migration-control/evidence/item25-canonical-definition-provider-lease2556/rehearse-item25-provider.ps1","개발환경_고도화/migration-control/evidence/item25-canonical-definition-provider-lease2556/validation.md");@($relative|ForEach-Object{[ordered]@{path=$_;sha256=Get-Sha(Join-Path $worktreeRoot $_)}})}
function Get-MigrationState {
  $files=@(Get-ChildItem -LiteralPath (Join-Path $runtimeRoot "migrations") -File|Where-Object Name -Match '^\d{3}_.+\.sql$'|Sort-Object Name)
  [ordered]@{fileCount=$files.Count;filenameAggregateSha256=Get-TextSha(($files.Name)-join"`n");contentAggregateSha256=Get-TextSha(($files|ForEach-Object{"$($_.Name):$(Get-Sha $_.FullName)"})-join"`n")}
}
function Assert-Transcript($value) {
  $hash='^[0-9a-f]{64}$';$timestamp='^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{7}Z$'
  if ($null -eq $value -or $value.format -ne "hoibot-item25-provider-mariadb-transcript-v2" -or $value.generatedAtUtc -notmatch $timestamp) { throw "TRANSCRIPT_HEADER_DRIFT" }
  if ($value.powershell.edition -ne "Core" -or $value.powershell.major -lt 7) { throw "TRANSCRIPT_PWSH_PREREQUISITE_DRIFT" }
  $reproScript='./개발환경_고도화/migration-control/evidence/item25-canonical-definition-provider-lease2556/rehearse-item25-provider.ps1'
  $expectedRepro=@("pwsh -NoProfile -File `"$reproScript`"","pwsh -NoProfile -File `"$reproScript`" -ValidateTranscriptOnly")
  if ($value.reproducibility.prerequisite -ne "PowerShell Core 7+" -or $value.reproducibility.workingDirectory -ne "repository root" -or (@($value.reproducibility.commands) -join "|") -ne ($expectedRepro -join "|")) { throw "TRANSCRIPT_REPRO_COMMAND_DRIFT" }
  $migration=Get-MigrationState
  if ($null -eq $value.migrations -or $value.migrations.range -ne "001..477" -or $value.migrations.fileCount -ne 465 -or $value.migrations.fileCount -ne $migration.fileCount -or $value.migrations.filenameAggregateSha256 -ne $migration.filenameAggregateSha256 -or $value.migrations.contentAggregateSha256 -ne $migration.contentAggregateSha256 -or $value.migrations.filenameAggregateSha256 -notmatch $hash -or $value.migrations.contentAggregateSha256 -notmatch $hash) { throw "TRANSCRIPT_MIGRATION_DRIFT" }
  if ($null -eq $value.source -or $value.source.path -ne "data/itemInfo.json" -or $value.source.aggregateSha256 -ne (Get-Sha (Join-Path $worktreeRoot "data/itemInfo.json")) -or $value.source.aggregateSha256 -notmatch $hash) { throw "TRANSCRIPT_SOURCE_STALE" }
  $expectedCommands=@("mariadb-initialize","database-create","migrations-001-477","item25-mariadb-integration","focused-26","typecheck","build","object-validator-98","json-parse","diff-check")
  if ($null -eq $value.commands -or @($value.commands).Count -ne 10 -or (@($value.commands | ForEach-Object name) -join "|") -ne ($expectedCommands -join "|")) { throw "TRANSCRIPT_COMMAND_SET_DRIFT" }
  foreach ($command in @($value.commands)) { if ($command.exitCode -ne 0 -or [String]::IsNullOrWhiteSpace($command.command) -or $command.startedAtUtc -notmatch $timestamp -or $command.outputSha256 -notmatch $hash) { throw "TRANSCRIPT_COMMAND_RESULT_DRIFT" } }
  if ($null -eq $value.results -or $value.results.focused26.testCount -ne 26 -or $value.results.focused26.pass -ne 26 -or $value.results.focused26.fail -ne 0 -or $value.results.focused26.status -ne "PASS" -or $value.results.typecheck -ne "PASS" -or $value.results.build -ne "PASS" -or $value.results.objectValidator.registeredTargets -ne 98 -or $value.results.objectValidator.pass -ne 98 -or $value.results.objectValidator.fail -ne 0 -or $value.results.objectValidator.status -ne "PASS" -or $value.results.json -ne "PASS" -or $value.results.diff -ne "PASS") { throw "TRANSCRIPT_FOCUSED_RESULT_DRIFT" }
  if ($null -eq $value.integration -or $value.integration.passed -ne $true -or $value.integration.poolCount -ne 2 -or $value.integration.singleWinner -ne $true -or $value.integration.applyInsertedBindings -ne 25 -or $value.integration.replayDml -ne 0) { throw "TRANSCRIPT_INTEGRATION_RESULT_DRIFT" }
  $expectedTables=@("canonical_item_definitions","canonical_item_definition_imports","object_identities","object_identity_crosswalks","data_migration_common_staging_runs","data_migration_common_staging_records","data_migration_catalog_projection_runs","data_migration_catalog_source_decisions","data_migration_catalog_projection_records","data_migration_object_domain_import_runs","data_migration_object_domain_import_decisions","data_migration_object_domain_import_records","canonical_owned_item_stacks","canonical_item_inventory_operations","canonical_item_inventory_ledger_entries","canonical_players")|Sort-Object
  if ($null -eq $value.cleanup -or $null -eq $value.cleanup.databaseCounts) { throw "TRANSCRIPT_DATABASE_CLEANUP_MISSING" };$actualTables=@($value.cleanup.databaseCounts.psobject.Properties.Name|Sort-Object)
  if (($actualTables -join "|") -ne ($expectedTables -join "|") -or @($value.cleanup.databaseCounts.psobject.Properties|Where-Object Value -ne 0).Count -ne 0) { throw "TRANSCRIPT_DATABASE_CLEANUP_FAILURE" }
  if ($value.cleanup.serverProcessRunning -ne $false -or $value.cleanup.listenerPresent -ne $false -or $value.cleanup.temporaryPathPresent -ne $false -or $value.cleanup.environmentRestored -ne $true -or $value.secretScan.occurrences -ne 0) { throw "TRANSCRIPT_HOST_CLEANUP_FAILURE" }
  $expectedNegative=@("commands-empty","cleanup-empty","migration-aggregate","artifact-hash","timestamp","integration","focused-spoof-260","object-spoof-98","repro-command")
  if ($null -eq $value.negativeValidationCases -or (@($value.negativeValidationCases.psobject.Properties.Name|Sort-Object) -join "|") -ne (($expectedNegative|Sort-Object) -join "|") -or @($value.negativeValidationCases.psobject.Properties|Where-Object Value -ne $true).Count -ne 0) { throw "TRANSCRIPT_NEGATIVE_RESULT_DRIFT" }
  $expectedArtifacts=Get-ArtifactHashes;if ($null -eq $value.artifacts -or @($value.artifacts).Count -ne 6 -or @($value.artifacts|Where-Object{$_.sha256 -notmatch $hash}).Count -ne 0 -or (ConvertTo-Json $value.artifacts -Depth 8 -Compress) -ne (ConvertTo-Json $expectedArtifacts -Depth 8 -Compress)) { throw "TRANSCRIPT_ARTIFACT_STALE" }
}
if($ValidateTranscriptOnly){Assert-Transcript(Get-Content -Raw -LiteralPath $transcriptPath|ConvertFrom-Json -DateKind String);Write-Output '{"transcriptValidation":"PASS"}';exit 0}
$process=$null;$migrationCount=0;$cleanupCounts=[ordered]@{};$listenerAfter=$true;$temporaryAfter=$true;$environmentRestored=$false;$migrationState=$null;$integrationMachineResult=$null
try{
 Assert-SafeTemporaryPath;if(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){throw "Port in use"};if(Test-Path -LiteralPath $temporaryRoot){throw "Temporary path exists"};New-Item -ItemType Directory -Path $temporaryRoot|Out-Null
 Invoke-Recorded "mariadb-initialize" "mariadb-install-db --datadir=<temporary> --password=<redacted>" {&(Join-Path $mariaBin "mariadb-install-db.exe") "--datadir=$(Join-Path $temporaryRoot 'data')" "--password=$password" "--port=$port" --allow-remote-root-access --silent}|Out-Null
 $process=Start-Process -FilePath (Join-Path $mariaBin "mariadbd.exe") -ArgumentList @("--no-defaults","--datadir=$(Join-Path $temporaryRoot 'data')","--port=$port","--bind-address=127.0.0.1","--skip-networking=0","--pid-file=$(Join-Path $temporaryRoot 'mariadbd.pid')","--log-error=$(Join-Path $temporaryRoot 'mariadbd.err')") -PassThru -WindowStyle Hidden;$listener=$null
 for($attempt=0;$attempt-lt150;$attempt+=1){if($process.HasExited){throw "MariaDB exited early"};$listener=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;if($listener){break};Start-Sleep -Milliseconds 200};if(-not$listener-or@($listener|Select-Object -ExpandProperty OwningProcess -Unique)-ne$process.Id){throw "Listener ownership invalid"}
 Invoke-Recorded "database-create" "mariadb --execute=<isolated database create>" {&(Join-Path $mariaBin "mariadb.exe") --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" "--execute=CREATE DATABASE $databaseName CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"}|Out-Null
 $migrationState=Get-MigrationState;if($migrationState.fileCount-ne465){throw "Expected 465 migration files, got $($migrationState.fileCount)"}
 $env:HOIBOT_ENVIRONMENT_CODE="dev";$env:DATABASE_ENABLED="true";$env:DATABASE_HOST="127.0.0.1";$env:DATABASE_PORT=[string]$port;$env:DATABASE_USER="root";$env:DATABASE_PASSWORD=$password;$env:DATABASE_NAME=$databaseName;$env:IRIS_SHARED_TOKEN="lease2556-isolated"
 Push-Location $runtimeRoot;try{Invoke-Recorded "migrations-001-477" "npm.cmd run db:migrate" {&npm.cmd run db:migrate}|Out-Null;$migrationCount=[int]((&(Join-Path $mariaBin "mariadb.exe") --batch --skip-column-names --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" $databaseName "--execute=SELECT COUNT(*) FROM schema_migrations")-join"").Trim();if($migrationCount-ne465){throw "Applied migration count drift: $migrationCount"};$env:RUN_ITEM25_CANONICAL_MARIADB_INTEGRATION="true";$integrationOutput=Invoke-Recorded "item25-mariadb-integration" "node --import tsx --test test/item25-canonical-definition-provider-mariadb.integration.test.ts" {&node --import tsx --test test/item25-canonical-definition-provider-mariadb.integration.test.ts};$machineLine=@($integrationOutput|Where-Object{$_-match'ITEM25_MARIA_MACHINE_RESULT='});if($machineLine.Count-ne1){throw "Maria machine result missing"};$integrationMachineResult=($machineLine[0]-replace'^.*ITEM25_MARIA_MACHINE_RESULT=','')|ConvertFrom-Json
  $tables=@("canonical_item_definitions","canonical_item_definition_imports","object_identities","object_identity_crosswalks","data_migration_common_staging_runs","data_migration_common_staging_records","data_migration_catalog_projection_runs","data_migration_catalog_source_decisions","data_migration_catalog_projection_records","data_migration_object_domain_import_runs","data_migration_object_domain_import_decisions","data_migration_object_domain_import_records","canonical_owned_item_stacks","canonical_item_inventory_operations","canonical_item_inventory_ledger_entries","canonical_players");foreach($table in $tables){$count=[int]((&(Join-Path $mariaBin "mariadb.exe") --batch --skip-column-names --protocol=TCP --host=127.0.0.1 "--port=$port" --user=root "--password=$password" $databaseName "--execute=SELECT COUNT(*) FROM $table")-join"").Trim();$cleanupCounts[$table]=$count;if($count-ne0){throw "Cleanup nonzero: $table=$count"}}}finally{Pop-Location}
}finally{foreach($name in $environmentNames){$value=$savedEnvironment[$name];if($null-eq$value){Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath "Env:$name" -Value $value}};$environmentRestored=$true;foreach($name in $environmentNames){if([Environment]::GetEnvironmentVariable($name,"Process")-ne$savedEnvironment[$name]){$environmentRestored=$false}};if($process-and-not$process.HasExited){Stop-Process -Id $process.Id;$process.WaitForExit(10000)|Out-Null};$listenerAfter=[bool](Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue);if(-not$listenerAfter){Assert-SafeTemporaryPath;if(Test-Path -LiteralPath $temporaryRoot){Remove-Item -LiteralPath $temporaryRoot -Recurse -Force}};$temporaryAfter=[bool](Test-Path -LiteralPath $temporaryRoot)}
if($listenerAfter-or$temporaryAfter-or-not$environmentRestored){throw "Host cleanup failed"}
Push-Location $runtimeRoot;try{$focusedOutput=Invoke-Recorded "focused-26" "node --import tsx --test iteminfo/provider/inventory focused files" {&node --import tsx --test test/iteminfo-dev-rehearsal-adapter.test.ts test/item25-canonical-definition-provider.test.ts test/item25-canonical-definition-provider-mariadb.integration.test.ts test/canonical-item-inventory-repository.test.ts};$focusedResult=Parse-FocusedTapSummary $focusedOutput;Invoke-Recorded "typecheck" "npm.cmd run typecheck" {&npm.cmd run typecheck}|Out-Null;Invoke-Recorded "build" "npm.cmd run build" {&npm.cmd run build}|Out-Null;$objectOutput=Invoke-Recorded "object-validator-98" "npm.cmd run object-data:validate" {&npm.cmd run object-data:validate};$objectResult=Parse-ObjectValidatorSummary $objectOutput}finally{Pop-Location}
Invoke-Recorded "json-parse" "node -e <parse item25 contract>" {&node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'));" (Join-Path $worktreeRoot "개발환경_고도화/migration-control/contracts/item25-canonical-definition-binding.v1.json")}|Out-Null;Invoke-Recorded "diff-check" "git diff --check" {&git -C $worktreeRoot diff --check}|Out-Null
$transcript=[ordered]@{format="hoibot-item25-provider-mariadb-transcript-v2";generatedAtUtc=(Get-Date).ToUniversalTime().ToString("o");powershell=[ordered]@{edition=$PSVersionTable.PSEdition;major=$PSVersionTable.PSVersion.Major};reproducibility=[ordered]@{prerequisite="PowerShell Core 7+";workingDirectory="repository root";commands=@("pwsh -NoProfile -File `"./개발환경_고도화/migration-control/evidence/item25-canonical-definition-provider-lease2556/rehearse-item25-provider.ps1`"","pwsh -NoProfile -File `"./개발환경_고도화/migration-control/evidence/item25-canonical-definition-provider-lease2556/rehearse-item25-provider.ps1`" -ValidateTranscriptOnly")};migrations=[ordered]@{range="001..477";fileCount=$migrationCount;filenameAggregateSha256=$migrationState.filenameAggregateSha256;contentAggregateSha256=$migrationState.contentAggregateSha256};source=[ordered]@{path="data/itemInfo.json";aggregateSha256=Get-Sha(Join-Path $worktreeRoot "data/itemInfo.json")};commands=@($commands);results=[ordered]@{focused26=$focusedResult;typecheck="PASS";build="PASS";objectValidator=$objectResult;json="PASS";diff="PASS"};integration=[ordered]@{passed=$true;poolCount=[int]$integrationMachineResult.poolCount;singleWinner=[bool]$integrationMachineResult.singleWinner;applyInsertedBindings=[int]$integrationMachineResult.applyInsertedBindings;replayDml=[int]$integrationMachineResult.replayDml};cleanup=[ordered]@{databaseCounts=$cleanupCounts;serverProcessRunning=[bool]($process -and -not $process.HasExited);listenerPresent=$listenerAfter;temporaryPathPresent=$temporaryAfter;environmentRestored=$environmentRestored};secretScan=[ordered]@{occurrences=0;rule="ephemeral credential exact-value scan; raw output not persisted"};negativeValidationCases=[ordered]@{"commands-empty"=$true;"cleanup-empty"=$true;"migration-aggregate"=$true;"artifact-hash"=$true;timestamp=$true;integration=$true;"focused-spoof-260"=$true;"object-spoof-98"=$true;"repro-command"=$true};artifacts=Get-ArtifactHashes}
function Test-Rejected($probe){try{Assert-Transcript $probe;$false}catch{$true}}
$probes=[ordered]@{}
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.commands=@();$probes["commands-empty"]=Test-Rejected $probe
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.cleanup.databaseCounts=[pscustomobject]@{};$probes["cleanup-empty"]=Test-Rejected $probe
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.migrations.contentAggregateSha256="0"*64;$probes["migration-aggregate"]=Test-Rejected $probe
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.artifacts[0].sha256="0"*64;$probes["artifact-hash"]=Test-Rejected $probe
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.generatedAtUtc="stale";$probes.timestamp=Test-Rejected $probe
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.integration.poolCount=1;$probes.integration=Test-Rejected $probe
$info=[string][char]0x2139;try{Parse-FocusedTapSummary @("$info tests 260","$info pass 26","$info fail 0")|Out-Null;$probes["focused-spoof-260"]=$false}catch{$probes["focused-spoof-260"]=$true}
try{Parse-ObjectValidatorSummary @("arbitrary log 98")|Out-Null;$probes["object-spoof-98"]=$false}catch{$probes["object-spoof-98"]=$true}
$probe=$transcript|ConvertTo-Json -Depth 20|ConvertFrom-Json -DateKind String;$probe.reproducibility.commands[0]="pwsh -File tampered.ps1";$probes["repro-command"]=Test-Rejected $probe
if(@($probes.Values|Where-Object{$_-ne$true}).Count-ne0){throw "Transcript negative validation failed"};$transcript.negativeValidationCases=$probes
$json=$transcript|ConvertTo-Json -Depth 20;$occurrences=([regex]::Matches($json,[regex]::Escape($password))).Count;if($occurrences-ne0){throw "Secret scan failed"};$transcript.secretScan.occurrences=$occurrences;$json=$transcript|ConvertTo-Json -Depth 20;[IO.File]::WriteAllText($transcriptPath,$json,(New-Object Text.UTF8Encoding($false)));Assert-Transcript(Get-Content -Raw -LiteralPath $transcriptPath|ConvertFrom-Json -DateKind String);Write-Output([ordered]@{transcript=$transcriptPath;migrationFiles=$migrationCount;focused=$transcript.results.focused26;objectValidator=$transcript.results.objectValidator;integration=$transcript.integration;cleanup="PASS";negativeCases=9}|ConvertTo-Json -Depth 5 -Compress)
