import { createHash,randomUUID } from "node:crypto";
import type { DatabaseClient,DatabaseTransaction } from "../database.js";
import { ApplicationError } from "../shared/application-error.js";

const ALIAS="/입찰 [아이템번호] [포인트]",MAX_UINT64=18_446_744_073_709_551_615n,MAX_WHOLE=999_999_999_999_999_999_999_999_999n;
interface Actor{identity_id:bigint;player_id:bigint;display_name:string;rank_emoji:string|null}
interface Listing{id:bigint;item_name:string;reward_code:string|null;highest_bidder_player_id:bigint|null;highest_bid:string;ends_at:string;version:bigint}
interface Account{player_id:bigint;balance:string;version:bigint}
interface Policy{bid_fee:string;extension_threshold_seconds:bigint;extension_seconds:bigint}
export interface AuctionBidCommand{listingNo:bigint;amount:bigint}
export interface AuctionBidResult{status:"bid"|"usage"|"rejected";data:string;listingId?:string;amount?:string;fee?:string;outboxId:string;replayed?:boolean}

// 입찰 exact 사용법과 양의 정수 경매번호·포인트 전체 형식만 후보로 허용합니다.
export function isAuctionBidCandidate(message:string|undefined):boolean{return message==="/입찰"||(message!==undefined&&/^\/입찰\s+\d+\s+\d+$/.test(message));}
// 입찰 명령의 uint64 경매번호와 DECIMAL(30,3) 정수 포인트를 정밀도 손실 없이 해석합니다.
export function parseAuctionBidCommand(message:string):AuctionBidCommand|null{const match=/^\/입찰\s+(\d+)\s+(\d+)$/.exec(message);if(match===null)return null;const listingNo=BigInt(match[1]!),amount=BigInt(match[2]!);return listingNo===0n||listingNo>MAX_UINT64||amount===0n||amount>MAX_WHOLE?null:{listingNo,amount};}
// partial dispatch가 사용하는 대표 입찰 별칭으로 정규화합니다.
export function normalizeAuctionBidDispatchMessage(message:string):string{return parseAuctionBidCommand(message)!==null?ALIAS:message;}
function eventKey(value:string):string{return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;}
function integer(value:string):bigint{return BigInt(value.split(".")[0]!);}
function decimal(value:bigint):string{return `${value}.000`;}
function commas(value:bigint):string{return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
function parsed(value:string|AuctionBidResult):AuctionBidResult{return typeof value==="string"?JSON.parse(value) as AuctionBidResult:value;}
function retryable(error:unknown):boolean{const code=(error as{code?:string}).code;return code==="ER_LOCK_DEADLOCK"||code==="ER_LOCK_WAIT_TIMEOUT";}

async function complete(t:DatabaseTransaction,input:{operationId:bigint;eventId:string;destinationId:string;actor:Actor;status:AuctionBidResult["status"];listingId:bigint|null;data:string;amount:bigint|null;fee:bigint|null;summary:Record<string,unknown>}):Promise<AuctionBidResult>{
 const outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES(?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.operationId,input.destinationId,JSON.stringify({data:input.data})]);
 await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES(?,'STORE_AUCTION_BID',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,input.operationId,input.status]);
 await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES(?,'external_identity',?,'auction_listing',?,'store.auction.bid',?,'Iris /입찰',?,UTC_TIMESTAMP(3))",[input.operationId,input.actor.identity_id,input.listingId,input.status,JSON.stringify(input.summary)]);
 const result:AuctionBidResult={status:input.status,data:input.data,outboxId:outbox.insertId.toString(),replayed:false,...(input.listingId===null?{}:{listingId:input.listingId.toString()}),...(input.amount===null?{}:{amount:input.amount.toString()}),...(input.fee===null?{}:{fee:input.fee.toString()})};
 await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),input.operationId]);return result;
}

// 경매 입찰의 이전 최고가 환급·신규 금액과 수수료 차감·연장을 하나의 transaction으로 처리합니다.
export class AuctionBidService{
 constructor(private readonly db:DatabaseClient){}
 async handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<AuctionBidResult|null>{if(!isAuctionBidCandidate(input.message))return null;let last:unknown;for(let attempt=0;attempt<3;attempt+=1){try{return await this.db.withTransaction(t=>this.execute(t,input));}catch(error){last=error;if(!retryable(error)||attempt===2)throw error;}}throw last;}
 private async execute(t:DatabaseTransaction,input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<AuctionBidResult|null>{
  const actor=(await t.query<Actor[]>("SELECT identity.id identity_id,identity.player_id,profile.current_display_name display_name,rank.rank_emoji FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' AND player.deleted_at IS NULL JOIN player_profiles profile ON profile.player_id=player.id LEFT JOIN player_legacy_rank_profiles rank ON rank.player_id=player.id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' ORDER BY identity.player_id LIMIT 1 FOR UPDATE",[input.externalUserId]))[0];if(actor===undefined)return null;
  const claim=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES(?,'store.auction.bid',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)",[randomUUID(),eventKey(input.eventId),actor.identity_id]);
  const prior=(await t.query<Array<{result_json:string|AuctionBidResult|null}>>("SELECT result_json FROM operations WHERE id=? FOR UPDATE",[claim.insertId]))[0]!;if(prior.result_json!==null)return{...parsed(prior.result_json),replayed:true};
  const command=parseAuctionBidCommand(input.message);if(command===null)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"usage",listingId:null,data:"사용법: /입찰 [아이템번호] [포인트]",amount:null,fee:null,summary:{mutation:false,reason:"invalid_format"}});
  await t.query("SELECT lock_code FROM admin_global_locks WHERE lock_code IN ('auction_bid','auction_settlement') ORDER BY lock_code FOR UPDATE");
  const policy=(await t.query<Policy[]>("SELECT CAST(bid_fee AS CHAR) bid_fee,extension_threshold_seconds,extension_seconds FROM auction_bid_policy WHERE policy_key='default' FOR UPDATE"))[0];if(policy===undefined)throw new ApplicationError("AUCTION_BID_POLICY_MISSING","경매 입찰 정책이 준비되지 않았습니다.",409);const fee=integer(policy.bid_fee);
  if(command.amount>MAX_WHOLE-fee)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:null,data:"❌ 입찰 포인트 범위를 확인해주세요.",amount:null,fee,summary:{mutation:false,reason:"amount_overflow"}});
  const listing=(await t.query<Listing[]>("SELECT id,item_name,reward_code,highest_bidder_player_id,CAST(highest_bid AS CHAR) highest_bid,ends_at,version FROM auction_listings WHERE legacy_original_index=? AND status='active' AND ends_at>UTC_TIMESTAMP(3) FOR UPDATE",[command.listingNo]))[0];
  if(listing===undefined)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:null,data:"❌ 입찰 가능한 경매를 찾을 수 없습니다.",amount:null,fee,summary:{mutation:false,reason:"listing_not_found",listingNo:command.listingNo.toString()}});
  const current=integer(listing.highest_bid);if(listing.highest_bidder_player_id===actor.player_id)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:listing.id,data:"❌ 이미 최고 입찰자입니다.",amount:command.amount,fee,summary:{mutation:false,reason:"self_highest"}});
  if(command.amount<=current)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:listing.id,data:"❌ 현재 최고 입찰가보다 높은 포인트를 입력해주세요.",amount:command.amount,fee,summary:{mutation:false,reason:"not_higher",current:current.toString()}});
  const cap=(await t.query<Array<{item_id:bigint|null;bid_inventory_cap:bigint|null}>>("SELECT item_id,bid_inventory_cap FROM auction_reward_catalog WHERE reward_code=? FOR UPDATE",[listing.reward_code]))[0];
  if(cap?.bid_inventory_cap!==null&&cap?.bid_inventory_cap!==undefined&&cap.item_id!==null){const owned=(await t.query<Array<{quantity:bigint}>>("SELECT quantity FROM inventory_stacks WHERE player_id=? AND item_id=? FOR UPDATE",[actor.player_id,cap.item_id]))[0]?.quantity??0n;if(owned>cap.bid_inventory_cap)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:listing.id,data:"❌ 해당 경매 보상의 보유 한도를 초과했습니다.",amount:command.amount,fee,summary:{mutation:false,reason:"inventory_cap",owned:owned.toString(),cap:cap.bid_inventory_cap.toString()}});}
  const playerIds=listing.highest_bidder_player_id===null?[actor.player_id]:[actor.player_id,listing.highest_bidder_player_id];for(const id of playerIds)await t.execute("INSERT IGNORE INTO currency_accounts(player_id,currency_code,balance,version) VALUES(?,'point',0,1)",[id]);
  const accounts=await t.query<Account[]>(`SELECT player_id,CAST(balance AS CHAR) balance,version FROM currency_accounts WHERE player_id IN (${playerIds.map(()=>"?").join(",")}) AND currency_code='point' ORDER BY player_id FOR UPDATE`,playerIds);const bidder=accounts.find(row=>row.player_id===actor.player_id)!;const bidderBefore=integer(bidder.balance),required=command.amount+fee;
  if(bidderBefore<required)return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"rejected",listingId:listing.id,data:`❌ 포인트가 부족합니다. 필요: 🅟${commas(required)}`,amount:command.amount,fee,summary:{mutation:false,reason:"insufficient_point",required:required.toString(),balance:bidderBefore.toString()}});
  const bidderAfter=bidderBefore-required;if((await t.execute("UPDATE currency_accounts SET balance=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE player_id=? AND currency_code='point' AND version=?",[decimal(bidderAfter),actor.player_id,bidder.version])).affectedRows!==1n)throw new ApplicationError("AUCTION_BID_CONFLICT","입찰자 포인트가 먼저 변경되었습니다.",409);
  await t.execute("INSERT INTO currency_ledger(operation_id,sequence_no,player_id,currency_code,delta,balance_after,reason_code) VALUES(?,1,?,'point',?,?,'AUCTION_BID_DEBIT')",[claim.insertId,actor.player_id,decimal(-required),decimal(bidderAfter)]);
  let previousBefore:bigint|null=null,previousAfter:bigint|null=null;if(listing.highest_bidder_player_id!==null){const previous=accounts.find(row=>row.player_id===listing.highest_bidder_player_id)!;previousBefore=integer(previous.balance);previousAfter=previousBefore+current;if((await t.execute("UPDATE currency_accounts SET balance=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE player_id=? AND currency_code='point' AND version=?",[decimal(previousAfter),previous.player_id,previous.version])).affectedRows!==1n)throw new ApplicationError("AUCTION_BID_CONFLICT","이전 입찰자 포인트가 먼저 변경되었습니다.",409);await t.execute("INSERT INTO currency_ledger(operation_id,sequence_no,player_id,currency_code,delta,balance_after,reason_code) VALUES(?,2,?,'point',?,?,'AUCTION_BID_REFUND')",[claim.insertId,previous.player_id,decimal(current),decimal(previousAfter)]);}
  const time=(await t.query<Array<{before_at:string;after_at:string}>>("SELECT ends_at before_at,IF(TIMESTAMPDIFF(SECOND,UTC_TIMESTAMP(3),ends_at)<=?,DATE_ADD(ends_at,INTERVAL ? SECOND),ends_at) after_at FROM auction_listings WHERE id=?",[policy.extension_threshold_seconds,policy.extension_seconds,listing.id]))[0]!;const nextVersion=listing.version+1n;
  if((await t.execute("UPDATE auction_listings SET highest_bidder_player_id=?,highest_bid=?,ends_at=?,version=?,updated_at=UTC_TIMESTAMP(3) WHERE id=? AND status='active' AND version=?",[actor.player_id,decimal(command.amount),time.after_at,nextVersion,listing.id,listing.version])).affectedRows!==1n)throw new ApplicationError("AUCTION_BID_CONFLICT","경매 상태가 먼저 변경되었습니다.",409);
  await t.execute("INSERT INTO auction_bids(operation_id,listing_id,bidder_player_id,previous_bidder_player_id,bid_amount,fee_amount,previous_bid_amount,bidder_balance_before,bidder_balance_after,previous_balance_before,previous_balance_after,listing_version_before,listing_version_after,ends_at_before,ends_at_after) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[claim.insertId,listing.id,actor.player_id,listing.highest_bidder_player_id,decimal(command.amount),decimal(fee),decimal(current),decimal(bidderBefore),decimal(bidderAfter),previousBefore===null?null:decimal(previousBefore),previousAfter===null?null:decimal(previousAfter),listing.version,nextVersion,time.before_at,time.after_at]);
  const data=`✅ 입찰 완료\n${listing.item_name}\n입찰자: ${actor.rank_emoji??""}${actor.display_name}\n입찰가: 🅟${commas(command.amount)}\n수수료: 🅟${commas(fee)}`;return complete(t,{operationId:claim.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,status:"bid",listingId:listing.id,data,amount:command.amount,fee,summary:{mutation:true,listingNo:command.listingNo.toString(),listingVersionBefore:listing.version.toString(),listingVersionAfter:nextVersion.toString(),previousBidderPlayerId:listing.highest_bidder_player_id?.toString()??null,previousBid:current.toString(),bidderPlayerId:actor.player_id.toString(),bid:command.amount.toString(),fee:fee.toString(),bidderBalanceBefore:bidderBefore.toString(),bidderBalanceAfter:bidderAfter.toString(),previousBalanceBefore:previousBefore?.toString()??null,previousBalanceAfter:previousAfter?.toString()??null,endsAtBefore:time.before_at,endsAtAfter:time.after_at}});
 }
}
