import{createHash,randomUUID}from"node:crypto";import type{DatabaseClient,DatabaseTransaction}from"../database.js";
interface Operator{operator_id:bigint}interface Post{id:bigint}export interface CarrotBoardDeleteResult{status:"cleared"|"empty";data:string;clearedCount:number;postIds:string[];outboxId:string}
// 당근게시판 전체 삭제는 안내 문구나 인자가 없는 exact 명령만 허용합니다.
export function isCarrotBoardDeleteCommand(message:string|undefined){return message==="/당근게시판삭제";}
export function formatCarrotBoardDeleteResult(count:number){return count===0?"당근게시판에 삭제할 게시글이 없습니다.":`✅ 당근게시판 게시글 ${count}개를 삭제했습니다.`;}
function key(v:string){return v.length<=191?v:`sha256:${createHash("sha256").update(v).digest("hex")}`;}
async function finish(t:DatabaseTransaction,i:{op:bigint;eventId:string;room:string;operator:Operator;posts:Post[]}):Promise<CarrotBoardDeleteResult>{const postIds=i.posts.map(p=>p.id.toString()),clearedCount=postIds.length,status=clearedCount===0?"empty":"cleared",data=formatCarrotBoardDeleteResult(clearedCount);const out=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.op,i.room,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'MARKET_CARROT_BOARD_DELETE',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.eventId,i.op,status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'admin_operator',?,'carrot_board',NULL,'market.carrot_board.clear',?,'Iris carrot board clear',?,UTC_TIMESTAMP(3))",[i.op,i.operator.operator_id,status,JSON.stringify({clearedCount,postIds,mutation:clearedCount>0,restorable:true})]);const result={status,data,clearedCount,postIds,outboxId:out.insertId.toString()} as CarrotBoardDeleteResult;await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),i.op]);return result;}
// 게시판 활성 행을 잠근 뒤 복구 가능한 soft delete와 감사·응답을 원자 처리합니다.
export class CarrotBoardDeleteService{constructor(private readonly db:DatabaseClient){}async clear(i:{eventId:string;externalUserId:string;destinationId:string}):Promise<CarrotBoardDeleteResult|null>{let last:unknown;for(let a=0;a<3;a++){try{return await this.db.withTransaction(async t=>{const ops=await t.query<Operator[]>(`SELECT mapping.operator_id FROM external_identities identity JOIN admin_operator_external_identities mapping ON mapping.external_identity_id=identity.id JOIN admin_operators operator ON operator.id=mapping.operator_id AND operator.status='active' JOIN admin_operator_roles operator_role ON operator_role.operator_id=operator.id JOIN admin_roles role ON role.id=operator_role.role_id AND role.code='super_admin' AND role.active=TRUE JOIN admin_role_permissions permission ON permission.role_id=role.id AND permission.permission_code='market.carrot_board.clear' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE`,[i.externalUserId]),operator=ops[0];if(operator===undefined)return null;const k=key(i.eventId),prior=await t.query<Array<{result_json:string|CarrotBoardDeleteResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='market.carrot_board.clear' AND idempotency_key=? FOR UPDATE",[k]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'market.carrot_board.clear',?,'admin_operator',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),k,operator.operator_id]),posts=await t.query<Post[]>("SELECT id FROM carrot_board_posts WHERE status='published' AND deleted_at IS NULL ORDER BY source_order,id FOR UPDATE");if(posts.length>0)await t.execute("UPDATE carrot_board_posts SET status='deleted',deleted_at=UTC_TIMESTAMP(3) WHERE status='published' AND deleted_at IS NULL");return finish(t,{op:op.insertId,eventId:i.eventId,room:i.destinationId,operator,posts});});}catch(e){last=e;const c=(e as{code?:string}).code;if(c!=="ER_LOCK_DEADLOCK"&&c!=="ER_LOCK_WAIT_TIMEOUT")throw e;}}throw last;}}
