import {createHash,randomUUID} from "node:crypto";
import type {DatabaseClient,DatabaseTransaction} from "../database.js";
interface Actor{identity_id:bigint;player_id:bigint} interface RankRow{player_id:bigint;display_name:string;temperature:bigint}
export interface CarrotTemperatureRankResult{status:"shown"|"empty";data:string;count:number;playerIds:string[];outboxId:string}
// 당근온도순위는 exact 명령만 실행합니다.
export function isCarrotTemperatureRankReadCommand(message:string|undefined):boolean{return message==="/당근온도순위";}
function eventKey(v:string){return v.length<=191?v:`sha256:${createHash("sha256").update(v).digest("hex")}`;} function comma(v:bigint){return v.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
// TOP 10과 1위 온도계 표시를 고정 형식으로 투영합니다.
export function formatCarrotTemperatureRank(rows:RankRow[]):string{const header="🥕 당근온도 순위\n━━━━━━━━━━━━";if(rows.length===0)return `${header}\n당근온도가 기록된 회원이 없습니다.`;return `${header}\n${rows.map((r,i)=>`${i+1}. ${i===0?"🌡️ ":""}${r.display_name} : ${comma(r.temperature)}℃`).join("\n")}`;}
async function finish(t:DatabaseTransaction,i:{operationId:bigint;eventId:string;destinationId:string;actor:Actor;rows:RankRow[]}):Promise<CarrotTemperatureRankResult>{const data=formatCarrotTemperatureRank(i.rows),playerIds=i.rows.map(r=>r.player_id.toString()),status=i.rows.length===0?"empty":"shown";const outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.operationId,i.destinationId,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'MARKET_CARROT_TEMPERATURE_RANK_READ',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.eventId,i.operationId,status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'leaderboard',NULL,'market.carrot_temperature.rank.read',?,'Iris carrot temperature rank read',?,UTC_TIMESTAMP(3))",[i.operationId,i.actor.identity_id,status,JSON.stringify({count:i.rows.length,playerIds,mutation:false})]);const result={status,data,count:i.rows.length,playerIds,outboxId:outbox.insertId.toString()} as CarrotTemperatureRankResult;await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),i.operationId]);return result;}
// 순위 조회를 operation replay 가능한 단일 snapshot으로 실행합니다.
export class CarrotTemperatureRankReadService{constructor(private readonly db:DatabaseClient){}async read(input:{eventId:string;externalUserId:string;destinationId:string}):Promise<CarrotTemperatureRankResult|null>{let last:unknown;for(let a=0;a<3;a+=1){try{return await this.db.withTransaction(async t=>{const actors=await t.query<Actor[]>("SELECT identity.id identity_id,identity.player_id FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE",[input.externalUserId]),actor=actors[0];if(actor===undefined)return null;const k=eventKey(input.eventId),prior=await t.query<Array<{result_json:string|CarrotTemperatureRankResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='market.carrot_temperature.rank.read' AND idempotency_key=? FOR UPDATE",[k]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'market.carrot_temperature.rank.read',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),k,actor.identity_id]);const rows=await t.query<RankRow[]>(`SELECT player.id player_id,profile.current_display_name display_name,counter.value temperature FROM player_counters counter JOIN players player ON player.id=counter.player_id AND player.status='active' JOIN player_profiles profile ON profile.player_id=player.id LEFT JOIN player_legacy_rank_profiles legacy ON legacy.player_id=player.id WHERE counter.counter_code='carrot_temperature' AND counter.period_key='lifetime' AND counter.value>0 ORDER BY counter.value DESC,COALESCE(legacy.source_order,18446744073709551615) ASC,player.id ASC LIMIT 10`);return finish(t,{operationId:op.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,rows});});}catch(e){last=e;const c=(e as {code?:string}).code;if(c!=="ER_LOCK_DEADLOCK"&&c!=="ER_LOCK_WAIT_TIMEOUT")throw e;}}throw last;}}
