import{createHash,randomUUID}from"node:crypto";import type{DatabaseClient,DatabaseTransaction}from"../database.js";
const ALLSEE="\u200b".repeat(500);interface Actor{identity_id:bigint;player_id:bigint}export interface CarrotRankRow{playerId:string;displayName:string;rankEmoji:string;carrotGiven:string}export interface CarrotRankReadResult{status:"shown"|"empty";data:string;rowCount:number;topPlayerId:string|null;topCarrotGiven:string|null;outboxId:string}
// 레거시와 동일하게 인자가 없는 정확한 당근순위 명령만 실행합니다.
export function isCarrotRankReadCommand(message:string|undefined):boolean{return message==="/당근순위";}
function rankLabel(rank:number):string{return rank===1?"🥇":rank===2?"🥈":rank===3?"🥉":`${rank}위`;}function commas(v:bigint){return v.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}function eventKey(v:string){return v.length<=191?v:`sha256:${createHash("sha256").update(v).digest("hex")}`;}
// DB 순서를 BIGINT-safe 당근 순위와 11위 allsee 경계로 투영합니다.
export function formatCarrotRanking(rows:readonly CarrotRankRow[]):string{const header="🥕 당근 거래 순위 🥕\n━━━━━━━━━━━━";if(rows.length===0)return `${header}\n나눔 당근 기록이 있는 회원이 없습니다.`;return `${header}\n${rows.map((r,i)=>`${i===10?ALLSEE:""}${rankLabel(i+1)}. ${r.rankEmoji}${r.displayName} - 나눔 당근: ${commas(BigInt(r.carrotGiven))}개`).join("\n")}`;}
async function finish(t:DatabaseTransaction,i:{operationId:bigint;eventId:string;destinationId:string;actor:Actor;rows:CarrotRankRow[]}):Promise<CarrotRankReadResult>{const data=formatCarrotRanking(i.rows),top=i.rows[0],status=i.rows.length===0?"empty":"shown",outbox=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.operationId,i.destinationId,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'MARKET_CARROT_RANK_READ',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.eventId,i.operationId,status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'leaderboard',NULL,'market.carrot_rank.read',?,'Iris carrot rank read',?,UTC_TIMESTAMP(3))",[i.operationId,i.actor.identity_id,status,JSON.stringify({rowCount:i.rows.length,stableIds:i.rows.map(r=>r.playerId),topPlayerId:top?.playerId??null,topCarrotGiven:top?.carrotGiven??null,legacyTopCacheWrite:false,counterMutation:false})]);const result={status,data,rowCount:i.rows.length,topPlayerId:top?.playerId??null,topCarrotGiven:top?.carrotGiven??null,outboxId:outbox.insertId.toString()}as CarrotRankReadResult;await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),i.operationId]);return result;}
// 당근 나눔 카운터를 안정 순서로 조회하고 operation replay 가능한 snapshot 응답을 기록합니다.
export class CarrotRankReadService{constructor(private readonly db:DatabaseClient){}async read(input:{eventId:string;externalUserId:string;destinationId:string}):Promise<CarrotRankReadResult|null>{let last:unknown;for(let attempt=0;attempt<3;attempt+=1){try{return await this.db.withTransaction(async t=>{const actors=await t.query<Actor[]>("SELECT identity.id identity_id,identity.player_id FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE",[input.externalUserId]),actor=actors[0];if(actor===undefined)return null;const key=eventKey(input.eventId),prior=await t.query<Array<{result_json:string|CarrotRankReadResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='market.carrot_rank.read' AND idempotency_key=? FOR UPDATE",[key]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'market.carrot_rank.read',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),key,actor.identity_id]);const rows=await t.query<Array<{player_id:bigint;display_name:string;rank_emoji:string|null;carrot_given:bigint}>>(`SELECT player.id player_id,profile.current_display_name display_name,legacy.rank_emoji,counter.value carrot_given FROM player_counters counter JOIN players player ON player.id=counter.player_id AND player.status='active' AND player.deleted_at IS NULL JOIN player_profiles profile ON profile.player_id=player.id LEFT JOIN player_legacy_rank_profiles legacy ON legacy.player_id=player.id WHERE counter.counter_code='carrot_given' AND counter.period_key='lifetime' AND counter.value>0 ORDER BY counter.value DESC,(legacy.source_order IS NULL),legacy.source_order,player.id`),mapped=rows.map(r=>({playerId:r.player_id.toString(),displayName:r.display_name,rankEmoji:r.rank_emoji??"",carrotGiven:r.carrot_given.toString()}));return finish(t,{operationId:op.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,rows:mapped});});}catch(error){last=error;const code=(error as{code?:string}).code;if(code!=="ER_LOCK_DEADLOCK"&&code!=="ER_LOCK_WAIT_TIMEOUT")throw error;}}throw last;}}
