import{createHash,randomUUID}from"node:crypto";import type{DatabaseClient,DatabaseTransaction}from"../database.js";
interface Actor{identity_id:bigint;player_id:bigint;display_name:string}interface Post{id:bigint}export interface CarrotBoardCompleteResult{status:"completed"|"not_found";data:string;completedCount:number;postIds:string[];outboxId:string}
// 당근 게시글 완료 처리는 인자 없는 exact 명령만 허용합니다.
export function isCarrotBoardCompleteCommand(message:string|undefined){return message==="/당근완료";}
export function formatCarrotBoardCompleteResult(count:number){return count===0?"완료 처리할 당근 게시글이 없습니다.":`✅ 당근 게시글 ${count}개를 완료 처리했습니다.`;}
function key(v:string){return v.length<=191?v:`sha256:${createHash("sha256").update(v).digest("hex")}`;}
async function finish(t:DatabaseTransaction,i:{op:bigint;eventId:string;room:string;actor:Actor;posts:Post[]}):Promise<CarrotBoardCompleteResult>{const postIds=i.posts.map(p=>p.id.toString()),completedCount=postIds.length,status=completedCount===0?"not_found":"completed",data=formatCarrotBoardCompleteResult(completedCount);const out=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.op,i.room,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'MARKET_CARROT_BOARD_COMPLETE',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[i.eventId,i.op,status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'carrot_board',NULL,'market.carrot_board.complete',?,'Iris own carrot posts complete',?,UTC_TIMESTAMP(3))",[i.op,i.actor.identity_id,status,JSON.stringify({completedCount,postIds,mutation:completedCount>0,restorable:true})]);const result={status,data,completedCount,postIds,outboxId:out.insertId.toString()} as CarrotBoardCompleteResult;await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),i.op]);return result;}
// 안정 player ID와 이관용 표시명 fallback으로 본인 게시글만 원자 완료 처리합니다.
export class CarrotBoardCompleteService{constructor(private readonly db:DatabaseClient){}async complete(i:{eventId:string;externalUserId:string;destinationId:string}):Promise<CarrotBoardCompleteResult|null>{let last:unknown;for(let a=0;a<3;a++){try{return await this.db.withTransaction(async t=>{const actors=await t.query<Actor[]>(`SELECT identity.id identity_id,identity.player_id,profile.current_display_name display_name FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' JOIN player_profiles profile ON profile.player_id=player.id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE`,[i.externalUserId]),actor=actors[0];if(actor===undefined)return null;const k=key(i.eventId),prior=await t.query<Array<{result_json:string|CarrotBoardCompleteResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='market.carrot_board.complete' AND idempotency_key=? FOR UPDATE",[k]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'market.carrot_board.complete',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),k,actor.identity_id]),posts=await t.query<Post[]>("SELECT id FROM carrot_board_posts WHERE status='published' AND deleted_at IS NULL AND (author_player_id=? OR (author_player_id IS NULL AND author_name_snapshot=?)) ORDER BY source_order,id FOR UPDATE",[actor.player_id,actor.display_name]);if(posts.length>0)await t.execute("UPDATE carrot_board_posts SET status='completed',deleted_at=UTC_TIMESTAMP(3) WHERE status='published' AND deleted_at IS NULL AND (author_player_id=? OR (author_player_id IS NULL AND author_name_snapshot=?))",[actor.player_id,actor.display_name]);return finish(t,{op:op.insertId,eventId:i.eventId,room:i.destinationId,actor,posts});});}catch(e){last=e;const c=(e as{code?:string}).code;if(c!=="ER_LOCK_DEADLOCK"&&c!=="ER_LOCK_WAIT_TIMEOUT")throw e;}}throw last;}}
