import {createHash,randomUUID} from "node:crypto";
import type {DatabaseClient} from "../database.js";
const ALLSEE="\u200b".repeat(500);
export interface HomeFurnitureStatsRow{grade:string;count:bigint;firstStableId:string}
export interface HomeFurnitureStatsReadResult{data:string;outboxId:string;gradeCount:number;totalCount:string}
// 레거시와 동일하게 인자가 없는 정확한 가구 통계 명령만 허용합니다.
export function isHomeFurnitureStatsReadCommand(message:string|undefined):boolean{return message==="/가구통계";}
function commas(value:bigint):string{return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
// 등급별 개수와 전체 비율을 레거시 통계 메시지로 투영합니다.
export function formatHomeFurnitureStats(rows:readonly HomeFurnitureStatsRow[]):string{const total=rows.reduce((sum,row)=>sum+row.count,0n);if(total===0n)return"📭 등록된 가구가 없습니다.";let output=`📊 전체 가구 등급별 통계 📊\n\n총합: ${commas(total)}개\n\n${ALLSEE}`;for(const row of rows){const scaled=(row.count*1000n+total/2n)/total;const percent=`${scaled/10n}.${scaled%10n}`;output+=`- ${row.grade} [${percent}%]: ${commas(row.count)}개\n`;}return output;}
// 가방 가구를 읽기 전용으로 집계하고 실행·감사·outbox 증적을 남깁니다.
export class HomeFurnitureStatsReadService{constructor(private readonly database:DatabaseClient){}async read(input:{eventId:string;externalUserId:string;destinationId:string}):Promise<HomeFurnitureStatsReadResult>{return this.database.withTransaction(async transaction=>{const key=input.eventId.length<=191?input.eventId:`sha256:${createHash("sha256").update(input.eventId).digest("hex")}`;const prior=(await transaction.query<Array<{result_json:string|HomeFurnitureStatsReadResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='home.furniture_stats_read' AND idempotency_key=? FOR UPDATE",[key]))[0];if(prior?.result_json!=null)return typeof prior.result_json==="string"?JSON.parse(prior.result_json):prior.result_json;const rows=await transaction.query<Array<{grade_name:string;count_value:bigint;first_id:bigint}>>("SELECT COALESCE(NULLIF(grade_display_name,''),'기타') grade_name,COUNT(*) count_value,MIN(id) first_id FROM furniture_inventory_instances WHERE status='bag' GROUP BY COALESCE(NULLIF(grade_display_name,''),'기타') ORDER BY count_value DESC,first_id");const mapped=rows.map(row=>({grade:row.grade_name,count:BigInt(row.count_value),firstStableId:row.first_id.toString()}));const total=mapped.reduce((sum,row)=>sum+row.count,0n);const operationId=(await transaction.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'home.furniture_stats_read',?,'external_identity',NULL,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),key])).insertId;const data=formatHomeFurnitureStats(mapped);const outbox=(await transaction.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[operationId,input.destinationId,JSON.stringify({data})])).insertId;await transaction.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'HOME_FURNITURE_STATS_READ',?,'completed','reply_queued',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,operationId]);await transaction.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',NULL,'furniture_inventory',NULL,'home.furniture_stats_read','success','Iris /가구통계',?,UTC_TIMESTAMP(3))",[operationId,JSON.stringify({externalUserId:input.externalUserId,gradeCount:mapped.length,totalCount:total.toString(),firstStableIds:mapped.map(row=>row.firstStableId),readOnly:true})]);const result={data,outboxId:outbox.toString(),gradeCount:mapped.length,totalCount:total.toString()};await transaction.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),operationId]);return result;});}}
