const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const main = fs.readFileSync(path.join(__dirname, "..", "main.js"), "utf8");
const configStart = main.indexOf("    maintenance: {");
const configEnd = main.indexOf("    miniPetCollection: {", configStart);
const responseStart = main.indexOf("function response(room, msg, sender, isGroupChat, replier, imageDB, packageName) {");
const lockStart = main.indexOf("    var responseDataLock = ", responseStart);
assert(configStart >= 0 && configEnd > configStart && responseStart >= 0 && lockStart > responseStart);
const guard = main.slice(main.indexOf("{", responseStart) + 1, lockStart);
assert(guard.includes("room !== testRoom"));
assert(guard.includes('msg === "/메인방제한 ON"'));
assert(guard.includes("isMasterIdentity(sender)"));
const context = { testRoom: "팻 테스트방" };
vm.createContext(context);
vm.runInContext("this.maintenance = ({" + main.slice(configStart, configEnd) + "}).maintenance;", context);
assert.strictEqual(context.maintenance.testRoomOnly, false);
context.GLOBAL_CONFIG = { maintenance: context.maintenance };
context.isMasterIdentity = sender => sender === "운영자";
const replies = [];
const replier = { reply: message => replies.push(message) };
vm.runInContext("function acceptsMainRoom(room, msg, sender, replier) {" + guard + "return true; }", context);
assert.strictEqual(context.acceptsMainRoom("팻 테스트방", "/일반명령", "일반인", replier), true);
assert.strictEqual(context.acceptsMainRoom("일반방", "/일반명령", "일반인", replier), true);
context.acceptsMainRoom("일반방", "/메인방제한 ON", "운영자", replier);
context.acceptsMainRoom("팻 테스트방", "/메인방제한 ON", "일반인", replier);
context.acceptsMainRoom("팻 테스트방", "/메인방제한 ON 해봐", "운영자", replier);
assert.strictEqual(context.maintenance.testRoomOnly, false, "다른 방·일반인·추가 문구는 설정을 변경하지 않음");
assert.strictEqual(replies.length, 0);
context.acceptsMainRoom("팻 테스트방", "/메인방제한 ON", "운영자", replier);
assert.strictEqual(context.maintenance.testRoomOnly, true);
assert(replies.pop().includes("팻 테스트방만 응답"));
assert.strictEqual(context.acceptsMainRoom("일반방", "/일반명령", "일반인", replier), undefined);
assert.strictEqual(context.acceptsMainRoom("팻 테스트방", "/일반명령", "일반인", replier), true);
context.acceptsMainRoom("팻 테스트방", "/메인방제한", "운영자", replier);
assert(replies.pop().includes("ON"));
context.acceptsMainRoom("팻 테스트방", "/메인방제한 OFF", "운영자", replier);
assert.strictEqual(context.maintenance.testRoomOnly, false);
assert(replies.pop().includes("일반 채팅방도 응답"));
assert.strictEqual(context.acceptsMainRoom("일반방", "/일반명령", "일반인", replier), true);
assert(lockStart < main.indexOf("dataTransactionLock.tryLock()", responseStart), "차단 후 잠금·데이터 작업 시작");

console.log("MAIN 방 제한 메모리 명령 테스트 통과");
