import { createHash,randomUUID } from "node:crypto";
import type { DatabaseClient } from "../database.js";
import { ApplicationError } from "../shared/application-error.js";
export const PET_SKILL_BOOK_FRAGMENT_CODE="pet_skill_book_fragment",PET_SKILL_BOOK_CODE="pet_skill_book",FRAGMENTS_PER_BOOK=10n;
export function isPetSkillBookCombineCandidate(message:string|undefined):boolean{return message==="/펫스킬북조합"||message?.startsWith("/펫스킬북조합 ")===true;}
export function parsePetSkillBookCombine(message:string):bigint|null{const m=/^\/펫스킬북조합(?:\s+([1-9]\d*))?$/.exec(message);if(!m)return null;const n=BigInt(m[1]??"1");return n<=1844674407370955161n?n:null;}
export function normalizePetSkillBookCombineDispatchMessage(message:string):string{const n=parsePetSkillBookCombine(message);return n===null?message:n===1n&&message==="/펫스킬북조합"?"/펫스킬북조합":"/펫스킬북조합 [숫자]";}
const commas=(n:bigint)=>n.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");
export interface PetSkillBookCombineResult{reply:string;outboxId:string;combineCount:string;fragmentQuantity:string;bookQuantity:string;}
// 조각 차감과 펫스킬북 지급·원장·감사·답장을 한 트랜잭션으로 저장합니다.
export class PetSkillBookCombineService{constructor(private readonly database:DatabaseClient){}
async handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<PetSkillBookCombineResult>{
 const count=parsePetSkillBookCombine(input.message);if(count===null)throw new ApplicationError("INVALID_PET_SKILL_BOOK_COMBINE","사용법: /펫스킬북조합 또는 /펫스킬북조합 숫자\n예) /펫스킬북조합 3",422);
 return this.database.withTransaction(async tx=>{
  const owner=(await tx.query<Array<{identity_id:bigint;player_id:bigint;current_display_name:string;rank_emoji:string|null}>>(`SELECT identity.id identity_id,identity.player_id,profile.current_display_name,rank_profile.rank_emoji FROM external_identities identity JOIN player_profiles profile ON profile.player_id=identity.player_id LEFT JOIN player_legacy_rank_profiles rank_profile ON rank_profile.player_id=identity.player_id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' FOR UPDATE`,[input.externalUserId]))[0];if(!owner)throw new ApplicationError("PLAYER_IDENTITY_REQUIRED","가입된 회원 정보를 찾을 수 없습니다.",409);
  const key=input.eventId.length<=191?input.eventId:`sha256:${createHash("sha256").update(input.eventId).digest("hex")}`,scope=`pet.skill_book_combine:${owner.identity_id}`;
  const prior=await tx.query<Array<{result_json:string|PetSkillBookCombineResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,key]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json) as PetSkillBookCombineResult:prior[0].result_json;
  const rows=await tx.query<Array<{item_id:bigint;code:string;quantity:bigint|null;version:bigint|null}>>(`SELECT item.id item_id,item.code,stack.quantity,stack.version FROM item_definitions item LEFT JOIN inventory_stacks stack ON stack.item_id=item.id AND stack.player_id=? WHERE item.code IN (?,?) AND item.active=TRUE AND item.stackable=TRUE ORDER BY item.code FOR UPDATE`,[owner.player_id,PET_SKILL_BOOK_FRAGMENT_CODE,PET_SKILL_BOOK_CODE]);
  const fragment=rows.find(r=>r.code===PET_SKILL_BOOK_FRAGMENT_CODE),book=rows.find(r=>r.code===PET_SKILL_BOOK_CODE),need=FRAGMENTS_PER_BOOK*count,have=BigInt(fragment?.quantity??0);
  if(!fragment||fragment.version===null||have<need)throw new ApplicationError("PET_SKILL_BOOK_FRAGMENT_REQUIRED",`❌[${owner.rank_emoji??""}${owner.current_display_name}]님 펫스킬북 조각📙이 부족합니다.\n필요: ${commas(need)}개 / 보유: ${commas(have)}개`,409);
  if(!book)throw new ApplicationError("PET_SKILL_BOOK_ITEM_REQUIRED","펫스킬북 설정을 찾을 수 없습니다.",409);
  const op=await tx.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,?,?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),scope,key,owner.identity_id]),fragmentAfter=have-need,bookAfter=BigInt(book.quantity??0)+count;
  const changed=await tx.execute("UPDATE inventory_stacks SET quantity=?,version=version+1 WHERE player_id=? AND item_id=? AND version=?",[fragmentAfter,owner.player_id,fragment.item_id,fragment.version]);if(changed.affectedRows!==1n)throw new ApplicationError("PET_SKILL_BOOK_COMBINE_CONFLICT","인벤토리가 먼저 변경되었습니다.",409);
  if(book.version===null)await tx.execute("INSERT INTO inventory_stacks(player_id,item_id,quantity,version) VALUES (?,?,?,1)",[owner.player_id,book.item_id,count]);else{const grant=await tx.execute("UPDATE inventory_stacks SET quantity=?,version=version+1 WHERE player_id=? AND item_id=? AND version=?",[bookAfter,owner.player_id,book.item_id,book.version]);if(grant.affectedRows!==1n)throw new ApplicationError("PET_SKILL_BOOK_COMBINE_CONFLICT","인벤토리가 먼저 변경되었습니다.",409);}
  await tx.execute("INSERT INTO inventory_ledger(operation_id,sequence_no,player_id,item_id,quantity_delta,reason_code) VALUES (?,1,?,?,?,'pet_skill_book_fragment_consume'),(?,2,?,?,?,'pet_skill_book_crafted')",[op.insertId,owner.player_id,fragment.item_id,-need,op.insertId,owner.player_id,book.item_id,count]);
  const reply=`✅ 펫스킬북 조합 완료\n[${owner.rank_emoji??""}${owner.current_display_name}]\n소비: 펫스킬북 조각📙 ${commas(need)}개\n획득: 펫스킬북📙(/펫스킬오픈) ${commas(count)}개`,outbox=await tx.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[op.insertId,input.destinationId,JSON.stringify({data:reply})]);
  await tx.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'PET_SKILL_BOOK_COMBINE',?,'completed','reply_queued',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,op.insertId]);
  await tx.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'player',?,'pet.skill_book_combine','success','Iris /펫스킬북조합',?,UTC_TIMESTAMP(3))",[op.insertId,owner.identity_id,owner.player_id,JSON.stringify({combineCount:count.toString(),fragmentQuantity:fragmentAfter.toString(),bookQuantity:bookAfter.toString()})]);
  const result={reply,outboxId:outbox.insertId.toString(),combineCount:count.toString(),fragmentQuantity:fragmentAfter.toString(),bookQuantity:bookAfter.toString()};await tx.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),op.insertId]);return result;
 });}}
