import { createHash, randomUUID } from "node:crypto";
import type { DatabaseClient, DatabaseTransaction } from "../database.js";

interface Actor { identity_id: bigint; player_id: bigint; display_name: string }
interface Pet { id: bigint }
interface Feed { item_id: bigint; quantity: bigint | number | string; version: bigint }
interface Intimacy { progress: bigint | number | string; level_value: bigint | number | string; charm_bonus: bigint | number | string; version: bigint }
export interface PetFeedIntimacyResult { status: "consumed" | "invalid" | "pet_required" | "feed_required"; data: string; requestedQuantity: string; consumedQuantity: string; feedBefore: string | null; feedAfter: string | null; progressBefore: string | null; progressAfter: string | null; levelBefore: string | null; levelAfter: string | null; charmBefore: string | null; charmAfter: string | null; outboxId: string; replayed?: boolean }

// /냠냠과 공백 뒤 숫자 수량만 명령 후보로 받습니다.
export function isPetFeedIntimacyCandidate(message: string | undefined): boolean { return message === "/냠냠" || /^\/냠냠\s/.test(message ?? ""); }
// DB dispatch용 대표 alias를 반환합니다.
export function normalizePetFeedIntimacyCommand(message: string | undefined): string | undefined { return isPetFeedIntimacyCandidate(message) ? "/냠냠" : undefined; }
// 인자 생략은 1개이며 양의 uint64만 허용합니다.
export function parsePetFeedQuantity(message: string | undefined): bigint | null { if (message === "/냠냠") return 1n; const match=(message ?? "").match(/^\/냠냠\s+(\d+)$/); if(match===null)return null; const value=BigInt(match[1]!); return value>0n&&value<=18446744073709551615n?value:null; }
function key(value:string){return value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;}
function big(value:bigint|number|string){return BigInt(String(value));}

async function finish(transaction:DatabaseTransaction,input:{operationId:bigint;eventId:string;destinationId:string;actor:Actor;petId:bigint;itemId:bigint;status:PetFeedIntimacyResult["status"];requested:bigint;consumed:bigint;feedBefore:bigint|null;feedAfter:bigint|null;progressBefore:bigint|null;progressAfter:bigint|null;levelBefore:bigint|null;levelAfter:bigint|null;charmBefore:bigint|null;charmAfter:bigint|null}):Promise<PetFeedIntimacyResult>{
  const data=input.status==="invalid"?"사용법: /냠냠 또는 /냠냠 [양의 수량]":input.status==="pet_required"?"먹이를 줄 펫이 없습니다.":input.status==="feed_required"?`펫먹이가 ${input.requested.toString()}개 필요합니다.`:`냠냠! 펫먹이 ${input.consumed.toString()}개를 먹었습니다.\n친밀도: ${input.progressAfter!.toString()}/1000\n친밀도 레벨: ${input.levelAfter!.toString()}\n친밀도 매력: ${input.charmAfter!.toString()}💕`;
  await transaction.execute("INSERT INTO pet_feed_operations(operation_id,player_id,pet_id,item_id,status_code,requested_quantity,consumed_quantity,feed_before,feed_after,progress_before,progress_after,level_before,level_after,charm_before,charm_after) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[input.operationId,input.actor.player_id,input.petId,input.itemId,input.status,input.requested,input.consumed,input.feedBefore,input.feedAfter,input.progressBefore,input.progressAfter,input.levelBefore,input.levelAfter,input.charmBefore,input.charmAfter]);
  const out=await transaction.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status,available_at,created_at) VALUES (?,'iris',?,'text',?,'pending',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.operationId,input.destinationId,JSON.stringify({data})]);
  await transaction.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,'PET_FEED_INTIMACY',?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,input.operationId,input.status]);
  const summary={mutation:input.status==="consumed",requestedQuantity:input.requested.toString(),consumedQuantity:input.consumed.toString(),feedBefore:input.feedBefore?.toString()??null,feedAfter:input.feedAfter?.toString()??null,progressBefore:input.progressBefore?.toString()??null,progressAfter:input.progressAfter?.toString()??null,levelBefore:input.levelBefore?.toString()??null,levelAfter:input.levelAfter?.toString()??null,charmBefore:input.charmBefore?.toString()??null,charmAfter:input.charmAfter?.toString()??null};
  await transaction.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json,created_at) VALUES (?,'external_identity',?,'player_pet',?,'pet.feed.intimacy',?,'Iris pet feed',?,UTC_TIMESTAMP(3))",[input.operationId,input.actor.identity_id,input.petId,input.status,JSON.stringify(summary)]);
  const result:PetFeedIntimacyResult={status:input.status,data,requestedQuantity:input.requested.toString(),consumedQuantity:input.consumed.toString(),feedBefore:summary.feedBefore,feedAfter:summary.feedAfter,progressBefore:summary.progressBefore,progressAfter:summary.progressAfter,levelBefore:summary.levelBefore,levelAfter:summary.levelAfter,charmBefore:summary.charmBefore,charmAfter:summary.charmAfter,outboxId:out.insertId.toString()};
  await transaction.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),input.operationId]);return result;
}

// 먹이 차감과 친밀도 승급·매력 증가를 한 transaction으로 처리합니다.
export class PetFeedIntimacyService{constructor(private readonly db:DatabaseClient){}async handle(input:{eventId:string;externalUserId:string;destinationId:string;message:string}):Promise<PetFeedIntimacyResult|null>{let last:unknown;for(let attempt=0;attempt<3;attempt++){try{return await this.db.withTransaction(async transaction=>{
  const actors=await transaction.query<Actor[]>("SELECT identity.id identity_id,identity.player_id,profile.current_display_name display_name FROM external_identities identity JOIN players player ON player.id=identity.player_id AND player.status='active' JOIN player_profiles profile ON profile.player_id=player.id WHERE identity.provider_code='kakao' AND identity.external_user_id=? AND identity.status='linked' LIMIT 1 FOR UPDATE",[input.externalUserId]),actor=actors[0];if(actor===undefined)return null;
  const prior=await transaction.query<Array<{result_json:string|PetFeedIntimacyResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope='pet.feed.intimacy' AND idempotency_key=? FOR UPDATE",[key(input.eventId)]);if(prior[0]?.result_json!=null){const result=typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json) as PetFeedIntimacyResult:prior[0].result_json;return{...result,replayed:true};}
  const pets=await transaction.query<Pet[]>("SELECT id FROM player_pets WHERE player_id=? LIMIT 1 FOR UPDATE",[actor.player_id]);const pet=pets[0];if(pet===undefined)return null;
  const items=await transaction.query<Array<{id:bigint}>>("SELECT id FROM item_definitions WHERE code='pet_food' AND active=TRUE LIMIT 1"),item=items[0];if(item===undefined)throw new Error("PET_FOOD_ITEM_REQUIRED");
  const requested=parsePetFeedQuantity(input.message)??0n,operation=await transaction.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status,created_at) VALUES (?,'pet.feed.intimacy',?,'external_identity',?,'iris','processing',UTC_TIMESTAMP(3))",[randomUUID(),key(input.eventId),actor.identity_id]);
  await transaction.execute("INSERT IGNORE INTO pet_intimacy(pet_id,progress,level_value,charm_bonus,version) VALUES (?,0,0,0,1)",[pet.id]);const intimacy=(await transaction.query<Intimacy[]>("SELECT progress,level_value,charm_bonus,version FROM pet_intimacy WHERE pet_id=? FOR UPDATE",[pet.id]))[0]!;
  const feeds=await transaction.query<Feed[]>("SELECT stack.item_id,stack.quantity,stack.version FROM inventory_stacks stack JOIN item_definitions item ON item.id=stack.item_id WHERE stack.player_id=? AND item.code='pet_food' FOR UPDATE",[actor.player_id]),feed=feeds[0];const progress=big(intimacy.progress),level=big(intimacy.level_value),charm=big(intimacy.charm_bonus),feedBefore=feed===undefined?0n:big(feed.quantity);
  if(requested===0n)return finish(transaction,{operationId:operation.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,petId:pet.id,itemId:item.id,status:"invalid",requested,consumed:0n,feedBefore,feedAfter:feedBefore,progressBefore:progress,progressAfter:progress,levelBefore:level,levelAfter:level,charmBefore:charm,charmAfter:charm});
  if(feed===undefined||feedBefore<requested)return finish(transaction,{operationId:operation.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,petId:pet.id,itemId:item.id,status:"feed_required",requested,consumed:0n,feedBefore,feedAfter:feedBefore,progressBefore:progress,progressAfter:progress,levelBefore:level,levelAfter:level,charmBefore:charm,charmAfter:charm});
  const total=progress+requested,levelUps=total/1000n,progressAfter=total%1000n,levelAfter=level+levelUps,charmAfter=charm+levelUps*1100n,feedAfter=feedBefore-requested;
  const stackUpdate=await transaction.execute("UPDATE inventory_stacks SET quantity=?,version=version+1 WHERE player_id=? AND item_id=? AND version=?",[feedAfter,actor.player_id,item.id,feed.version]);if(stackUpdate.affectedRows!==1n)throw new Error("Pet feed inventory version conflict.");
  const intimacyUpdate=await transaction.execute("UPDATE pet_intimacy SET progress=?,level_value=?,charm_bonus=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE pet_id=? AND version=?",[progressAfter,levelAfter,charmAfter,pet.id,intimacy.version]);if(intimacyUpdate.affectedRows!==1n)throw new Error("Pet intimacy version conflict.");
  await transaction.execute("INSERT INTO inventory_ledger(operation_id,sequence_no,player_id,item_id,quantity_delta,reason_code) VALUES (?,1,?,?,?,'pet_feed_intimacy')",[operation.insertId,actor.player_id,item.id,-requested]);
  return finish(transaction,{operationId:operation.insertId,eventId:input.eventId,destinationId:input.destinationId,actor,petId:pet.id,itemId:item.id,status:"consumed",requested,consumed:requested,feedBefore,feedAfter,progressBefore:progress,progressAfter,levelBefore:level,levelAfter,charmBefore:charm,charmAfter});
});}catch(error){last=error;const code=(error as{code?:string}).code;if(code!=="ER_LOCK_DEADLOCK"&&code!=="ER_LOCK_WAIT_TIMEOUT")throw error;}}throw last;}}
