import{createHash,randomUUID}from"node:crypto";import type{DatabaseClient,DatabaseTransaction}from"../database.js";
export type MatzangSessionResult={status:"started"|"already_active"|"ended"|"stale_cleared"|"inactive";data:string;outboxId:string;participantCount:number;rewardCount:number};
export function matzangRankReward(rank:number):bigint{if(rank>=1&&rank<=10)return BigInt(21-rank);if(rank<=20&&rank>=11)return 4n;if(rank<=30&&rank>=21)return 2n;if(rank<=100&&rank>=31)return 1n;return 0n;}
const eventKey=(value:string)=>value.length<=191?value:`sha256:${createHash("sha256").update(value).digest("hex")}`;
type Field={active:number;resting:number};type Participant={player_id:bigint;display_name:string;pt:bigint};
// 맞짱 필드 시작·종료와 종료 순위 다이아 정산을 공용 transaction으로 처리합니다.
export class MatzangSessionProvider{constructor(private readonly db:DatabaseClient){}
 async start(input:{eventId:string;destinationId:string;operatorId:string;fieldKey?:string}):Promise<MatzangSessionResult>{return this.db.withTransaction(t=>this.run(t,"start",input));}
 async end(input:{eventId:string;destinationId:string;operatorId:string;fieldKey?:string}):Promise<MatzangSessionResult>{return this.db.withTransaction(t=>this.run(t,"end",input));}
 private async run(t:DatabaseTransaction,action:"start"|"end",input:{eventId:string;destinationId:string;operatorId:string;fieldKey?:string}):Promise<MatzangSessionResult>{const scope=`matzang.session.${action}`,key=eventKey(input.eventId),prior=await t.query<Array<{result_json:string|MatzangSessionResult|null}>>("SELECT result_json FROM operations WHERE idempotency_scope=? AND idempotency_key=? FOR UPDATE",[scope,key]);if(prior[0]?.result_json!=null)return typeof prior[0].result_json==="string"?JSON.parse(prior[0].result_json):prior[0].result_json;const op=await t.execute("INSERT INTO operations(operation_key,idempotency_scope,idempotency_key,actor_type,actor_id,source_code,status) VALUES (?,?,?,'admin_operator',?,'iris','processing')",[randomUUID(),scope,key,input.operatorId]),fieldKey=input.fieldKey??"current",field=(await t.query<Field[]>("SELECT active,resting FROM matzang_fields WHERE field_key=? FOR UPDATE",[fieldKey]))[0];if(field===undefined)throw new Error(`matzang field not found: ${fieldKey}`);let status:MatzangSessionResult["status"],data="",participantCount=0,rewardCount=0;
 if(action==="start"){if(field.active){status="already_active";data="이미 맞짱필드👊가 진행 중입니다.";}else{await t.execute("DELETE FROM matzang_participants WHERE field_key=?",[fieldKey]);await t.execute("UPDATE matzang_fields SET active=TRUE,resting=FALSE,started_at=UTC_TIMESTAMP(3),ended_at=NULL,version=version+1 WHERE field_key=?",[fieldKey]);status="started";data="[📢전체알림📢]\n맞짱필드👊\n\n호이월드 유저의 맞짱이 시작되었습니다.\n\n참여방법: /참여 or ㅊㅇ\n대전방법: /맞짱 or ㅁㅁ";}}
 else{const rows=await t.query<Participant[]>("SELECT player_id,display_name,pt FROM matzang_participants WHERE field_key=? ORDER BY pt DESC,display_name ASC,player_id ASC FOR UPDATE",[fieldKey]);participantCount=rows.length;if(!field.active){if(rows.length===0){status="inactive";data="현재 맞짱필드👊가 진행 중이 아닙니다.";}else{await t.execute("DELETE FROM matzang_participants WHERE field_key=?",[fieldKey]);await t.execute("UPDATE matzang_fields SET resting=FALSE,ended_at=UTC_TIMESTAMP(3),version=version+1 WHERE field_key=?",[fieldKey]);status="stale_cleared";data=`✅ 맞짱필드👊 과거 참여자 ${rows.length}명을 초기화했습니다.`;}}else{const ranked=rows.filter(x=>x.pt>0n).slice(0,100),lines:string[]=[];for(let i=0;i<ranked.length;i++){const p=ranked[i]!,rank=i+1,reward=matzangRankReward(rank);await t.execute("INSERT IGNORE INTO currency_accounts(player_id,currency_code,balance,version) VALUES (?,'diamond',0,0)",[p.player_id]);const account=(await t.query<Array<{balance:string}>>("SELECT balance FROM currency_accounts WHERE player_id=? AND currency_code='diamond' FOR UPDATE",[p.player_id]))[0]!,balance=BigInt(account.balance.split('.')[0]!)+reward;await t.execute("UPDATE currency_accounts SET balance=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE player_id=? AND currency_code='diamond'",[balance,p.player_id]);await t.execute("INSERT INTO currency_ledger(operation_id,sequence_no,player_id,currency_code,delta,balance_after,reason_code) VALUES (?,?,?,'diamond',?,?,'MATZZANG_RANK_REWARD')",[op.insertId,i+1,p.player_id,reward,balance]);await t.execute("INSERT INTO matzang_rank_rewards(operation_id,field_key,rank_no,player_id,pt,diamond_reward) VALUES (?,?,?,?,?,?)",[op.insertId,fieldKey,rank,p.player_id,p.pt,reward]);lines.push(`${rank}. [${p.display_name}] ${p.pt}pt - 다이아💎 ${reward}개`);rewardCount++;}await t.execute("DELETE FROM matzang_participants WHERE field_key=?",[fieldKey]);await t.execute("UPDATE matzang_fields SET active=FALSE,resting=FALSE,started_at=started_at,ended_at=UTC_TIMESTAMP(3),version=version+1 WHERE field_key=?",[fieldKey]);status="ended";data=["[📢맞짱필드👊 종료]","1등~100등 차등 다이아💎 보상안내","",...(lines.length?lines:["보상 대상자가 없습니다."]),"",`✅ 참여자 ${rows.length}명의 맞짱필드 기록을 초기화했습니다.`].join("\n");}}
 const out=await t.execute("INSERT INTO outbox_messages(operation_id,provider_code,destination_id,message_type,payload_json,status) VALUES (?,'iris',?,'text',?,'pending')",[op.insertId,input.destinationId,JSON.stringify({data})]);await t.execute("INSERT INTO command_executions(event_id,command_code,operation_id,execution_status,result_code,created_at,completed_at) VALUES (?,?,?,'completed',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",[input.eventId,action==="start"?"MATZZANG_SESSION_START":"MATZZANG_SESSION_END",op.insertId,status]);await t.execute("INSERT INTO command_audit(operation_id,actor_type,actor_id,target_type,target_id,action_code,result_code,reason,change_summary_json) VALUES (?,'admin_operator',?,'matzang_field',NULL,?,?,?,?)",[op.insertId,input.operatorId,`matzang.session.${action}`,status,`Iris /맞짱${action==="start"?"시작":"종료"}`,JSON.stringify({status,participantCount,rewardCount})]);const result={status,data,outboxId:out.insertId.toString(),participantCount,rewardCount};await t.execute("UPDATE operations SET status='completed',result_json=?,completed_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),op.insertId]);return result;}
}
